var _tanimoto_mol_similarity_by_substructure_8java =
[
    [ "denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure", "classdenoptim_1_1fitness_1_1descriptors_1_1_tanimoto_mol_similarity_by_substructure.html", "classdenoptim_1_1fitness_1_1descriptors_1_1_tanimoto_mol_similarity_by_substructure" ]
];