DENOPTIM: denoptim.json.DENOPTIMgson Class Reference
denoptim.json.DENOPTIMgson Class Reference
Class for de/serializing DENOPTIM graphs from/to JSON format.
Classes
class DENOPTIMExclusionStrategy
class DENOPTIMExclusionStrategyNoAPMap
Static Public Member Functions
static Gson getReader ()
static Gson getWriter ()
Package Attributes
Gson reader
Gson writer
Private Member Functions
DENOPTIMgson ()
Static Private Member Functions
static DENOPTIMgson getInstance ()
Static Private Attributes
static DENOPTIMgson instance = null
Detailed Description
Class for de/serializing DENOPTIM graphs from/to JSON format.
Definition at line 53 of file DENOPTIMgson.java.
Constructor & Destructor Documentation
DENOPTIMgson()
denoptim.json.DENOPTIMgson.DENOPTIMgson () private
Definition at line 63 of file DENOPTIMgson.java.
References denoptim.json.DENOPTIMgson.reader, and denoptim.json.DENOPTIMgson.writer.
Referenced by denoptim.json.DENOPTIMgson.getInstance().
Member Function Documentation
getInstance()
static DENOPTIMgson denoptim.json.DENOPTIMgson.getInstance () static private
Definition at line 119 of file DENOPTIMgson.java.
References denoptim.json.DENOPTIMgson.DENOPTIMgson(), and denoptim.json.DENOPTIMgson.instance.
Referenced by denoptim.json.DENOPTIMgson.getReader(), and denoptim.json.DENOPTIMgson.getWriter().
getReader()
static Gson denoptim.json.DENOPTIMgson.getReader () static
Definition at line 128 of file DENOPTIMgson.java.
References denoptim.json.DENOPTIMgson.getInstance(), and denoptim.json.DENOPTIMgson.reader.
Referenced by denoptim.files.FileUtils.detectKindOfJSONFile(), denoptim.graph.DGraph.fromJson(), denoptim.graph.EmptyVertex.fromJson(), denoptim.graph.Fragment.fromJson(), denoptim.graph.Template.fromJson(), denoptim.graph.Vertex.fromJson(), denoptim.io.DenoptimIO.readBridgeHesFindingRules(), denoptim.io.DenoptimIO.readDENOPTIMGraphEditFromFile(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromSDFile(), denoptim.json.DENOPTIMgsonTest.testIAtomContainerToJSONAndBack(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), and denoptim.json.DENOPTIMgsonTest.testTemplateSerialization().
getWriter()
static Gson denoptim.json.DENOPTIMgson.getWriter () static
Definition at line 135 of file DENOPTIMgson.java.
References denoptim.json.DENOPTIMgson.getInstance(), and denoptim.json.DENOPTIMgson.writer.
Referenced by denoptim.json.DENOPTIMgsonTest.testIAtomContainerToJSONAndBack(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.graph.DGraph.toJson(), denoptim.graph.EmptyVertex.toJson(), denoptim.graph.Fragment.toJson(), denoptim.graph.Template.toJson(), denoptim.io.DenoptimIO.writeGraphsToJSON(), and denoptim.io.DenoptimIO.writeVertexesToJSON().
Member Data Documentation
instance
DENOPTIMgson denoptim.json.DENOPTIMgson.instance = null static private
Definition at line 55 of file DENOPTIMgson.java.
Referenced by denoptim.json.DENOPTIMgson.getInstance().
reader
Gson denoptim.json.DENOPTIMgson.reader package
Definition at line 57 of file DENOPTIMgson.java.
Referenced by denoptim.json.DENOPTIMgson.DENOPTIMgson(), and denoptim.json.DENOPTIMgson.getReader().
writer
Gson denoptim.json.DENOPTIMgson.writer package
Definition at line 59 of file DENOPTIMgson.java.
Referenced by denoptim.json.DENOPTIMgson.DENOPTIMgson(), and denoptim.json.DENOPTIMgson.getWriter().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/json/DENOPTIMgson.java