DENOPTIM: denoptim.programs.moldecularmodelbuilder.MMBuilderParameters Class Reference
denoptim.programs.moldecularmodelbuilder.MMBuilderParameters Class Reference
Parameters for the conformer generator (3D builder).
Public Member Functions
MMBuilderParameters ()
Constructor.
int getTaskID ()
String getInputSDFFile ()
String getOutputSDFFile ()
String getPSSROTTool ()
String getXYZINTTool ()
String getINTXYZTool ()
String getParamFile ()
ArrayList< String > getInitPSSROTParams ()
ArrayList< String > getRSInitPSSROTParams ()
ArrayList< String > getRestPSSROTParams ()
ArrayList< String > getRSRestPSSROTParams ()
ArrayList< String > getKeyFileParams ()
boolean getKeepDummyFlag ()
ArrayList< String > getRSKeyFileParams ()
boolean debug ()
int getAtomOrderingScheme ()
HashMap< String, Integer > getTinkerMap ()
String getWorkingDirectory ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void checkParameters () throws DENOPTIMException
Check all parameters.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Protected Attributes
boolean debug = false
Flag controlling debug verbosity.
String toolPSSROT
Pathname to Tinker's pssrot executable.
String toolXYZINT
Pathname to Tinker's xyzint executable.
String toolINTXYZ
Pathname to Tinker's intxyz executable.
boolean keepDummy = false
Flag controlling removal of dummy atoms from output geometry.
String forceFieldFile
Pathname to force field parameters file for Tinker.
String pssrotFile
Pathname to parameters file for PSS part of Tinker's PSSROT.
String rsPssrotFile
Pathname to parameters file for PSS part of Tinker's ring-closing PSSROT.
String keyFile
Pathname to keywords file for Tinker's conformational search.
String rsKeyFile
Pathname to keywords file for Tinker's ring-closing conformational search.
ArrayList< String > pssrotParams_Init
Parameters for PSS part of Tinker's PSSROT step.
ArrayList< String > pssrotParams_Rest
Parameters for linear search part of Tinker's PSSROT step.
ArrayList< String > keyFileParams
Keywords for Tinker's conformational search.
ArrayList< String > rsPssrotParams_Init
Parameters for PSS part of Tinker's ring-closing PSSROT step.
ArrayList< String > rsPssrotParams_Rest
Parameters for linear search part of Tinker's ring-closing PSSROT step.
ArrayList< String > rsKeyFileParams
Keywords for Tinker's ring-closing conformational search.
int atomOrderingScheme = 1
Flag controlling the criterion used to reorder atom lists.
HashMap< String, Integer > TINKER_MAP
Atom type map.
int taskID
Unique task identifier.
String inpSDFFile
Pathname of input SDF file.
String outSDFFile
Pathname of ouput SDF file.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Detailed Description
Parameters for the conformer generator (3D builder).
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 37 of file MMBuilderParameters.java.
Constructor & Destructor Documentation
MMBuilderParameters()
denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.MMBuilderParameters ()
Constructor.
Definition at line 152 of file MMBuilderParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.MMB_PARAM.
Member Function Documentation
checkParameters()
void denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters () throws DENOPTIMException
Check all parameters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 378 of file MMBuilderParameters.java.
References denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.RunTimeParameters.ensureFileExists(), denoptim.programs.RunTimeParameters.ensureNotNull(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.forceFieldFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.inpSDFFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.outSDFFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolINTXYZ, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolPSSROT, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolXYZINT, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
debug()
boolean denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.debug ()
Definition at line 257 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.debug.
getAtomOrderingScheme()
int denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getAtomOrderingScheme ()
Definition at line 264 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.atomOrderingScheme.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree().
getInitPSSROTParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInitPSSROTParams ()
Definition at line 208 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Init.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getInputSDFFile()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInputSDFFile ()
Definition at line 166 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.inpSDFFile.
Referenced by denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
getINTXYZTool()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getINTXYZTool ()
Definition at line 194 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolINTXYZ.
getKeepDummyFlag()
boolean denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeepDummyFlag ()
Definition at line 243 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keepDummy.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getKeyFileParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeyFileParams ()
Definition at line 236 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFileParams.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getOutputSDFFile()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getOutputSDFFile ()
Definition at line 173 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.outSDFFile.
Referenced by denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
getParamFile()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getParamFile ()
Definition at line 201 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.forceFieldFile.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getPrintedList()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 423 of file MMBuilderParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getPSSROTTool()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getPSSROTTool ()
Definition at line 180 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolPSSROT.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getRestPSSROTParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRestPSSROTParams ()
Definition at line 222 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Rest.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getRSInitPSSROTParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSInitPSSROTParams ()
Definition at line 215 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Init.
getRSKeyFileParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSKeyFileParams ()
Definition at line 250 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFileParams.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure().
getRSRestPSSROTParams()
ArrayList< String > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSRestPSSROTParams ()
Definition at line 229 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Rest.
getTaskID()
int denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTaskID ()
Definition at line 159 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.taskID.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getTinkerMap()
HashMap< String, Integer > denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTinkerMap ()
Definition at line 271 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.TINKER_MAP.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), and denoptim.molecularmodeling.RingClosureTool.setTinkerTypes().
getWorkingDirectory()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getWorkingDirectory ()
Definition at line 278 of file MMBuilderParameters.java.
References denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getXYZINTTool()
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getXYZINTTool ()
Definition at line 187 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolXYZINT.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
interpretKeyword()
void denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 292 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.atomOrderingScheme, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.debug, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.forceFieldFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.inpSDFFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keepDummy, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.outSDFFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolINTXYZ, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolPSSROT, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolXYZINT, denoptim.programs.RunTimeParameters.verbosity, and denoptim.programs.RunTimeParameters.workDir.
processParameters()
void denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 450 of file MMBuilderParameters.java.
References denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.forceFieldFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFileParams, denoptim.programs.RunTimeParameters.otherParameters, denoptim.programs.RunTimeParameters.processOtherParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Init, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Rest, denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.molecularmodeling.MMBuilderUtils.readKeyFileParams(), denoptim.integration.tinker.TinkerUtils.readPSSROTParams(), denoptim.integration.tinker.TinkerUtils.readTinkerAtomTypes(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFileParams, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotFile, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Init, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Rest, and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.TINKER_MAP.
Referenced by denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
Member Data Documentation
atomOrderingScheme
int denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.atomOrderingScheme = 1 protected
Flag controlling the criterion used to reorder atom lists.
1: branch-oriented (completes a branch before moving to the next one). 2: layer-oriented) completes a layer before moving to the next one).
Definition at line 124 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getAtomOrderingScheme(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
debug
boolean denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.debug = false protected
Flag controlling debug verbosity.
Definition at line 42 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.debug(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
forceFieldFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.forceFieldFile protected
Pathname to force field parameters file for Tinker.
Definition at line 67 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getParamFile(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
inpSDFFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.inpSDFFile protected
Pathname of input SDF file.
Definition at line 139 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInputSDFFile(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
keepDummy
boolean denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keepDummy = false protected
Flag controlling removal of dummy atoms from output geometry.
Definition at line 62 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeepDummyFlag(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
keyFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFile protected
Pathname to keywords file for Tinker's conformational search.
Definition at line 82 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
keyFileParams
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.keyFileParams protected
Keywords for Tinker's conformational search.
Definition at line 102 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeyFileParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
outSDFFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.outSDFFile protected
Pathname of ouput SDF file.
Definition at line 144 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getOutputSDFFile(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
pssrotFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotFile protected
Pathname to parameters file for PSS part of Tinker's PSSROT.
Definition at line 72 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
pssrotParams_Init
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Init protected
Parameters for PSS part of Tinker's PSSROT step.
Definition at line 92 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInitPSSROTParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
pssrotParams_Rest
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.pssrotParams_Rest protected
Parameters for linear search part of Tinker's PSSROT step.
Definition at line 97 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRestPSSROTParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
rsKeyFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFile protected
Pathname to keywords file for Tinker's ring-closing conformational search.
Definition at line 87 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
rsKeyFileParams
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsKeyFileParams protected
Keywords for Tinker's ring-closing conformational search.
Definition at line 117 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSKeyFileParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
rsPssrotFile
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotFile protected
Pathname to parameters file for PSS part of Tinker's ring-closing PSSROT.
Definition at line 77 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
rsPssrotParams_Init
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Init protected
Parameters for PSS part of Tinker's ring-closing PSSROT step.
Definition at line 107 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSInitPSSROTParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
rsPssrotParams_Rest
ArrayList<String> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.rsPssrotParams_Rest protected
Parameters for linear search part of Tinker's ring-closing PSSROT step.
Definition at line 112 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRSRestPSSROTParams(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
taskID
int denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.taskID protected
Unique task identifier.
Definition at line 134 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTaskID().
TINKER_MAP
HashMap<String, Integer> denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.TINKER_MAP protected
Atom type map.
Definition at line 129 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTinkerMap(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters().
toolINTXYZ
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolINTXYZ protected
Pathname to Tinker's intxyz executable.
Definition at line 57 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getINTXYZTool(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
toolPSSROT
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolPSSROT protected
Pathname to Tinker's pssrot executable.
Definition at line 47 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getPSSROTTool(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
toolXYZINT
String denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.toolXYZINT protected
Pathname to Tinker's xyzint executable.
Definition at line 52 of file MMBuilderParameters.java.
Referenced by denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getXYZINTTool(), and denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.interpretKeyword().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/moldecularmodelbuilder/MMBuilderParameters.java