DENOPTIM: denoptim.graph.rings.RingClosureParameters Class Reference
denoptim.graph.rings.RingClosureParameters Class Reference
Parameters and setting related to handling ring closures.
Public Member Functions
RingClosureParameters ()
Constructor.
int getClosabilityEvalMode ()
int getMaxNumberRotatableBonds ()
int getMaxRingSize ()
List< Integer > getRingSizeBias ()
void setRingSizeBias (List< Integer > biases)
Sets the preference for certain ring sizes or the prohibition to generate certain rings (i.e., weight = 0).
int getMinRcaPerType (String type)
int getMaxRcaPerType (String type)
int getMinRingClosures ()
int getMaxRingClosures ()
Map< String, String > getConstitutionalClosabilityConds ()
void setConstitutionalClosabilityConds (Map< String, String > ringClosabCondAsSMARTS)
Sets the list of constitutions that can be formed by ring closure.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void allowRingClosures (boolean value)
boolean allowRingClosures ()
boolean buildChelatesMode ()
boolean selectFragmentsFromClosableChains ()
double getRCDistTolerance ()
double getConfPathExtraTolerance ()
double getRCDotPrTolerance ()
double getLinearityLimit ()
double getPathConfSearchStep ()
Set< String > getRequiredRingElements ()
List< BridgeHeadFindingRule > getBridgeHeadFindingRules ()
String getRCCLibraryIndexFile ()
String getRCCLibraryFolder ()
RingClosuresArchive getRingClosuresArchive ()
boolean doExhaustiveConfSrch ()
boolean serializeRCCs ()
boolean checkInterdependentChains ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Public Attributes
boolean requireCompleteRingclosure = true
Flag requesting complete ring closure of all pairs of RCAs in at least one combination of RCAs to consider the calculation successful.
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Attributes
boolean closeRings = false
Flag activating the ring closing machinery.
boolean buildChelatesMode = false
Flag activating procedures favoring formation of chelates.
Set< APClass > metalCoordinatingAPClasses
List of metal-coordinating APClasses.
boolean selectFragsFromCC = false
Flag activating the biased selection of closable fragment chains.
int rceMode = -1
The ring closability evaluation mode: -1= only ring rize bias 0 = only constitution of candidate ring, 1 = only closability of 3D chain, 2 = both 0 and 1.
int maxRotBonds = 7
Maximum number of rotatable bonds for which conformational space is explored.
int maxRingSize = 9
Maximum size (number of atoms) in ring closing chain.
Map< String, Integer > minRcaPerType = new HashMap<String,Integer>()
Minimum number of RingClosingAttractors in a valid graph.
Map< String, Integer > maxRcaPerType = new HashMap<String,Integer>()
Maximum number of RingClosingAttractors in a valid graph.
int minRingClosures = 0
Minimum number of RingClosures in a valid graph.
int maxRingClosures = 50
Maximum number of RingClosures in a valid graph.
double linearityLimit = 178.5
Maximum value for non-flat bond angle (in degree).
double rcTolDist = 0.33
Tolerance factor for interatomic distances.
double pathConfSearchExtraTol = 1.1
Extra tolerance factor for interatomic distances.
double rcMaxDot = -0.75
Maximum value of dot product between the normalized attachment point vectors at the head and tail of a candidate chain.
double pathConfSearchStep = 12.0
Torsion angle step for conformational scan of candidate closable chain.
List< Integer > ringSizeBias
Relative weight of ring sizes to bias the selection of a ring combination among the various alternatives.
Map< String, String > ringClosabCondAsSMARTS
SMARTS defining the constitution-based ring closability condition.
Set< String > reqElInRings = new HashSet<String>()
Required elements in closable chains.
String rccIndex = ""
Pathname of the text file containing the list of visited RingClosingConformations (i.e., index file).
String rccFolder = ""
Pathname of the root folder containing the archive of serialized RingClosingConformations.
boolean exhaustiveConfSrch = false
Flag controlling conformational search.
boolean checkInterdepPaths = false
Flag controlling the ring-closing criterion evaluating the simultaneous closability of interdependent chains.
boolean serializeRCCs = false
Flag controlling the serialization of the RingClosingConformations.
List< BridgeHeadFindingRule > bridgeHeadFindingRules
Rules that identify the atoms that can become bridge heads to form fused rings.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Private Attributes
RingClosuresArchive rcArchive
Collection of information about ring-closability of graph substructures.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Detailed Description
Parameters and setting related to handling ring closures.
Author
Marco Foscato
Definition at line 49 of file RingClosureParameters.java.
Constructor & Destructor Documentation
RingClosureParameters()
denoptim.graph.rings.RingClosureParameters.RingClosureParameters ()
Constructor.
Parameters
paramType the type of parameters this instance is meant to collect.
Definition at line 256 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.bridgeHeadFindingRules, denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.graph.rings.RingClosureParameters.rcArchive, and denoptim.io.DenoptimIO.readBridgeHesFindingRules().
Member Function Documentation
allowRingClosures() [1/2]
boolean denoptim.graph.rings.RingClosureParameters.allowRingClosures ()
Definition at line 405 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.closeRings.
allowRingClosures() [2/2]
void denoptim.graph.rings.RingClosureParameters.allowRingClosures (boolean value)
Definition at line 398 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.closeRings.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), denoptim.graph.DGraph.checkConsistency(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.programs.denovo.GAParameters.processParameters(), and denoptim.ga.EAUtils.setupRings().
buildChelatesMode()
boolean denoptim.graph.rings.RingClosureParameters.buildChelatesMode ()
Definition at line 412 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.buildChelatesMode.
checkInterdependentChains()
boolean denoptim.graph.rings.RingClosureParameters.checkInterdependentChains ()
Definition at line 510 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.checkInterdepPaths.
Referenced by denoptim.graph.rings.CyclicGraphHandler.combineCompatPathSubGraphs(), denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability(), and denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings().
checkParameters()
void denoptim.graph.rings.RingClosureParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 800 of file RingClosureParameters.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.graph.rings.RingClosureParameters.buildChelatesMode, denoptim.files.FileUtils.checkExists(), denoptim.graph.rings.RingClosureParameters.checkInterdepPaths, denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.graph.rings.RingClosureParameters.closeRings, denoptim.graph.rings.RingClosureParameters.exhaustiveConfSrch, denoptim.graph.rings.RingClosureParameters.maxRcaPerType, denoptim.graph.rings.RingClosureParameters.maxRingClosures, denoptim.graph.rings.RingClosureParameters.minRcaPerType, denoptim.graph.rings.RingClosureParameters.minRingClosures, denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.graph.rings.RingClosureParameters.rccFolder, denoptim.graph.rings.RingClosureParameters.rceMode, and denoptim.graph.rings.RingClosureParameters.selectFragsFromCC.
doExhaustiveConfSrch()
boolean denoptim.graph.rings.RingClosureParameters.doExhaustiveConfSrch ()
Definition at line 496 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.exhaustiveConfSrch.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability(), and denoptim.graph.rings.RingClosureFinder.evaluateClosability().
getBridgeHeadFindingRules()
List< BridgeHeadFindingRule > denoptim.graph.rings.RingClosureParameters.getBridgeHeadFindingRules ()
Definition at line 468 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.bridgeHeadFindingRules.
getClosabilityEvalMode()
int denoptim.graph.rings.RingClosureParameters.getClosabilityEvalMode ()
Definition at line 276 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rceMode.
Referenced by denoptim.graph.rings.PathClosabilityTools.isCloseable().
getConfPathExtraTolerance()
double denoptim.graph.rings.RingClosureParameters.getConfPathExtraTolerance ()
Definition at line 433 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.pathConfSearchExtraTol.
Referenced by denoptim.graph.rings.RingClosureFinder.evaluateClosability().
getConstitutionalClosabilityConds()
Map< String, String > denoptim.graph.rings.RingClosureParameters.getConstitutionalClosabilityConds ()
Definition at line 365 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.ringClosabCondAsSMARTS.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluateConstitutionalClosability().
getLinearityLimit()
double denoptim.graph.rings.RingClosureParameters.getLinearityLimit ()
Definition at line 447 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.linearityLimit.
Referenced by denoptim.graph.rings.RingClosureFinder.evaluateClosability().
getMaxNumberRotatableBonds()
int denoptim.graph.rings.RingClosureParameters.getMaxNumberRotatableBonds ()
Definition at line 283 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.maxRotBonds.
Referenced by denoptim.graph.rings.RingClosureFinder.evaluateClosability().
getMaxRcaPerType()
int denoptim.graph.rings.RingClosureParameters.getMaxRcaPerType (String type)
Parameters
type the elemental symbol of the RCA to consider.
Returns
the maximum allowed number of RCAs or 0, if not set.
Definition at line 341 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.maxRcaPerType.
Referenced by denoptim.graph.DGraph.checkConsistency().
getMaxRingClosures()
int denoptim.graph.rings.RingClosureParameters.getMaxRingClosures ()
Definition at line 358 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.maxRingClosures.
Referenced by denoptim.ga.EAUtils.setupRings().
getMaxRingSize()
int denoptim.graph.rings.RingClosureParameters.getMaxRingSize ()
Definition at line 290 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.maxRingSize.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.graph.rings.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.RingSizeManager.getRSBiasedListOfCandidates(), and denoptim.ga.GraphOperationsTest.testAddRing().
getMinRcaPerType()
int denoptim.graph.rings.RingClosureParameters.getMinRcaPerType (String type)
Parameters
type the elemental symbol of the RCA to consider.
Returns
the minimum allowed number of RCAs or 0, if not set.
Definition at line 327 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.minRcaPerType.
Referenced by denoptim.graph.DGraph.checkConsistency().
getMinRingClosures()
int denoptim.graph.rings.RingClosureParameters.getMinRingClosures ()
Definition at line 351 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.minRingClosures.
Referenced by denoptim.graph.DGraph.checkConsistency().
getPathConfSearchStep()
double denoptim.graph.rings.RingClosureParameters.getPathConfSearchStep ()
Definition at line 454 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.pathConfSearchStep.
Referenced by denoptim.graph.rings.CyclicGraphHandler.ClosableConf.canCoexistWith(), and denoptim.graph.rings.RingClosureFinder.evaluateClosability().
getPrintedList()
String denoptim.graph.rings.RingClosureParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 907 of file RingClosureParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getRCCLibraryFolder()
String denoptim.graph.rings.RingClosureParameters.getRCCLibraryFolder ()
Definition at line 482 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rccFolder.
Referenced by denoptim.graph.rings.RingClosuresArchive.getRCCsFromArchive(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
getRCCLibraryIndexFile()
String denoptim.graph.rings.RingClosureParameters.getRCCLibraryIndexFile ()
Definition at line 475 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rccIndex.
Referenced by denoptim.graph.rings.RingClosuresArchive.RingClosuresArchive(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
getRCDistTolerance()
double denoptim.graph.rings.RingClosureParameters.getRCDistTolerance ()
Definition at line 426 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rcTolDist.
Referenced by denoptim.molecularmodeling.RingClosureTool.closeRings(), and denoptim.graph.rings.RingClosure.getClosabilityConditions().
getRCDotPrTolerance()
double denoptim.graph.rings.RingClosureParameters.getRCDotPrTolerance ()
Definition at line 440 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rcMaxDot.
Referenced by denoptim.molecularmodeling.RingClosureTool.closeRings(), and denoptim.graph.rings.RingClosure.getClosabilityConditions().
getRequiredRingElements()
Set< String > denoptim.graph.rings.RingClosureParameters.getRequiredRingElements ()
Definition at line 461 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.reqElInRings.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluateConstitutionalClosability().
getRingClosuresArchive()
RingClosuresArchive denoptim.graph.rings.RingClosureParameters.getRingClosuresArchive ()
Definition at line 489 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.rcArchive.
Referenced by denoptim.ga.EAUtils.buildGraph(), and denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
getRingSizeBias()
List< Integer > denoptim.graph.rings.RingClosureParameters.getRingSizeBias ()
Returns
the list of biases for ring size. Each value is the weight of the preference for rings of the size equal to the index of the value in the list.
Definition at line 302 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.ringSizeBias.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.gui.FSParametersForm.FSParametersForm(), and denoptim.graph.rings.RingSizeManager.RingSizeManager().
getVerbosity()
int denoptim.graph.rings.RingClosureParameters.getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
Returns
the level of verbosity.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 391 of file RingClosureParameters.java.
References denoptim.programs.RunTimeParameters.verbosity.
Referenced by denoptim.graph.rings.RingClosuresArchive.getRCCsOfChain().
interpretKeyword()
void denoptim.graph.rings.RingClosureParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException is the parameter cannot be configured from the given value.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 517 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.bridgeHeadFindingRules, denoptim.graph.rings.RingClosureParameters.buildChelatesMode, denoptim.graph.rings.RingClosureParameters.checkInterdepPaths, denoptim.graph.rings.RingClosureParameters.closeRings, denoptim.graph.rings.RingClosureParameters.exhaustiveConfSrch, denoptim.graph.rings.RingClosureParameters.linearityLimit, denoptim.graph.APClass.make(), denoptim.graph.rings.RingClosureParameters.maxRcaPerType, denoptim.graph.rings.RingClosureParameters.maxRingClosures, denoptim.graph.rings.RingClosureParameters.maxRingSize, denoptim.graph.rings.RingClosureParameters.maxRotBonds, denoptim.graph.rings.RingClosureParameters.metalCoordinatingAPClasses, denoptim.graph.rings.RingClosureParameters.minRcaPerType, denoptim.graph.rings.RingClosureParameters.minRingClosures, denoptim.graph.rings.RingClosureParameters.pathConfSearchExtraTol, denoptim.graph.rings.RingClosureParameters.pathConfSearchStep, denoptim.graph.rings.RingClosureParameters.rccFolder, denoptim.graph.rings.RingClosureParameters.rccIndex, denoptim.graph.rings.RingClosureParameters.rceMode, denoptim.graph.rings.RingClosureParameters.rcMaxDot, denoptim.graph.rings.RingClosureParameters.rcTolDist, denoptim.io.DenoptimIO.readBridgeHesFindingRules(), denoptim.graph.rings.RingClosureParameters.reqElInRings, denoptim.graph.rings.RingClosureParameters.ringClosabCondAsSMARTS, denoptim.graph.rings.RingClosureParameters.ringSizeBias, denoptim.graph.rings.RingClosureParameters.selectFragsFromCC, denoptim.graph.rings.RingClosureParameters.serializeRCCs, and denoptim.programs.RunTimeParameters.verbosity.
processParameters()
void denoptim.graph.rings.RingClosureParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 893 of file RingClosureParameters.java.
References denoptim.programs.RunTimeParameters.processOtherParameters(), and denoptim.graph.rings.RingClosureParameters.rcArchive.
selectFragmentsFromClosableChains()
boolean denoptim.graph.rings.RingClosureParameters.selectFragmentsFromClosableChains ()
Definition at line 419 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.selectFragsFromCC.
Referenced by denoptim.ga.GraphOperations.extendGraph().
serializeRCCs()
boolean denoptim.graph.rings.RingClosureParameters.serializeRCCs ()
Definition at line 503 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.serializeRCCs.
setConstitutionalClosabilityConds()
void denoptim.graph.rings.RingClosureParameters.setConstitutionalClosabilityConds (Map< String, String > ringClosabCondAsSMARTS)
Sets the list of constitutions that can be formed by ring closure.
SMARTS are used to define such constitutions. Note that the ring-closing attractors are not considered in the definition of the constitution of the ring.
Parameters
ringClosabCondAsSMARTS a map where each entry is a rule that defined constitutions that can be formed. In each entry, the key is the name of the rule and is used only for logging, and the value is the SMARTS query that must be matched for a candidate ring to be accepted.
Definition at line 383 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.ringClosabCondAsSMARTS.
Referenced by denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability().
setRingSizeBias()
void denoptim.graph.rings.RingClosureParameters.setRingSizeBias (List< Integer > biases)
Sets the preference for certain ring sizes or the prohibition to generate certain rings (i.e., weight = 0).
Parameters
biases the list of biases for ring size. Each value is the weight
of the preference for rings of the size equal to the index of the value in the list.
Definition at line 316 of file RingClosureParameters.java.
References denoptim.graph.rings.RingClosureParameters.ringSizeBias.
Referenced by denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), and denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair().
Member Data Documentation
bridgeHeadFindingRules
List<BridgeHeadFindingRule> denoptim.graph.rings.RingClosureParameters.bridgeHeadFindingRules protected
Rules that identify the atoms that can become bridge heads to form fused rings.
Definition at line 248 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getBridgeHeadFindingRules(), denoptim.graph.rings.RingClosureParameters.interpretKeyword(), and denoptim.graph.rings.RingClosureParameters.RingClosureParameters().
buildChelatesMode
boolean denoptim.graph.rings.RingClosureParameters.buildChelatesMode = false protected
Flag activating procedures favoring formation of chelates.
Definition at line 66 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.buildChelatesMode(), denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.interpretKeyword(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), and denoptim.ga.EAUtils.setupRings().
checkInterdepPaths
boolean denoptim.graph.rings.RingClosureParameters.checkInterdepPaths = false protected
Flag controlling the ring-closing criterion evaluating the simultaneous closability of interdependent chains.
If true requires the evaluation of interdependent chains.
Definition at line 235 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkInterdependentChains(), denoptim.graph.rings.RingClosureParameters.checkParameters(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
closeRings
boolean denoptim.graph.rings.RingClosureParameters.closeRings = false protected
Flag activating the ring closing machinery.
Definition at line 54 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.allowRingClosures(), denoptim.graph.rings.RingClosureParameters.checkParameters(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
exhaustiveConfSrch
boolean denoptim.graph.rings.RingClosureParameters.exhaustiveConfSrch = false protected
Flag controlling conformational search.
If true the whole torsional space is scanned looking for ring closing conformations. WARNING! This is very time consuming, but is needed for the current implementation of the iterdependent ring criterion.
Definition at line 228 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.doExhaustiveConfSrch(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
linearityLimit
double denoptim.graph.rings.RingClosureParameters.linearityLimit = 178.5 protected
Maximum value for non-flat bond angle (in degree).
Definition at line 127 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getLinearityLimit(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
maxRcaPerType
Map<String,Integer> denoptim.graph.rings.RingClosureParameters.maxRcaPerType = new HashMap<String,Integer>() protected
Maximum number of RingClosingAttractors in a valid graph.
Definition at line 112 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getMaxRcaPerType(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
maxRingClosures
int denoptim.graph.rings.RingClosureParameters.maxRingClosures = 50 protected
Maximum number of RingClosures in a valid graph.
Definition at line 122 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getMaxRingClosures(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
maxRingSize
int denoptim.graph.rings.RingClosureParameters.maxRingSize = 9 protected
Maximum size (number of atoms) in ring closing chain.
The shortest path is considered.
Definition at line 102 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getMaxRingSize(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
maxRotBonds
int denoptim.graph.rings.RingClosureParameters.maxRotBonds = 7 protected
Maximum number of rotatable bonds for which conformational space is explored.
Definition at line 96 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getMaxNumberRotatableBonds(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
metalCoordinatingAPClasses
Set<APClass> denoptim.graph.rings.RingClosureParameters.metalCoordinatingAPClasses protected
Initial value:
=
            new HashSet<APClass>()
List of metal-coordinating APClasses.
Used to identify 'orphan' metal-coordinating sites that give rise to coordination isomerism (i.e., we have build a specific isomer, but the existence of unused metal- coordinating groups opens for the possibility of binding the metal/s with a different combination of groups).
Definition at line 75 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
minRcaPerType
Map<String,Integer> denoptim.graph.rings.RingClosureParameters.minRcaPerType = new HashMap<String,Integer>() protected
Minimum number of RingClosingAttractors in a valid graph.
Definition at line 107 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getMinRcaPerType(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
minRingClosures
int denoptim.graph.rings.RingClosureParameters.minRingClosures = 0 protected
Minimum number of RingClosures in a valid graph.
Definition at line 117 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getMinRingClosures(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
pathConfSearchExtraTol
double denoptim.graph.rings.RingClosureParameters.pathConfSearchExtraTol = 1.1 protected
Extra tolerance factor for interatomic distances.
This value (ep) is multiplied to the tolerance factor (p) when discrete as opposite to continue variation of torsion angles is performed. With the normal tolerance factor (p) and the lengths of the AP vectors l_H and l_T, the accepted deviation to an interatomic distance (dt) is calculated as dt = ep * p * (l_H + l_T) / 2
Definition at line 152 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getConfPathExtraTolerance(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
pathConfSearchStep
double denoptim.graph.rings.RingClosureParameters.pathConfSearchStep = 12.0 protected
Torsion angle step for conformational scan of candidate closable chain.
Definition at line 164 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getPathConfSearchStep(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
rcArchive
RingClosuresArchive denoptim.graph.rings.RingClosureParameters.rcArchive private
Collection of information about ring-closability of graph substructures.
Definition at line 220 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRingClosuresArchive(), denoptim.graph.rings.RingClosureParameters.processParameters(), and denoptim.graph.rings.RingClosureParameters.RingClosureParameters().
rccFolder
String denoptim.graph.rings.RingClosureParameters.rccFolder = "" protected
Pathname of the root folder containing the archive of serialized RingClosingConformations.
Definition at line 215 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getRCCLibraryFolder(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
rccIndex
String denoptim.graph.rings.RingClosureParameters.rccIndex = "" protected
Pathname of the text file containing the list of visited RingClosingConformations (i.e., index file).
The index file is machine-written and is bound to the corresponding libraries of fragments.
Definition at line 209 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRCCLibraryIndexFile(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
rceMode
int denoptim.graph.rings.RingClosureParameters.rceMode = -1 protected
The ring closability evaluation mode: -1= only ring rize bias 0 = only constitution of candidate ring, 1 = only closability of 3D chain, 2 = both 0 and 1.
Definition at line 90 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.getClosabilityEvalMode(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
rcMaxDot
double denoptim.graph.rings.RingClosureParameters.rcMaxDot = -0.75 protected
Maximum value of dot product between the normalized attachment point vectors at the head and tail of a candidate chain.
Note that perfect alignment implies a dot product of -1.0.
Definition at line 159 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRCDotPrTolerance(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
rcTolDist
double denoptim.graph.rings.RingClosureParameters.rcTolDist = 0.33 protected
Tolerance factor for interatomic distances.
This value is the percentage (p) of the average between the attachment point vector lengths at the head (l_H) and tail (l_T) of a candidate chain. dt = p * (l_H + l_T) / 2 Interatomic distance criteria are satisfied with a deviation of +/- dt
Definition at line 139 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRCDistTolerance(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
reqElInRings
Set<String> denoptim.graph.rings.RingClosureParameters.reqElInRings = new HashSet<String>() protected
Required elements in closable chains.
Definition at line 201 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRequiredRingElements(), and denoptim.graph.rings.RingClosureParameters.interpretKeyword().
requireCompleteRingclosure
boolean denoptim.graph.rings.RingClosureParameters.requireCompleteRingclosure = true
Flag requesting complete ring closure of all pairs of RCAs in at least one combination of RCAs to consider the calculation successful.
Definition at line 61 of file RingClosureParameters.java.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
ringClosabCondAsSMARTS
Map<String,String> denoptim.graph.rings.RingClosureParameters.ringClosabCondAsSMARTS protected
Initial value:
=
                                                 new HashMap<String,String>()
SMARTS defining the constitution-based ring closability condition.
Definition at line 195 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getConstitutionalClosabilityConds(), denoptim.graph.rings.RingClosureParameters.interpretKeyword(), and denoptim.graph.rings.RingClosureParameters.setConstitutionalClosabilityConds().
ringSizeBias
List<Integer> denoptim.graph.rings.RingClosureParameters.ringSizeBias protected
Initial value:
= new ArrayList<Integer>()
        {
            private static final long serialVersionUID = 1L;
            {
                for (int i=0; i<maxRingSize+1; i++)
                {
                    add(0);
                }
                if (maxRingSize>=7)
                {
                        set(5,2);
                        set(6,4);
                        set(7,1);
                }
            }
        }
Relative weight of ring sizes to bias the selection of a ring combination among the various alternatives.
Definition at line 170 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.getRingSizeBias(), denoptim.graph.rings.RingClosureParameters.interpretKeyword(), and denoptim.graph.rings.RingClosureParameters.setRingSizeBias().
selectFragsFromCC
boolean denoptim.graph.rings.RingClosureParameters.selectFragsFromCC = false protected
Flag activating the biased selection of closable fragment chains.
Definition at line 81 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.graph.rings.RingClosureParameters.interpretKeyword(), and denoptim.graph.rings.RingClosureParameters.selectFragmentsFromClosableChains().
serializeRCCs
boolean denoptim.graph.rings.RingClosureParameters.serializeRCCs = false protected
Flag controlling the serialization of the RingClosingConformations.
This flag is activated by the keyword providing the pathname of the root folder of the RCCs archive
Definition at line 242 of file RingClosureParameters.java.
Referenced by denoptim.graph.rings.RingClosureParameters.interpretKeyword(), denoptim.graph.rings.RingClosureParameters.serializeRCCs(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/RingClosureParameters.java