DENOPTIM: denoptim.combinatorial.CheckPoint Class Reference
denoptim.combinatorial.CheckPoint Class Reference
Object collecting information needed to restart a FragSpaceExplorer job.
Public Member Functions
CheckPoint ()
int getLevel ()
long getUnqVrtId ()
int getUnqGraphId ()
int getUnqMolId ()
ArrayList< Integer > getNextIds ()
int getLatestSafelyCompletedGraphId ()
int getRootId ()
boolean serFileAlreadyUsed (String filename)
void setNextIds (ArrayList< Integer > nextIds)
Set the indexes that identify the combination of fragments next to the latest one that has been properly processed.
void setLevel (int level)
Set the current level.
void setUnqVrtId (long l)
Set the restart value for the unique vertex ID.
void setUnqGraphId (int val)
Set the restart value for the unique graph ID.
void setUnqMolId (int val)
Set the restart value for the unique molecule ID.
void setSafelyCompletedGraphId (int val)
Set the graphId of the safely completed graph.
void setRootId (int val)
Set the graph ID of the root graph used to build this task.
String toString ()
Protected Attributes
int level = -1
Level.
long unqVrtId = -1L
Unique vertex index.
int unqGraphId = -1
Unique graph index.
int unqMolId = -1
Unique molecule index.
int rootId = -1
ID of the root graph used to build this graph.
int graphId = -1
ID of safely completed graph.
ArrayList< Integer > nextIds
Set of indexes for the next iteration in combination of building blocks.
Detailed Description
Object collecting information needed to restart a FragSpaceExplorer job.
The unique indexes are stored aiming to maintain the uniqueness property when restarting a job. Thus no vertex/graph/molecule will be found in the run generating a checkpoint with the ID stored in that checkpoint.
The checkpoint also stores the ID of the latest safely completed graph: a graph for which the corresponding task was completed when the checkpoint has been created, and of which all preceding tasks were also completed.
Author
Marco Foscato
Definition at line 39 of file CheckPoint.java.
Constructor & Destructor Documentation
CheckPoint()
denoptim.combinatorial.CheckPoint.CheckPoint ()
Definition at line 79 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.nextIds.
Member Function Documentation
getLatestSafelyCompletedGraphId()
int denoptim.combinatorial.CheckPoint.getLatestSafelyCompletedGraphId ()
Definition at line 121 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.graphId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getLevel()
int denoptim.combinatorial.CheckPoint.getLevel ()
Definition at line 86 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.level.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getNextIds()
ArrayList< Integer > denoptim.combinatorial.CheckPoint.getNextIds ()
Definition at line 114 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.nextIds.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel().
getRootId()
int denoptim.combinatorial.CheckPoint.getRootId ()
Definition at line 128 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.rootId.
getUnqGraphId()
int denoptim.combinatorial.CheckPoint.getUnqGraphId ()
Definition at line 100 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqGraphId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getUnqMolId()
int denoptim.combinatorial.CheckPoint.getUnqMolId ()
Definition at line 107 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqMolId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getUnqVrtId()
long denoptim.combinatorial.CheckPoint.getUnqVrtId ()
Definition at line 93 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqVrtId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
serFileAlreadyUsed()
boolean denoptim.combinatorial.CheckPoint.serFileAlreadyUsed (String filename)
Parameters
file the name of the binary file containing a serialized DENOPTIMGraph.
Returns
true if the graph from the given file has been fully explored before.
Definition at line 142 of file CheckPoint.java.
References denoptim.combinatorial.CEBLUtils.getBaseNameOfStorageFile(), and denoptim.combinatorial.CheckPoint.rootId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel().
setLevel()
void denoptim.combinatorial.CheckPoint.setLevel (int level)
Set the current level.
Definition at line 172 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.level.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setNextIds()
void denoptim.combinatorial.CheckPoint.setNextIds (ArrayList< Integer > nextIds)
Set the indexes that identify the combination of fragments next to the latest one that has been properly processed.
Definition at line 161 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.nextIds.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setRootId()
void denoptim.combinatorial.CheckPoint.setRootId (int val)
Set the graph ID of the root graph used to build this task.
Definition at line 227 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.rootId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setSafelyCompletedGraphId()
void denoptim.combinatorial.CheckPoint.setSafelyCompletedGraphId (int val)
Set the graphId of the safely completed graph.
Definition at line 216 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.graphId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setUnqGraphId()
void denoptim.combinatorial.CheckPoint.setUnqGraphId (int val)
Set the restart value for the unique graph ID.
Definition at line 194 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqGraphId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setUnqMolId()
void denoptim.combinatorial.CheckPoint.setUnqMolId (int val)
Set the restart value for the unique molecule ID.
Definition at line 205 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqMolId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
setUnqVrtId()
void denoptim.combinatorial.CheckPoint.setUnqVrtId (long l)
Set the restart value for the unique vertex ID.
Definition at line 183 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.unqVrtId.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint().
toString()
String denoptim.combinatorial.CheckPoint.toString ()
Definition at line 235 of file CheckPoint.java.
References denoptim.combinatorial.CheckPoint.graphId, denoptim.combinatorial.CheckPoint.level, denoptim.combinatorial.CheckPoint.nextIds, denoptim.combinatorial.CheckPoint.rootId, denoptim.combinatorial.CheckPoint.unqGraphId, denoptim.combinatorial.CheckPoint.unqMolId, and denoptim.combinatorial.CheckPoint.unqVrtId.
Member Data Documentation
graphId
int denoptim.combinatorial.CheckPoint.graphId = -1 protected
ID of safely completed graph.
Definition at line 69 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getLatestSafelyCompletedGraphId(), denoptim.combinatorial.CheckPoint.setSafelyCompletedGraphId(), and denoptim.combinatorial.CheckPoint.toString().
level
int denoptim.combinatorial.CheckPoint.level = -1 protected
Level.
Definition at line 44 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getLevel(), denoptim.combinatorial.CheckPoint.setLevel(), and denoptim.combinatorial.CheckPoint.toString().
nextIds
ArrayList<Integer> denoptim.combinatorial.CheckPoint.nextIds protected
Set of indexes for the next iteration in combination of building blocks.
Definition at line 74 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.CheckPoint(), denoptim.combinatorial.CheckPoint.getNextIds(), denoptim.combinatorial.CheckPoint.setNextIds(), and denoptim.combinatorial.CheckPoint.toString().
rootId
int denoptim.combinatorial.CheckPoint.rootId = -1 protected
ID of the root graph used to build this graph.
Definition at line 64 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getRootId(), denoptim.combinatorial.CheckPoint.serFileAlreadyUsed(), denoptim.combinatorial.CheckPoint.setRootId(), and denoptim.combinatorial.CheckPoint.toString().
unqGraphId
int denoptim.combinatorial.CheckPoint.unqGraphId = -1 protected
Unique graph index.
Definition at line 54 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getUnqGraphId(), denoptim.combinatorial.CheckPoint.setUnqGraphId(), and denoptim.combinatorial.CheckPoint.toString().
unqMolId
int denoptim.combinatorial.CheckPoint.unqMolId = -1 protected
Unique molecule index.
Definition at line 59 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getUnqMolId(), denoptim.combinatorial.CheckPoint.setUnqMolId(), and denoptim.combinatorial.CheckPoint.toString().
unqVrtId
long denoptim.combinatorial.CheckPoint.unqVrtId = -1L protected
Unique vertex index.
Definition at line 49 of file CheckPoint.java.
Referenced by denoptim.combinatorial.CheckPoint.getUnqVrtId(), denoptim.combinatorial.CheckPoint.setUnqVrtId(), and denoptim.combinatorial.CheckPoint.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/combinatorial/CheckPoint.java