DENOPTIM: denoptim.gui.GraphVertexMolViewerPanel Class Reference
denoptim.gui.GraphVertexMolViewerPanel Class Reference
A panel that collects three viewers:
Classes
class MouseModeChoiceListener
Listener for identifying the node on which the user has clicked and load the corresponding fragment into the fragment viewer pane.
class NodeClickedListener
Listener for identifying the node on which the user has clicked and load the corresponding fragment into the fragment viewer pane.
Public Member Functions
GraphVertexMolViewerPanel ()
Constructor.
void loadDnGraphToViewer (DGraph dnGraph, IAtomContainer mol, boolean keepSprites)
Loads the given graph into the graph viewer.
void loadDnGraphToViewer (DGraph dnGraph, boolean keepLabels)
Loads the given graph into the graph viewer.
void renderMolVieverToNeedUpdate ()
Triggers the generation of the molecular representation of the loaded graph.
IAtomContainer updateMolevularViewer ()
Updates the molecular representation of the loaded graph.
void resetFragViewerCardDeck ()
Changes the appearance of the vertex visualisation panel to an empty card that is consistent with the presence or lack of a loaded fragment space.
void clearCurrentSystem ()
Clears the current graph viewer but keeps track of the latest graph loaded.
void clearVertexViewer ()
Clears the molecular viewer and hides it behind the empty card.
void clearMolecularViewer ()
Clears the molecular viewer and hides it behind the empty card.
void moveDividerLocation ()
Moved the divider to the location configured by some content-based reasoning.
boolean hasSelectedNodes ()
void alterLabels (LabelType labelName, boolean show)
Adds/Removes labels to the graph components that are presently selected.
ArrayList< AttachmentPoint > getAPsSelectedInViewer ()
Identifies which attachment points are selected in the graph viewer.
ArrayList< Vertex > getSelectedNodesInViewer ()
Identifies which vertices are selected in the graph viewer.
void bringCardToTopOfVertexViewer (String cardName)
Allows to show the given card in the vertex viewer panel.
void bringCardToTopOfMolViewer (String cardName)
Allows to show the given card in the molecular structure viewer.
void dispose ()
void setMouseMode (ModalGraphMouse.Mode mode)
Alters the functionality of mouse in the graph visualization panel.
Protected Attributes
FragmentViewPanel fragViewer
MoleculeViewPanel molViewer
final String NOFSCARDNAME = "noFSCard"
final String EMPTYCARDNAME = "emptyCard"
final String NOTDUABLECARDNAME = "notDoableCard"
final String UPDATETOVIEW = "updateCard"
final String MOLVIEWERCARDNAME = "molViewerCard"
final String FRAGVIEWERCARDNAME = "fragViewerCard"
final String TMPLVIEWERCARDNAME = "tmplViewwerCard"
GraphViewerPanel graphViewer
Private Member Functions
void initialize ()
Initialize the panel and add buttons.
void removeNestedGraphViewer ()
void visualizeVertexInNestedViewer (Vertex v)
Makes a clone of the given vertex and loads that clone into the nested visualization frame.
Private Attributes
DGraph dnGraph
The unsaved version of the currently loaded graph.
JUNGGraphSnapshot oldGSStatus
The snapshot of the old (removed) visualized GraphStrem system.
JSplitPane leftPane
JPanel fragViewerPanel
JPanel fragViewerHeader
JPanel fragViewerCardHolder
JPanel fragViewerEmptyCard
JPanel fragViewerNotDuableCard
JPanel fragViewerNoFSCard
GraphVertexMolViewerPanel fragViewerTmplViewerCard
JPanel molViewerPanel
JPanel molViewerHeader
JPanel molViewerCardHolder
JPanel molViewerEmptyCard
JPanel molViewerNeedUpdateCard
final double DEFDIVLOC = 0.5
double defDivLoc = DEFDIVLOC
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
static final IChemObjectBuilder builder
Detailed Description
A panel that collects three viewers:
one for Graphs,
one for vertex content,
and one for molecular structures.
Author
Marco Foscato
Definition at line 63 of file GraphVertexMolViewerPanel.java.
Constructor & Destructor Documentation
GraphVertexMolViewerPanel()
denoptim.gui.GraphVertexMolViewerPanel.GraphVertexMolViewerPanel ()
Constructor.
Definition at line 117 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.initialize().
Referenced by denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
Member Function Documentation
alterLabels()
void denoptim.gui.GraphVertexMolViewerPanel.alterLabels (LabelType labelName, boolean show)
Adds/Removes labels to the graph components that are presently selected.
Parameters
labelName the string identifying which label to add.
show use true to display labels, or false to hide labels of the given kind.
Definition at line 562 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphViewerPanel.alterLabels(), and denoptim.gui.GraphVertexMolViewerPanel.graphViewer.
Referenced by denoptim.gui.GUIGraphHandler.showHideLabelsListener.actionPerformed().
bringCardToTopOfMolViewer()
void denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer (String cardName)
Allows to show the given card in the molecular structure viewer.
Parameters
cardName the name of the card to display. The possible values are defined as static, final fields: GraphVertexMolViewerPanel.UPDATETOVIEW, GraphVertexMolViewerPanel.MOLVIEWERCARDNAME, GraphVertexMolViewerPanel.TMPLVIEWERCARDNAME
Definition at line 635 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.molViewerCardHolder.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
bringCardToTopOfVertexViewer()
void denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfVertexViewer (String cardName)
Allows to show the given card in the vertex viewer panel.
Parameters
cardName the name of the card to display. The possible values are defined as static, final fields: GraphVertexMolViewerPanel.NOFSCARDNAME, GraphVertexMolViewerPanel.EMPTYCARDNAME, GraphVertexMolViewerPanel.NOTDUABLECARDNAME, GraphVertexMolViewerPanel.FRAGVIEWERCARDNAME
Definition at line 619 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.fragViewerCardHolder.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer(), denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
clearCurrentSystem()
void denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem ()
Clears the current graph viewer but keeps track of the latest graph loaded.
Definition at line 395 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphViewerPanel.cleanup(), denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer(), denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer(), denoptim.gui.GraphVertexMolViewerPanel.dnGraph, and denoptim.gui.GraphVertexMolViewerPanel.graphViewer.
Referenced by denoptim.gui.GUIGraphHandler.clearCurrentSystem().
clearMolecularViewer()
void denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer ()
Clears the molecular viewer and hides it behind the empty card.
Definition at line 421 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), denoptim.gui.MoleculeViewPanel.clearAll(), denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, and denoptim.gui.GraphVertexMolViewerPanel.molViewer.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem(), and denoptim.gui.GUIGraphHandler.initializeCurrentGraph().
clearVertexViewer()
void denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer ()
Clears the molecular viewer and hides it behind the empty card.
Definition at line 408 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfVertexViewer(), denoptim.gui.FragmentViewPanel.clearAll(), denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, and denoptim.gui.GraphVertexMolViewerPanel.fragViewer.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem().
dispose()
void denoptim.gui.GraphVertexMolViewerPanel.dispose ()
Definition at line 647 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.FragmentViewPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphViewerPanel.dispose(), denoptim.gui.MoleculeViewPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.fragViewer, denoptim.gui.GraphVertexMolViewerPanel.fragViewerTmplViewerCard, denoptim.gui.GraphVertexMolViewerPanel.graphViewer, and denoptim.gui.GraphVertexMolViewerPanel.molViewer.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GUIGraphHandler.dispose(), and denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer().
getAPsSelectedInViewer()
ArrayList< AttachmentPoint > denoptim.gui.GraphVertexMolViewerPanel.getAPsSelectedInViewer ()
Identifies which attachment points are selected in the graph viewer.
Returns
the list selected attachment points.
Definition at line 574 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphViewerPanel.JVertexType.AP, denoptim.gui.GraphViewerPanel.getSelectedNodes(), and denoptim.gui.GraphVertexMolViewerPanel.graphViewer.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
getSelectedNodesInViewer()
ArrayList< Vertex > denoptim.gui.GraphVertexMolViewerPanel.getSelectedNodesInViewer ()
Identifies which vertices are selected in the graph viewer.
Returns
the list of identifiers
Definition at line 594 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphViewerPanel.JVertexType.AP, denoptim.gui.GraphViewerPanel.getSelectedNodes(), and denoptim.gui.GraphVertexMolViewerPanel.graphViewer.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
hasSelectedNodes()
boolean denoptim.gui.GraphVertexMolViewerPanel.hasSelectedNodes ()
Returns
true is there is any selected node in the graph viewer
Definition at line 549 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.graphViewer, and denoptim.gui.GraphViewerPanel.hasSelected().
Referenced by denoptim.gui.GUIGraphHandler.showHideLabelsListener.actionPerformed().
initialize()
void denoptim.gui.GraphVertexMolViewerPanel.initialize () private
Initialize the panel and add buttons.
Definition at line 127 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, denoptim.gui.MoleculeViewPanel.enablePartialData(), denoptim.gui.GraphVertexMolViewerPanel.fragViewer, denoptim.gui.GraphVertexMolViewerPanel.fragViewerCardHolder, denoptim.gui.GraphVertexMolViewerPanel.FRAGVIEWERCARDNAME, denoptim.gui.GraphVertexMolViewerPanel.fragViewerEmptyCard, denoptim.gui.GraphVertexMolViewerPanel.fragViewerHeader, denoptim.gui.GraphVertexMolViewerPanel.fragViewerNoFSCard, denoptim.gui.GraphVertexMolViewerPanel.fragViewerNotDuableCard, denoptim.gui.GraphVertexMolViewerPanel.fragViewerPanel, denoptim.gui.GraphVertexMolViewerPanel.graphViewer, denoptim.gui.GraphVertexMolViewerPanel.leftPane, denoptim.gui.GraphVertexMolViewerPanel.molViewer, denoptim.gui.GraphVertexMolViewerPanel.molViewerCardHolder, denoptim.gui.GraphVertexMolViewerPanel.MOLVIEWERCARDNAME, denoptim.gui.GraphVertexMolViewerPanel.molViewerEmptyCard, denoptim.gui.GraphVertexMolViewerPanel.molViewerHeader, denoptim.gui.GraphVertexMolViewerPanel.molViewerNeedUpdateCard, denoptim.gui.GraphVertexMolViewerPanel.molViewerPanel, denoptim.gui.GraphVertexMolViewerPanel.NOFSCARDNAME, denoptim.gui.GraphVertexMolViewerPanel.NOTDUABLECARDNAME, denoptim.gui.GraphViewerPanel.PROPERTYMOUSEMODE, denoptim.gui.GraphViewerPanel.PROPERTYNODECLICKED, and denoptim.gui.GraphVertexMolViewerPanel.UPDATETOVIEW.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.GraphVertexMolViewerPanel().
loadDnGraphToViewer() [1/2]
void denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer (DGraph dnGraph, boolean keepLabels)
Loads the given graph into the graph viewer.
Parameters
dnGraph the graph to load.
keepLabels if true we'll keep track of old labels. loaded.
Definition at line 268 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphViewerPanel.cleanup(), denoptim.gui.GraphVertexMolViewerPanel.defDivLoc, denoptim.gui.GraphVertexMolViewerPanel.dnGraph, denoptim.gui.GraphViewerPanel.getGraphStatusSnapshot(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.gui.GraphVertexMolViewerPanel.graphViewer, denoptim.gui.GraphVertexMolViewerPanel.leftPane, denoptim.gui.GraphViewerPanel.loadGraphToViewer(), denoptim.gui.GraphVertexMolViewerPanel.oldGSStatus, denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
loadDnGraphToViewer() [2/2]
void denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer (DGraph dnGraph, IAtomContainer mol, boolean keepSprites)
Loads the given graph into the graph viewer.
Parameters
dnGraph the graph to load.
mol the molecular representation of the graph. Use this to avoid converting the graph into a molecular representation every time you load the same graph.
keepSprites if true we'll keep track of old labels.
Definition at line 245 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), denoptim.gui.GraphVertexMolViewerPanel.dnGraph, denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, denoptim.gui.MoleculeViewPanel.loadChemicalStructure(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GraphVertexMolViewerPanel.molViewer, and denoptim.gui.GraphVertexMolViewerPanel.MOLVIEWERCARDNAME.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
moveDividerLocation()
void denoptim.gui.GraphVertexMolViewerPanel.moveDividerLocation ()
Moved the divider to the location configured by some content-based reasoning.
Definition at line 539 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.defDivLoc.
Referenced by denoptim.gui.GUIGraphHandler.paint().
removeNestedGraphViewer()
void denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer () private
Definition at line 378 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.fragViewerCardHolder, and denoptim.gui.GraphVertexMolViewerPanel.fragViewerTmplViewerCard.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
renderMolVieverToNeedUpdate()
void denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate ()
Triggers the generation of the molecular representation of the loaded graph.
Definition at line 299 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), denoptim.gui.MoleculeViewPanel.clearAll(), denoptim.gui.GraphVertexMolViewerPanel.molViewer, and denoptim.gui.GraphVertexMolViewerPanel.UPDATETOVIEW.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), and denoptim.gui.GUIGraphHandler.initialize().
resetFragViewerCardDeck()
void denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck ()
Changes the appearance of the vertex visualisation panel to an empty card that is consistent with the presence or lack of a loaded fragment space.
Definition at line 364 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfVertexViewer(), denoptim.gui.FragmentViewPanel.clearAll(), denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, denoptim.gui.GraphVertexMolViewerPanel.fragViewer, and denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer().
Referenced by denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.loadFragmentSpace(), and denoptim.gui.GraphVertexMolViewerPanel.NodeClickedListener.propertyChange().
setMouseMode()
void denoptim.gui.GraphVertexMolViewerPanel.setMouseMode (ModalGraphMouse.Mode mode)
Alters the functionality of mouse in the graph visualization panel.
Parameters
mode the mode of action of the mouse.
Definition at line 664 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.graphViewer, and denoptim.gui.GraphViewerPanel.setMouseMode().
Referenced by denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.MouseModeChoiceListener.propertyChange().
updateMolevularViewer()
IAtomContainer denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer ()
Updates the molecular representation of the loaded graph.
We rebuild the molecular representation. This method is needed in case of changes to the loaded graph, to project those changes in the graph into the molecular representation.
Definition at line 316 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), denoptim.gui.GraphVertexMolViewerPanel.builder, denoptim.gui.MoleculeViewPanel.clearAll(), denoptim.graph.DGraph.containsAtoms(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.gui.GraphVertexMolViewerPanel.dnGraph, denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, denoptim.gui.GUI.GUILOGGER, denoptim.gui.MoleculeViewPanel.loadChemicalStructure(), denoptim.gui.GraphVertexMolViewerPanel.molViewer, denoptim.gui.GraphVertexMolViewerPanel.MOLVIEWERCARDNAME, denoptim.gui.GUI.PRNG, and denoptim.utils.MoleculeUtils.removeUsedRCA().
Referenced by denoptim.gui.GUIGraphHandler.saveUnsavedChanges().
visualizeVertexInNestedViewer()
void denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer (Vertex v) private
Makes a clone of the given vertex and loads that clone into the nested visualization frame.
Parameters
v the original vertex
Definition at line 458 of file GraphVertexMolViewerPanel.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfVertexViewer(), denoptim.gui.FragmentViewPanel.clearAll(), denoptim.graph.Vertex.clone(), denoptim.gui.GraphVertexMolViewerPanel.DEFDIVLOC, denoptim.gui.GraphVertexMolViewerPanel.fragViewer, denoptim.gui.GraphVertexMolViewerPanel.fragViewerCardHolder, denoptim.gui.GraphVertexMolViewerPanel.FRAGVIEWERCARDNAME, denoptim.gui.GraphVertexMolViewerPanel.fragViewerTmplViewerCard, denoptim.graph.Template.getIAtomContainer(), denoptim.graph.Template.getInnerGraph(), denoptim.gui.GraphVertexMolViewerPanel.GraphVertexMolViewerPanel(), denoptim.gui.GraphVertexMolViewerPanel.graphViewer, denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.FragmentViewPanel.loadFragmentToViewer(), denoptim.gui.GraphVertexMolViewerPanel.NOTDUABLECARDNAME, denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer(), and denoptim.gui.GraphVertexMolViewerPanel.TMPLVIEWERCARDNAME.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), and denoptim.gui.GraphVertexMolViewerPanel.NodeClickedListener.propertyChange().
Member Data Documentation
builder
final IChemObjectBuilder denoptim.gui.GraphVertexMolViewerPanel.builder static private
Initial value:
=
                SilentChemObjectBuilder.getInstance()
Definition at line 109 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
DEFDIVLOC
final double denoptim.gui.GraphVertexMolViewerPanel.DEFDIVLOC = 0.5 private
Definition at line 106 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
defDivLoc
double denoptim.gui.GraphVertexMolViewerPanel.defDivLoc = DEFDIVLOC private
Definition at line 107 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), and denoptim.gui.GraphVertexMolViewerPanel.moveDividerLocation().
dnGraph
DGraph denoptim.gui.GraphVertexMolViewerPanel.dnGraph private
The unsaved version of the currently loaded graph.
Definition at line 73 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
EMPTYCARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME = "emptyCard" protected
Definition at line 97 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer(), denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer(), denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
fragViewer
FragmentViewPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewer protected
Definition at line 82 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer(), denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
fragViewerCardHolder
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerCardHolder private
Definition at line 85 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfVertexViewer(), denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
FRAGVIEWERCARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.FRAGVIEWERCARDNAME = "fragViewerCard" protected
Definition at line 101 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
fragViewerEmptyCard
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerEmptyCard private
Definition at line 86 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
fragViewerHeader
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerHeader private
Definition at line 84 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
fragViewerNoFSCard
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerNoFSCard private
Definition at line 88 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
fragViewerNotDuableCard
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerNotDuableCard private
Definition at line 87 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
fragViewerPanel
JPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerPanel private
Definition at line 83 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
fragViewerTmplViewerCard
GraphVertexMolViewerPanel denoptim.gui.GraphVertexMolViewerPanel.fragViewerTmplViewerCard private
Definition at line 89 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.removeNestedGraphViewer(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
graphViewer
GraphViewerPanel denoptim.gui.GraphVertexMolViewerPanel.graphViewer protected
Definition at line 103 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.alterLabels(), denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem(), denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.getAPsSelectedInViewer(), denoptim.gui.GraphVertexMolViewerPanel.getSelectedNodesInViewer(), denoptim.gui.GraphVertexMolViewerPanel.hasSelectedNodes(), denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GraphVertexMolViewerPanel.setMouseMode(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
leftPane
JSplitPane denoptim.gui.GraphVertexMolViewerPanel.leftPane private
Definition at line 81 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer().
molViewer
MoleculeViewPanel denoptim.gui.GraphVertexMolViewerPanel.molViewer protected
Definition at line 90 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer(), denoptim.gui.GraphVertexMolViewerPanel.dispose(), denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
molViewerCardHolder
JPanel denoptim.gui.GraphVertexMolViewerPanel.molViewerCardHolder private
Definition at line 93 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), and denoptim.gui.GraphVertexMolViewerPanel.initialize().
MOLVIEWERCARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.MOLVIEWERCARDNAME = "molViewerCard" protected
Definition at line 100 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
molViewerEmptyCard
JPanel denoptim.gui.GraphVertexMolViewerPanel.molViewerEmptyCard private
Definition at line 94 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
molViewerHeader
JPanel denoptim.gui.GraphVertexMolViewerPanel.molViewerHeader private
Definition at line 92 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
molViewerNeedUpdateCard
JPanel denoptim.gui.GraphVertexMolViewerPanel.molViewerNeedUpdateCard private
Definition at line 95 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
molViewerPanel
JPanel denoptim.gui.GraphVertexMolViewerPanel.molViewerPanel private
Definition at line 91 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
NOFSCARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.NOFSCARDNAME = "noFSCard" protected
Definition at line 96 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize().
NOTDUABLECARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.NOTDUABLECARDNAME = "notDoableCard" protected
Definition at line 98 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
oldGSStatus
JUNGGraphSnapshot denoptim.gui.GraphVertexMolViewerPanel.oldGSStatus private
The snapshot of the old (removed) visualized GraphStrem system.
Used only to remember stuff like sprites and node positions.
Definition at line 79 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer().
serialVersionUID
final long denoptim.gui.GraphVertexMolViewerPanel.serialVersionUID = 1L static private
Version UID.
Definition at line 68 of file GraphVertexMolViewerPanel.java.
TMPLVIEWERCARDNAME
final String denoptim.gui.GraphVertexMolViewerPanel.TMPLVIEWERCARDNAME = "tmplViewwerCard" protected
Definition at line 102 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
UPDATETOVIEW
final String denoptim.gui.GraphVertexMolViewerPanel.UPDATETOVIEW = "updateCard" protected
Definition at line 99 of file GraphVertexMolViewerPanel.java.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GraphVertexMolViewerPanel.java