DENOPTIM: denoptim.programs.grapheditor.GraphEdParameters Class Reference
denoptim.programs.grapheditor.GraphEdParameters Class Reference
Parameters controlling execution of GraphEditor.
Public Member Functions
GraphEdParameters ()
Constructor.
ArrayList< GraphEdit > getGraphEditTasks ()
ArrayList< DGraph > getInputGraphs ()
IAtomContainer getInpMol (int i)
String getOutFile ()
boolean symmetryFlag ()
FileFormat getOutFormat ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Protected Member Functions
void readInputGraphs () throws DENOPTIMException
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Private Attributes
String inGraphsFile = null
File with input graphs.
ArrayList< DGraph > inGraphs = new ArrayList<DGraph>()
Input graphs.
ArrayList< IAtomContainer > inMols
Input molecular objects.
String graphEditsFile = null
File with list of edit tasks.
ArrayList< GraphEdit > graphEdits
Graph's editing tasks.
String outGraphsFile = null
File with output graphs.
FileFormat outGraphsFormat = FileFormat.GRAPHSDF
boolean symmetry = false
Flag controlling strategy with respect to symmetry.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Detailed Description
Parameters controlling execution of GraphEditor.
Author
Marco Foscato
Definition at line 44 of file GraphEdParameters.java.
Constructor & Destructor Documentation
GraphEdParameters()
denoptim.programs.grapheditor.GraphEdParameters.GraphEdParameters ()
Constructor.
Definition at line 87 of file GraphEdParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.GE_PARAMS.
Member Function Documentation
checkParameters()
void denoptim.programs.grapheditor.GraphEdParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 242 of file GraphEdParameters.java.
References denoptim.files.FileUtils.checkExists(), denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.grapheditor.GraphEdParameters.graphEditsFile, denoptim.programs.grapheditor.GraphEdParameters.inGraphsFile, denoptim.programs.grapheditor.GraphEdParameters.outGraphsFile, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
getGraphEditTasks()
ArrayList< GraphEdit > denoptim.programs.grapheditor.GraphEdParameters.getGraphEditTasks ()
Definition at line 94 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.graphEdits.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
getInpMol()
IAtomContainer denoptim.programs.grapheditor.GraphEdParameters.getInpMol (int i)
Definition at line 108 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.inMols.
getInputGraphs()
ArrayList< DGraph > denoptim.programs.grapheditor.GraphEdParameters.getInputGraphs ()
Definition at line 101 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.inGraphs.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
getOutFile()
String denoptim.programs.grapheditor.GraphEdParameters.getOutFile ()
Definition at line 115 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.outGraphsFile.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
getOutFormat()
FileFormat denoptim.programs.grapheditor.GraphEdParameters.getOutFormat ()
Definition at line 129 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.outGraphsFormat.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
getPrintedList()
String denoptim.programs.grapheditor.GraphEdParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 210 of file GraphEdParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
interpretKeyword()
void denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 143 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.graphEditsFile, denoptim.files.FileFormat.GRAPHJSON, denoptim.files.FileFormat.GRAPHSDF, denoptim.programs.grapheditor.GraphEdParameters.inGraphsFile, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.grapheditor.GraphEdParameters.outGraphsFile, denoptim.programs.grapheditor.GraphEdParameters.outGraphsFormat, denoptim.programs.grapheditor.GraphEdParameters.symmetry, denoptim.programs.RunTimeParameters.verbosity, and denoptim.programs.RunTimeParameters.workDir.
processParameters()
void denoptim.programs.grapheditor.GraphEdParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 286 of file GraphEdParameters.java.
References denoptim.files.FileUtils.checkExists(), denoptim.programs.grapheditor.GraphEdParameters.graphEdits, denoptim.programs.grapheditor.GraphEdParameters.graphEditsFile, denoptim.programs.grapheditor.GraphEdParameters.inGraphsFile, denoptim.programs.grapheditor.GraphEdParameters.outGraphsFile, denoptim.programs.RunTimeParameters.processOtherParameters(), and denoptim.io.DenoptimIO.readDENOPTIMGraphEditFromFile().
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
readInputGraphs()
void denoptim.programs.grapheditor.GraphEdParameters.readInputGraphs () throws DENOPTIMException protected
Definition at line 317 of file GraphEdParameters.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.grapheditor.GraphEdParameters.inGraphs, denoptim.programs.grapheditor.GraphEdParameters.inGraphsFile, and denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile().
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
symmetryFlag()
boolean denoptim.programs.grapheditor.GraphEdParameters.symmetryFlag ()
Definition at line 122 of file GraphEdParameters.java.
References denoptim.programs.grapheditor.GraphEdParameters.symmetry.
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
Member Data Documentation
graphEdits
ArrayList<GraphEdit> denoptim.programs.grapheditor.GraphEdParameters.graphEdits private
Graph's editing tasks.
Definition at line 69 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.getGraphEditTasks(), and denoptim.programs.grapheditor.GraphEdParameters.processParameters().
graphEditsFile
String denoptim.programs.grapheditor.GraphEdParameters.graphEditsFile = null private
File with list of edit tasks.
Definition at line 64 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.checkParameters(), denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword(), and denoptim.programs.grapheditor.GraphEdParameters.processParameters().
inGraphs
ArrayList<DGraph> denoptim.programs.grapheditor.GraphEdParameters.inGraphs = new ArrayList<DGraph>() private
Input graphs.
Definition at line 54 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.getInputGraphs(), and denoptim.programs.grapheditor.GraphEdParameters.readInputGraphs().
inGraphsFile
String denoptim.programs.grapheditor.GraphEdParameters.inGraphsFile = null private
File with input graphs.
Definition at line 49 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.checkParameters(), denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword(), denoptim.programs.grapheditor.GraphEdParameters.processParameters(), and denoptim.programs.grapheditor.GraphEdParameters.readInputGraphs().
inMols
ArrayList<IAtomContainer> denoptim.programs.grapheditor.GraphEdParameters.inMols private
Input molecular objects.
Definition at line 59 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.getInpMol().
outGraphsFile
String denoptim.programs.grapheditor.GraphEdParameters.outGraphsFile = null private
File with output graphs.
Definition at line 74 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.checkParameters(), denoptim.programs.grapheditor.GraphEdParameters.getOutFile(), denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword(), and denoptim.programs.grapheditor.GraphEdParameters.processParameters().
outGraphsFormat
FileFormat denoptim.programs.grapheditor.GraphEdParameters.outGraphsFormat = FileFormat.GRAPHSDF private
Definition at line 75 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.getOutFormat(), and denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword().
symmetry
boolean denoptim.programs.grapheditor.GraphEdParameters.symmetry = false private
Flag controlling strategy with respect to symmetry.
Definition at line 80 of file GraphEdParameters.java.
Referenced by denoptim.programs.grapheditor.GraphEdParameters.interpretKeyword(), and denoptim.programs.grapheditor.GraphEdParameters.symmetryFlag().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/grapheditor/GraphEdParameters.java