DENOPTIM: denoptim.graph.FragmentIsomorphismInspectorTest Class Reference
denoptim.graph.FragmentIsomorphismInspectorTest Class Reference
Unit test for isomorphism inspector.
Public Member Functions
void testTimeout () throws Exception
void testIsomorphismExists () throws Exception
Static Public Member Functions
static Fragment makePathologicalFragment (int size) throws DENOPTIMException
Detailed Description
Unit test for isomorphism inspector.
Author
Marco Foscato
Definition at line 40 of file FragmentIsomorphismInspectorTest.java.
Member Function Documentation
makePathologicalFragment()
static Fragment denoptim.graph.FragmentIsomorphismInspectorTest.makePathologicalFragment (int size) throws DENOPTIMException static
Definition at line 45 of file FragmentIsomorphismInspectorTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.Fragment.getAtom(), and denoptim.graph.APClass.make().
Referenced by denoptim.graph.FragmentIsomorphismInspectorTest.testTimeout().
testIsomorphismExists()
void denoptim.graph.FragmentIsomorphismInspectorTest.testIsomorphismExists () throws Exception
Definition at line 82 of file FragmentIsomorphismInspectorTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.Fragment.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.Fragment.getAtom(), denoptim.graph.FragmentIsomorphismInspector.isomorphismExists(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.removeAP(), denoptim.graph.Fragment.removeBond(), denoptim.graph.AttachmentPoint.setAPClass(), and denoptim.graph.AttachmentPoint.setDirectionVector().
testTimeout()
void denoptim.graph.FragmentIsomorphismInspectorTest.testTimeout () throws Exception
Definition at line 64 of file FragmentIsomorphismInspectorTest.java.
References denoptim.graph.FragmentIsomorphismInspector.isomorphismExists(), and denoptim.graph.FragmentIsomorphismInspectorTest.makePathologicalFragment().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/FragmentIsomorphismInspectorTest.java