DENOPTIM: denoptim.graph.APClassTest Class Reference
denoptim.graph.APClassTest Class Reference
Unit test for APClass.
Public Member Functions
void testConstructor () throws Exception
void testIsValidAPSubCLassString () throws Exception
void testIsValidAPRuleString () throws Exception
void testEquals () throws Exception
void testListContains () throws Exception
void testCompareTo () throws Exception
Detailed Description
Unit test for APClass.
Author
Marco Foscato
Definition at line 46 of file APClassTest.java.
Member Function Documentation
testCompareTo()
void denoptim.graph.APClassTest.testCompareTo () throws Exception
Definition at line 139 of file APClassTest.java.
References denoptim.graph.APClass.make(), and denoptim.graph.Edge.BondType.UNDEFINED.
testConstructor()
void denoptim.graph.APClassTest.testConstructor () throws Exception
Definition at line 51 of file APClassTest.java.
testEquals()
void denoptim.graph.APClassTest.testEquals () throws Exception
Definition at line 91 of file APClassTest.java.
References denoptim.graph.APClass.equals(), denoptim.graph.APClass.make(), and denoptim.graph.Edge.BondType.UNDEFINED.
testIsValidAPRuleString()
void denoptim.graph.APClassTest.testIsValidAPRuleString () throws Exception
Definition at line 76 of file APClassTest.java.
References denoptim.graph.APClass.isValidAPRuleString(), and denoptim.constants.DENOPTIMConstants.SEPARATORAPPROPSCL.
testIsValidAPSubCLassString()
void denoptim.graph.APClassTest.testIsValidAPSubCLassString () throws Exception
Definition at line 63 of file APClassTest.java.
References denoptim.graph.APClass.isValidAPSubCLassString().
testListContains()
void denoptim.graph.APClassTest.testListContains () throws Exception
Definition at line 113 of file APClassTest.java.
References denoptim.graph.APClass.DEFAULTBT, and denoptim.graph.APClass.make().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/APClassTest.java