DENOPTIM: denoptim.graph.AttachmentPointQuery Class Reference
denoptim.graph.AttachmentPointQuery Class Reference
Query for searching AttachmentPoints.
Public Member Functions
AttachmentPointQuery ()
Constructor for an empty query.
AttachmentPointQuery (Long apID, Integer apIndex, APClass apClass, VertexQuery vertexQuery, EdgeQuery edgeQuery, AttachmentPointQuery linkedAPQuery)
Constructor from individual criteria.
boolean matches (AttachmentPoint ap)
Tests whether the given attachment point satisfies all non-null criteria in this query.
Private Attributes
Long apID = null
Query on the unique identifier of the target attachment point, or null.
Integer apIndex = null
Query on the index of the target attachment point, or null.
APClass apClass = null
Query on the APClass of the target attachment point, or null.
VertexQuery vertexQuery = null
Query on vertex owning the target attachment point, or null.
EdgeQuery edgeQuery = null
Query on the Edge using the target attachment point, or null.
AttachmentPointQuery linkedAPQuery = null
Query defining the attachment point linked by an edge to the target attachment point, or null.
Detailed Description
Query for searching AttachmentPoints.
Definition at line 24 of file AttachmentPointQuery.java.
Constructor & Destructor Documentation
AttachmentPointQuery() [1/2]
denoptim.graph.AttachmentPointQuery.AttachmentPointQuery ()
Constructor for an empty query.
Definition at line 62 of file AttachmentPointQuery.java.
AttachmentPointQuery() [2/2]
denoptim.graph.AttachmentPointQuery.AttachmentPointQuery (Long apID, Integer apIndex, APClass apClass, VertexQuery vertexQuery, EdgeQuery edgeQuery, AttachmentPointQuery linkedAPQuery)
Constructor from individual criteria.
Parameters
apID the query on the unique identifier of the target attachment point, or null.
apIndex the query on the index of the target attachment point, or null.
apClass the query on the APClass of the target attachment point, or null.
vertexQuery the query on the vertex owning the target attachment point, or null.
edgeQuery the query on the Edge using the target attachment point, or null.
linkedAPQuery the query on the attachment point linked by an edge to the target attachment point, or null.
Definition at line 77 of file AttachmentPointQuery.java.
References denoptim.graph.AttachmentPointQuery.apClass, denoptim.graph.AttachmentPointQuery.apID, denoptim.graph.AttachmentPointQuery.apIndex, denoptim.graph.AttachmentPointQuery.edgeQuery, denoptim.graph.AttachmentPointQuery.linkedAPQuery, and denoptim.graph.AttachmentPointQuery.vertexQuery.
Member Function Documentation
matches()
boolean denoptim.graph.AttachmentPointQuery.matches (AttachmentPoint ap)
Tests whether the given attachment point satisfies all non-null criteria in this query.
Parameters
ap the attachment point to test
Returns
true if the attachment point matches, false otherwise
Definition at line 98 of file AttachmentPointQuery.java.
References denoptim.graph.AttachmentPointQuery.apClass, denoptim.graph.AttachmentPointQuery.apID, denoptim.graph.AttachmentPointQuery.apIndex, denoptim.graph.AttachmentPointQuery.edgeQuery, denoptim.graph.APClass.equals(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.AttachmentPoint.getID(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.AttachmentPointQuery.linkedAPQuery, denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.EdgeQuery.matches(), denoptim.graph.VertexQuery.matches(), and denoptim.graph.AttachmentPointQuery.vertexQuery.
Referenced by denoptim.graph.DGraph.findAPs(), denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.EdgeQuery.matches(), denoptim.graph.AttachmentPointQueryTest.testEmptyEdgeQueryRequiresEdge(), denoptim.graph.AttachmentPointQueryTest.testFindAPsUsesMatches(), denoptim.graph.AttachmentPointQueryTest.testLinkedAPQuery(), denoptim.graph.AttachmentPointQueryTest.testMatchesAllNullCriteria(), denoptim.graph.AttachmentPointQueryTest.testMatchesAPClass(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointId(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointIndex(), denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedVertexQuery().
Member Data Documentation
apClass
APClass denoptim.graph.AttachmentPointQuery.apClass = null private
Query on the APClass of the target attachment point, or null.
Definition at line 39 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
apID
Long denoptim.graph.AttachmentPointQuery.apID = null private
Query on the unique identifier of the target attachment point, or null.
Definition at line 29 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
apIndex
Integer denoptim.graph.AttachmentPointQuery.apIndex = null private
Query on the index of the target attachment point, or null.
Definition at line 34 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
edgeQuery
EdgeQuery denoptim.graph.AttachmentPointQuery.edgeQuery = null private
Query on the Edge using the target attachment point, or null.
Definition at line 49 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
linkedAPQuery
AttachmentPointQuery denoptim.graph.AttachmentPointQuery.linkedAPQuery = null private
Query defining the attachment point linked by an edge to the target attachment point, or null.
Definition at line 55 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
vertexQuery
VertexQuery denoptim.graph.AttachmentPointQuery.vertexQuery = null private
Query on vertex owning the target attachment point, or null.
Definition at line 44 of file AttachmentPointQuery.java.
Referenced by denoptim.graph.AttachmentPointQuery.AttachmentPointQuery(), and denoptim.graph.AttachmentPointQuery.matches().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/AttachmentPointQuery.java