DENOPTIM: denoptim.gui.GUIPrepare Class Reference
denoptim.gui.GUIPrepare Class Reference
Class representing the general structure of a form including a specific set of parameter collections.
Public Member Functions
GUIPrepare (GUIMainPanel mainPanel, String newPanelName)
Constructor.
File prepareWorkSpace () throws DENOPTIMException
void importParametersFromDenoptimParamsFile (File file)
boolean hasUnsavedChanges ()
Check whether any of the parameter forms (i.e., a tab) in this list of tabs has unsaved changes.
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Public Attributes
ArrayList< IParametersForm > allParams
Storage of parameters.
Protected Attributes
JTabbedPane tabbedPane
Parameters for the various components are divided in TABs.
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Private Member Functions
void initialize ()
Initialize the panel with tabbedPane and buttons.
FileFormat getFileFormat (String string)
RunType getAchronimFromClass ()
File instantiateParametersFile (File wrkSpace)
boolean printAllParamsToFile (File outFile)
ProgramTask buildProgramTask (File configFile, File workDir) throws DENOPTIMException
The type of main to run is determined by which subclass calls this method.
Static Private Attributes
static final long serialVersionUID = 6481647840284906676L
Version UID.
Detailed Description
Class representing the general structure of a form including a specific set of parameter collections.
Each parameter collection is a tab in a set of tabs (i.e., a tabbed pane).
Author
Marco Foscato
Definition at line 58 of file GUIPrepare.java.
Constructor & Destructor Documentation
GUIPrepare()
denoptim.gui.GUIPrepare.GUIPrepare (GUIMainPanel mainPanel, String newPanelName)
Constructor.
Definition at line 79 of file GUIPrepare.java.
References denoptim.gui.GUIPrepare.initialize(), and denoptim.gui.GUICardPanel.mainPanel.
Member Function Documentation
buildProgramTask()
ProgramTask denoptim.gui.GUIPrepare.buildProgramTask (File configFile, File workDir) throws DENOPTIMException private
The type of main to run is determined by which subclass calls this method.
Parameters
configFile the file containing the configuration parameter for the program to run.
workDir the file system location from which to run the program.
Exceptions
DENOPTIMException
Definition at line 408 of file GUIPrepare.java.
Referenced by denoptim.gui.GUIPrepare.initialize().
getAchronimFromClass()
RunType denoptim.gui.GUIPrepare.getAchronimFromClass () private
Definition at line 316 of file GUIPrepare.java.
References denoptim.main.Main.RunType.FIT, denoptim.main.Main.RunType.FSE, and denoptim.main.Main.RunType.GA.
Referenced by denoptim.gui.GUIPrepare.instantiateParametersFile(), and denoptim.gui.GUIPrepare.prepareWorkSpace().
getFileFormat()
FileFormat denoptim.gui.GUIPrepare.getFileFormat (String string) private
Definition at line 262 of file GUIPrepare.java.
References denoptim.files.FileFormat.FSE_PARAM, denoptim.files.FileFormat.GA_PARAM, and denoptim.files.FileFormat.GA_RUN.
Referenced by denoptim.gui.GUIPrepare.initialize().
hasUnsavedChanges()
boolean denoptim.gui.GUIPrepare.hasUnsavedChanges ()
Check whether any of the parameter forms (i.e., a tab) in this list of tabs has unsaved changes.
Returns
true if there are unsaved changes to the forms.
Reimplemented from denoptim.gui.GUICardPanel.
Definition at line 480 of file GUIPrepare.java.
References denoptim.gui.GUIPrepare.allParams.
importParametersFromDenoptimParamsFile()
void denoptim.gui.GUIPrepare.importParametersFromDenoptimParamsFile (File file)
Definition at line 437 of file GUIPrepare.java.
References denoptim.gui.GUIPrepare.allParams.
Referenced by denoptim.gui.GUIPrepare.initialize(), and denoptim.gui.MainToolBar.openFile().
initialize()
void denoptim.gui.GUIPrepare.initialize () private
Initialize the panel with tabbedPane and buttons.
Reimplemented in denoptim.gui.GUIPrepareFitnessRunner, denoptim.gui.GUIPrepareFSERun, and denoptim.gui.GUIPrepareGARun.
Definition at line 90 of file GUIPrepare.java.
References denoptim.gui.ButtonsBar.add(), denoptim.files.FileUtils.addToRecentFiles(), denoptim.gui.GUIPrepare.allParams, denoptim.gui.GUIPrepare.buildProgramTask(), denoptim.gui.GUIPrepare.getFileFormat(), denoptim.task.StaticTaskManager.getQueueSnapshot(), denoptim.gui.GUIPrepare.importParametersFromDenoptimParamsFile(), denoptim.gui.GUIPrepare.instantiateParametersFile(), denoptim.gui.GUIFileOpener.pickFile(), denoptim.gui.GUIFileOpener.pickFileForSaving(), denoptim.gui.GUIPrepare.prepareWorkSpace(), denoptim.gui.GUIPrepare.printAllParamsToFile(), denoptim.task.StaticTaskManager.submit(), and denoptim.gui.GUIPrepare.tabbedPane.
Referenced by denoptim.gui.GUIPrepare.GUIPrepare().
instantiateParametersFile()
File denoptim.gui.GUIPrepare.instantiateParametersFile (File wrkSpace) private
Definition at line 334 of file GUIPrepare.java.
References denoptim.gui.GUIPrepare.getAchronimFromClass().
Referenced by denoptim.gui.GUIPrepare.initialize().
prepareWorkSpace()
File denoptim.gui.GUIPrepare.prepareWorkSpace () throws DENOPTIMException
Definition at line 427 of file GUIPrepare.java.
References denoptim.files.FileUtils.createDirectory(), denoptim.gui.GUIPrepare.getAchronimFromClass(), denoptim.files.FileUtils.getAvailableFileName(), and denoptim.gui.GUIPreferences.tmpSpace.
Referenced by denoptim.gui.GUIPrepare.initialize().
printAllParamsToFile()
boolean denoptim.gui.GUIPrepare.printAllParamsToFile (File outFile) private
Parameters
task that will make use of the parameters printed by this method.
outFile where we'll try to print the parameters.
Returns
false if we could not produce the file
Definition at line 349 of file GUIPrepare.java.
References denoptim.gui.GUIPrepare.allParams.
Referenced by denoptim.gui.GUIPrepare.initialize().
Member Data Documentation
allParams
ArrayList<IParametersForm> denoptim.gui.GUIPrepare.allParams
Storage of parameters.
Definition at line 74 of file GUIPrepare.java.
Referenced by denoptim.gui.GUIPrepare.hasUnsavedChanges(), denoptim.gui.GUIPrepare.importParametersFromDenoptimParamsFile(), denoptim.gui.GUIPrepare.initialize(), and denoptim.gui.GUIPrepare.printAllParamsToFile().
serialVersionUID
final long denoptim.gui.GUIPrepare.serialVersionUID = 6481647840284906676L static private
Version UID.
Definition at line 64 of file GUIPrepare.java.
tabbedPane
JTabbedPane denoptim.gui.GUIPrepare.tabbedPane protected
Parameters for the various components are divided in TABs.
Definition at line 69 of file GUIPrepare.java.
Referenced by denoptim.gui.GUIPrepare.initialize().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIPrepare.java