DENOPTIM: denoptim.utils.ManySMARTSQuery Class Reference
denoptim.utils.ManySMARTSQuery Class Reference
Container of lists of atoms matching a list of SMARTS.
Public Member Functions
ManySMARTSQuery (IAtomContainer mol, Map< String, String > smarts)
boolean hasProblems ()
Throwable getProblem ()
String getMessage ()
Map< String, Mappings > getAllMatches ()
int getNumMatchesOfQuery (String query)
Mappings getMatchesOfSMARTS (String ref)
Private Attributes
Map< String, Mappings > allMatches = new HashMap<>()
Map< String, Integer > numMatches = new HashMap<>()
Throwable problem
boolean problems = false
String message = ""
Detailed Description
Container of lists of atoms matching a list of SMARTS.
Author
Marco Foscato
Definition at line 36 of file ManySMARTSQuery.java.
Constructor & Destructor Documentation
ManySMARTSQuery()
denoptim.utils.ManySMARTSQuery.ManySMARTSQuery (IAtomContainer mol, Map< String, String > smarts)
Definition at line 51 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.allMatches, denoptim.utils.MoleculeUtils.ensureNoUnsetBondOrdersSilent(), denoptim.utils.ManySMARTSQuery.message, denoptim.utils.ManySMARTSQuery.numMatches, denoptim.utils.ManySMARTSQuery.problem, denoptim.utils.ManySMARTSQuery.problems, and denoptim.utils.MoleculeUtils.setZeroImplicitHydrogensToAllAtoms().
Member Function Documentation
getAllMatches()
Map< String, Mappings > denoptim.utils.ManySMARTSQuery.getAllMatches ()
Definition at line 115 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.allMatches.
Referenced by denoptim.fragmenter.FragmenterTools.filterStrucutresBySMARTS(), and denoptim.fitness.FitnessProvider.getFitness().
getMatchesOfSMARTS()
Mappings denoptim.utils.ManySMARTSQuery.getMatchesOfSMARTS (String ref)
Definition at line 129 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.allMatches.
Referenced by denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.programs.fragmenter.CuttingRule.satisfiesOptions(), and denoptim.ga.EAUtils.searchRingFusionSites().
getMessage()
String denoptim.utils.ManySMARTSQuery.getMessage ()
Definition at line 108 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.message.
Referenced by denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.graph.rings.PathClosabilityTools.evaluateConstitutionalClosability(), denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.fragmenter.FragmenterTools.filterStrucutresBySMARTS(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.programs.fragmenter.CuttingRule.satisfiesOptions(), and denoptim.ga.EAUtils.searchRingFusionSites().
getNumMatchesOfQuery()
int denoptim.utils.ManySMARTSQuery.getNumMatchesOfQuery (String query)
Definition at line 122 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.numMatches.
Referenced by denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.graph.rings.PathClosabilityTools.evaluateConstitutionalClosability(), denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.programs.fragmenter.CuttingRule.satisfiesOptions(), and denoptim.ga.EAUtils.searchRingFusionSites().
getProblem()
Throwable denoptim.utils.ManySMARTSQuery.getProblem ()
Definition at line 101 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.problem.
Referenced by denoptim.fragmenter.FragmenterTools.filterStrucutresBySMARTS(), and denoptim.fitness.FitnessProvider.getFitness().
hasProblems()
boolean denoptim.utils.ManySMARTSQuery.hasProblems ()
Definition at line 94 of file ManySMARTSQuery.java.
References denoptim.utils.ManySMARTSQuery.problems.
Referenced by denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.graph.rings.PathClosabilityTools.evaluateConstitutionalClosability(), denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.fragmenter.FragmenterTools.filterStrucutresBySMARTS(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.programs.fragmenter.CuttingRule.satisfiesOptions(), and denoptim.ga.EAUtils.searchRingFusionSites().
Member Data Documentation
allMatches
Map<String,Mappings> denoptim.utils.ManySMARTSQuery.allMatches = new HashMap<>() private
Definition at line 39 of file ManySMARTSQuery.java.
Referenced by denoptim.utils.ManySMARTSQuery.getAllMatches(), denoptim.utils.ManySMARTSQuery.getMatchesOfSMARTS(), and denoptim.utils.ManySMARTSQuery.ManySMARTSQuery().
message
String denoptim.utils.ManySMARTSQuery.message = "" private
Definition at line 47 of file ManySMARTSQuery.java.
Referenced by denoptim.utils.ManySMARTSQuery.getMessage(), and denoptim.utils.ManySMARTSQuery.ManySMARTSQuery().
numMatches
Map<String,Integer> denoptim.utils.ManySMARTSQuery.numMatches = new HashMap<>() private
Definition at line 42 of file ManySMARTSQuery.java.
Referenced by denoptim.utils.ManySMARTSQuery.getNumMatchesOfQuery(), and denoptim.utils.ManySMARTSQuery.ManySMARTSQuery().
problem
Throwable denoptim.utils.ManySMARTSQuery.problem private
Definition at line 45 of file ManySMARTSQuery.java.
Referenced by denoptim.utils.ManySMARTSQuery.getProblem(), and denoptim.utils.ManySMARTSQuery.ManySMARTSQuery().
problems
boolean denoptim.utils.ManySMARTSQuery.problems = false private
Definition at line 46 of file ManySMARTSQuery.java.
Referenced by denoptim.utils.ManySMARTSQuery.hasProblems(), and denoptim.utils.ManySMARTSQuery.ManySMARTSQuery().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/utils/ManySMARTSQuery.java