DENOPTIM: denoptim.utils.TaskUtils Class Reference
denoptim.utils.TaskUtils Class Reference
Utilities for tasks.
Static Public Member Functions
static synchronized int getUniqueTaskIndex ()
Unique counter for tasks.
Static Private Attributes
static AtomicInteger taskCounter = new AtomicInteger(1)
Detailed Description
Utilities for tasks.
Author
Marco Foscato
Definition at line 30 of file TaskUtils.java.
Member Function Documentation
getUniqueTaskIndex()
static synchronized int denoptim.utils.TaskUtils.getUniqueTaskIndex () static
Unique counter for tasks.
Returns
the new task id (number)
Definition at line 41 of file TaskUtils.java.
References denoptim.utils.TaskUtils.taskCounter.
Referenced by denoptim.fragmenter.ConformerExtractorTask.ConformerExtractorTask(), denoptim.task.FitnessTask.FitnessTask(), denoptim.fragmenter.FragmenterTask.FragmenterTask(), and denoptim.task.ProgramTask.ProgramTask().
Member Data Documentation
taskCounter
AtomicInteger denoptim.utils.TaskUtils.taskCounter = new AtomicInteger(1) static private
Definition at line 32 of file TaskUtils.java.
Referenced by denoptim.utils.TaskUtils.getUniqueTaskIndex().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/utils/TaskUtils.java