DENOPTIM: denoptim.integration.tinker.TinkerMolecule Class Reference
denoptim.integration.tinker.TinkerMolecule Class Reference
Public Member Functions
TinkerMolecule ()
TinkerMolecule (String molName, ArrayList< int[]> zadd, ArrayList< int[]> zdel, ArrayList< TinkerAtom > lstAtoms)
ArrayList< Integer > getConnectedAtoms (int pos)
Identify the list of connected atoms (only first neighbours are considered) to the atom at the specified position.
void set3DCoordinates (ArrayList< double[]> coords)
store 3d coordinates of the fragments
void setName (String molName)
void setAtoms (ArrayList< TinkerAtom > lstAtoms)
void setBondPairs (ArrayList< int[]> zdel, ArrayList< int[]> zadd)
ArrayList< TinkerAtom > getAtoms ()
int getLastAtomNumber ()
String getName ()
ArrayList< int[]> getBondAdd ()
ArrayList< int[]> getBondDel ()
TinkerAtom getAtom (int pos)
Returns the atom which has the XYZ index set to pos.
Object clone () throws CloneNotSupportedException
This method produces a shallow copy of the object.
TinkerMolecule deepCopy ()
This method produces a deep copy of the object.
boolean isConnected (int atm1, int atm2)
void addMolecule (TinkerMolecule tmol2)
void addAtom (TinkerAtom ta)
Add one atom to this molecule.
void addBond (int a1, int a2)
Add one bond by appending a pair of indeces into the z-add section.
boolean isTorsionUsed (int t1, int t2)
Check if the pair of atoms has been used to define a proper torsion.
void printIC ()
Package Attributes
ArrayList< int[]> zdel
ArrayList< int[]> zadd
String molName
Private Attributes
ArrayList< TinkerAtom > lstAtoms
boolean debug = false
Detailed Description
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 30 of file TinkerMolecule.java.
Constructor & Destructor Documentation
TinkerMolecule() [1/2]
denoptim.integration.tinker.TinkerMolecule.TinkerMolecule ()
Definition at line 41 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms, denoptim.integration.tinker.TinkerMolecule.molName, denoptim.integration.tinker.TinkerMolecule.zadd, and denoptim.integration.tinker.TinkerMolecule.zdel.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy().
TinkerMolecule() [2/2]
denoptim.integration.tinker.TinkerMolecule.TinkerMolecule (String molName, ArrayList< int[]> zadd, ArrayList< int[]> zdel, ArrayList< TinkerAtom > lstAtoms)
Definition at line 51 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms, denoptim.integration.tinker.TinkerMolecule.molName, denoptim.integration.tinker.TinkerMolecule.zadd, and denoptim.integration.tinker.TinkerMolecule.zdel.
Member Function Documentation
addAtom()
void denoptim.integration.tinker.TinkerMolecule.addAtom (TinkerAtom ta)
Add one atom to this molecule.
Definition at line 287 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms.
Referenced by denoptim.integration.tinker.TinkerUtils.getICFromIAC().
addBond()
void denoptim.integration.tinker.TinkerMolecule.addBond (int a1, int a2)
Add one bond by appending a pair of indeces into the z-add section.
Parameters
a1 first atom index
a2 second atom index
Definition at line 299 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.zadd.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.addBond(), and denoptim.integration.tinker.TinkerUtils.getICFromIAC().
addMolecule()
void denoptim.integration.tinker.TinkerMolecule.addMolecule (TinkerMolecule tmol2)
Definition at line 272 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.getAtoms(), denoptim.integration.tinker.TinkerMolecule.getBondAdd(), denoptim.integration.tinker.TinkerMolecule.getBondDel(), denoptim.integration.tinker.TinkerMolecule.lstAtoms, denoptim.integration.tinker.TinkerMolecule.zadd, and denoptim.integration.tinker.TinkerMolecule.zdel.
clone()
Object denoptim.integration.tinker.TinkerMolecule.clone () throws CloneNotSupportedException
This method produces a shallow copy of the object.
Definition at line 200 of file TinkerMolecule.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.deepcopy().
deepCopy()
TinkerMolecule denoptim.integration.tinker.TinkerMolecule.deepCopy ()
This method produces a deep copy of the object.
Definition at line 210 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerAtom.getAtomNeighbours(), denoptim.integration.tinker.TinkerAtom.getAtomString(), denoptim.integration.tinker.TinkerAtom.getAtomType(), denoptim.integration.tinker.TinkerAtom.getDistAngle(), denoptim.integration.tinker.TinkerAtom.getVertexId(), denoptim.integration.tinker.TinkerAtom.getXYZ(), denoptim.integration.tinker.TinkerMolecule.molName, denoptim.integration.tinker.TinkerAtom.setVertexId(), denoptim.integration.tinker.TinkerMolecule.TinkerMolecule(), denoptim.integration.tinker.TinkerMolecule.zadd, and denoptim.integration.tinker.TinkerMolecule.zdel.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.deepcopy().
getAtom()
TinkerAtom denoptim.integration.tinker.TinkerMolecule.getAtom (int pos)
Returns the atom which has the XYZ index set to pos.
Parameters
pos
Returns
the TinkerAtom at the specified position
Definition at line 181 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerAtom.getXYZIndex(), and denoptim.integration.tinker.TinkerMolecule.lstAtoms.
Referenced by denoptim.integration.tinker.TinkerMolecule.getConnectedAtoms(), denoptim.integration.tinker.TinkerMolecule.isConnected(), denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getAtoms()
ArrayList< TinkerAtom > denoptim.integration.tinker.TinkerMolecule.getAtoms ()
Definition at line 140 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms.
Referenced by denoptim.integration.tinker.TinkerMolecule.addMolecule(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getBondAdd()
ArrayList< int[]> denoptim.integration.tinker.TinkerMolecule.getBondAdd ()
Definition at line 161 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.zadd.
Referenced by denoptim.integration.tinker.TinkerMolecule.addMolecule().
getBondDel()
ArrayList< int[]> denoptim.integration.tinker.TinkerMolecule.getBondDel ()
Definition at line 168 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.zdel.
Referenced by denoptim.integration.tinker.TinkerMolecule.addMolecule().
getConnectedAtoms()
ArrayList< Integer > denoptim.integration.tinker.TinkerMolecule.getConnectedAtoms (int pos)
Identify the list of connected atoms (only first neighbours are considered) to the atom at the specified position.
Parameters
pos
Returns
list of connected atoms
Definition at line 70 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.getAtom(), denoptim.integration.tinker.TinkerAtom.getAtomNeighbours(), denoptim.integration.tinker.TinkerAtom.getXYZIndex(), and denoptim.integration.tinker.TinkerMolecule.lstAtoms.
getLastAtomNumber()
int denoptim.integration.tinker.TinkerMolecule.getLastAtomNumber ()
Definition at line 147 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms.
getName()
String denoptim.integration.tinker.TinkerMolecule.getName ()
Definition at line 154 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.molName.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
isConnected()
boolean denoptim.integration.tinker.TinkerMolecule.isConnected (int atm1, int atm2)
Definition at line 254 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.getAtom(), and denoptim.integration.tinker.TinkerAtom.getAtomNeighbours().
isTorsionUsed()
boolean denoptim.integration.tinker.TinkerMolecule.isTorsionUsed (int t1, int t2)
Check if the pair of atoms has been used to define a proper torsion.
Parameters
t1
t2
Returns
true if the atoms have been used already
Definition at line 316 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.debug, and denoptim.integration.tinker.TinkerMolecule.lstAtoms.
printIC()
void denoptim.integration.tinker.TinkerMolecule.printIC ()
Definition at line 341 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerAtom.getAtomNeighbours(), denoptim.integration.tinker.TinkerAtom.getAtomString(), denoptim.integration.tinker.TinkerAtom.getAtomType(), denoptim.integration.tinker.TinkerAtom.getDistAngle(), denoptim.integration.tinker.TinkerAtom.getXYZIndex(), denoptim.integration.tinker.TinkerMolecule.lstAtoms, and denoptim.integration.tinker.TinkerMolecule.molName.
Referenced by denoptim.integration.tinker.TinkerUtils.getICFromIAC().
set3DCoordinates()
void denoptim.integration.tinker.TinkerMolecule.set3DCoordinates (ArrayList< double[]> coords)
store 3d coordinates of the fragments
Parameters
coords
Definition at line 105 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms, and denoptim.integration.tinker.TinkerAtom.moveTo().
setAtoms()
void denoptim.integration.tinker.TinkerMolecule.setAtoms (ArrayList< TinkerAtom > lstAtoms)
Definition at line 125 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.lstAtoms.
Referenced by denoptim.integration.tinker.TinkerUtils.readTinkerIC().
setBondPairs()
void denoptim.integration.tinker.TinkerMolecule.setBondPairs (ArrayList< int[]> zdel, ArrayList< int[]> zadd)
Definition at line 132 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.zadd, and denoptim.integration.tinker.TinkerMolecule.zdel.
Referenced by denoptim.integration.tinker.TinkerUtils.readTinkerIC().
setName()
void denoptim.integration.tinker.TinkerMolecule.setName (String molName)
Definition at line 118 of file TinkerMolecule.java.
References denoptim.integration.tinker.TinkerMolecule.molName.
Referenced by denoptim.integration.tinker.TinkerUtils.readTinkerIC().
Member Data Documentation
debug
boolean denoptim.integration.tinker.TinkerMolecule.debug = false private
Definition at line 37 of file TinkerMolecule.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.isTorsionUsed().
lstAtoms
ArrayList<TinkerAtom> denoptim.integration.tinker.TinkerMolecule.lstAtoms private
Definition at line 32 of file TinkerMolecule.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.addAtom(), denoptim.integration.tinker.TinkerMolecule.addMolecule(), denoptim.integration.tinker.TinkerMolecule.getAtom(), denoptim.integration.tinker.TinkerMolecule.getAtoms(), denoptim.integration.tinker.TinkerMolecule.getConnectedAtoms(), denoptim.integration.tinker.TinkerMolecule.getLastAtomNumber(), denoptim.integration.tinker.TinkerMolecule.isTorsionUsed(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.integration.tinker.TinkerMolecule.set3DCoordinates(), denoptim.integration.tinker.TinkerMolecule.setAtoms(), and denoptim.integration.tinker.TinkerMolecule.TinkerMolecule().
molName
String denoptim.integration.tinker.TinkerMolecule.molName package
Definition at line 35 of file TinkerMolecule.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.getName(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.integration.tinker.TinkerMolecule.setName(), and denoptim.integration.tinker.TinkerMolecule.TinkerMolecule().
zadd
ArrayList<int[]> denoptim.integration.tinker.TinkerMolecule.zadd package
Definition at line 34 of file TinkerMolecule.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.addBond(), denoptim.integration.tinker.TinkerMolecule.addMolecule(), denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.getBondAdd(), denoptim.integration.tinker.TinkerMolecule.setBondPairs(), and denoptim.integration.tinker.TinkerMolecule.TinkerMolecule().
zdel
ArrayList<int[]> denoptim.integration.tinker.TinkerMolecule.zdel package
Definition at line 33 of file TinkerMolecule.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.addMolecule(), denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.getBondDel(), denoptim.integration.tinker.TinkerMolecule.setBondPairs(), and denoptim.integration.tinker.TinkerMolecule.TinkerMolecule().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/integration/tinker/TinkerMolecule.java