DENOPTIM: denoptim.fitness.DescriptorUtils Class Reference
denoptim.fitness.DescriptorUtils Class Reference
Static Public Member Functions
static List< String > getAllClassNamesInPackage (String packageName, String jarFileWildQuery)
Search for packages in the class path and in the appended archives.
static List< String > getClassNamesToDenoptimDescriptors ()
static List< String > getClassNamesToCDKDescriptors ()
static DescriptorEngine getCDKDescriptorEngine ()
Makes an engine using CDK descriptors.
static List< DescriptorForFitness > findAllCDKDescriptors (Set< String > requiredDescriptors) throws DENOPTIMException
Searches for descriptor implementations in the CDK packages.
static List< DescriptorForFitness > findAllDENOPTIMDescriptors (Set< String > requiredDescriptors) throws DENOPTIMException
Searches for descriptor implementations in the DENOPTIM packages.
static List< DescriptorForFitness > findAllDescriptorImplementations (Set< String > requiredDescriptors) throws DENOPTIMException
Searches for descriptor implementations.
static List< DescriptorForFitness > findDescriptorImplementations (Set< String > requiredDescriptors, List< String > classNames) throws DENOPTIMException
Searches for descriptor implementations.
Static Private Attributes
static final String FS = System.getProperty("file.separator")
static List< String > rejectedDescriptors
List of descriptor names that are excluded from default import because they have been shown to contain bugs.
Detailed Description
Definition at line 43 of file DescriptorUtils.java.
Member Function Documentation
findAllCDKDescriptors()
static List< DescriptorForFitness > denoptim.fitness.DescriptorUtils.findAllCDKDescriptors (Set< String > requiredDescriptors) throws DENOPTIMException static
Searches for descriptor implementations in the CDK packages.
This method excludes descriptors that have been listed in rejectedDescriptors.
Parameters
requiredDescriptors list of descriptor short names that we want to obtain. All the rest will be ignored. This parameter can be null, in which case we'll return all the descriptors.
Returns
the list of descriptor information bundles.
Exceptions
DENOPTIMException
Definition at line 179 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.findDescriptorImplementations(), and denoptim.fitness.DescriptorUtils.getClassNamesToCDKDescriptors().
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
findAllDENOPTIMDescriptors()
static List< DescriptorForFitness > denoptim.fitness.DescriptorUtils.findAllDENOPTIMDescriptors (Set< String > requiredDescriptors) throws DENOPTIMException static
Searches for descriptor implementations in the DENOPTIM packages.
This method excludes descriptors that have been listed in rejectedDescriptors.
Parameters
requiredDescriptors list of descriptor short names that we want to obtain. All the rest will be ignored. This parameter can be null, in which case we'll return all the descriptors.
Returns
the list of descriptor information bundles.
Exceptions
DENOPTIMException
Definition at line 199 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.findDescriptorImplementations(), and denoptim.fitness.DescriptorUtils.getClassNamesToDenoptimDescriptors().
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
findAllDescriptorImplementations()
static List< DescriptorForFitness > denoptim.fitness.DescriptorUtils.findAllDescriptorImplementations (Set< String > requiredDescriptors) throws DENOPTIMException static
Searches for descriptor implementations.
Searches in both CDK and DENOPTIM packages. This method excludes descriptors that have been listed in rejectedDescriptors.
Parameters
requiredDescriptors list of descriptor short names that we want to obtain. All the rest will be ignored. This parameter can be null, in which case we'll return all the descriptors.
Returns
the list of descriptor information bundles.
Exceptions
DENOPTIMException
Definition at line 219 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.findDescriptorImplementations(), denoptim.fitness.DescriptorUtils.getClassNamesToCDKDescriptors(), and denoptim.fitness.DescriptorUtils.getClassNamesToDenoptimDescriptors().
Referenced by denoptim.fitness.FitnessExpressionParser.parse().
findDescriptorImplementations()
static List< DescriptorForFitness > denoptim.fitness.DescriptorUtils.findDescriptorImplementations (Set< String > requiredDescriptors, List< String > classNames) throws DENOPTIMException static
Searches for descriptor implementations.
This method excludes descriptors that have been listed in rejectedDescriptors.
Parameters
requiredDescriptors list of descriptor short names that we want to obtain. All the rest will be ignored. This parameter can be null, in which case we'll return all the descriptors.
classNames the classnames of the implementations.
Returns
the list of descriptor information bundles.
Exceptions
DENOPTIMException
Definition at line 240 of file DescriptorUtils.java.
References denoptim.fitness.IDenoptimDescriptor.getDictionaryClass(), denoptim.fitness.IDenoptimDescriptor.getDictionaryDefinition(), denoptim.fitness.IDenoptimDescriptor.getDictionaryTitle(), and denoptim.fitness.DescriptorUtils.rejectedDescriptors.
Referenced by denoptim.fitness.DescriptorUtils.findAllCDKDescriptors(), denoptim.fitness.DescriptorUtils.findAllDENOPTIMDescriptors(), and denoptim.fitness.DescriptorUtils.findAllDescriptorImplementations().
getAllClassNamesInPackage()
static List< String > denoptim.fitness.DescriptorUtils.getAllClassNamesInPackage (String packageName, String jarFileWildQuery) static
Search for packages in the class path and in the appended archives.
Parameters
packageName package name that uses '.' as separator.
jarFileWildQuery a query to identify the jar file that should contain the wanter package.
Returns
the list of class names reported in Java format (e.g., 'org.openscience.cdk.qsar.descriptors....'.
Definition at line 64 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.FS.
Referenced by denoptim.fitness.DescriptorUtils.getClassNamesToCDKDescriptors(), and denoptim.fitness.DescriptorUtils.getClassNamesToDenoptimDescriptors().
getCDKDescriptorEngine()
static DescriptorEngine denoptim.fitness.DescriptorUtils.getCDKDescriptorEngine () static
Makes an engine using CDK descriptors.
Returns
an engine using CDK descriptors.
Definition at line 162 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.getClassNamesToCDKDescriptors().
getClassNamesToCDKDescriptors()
static List< String > denoptim.fitness.DescriptorUtils.getClassNamesToCDKDescriptors () static
Definition at line 150 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.getAllClassNamesInPackage().
Referenced by denoptim.fitness.DescriptorUtils.findAllCDKDescriptors(), denoptim.fitness.DescriptorUtils.findAllDescriptorImplementations(), denoptim.fitness.DescriptorUtils.getCDKDescriptorEngine(), and denoptim.fitness.DescriptorUtilsTest.testFindCDKDescriptors().
getClassNamesToDenoptimDescriptors()
static List< String > denoptim.fitness.DescriptorUtils.getClassNamesToDenoptimDescriptors () static
Definition at line 142 of file DescriptorUtils.java.
References denoptim.fitness.DescriptorUtils.getAllClassNamesInPackage().
Referenced by denoptim.fitness.DescriptorUtils.findAllDENOPTIMDescriptors(), denoptim.fitness.DescriptorUtils.findAllDescriptorImplementations(), and denoptim.fitness.DescriptorUtilsTest.testFindDemoptimDescriptors().
Member Data Documentation
FS
final String denoptim.fitness.DescriptorUtils.FS = System.getProperty("file.separator") static private
Definition at line 45 of file DescriptorUtils.java.
Referenced by denoptim.fitness.DescriptorUtils.getAllClassNamesInPackage().
rejectedDescriptors
List<String> denoptim.fitness.DescriptorUtils.rejectedDescriptors static private
Initial value:
= Arrays.asList(
            new String[]{"JPLogP"})
List of descriptor names that are excluded from default import because they have been shown to contain bugs.
Definition at line 51 of file DescriptorUtils.java.
Referenced by denoptim.fitness.DescriptorUtils.findDescriptorImplementations().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fitness/DescriptorUtils.java