DENOPTIM: denoptim.gui.FSParamsDialog Class Reference
denoptim.gui.FSParamsDialog Class Reference
A modal dialog to define a fragment space and load it.
Public Member Functions
FSParamsDialog (Component refForPlacement)
Constructor.
FragmentSpace makeFragSpace () throws Exception
Reads all the parameters, calls the interpreters, and eventually creates the static FragmentSpace object.
Public Member Functions inherited from denoptim.gui.GUIModalDialog
GUIModalDialog (Component refForPlacement)
Constructor.
GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Object showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
void addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
void addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Private Attributes
FSParametersForm fsParsForm
Static Private Attributes
static final long serialVersionUID = 1L
Version ID.
Additional Inherited Members
Protected Member Functions inherited from denoptim.gui.GUIModalDialog
void close ()
Closes the dialog window.
Protected Attributes inherited from denoptim.gui.GUIModalDialog
JButton btnDone
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
JButton btnCanc
The button that is used to close the dialog without processing any input.
JButton btnExtra
The button that can be used for any action that does not close the dialog.
Object result = null
The result to be returned once the dialog is closed.
Detailed Description
A modal dialog to define a fragment space and load it.
Definition at line 36 of file FSParamsDialog.java.
Constructor & Destructor Documentation
FSParamsDialog()
denoptim.gui.FSParamsDialog.FSParamsDialog (Component refForPlacement)
Constructor.
Definition at line 50 of file FSParamsDialog.java.
References denoptim.gui.GUIModalDialog.addToCentralPane(), denoptim.gui.GUIModalDialog.btnCanc, denoptim.gui.GUIModalDialog.btnDone, denoptim.gui.GUIModalDialog.close(), denoptim.gui.FSParamsDialog.fsParsForm, denoptim.gui.FSParamsDialog.makeFragSpace(), and denoptim.gui.FSParametersForm.possiblyReadParamsFromFSParFile().
Member Function Documentation
makeFragSpace()
FragmentSpace denoptim.gui.FSParamsDialog.makeFragSpace () throws Exception
Reads all the parameters, calls the interpreters, and eventually creates the static FragmentSpace object.
Returns
Exceptions
Exception
Definition at line 114 of file FSParamsDialog.java.
References denoptim.fragspace.FragmentSpaceParameters.checkParameters(), denoptim.gui.FSParamsDialog.fsParsForm, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.processParameters(), denoptim.gui.FSParametersForm.putParametersToString(), denoptim.programs.RunTimeParameters.readParameterLine(), and denoptim.gui.FSParametersForm.txtPar1.
Referenced by denoptim.gui.FSParamsDialog.FSParamsDialog(), and denoptim.gui.GUIGraphHandler.loadFragmentSpace().
Member Data Documentation
fsParsForm
FSParametersForm denoptim.gui.FSParamsDialog.fsParsForm private
Definition at line 43 of file FSParamsDialog.java.
Referenced by denoptim.gui.FSParamsDialog.FSParamsDialog(), and denoptim.gui.FSParamsDialog.makeFragSpace().
serialVersionUID
final long denoptim.gui.FSParamsDialog.serialVersionUID = 1L static private
Version ID.
Definition at line 41 of file FSParamsDialog.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/FSParamsDialog.java