DENOPTIM: denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder Class Reference
denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder Class Reference
Builder of molecular models.
Public Member Functions
MolecularModelBuilder (File configFile, File workDir)
Creates and configures the program task.
void runProgram () throws Throwable
Public Member Functions inherited from denoptim.task.ProgramTask
ProgramTask (File configFile, File workDir)
Creates and configures the program task.
Object call ()
This method redirects the callable functionality to an abstract method (namely ProgramTask#runProgram()) to be specified by the implementations of this abstract class.
void printErrorToFile ()
Method that can be called to create a text file with the error triggered by any Throwable that can be thrown by the execution of the program.
Public Member Functions inherited from denoptim.task.Task
Task (final int id)
int getId ()
void setVerbosity (int verbosity)
Set the verbosity: i.e., amount of log printed by this class.
void setWorkSpace (File workDir)
Sets the pathname of the work space, i.e., the location where the task is supposed to use move to or to threat as the result of "pwd" at runtime.
boolean isCompleted ()
boolean foundException ()
Throwable getException ()
String getErrorMessage ()
void stopTask ()
Stop the task if not already completed.
String toString ()
Returns a string identifying this task by its ID and reporting whether an exception has been thrown and if the tasks is completed.
void setNotify (boolean notify)
Additional Inherited Members
Public Attributes inherited from denoptim.task.Task
Object lock = new Object()
Lock for addressing synchronization issues.
Protected Member Functions inherited from denoptim.task.ProgramTask
void handleThrowable ()
Method to handle any Throwable originated from the runProgram() method.
void stopLogger ()
Stops the program-specific logger and releases the lock file on the logfile.
abstract void runProgram () throws Throwable
Protected Attributes inherited from denoptim.task.ProgramTask
File configFilePathName
File containing configuration parameters for the program task.
String loggerIdentifier = "none"
Identifier of this program's logger.
Protected Attributes inherited from denoptim.task.Task
boolean notifyGlobalTaskManager = false
Flag controlling whether this task is expected to notify the static task manager.
boolean completed = false
Flag about completion.
boolean hasException = false
Flag about exception.
String errMsg = ""
Error message produced by any subtask.
Throwable thrownExc
Exception thrown.
int id
A user-assigned id for this task.
ProcessHandler processHandler
Executor for external bash script.
File workDir
The file system location where we want to be placed when doing the work.
int verbosity = 0
Verbosity level.
final String SEP = System.getProperty("file.separator")
System-dependent file separator.
final String NL = System.getProperty("line.separator")
System-dependent line separator (newline)
Detailed Description
Builder of molecular models.
This program constructs a three-dimensional molecular model by converting a given DENOPTIM Candidate.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 44 of file MolecularModelBuilder.java.
Constructor & Destructor Documentation
MolecularModelBuilder()
denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.MolecularModelBuilder (File configFile, File workDir)
Creates and configures the program task.
Parameters
configFile the file containing the configuration parameters.
workDir the file system location from which to run the program.
Definition at line 54 of file MolecularModelBuilder.java.
References denoptim.task.Task.workDir.
Member Function Documentation
runProgram()
void denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram () throws Throwable
Reimplemented from denoptim.task.ProgramTask.
Definition at line 62 of file MolecularModelBuilder.java.
References denoptim.constants.DENOPTIMConstants.ATMPROPVERTEXID, denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.checkParameters(), denoptim.task.ProgramTask.configFilePathName, denoptim.graph.Candidate.getChemicalRepresentation(), denoptim.graph.Candidate.getGraph(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInputSDFFile(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.Candidate.getName(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getOutputSDFFile(), denoptim.task.ProgramTask.loggerIdentifier, denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.task.Task.NL, denoptim.programs.RunTimeParameters.printParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.processParameters(), denoptim.io.DenoptimIO.readCandidates(), denoptim.programs.RunTimeParameters.readParameterFile(), denoptim.programs.RunTimeParameters.setWorkDirectory(), denoptim.integration.tinker.TinkerException.solution, denoptim.programs.RunTimeParameters.startProgramSpecificLogger(), denoptim.task.Task.workDir, and denoptim.io.DenoptimIO.writeSDFFile().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/moldecularmodelbuilder/MolecularModelBuilder.java