DENOPTIM: denoptim.gui.GUIFileOpener Class Reference
denoptim.gui.GUIFileOpener Class Reference
File opener for DENOPTIM GUI.
Static Public Member Functions
static File pickFileOrFolder (Component parent)
static File pickFileForTxtField (JTextField txtField, Component parent)
static Set< File > pickManyFiles (Component parent)
static File pickFile (Component parent)
static File pickFileWithGraph (Component parent)
static File pickFolderForTxtField (JTextField txtField, Component parent)
static File pickFolder (Component parent)
static File pickFileForSaving (Component parent)
Static Protected Attributes
static JFileChooser fileChooser = new JFileChooser(getSystemRoot())
Static Private Member Functions
static File getSystemRoot ()
Detailed Description
File opener for DENOPTIM GUI.
Definition at line 35 of file GUIFileOpener.java.
Member Function Documentation
getSystemRoot()
static File denoptim.gui.GUIFileOpener.getSystemRoot () static private
Definition at line 41 of file GUIFileOpener.java.
pickFile()
static File denoptim.gui.GUIFileOpener.pickFile (Component parent) static
Definition at line 102 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.GUICompatibilityMatrixTab.initialize(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIPrepare.initialize(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.gui.GUIFileOpener.pickFileForTxtField().
pickFileForSaving()
static File denoptim.gui.GUIFileOpener.pickFileForSaving (Component parent) static
Definition at line 172 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize(), and denoptim.gui.GUIPrepare.initialize().
pickFileForTxtField()
static File denoptim.gui.GUIFileOpener.pickFileForTxtField (JTextField txtField, Component parent) static
Definition at line 68 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.pickFile().
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm(), denoptim.gui.FSEParametersForm.FSEParametersForm(), denoptim.gui.FSParametersForm.FSParametersForm(), denoptim.gui.GAParametersForm.GAParametersForm(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm().
pickFileOrFolder()
static File denoptim.gui.GUIFileOpener.pickFileOrFolder (Component parent) static
Definition at line 53 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.MainToolBar.initialize().
pickFileWithGraph()
static File denoptim.gui.GUIFileOpener.pickFileWithGraph (Component parent) static
Definition at line 118 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
pickFolder()
static File denoptim.gui.GUIFileOpener.pickFolder (Component parent) static
Definition at line 155 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.HomePanel.initialize(), and denoptim.gui.GUIFileOpener.pickFolderForTxtField().
pickFolderForTxtField()
static File denoptim.gui.GUIFileOpener.pickFolderForTxtField (JTextField txtField, Component parent) static
Definition at line 141 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser, and denoptim.gui.GUIFileOpener.pickFolder().
Referenced by denoptim.gui.FSEParametersForm.FSEParametersForm(), and denoptim.gui.FSParametersForm.FSParametersForm().
pickManyFiles()
static Set< File > denoptim.gui.GUIFileOpener.pickManyFiles (Component parent) static
Definition at line 80 of file GUIFileOpener.java.
References denoptim.gui.GUIFileOpener.fileChooser.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
Member Data Documentation
fileChooser
JFileChooser denoptim.gui.GUIFileOpener.fileChooser = new JFileChooser(getSystemRoot()) static protected
Definition at line 37 of file GUIFileOpener.java.
Referenced by denoptim.gui.GUIFileOpener.pickFile(), denoptim.gui.GUIFileOpener.pickFileForSaving(), denoptim.gui.GUIFileOpener.pickFileOrFolder(), denoptim.gui.GUIFileOpener.pickFileWithGraph(), denoptim.gui.GUIFileOpener.pickFolder(), denoptim.gui.GUIFileOpener.pickFolderForTxtField(), and denoptim.gui.GUIFileOpener.pickManyFiles().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIFileOpener.java