DENOPTIM: denoptim.graph.SymmetricSetWithMode Class Reference
denoptim.graph.SymmetricSetWithMode Class Reference
Class coupling a reference to a SymmetricSet with a string that we call "mode" and can is used to store any sort of information.
Public Member Functions
SymmetricSetWithMode (SymmetricSet symItems, String mode)
SymmetricSet<?> getItems ()
boolean equals (Object o)
int hashCode ()
Protected Attributes
SymmetricSet symItems
String mode
Detailed Description
Class coupling a reference to a SymmetricSet with a string that we call "mode" and can is used to store any sort of information.
The use case for this class is to be the identifier for different uses (i.e., different "modes") of the same SymmetricSet. In fact, this class is meant to return the same hash when two instances link to the same SymmetricSet and mode string.
Definition at line 12 of file SymmetricSetWithMode.java.
Constructor & Destructor Documentation
SymmetricSetWithMode()
denoptim.graph.SymmetricSetWithMode.SymmetricSetWithMode (SymmetricSet symItems, String mode)
Definition at line 19 of file SymmetricSetWithMode.java.
References denoptim.graph.SymmetricSetWithMode.mode, and denoptim.graph.SymmetricSetWithMode.symItems.
Referenced by denoptim.graph.SymmetricSetWithMode.equals().
Member Function Documentation
equals()
boolean denoptim.graph.SymmetricSetWithMode.equals (Object o)
Definition at line 38 of file SymmetricSetWithMode.java.
References denoptim.graph.SymmetricSetWithMode.equals(), denoptim.graph.SymmetricSetWithMode.mode, denoptim.graph.SymmetricSetWithMode.symItems, and denoptim.graph.SymmetricSetWithMode.SymmetricSetWithMode().
Referenced by denoptim.graph.SymmetricSetWithMode.equals(), and denoptim.graph.SymmetricSetWithModeTest.testEquals().
getItems()
SymmetricSet<?> denoptim.graph.SymmetricSetWithMode.getItems ()
Returns
the symmetry-related items.
Definition at line 30 of file SymmetricSetWithMode.java.
References denoptim.graph.SymmetricSetWithMode.symItems.
hashCode()
int denoptim.graph.SymmetricSetWithMode.hashCode ()
Definition at line 60 of file SymmetricSetWithMode.java.
References denoptim.graph.SymmetricSetWithMode.mode, and denoptim.graph.SymmetricSetWithMode.symItems.
Referenced by denoptim.graph.SymmetricSetWithModeTest.testHashCode().
Member Data Documentation
mode
String denoptim.graph.SymmetricSetWithMode.mode protected
Definition at line 15 of file SymmetricSetWithMode.java.
Referenced by denoptim.graph.SymmetricSetWithMode.equals(), denoptim.graph.SymmetricSetWithMode.hashCode(), and denoptim.graph.SymmetricSetWithMode.SymmetricSetWithMode().
symItems
SymmetricSet denoptim.graph.SymmetricSetWithMode.symItems protected
Definition at line 14 of file SymmetricSetWithMode.java.
Referenced by denoptim.graph.SymmetricSetWithMode.equals(), denoptim.graph.SymmetricSetWithMode.getItems(), denoptim.graph.SymmetricSetWithMode.hashCode(), and denoptim.graph.SymmetricSetWithMode.SymmetricSetWithMode().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/SymmetricSetWithMode.java