DENOPTIM: denoptim.gui.GraphViewerPanel.JEdge Class Reference
denoptim.gui.GraphViewerPanel.JEdge Class Reference
An edge in the JUNG Graph.
Public Member Functions
JEdge (AttachmentPoint srcAP)
Constructor for a JUNG edge representing a AttachmentPoint.
JEdge (AttachmentPoint srcAP, AttachmentPoint trgAP, String bt)
Constructor for a JUNG edge representing a Edge or a chord that closes a Ring.
Package Attributes
String id = ""
String identifying this edge within a graph.
String srcAPC
String representing the APClass on the source AP of directed edges or on the AP this edge represents.
String trgAPC
String representing the APClass on the target AP of directed edged this JUNG edge represents.
String srcAPID = ""
String representing the index of the source AP in the list of APs of the vertex owning the source AP.
String trgAPID = ""
String representing the index of the target AP in the list of APs of the vertex owning the source AP.
String bt = "none"
The bond type for edges that correspond to connections between Vertexs or "none" when for edges representing AttachmentPoints.
boolean toAp = false
Flag defining whether this edge is representing a AttachmentPoint.
boolean displayAPCs = false
Flag requiring to display APClasses.
boolean displayAPIDs = false
Flag requiring to display APClasses.
boolean displayBndTyp = false
Flag requiring to display Bond type.
Detailed Description
An edge in the JUNG Graph.
It represents any kind of Edge, a chord that closes a Ring, or a free AttachmentPoint.
Definition at line 203 of file GraphViewerPanel.java.
Constructor & Destructor Documentation
JEdge() [1/2]
denoptim.gui.GraphViewerPanel.JEdge.JEdge (AttachmentPoint srcAP)
Constructor for a JUNG edge representing a AttachmentPoint.
Parameters
srcAPC the string representation of the APClass of the AP.
Definition at line 272 of file GraphViewerPanel.java.
References denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getVertexId(), and denoptim.graph.APClass.toString().
JEdge() [2/2]
denoptim.gui.GraphViewerPanel.JEdge.JEdge (AttachmentPoint srcAP, AttachmentPoint trgAP, String bt)
Constructor for a JUNG edge representing a Edge or a chord that closes a Ring.
Parameters
srcAPC the string representation of the APClass of the source AP of directed Edges.
trgAPC the string representation of the APClass of the target AP of directed Edges.
bt the string representation of the bond type in the Edge represented by this JUNG edge.
Definition at line 293 of file GraphViewerPanel.java.
References denoptim.gui.GraphViewerPanel.JEdge.bt, denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getVertexId(), and denoptim.graph.APClass.toString().
Member Data Documentation
bt
String denoptim.gui.GraphViewerPanel.JEdge.bt = "none" package
The bond type for edges that correspond to connections between Vertexs or "none" when for edges representing AttachmentPoints.
Definition at line 243 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply(), and denoptim.gui.GraphViewerPanel.JEdge.JEdge().
displayAPCs
boolean denoptim.gui.GraphViewerPanel.JEdge.displayAPCs = false package
Flag requiring to display APClasses.
Definition at line 254 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
displayAPIDs
boolean denoptim.gui.GraphViewerPanel.JEdge.displayAPIDs = false package
Flag requiring to display APClasses.
Definition at line 259 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
displayBndTyp
boolean denoptim.gui.GraphViewerPanel.JEdge.displayBndTyp = false package
Flag requiring to display Bond type.
Definition at line 264 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
id
String denoptim.gui.GraphViewerPanel.JEdge.id = "" package
String identifying this edge within a graph.
This is not meant to be unique across graphs, but is unique within a graph, provided that the vertex IDs are unique.
Definition at line 210 of file GraphViewerPanel.java.
Referenced by denoptim.gui.JUNGGraphSnapshot.processEdge().
srcAPC
String denoptim.gui.GraphViewerPanel.JEdge.srcAPC package
String representing the APClass on the source AP of directed edges or on the AP this edge represents.
Definition at line 216 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
srcAPID
String denoptim.gui.GraphViewerPanel.JEdge.srcAPID = "" package
String representing the index of the source AP in the list of APs of the vertex owning the source AP.
This property allies only to directed edges
Definition at line 229 of file GraphViewerPanel.java.
toAp
boolean denoptim.gui.GraphViewerPanel.JEdge.toAp = false package
Flag defining whether this edge is representing a AttachmentPoint.
Definition at line 249 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeDrawPaintTransformer.apply(), and denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
trgAPC
String denoptim.gui.GraphViewerPanel.JEdge.trgAPC package
String representing the APClass on the target AP of directed edged this JUNG edge represents.
Definition at line 222 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
trgAPID
String denoptim.gui.GraphViewerPanel.JEdge.trgAPID = "" package
String representing the index of the target AP in the list of APs of the vertex owning the source AP.
This property allies only to directed edges
Definition at line 236 of file GraphViewerPanel.java.
Referenced by denoptim.gui.GraphViewerPanel.EdgeLabelTransformer.apply().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GraphViewerPanel.java