DENOPTIM: denoptim.graph.AttachmentPointQueryTest Class Reference
denoptim.graph.AttachmentPointQueryTest Class Reference
Unit tests for AttachmentPointQuery#matches(AttachmentPoint).
Public Member Functions
void setUp ()
void testMatchesAllNullCriteria ()
void testMatchesAttachmentPointId ()
void testMatchesAttachmentPointIndex ()
void testMatchesAPClass () throws DENOPTIMException
void testMatchesNestedVertexQuery ()
void testMatchesNestedEdgeQuery ()
void testEmptyEdgeQueryRequiresEdge ()
void testLinkedAPQuery ()
void testFindAPsUsesMatches () throws DENOPTIMException
Private Attributes
DGraph graph
Vertex v1
Vertex v3
AttachmentPoint v1Ap0
AttachmentPoint v1Ap1
AttachmentPoint v3Ap0
Detailed Description
Unit tests for AttachmentPointQuery#matches(AttachmentPoint).
Definition at line 31 of file AttachmentPointQueryTest.java.
Member Function Documentation
setUp()
void denoptim.graph.AttachmentPointQueryTest.setUp ()
Definition at line 41 of file AttachmentPointQueryTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.AttachmentPointQueryTest.graph, denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.AttachmentPointQueryTest.v1, denoptim.graph.AttachmentPointQueryTest.v1Ap0, denoptim.graph.AttachmentPointQueryTest.v1Ap1, denoptim.graph.AttachmentPointQueryTest.v3, and denoptim.graph.AttachmentPointQueryTest.v3Ap0.
testEmptyEdgeQueryRequiresEdge()
void denoptim.graph.AttachmentPointQueryTest.testEmptyEdgeQueryRequiresEdge ()
Definition at line 134 of file AttachmentPointQueryTest.java.
References denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.AttachmentPointQueryTest.graph, and denoptim.graph.AttachmentPointQuery.matches().
testFindAPsUsesMatches()
void denoptim.graph.AttachmentPointQueryTest.testFindAPsUsesMatches () throws DENOPTIMException
Definition at line 201 of file AttachmentPointQueryTest.java.
References denoptim.graph.DGraph.findAPs(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.AttachmentPointQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.AttachmentPointQuery.matches().
testLinkedAPQuery()
void denoptim.graph.AttachmentPointQueryTest.testLinkedAPQuery ()
Definition at line 164 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getID(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.AttachmentPointQueryTest.graph, and denoptim.graph.AttachmentPointQuery.matches().
testMatchesAllNullCriteria()
void denoptim.graph.AttachmentPointQueryTest.testMatchesAllNullCriteria ()
Definition at line 54 of file AttachmentPointQueryTest.java.
References denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.AttachmentPointQueryTest.graph, and denoptim.graph.AttachmentPointQuery.matches().
testMatchesAPClass()
void denoptim.graph.AttachmentPointQueryTest.testMatchesAPClass () throws DENOPTIMException
Definition at line 89 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.AttachmentPointQueryTest.v1Ap0, and denoptim.graph.AttachmentPointQueryTest.v3Ap0.
testMatchesAttachmentPointId()
void denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointId ()
Definition at line 67 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPoint.getID(), denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.AttachmentPointQueryTest.v1Ap0, and denoptim.graph.AttachmentPointQueryTest.v1Ap1.
testMatchesAttachmentPointIndex()
void denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointIndex ()
Definition at line 78 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.AttachmentPointQueryTest.v1Ap0, and denoptim.graph.AttachmentPointQueryTest.v1Ap1.
testMatchesNestedEdgeQuery()
void denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery ()
Definition at line 114 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.AttachmentPointQueryTest.graph, denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.EdgeQuery.matches(), denoptim.graph.Edge.BondType.TRIPLE, denoptim.graph.AttachmentPointQueryTest.v1, denoptim.graph.AttachmentPointQueryTest.v1Ap0, and denoptim.graph.AttachmentPointQueryTest.v1Ap1.
testMatchesNestedVertexQuery()
void denoptim.graph.AttachmentPointQueryTest.testMatchesNestedVertexQuery ()
Definition at line 100 of file AttachmentPointQueryTest.java.
References denoptim.graph.AttachmentPointQuery.matches(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.AttachmentPointQueryTest.v1Ap0, and denoptim.graph.AttachmentPointQueryTest.v3Ap0.
Member Data Documentation
graph
DGraph denoptim.graph.AttachmentPointQueryTest.graph private
Definition at line 33 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), denoptim.graph.AttachmentPointQueryTest.testEmptyEdgeQueryRequiresEdge(), denoptim.graph.AttachmentPointQueryTest.testFindAPsUsesMatches(), denoptim.graph.AttachmentPointQueryTest.testLinkedAPQuery(), denoptim.graph.AttachmentPointQueryTest.testMatchesAllNullCriteria(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery().
v1
Vertex denoptim.graph.AttachmentPointQueryTest.v1 private
Definition at line 34 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery().
v1Ap0
AttachmentPoint denoptim.graph.AttachmentPointQueryTest.v1Ap0 private
Definition at line 36 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), denoptim.graph.AttachmentPointQueryTest.testMatchesAPClass(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointId(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointIndex(), denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedVertexQuery().
v1Ap1
AttachmentPoint denoptim.graph.AttachmentPointQueryTest.v1Ap1 private
Definition at line 37 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointId(), denoptim.graph.AttachmentPointQueryTest.testMatchesAttachmentPointIndex(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedEdgeQuery().
v3
Vertex denoptim.graph.AttachmentPointQueryTest.v3 private
Definition at line 35 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp().
v3Ap0
AttachmentPoint denoptim.graph.AttachmentPointQueryTest.v3Ap0 private
Definition at line 38 of file AttachmentPointQueryTest.java.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), denoptim.graph.AttachmentPointQueryTest.testMatchesAPClass(), and denoptim.graph.AttachmentPointQueryTest.testMatchesNestedVertexQuery().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/AttachmentPointQueryTest.java