DENOPTIM: denoptim.main.MainTest Class Reference
denoptim.main.MainTest Class Reference
Public Member Functions
void testDefineProgramBehavior () throws Exception
Package Attributes
File tempDir
Private Attributes
final String SEP = System.getProperty("file.separator")
Detailed Description
Definition at line 35 of file MainTest.java.
Member Function Documentation
testDefineProgramBehavior()
void denoptim.main.MainTest.testDefineProgramBehavior () throws Exception
Definition at line 45 of file MainTest.java.
References denoptim.main.Behavior.cmd, denoptim.main.Main.defineProgramBehavior(), denoptim.main.Behavior.errorMsg, denoptim.main.Behavior.exitStatus, denoptim.main.Main.RunType.FSE, denoptim.main.Main.RunType.GA, denoptim.programs.RunTimeParameters.ParametersType.GA_PARAMS, denoptim.main.Main.RunType.GUI, denoptim.main.CLIOptions.help, denoptim.main.Behavior.helpMsg, denoptim.main.CLIOptions.run, denoptim.main.Behavior.runType, denoptim.main.MainTest.SEP, denoptim.main.MainTest.tempDir, denoptim.logging.Version.VERSION, denoptim.main.CLIOptions.version, and denoptim.io.DenoptimIO.writeData().
Member Data Documentation
SEP
final String denoptim.main.MainTest.SEP = System.getProperty("file.separator") private
Definition at line 37 of file MainTest.java.
Referenced by denoptim.main.MainTest.testDefineProgramBehavior().
tempDir
File denoptim.main.MainTest.tempDir package
Definition at line 40 of file MainTest.java.
Referenced by denoptim.main.MainTest.testDefineProgramBehavior().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/main/MainTest.java