DENOPTIM: denoptim.utils.MathUtils Class Reference
denoptim.utils.MathUtils Class Reference
Some useful math operations.
Static Public Member Functions
static double calculateAngle (double[] a, double[] b)
compute the angle between two vectors a & b of same length
static void norm (double[] d, double[] ret)
Normalizes a vector.
static Vector3d normDist (Point3d p1, Point3d p2)
Get normalized distance between two point.
static double[] scale (double[] d, double a)
Scales a vector.
static void scalar (double[] d, double a, double[] ret)
Scales a vector.
static double length (double[] v)
Return the norm of a vector.
static double computeDotProduct (double[] v0, double[] v1)
Compute the dot product (a scalar) between two vectors.
static double[] computeCrossProduct (double[] v0, double[] v1)
Compute the cross product of two vectors.
static double[] subtract (double[] v0, double[] v1)
Perform vector subtraction.
static double[] add (double[] v0, double[] v1)
Perform vector addition.
static double computeDihedralAngle (Point3d p0, Point3d p1, Point3d p2, Point3d p3)
Compute the dihedral angle.
static double computeDihedralAngle (double[] v0, double[] v1, double[] v2, double[] v3)
Compute the dihedral angle.
static double log2 (double x)
static double roundValue (double val, int decimalPlaces)
static double angle (Point3d a, Point3d b, Point3d c)
Calculate the angle between the 3 points.
static double getAngle (double[] A, double[] B, double[] C)
Calculates angle (in degrees) between vectors BA and BC.
static double distance (Point3d a, Point3d b)
Calculates distance between point a and point b.
static double torsion (Point3d p1, Point3d p2, Point3d p3, Point3d p4)
Calculate the torsion angle between the 4 points.
static double sum (double[] a)
Return sum of all values in array.
static double mean (double[] a)
Calculate mean value.
static double mean (List< Double > vals)
static Vector3d getNormalDirection (Vector3d vecA)
Generate a vector that is perpendicular to the given one.
static double[] centroidOf (Collection< double[]> points, int dimension)
Static Private Attributes
static final double[] tp1 = new double[3]
static final double[] tp2 = new double[3]
static final double[] tp3 = new double[3]
static final double[] tp4 = new double[3]
Detailed Description
Some useful math operations.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 38 of file MathUtils.java.
Member Function Documentation
add()
static double[] denoptim.utils.MathUtils.add (double[] v0, double[] v1) static
Perform vector addition.
Parameters
v0 First vector
v1 Second vector
Returns
v0 + v1
Definition at line 198 of file MathUtils.java.
Referenced by denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer().
angle()
static double denoptim.utils.MathUtils.angle (Point3d a, Point3d b, Point3d c) static
Calculate the angle between the 3 points.
Parameters
a
b
c
Returns
angle calculated
Definition at line 284 of file MathUtils.java.
References denoptim.utils.MathUtils.angle(), and denoptim.constants.DENOPTIMConstants.FLOATCOMPARISONTOLERANCE.
Referenced by denoptim.utils.DummyAtomHandler.addDummiesOnLinearities(), denoptim.utils.MathUtils.angle(), denoptim.utils.MathUtils.calculateAngle(), denoptim.graph.rings.RingClosureFinder.evaluateClosability(), denoptim.integration.tinker.TinkerUtils.getICFromIAC(), and denoptim.integration.tinker.TinkerUtils.getThirdRefAtomId().
calculateAngle()
static double denoptim.utils.MathUtils.calculateAngle (double[] a, double[] b) static
compute the angle between two vectors a & b of same length
Parameters
a
b
Returns
angle in degrees
Definition at line 51 of file MathUtils.java.
References denoptim.utils.MathUtils.angle(), denoptim.utils.MathUtils.computeDotProduct(), and denoptim.utils.MathUtils.length().
Referenced by denoptim.utils.MathUtils.getAngle().
centroidOf()
static double[] denoptim.utils.MathUtils.centroidOf (Collection< double[]> points, int dimension) static
Definition at line 457 of file MathUtils.java.
Referenced by denoptim.fragmenter.DynamicCentroidCluster.getCentroid(), and denoptim.fragmenter.FragmentClusterer.getRMSDStatsOfNoisyDistorsions().
computeCrossProduct()
static double[] denoptim.utils.MathUtils.computeCrossProduct (double[] v0, double[] v1) static
Compute the cross product of two vectors.
Result is a vector
Parameters
v0 First vector
v1 Second vector
Returns
crossProduct Cross product of vectors [x,y,z].
Definition at line 162 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.computeDihedralAngle().
computeDihedralAngle() [1/2]
static double denoptim.utils.MathUtils.computeDihedralAngle (double[] v0, double[] v1, double[] v2, double[] v3) static
Compute the dihedral angle.
Parameters
v0 3D coordinates
v1 3D coordinates
v2 3D coordinates
v3 3D coordinates
Returns
angle
Definition at line 241 of file MathUtils.java.
References denoptim.utils.MathUtils.computeCrossProduct(), denoptim.utils.MathUtils.computeDotProduct(), and denoptim.utils.MathUtils.subtract().
computeDihedralAngle() [2/2]
static double denoptim.utils.MathUtils.computeDihedralAngle (Point3d p0, Point3d p1, Point3d p2, Point3d p3) static
Compute the dihedral angle.
Parameters
p0 point in 3D
p1 point in 3D
p2 point in 3D
p3 point in 3D
Returns
angle
Definition at line 218 of file MathUtils.java.
References denoptim.utils.MathUtils.computeDihedralAngle().
Referenced by denoptim.utils.MathUtils.computeDihedralAngle(), denoptim.graph.rings.RingClosureFinder.evaluateClosability(), and denoptim.utils.MathUtils.torsion().
computeDotProduct()
static double denoptim.utils.MathUtils.computeDotProduct (double[] v0, double[] v1) static
Compute the dot product (a scalar) between two vectors.
Parameters
v0 First vector
v1 Second vector
Returns
Dot product of given vectors.
Definition at line 148 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.calculateAngle(), and denoptim.utils.MathUtils.computeDihedralAngle().
distance()
static double denoptim.utils.MathUtils.distance (Point3d a, Point3d b) static
Calculates distance between point a and point b.
Parameters
a Point
b Point
Returns
Distance between a and b
Definition at line 342 of file MathUtils.java.
Referenced by denoptim.graph.Fragment.is3D(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getAngle()
static double denoptim.utils.MathUtils.getAngle (double[] A, double[] B, double[] C) static
Calculates angle (in degrees) between vectors BA and BC.
Parameters
A Point
B Point
C Point
Returns
Angle (degrees)
Definition at line 324 of file MathUtils.java.
References denoptim.utils.MathUtils.calculateAngle().
getNormalDirection()
static Vector3d denoptim.utils.MathUtils.getNormalDirection (Vector3d vecA) static
Generate a vector that is perpendicular to the given one.
No control over which perpendicular direction will be chosen.
Parameters
vecA input vector
Returns
a normal vector
Definition at line 426 of file MathUtils.java.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges().
length()
static double denoptim.utils.MathUtils.length (double[] v) static
Return the norm of a vector.
Parameters
v Vector to compute length of.
Returns
Length of vector.
Definition at line 134 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.calculateAngle(), and denoptim.utils.MathUtils.norm().
log2()
static double denoptim.utils.MathUtils.log2 (double x) static
Definition at line 260 of file MathUtils.java.
mean() [1/2]
static double denoptim.utils.MathUtils.mean (double[] a) static
Calculate mean value.
Parameters
a Array to calculate mean from.
Returns
mean value of array, NaN if empty array.
Definition at line 396 of file MathUtils.java.
References denoptim.utils.MathUtils.sum().
Referenced by denoptim.fitness.FitnessProvider.getFitness(), and denoptim.utils.MathUtils.mean().
mean() [2/2]
static double denoptim.utils.MathUtils.mean (List< Double > vals) static
Definition at line 406 of file MathUtils.java.
References denoptim.utils.MathUtils.mean().
norm()
static void denoptim.utils.MathUtils.norm (double[] d, double[] ret) static
Normalizes a vector.
Parameters
d A vector to be normalized.
ret The normalized vector.
Definition at line 67 of file MathUtils.java.
References denoptim.utils.MathUtils.length().
normDist()
static Vector3d denoptim.utils.MathUtils.normDist (Point3d p1, Point3d p2) static
Get normalized distance between two point.
Parameters
p1 the first point
p2 the second point
Returns
the normalized vector
Definition at line 86 of file MathUtils.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
roundValue()
static double denoptim.utils.MathUtils.roundValue (double val, int decimalPlaces) static
Definition at line 268 of file MathUtils.java.
scalar()
static void denoptim.utils.MathUtils.scalar (double[] d, double a, double[] ret) static
Scales a vector.
Parameters
d A vector to be scaled
a A scaling value
ret The scaled vector
Definition at line 119 of file MathUtils.java.
scale()
static double[] denoptim.utils.MathUtils.scale (double[] d, double a) static
Scales a vector.
Parameters
d A vector to be scaled
a A scaling value
Definition at line 102 of file MathUtils.java.
Referenced by denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer().
subtract()
static double[] denoptim.utils.MathUtils.subtract (double[] v0, double[] v1) static
Perform vector subtraction.
Parameters
v0 Vector to subtract from
v1 Vector to subtract
Returns
v0 - v1
Definition at line 180 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.computeDihedralAngle(), and denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer().
sum()
static double denoptim.utils.MathUtils.sum (double[] a) static
Return sum of all values in array.
Parameters
a Array to sum elements of.
Returns
array sum.
Definition at line 380 of file MathUtils.java.
References denoptim.utils.MathUtils.sum().
Referenced by denoptim.utils.MathUtils.mean(), and denoptim.utils.MathUtils.sum().
torsion()
static double denoptim.utils.MathUtils.torsion (Point3d p1, Point3d p2, Point3d p3, Point3d p4) static
Calculate the torsion angle between the 4 points.
Parameters
p1 Point
p2 Point
p3 Point
p4 Point
Returns
Torsion between arguments
Definition at line 363 of file MathUtils.java.
References denoptim.utils.MathUtils.computeDihedralAngle(), denoptim.utils.MathUtils.tp1, denoptim.utils.MathUtils.tp2, denoptim.utils.MathUtils.tp3, and denoptim.utils.MathUtils.tp4.
Referenced by denoptim.integration.tinker.TinkerUtils.getICFromIAC().
Member Data Documentation
tp1
final double [] denoptim.utils.MathUtils.tp1 = new double[3] static private
Definition at line 350 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.torsion().
tp2
final double [] denoptim.utils.MathUtils.tp2 = new double[3] static private
Definition at line 351 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.torsion().
tp3
final double [] denoptim.utils.MathUtils.tp3 = new double[3] static private
Definition at line 352 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.torsion().
tp4
final double [] denoptim.utils.MathUtils.tp4 = new double[3] static private
Definition at line 353 of file MathUtils.java.
Referenced by denoptim.utils.MathUtils.torsion().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/utils/MathUtils.java