DENOPTIM: denoptim.gui.GUICompatibilityMatrixTab Class Reference
denoptim.gui.GUICompatibilityMatrixTab Class Reference
A panel for handling of compatibility matrix.
Public Member Functions
GUICompatibilityMatrixTab (GUIMainPanel mainPanel)
Constructor.
void importCPMapFromFile (JComponent parent, File inFile)
boolean hasUnsavedChanges ()
Check whether there are unsaved changes.
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Static Public Attributes
static AtomicInteger CPMapTabUID = new AtomicInteger(1)
Unique identified for instances of this inspector.
Private Member Functions
void initialize ()
Initialize the panel and add buttons.
Private Attributes
boolean unsavedChanges = false
Flag signaling that loaded data has changes since last save.
JButton btnLoadCPMap
JButton btnImportAPClasses
CompatibilityMatrixForm cpMapHandler
Static Private Attributes
static final long serialVersionUID = 912850110991449553L
Version UID.
Additional Inherited Members
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Detailed Description
A panel for handling of compatibility matrix.
Author
Marco Foscato
Definition at line 42 of file GUICompatibilityMatrixTab.java.
Constructor & Destructor Documentation
GUICompatibilityMatrixTab()
denoptim.gui.GUICompatibilityMatrixTab.GUICompatibilityMatrixTab (GUIMainPanel mainPanel)
Constructor.
Definition at line 70 of file GUICompatibilityMatrixTab.java.
References denoptim.gui.GUICompatibilityMatrixTab.CPMapTabUID, denoptim.gui.GUICompatibilityMatrixTab.initialize(), and denoptim.gui.GUICardPanel.mainPanel.
Member Function Documentation
hasUnsavedChanges()
boolean denoptim.gui.GUICompatibilityMatrixTab.hasUnsavedChanges ()
Check whether there are unsaved changes.
Returns
true if there are unsaved changes.
Reimplemented from denoptim.gui.GUICardPanel.
Definition at line 222 of file GUICompatibilityMatrixTab.java.
References denoptim.gui.GUICompatibilityMatrixTab.unsavedChanges.
importCPMapFromFile()
void denoptim.gui.GUICompatibilityMatrixTab.importCPMapFromFile (JComponent parent, File inFile)
Definition at line 210 of file GUICompatibilityMatrixTab.java.
References denoptim.gui.GUICompatibilityMatrixTab.cpMapHandler, and denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
Referenced by denoptim.gui.MainToolBar.openFile().
initialize()
void denoptim.gui.GUICompatibilityMatrixTab.initialize () private
Initialize the panel and add buttons.
Definition at line 82 of file GUICompatibilityMatrixTab.java.
References denoptim.gui.ButtonsBar.add(), denoptim.files.FileUtils.addToRecentFiles(), denoptim.gui.GUICompatibilityMatrixTab.btnImportAPClasses, denoptim.gui.GUICompatibilityMatrixTab.btnLoadCPMap, denoptim.files.FileFormat.COMP_MAP, denoptim.gui.GUICompatibilityMatrixTab.cpMapHandler, denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCappingGroupLibs(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromFragmentLibs(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), denoptim.gui.GUIFileOpener.pickFile(), denoptim.gui.GUIFileOpener.pickFileForSaving(), denoptim.gui.GUIFileOpener.pickManyFiles(), denoptim.gui.GUICompatibilityMatrixTab.unsavedChanges, and denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile().
Referenced by denoptim.gui.GUICompatibilityMatrixTab.GUICompatibilityMatrixTab().
Member Data Documentation
btnImportAPClasses
JButton denoptim.gui.GUICompatibilityMatrixTab.btnImportAPClasses private
Definition at line 60 of file GUICompatibilityMatrixTab.java.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
btnLoadCPMap
JButton denoptim.gui.GUICompatibilityMatrixTab.btnLoadCPMap private
Definition at line 59 of file GUICompatibilityMatrixTab.java.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
cpMapHandler
CompatibilityMatrixForm denoptim.gui.GUICompatibilityMatrixTab.cpMapHandler private
Definition at line 62 of file GUICompatibilityMatrixTab.java.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.importCPMapFromFile(), and denoptim.gui.GUICompatibilityMatrixTab.initialize().
CPMapTabUID
AtomicInteger denoptim.gui.GUICompatibilityMatrixTab.CPMapTabUID = new AtomicInteger(1) static
Unique identified for instances of this inspector.
Definition at line 52 of file GUICompatibilityMatrixTab.java.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.GUICompatibilityMatrixTab().
serialVersionUID
final long denoptim.gui.GUICompatibilityMatrixTab.serialVersionUID = 912850110991449553L static private
Version UID.
Definition at line 47 of file GUICompatibilityMatrixTab.java.
unsavedChanges
boolean denoptim.gui.GUICompatibilityMatrixTab.unsavedChanges = false private
Flag signaling that loaded data has changes since last save.
Definition at line 57 of file GUICompatibilityMatrixTab.java.
Referenced by denoptim.gui.GUICompatibilityMatrixTab.hasUnsavedChanges(), and denoptim.gui.GUICompatibilityMatrixTab.initialize().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUICompatibilityMatrixTab.java