DENOPTIM: denoptim.graph.simplified.UndirectedEdge Class Reference
denoptim.graph.simplified.UndirectedEdge Class Reference
This class represents an undirected version of the edge between two vertices.
Public Member Functions
UndirectedEdge (AttachmentPoint apA, AttachmentPoint apB, BondType bondType)
Constructor for an undirected edge.
UndirectedEdge (AttachmentPoint apA, AttachmentPoint apB)
Constructor for an undirected edge.
int compare (UndirectedEdge other)
String toString ()
Private Member Functions
void makeInvariant ()
Private Attributes
AttachmentPoint apA
Attachment point A.
AttachmentPoint apB
Attachment point B.
BondType bondType = BondType.UNDEFINED
The bond type associated with the connection between the fragments.
String invariant = null
Invariant representation used to compare.
Detailed Description
This class represents an undirected version of the edge between two vertices.
However, it does not behave as a DENOPTIMEdge since it does not interfere with the available state of the attachment points.
Definition at line 32 of file UndirectedEdge.java.
Constructor & Destructor Documentation
UndirectedEdge() [1/2]
denoptim.graph.simplified.UndirectedEdge.UndirectedEdge (AttachmentPoint apA, AttachmentPoint apB, BondType bondType)
Constructor for an undirected edge.
This edge does not make the APs unavailable.
Parameters
apA one of the attachment points connected by this edge
apB another of the attachment points connected by this edge
bondType defines what kind of bond type this edge should be converted to when converting a graph into a chemical representation.
Definition at line 65 of file UndirectedEdge.java.
References denoptim.graph.simplified.UndirectedEdge.apA, denoptim.graph.simplified.UndirectedEdge.apB, and denoptim.graph.simplified.UndirectedEdge.bondType.
UndirectedEdge() [2/2]
denoptim.graph.simplified.UndirectedEdge.UndirectedEdge (AttachmentPoint apA, AttachmentPoint apB)
Constructor for an undirected edge.
This edge does not make the APs unavailable. Bond type is inferred from the first attachment point.
Parameters
apA one of the attachment points connected by this edge
apB another of the attachment points connected by this edge
Definition at line 82 of file UndirectedEdge.java.
References denoptim.graph.simplified.UndirectedEdge.apA, denoptim.graph.simplified.UndirectedEdge.apB, denoptim.graph.AttachmentPoint.getAPClass(), and denoptim.graph.APClass.getBondType().
Member Function Documentation
compare()
int denoptim.graph.simplified.UndirectedEdge.compare (UndirectedEdge other)
Definition at line 111 of file UndirectedEdge.java.
References denoptim.graph.simplified.UndirectedEdge.bondType, denoptim.graph.simplified.UndirectedEdge.invariant, and denoptim.graph.simplified.UndirectedEdge.makeInvariant().
Referenced by denoptim.graph.DGraph.isIsomorphicTo(), and denoptim.graph.UndirectedEdgeRelationTest.testUndirectedComparison().
makeInvariant()
void denoptim.graph.simplified.UndirectedEdge.makeInvariant () private
Definition at line 89 of file UndirectedEdge.java.
References denoptim.graph.simplified.UndirectedEdge.apA, denoptim.graph.simplified.UndirectedEdge.apB, denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.utils.GeneralUtils.getPaddedString().
Referenced by denoptim.graph.simplified.UndirectedEdge.compare().
toString()
String denoptim.graph.simplified.UndirectedEdge.toString ()
Definition at line 135 of file UndirectedEdge.java.
References denoptim.graph.simplified.UndirectedEdge.apA, denoptim.graph.simplified.UndirectedEdge.apB, denoptim.graph.simplified.UndirectedEdge.bondType, denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.graph.Vertex.getVertexId().
Member Data Documentation
apA
AttachmentPoint denoptim.graph.simplified.UndirectedEdge.apA private
Attachment point A.
Definition at line 37 of file UndirectedEdge.java.
Referenced by denoptim.graph.simplified.UndirectedEdge.makeInvariant(), denoptim.graph.simplified.UndirectedEdge.toString(), and denoptim.graph.simplified.UndirectedEdge.UndirectedEdge().
apB
AttachmentPoint denoptim.graph.simplified.UndirectedEdge.apB private
Attachment point B.
Definition at line 42 of file UndirectedEdge.java.
Referenced by denoptim.graph.simplified.UndirectedEdge.makeInvariant(), denoptim.graph.simplified.UndirectedEdge.toString(), and denoptim.graph.simplified.UndirectedEdge.UndirectedEdge().
bondType
BondType denoptim.graph.simplified.UndirectedEdge.bondType = BondType.UNDEFINED private
The bond type associated with the connection between the fragments.
Definition at line 47 of file UndirectedEdge.java.
Referenced by denoptim.graph.simplified.UndirectedEdge.compare(), denoptim.graph.simplified.UndirectedEdge.toString(), and denoptim.graph.simplified.UndirectedEdge.UndirectedEdge().
invariant
String denoptim.graph.simplified.UndirectedEdge.invariant = null private
Invariant representation used to compare.
Definition at line 52 of file UndirectedEdge.java.
Referenced by denoptim.graph.simplified.UndirectedEdge.compare().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/simplified/UndirectedEdge.java