DENOPTIM: denoptim.fragmenter.ParallelConformerExtractionAlgorithm Class Reference
denoptim.fragmenter.ParallelConformerExtractionAlgorithm Class Reference
Runs threads that extract the most representative conformer of fragments given as input.
Public Member Functions
ParallelConformerExtractionAlgorithm (FragmenterParameters settings)
Constructor.
List< String > getResults ()
Returns the list of pathnames collecting the most representative conformers, as defined by the settings (i.e., either cluster centroids or fragment closest to the centroids).
Public Member Functions inherited from denoptim.task.ParallelAsynchronousTaskExecutor
ParallelAsynchronousTaskExecutor (int numberOfTasks, Logger logger)
Constructor.
void stopRun ()
Stops all subtasks and shutdown executor.
void run () throws DENOPTIMException, IOException
Run the parallelized task.
Protected Member Functions
boolean doPreFlightOperations ()
void createAndSubmitTasks ()
Implementations of this method must call the submitTask(Task, String) method to actually send the task to the executor and eventually start it.
boolean doPostFlightOperations ()
Protected Member Functions inherited from denoptim.task.ParallelAsynchronousTaskExecutor
boolean subtaskHasException ()
Looks for exceptions in the subtasks and, if any, store its reference locally to allow reporting it back from the main thread.
Throwable getExceptionFromSubTask ()
boolean allTasksCompleted ()
Check for completion of all subtasks.
void submitTask (Task task, String logFilePathname)
abstract void createAndSubmitTasks ()
Implementations of this method must call the submitTask(Task, String) method to actually send the task to the executor and eventually start it.
abstract boolean doPostFlightOperations ()
abstract boolean doPreFlightOperations ()
Private Attributes
FragmenterParameters settings = null
All settings controlling the tasks executed by this class.
Additional Inherited Members
Protected Attributes inherited from denoptim.task.ParallelAsynchronousTaskExecutor
final List< Object > results
List of object returned by completed tasks.
Package Attributes inherited from denoptim.task.ParallelAsynchronousTaskExecutor
final ThreadPoolExecutor tpe
Asynchronous tasks manager.
Detailed Description
Runs threads that extract the most representative conformer of fragments given as input.
Author
Marco Foscato
Definition at line 40 of file ParallelConformerExtractionAlgorithm.java.
Constructor & Destructor Documentation
ParallelConformerExtractionAlgorithm()
denoptim.fragmenter.ParallelConformerExtractionAlgorithm.ParallelConformerExtractionAlgorithm (FragmenterParameters settings)
Constructor.
We expect to run this from ParallelFragmentationAlgorithm.
Definition at line 55 of file ParallelConformerExtractionAlgorithm.java.
References denoptim.programs.RunTimeParameters.getLogger(), denoptim.programs.fragmenter.FragmenterParameters.getNumTasks(), and denoptim.fragmenter.ParallelConformerExtractionAlgorithm.settings.
Member Function Documentation
createAndSubmitTasks()
void denoptim.fragmenter.ParallelConformerExtractionAlgorithm.createAndSubmitTasks () protected
Implementations of this method must call the submitTask(Task, String) method to actually send the task to the executor and eventually start it.
Reimplemented from denoptim.task.ParallelAsynchronousTaskExecutor.
Definition at line 70 of file ParallelConformerExtractionAlgorithm.java.
References denoptim.fragmenter.ConformerExtractorTask.getLogFilePathname(), denoptim.programs.RunTimeParameters.getWorkDirectory(), denoptim.io.DenoptimIO.readVertexes(), denoptim.fragmenter.ParallelConformerExtractionAlgorithm.settings, denoptim.task.ParallelAsynchronousTaskExecutor.submitTask(), and denoptim.graph.Vertex.BBType.UNDEFINED.
doPostFlightOperations()
boolean denoptim.fragmenter.ParallelConformerExtractionAlgorithm.doPostFlightOperations () protected
Reimplemented from denoptim.task.ParallelAsynchronousTaskExecutor.
Definition at line 106 of file ParallelConformerExtractionAlgorithm.java.
doPreFlightOperations()
boolean denoptim.fragmenter.ParallelConformerExtractionAlgorithm.doPreFlightOperations () protected
Reimplemented from denoptim.task.ParallelAsynchronousTaskExecutor.
Definition at line 63 of file ParallelConformerExtractionAlgorithm.java.
getResults()
List< String > denoptim.fragmenter.ParallelConformerExtractionAlgorithm.getResults ()
Returns the list of pathnames collecting the most representative conformers, as defined by the settings (i.e., either cluster centroids or fragment closest to the centroids).
Returns
the list of patnames where results are collected.
Definition at line 120 of file ParallelConformerExtractionAlgorithm.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.results.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations().
Member Data Documentation
settings
FragmenterParameters denoptim.fragmenter.ParallelConformerExtractionAlgorithm.settings = null private
All settings controlling the tasks executed by this class.
Definition at line 46 of file ParallelConformerExtractionAlgorithm.java.
Referenced by denoptim.fragmenter.ParallelConformerExtractionAlgorithm.createAndSubmitTasks(), and denoptim.fragmenter.ParallelConformerExtractionAlgorithm.ParallelConformerExtractionAlgorithm().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragmenter/ParallelConformerExtractionAlgorithm.java