DENOPTIM: denoptim.fitness.FitnessProviderTest Class Reference
denoptim.fitness.FitnessProviderTest Class Reference
Unit test for internal fitness provider.
Public Member Functions
void testConfigureDescriptorsList () throws Exception
void testGetFitness () throws Exception
void testGetFitnessWithCustomDescriptors () throws Exception
void testGetFitnessWithParametrizedDescriptors () throws Exception
This test is reproducing most of what done in FitnessParametersTest#testProcessExpressions() so if both fail the problem is most likely in FitnessParameters.
void testGetConstantFitness () throws Exception
Package Functions
void setUp ()
Static Package Attributes
static File tempDir
Private Member Functions
boolean closeEnough (double expected, double actual)
Private Attributes
SmilesParser sp
Logger logger
Static Private Attributes
static final String SEP = System.getProperty("file.separator")
Detailed Description
Unit test for internal fitness provider.
Author
Marco Foscato
Definition at line 55 of file FitnessProviderTest.java.
Member Function Documentation
closeEnough()
boolean denoptim.fitness.FitnessProviderTest.closeEnough (double expected, double actual) private
Definition at line 310 of file FitnessProviderTest.java.
Referenced by denoptim.fitness.FitnessProviderTest.testGetConstantFitness(), and denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors().
setUp()
void denoptim.fitness.FitnessProviderTest.setUp () package
Definition at line 66 of file FitnessProviderTest.java.
References denoptim.fitness.FitnessProviderTest.logger, denoptim.fitness.FitnessProviderTest.sp, and denoptim.fitness.FitnessProviderTest.tempDir.
testConfigureDescriptorsList()
void denoptim.fitness.FitnessProviderTest.testConfigureDescriptorsList () throws Exception
Definition at line 77 of file FitnessProviderTest.java.
References denoptim.fitness.FitnessProvider.engine, and denoptim.fitness.FitnessProviderTest.logger.
testGetConstantFitness()
void denoptim.fitness.FitnessProviderTest.testGetConstantFitness () throws Exception
Definition at line 286 of file FitnessProviderTest.java.
References denoptim.fitness.FitnessProviderTest.closeEnough(), denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.fitness.FitnessParameters.getDescriptors(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.fitness.FitnessParameters.getFitnessExpression(), denoptim.fitness.FitnessParameters.interpretKeyword(), denoptim.fitness.FitnessProviderTest.logger, denoptim.fitness.FitnessParameters.processParameters(), and denoptim.fitness.FitnessProviderTest.sp.
testGetFitness()
void denoptim.fitness.FitnessProviderTest.testGetFitness () throws Exception
Definition at line 108 of file FitnessProviderTest.java.
References denoptim.fitness.DescriptorForFitness.addDependentVariable(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.fitness.FitnessProviderTest.logger, and denoptim.fitness.FitnessProviderTest.sp.
testGetFitnessWithCustomDescriptors()
void denoptim.fitness.FitnessProviderTest.testGetFitnessWithCustomDescriptors () throws Exception
Definition at line 173 of file FitnessProviderTest.java.
References denoptim.fitness.DescriptorForFitness.addDependentVariable(), denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.fitness.FitnessProvider.getFitness(), denoptim.fitness.FitnessProviderTest.logger, and denoptim.fitness.FitnessProviderTest.sp.
testGetFitnessWithParametrizedDescriptors()
void denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors () throws Exception
This test is reproducing most of what done in FitnessParametersTest#testProcessExpressions() so if both fail the problem is most likely in FitnessParameters.
Definition at line 228 of file FitnessProviderTest.java.
References denoptim.fitness.FitnessProviderTest.closeEnough(), denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.fitness.FitnessParameters.getDescriptors(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.fitness.FitnessParameters.getFitnessExpression(), denoptim.fitness.FitnessParameters.interpretKeyword(), denoptim.fitness.FitnessProviderTest.logger, denoptim.fitness.FitnessParameters.processParameters(), denoptim.fitness.FitnessProviderTest.SEP, denoptim.fitness.FitnessProviderTest.sp, denoptim.fitness.FitnessProviderTest.tempDir, and denoptim.io.DenoptimIO.writeSDFFile().
Member Data Documentation
logger
Logger denoptim.fitness.FitnessProviderTest.logger private
Definition at line 63 of file FitnessProviderTest.java.
Referenced by denoptim.fitness.FitnessProviderTest.setUp(), denoptim.fitness.FitnessProviderTest.testConfigureDescriptorsList(), denoptim.fitness.FitnessProviderTest.testGetConstantFitness(), denoptim.fitness.FitnessProviderTest.testGetFitness(), denoptim.fitness.FitnessProviderTest.testGetFitnessWithCustomDescriptors(), and denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors().
SEP
final String denoptim.fitness.FitnessProviderTest.SEP = System.getProperty("file.separator") static private
Definition at line 58 of file FitnessProviderTest.java.
Referenced by denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors().
sp
SmilesParser denoptim.fitness.FitnessProviderTest.sp private
Definition at line 57 of file FitnessProviderTest.java.
Referenced by denoptim.fitness.FitnessProviderTest.setUp(), denoptim.fitness.FitnessProviderTest.testGetConstantFitness(), denoptim.fitness.FitnessProviderTest.testGetFitness(), denoptim.fitness.FitnessProviderTest.testGetFitnessWithCustomDescriptors(), and denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors().
tempDir
File denoptim.fitness.FitnessProviderTest.tempDir static package
Definition at line 61 of file FitnessProviderTest.java.
Referenced by denoptim.fitness.FitnessProviderTest.setUp(), and denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fitness/FitnessProviderTest.java