DENOPTIM: denoptim.programs.denovo.GAParameters Class Reference
denoptim.programs.denovo.GAParameters Class Reference
Parameters for genetic algorithm.
Public Member Functions
GAParameters ()
Constructor.
String getUIDFileIn ()
String getUIDFileOut ()
String getVisitedGraphsFile ()
String getInterfaceDir ()
String getMonitorFile ()
int getMonitorDumpStep ()
boolean recordMateSelection ()
int getPrecisionLevel ()
int getNumberOfCPU ()
boolean isSortOrderDecreasing ()
boolean isNanFitnessKillsExperiment ()
int getMaxTriesFactor ()
int getMaxGeneticOpAttempts ()
String getDataDirectory ()
void setWorkingDirectory (String pathName)
int getReplacementStrategy ()
boolean parentsSurvive ()
double getCrowdingFactorSteepSigma ()
double getCrowdingFactorMiddleSigma ()
double getCrowdingMultiplier ()
int getCrowdingProbabilityScheme ()
double getGrowthFactorSteepSigma ()
double getGrowthFactorMiddleSigma ()
double getGrowthMultiplier ()
int getGrowthProbabilityScheme ()
double getMolGrowthFactorSteepSigma ()
double getMolGrowthFactorMiddleSigma ()
double getMolGrowthMultiplier ()
int getMolGrowthProbabilityScheme ()
void setPopulationSize (int size)
int getPopulationSize ()
int getNumberOfGenerations ()
String getSelectionStrategy ()
int getSelectivePressure ()
List< MutationType > getExcludedMutationTypes ()
int getSelectionStrategyType ()
int getNumberOfConvergenceGenerations ()
int getNumberOfChildren ()
double getCrossoverWeight ()
int maxOffsprintFromXover ()
boolean keepBestSibling ()
double getMutationWeight ()
double getConstructionWeight ()
double getSymmetryProbability ()
String getInitialPopulationFile ()
String getInitMolsToFragmentFile ()
double[] getMultiSiteMutationWeights ()
boolean useMolSizeBasedProb ()
boolean useLevelBasedProb ()
int getParallelizationScheme ()
double getMinFitnessSD ()
boolean dumpMonitor ()
double getSaveRingSystemsFitnessThreshold ()
boolean getSaveRingSystemsAsTemplatesNonScaff ()
boolean getSaveRingSystemsAsTemplatesScaff ()
boolean coupleMutationAndCrossover ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void processParameters () throws DENOPTIMException
Processes currently loaded fields.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
boolean savePopFile ()
int getMaxRingsAddedByMutation ()
Return the value of the number of rings that we are allowed to add in a single MutationType#ADDRING mutation.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Static Public Member Functions
static int convertProbabilityScheme (String option) throws DENOPTIMException
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes
String timeStamp = "NOTIMESTAMP"
Time stamp identifying this run.
int maxUIDMemory = 1000000
Maximum number of unique identifiers kept in memory.
String uidMemoryOnDisk = "memory_UIDs.txt"
Text file used to store unique identifiers beyond the limits of the memory (see GAParameters#maxUIDMemory).
boolean mutatedGraphFailedEvalTolerant = true
Flag that enables the ignoring of mutated graphs that lead to a failure in the evaluation of graphs that generates SMILES, InChI and molecular representation.
boolean xoverGraphFailedEvalTolerant = true
Flag that enables the ignoring of crossover-ed graphs that lead to a f ailure in the evaluation of graphs that generates SMILES, InChI and molecular representation.
boolean xoverFailureTolerant = true
Flag that enables the ignoring of crossover events triggering exceptions.
boolean mutationFailureTolerant = true
Flag that enables the ignoring of mutation events triggering exceptions.
boolean buildAnewFailureTolerant = true
Flag that enables the ignoring of construction from scratch events triggering exceptions.
int maxXOverableSubGraphSize = 20
Limit to the size of subgraphs that are exchanged during crossover.
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Attributes
String initPoplnFile = ""
Pathname of the initial population file.
String initMolsToFragmentFile = null
Pathname to the file collecting molecules to fragment to generate initial population.
String uidFileIn = ""
Pathname of the file with the list of individuals unique identifiers that are initially known.
String uidFileOut = ""
Pathname of the file where the individuals unique identifiers will be recorded.
String visitedGraphsFile = "GRAPHS.txt"
Pathname to the file containing the list of previously visited graph.
int populationSize = 50
Size of the population.
int numOfChildren = 5
Number of children (i.e., new offspring) to be produced in each generation.
int numConvGen = 5
Number of identical generations before convergence is reached.
int numGenerations = 100
Maximum number of generations to run for.
int maxTriesPerPop = 25
Factor controlling the maximum number of attempts to build a graph so that the maximum number of attempts = factor * population size.
int maxGeneticOpAttempts = 100
Maximum number of attempts to perform any genetic operation (i.e., either crossover or mutation) on any parents before giving up.
int replacementStrategy = 1
Replacement strategy: 1) replace worst individuals with new ones that are better than the worst, 2) no replacement (the population keeps growing).
boolean parentsSurvive = true
Flag defining if population members can survive multiple generations (when this variable is true) or the population is refreshed at every generation (when this variable is false).
int lvlGrowthProbabilityScheme = 0
Definition of the growth probability function:
double lvlGrowthMultiplier = 0.5
Parameter controlling the growth probability function of types 'EXP_DIFF' and 'TANH'.
double lvlGrowthSigmaSteepness = 1.0
Parameters controlling the growth probability function of type 'SIGMA': steepness of the function where p=50%.
double lvlGrowthSigmaMiddle = 2.5
Parameters controlling the growth probability function of type 'SIGMA': level at which p=50% (can be a float)
boolean useLevelBasedProb = false
Flag recording the intention to use level-controlled graph extension probability.
boolean useMolSizeBasedProb = false
Flag recording the intention to use molecular size-controlled graph extension probability.
int molGrowthProbabilityScheme = 2
Definition of the molGrowth probability function:
double molGrowthMultiplier = 0.5
Parameter controlling the molGrowth probability function of types 'EXP_DIFF' and 'TANH'.
double molGrowthSigmaSteepness = 0.2
Parameters controlling the molGrowth probability function of type 'SIGMA': steepness of the function where p=50%.
double molGrowthSigmaMiddle = 25
Parameters controlling the molGrowth probability function of type 'SIGMA': level at which p=50% (can be a float)
int crowdingProbabilityScheme = 3
Definition of the crowding probability function.
double crowdingMultiplier = 0.5
Parameter controlling the crowding probability function of types 'EXP_DIFF' and 'TANH'.
double crowdingSigmaSteepness = 1.0
Parameters controlling the crowding probability function of type 'SIGMA': steepness of the function where p=50%.
double crowdingSigmaMiddle = 2.5
Parameters controlling the crowding probability function of type 'SIGMA': level at which p=50% (can be a float)
double symmetricSubProbability = 0.8
The probability at which symmetric substitution occurs.
double mutationWeight = 1.0
The relative weight at which mutation is performed.
boolean coupleMutationAndCrossover = false
Flag defining if we want mutation to occur on offspring that result from crossover (i.e., mutation and crossover are coupled), otherwise we want to mutate population members irrespectively on crossover.
double builtAnewWeight = 1.0
The relative weight at which construction from scratch is performed.
double crossoverWeight = 1.0
The relative weight at which crossover is performed.
int xoverSelectionMode = 3
Crossover parents selection strategy: integer code.
String strXoverSelectionMode = xoverSelectionMode+""
Crossover parents selection strategy: string.
int selectivePressure = -1
Intensity for selecting high fitness parents.
int maxOffsprintFromXover = 1
Number of offspring that a single crossover operation can produce.
boolean keepBestSibling = false
Flag controlling if we choose the best sibling out of crossover.
long seed = 0L
The seed value for random number generation.
int parallelizationScheme = 1
Parallelization scheme: synchronous or asynchronous.
int numParallelTasks = 0
Maximum number of parallel tasks.
boolean sortOrderDecreasing = true
Flag controlling how to sort the population based on the fitness.
boolean nanFitnessKillsExperiment = false
Flag controlling whether we allow NaN fitness to kill design experiments.
int precisionLevel = 3
Precision for reporting the value of the fitness.
int monitorDumpStep = 50
Monitor dumps step.
boolean dumpMonitor = false
Flag controlling if we dump monitored data or not.
double minFitnessSD = 0.000001
Minimal standard deviation accepted in the fitness values of the initial population.
int maxRingsAddedByMutation = 1
Maximum number of rings added by a single mutation operation.
boolean saveRingSystemsAsTemplatesScaffolds = false
Flag controlling the possibility of collecting cyclic graph systems that include a scaffold and save them as new template scaffolds.
boolean saveRingSystemsAsTemplatesNonScaff = false
Flag controlling the possibility of collecting cyclic graph systems that do NOT include a scaffold and save them as new template non-scaffold building blocks.
double saveRingSystemsFitnessThreshold = 0.10
Fitness threshold for adding template to building block libraries.
boolean writePopOnDisk = false
Flag requesting to write a SDF file that collects all the population members each time we report the population details on file.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Package Attributes
List< MutationType > excludedMutationTypes = new ArrayList<MutationType>()
Mutation types that are excluded everywhere.
Private Member Functions
void createWorkingDirectory () throws DENOPTIMException
Create the directory that will store the output of the GA run.
Private Attributes
String dataDir = System.getProperty("user.dir")
Pathname to the working directory for the current run.
String interfaceDir
Pathname to the interface directory for the current run.
String monitorFile = ""
Pathname of file where EA monitors dumps are printed.
boolean recordMateSelection = false
Flag defining whether we record which mates are selected or not.
final String DEFUIDFILEOUTNAME = "MOLUID.txt"
Default name of the UIDFileOut.
double[] mutliSiteMutationWeights = new double[]{0,10,1}
The weights of multi-site mutations.
Additional Inherited Members
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Detailed Description
Parameters for genetic algorithm.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 45 of file GAParameters.java.
Constructor & Destructor Documentation
GAParameters()
denoptim.programs.denovo.GAParameters.GAParameters ()
Constructor.
Parameters
paramType
Definition at line 439 of file GAParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.GA_PARAMS.
Member Function Documentation
checkParameters()
void denoptim.programs.denovo.GAParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1512 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.builtAnewWeight, denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.denovo.GAParameters.crossoverWeight, denoptim.programs.denovo.GAParameters.initMolsToFragmentFile, denoptim.programs.denovo.GAParameters.initPoplnFile, denoptim.programs.denovo.GAParameters.mutationWeight, denoptim.programs.denovo.GAParameters.numConvGen, denoptim.programs.denovo.GAParameters.numGenerations, denoptim.programs.denovo.GAParameters.numOfChildren, denoptim.programs.denovo.GAParameters.symmetricSubProbability, denoptim.programs.denovo.GAParameters.useLevelBasedProb, and denoptim.programs.denovo.GAParameters.useMolSizeBasedProb.
Referenced by denoptim.programs.denovo.GARunner.runProgram().
convertProbabilityScheme()
static int denoptim.programs.denovo.GAParameters.convertProbabilityScheme (String option) throws DENOPTIMException static
Definition at line 1406 of file GAParameters.java.
Referenced by denoptim.gui.GAParametersForm.createCrowdProbDataset(), denoptim.gui.GAParametersForm.createLvlProbDataset(), denoptim.gui.GAParametersForm.createMolSizeProbDataset(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
coupleMutationAndCrossover()
boolean denoptim.programs.denovo.GAParameters.coupleMutationAndCrossover ()
Returns
true if we want mutation to occur on offspring that result from crossover, otherwise we want to mutate population members irrespectively on crossover.
Definition at line 866 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.coupleMutationAndCrossover.
createWorkingDirectory()
void denoptim.programs.denovo.GAParameters.createWorkingDirectory () throws DENOPTIMException private
Create the directory that will store the output of the GA run.
Exceptions
DENOPTIMException
Definition at line 1438 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.dataDir, denoptim.files.FileFormat.GA_RUN, denoptim.programs.denovo.GAParameters.interfaceDir, denoptim.programs.denovo.GAParameters.setWorkingDirectory(), and denoptim.programs.denovo.GAParameters.timeStamp.
Referenced by denoptim.programs.denovo.GAParameters.processParameters().
dumpMonitor()
boolean denoptim.programs.denovo.GAParameters.dumpMonitor ()
Definition at line 832 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.dumpMonitor.
getConstructionWeight()
double denoptim.programs.denovo.GAParameters.getConstructionWeight ()
Definition at line 765 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.builtAnewWeight.
Referenced by denoptim.ga.EAUtils.chooseGenerationMethod(), and denoptim.ga.EvolutionaryAlgorithm.makeOffspringB().
getCrossoverWeight()
double denoptim.programs.denovo.GAParameters.getCrossoverWeight ()
Definition at line 729 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.crossoverWeight.
Referenced by denoptim.ga.EAUtils.chooseGenerationMethod(), and denoptim.ga.EvolutionaryAlgorithm.makeOffspringB().
getCrowdingFactorMiddleSigma()
double denoptim.programs.denovo.GAParameters.getCrowdingFactorMiddleSigma ()
Definition at line 589 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.crowdingSigmaMiddle.
Referenced by denoptim.ga.EAUtils.getCrowdingProbability().
getCrowdingFactorSteepSigma()
double denoptim.programs.denovo.GAParameters.getCrowdingFactorSteepSigma ()
Definition at line 582 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.crowdingSigmaSteepness.
Referenced by denoptim.ga.EAUtils.getCrowdingProbability().
getCrowdingMultiplier()
double denoptim.programs.denovo.GAParameters.getCrowdingMultiplier ()
Definition at line 596 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.crowdingMultiplier.
Referenced by denoptim.ga.EAUtils.getCrowdingProbability().
getCrowdingProbabilityScheme()
int denoptim.programs.denovo.GAParameters.getCrowdingProbabilityScheme ()
Definition at line 603 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.crowdingProbabilityScheme.
Referenced by denoptim.ga.EAUtils.getCrowdingProbability().
getDataDirectory()
String denoptim.programs.denovo.GAParameters.getDataDirectory ()
Definition at line 541 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.dataDir.
Referenced by denoptim.ga.EAUtils.getPathNameToFinalPopulationDetailsFile(), denoptim.ga.EAUtils.getPathNameToFinalPopulationFolder(), denoptim.ga.EAUtils.getPathNameToGenerationDetailsFile(), denoptim.ga.EAUtils.getPathNameToGenerationFolder(), and denoptim.programs.denovo.GAParametersTest.testLogging().
getExcludedMutationTypes()
List< MutationType > denoptim.programs.denovo.GAParameters.getExcludedMutationTypes ()
Definition at line 701 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.excludedMutationTypes.
getGrowthFactorMiddleSigma()
double denoptim.programs.denovo.GAParameters.getGrowthFactorMiddleSigma ()
Definition at line 617 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.lvlGrowthSigmaMiddle.
Referenced by denoptim.ga.EAUtils.getGrowthByLevelProbability().
getGrowthFactorSteepSigma()
double denoptim.programs.denovo.GAParameters.getGrowthFactorSteepSigma ()
Definition at line 610 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.lvlGrowthSigmaSteepness.
Referenced by denoptim.ga.EAUtils.getGrowthByLevelProbability().
getGrowthMultiplier()
double denoptim.programs.denovo.GAParameters.getGrowthMultiplier ()
Definition at line 624 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.lvlGrowthMultiplier.
Referenced by denoptim.ga.EAUtils.getGrowthByLevelProbability().
getGrowthProbabilityScheme()
int denoptim.programs.denovo.GAParameters.getGrowthProbabilityScheme ()
Definition at line 631 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.lvlGrowthProbabilityScheme.
Referenced by denoptim.ga.EAUtils.getGrowthByLevelProbability().
getInitialPopulationFile()
String denoptim.programs.denovo.GAParameters.getInitialPopulationFile ()
Definition at line 779 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.initPoplnFile.
getInitMolsToFragmentFile()
String denoptim.programs.denovo.GAParameters.getInitMolsToFragmentFile ()
Returns
the pathname to the file defining molecules to convert into candidates by fragmentation.
Definition at line 790 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.initMolsToFragmentFile.
Referenced by denoptim.ga.EvolutionaryAlgorithm.initializePopulation().
getInterfaceDir()
String denoptim.programs.denovo.GAParameters.getInterfaceDir ()
Definition at line 467 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.interfaceDir.
Referenced by denoptim.programs.denovo.GARunner.runProgram().
getMaxGeneticOpAttempts()
int denoptim.programs.denovo.GAParameters.getMaxGeneticOpAttempts ()
Definition at line 534 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.maxGeneticOpAttempts.
getMaxRingsAddedByMutation()
int denoptim.programs.denovo.GAParameters.getMaxRingsAddedByMutation ()
Return the value of the number of rings that we are allowed to add in a single MutationType#ADDRING mutation.
Returns
the maximum number of rings added in a single mutation.
Definition at line 1647 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.maxRingsAddedByMutation.
getMaxTriesFactor()
int denoptim.programs.denovo.GAParameters.getMaxTriesFactor ()
Definition at line 527 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.maxTriesPerPop.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.initializePopulation(), and denoptim.ga.EvolutionaryAlgorithm.processInitialPopCandidate().
getMinFitnessSD()
double denoptim.programs.denovo.GAParameters.getMinFitnessSD ()
Definition at line 825 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.minFitnessSD.
Referenced by denoptim.ga.EvolutionaryAlgorithm.run().
getMolGrowthFactorMiddleSigma()
double denoptim.programs.denovo.GAParameters.getMolGrowthFactorMiddleSigma ()
Definition at line 645 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.molGrowthSigmaMiddle.
Referenced by denoptim.ga.EAUtils.getMolSizeProbability().
getMolGrowthFactorSteepSigma()
double denoptim.programs.denovo.GAParameters.getMolGrowthFactorSteepSigma ()
Definition at line 638 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.molGrowthSigmaSteepness.
Referenced by denoptim.ga.EAUtils.getMolSizeProbability().
getMolGrowthMultiplier()
double denoptim.programs.denovo.GAParameters.getMolGrowthMultiplier ()
Definition at line 652 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.molGrowthMultiplier.
Referenced by denoptim.ga.EAUtils.getMolSizeProbability().
getMolGrowthProbabilityScheme()
int denoptim.programs.denovo.GAParameters.getMolGrowthProbabilityScheme ()
Definition at line 659 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.molGrowthProbabilityScheme.
Referenced by denoptim.ga.EAUtils.getMolSizeProbability().
getMonitorDumpStep()
int denoptim.programs.denovo.GAParameters.getMonitorDumpStep ()
Definition at line 481 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.monitorDumpStep.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), and denoptim.ga.EvolutionaryAlgorithm.initializePopulation().
getMonitorFile()
String denoptim.programs.denovo.GAParameters.getMonitorFile ()
Definition at line 474 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.monitorFile.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.initializePopulation(), denoptim.ga.EvolutionaryAlgorithm.run(), and denoptim.ga.EAUtils.selectBasedOnFitness().
getMultiSiteMutationWeights()
double[] denoptim.programs.denovo.GAParameters.getMultiSiteMutationWeights ()
Definition at line 797 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.mutliSiteMutationWeights.
Referenced by denoptim.programs.denovo.GAParametersTest.testInterpretationOfKeywords().
getMutationWeight()
double denoptim.programs.denovo.GAParameters.getMutationWeight ()
Definition at line 758 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.mutationWeight.
Referenced by denoptim.ga.EAUtils.chooseGenerationMethod(), and denoptim.ga.EvolutionaryAlgorithm.makeOffspringB().
getNumberOfChildren()
int denoptim.programs.denovo.GAParameters.getNumberOfChildren ()
Definition at line 722 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.numOfChildren.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation().
getNumberOfConvergenceGenerations()
int denoptim.programs.denovo.GAParameters.getNumberOfConvergenceGenerations ()
Definition at line 715 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.numConvGen.
Referenced by denoptim.ga.EvolutionaryAlgorithm.run().
getNumberOfCPU()
int denoptim.programs.denovo.GAParameters.getNumberOfCPU ()
Definition at line 506 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.numParallelTasks.
Referenced by denoptim.ga.EvolutionaryAlgorithm.EvolutionaryAlgorithm(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.processInitialPopCandidate(), and denoptim.ga.EvolutionaryAlgorithm.submitSyncParallelBatch().
getNumberOfGenerations()
int denoptim.programs.denovo.GAParameters.getNumberOfGenerations ()
Definition at line 680 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.numGenerations.
Referenced by denoptim.ga.EAUtils.getPathNameToGenerationDetailsFile(), denoptim.ga.EAUtils.getPathNameToGenerationFolder(), and denoptim.ga.EvolutionaryAlgorithm.run().
getParallelizationScheme()
int denoptim.programs.denovo.GAParameters.getParallelizationScheme ()
Definition at line 818 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.parallelizationScheme.
Referenced by denoptim.ga.EvolutionaryAlgorithm.EvolutionaryAlgorithm().
getPopulationSize()
int denoptim.programs.denovo.GAParameters.getPopulationSize ()
Definition at line 673 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.populationSize.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.initializePopulation(), denoptim.ga.EvolutionaryAlgorithm.processInitialPopCandidate(), denoptim.ga.EvolutionaryAlgorithm.run(), and denoptim.ga.Population.trim().
getPrecisionLevel()
int denoptim.programs.denovo.GAParameters.getPrecisionLevel ()
Definition at line 499 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.precisionLevel.
Referenced by denoptim.ga.EAUtils.getSummaryStatistics().
getPrintedList()
String denoptim.programs.denovo.GAParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1604 of file GAParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getReplacementStrategy()
int denoptim.programs.denovo.GAParameters.getReplacementStrategy ()
Definition at line 564 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.replacementStrategy.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.initializePopulation(), and denoptim.ga.EvolutionaryAlgorithm.run().
getSaveRingSystemsAsTemplatesNonScaff()
boolean denoptim.programs.denovo.GAParameters.getSaveRingSystemsAsTemplatesNonScaff ()
Definition at line 846 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesNonScaff.
Referenced by denoptim.ga.OffspringEvaluationTask.call().
getSaveRingSystemsAsTemplatesScaff()
boolean denoptim.programs.denovo.GAParameters.getSaveRingSystemsAsTemplatesScaff ()
Definition at line 853 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesScaffolds.
Referenced by denoptim.ga.OffspringEvaluationTask.call().
getSaveRingSystemsFitnessThreshold()
double denoptim.programs.denovo.GAParameters.getSaveRingSystemsFitnessThreshold ()
Definition at line 839 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.saveRingSystemsFitnessThreshold.
Referenced by denoptim.ga.OffspringEvaluationTask.call().
getSelectionStrategy()
String denoptim.programs.denovo.GAParameters.getSelectionStrategy ()
Definition at line 687 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.strXoverSelectionMode.
getSelectionStrategyType()
int denoptim.programs.denovo.GAParameters.getSelectionStrategyType ()
Definition at line 708 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.xoverSelectionMode.
Referenced by denoptim.ga.EAUtils.selectBasedOnFitness().
getSelectivePressure()
int denoptim.programs.denovo.GAParameters.getSelectivePressure ()
Definition at line 694 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.selectivePressure.
Referenced by denoptim.ga.SelectionHelper.performTournamentSelection().
getSymmetryProbability()
double denoptim.programs.denovo.GAParameters.getSymmetryProbability ()
Definition at line 772 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.symmetricSubProbability.
getUIDFileIn()
String denoptim.programs.denovo.GAParameters.getUIDFileIn ()
Definition at line 446 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.uidFileIn.
getUIDFileOut()
String denoptim.programs.denovo.GAParameters.getUIDFileOut ()
Definition at line 453 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.uidFileOut.
Referenced by denoptim.ga.EvolutionaryAlgorithm.EvolutionaryAlgorithm(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), and denoptim.ga.EvolutionaryAlgorithm.processInitialPopCandidate().
getVisitedGraphsFile()
String denoptim.programs.denovo.GAParameters.getVisitedGraphsFile ()
Definition at line 460 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.visitedGraphsFile.
interpretKeyword()
void denoptim.programs.denovo.GAParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 880 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.buildAnewFailureTolerant, denoptim.programs.denovo.GAParameters.builtAnewWeight, denoptim.programs.denovo.GAParameters.convertProbabilityScheme(), denoptim.programs.denovo.GAParameters.coupleMutationAndCrossover, denoptim.programs.denovo.GAParameters.crossoverWeight, denoptim.programs.denovo.GAParameters.crowdingMultiplier, denoptim.programs.denovo.GAParameters.crowdingProbabilityScheme, denoptim.programs.denovo.GAParameters.crowdingSigmaMiddle, denoptim.programs.denovo.GAParameters.crowdingSigmaSteepness, denoptim.programs.denovo.GAParameters.dumpMonitor, denoptim.programs.denovo.GAParameters.excludedMutationTypes, denoptim.programs.denovo.GAParameters.initMolsToFragmentFile, denoptim.programs.denovo.GAParameters.initPoplnFile, denoptim.programs.denovo.GAParameters.keepBestSibling, denoptim.programs.denovo.GAParameters.lvlGrowthMultiplier, denoptim.programs.denovo.GAParameters.lvlGrowthProbabilityScheme, denoptim.programs.denovo.GAParameters.lvlGrowthSigmaMiddle, denoptim.programs.denovo.GAParameters.lvlGrowthSigmaSteepness, denoptim.programs.denovo.GAParameters.maxGeneticOpAttempts, denoptim.programs.denovo.GAParameters.maxOffsprintFromXover, denoptim.programs.denovo.GAParameters.maxRingsAddedByMutation, denoptim.programs.denovo.GAParameters.maxTriesPerPop, denoptim.programs.denovo.GAParameters.maxXOverableSubGraphSize, denoptim.programs.denovo.GAParameters.molGrowthMultiplier, denoptim.programs.denovo.GAParameters.molGrowthProbabilityScheme, denoptim.programs.denovo.GAParameters.molGrowthSigmaMiddle, denoptim.programs.denovo.GAParameters.molGrowthSigmaSteepness, denoptim.programs.denovo.GAParameters.monitorDumpStep, denoptim.programs.denovo.GAParameters.monitorFile, denoptim.programs.denovo.GAParameters.mutatedGraphFailedEvalTolerant, denoptim.programs.denovo.GAParameters.mutationFailureTolerant, denoptim.programs.denovo.GAParameters.mutationWeight, denoptim.programs.denovo.GAParameters.mutliSiteMutationWeights, denoptim.programs.denovo.GAParameters.nanFitnessKillsExperiment, denoptim.programs.denovo.GAParameters.numConvGen, denoptim.programs.denovo.GAParameters.numGenerations, denoptim.programs.denovo.GAParameters.numOfChildren, denoptim.programs.denovo.GAParameters.numParallelTasks, denoptim.programs.denovo.GAParameters.parallelizationScheme, denoptim.programs.denovo.GAParameters.parentsSurvive, denoptim.programs.denovo.GAParameters.populationSize, denoptim.programs.denovo.GAParameters.precisionLevel, denoptim.programs.RunTimeParameters.readYesNoTrueFalse(), denoptim.programs.denovo.GAParameters.recordMateSelection, denoptim.programs.denovo.GAParameters.replacementStrategy, denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesNonScaff, denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesScaffolds, denoptim.programs.denovo.GAParameters.saveRingSystemsFitnessThreshold, denoptim.programs.denovo.GAParameters.seed, denoptim.programs.denovo.GAParameters.selectivePressure, denoptim.programs.denovo.GAParameters.sortOrderDecreasing, denoptim.programs.denovo.GAParameters.strXoverSelectionMode, denoptim.programs.denovo.GAParameters.symmetricSubProbability, denoptim.programs.denovo.GAParameters.uidFileIn, denoptim.programs.denovo.GAParameters.uidFileOut, denoptim.programs.denovo.GAParameters.useLevelBasedProb, denoptim.programs.denovo.GAParameters.useMolSizeBasedProb, denoptim.programs.RunTimeParameters.verbosity, denoptim.programs.denovo.GAParameters.writePopOnDisk, denoptim.programs.denovo.GAParameters.xoverFailureTolerant, denoptim.programs.denovo.GAParameters.xoverGraphFailedEvalTolerant, and denoptim.programs.denovo.GAParameters.xoverSelectionMode.
Referenced by denoptim.programs.denovo.GAParametersTest.testInterpretationOfKeywords(), and denoptim.programs.denovo.GAParametersTest.testYesNoTrueFalseKeyword().
isNanFitnessKillsExperiment()
boolean denoptim.programs.denovo.GAParameters.isNanFitnessKillsExperiment ()
Definition at line 520 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.nanFitnessKillsExperiment.
isSortOrderDecreasing()
boolean denoptim.programs.denovo.GAParameters.isSortOrderDecreasing ()
Definition at line 513 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.sortOrderDecreasing.
keepBestSibling()
boolean denoptim.programs.denovo.GAParameters.keepBestSibling ()
Returns
true if we want to keep only the best among the two sibling that result from a single crossover.
Definition at line 751 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.keepBestSibling.
maxOffsprintFromXover()
int denoptim.programs.denovo.GAParameters.maxOffsprintFromXover ()
Returns
the maximum number of offspring produced by a single crossover operation.
Definition at line 740 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.maxOffsprintFromXover.
parentsSurvive()
boolean denoptim.programs.denovo.GAParameters.parentsSurvive ()
Returns
the flag controlling if parents are allowed to survive multiple generation or not.
Definition at line 575 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.parentsSurvive.
processParameters()
void denoptim.programs.denovo.GAParameters.processParameters () throws DENOPTIMException
Processes currently loaded fields.
Exceptions
DENOPTIMException typically due to I/O exception.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1466 of file GAParameters.java.
References denoptim.utils.MutationType.ADDFUSEDRING, denoptim.utils.MutationType.ADDRING, denoptim.graph.rings.RingClosureParameters.allowRingClosures(), denoptim.logging.StaticLogger.appLogger, denoptim.programs.RunTimeParameters.containsParameters(), denoptim.programs.denovo.GAParameters.createWorkingDirectory(), denoptim.programs.denovo.GAParameters.dataDir, denoptim.constants.DENOPTIMConstants.EOL, denoptim.programs.denovo.GAParameters.excludedMutationTypes, denoptim.programs.RunTimeParameters.getParameters(), denoptim.programs.RunTimeParameters.getRandomSeed(), denoptim.programs.RunTimeParameters.isMaster, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.denovo.GAParameters.numParallelTasks, denoptim.programs.denovo.GAParameters.populationSize, denoptim.programs.RunTimeParameters.processOtherParameters(), denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.programs.denovo.GAParameters.seed, denoptim.programs.denovo.GAParameters.selectivePressure, and denoptim.programs.RunTimeParameters.startRandomizer().
Referenced by denoptim.programs.denovo.GARunner.runProgram(), and denoptim.programs.denovo.GAParametersTest.testLogging().
recordMateSelection()
boolean denoptim.programs.denovo.GAParameters.recordMateSelection ()
Returns
true if we are asked to print the selected mates to file.
Definition at line 492 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.recordMateSelection.
savePopFile()
boolean denoptim.programs.denovo.GAParameters.savePopFile ()
Returns
true if we are configures to save all population members each time we report the population details on file.
Definition at line 1635 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.writePopOnDisk.
setPopulationSize()
void denoptim.programs.denovo.GAParameters.setPopulationSize (int size)
Definition at line 666 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.populationSize.
Referenced by denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
setWorkingDirectory()
void denoptim.programs.denovo.GAParameters.setWorkingDirectory (String pathName)
Definition at line 548 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.dataDir, denoptim.programs.denovo.GAParameters.DEFUIDFILEOUTNAME, denoptim.programs.denovo.GAParameters.interfaceDir, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.denovo.GAParameters.monitorFile, and denoptim.programs.denovo.GAParameters.uidFileOut.
Referenced by denoptim.programs.denovo.GAParameters.createWorkingDirectory(), denoptim.programs.denovo.GARunner.runProgram(), denoptim.programs.denovo.GAParametersTest.testLogging(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
useLevelBasedProb()
boolean denoptim.programs.denovo.GAParameters.useLevelBasedProb ()
Definition at line 811 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.useLevelBasedProb.
useMolSizeBasedProb()
boolean denoptim.programs.denovo.GAParameters.useMolSizeBasedProb ()
Definition at line 804 of file GAParameters.java.
References denoptim.programs.denovo.GAParameters.useMolSizeBasedProb.
Member Data Documentation
buildAnewFailureTolerant
boolean denoptim.programs.denovo.GAParameters.buildAnewFailureTolerant = true
Flag that enables the ignoring of construction from scratch events triggering exceptions.
Such events will still be recorded in the GA run Monitor.
Definition at line 420 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword().
builtAnewWeight
double denoptim.programs.denovo.GAParameters.builtAnewWeight = 1.0 protected
The relative weight at which construction from scratch is performed.
Definition at line 260 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getConstructionWeight(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
coupleMutationAndCrossover
boolean denoptim.programs.denovo.GAParameters.coupleMutationAndCrossover = false protected
Flag defining if we want mutation to occur on offspring that result from crossover (i.e., mutation and crossover are coupled), otherwise we want to mutate population members irrespectively on crossover.
Definition at line 255 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.coupleMutationAndCrossover(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
crossoverWeight
double denoptim.programs.denovo.GAParameters.crossoverWeight = 1.0 protected
The relative weight at which crossover is performed.
Definition at line 265 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getCrossoverWeight(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
crowdingMultiplier
double denoptim.programs.denovo.GAParameters.crowdingMultiplier = 0.5 protected
Parameter controlling the crowding probability function of types 'EXP_DIFF' and 'TANH'.
Definition at line 225 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getCrowdingMultiplier(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
crowdingProbabilityScheme
int denoptim.programs.denovo.GAParameters.crowdingProbabilityScheme = 3 protected
Definition of the crowding probability function.
By default, the probability of using an AP that is hosted on an atom that already has an used AP is 100%.
Definition at line 219 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getCrowdingProbabilityScheme(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
crowdingSigmaMiddle
double denoptim.programs.denovo.GAParameters.crowdingSigmaMiddle = 2.5 protected
Parameters controlling the crowding probability function of type 'SIGMA': level at which p=50% (can be a float)
Definition at line 237 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getCrowdingFactorMiddleSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
crowdingSigmaSteepness
double denoptim.programs.denovo.GAParameters.crowdingSigmaSteepness = 1.0 protected
Parameters controlling the crowding probability function of type 'SIGMA': steepness of the function where p=50%.
Definition at line 231 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getCrowdingFactorSteepSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
dataDir
String denoptim.programs.denovo.GAParameters.dataDir = System.getProperty("user.dir") private
Pathname to the working directory for the current run.
Definition at line 55 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.createWorkingDirectory(), denoptim.programs.denovo.GAParameters.getDataDirectory(), denoptim.programs.denovo.GAParameters.processParameters(), and denoptim.programs.denovo.GAParameters.setWorkingDirectory().
DEFUIDFILEOUTNAME
final String denoptim.programs.denovo.GAParameters.DEFUIDFILEOUTNAME = "MOLUID.txt" private
Default name of the UIDFileOut.
Definition at line 101 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.setWorkingDirectory().
dumpMonitor
boolean denoptim.programs.denovo.GAParameters.dumpMonitor = false protected
Flag controlling if we dump monitored data or not.
Definition at line 338 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.dumpMonitor(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.ga.EvolutionaryAlgorithm.initializePopulation(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
excludedMutationTypes
List<MutationType> denoptim.programs.denovo.GAParameters.excludedMutationTypes = new ArrayList<MutationType>() package
Mutation types that are excluded everywhere.
Definition at line 297 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getExcludedMutationTypes(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.processParameters().
initMolsToFragmentFile
String denoptim.programs.denovo.GAParameters.initMolsToFragmentFile = null protected
Pathname to the file collecting molecules to fragment to generate initial population.
Definition at line 74 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getInitMolsToFragmentFile(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
initPoplnFile
String denoptim.programs.denovo.GAParameters.initPoplnFile = "" protected
Pathname of the initial population file.
The file itself can be an SDF or a list of pathnames
Definition at line 68 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getInitialPopulationFile(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
interfaceDir
String denoptim.programs.denovo.GAParameters.interfaceDir private
Initial value:
= dataDir
            + System.getProperty("file.separator") + "interface"
Pathname to the interface directory for the current run.
This is the pathname that is watched for external instructions
Definition at line 61 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.createWorkingDirectory(), denoptim.programs.denovo.GAParameters.getInterfaceDir(), and denoptim.programs.denovo.GAParameters.setWorkingDirectory().
keepBestSibling
boolean denoptim.programs.denovo.GAParameters.keepBestSibling = false protected
Flag controlling if we choose the best sibling out of crossover.
Definition at line 292 of file GAParameters.java.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.keepBestSibling().
lvlGrowthMultiplier
double denoptim.programs.denovo.GAParameters.lvlGrowthMultiplier = 0.5 protected
Parameter controlling the growth probability function of types 'EXP_DIFF' and 'TANH'.
Definition at line 165 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getGrowthMultiplier(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
lvlGrowthProbabilityScheme
int denoptim.programs.denovo.GAParameters.lvlGrowthProbabilityScheme = 0 protected
Definition of the growth probability function:
Definition at line 159 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getGrowthProbabilityScheme(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
lvlGrowthSigmaMiddle
double denoptim.programs.denovo.GAParameters.lvlGrowthSigmaMiddle = 2.5 protected
Parameters controlling the growth probability function of type 'SIGMA': level at which p=50% (can be a float)
Definition at line 177 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getGrowthFactorMiddleSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
lvlGrowthSigmaSteepness
double denoptim.programs.denovo.GAParameters.lvlGrowthSigmaSteepness = 1.0 protected
Parameters controlling the growth probability function of type 'SIGMA': steepness of the function where p=50%.
Definition at line 171 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getGrowthFactorSteepSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
maxGeneticOpAttempts
int denoptim.programs.denovo.GAParameters.maxGeneticOpAttempts = 100 protected
Maximum number of attempts to perform any genetic operation (i.e., either crossover or mutation) on any parents before giving up.
Definition at line 139 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMaxGeneticOpAttempts(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
maxOffsprintFromXover
int denoptim.programs.denovo.GAParameters.maxOffsprintFromXover = 1 protected
Number of offspring that a single crossover operation can produce.
Definition at line 287 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.maxOffsprintFromXover().
maxRingsAddedByMutation
int denoptim.programs.denovo.GAParameters.maxRingsAddedByMutation = 1 protected
Maximum number of rings added by a single mutation operation.
Definition at line 348 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMaxRingsAddedByMutation(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
maxTriesPerPop
int denoptim.programs.denovo.GAParameters.maxTriesPerPop = 25 protected
Factor controlling the maximum number of attempts to build a graph so that the maximum number of attempts = factor * population size.
Definition at line 133 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMaxTriesFactor(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
maxUIDMemory
int denoptim.programs.denovo.GAParameters.maxUIDMemory = 1000000
Maximum number of unique identifiers kept in memory.
Beyond this value the identifiers are dealt with using a file on disk.
Definition at line 380 of file GAParameters.java.
Referenced by denoptim.ga.EvolutionaryAlgorithm.EvolutionaryAlgorithm().
maxXOverableSubGraphSize
int denoptim.programs.denovo.GAParameters.maxXOverableSubGraphSize = 20
Limit to the size of subgraphs that are exchanged during crossover.
Definition at line 425 of file GAParameters.java.
Referenced by denoptim.ga.Population.getXoverPartners(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.genetweeker.GeneOpsRunner.runXOver().
minFitnessSD
double denoptim.programs.denovo.GAParameters.minFitnessSD = 0.000001 protected
Minimal standard deviation accepted in the fitness values of the initial population.
Definition at line 343 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMinFitnessSD().
molGrowthMultiplier
double denoptim.programs.denovo.GAParameters.molGrowthMultiplier = 0.5 protected
Parameter controlling the molGrowth probability function of types 'EXP_DIFF' and 'TANH'.
Definition at line 200 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMolGrowthMultiplier(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
molGrowthProbabilityScheme
int denoptim.programs.denovo.GAParameters.molGrowthProbabilityScheme = 2 protected
Definition of the molGrowth probability function:
Definition at line 194 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMolGrowthProbabilityScheme(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
molGrowthSigmaMiddle
double denoptim.programs.denovo.GAParameters.molGrowthSigmaMiddle = 25 protected
Parameters controlling the molGrowth probability function of type 'SIGMA': level at which p=50% (can be a float)
Definition at line 212 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMolGrowthFactorMiddleSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
molGrowthSigmaSteepness
double denoptim.programs.denovo.GAParameters.molGrowthSigmaSteepness = 0.2 protected
Parameters controlling the molGrowth probability function of type 'SIGMA': steepness of the function where p=50%.
Definition at line 206 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMolGrowthFactorSteepSigma(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
monitorDumpStep
int denoptim.programs.denovo.GAParameters.monitorDumpStep = 50 protected
Monitor dumps step.
The EA Monitor will dump data to file every this number of new attempts to generate candidate.
Definition at line 333 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMonitorDumpStep(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
monitorFile
String denoptim.programs.denovo.GAParameters.monitorFile = "" private
Pathname of file where EA monitors dumps are printed.
Definition at line 91 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMonitorFile(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.setWorkingDirectory().
mutatedGraphFailedEvalTolerant
boolean denoptim.programs.denovo.GAParameters.mutatedGraphFailedEvalTolerant = true
Flag that enables the ignoring of mutated graphs that lead to a failure in the evaluation of graphs that generates SMILES, InChI and molecular representation.
Definition at line 393 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParametersTest.testYesNoTrueFalseKeyword().
mutationFailureTolerant
boolean denoptim.programs.denovo.GAParameters.mutationFailureTolerant = true
Flag that enables the ignoring of mutation events triggering exceptions.
Such events will still be recorded in the GA run Monitor.
Definition at line 413 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword().
mutationWeight
double denoptim.programs.denovo.GAParameters.mutationWeight = 1.0 protected
The relative weight at which mutation is performed.
Definition at line 247 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getMutationWeight(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
mutliSiteMutationWeights
double [] denoptim.programs.denovo.GAParameters.mutliSiteMutationWeights = new double[]{0,10,1} private
The weights of multi-site mutations.
Definition at line 374 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getMultiSiteMutationWeights(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
nanFitnessKillsExperiment
boolean denoptim.programs.denovo.GAParameters.nanFitnessKillsExperiment = false protected
Flag controlling whether we allow NaN fitness to kill design experiments.
Definition at line 322 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.isNanFitnessKillsExperiment().
numConvGen
int denoptim.programs.denovo.GAParameters.numConvGen = 5 protected
Number of identical generations before convergence is reached.
Definition at line 122 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getNumberOfConvergenceGenerations(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
numGenerations
int denoptim.programs.denovo.GAParameters.numGenerations = 100 protected
Maximum number of generations to run for.
Definition at line 127 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getNumberOfGenerations(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
numOfChildren
int denoptim.programs.denovo.GAParameters.numOfChildren = 5 protected
Number of children (i.e., new offspring) to be produced in each generation.
Definition at line 117 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getNumberOfChildren(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
numParallelTasks
int denoptim.programs.denovo.GAParameters.numParallelTasks = 0 protected
Maximum number of parallel tasks.
Definition at line 312 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getNumberOfCPU(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.processParameters().
parallelizationScheme
int denoptim.programs.denovo.GAParameters.parallelizationScheme = 1 protected
Parallelization scheme: synchronous or asynchronous.
Definition at line 307 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getParallelizationScheme(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
parentsSurvive
boolean denoptim.programs.denovo.GAParameters.parentsSurvive = true protected
Flag defining if population members can survive multiple generations (when this variable is true) or the population is refreshed at every generation (when this variable is false).
Definition at line 154 of file GAParameters.java.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.parentsSurvive().
populationSize
int denoptim.programs.denovo.GAParameters.populationSize = 50 protected
Size of the population.
Definition at line 111 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getPopulationSize(), denoptim.programs.denovo.GAParameters.interpretKeyword(), denoptim.programs.denovo.GAParameters.processParameters(), and denoptim.programs.denovo.GAParameters.setPopulationSize().
precisionLevel
int denoptim.programs.denovo.GAParameters.precisionLevel = 3 protected
Precision for reporting the value of the fitness.
Definition at line 327 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getPrecisionLevel(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
recordMateSelection
boolean denoptim.programs.denovo.GAParameters.recordMateSelection = false private
Flag defining whether we record which mates are selected or not.
Definition at line 96 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), denoptim.programs.denovo.GAParameters.recordMateSelection(), and denoptim.ga.EAUtils.selectBasedOnFitness().
replacementStrategy
int denoptim.programs.denovo.GAParameters.replacementStrategy = 1 protected
Replacement strategy: 1) replace worst individuals with new ones that are better than the worst, 2) no replacement (the population keeps growing).
Obviously, with strategy 2 we consume a lot of resources.
Definition at line 146 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getReplacementStrategy(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
saveRingSystemsAsTemplatesNonScaff
boolean denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesNonScaff = false protected
Flag controlling the possibility of collecting cyclic graph systems that do NOT include a scaffold and save them as new template non-scaffold building blocks.
Definition at line 361 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSaveRingSystemsAsTemplatesNonScaff(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
saveRingSystemsAsTemplatesScaffolds
boolean denoptim.programs.denovo.GAParameters.saveRingSystemsAsTemplatesScaffolds = false protected
Flag controlling the possibility of collecting cyclic graph systems that include a scaffold and save them as new template scaffolds.
Definition at line 354 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSaveRingSystemsAsTemplatesScaff(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
saveRingSystemsFitnessThreshold
double denoptim.programs.denovo.GAParameters.saveRingSystemsFitnessThreshold = 0.10 protected
Fitness threshold for adding template to building block libraries.
This is expressed as percentage, i.e., if the fitness is in the best X% of the population, then the template is added to the scaffold/vertex library.
Definition at line 369 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSaveRingSystemsFitnessThreshold(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
seed
long denoptim.programs.denovo.GAParameters.seed = 0L protected
The seed value for random number generation.
Definition at line 302 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.processParameters().
selectivePressure
int denoptim.programs.denovo.GAParameters.selectivePressure = -1 protected
Intensity for selecting high fitness parents.
For tournament selection acts as the size of the tournament pool. Default value is calculated from population size.
Definition at line 282 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSelectivePressure(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.processParameters().
sortOrderDecreasing
boolean denoptim.programs.denovo.GAParameters.sortOrderDecreasing = true protected
Flag controlling how to sort the population based on the fitness.
Definition at line 317 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.isSortOrderDecreasing().
strXoverSelectionMode
String denoptim.programs.denovo.GAParameters.strXoverSelectionMode = xoverSelectionMode+"" protected
Crossover parents selection strategy: string.
Definition at line 275 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSelectionStrategy(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
symmetricSubProbability
double denoptim.programs.denovo.GAParameters.symmetricSubProbability = 0.8 protected
The probability at which symmetric substitution occurs.
Definition at line 242 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.programs.denovo.GAParameters.getSymmetryProbability(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
timeStamp
String denoptim.programs.denovo.GAParameters.timeStamp = "NOTIMESTAMP"
Time stamp identifying this run.
Definition at line 50 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.createWorkingDirectory().
uidFileIn
String denoptim.programs.denovo.GAParameters.uidFileIn = "" protected
Pathname of the file with the list of individuals unique identifiers that are initially known.
Definition at line 80 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getUIDFileIn(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
uidFileOut
String denoptim.programs.denovo.GAParameters.uidFileOut = "" protected
Pathname of the file where the individuals unique identifiers will be recorded.
Definition at line 86 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getUIDFileOut(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.setWorkingDirectory().
uidMemoryOnDisk
String denoptim.programs.denovo.GAParameters.uidMemoryOnDisk = "memory_UIDs.txt"
Text file used to store unique identifiers beyond the limits of the memory (see GAParameters#maxUIDMemory).
Definition at line 386 of file GAParameters.java.
Referenced by denoptim.ga.EvolutionaryAlgorithm.EvolutionaryAlgorithm().
useLevelBasedProb
boolean denoptim.programs.denovo.GAParameters.useLevelBasedProb = false protected
Flag recording the intention to use level-controlled graph extension probability.
Definition at line 183 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.ga.EAUtils.getGrowthByLevelProbability(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.useLevelBasedProb().
useMolSizeBasedProb
boolean denoptim.programs.denovo.GAParameters.useMolSizeBasedProb = false protected
Flag recording the intention to use molecular size-controlled graph extension probability.
Definition at line 189 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.checkParameters(), denoptim.ga.EAUtils.getMolSizeProbability(), denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.useMolSizeBasedProb().
visitedGraphsFile
String denoptim.programs.denovo.GAParameters.visitedGraphsFile = "GRAPHS.txt" protected
Pathname to the file containing the list of previously visited graph.
Definition at line 106 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getVisitedGraphsFile().
writePopOnDisk
boolean denoptim.programs.denovo.GAParameters.writePopOnDisk = false protected
Flag requesting to write a SDF file that collects all the population members each time we report the population details on file.
Definition at line 431 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.savePopFile().
xoverFailureTolerant
boolean denoptim.programs.denovo.GAParameters.xoverFailureTolerant = true
Flag that enables the ignoring of crossover events triggering exceptions.
Such events will still be recorded in the GA run Monitor.
Definition at line 407 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword().
xoverGraphFailedEvalTolerant
boolean denoptim.programs.denovo.GAParameters.xoverGraphFailedEvalTolerant = true
Flag that enables the ignoring of crossover-ed graphs that lead to a f ailure in the evaluation of graphs that generates SMILES, InChI and molecular representation.
Definition at line 401 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.interpretKeyword().
xoverSelectionMode
int denoptim.programs.denovo.GAParameters.xoverSelectionMode = 3 protected
Crossover parents selection strategy: integer code.
Definition at line 270 of file GAParameters.java.
Referenced by denoptim.programs.denovo.GAParameters.getSelectionStrategyType(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/denovo/GAParameters.java