DENOPTIM: denoptim.utils.ObjectPair Class Reference
denoptim.utils.ObjectPair Class Reference
This class is the equivalent of the Pair data structure used in C++ Although AbstractMap.SimpleImmutableEntry<K,V>> is available it does not have a setValue method.
Public Member Functions
ObjectPair ()
ObjectPair (Object o1, Object o2)
boolean isSame (Object o1, Object o2)
Object getFirst ()
Object getSecond ()
void setFirst (Object o)
void setSecond (Object o)
boolean equals (Object obj)
int hashCode ()
String toString ()
Private Attributes
Object o1
Object o2
Detailed Description
This class is the equivalent of the Pair data structure used in C++ Although AbstractMap.SimpleImmutableEntry<K,V>> is available it does not have a setValue method.
Author
Vishwesh Venkatraman
Definition at line 29 of file ObjectPair.java.
Constructor & Destructor Documentation
ObjectPair() [1/2]
denoptim.utils.ObjectPair.ObjectPair ()
Definition at line 36 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1, and denoptim.utils.ObjectPair.o2.
Referenced by denoptim.utils.ObjectPair.equals().
ObjectPair() [2/2]
denoptim.utils.ObjectPair.ObjectPair (Object o1, Object o2)
Definition at line 44 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1, and denoptim.utils.ObjectPair.o2.
Member Function Documentation
equals()
boolean denoptim.utils.ObjectPair.equals (Object obj)
Definition at line 88 of file ObjectPair.java.
References denoptim.utils.ObjectPair.isSame(), denoptim.utils.ObjectPair.o1, denoptim.utils.ObjectPair.o2, and denoptim.utils.ObjectPair.ObjectPair().
getFirst()
Object denoptim.utils.ObjectPair.getFirst ()
Definition at line 59 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1.
Referenced by denoptim.graph.rings.CyclicGraphHandler.combineCompatPathSubGraphs(), and denoptim.integration.tinker.TinkerUtils.getICFromIAC().
getSecond()
Object denoptim.utils.ObjectPair.getSecond ()
Definition at line 66 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o2.
Referenced by denoptim.graph.rings.CyclicGraphHandler.combineCompatPathSubGraphs(), and denoptim.integration.tinker.TinkerUtils.getICFromIAC().
hashCode()
int denoptim.utils.ObjectPair.hashCode ()
Definition at line 103 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1, and denoptim.utils.ObjectPair.o2.
isSame()
boolean denoptim.utils.ObjectPair.isSame (Object o1, Object o2)
Definition at line 52 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1, and denoptim.utils.ObjectPair.o2.
Referenced by denoptim.utils.ObjectPair.equals().
setFirst()
void denoptim.utils.ObjectPair.setFirst (Object o)
Definition at line 73 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1.
setSecond()
void denoptim.utils.ObjectPair.setSecond (Object o)
Definition at line 80 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o2.
toString()
String denoptim.utils.ObjectPair.toString ()
Definition at line 112 of file ObjectPair.java.
References denoptim.utils.ObjectPair.o1, and denoptim.utils.ObjectPair.o2.
Member Data Documentation
o1
Object denoptim.utils.ObjectPair.o1 private
Definition at line 31 of file ObjectPair.java.
Referenced by denoptim.utils.ObjectPair.equals(), denoptim.utils.ObjectPair.getFirst(), denoptim.utils.ObjectPair.hashCode(), denoptim.utils.ObjectPair.isSame(), denoptim.utils.ObjectPair.ObjectPair(), denoptim.utils.ObjectPair.setFirst(), and denoptim.utils.ObjectPair.toString().
o2
Object denoptim.utils.ObjectPair.o2 private
Definition at line 32 of file ObjectPair.java.
Referenced by denoptim.utils.ObjectPair.equals(), denoptim.utils.ObjectPair.getSecond(), denoptim.utils.ObjectPair.hashCode(), denoptim.utils.ObjectPair.isSame(), denoptim.utils.ObjectPair.ObjectPair(), denoptim.utils.ObjectPair.setSecond(), and denoptim.utils.ObjectPair.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/utils/ObjectPair.java