DENOPTIM: denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator Class Reference
denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator Class Reference
Compares the Molecule3DBuilder afters ring closing-biased conformational adaptation.
Public Member Functions
int compare (ChemicalObjectModel mA, ChemicalObjectModel mB)
Detailed Description
Compares the Molecule3DBuilder afters ring closing-biased conformational adaptation.
Criteria for the evaluation are (i) the number of closed rings, (ii) the sum of the overall quality of all new RingClosures, and (iii) the evaluation of atom proximity (dummy atoms excluded). Note that this comparator sorts in DESCENDING order.
Definition at line 197 of file RingClosureTool.java.
Member Function Documentation
compare()
int denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator.compare (ChemicalObjectModel mA, ChemicalObjectModel mB)
Definition at line 199 of file RingClosureTool.java.
References denoptim.molecularmodeling.ChemicalObjectModel.getAtomOverlapScore(), denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosures(), and denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosuresQuality().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/RingClosureTool.java