DENOPTIM: denoptim.gui.FragmentViewPanel Class Reference
denoptim.gui.FragmentViewPanel Class Reference
A panel with a molecular viewer and attachment point table.
Classes
class PausableTableModelListener
Public Member Functions
FragmentViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
FragmentViewPanel (JComponent parent, boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
FragmentViewPanel (JComponent parent, boolean editableTable, int dividerPosition)
Constructor that allows to specify whether the AP table is editable or not.
boolean hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
void deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
String getDataFromJmol ()
boolean loadSMILES (String smiles)
Loads a molecule build from a smiles string.
Fragment getLoadedStructure ()
Returns the chemical representation of the currently loaded chemical object.
void loadPlainStructure (IAtomContainer mol)
Loads a structure in the Jmol viewer.
void loadFragmentToViewer (Fragment frag)
Loads the given fragments to this viewer.
void clearAll (boolean dataIsComing)
Removes the currently visualized molecule and AP table.
void clearAPTable ()
Clears the table of attachment points.
void clearMolecularViewer (boolean dataIsComing)
Clears the molecular viewer.
ArrayList< AttachmentPoint > getSelectedAPs ()
Identifies which attachment points are selected in the visualized table.
ArrayList< Integer > getSelectedAPIDs ()
Identifies which attachment points are selected in the visualized table.
ArrayList< IAtom > getAtomsSelectedFromJMol ()
Identifies the atoms that are selected in the Jmol viewer.
void activateTabEditsListener (boolean var)
Allows to activate and deactivate the listener.
void dispose ()
Map< Integer, AttachmentPoint > getMapOfAPsInTable ()
DefaultTableModel getAPTableModel ()
ArrayList< Integer > getSelectedAPIDs ()
Map< Integer, AttachmentPoint > getMapOfAPsInTable ()
DefaultTableModel getAPTableModel ()
Public Attributes
boolean alteredAPData = false
Flag signalling that data about APs has been changed in the GUI.
Public Attributes inherited from denoptim.gui.IVertexAPSelection
final String APDATACHANGEEVENT = "APDATA"
Protected Attributes
Map< Integer, AttachmentPoint > mapAPs = null
Temporary list of attachment points of the current fragment.
DefaultTableModel apTabModel
JTable apTable
Private Member Functions
void initialize (int dividerPosition)
void waitForJmolViewer (int milliSecFirst, String cause)
Waits until Jmol is finished.
void make3DusingCDKgenerator (String smiles) throws CDKException, CloneNotSupportedException, IOException
IAtomContainer getStructureFromJmolViewer () throws DENOPTIMException
void putAPsFromTableIntoIAtomContainer (Fragment mol) throws DENOPTIMException
void loadStructure ()
Loads the structure of the currently loaded 'fragment' (i.e., our member) into the Jmol viewer.
void updateAPsMapAndTable ()
Uses the AP of the Fragment to create a new map and table of APs.
void preSelectAPs ()
void updateAPsInJmolViewer ()
String getJmolPositionStr (double[] position)
void setJmolViewer ()
Private Attributes
Fragment fragment
The currently loaded fragment.
JmolPanel jmolPanel
JScrollPane tabPanel
boolean editableAPTable = false
final String NL = System.getProperty("line.separator")
String tmpSDFFile
JComponent parent
Static Private Attributes
static final long serialVersionUID = 912850110991449553L
Version UID.
Detailed Description
A panel with a molecular viewer and attachment point table.
Author
Marco Foscato
Definition at line 78 of file FragmentViewPanel.java.
Constructor & Destructor Documentation
FragmentViewPanel() [1/3]
denoptim.gui.FragmentViewPanel.FragmentViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
editableTable use true to make the AP table editable
Definition at line 121 of file FragmentViewPanel.java.
FragmentViewPanel() [2/3]
denoptim.gui.FragmentViewPanel.FragmentViewPanel (JComponent parent, boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
parent the parent component
editableTable use true to make the AP table editable
Definition at line 134 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.parent.
FragmentViewPanel() [3/3]
denoptim.gui.FragmentViewPanel.FragmentViewPanel (JComponent parent, boolean editableTable, int dividerPosition)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
parent the parent component
editableTable use true to make the AP table editable
dividerPosition allows to set the initial position of the divide
Definition at line 148 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.editableAPTable, denoptim.gui.FragmentViewPanel.initialize(), and denoptim.gui.FragmentViewPanel.parent.
Member Function Documentation
activateTabEditsListener()
void denoptim.gui.FragmentViewPanel.activateTabEditsListener (boolean var)
Allows to activate and deactivate the listener.
Parameters
var use true to activate the listener
Definition at line 1043 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.apTabModel, and denoptim.gui.FragmentViewPanel.PausableTableModelListener.setActive().
Referenced by denoptim.gui.VertexViewPanel.activateTabEditsListener(), denoptim.gui.FragmentViewPanel.clearAPTable(), denoptim.gui.FragmentViewPanel.preSelectAPs(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
clearAll()
void denoptim.gui.FragmentViewPanel.clearAll (boolean dataIsComing)
Removes the currently visualized molecule and AP table.
Parameters
dataIsComing set true when there is incoming molecular data to visualize. In such case we do not run the very slow zap script in JMol because the molecular data will be overwritten anyway.
Definition at line 841 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearAPTable(), and denoptim.gui.FragmentViewPanel.clearMolecularViewer().
Referenced by denoptim.gui.GraphVertexMolViewerPanel.clearVertexViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
clearAPTable()
void denoptim.gui.FragmentViewPanel.clearAPTable ()
Clears the table of attachment points.
Definition at line 852 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.activateTabEditsListener(), and denoptim.gui.FragmentViewPanel.apTabModel.
Referenced by denoptim.gui.FragmentViewPanel.clearAll(), denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
clearMolecularViewer()
void denoptim.gui.FragmentViewPanel.clearMolecularViewer (boolean dataIsComing)
Clears the molecular viewer.
WARNING: this is VERY SLOW: do not do it unless you are sure you really need to clear the data. Typically, if there is incoming data, you do not need to run this, as the old data will be overwritten anyway.
Parameters
dataIsComing set true when there is incoming molecular data to visualize.
Definition at line 874 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.jmolPanel, and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.FragmentViewPanel.clearAll(), denoptim.gui.VertexViewPanel.clearMolecularViewer(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator(), and denoptim.gui.FragmentViewPanel.waitForJmolViewer().
deprotectEdits()
void denoptim.gui.FragmentViewPanel.deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
Use this after processing/saving the changes.
Definition at line 219 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.alteredAPData.
Referenced by denoptim.gui.VertexViewPanel.deprotectEdits().
dispose()
void denoptim.gui.FragmentViewPanel.dispose ()
Definition at line 1063 of file FragmentViewPanel.java.
References denoptim.gui.JmolPanel.dispose(), and denoptim.gui.FragmentViewPanel.jmolPanel.
Referenced by denoptim.gui.GraphVertexMolViewerPanel.dispose(), and denoptim.gui.VertexViewPanel.dispose().
getAPTableModel()
DefaultTableModel denoptim.gui.FragmentViewPanel.getAPTableModel ()
Implements denoptim.gui.IVertexAPSelection.
Definition at line 1079 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.apTabModel.
getAtomsSelectedFromJMol()
ArrayList< IAtom > denoptim.gui.FragmentViewPanel.getAtomsSelectedFromJMol ()
Identifies the atoms that are selected in the Jmol viewer.
Returns
the list of selected atoms
Definition at line 990 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Fragment.getAtom(), denoptim.graph.Fragment.getAtomCount(), denoptim.gui.FragmentViewPanel.jmolPanel, and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.VertexViewPanel.getAtomsSelectedFromJMol().
getDataFromJmol()
String denoptim.gui.FragmentViewPanel.getDataFromJmol ()
Definition at line 371 of file FragmentViewPanel.java.
References denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.gui.FragmentViewPanel.jmolPanel, and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), and denoptim.gui.FragmentViewPanel.loadSMILES().
getJmolPositionStr()
String denoptim.gui.FragmentViewPanel.getJmolPositionStr (double[] position) private
Definition at line 929 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer().
getLoadedStructure()
Fragment denoptim.gui.FragmentViewPanel.getLoadedStructure ()
Returns the chemical representation of the currently loaded chemical object.
In case of mismatch between the system loaded into the Jmol viewer and the one in the local memory, we take that from Jmol and made it be The 'current fragment'. Previously set references to the previous 'current fragment' will make no sense anymore.
Returns
the chemical representation of what is currently visualised. Can be empty and null.
Definition at line 607 of file FragmentViewPanel.java.
References denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Fragment.getAtom(), denoptim.graph.Fragment.getAtomCount(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.utils.MoleculeUtils.getSMILESForMolecule(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.GUI.GUILOGGER, denoptim.gui.FragmentViewPanel.putAPsFromTableIntoIAtomContainer(), and denoptim.gui.FragmentViewPanel.setJmolViewer().
Referenced by denoptim.gui.VertexViewPanel.getLoadedStructure().
getMapOfAPsInTable()
Map< Integer, AttachmentPoint > denoptim.gui.FragmentViewPanel.getMapOfAPsInTable ()
Implements denoptim.gui.IVertexAPSelection.
Definition at line 1071 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.mapAPs.
getSelectedAPIDs()
ArrayList< Integer > denoptim.gui.FragmentViewPanel.getSelectedAPIDs ()
Identifies which attachment points are selected in the visualized table.
Returns
the list of attachment points indexes
Implements denoptim.gui.IVertexAPSelection.
Definition at line 974 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.apTable.
getSelectedAPs()
ArrayList< AttachmentPoint > denoptim.gui.FragmentViewPanel.getSelectedAPs ()
Identifies which attachment points are selected in the visualized table.
Returns
the list of attachment points
Definition at line 956 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.apTable, and denoptim.gui.FragmentViewPanel.mapAPs.
getStructureFromJmolViewer()
IAtomContainer denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer () throws DENOPTIMException private
Definition at line 537 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearAPTable(), denoptim.gui.FragmentViewPanel.clearMolecularViewer(), denoptim.gui.FragmentViewPanel.getDataFromJmol(), denoptim.gui.FragmentViewPanel.NL, denoptim.io.DenoptimIO.readAllAtomContainers(), denoptim.gui.FragmentViewPanel.tmpSDFFile, and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.gui.FragmentViewPanel.getLoadedStructure(), denoptim.gui.FragmentViewPanel.loadSMILES(), and denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator().
hasUnsavedAPEdits()
boolean denoptim.gui.FragmentViewPanel.hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
Returns
true if there are unsaved edits
Definition at line 208 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.alteredAPData.
initialize()
void denoptim.gui.FragmentViewPanel.initialize (int dividerPosition) private
Definition at line 159 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.apTable, denoptim.gui.FragmentViewPanel.apTabModel, denoptim.gui.FragmentViewPanel.editableAPTable, denoptim.gui.Utils.getTempFile(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.tabPanel, and denoptim.gui.FragmentViewPanel.tmpSDFFile.
Referenced by denoptim.gui.FragmentViewPanel.FragmentViewPanel().
loadFragmentToViewer()
void denoptim.gui.FragmentViewPanel.loadFragmentToViewer (Fragment frag)
Loads the given fragments to this viewer.
The molecular data is loaded in the Jmol viewer, and the attachment point (AP) information in the the list of APs. Jmol is not aware of AP-related information, so this also launches the generation of the graphical objects representing the APs.
Parameters
frag the fragment to visualize
Definition at line 771 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.loadStructure(), denoptim.gui.FragmentViewPanel.preSelectAPs(), denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
Referenced by denoptim.gui.VertexViewPanel.loadFragmentToViewer(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
loadPlainStructure()
void denoptim.gui.FragmentViewPanel.loadPlainStructure (IAtomContainer mol)
Loads a structure in the Jmol viewer.
Parameters
mol the structure to load
Returns
the atom container created to visualize the molecular content. This is needed for operations involving the identification by means of reference to the atoms selected/present in the viewer.
Definition at line 710 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.fragment, denoptim.gui.FragmentViewPanel.loadStructure(), and denoptim.graph.Vertex.BBType.UNDEFINED.
Referenced by denoptim.gui.VertexViewPanel.loadPlainStructure(), and denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator().
loadSMILES()
boolean denoptim.gui.FragmentViewPanel.loadSMILES (String smiles)
Loads a molecule build from a smiles string.
The 3D geometry is either taken from remote CACTUS service (requires connection to the Internet) or built with CDK tools, as a fall-back. The CDK builder, however will produce a somewhat lower quality conformation than that obtained from on online generator.
Parameters
smiles the SMILES of the molecule to load
Returns
true if the SMILES could be converted into a 3D structure
Exceptions
DENOPTIMException
Definition at line 392 of file FragmentViewPanel.java.
References denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.gui.FragmentViewPanel.fragment, denoptim.gui.FragmentViewPanel.getDataFromJmol(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator(), denoptim.gui.FragmentViewPanel.parent, denoptim.gui.FragmentViewPanel.setJmolViewer(), denoptim.gui.GUIPreferences.smiTo3dResolver, denoptim.gui.JmolPanel.viewer, and denoptim.gui.FragmentViewPanel.waitForJmolViewer().
Referenced by denoptim.gui.VertexViewPanel.loadSMILES().
loadStructure()
void denoptim.gui.FragmentViewPanel.loadStructure () private
Loads the structure of the currently loaded 'fragment' (i.e., our member) into the Jmol viewer.
Definition at line 727 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Fragment.getIAtomContainer(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.setJmolViewer(), denoptim.gui.FragmentViewPanel.tmpSDFFile, denoptim.gui.JmolPanel.viewer, and denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.gui.FragmentViewPanel.loadFragmentToViewer(), and denoptim.gui.FragmentViewPanel.loadPlainStructure().
make3DusingCDKgenerator()
void denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator (String smiles) throws CDKException, CloneNotSupportedException, IOException private
Definition at line 315 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearMolecularViewer(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.loadPlainStructure(), denoptim.gui.JmolPanel.viewer, and denoptim.gui.FragmentViewPanel.waitForJmolViewer().
Referenced by denoptim.gui.FragmentViewPanel.loadSMILES().
preSelectAPs()
void denoptim.gui.FragmentViewPanel.preSelectAPs () private
Definition at line 810 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.activateTabEditsListener(), denoptim.gui.FragmentViewPanel.apTable, denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Vertex.getProperty(), denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELD, and denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELDSEP.
Referenced by denoptim.gui.FragmentViewPanel.loadFragmentToViewer().
putAPsFromTableIntoIAtomContainer()
void denoptim.gui.FragmentViewPanel.putAPsFromTableIntoIAtomContainer (Fragment mol) throws DENOPTIMException private
Definition at line 665 of file FragmentViewPanel.java.
References denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPoint.getAtomPositionNumber(), denoptim.graph.AttachmentPoint.getDirectionVector(), and denoptim.gui.FragmentViewPanel.mapAPs.
Referenced by denoptim.gui.FragmentViewPanel.getLoadedStructure().
setJmolViewer()
void denoptim.gui.FragmentViewPanel.setJmolViewer () private
Definition at line 941 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.NL, and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.FragmentViewPanel.getLoadedStructure(), denoptim.gui.FragmentViewPanel.loadSMILES(), and denoptim.gui.FragmentViewPanel.loadStructure().
updateAPsInJmolViewer()
void denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer () private
Definition at line 882 of file FragmentViewPanel.java.
References denoptim.utils.MathUtils.add(), denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Fragment.getAtom(), denoptim.graph.AttachmentPoint.getAtomPositionNumber(), denoptim.graph.AttachmentPoint.getDirectionVector(), denoptim.gui.FragmentViewPanel.getJmolPositionStr(), denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.mapAPs, denoptim.gui.FragmentViewPanel.NL, denoptim.utils.MathUtils.scale(), denoptim.utils.MathUtils.subtract(), and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.FragmentViewPanel.loadFragmentToViewer().
updateAPsMapAndTable()
void denoptim.gui.FragmentViewPanel.updateAPsMapAndTable () private
Uses the AP of the Fragment to create a new map and table of APs.
Definition at line 786 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.activateTabEditsListener(), denoptim.gui.FragmentViewPanel.apTabModel, denoptim.gui.FragmentViewPanel.clearAPTable(), denoptim.gui.FragmentViewPanel.fragment, denoptim.graph.Fragment.getCurrentAPs(), and denoptim.gui.FragmentViewPanel.mapAPs.
Referenced by denoptim.gui.FragmentViewPanel.loadFragmentToViewer().
waitForJmolViewer()
void denoptim.gui.FragmentViewPanel.waitForJmolViewer (int milliSecFirst, String cause) private
Waits until Jmol is finished.
Parameters
milliSecFirst
Definition at line 230 of file FragmentViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearMolecularViewer(), denoptim.gui.FragmentViewPanel.jmolPanel, denoptim.gui.FragmentViewPanel.parent, and denoptim.gui.JmolPanel.viewer.
Referenced by denoptim.gui.FragmentViewPanel.loadSMILES(), and denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator().
Member Data Documentation
alteredAPData
boolean denoptim.gui.FragmentViewPanel.alteredAPData = false
Flag signalling that data about APs has been changed in the GUI.
Definition at line 98 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.deprotectEdits(), denoptim.gui.FragmentViewPanel.hasUnsavedAPEdits(), and denoptim.gui.FragmentViewPanel.PausableTableModelListener.tableChanged().
apTable
JTable denoptim.gui.FragmentViewPanel.apTable protected
Definition at line 103 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.getSelectedAPIDs(), denoptim.gui.FragmentViewPanel.getSelectedAPs(), denoptim.gui.FragmentViewPanel.initialize(), and denoptim.gui.FragmentViewPanel.preSelectAPs().
apTabModel
DefaultTableModel denoptim.gui.FragmentViewPanel.apTabModel protected
Definition at line 102 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.activateTabEditsListener(), denoptim.gui.FragmentViewPanel.clearAPTable(), denoptim.gui.FragmentViewPanel.getAPTableModel(), denoptim.gui.FragmentViewPanel.initialize(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
editableAPTable
boolean denoptim.gui.FragmentViewPanel.editableAPTable = false private
Definition at line 105 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.FragmentViewPanel(), and denoptim.gui.FragmentViewPanel.initialize().
fragment
Fragment denoptim.gui.FragmentViewPanel.fragment private
The currently loaded fragment.
Definition at line 88 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.getAtomsSelectedFromJMol(), denoptim.gui.FragmentViewPanel.getLoadedStructure(), denoptim.gui.FragmentViewPanel.loadPlainStructure(), denoptim.gui.FragmentViewPanel.loadSMILES(), denoptim.gui.FragmentViewPanel.loadStructure(), denoptim.gui.FragmentViewPanel.preSelectAPs(), denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
jmolPanel
JmolPanel denoptim.gui.FragmentViewPanel.jmolPanel private
Definition at line 100 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.clearMolecularViewer(), denoptim.gui.FragmentViewPanel.dispose(), denoptim.gui.FragmentViewPanel.getAtomsSelectedFromJMol(), denoptim.gui.FragmentViewPanel.getDataFromJmol(), denoptim.gui.FragmentViewPanel.initialize(), denoptim.gui.FragmentViewPanel.loadSMILES(), denoptim.gui.FragmentViewPanel.loadStructure(), denoptim.gui.FragmentViewPanel.make3DusingCDKgenerator(), denoptim.gui.FragmentViewPanel.setJmolViewer(), denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer(), and denoptim.gui.FragmentViewPanel.waitForJmolViewer().
mapAPs
Map<Integer,AttachmentPoint> denoptim.gui.FragmentViewPanel.mapAPs = null protected
Temporary list of attachment points of the current fragment.
Definition at line 93 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.getMapOfAPsInTable(), denoptim.gui.FragmentViewPanel.getSelectedAPs(), denoptim.gui.FragmentViewPanel.putAPsFromTableIntoIAtomContainer(), denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer(), and denoptim.gui.FragmentViewPanel.updateAPsMapAndTable().
NL
final String denoptim.gui.FragmentViewPanel.NL = System.getProperty("line.separator") private
Definition at line 107 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.FragmentViewPanel.setJmolViewer(), and denoptim.gui.FragmentViewPanel.updateAPsInJmolViewer().
parent
JComponent denoptim.gui.FragmentViewPanel.parent private
Definition at line 111 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.FragmentViewPanel(), denoptim.gui.FragmentViewPanel.loadSMILES(), and denoptim.gui.FragmentViewPanel.waitForJmolViewer().
serialVersionUID
final long denoptim.gui.FragmentViewPanel.serialVersionUID = 912850110991449553L static private
Version UID.
Definition at line 83 of file FragmentViewPanel.java.
tabPanel
JScrollPane denoptim.gui.FragmentViewPanel.tabPanel private
Definition at line 101 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.initialize().
tmpSDFFile
String denoptim.gui.FragmentViewPanel.tmpSDFFile private
Definition at line 109 of file FragmentViewPanel.java.
Referenced by denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.FragmentViewPanel.initialize(), and denoptim.gui.FragmentViewPanel.loadStructure().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/FragmentViewPanel.java