DENOPTIM: denoptim.graph.EdgeQueryTest Class Reference
denoptim.graph.EdgeQueryTest Class Reference
Unit tests for EdgeQuery#matches(Edge).
Public Member Functions
void setUp () throws DENOPTIMException
void testMatchesNullEdge ()
void testMatchesAllNullCriteria ()
void testMatchesSourceAndTargetVertices ()
void testMatchesAttachmentPointIndices ()
void testMatchesBondType ()
void testMatchesAPClasses () throws DENOPTIMException
void testMatchesCombinedCriteria () throws DENOPTIMException
void testFindEdgesUsesMatches ()
void testMatchesNestedQueries () throws DENOPTIMException
Private Attributes
DGraph graph
Detailed Description
Unit tests for EdgeQuery#matches(Edge).
Definition at line 26 of file EdgeQueryTest.java.
Member Function Documentation
setUp()
void denoptim.graph.EdgeQueryTest.setUp () throws DENOPTIMException
Definition at line 31 of file EdgeQueryTest.java.
References denoptim.graph.EdgeQueryTest.graph, and denoptim.graph.DGraphTest.makeTestGraphA2().
testFindEdgesUsesMatches()
void denoptim.graph.EdgeQueryTest.testFindEdgesUsesMatches ()
Definition at line 192 of file EdgeQueryTest.java.
References denoptim.graph.DGraph.findEdges(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.EdgeQueryTest.graph, and denoptim.graph.EdgeQuery.matches().
testMatchesAllNullCriteria()
void denoptim.graph.EdgeQueryTest.testMatchesAllNullCriteria ()
Definition at line 48 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.EdgeQueryTest.graph, and denoptim.graph.EdgeQuery.matches().
testMatchesAPClasses()
void denoptim.graph.EdgeQueryTest.testMatchesAPClasses () throws DENOPTIMException
Definition at line 144 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.EdgeQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.EdgeQuery.matches().
testMatchesAttachmentPointIndices()
void denoptim.graph.EdgeQueryTest.testMatchesAttachmentPointIndices ()
Definition at line 92 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.EdgeQueryTest.graph, and denoptim.graph.EdgeQuery.matches().
testMatchesBondType()
void denoptim.graph.EdgeQueryTest.testMatchesBondType ()
Definition at line 124 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.EdgeQueryTest.graph, denoptim.graph.EdgeQuery.matches(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.graph.Edge.BondType.TRIPLE.
testMatchesCombinedCriteria()
void denoptim.graph.EdgeQueryTest.testMatchesCombinedCriteria () throws DENOPTIMException
Definition at line 164 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.EdgeQueryTest.graph, denoptim.graph.APClass.make(), denoptim.graph.EdgeQuery.matches(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.graph.Edge.BondType.TRIPLE.
testMatchesNestedQueries()
void denoptim.graph.EdgeQueryTest.testMatchesNestedQueries () throws DENOPTIMException
Definition at line 216 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.EdgeQueryTest.graph, denoptim.graph.APClass.make(), denoptim.graph.EdgeQuery.matches(), and denoptim.graph.Edge.BondType.TRIPLE.
testMatchesNullEdge()
void denoptim.graph.EdgeQueryTest.testMatchesNullEdge ()
Definition at line 39 of file EdgeQueryTest.java.
References denoptim.graph.EdgeQuery.matches().
testMatchesSourceAndTargetVertices()
void denoptim.graph.EdgeQueryTest.testMatchesSourceAndTargetVertices ()
Definition at line 60 of file EdgeQueryTest.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.EdgeQueryTest.graph, and denoptim.graph.EdgeQuery.matches().
Member Data Documentation
graph
DGraph denoptim.graph.EdgeQueryTest.graph private
Definition at line 28 of file EdgeQueryTest.java.
Referenced by denoptim.graph.EdgeQueryTest.setUp(), denoptim.graph.EdgeQueryTest.testFindEdgesUsesMatches(), denoptim.graph.EdgeQueryTest.testMatchesAllNullCriteria(), denoptim.graph.EdgeQueryTest.testMatchesAPClasses(), denoptim.graph.EdgeQueryTest.testMatchesAttachmentPointIndices(), denoptim.graph.EdgeQueryTest.testMatchesBondType(), denoptim.graph.EdgeQueryTest.testMatchesCombinedCriteria(), denoptim.graph.EdgeQueryTest.testMatchesNestedQueries(), and denoptim.graph.EdgeQueryTest.testMatchesSourceAndTargetVertices().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/EdgeQueryTest.java