DENOPTIM: denoptim.fitness.descriptors.SocketProvidedDescriptorTest Class Reference
denoptim.fitness.descriptors.SocketProvidedDescriptorTest Class Reference
Unit test for descriptor SocketProvidedDescriptor.
Classes
class MySocketServer
class RequestHandler
Public Member Functions
void setUpSertver () throws Exception
void ClossServer () throws Exception
void testSocketProvidedDescriptor () throws Exception
Private Member Functions
boolean closeEnough (double expected, double actual)
Private Attributes
SocketProvidedDescriptor descriptor
MySocketServer server
Gson jsonConverted
Static Private Attributes
static final String HOSTNAME = "localhost"
Detailed Description
Unit test for descriptor SocketProvidedDescriptor.
Author
Marco Foscato
Definition at line 51 of file SocketProvidedDescriptorTest.java.
Member Function Documentation
closeEnough()
boolean denoptim.fitness.descriptors.SocketProvidedDescriptorTest.closeEnough (double expected, double actual) private
Definition at line 282 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.testSocketProvidedDescriptor().
ClossServer()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.ClossServer () throws Exception
Definition at line 81 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.server, and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.stopServer().
setUpSertver()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver () throws Exception
Definition at line 63 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.getPort(), denoptim.fitness.descriptors.SocketProvidedDescriptorTest.HOSTNAME, denoptim.fitness.descriptors.SocketProvidedDescriptorTest.jsonConverted, denoptim.fitness.descriptors.SocketProvidedDescriptorTest.server, denoptim.fitness.descriptors.SocketProvidedDescriptor.setParameters(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.startServer().
testSocketProvidedDescriptor()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.testSocketProvidedDescriptor () throws Exception
Definition at line 243 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptor.calculate(), denoptim.fitness.descriptors.SocketProvidedDescriptorTest.closeEnough(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.descriptor.
Member Data Documentation
descriptor
SocketProvidedDescriptor denoptim.fitness.descriptors.SocketProvidedDescriptorTest.descriptor private
Definition at line 53 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.testSocketProvidedDescriptor().
HOSTNAME
final String denoptim.fitness.descriptors.SocketProvidedDescriptorTest.HOSTNAME = "localhost" static private
Definition at line 57 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver().
jsonConverted
Gson denoptim.fitness.descriptors.SocketProvidedDescriptorTest.jsonConverted private
Definition at line 55 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.RequestHandler.run(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver().
server
MySocketServer denoptim.fitness.descriptors.SocketProvidedDescriptorTest.server private
Definition at line 54 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.ClossServer(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fitness/descriptors/SocketProvidedDescriptorTest.java