DENOPTIM: denoptim.graph.rings.PathSubGraphTest Class Reference
denoptim.graph.rings.PathSubGraphTest Class Reference
Unit test for PathSubGraph.
Public Member Functions
void testMakePathSubGraph_sameVrtx () throws Exception
void testMakePathSubGraph_sameBranch () throws Exception
void testMakePathSubGraph_differentBranch () throws Exception
void testMakePathSubGraph_givenAdjacency () throws Exception
void testMakePathSubGraph_withIAC () throws Exception
Static Public Member Functions
static DGraph makeTestGraphA () throws DENOPTIMException
Build a graph meant to be used in unit tests.
static DGraph makeTestGraphB () throws DENOPTIMException
Build a graph meant to be used in unit tests.
Detailed Description
Unit test for PathSubGraph.
Author
Marco Foscato
Definition at line 65 of file PathSubGraphTest.java.
Member Function Documentation
makeTestGraphA()
static DGraph denoptim.graph.rings.PathSubGraphTest.makeTestGraphA () throws DENOPTIMException static
Build a graph meant to be used in unit tests.
The returned graph has the following structure:
             C-C-C-C      N
             |     |     / \
RCV--[O-O]--[C--C--C]--[N---N]--RCV
Returns
a new instance of the test graph.
Exceptions
DENOPTIMException
Definition at line 81 of file PathSubGraphTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.setAsRCV(), and denoptim.graph.Edge.BondType.SINGLE.
Referenced by denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_sameBranch(), denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_sameVrtx(), and denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_withIAC().
makeTestGraphB()
static DGraph denoptim.graph.rings.PathSubGraphTest.makeTestGraphB () throws DENOPTIMException static
Build a graph meant to be used in unit tests.
The returned graph has the following structure:
RCV--[O]--[C]--[N]--RCV
Returns
a new instance of the test graph.
Exceptions
DENOPTIMException
Definition at line 193 of file PathSubGraphTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.setAsRCV(), and denoptim.graph.Edge.BondType.SINGLE.
Referenced by denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_withIAC().
testMakePathSubGraph_differentBranch()
void denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_differentBranch () throws Exception
Definition at line 310 of file PathSubGraphTest.java.
References denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphO_B(), and denoptim.graph.DGraphTest.prepare().
testMakePathSubGraph_givenAdjacency()
void denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_givenAdjacency () throws Exception
Definition at line 325 of file PathSubGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Edge.BondType.DOUBLE, denoptim.graph.Vertex.getAP(), denoptim.graph.rings.PathSubGraph.getEdgesPath(), denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.APClass.make(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.graph.Edge.BondType.TRIPLE.
testMakePathSubGraph_sameBranch()
void denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_sameBranch () throws Exception
Definition at line 275 of file PathSubGraphTest.java.
References denoptim.graph.rings.PathSubGraph.getEdgesPath(), denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.rings.PathSubGraphTest.makeTestGraphA().
testMakePathSubGraph_sameVrtx()
void denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_sameVrtx () throws Exception
Definition at line 259 of file PathSubGraphTest.java.
References denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.rings.PathSubGraphTest.makeTestGraphA().
testMakePathSubGraph_withIAC()
void denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_withIAC () throws Exception
Definition at line 424 of file PathSubGraphTest.java.
References denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.graph.rings.PathSubGraph.getMolecularRepresentation(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.rings.PathSubGraph.makeMolecularRepresentation(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphA(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphB(), and denoptim.molecularmodeling.ThreeDimTreeBuilder.setAlignBBsIn3D().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/rings/PathSubGraphTest.java