DENOPTIM: denoptim.utils.MoleculeUtilsTest Class Reference
denoptim.utils.MoleculeUtilsTest Class Reference
Unit test for DENOPTIMMoleculeUtils.
Public Member Functions
void testGetPoint3d () throws Exception
void testCalculateCentroid () throws Exception
Private Member Functions
boolean areCloseEnough (double a, double b)
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Detailed Description
Unit test for DENOPTIMMoleculeUtils.
Author
Marco Foscato
Definition at line 41 of file MoleculeUtilsTest.java.
Member Function Documentation
areCloseEnough()
boolean denoptim.utils.MoleculeUtilsTest.areCloseEnough (double a, double b) private
Definition at line 70 of file MoleculeUtilsTest.java.
Referenced by denoptim.utils.MoleculeUtilsTest.testCalculateCentroid(), and denoptim.utils.MoleculeUtilsTest.testGetPoint3d().
testCalculateCentroid()
void denoptim.utils.MoleculeUtilsTest.testCalculateCentroid () throws Exception
Definition at line 79 of file MoleculeUtilsTest.java.
References denoptim.utils.MoleculeUtilsTest.areCloseEnough(), denoptim.utils.MoleculeUtilsTest.builder, and denoptim.utils.MoleculeUtils.calculateCentroid().
testGetPoint3d()
void denoptim.utils.MoleculeUtilsTest.testGetPoint3d () throws Exception
Definition at line 48 of file MoleculeUtilsTest.java.
References denoptim.utils.MoleculeUtilsTest.areCloseEnough().
Member Data Documentation
builder
IChemObjectBuilder denoptim.utils.MoleculeUtilsTest.builder = SilentChemObjectBuilder.getInstance() private
Definition at line 43 of file MoleculeUtilsTest.java.
Referenced by denoptim.utils.MoleculeUtilsTest.testCalculateCentroid().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/utils/MoleculeUtilsTest.java