DENOPTIM: denoptim.fragmenter.FragmentAlignement Class Reference
denoptim.fragmenter.FragmentAlignement Class Reference
Class performing the alignment of Fragments.
Public Member Functions
FragmentAlignement (Fragment fragA, Fragment fragB) throws DENOPTIMException
Constructor for an alignment of two fragments.
GraphMapping< FragIsomorphNode, FragIsomorphEdge > getLowestRMSDMapping ()
Returns the mapping leading to the lowest RMSD that could be found among all isomorphic mappings.
double getMinimumRMSD ()
Returns the lowest RMSD that could be found among all isomorphic mappings.
Private Attributes
double minRMSD = Double.MAX_VALUE
Lowest RMSD upon alignment.
GraphMapping< FragIsomorphNode, FragIsomorphEdge > bestMapping = null
Mapping of nodes leading to lowest RMSD upon alignment.
Detailed Description
Class performing the alignment of Fragments.
Author
marcof
Definition at line 21 of file FragmentAlignement.java.
Constructor & Destructor Documentation
FragmentAlignement()
denoptim.fragmenter.FragmentAlignement.FragmentAlignement (Fragment fragA, Fragment fragB) throws DENOPTIMException
Constructor for an alignment of two fragments.
Note we first have to find an ordering of the atoms/AP that is consistent. Thus we check for isomorphism between the fragments.
Parameters
fragA
fragB
Exceptions
DENOPTIMException if an isomorphism is not found.
Definition at line 43 of file FragmentAlignement.java.
References denoptim.fragmenter.FragmentAlignement.bestMapping, denoptim.graph.FragmentIsomorphismInspector.getMappings(), denoptim.graph.FragIsomorphNode.getPoint3d(), denoptim.graph.FragmentIsomorphismInspector.isomorphismExists(), and denoptim.fragmenter.FragmentAlignement.minRMSD.
Member Function Documentation
getLowestRMSDMapping()
GraphMapping< FragIsomorphNode, FragIsomorphEdge > denoptim.fragmenter.FragmentAlignement.getLowestRMSDMapping ()
Returns the mapping leading to the lowest RMSD that could be found among all isomorphic mappings.
Returns
Definition at line 99 of file FragmentAlignement.java.
References denoptim.fragmenter.FragmentAlignement.bestMapping.
Referenced by denoptim.fragmenter.ConformerExtractorTask.populateListOfClusterizableFragments().
getMinimumRMSD()
double denoptim.fragmenter.FragmentAlignement.getMinimumRMSD ()
Returns the lowest RMSD that could be found among all isomorphic mappings.
Returns
Definition at line 110 of file FragmentAlignement.java.
References denoptim.fragmenter.FragmentAlignement.minRMSD.
Referenced by denoptim.fragmenter.FragmentAlignementTest.testGetMinimumRMSD().
Member Data Documentation
bestMapping
GraphMapping<FragIsomorphNode, FragIsomorphEdge> denoptim.fragmenter.FragmentAlignement.bestMapping = null private
Mapping of nodes leading to lowest RMSD upon alignment.
Definition at line 31 of file FragmentAlignement.java.
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement(), and denoptim.fragmenter.FragmentAlignement.getLowestRMSDMapping().
minRMSD
double denoptim.fragmenter.FragmentAlignement.minRMSD = Double.MAX_VALUE private
Lowest RMSD upon alignment.
Definition at line 26 of file FragmentAlignement.java.
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement(), and denoptim.fragmenter.FragmentAlignement.getMinimumRMSD().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragmenter/FragmentAlignement.java