DENOPTIM: denoptim.graph.RingTest Class Reference
denoptim.graph.RingTest Class Reference
Unit test.
Public Member Functions
void testUndirectedComparison () throws Exception
void testGetDistance () throws Exception
void testGetCloserVertex () throws Exception
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 34 of file RingTest.java.
Member Function Documentation
testGetCloserVertex()
void denoptim.graph.RingTest.testGetCloserVertex () throws Exception
Definition at line 81 of file RingTest.java.
References denoptim.graph.Ring.getCloserTo(), denoptim.graph.Ring.getCloserToHead(), denoptim.graph.Ring.getCloserToTail(), denoptim.graph.Ring.getVertexAtPosition(), and denoptim.graph.Vertex.setBuildingBlockId().
testGetDistance()
void denoptim.graph.RingTest.testGetDistance () throws Exception
Definition at line 62 of file RingTest.java.
References denoptim.graph.Ring.getDistance(), and denoptim.graph.Vertex.setBuildingBlockId().
testUndirectedComparison()
void denoptim.graph.RingTest.testUndirectedComparison () throws Exception
Definition at line 39 of file RingTest.java.
References denoptim.graph.Ring.indexOf(), denoptim.graph.Ring.insertVertex(), and denoptim.graph.Vertex.setBuildingBlockId().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/RingTest.java