DENOPTIM: denoptim.graph.Edge.DENOPTIMEdgeSerializer Class Reference
denoptim.graph.Edge.DENOPTIMEdgeSerializer Class Reference
Public Member Functions
JsonElement serialize (Edge edge, Type typeOfSrc, JsonSerializationContext context)
Detailed Description
Definition at line 404 of file Edge.java.
Member Function Documentation
serialize()
JsonElement denoptim.graph.Edge.DENOPTIMEdgeSerializer.serialize (Edge edge, Type typeOfSrc, JsonSerializationContext context)
Definition at line 408 of file Edge.java.
References denoptim.graph.Edge.getBondType(), denoptim.graph.AttachmentPoint.getID(), denoptim.graph.Edge.getSrcAP(), and denoptim.graph.Edge.getTrgAP().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/Edge.java