DENOPTIM: denoptim.molecularmodeling.zmatrix.ZMatrixTest Class Reference
denoptim.molecularmodeling.zmatrix.ZMatrixTest Class Reference
Unit test for ZMatrix.
Public Member Functions
ZMatrix getTestZMatrix () throws Exception
void testAddAtom () throws Exception
void testRemoveAtom () throws Exception
void testGetIndex () throws Exception
void testGetBondRefAtomIndex () throws Exception
void testGetAngleRefAtomIndex () throws Exception
void testGetAngle2RefAtomIndex () throws Exception
void testGetChiralFlag () throws Exception
void testGetIdAndSetId () throws Exception
void testAddBond () throws Exception
void testDelBond () throws Exception
void testGetBondsToAdd () throws Exception
void testGetBondsToDel () throws Exception
void testClone () throws Exception
void testGetBondData () throws Exception
void testZMatrixEquals () throws Exception
void testZMatrixHashCode () throws Exception
void testGetZMatrixFromIAC () throws Exception
void testUsesProperDihedral () throws Exception
Detailed Description
Unit test for ZMatrix.
Author
Marco Foscato
Definition at line 45 of file ZMatrixTest.java.
Member Function Documentation
getTestZMatrix()
ZMatrix denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix () throws Exception
Definition at line 50 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.addBond().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testDelBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngle2RefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngleRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondData(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToAdd(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToDel(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetChiralFlag(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIdAndSetId(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIndex(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testUsesProperDihedral(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixHashCode().
testAddAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom () throws Exception
Definition at line 97 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testAddBond()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddBond () throws Exception
Definition at line 217 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testClone()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone () throws Exception
Definition at line 272 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm1(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm2(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getSymbol(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getType().
testDelBond()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testDelBond () throws Exception
Definition at line 229 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetAngle2RefAtomIndex()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngle2RefAtomIndex () throws Exception
Definition at line 170 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtomIndex(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetAngleRefAtomIndex()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngleRefAtomIndex () throws Exception
Definition at line 157 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetBondData()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondData () throws Exception
Definition at line 305 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondData(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetBondRefAtomIndex()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondRefAtomIndex () throws Exception
Definition at line 144 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetBondsToAdd()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToAdd () throws Exception
Definition at line 241 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToAdd(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetBondsToDel()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToDel () throws Exception
Definition at line 257 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetChiralFlag()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetChiralFlag () throws Exception
Definition at line 184 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetIdAndSetId()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIdAndSetId () throws Exception
Definition at line 199 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), and denoptim.molecularmodeling.zmatrix.ZMatrix.setId().
testGetIndex()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIndex () throws Exception
Definition at line 128 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getIndex(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix().
testGetZMatrixFromIAC()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetZMatrixFromIAC () throws Exception
Definition at line 363 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC().
testRemoveAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom () throws Exception
Definition at line 116 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), and denoptim.molecularmodeling.zmatrix.ZMatrix.removeAtom().
testUsesProperDihedral()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testUsesProperDihedral () throws Exception
Definition at line 399 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), and denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral().
testZMatrixEquals()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals () throws Exception
Definition at line 320 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), and denoptim.molecularmodeling.zmatrix.ZMatrix.setId().
testZMatrixHashCode()
void denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixHashCode () throws Exception
Definition at line 348 of file ZMatrixTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), denoptim.molecularmodeling.zmatrix.ZMatrix.hashCode(), and denoptim.molecularmodeling.zmatrix.ZMatrix.setId().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/molecularmodeling/zmatrix/ZMatrixTest.java