DENOPTIM: denoptim.molecularmodeling.zmatrix.ZMatrix Class Reference
denoptim.molecularmodeling.zmatrix.ZMatrix Class Reference
Representation of an atom container's geometry with internal coordinates.
Public Member Functions
ZMatrix ()
Constructor for ZMatrix.
void addAtom (ZMatrixAtom atom)
Add an atom to the ZMatrix.
void removeAtom (ZMatrixAtom atm)
Remove an atom from the ZMatrix.
int getAtomCount ()
Get the number of atoms in the ZMatrix.
int getBondCount ()
Get the number of bonds in the ZMatrix.
List< int[]> getBondData ()
Get the bond data for the ZMatrix.
String getId ()
Get the id of the ZMatrix.
void setId (String id)
Set the id of the ZMatrix.
List< int[]> getBondsToAdd ()
Get the bonds to add to the Z-matrix.
List< int[]> getBondsToDel ()
Get the bonds to delete from the ZMatrix.
ZMatrixAtom getAtom (int index)
Get the atom at the given index.
List< ZMatrixAtom > getAtoms ()
Get the atoms in the ZMatrix.
int getIndex (ZMatrixAtom atm)
Get the index of the atom.
ZMatrixAtom getBondRefAtom (int index)
Get the bond reference atom for the atom at the given index.
int getBondRefAtomIndex (int index)
Get the index of the bond reference atom for the atom at the given index.
ZMatrixAtom getAngleRefAtom (int index)
Get the angle reference atom for the atom at the given index.
int getAngleRefAtomIndex (int index)
Get the index of the angle reference atom for the atom at the given index.
ZMatrixAtom getAngle2RefAtom (int index)
Get the second angle reference atom for the atom at the given index.
int getAngle2RefAtomIndex (int index)
Get the index of the second angle reference atom for the atom at the given index.
Double getBondLength (int index)
Get the bond length for the atom at the given index.
Double getAngleValue (int index)
Get the bond angle for the atom at the given index.
Double getAngle2Value (int index)
Get the angle2 angle for the atom at the given index.
Integer getChiralFlag (int index)
Get the chiral flag for the atom at the given index.
boolean usesProperDihedral (int idx1, int idx2)
Check if the dihedral between the two atoms at the given indices uses proper torsion.
ZMatrixBond getBond (int index)
Get the bond at the given index.
void delBond (int a1, int a2)
Delete the bond between the two atoms at the given indices.
void delBond (ZMatrixAtom a1, ZMatrixAtom a2)
Delete the bond between the two atoms.
void addBond (int a1, int a2)
Add a bond between the two atoms at the given indices.
void addBond (ZMatrixAtom a1, ZMatrixAtom a2)
Add a bond between the two atoms.
ZMatrix clone ()
Clone the ZMatrix.
boolean equals (Object o)
int hashCode ()
Static Public Member Functions
static ZMatrix getZMatrixFromIAC (IAtomContainer mol) throws DENOPTIMException
Convert IAtomContainer to ZMatrix.
Static Private Member Functions
static int getFirstRefAtomId (int i1, IAtomContainer mol)
static int getSecondRefAtomId (int i1, int i2, IAtomContainer mol)
static ObjectPair getThirdRefAtomId (int i1, int i2, int i3, IAtomContainer mol, ZMatrix zmat) throws DENOPTIMException
static int countPredefinedNeighbours (int i, IAtom a, IAtomContainer mol)
Private Attributes
String id
Identifier of this ZMatrix.
List< ZMatrixAtom > lstAtoms
All atoms and pseudoAtoms mentioned in the Zmatrix.
List< ZMatrixBond > lstBonds
All bonds in the system, whether included or not in the Z-matrix intrinsic connections.
Detailed Description
Representation of an atom container's geometry with internal coordinates.
Definition at line 26 of file ZMatrix.java.
Constructor & Destructor Documentation
ZMatrix()
denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix ()
Constructor for ZMatrix.
Definition at line 49 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC().
Member Function Documentation
addAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom (ZMatrixAtom atom)
Add an atom to the ZMatrix.
Parameters
atom The atom to add
Definition at line 61 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC(), denoptim.integration.tinker.TinkerUtils.readTinkerINT(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom(), denoptim.integration.rcoserver.RCOSocketServerClientTest.testGetZMatrixAsJsonArray(), denoptim.integration.tinker.TinkerUtilsTest.testINTRoundTrip(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityMinusOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FirstAtomAtOrigin(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FourthAtomWithDihedral(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_SecondAtomAlongZAxis(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ThirdAtomWithAngle(), denoptim.integration.tinker.TinkerUtilsTest.testWriteTinkerINT(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals().
addBond() [1/2]
void denoptim.molecularmodeling.zmatrix.ZMatrix.addBond (int a1, int a2)
Add a bond between the two atoms at the given indices.
Parameters
a1 The index of the first atom
a2 The index of the second atom
order The order of the bond
Definition at line 461 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.getTestZMatrix(), denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC(), denoptim.integration.tinker.TinkerUtils.readTinkerINT(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddBond(), denoptim.integration.rcoserver.RCOSocketServerClientTest.testGetZMatrixAsJsonArray(), denoptim.integration.tinker.TinkerUtilsTest.testINTRoundTrip(), denoptim.integration.tinker.TinkerUtilsTest.testWriteTinkerINT(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals().
addBond() [2/2]
void denoptim.molecularmodeling.zmatrix.ZMatrix.addBond (ZMatrixAtom a1, ZMatrixAtom a2)
Add a bond between the two atoms.
Parameters
a1 The first atom
a2 The second atom
order The order of the bond
Definition at line 474 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
clone()
ZMatrix denoptim.molecularmodeling.zmatrix.ZMatrix.clone ()
Clone the ZMatrix.
Returns
The cloned ZMatrix
Definition at line 485 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondRefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone().
countPredefinedNeighbours()
static int denoptim.molecularmodeling.zmatrix.ZMatrix.countPredefinedNeighbours (int i, IAtom a, IAtomContainer mol) static private
Definition at line 836 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getThirdRefAtomId().
delBond() [1/2]
void denoptim.molecularmodeling.zmatrix.ZMatrix.delBond (int a1, int a2)
Delete the bond between the two atoms at the given indices.
Parameters
a1 The index of the first atom
a2 The index of the second atom
Definition at line 426 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), denoptim.integration.tinker.TinkerUtils.readTinkerINT(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testDelBond(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals().
delBond() [2/2]
void denoptim.molecularmodeling.zmatrix.ZMatrix.delBond (ZMatrixAtom a1, ZMatrixAtom a2)
Delete the bond between the two atoms.
Parameters
a1 The first atom
a2 The second atom
Definition at line 438 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
equals()
boolean denoptim.molecularmodeling.zmatrix.ZMatrix.equals (Object o)
Definition at line 851 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm1(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm2(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrix.id, denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds, and denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix().
Referenced by denoptim.integration.tinker.TinkerUtilsTest.testINTRoundTrip().
getAngle2RefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtom (int index)
Get the second angle reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The second angle reference atom or null if not set
Definition at line 312 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2RefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtomIndex().
getAngle2RefAtomIndex()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtomIndex (int index)
Get the index of the second angle reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The index of the second angle reference atom or -1 if not set
Definition at line 325 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngle2RefAtomIndex(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getAngle2Value()
Double denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2Value (int index)
Get the angle2 angle for the atom at the given index.
Parameters
index The index of the atom
Returns
The bond angle or null if not set
Definition at line 363 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2Value(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom().
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getAngleRefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtom (int index)
Get the angle reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The angle reference atom or null if not set
Definition at line 285 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleRefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex().
getAngleRefAtomIndex()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex (int index)
Get the index of the angle reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The index of the angle reference atom or -1 if not set
Definition at line 297 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetAngleRefAtomIndex(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral().
getAngleValue()
Double denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleValue (int index)
Get the bond angle for the atom at the given index.
Parameters
index The index of the atom
Returns
The bond angle or null if not set
Definition at line 351 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleValue(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom().
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom (int index)
Get the atom at the given index.
Parameters
index The index of the atom
Returns
The atom at the given index
Definition at line 223 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2Value(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleValue(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondLength(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag(), denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC(), denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.tinker.TinkerUtils.readTinkerINT(), denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), denoptim.integration.tinker.ConformationalSearchPSSROT.setTinkerTypes(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testDelBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIndex(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals().
getAtomCount()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount ()
Get the number of atoms in the ZMatrix.
Returns
The number of atoms in the ZMatrix
Definition at line 92 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetZMatrixFromIAC(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom().
getAtoms()
List< ZMatrixAtom > denoptim.molecularmodeling.zmatrix.ZMatrix.getAtoms ()
Get the atoms in the ZMatrix.
Returns
The atoms in the ZMatrix
Definition at line 234 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getBond()
ZMatrixBond denoptim.molecularmodeling.zmatrix.ZMatrix.getBond (int index)
Get the bond at the given index.
Parameters
index The index of the bond
Returns
The bond
Definition at line 414 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone().
getBondCount()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount ()
Get the number of bonds in the ZMatrix.
Returns
The number of bonds in the ZMatrix
Definition at line 103 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testAddBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testDelBond(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetZMatrixFromIAC(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom().
getBondData()
List< int[]> denoptim.molecularmodeling.zmatrix.ZMatrix.getBondData ()
Get the bond data for the ZMatrix.
Returns
The bond data for the ZMatrix
Definition at line 114 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getId(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondData().
getBondLength()
Double denoptim.molecularmodeling.zmatrix.ZMatrix.getBondLength (int index)
Get the bond length for the atom at the given index.
Parameters
index The index of the atom
Returns
The bond length or null if not set
Definition at line 339 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondLength().
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
getBondRefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtom (int index)
Get the bond reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The bond reference atom or null if not set
Definition at line 258 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondRefAtom().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex().
getBondRefAtomIndex()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex (int index)
Get the index of the bond reference atom for the atom at the given index.
Parameters
index The index of the atom
Returns
The index of the bond reference atom or -1 if not set
Definition at line 270 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCASrc(), denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondRefAtomIndex(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral().
getBondsToAdd()
List< int[]> denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToAdd ()
Get the bonds to add to the Z-matrix.
Returns
A list of bonds to add defined by the 0-basedindex of the atoms in the ZMatrix.
Definition at line 154 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getId(), denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToAdd().
getBondsToDel()
List< int[]> denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel ()
Get the bonds to delete from the ZMatrix.
Returns
The bonds to delete from the ZMatrix
Definition at line 188 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetBondsToDel().
getChiralFlag()
Integer denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag (int index)
Get the chiral flag for the atom at the given index.
Parameters
index The index of the atom
Returns
The chiral flag or null if not set
Definition at line 375 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getChiralFlag().
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetChiralFlag(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral().
getFirstRefAtomId()
static int denoptim.molecularmodeling.zmatrix.ZMatrix.getFirstRefAtomId (int i1, IAtomContainer mol) static private
Definition at line 713 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC().
getId()
String denoptim.molecularmodeling.zmatrix.ZMatrix.getId ()
Get the id of the ZMatrix.
Returns
The id of the ZMatrix
Definition at line 131 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.id.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getBondData(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToAdd(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIdAndSetId().
getIndex()
int denoptim.molecularmodeling.zmatrix.ZMatrix.getIndex (ZMatrixAtom atm)
Get the index of the atom.
Parameters
atm The atom
Returns
The index of the atom
Definition at line 246 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIndex().
getSecondRefAtomId()
static int denoptim.molecularmodeling.zmatrix.ZMatrix.getSecondRefAtomId (int i1, int i2, IAtomContainer mol) static private
Definition at line 731 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC().
getThirdRefAtomId()
static ObjectPair denoptim.molecularmodeling.zmatrix.ZMatrix.getThirdRefAtomId (int i1, int i2, int i3, IAtomContainer mol, ZMatrix zmat) throws DENOPTIMException static private
Definition at line 749 of file ZMatrix.java.
References denoptim.utils.MathUtils.angle(), denoptim.molecularmodeling.zmatrix.ZMatrix.countPredefinedNeighbours(), and denoptim.utils.MoleculeUtils.getSymbolOrLabel().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC().
getZMatrixFromIAC()
static ZMatrix denoptim.molecularmodeling.zmatrix.ZMatrix.getZMatrixFromIAC (IAtomContainer mol) throws DENOPTIMException static
Convert IAtomContainer to ZMatrix.
Supports only containers where all atoms are reachable following the connectivity and starting from any other atom in the container. Atom types, if any are read from the atom property DENOPTIMConstants#ATMPROPATOMTYPE.
Parameters
mol the IAtomContainer to convert
Returns
the molecule represented by internal coordinates
Definition at line 545 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.utils.MathUtils.angle(), denoptim.constants.DENOPTIMConstants.ATMPROPATOMTYPE, denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.utils.ObjectPair.getFirst(), denoptim.molecularmodeling.zmatrix.ZMatrix.getFirstRefAtomId(), denoptim.utils.ObjectPair.getSecond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getSecondRefAtomId(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.molecularmodeling.zmatrix.ZMatrix.getThirdRefAtomId(), denoptim.utils.RotationalSpaceUtils.PROPERTY_ROTDBDCSTR_DEF, denoptim.utils.RotationalSpaceUtils.PROPERTY_ROTDBDCSTR_VALUE, denoptim.utils.MathUtils.torsion(), and denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix().
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetZMatrixFromIAC().
hashCode()
int denoptim.molecularmodeling.zmatrix.ZMatrix.hashCode ()
Definition at line 910 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixHashCode().
removeAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrix.removeAtom (ZMatrixAtom atm)
Remove an atom from the ZMatrix.
Parameters
atm The atom to remove
Definition at line 72 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms, and denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testRemoveAtom().
setId()
void denoptim.molecularmodeling.zmatrix.ZMatrix.setId (String id)
Set the id of the ZMatrix.
Parameters
id The id to set
Definition at line 142 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.id.
Referenced by denoptim.integration.tinker.TinkerUtils.readTinkerINT(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testGetIdAndSetId(), denoptim.integration.tinker.TinkerUtilsTest.testINTRoundTrip(), denoptim.integration.tinker.TinkerUtilsTest.testWriteTinkerINT(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixEquals(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testZMatrixHashCode().
usesProperDihedral()
boolean denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral (int idx1, int idx2)
Check if the dihedral between the two atoms at the given indices uses proper torsion.
Parameters
idx1 The index of the first atom
idx2 The index of the second atom
Returns
True if the dihedral uses proper torsion, false otherwise
Definition at line 389 of file ZMatrix.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag(), and denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testUsesProperDihedral().
Member Data Documentation
id
String denoptim.molecularmodeling.zmatrix.ZMatrix.id private
Identifier of this ZMatrix.
Definition at line 31 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), denoptim.molecularmodeling.zmatrix.ZMatrix.getId(), and denoptim.molecularmodeling.zmatrix.ZMatrix.setId().
lstAtoms
List<ZMatrixAtom> denoptim.molecularmodeling.zmatrix.ZMatrix.lstAtoms private
All atoms and pseudoAtoms mentioned in the Zmatrix.
Definition at line 36 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtomCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAtoms(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToAdd(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel(), denoptim.molecularmodeling.zmatrix.ZMatrix.getIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrix.removeAtom(), denoptim.molecularmodeling.zmatrix.ZMatrix.usesProperDihedral(), and denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix().
lstBonds
List<ZMatrixBond> denoptim.molecularmodeling.zmatrix.ZMatrix.lstBonds private
All bonds in the system, whether included or not in the Z-matrix intrinsic connections.
Definition at line 42 of file ZMatrix.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrix.delBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBond(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondCount(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondData(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToAdd(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel(), denoptim.molecularmodeling.zmatrix.ZMatrix.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrix.removeAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.ZMatrix().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/zmatrix/ZMatrix.java