DENOPTIM: denoptim.gui.VertexViewPanel Class Reference
denoptim.gui.VertexViewPanel Class Reference
A panel for visualizing vertices.
Public Member Functions
VertexViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
boolean hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
void deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
void setSwitchable (boolean switchable)
Enable/disable switch-able view.
boolean loadSMILES (String smiles)
Loads a molecule build from a smiles string.
Vertex getLoadedStructure ()
Returns the currently loaded vertex.
void loadPlainStructure (IAtomContainer mol)
Loads a structure in the Jmol viewer.
void loadVertexToViewer (Vertex v)
Loads the given vertex to this viewer.
void clearCurrentSystem ()
Removes the currently visualized molecule and AP table.
void clearMolecularViewer (boolean dataIsComing)
Clears the molecular viewer.
Map< Integer, AttachmentPoint > getActiveMapAPs ()
Returns the map of attachment points in the currently active viewer.
DefaultTableModel getAPTableModel ()
ArrayList< Integer > getSelectedAPIDs ()
Identifies which attachment points are selected in the currently active viewer.
Public Attributes
boolean alteredAPData = false
Flag signalling that data about APs has been changed in the GUI.
Protected Member Functions
ArrayList< IAtom > getAtomsSelectedFromJMol ()
Identifies the atoms that are selected in the Jmol viewer.
void activateTabEditsListener (boolean var)
Allows to activate and deactivate the listener.
void dispose ()
Protected Attributes
final String EMPTYCARDNAME = "emptyCard"
final String GRAPHVIEWERCARDNAME = "emptyVertesCard"
final String MOLVIEWERCARDNAME = "fragViewerCard"
final String TWODVIEWERCARDNAME = "twoDimViewerCard"
Private Member Functions
void initialize ()
void switchToEmptyCard ()
void switchToGraphNodeViewer ()
void switchToMolecularViewer ()
void switchTo2DViewer ()
void loadEmptyVertexToViewer (EmptyVertex ev)
Loads the given empty vertex to this viewer.
void loadFragmentToViewer (Fragment frag)
Loads the given fragments to this viewer.
void loadTemplateToViewer (Template tmpl)
Loads the given template to this viewer.
Private Attributes
Vertex vertex
The currently loaded vertex.
JPanel titlePanel
JLabel labTitle
JButton btnSwitchToNodeViewer
JButton btnSwitchToMolViewer
JButton btnSwitchTo2DViewer
JPanel centralPanel
JPanel emptyViewerCard
FragmentViewPanel fragViewer
VertexAsGraphViewPanel graphNodeViewer
VertexAsTwoDimStructureViewPanel twoDimViewer
IVertexAPSelection activeViewer
boolean editableAPTable = false
boolean switchbleByVertexType = true
Flag enabling/disabling the capability to switch between mol- and graph-based viewer.
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
Detailed Description
A panel for visualizing vertices.
This is a deck of cards that brings up a specific card depending on the type of vertex to visualize.
Author
Marco Foscato
Definition at line 54 of file VertexViewPanel.java.
Constructor & Destructor Documentation
VertexViewPanel()
denoptim.gui.VertexViewPanel.VertexViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
editableTable use true to make the AP table editable
Definition at line 105 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.initialize().
Member Function Documentation
activateTabEditsListener()
void denoptim.gui.VertexViewPanel.activateTabEditsListener (boolean var) protected
Allows to activate and deactivate the listener.
Parameters
var use true to activate the listener
Definition at line 546 of file VertexViewPanel.java.
References denoptim.gui.FragmentViewPanel.activateTabEditsListener(), and denoptim.gui.VertexViewPanel.fragViewer.
Referenced by denoptim.gui.GUIVertexInspector.activateTabEditsListener(), and denoptim.gui.GUIVertexSelector.activateTabEditsListener().
clearCurrentSystem()
void denoptim.gui.VertexViewPanel.clearCurrentSystem ()
Removes the currently visualized molecule and AP table.
Definition at line 469 of file VertexViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearAPTable(), denoptim.gui.VertexAsGraphViewPanel.clearAPTable(), denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.VertexViewPanel.graphNodeViewer, denoptim.gui.VertexViewPanel.switchToEmptyCard(), and denoptim.gui.VertexViewPanel.vertex.
Referenced by denoptim.gui.GUIVertexInspector.clearCurrentSystem(), and denoptim.gui.GUIVertexSelector.clearCurrentSystem().
clearMolecularViewer()
void denoptim.gui.VertexViewPanel.clearMolecularViewer (boolean dataIsComing)
Clears the molecular viewer.
WARNING: this is VERY SLOW: do not do it unless you are sure you really need to clear the data. Typically, if there is incoming data, you do not need to run this, as the old data will be overwritten anyway.
Parameters
dataIsComing set true when there is incoming molecular data to visualize.
Definition at line 491 of file VertexViewPanel.java.
References denoptim.gui.FragmentViewPanel.clearMolecularViewer(), and denoptim.gui.VertexViewPanel.fragViewer.
Referenced by denoptim.gui.GUIVertexInspector.removeCurrentVrtx().
deprotectEdits()
void denoptim.gui.VertexViewPanel.deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
Definition at line 223 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.alteredAPData, denoptim.gui.FragmentViewPanel.deprotectEdits(), denoptim.gui.VertexAsGraphViewPanel.deprotectEdits(), denoptim.gui.VertexViewPanel.fragViewer, and denoptim.gui.VertexViewPanel.graphNodeViewer.
Referenced by denoptim.gui.GUIVertexInspector.deprotectEditedSystem().
dispose()
void denoptim.gui.VertexViewPanel.dispose () protected
Definition at line 556 of file VertexViewPanel.java.
References denoptim.gui.FragmentViewPanel.dispose(), and denoptim.gui.VertexViewPanel.fragViewer.
Referenced by denoptim.gui.GUIVertexInspector.dispose(), and denoptim.gui.GUIVertexSelector.GUIVertexSelector().
getActiveMapAPs()
Map< Integer, AttachmentPoint > denoptim.gui.VertexViewPanel.getActiveMapAPs ()
Returns the map of attachment points in the currently active viewer.
Returns
the map of attachment points in the currently active viewer.
Definition at line 502 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, and denoptim.gui.IVertexAPSelection.getMapOfAPsInTable().
Referenced by denoptim.gui.GUIVertexInspector.saveUnsavedChanges().
getAPTableModel()
DefaultTableModel denoptim.gui.VertexViewPanel.getAPTableModel ()
Returns
the table model of the currently active viewer
Definition at line 512 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, and denoptim.gui.IVertexAPSelection.getAPTableModel().
Referenced by denoptim.gui.GUIVertexInspector.saveUnsavedChanges().
getAtomsSelectedFromJMol()
ArrayList< IAtom > denoptim.gui.VertexViewPanel.getAtomsSelectedFromJMol () protected
Identifies the atoms that are selected in the Jmol viewer.
Returns
the list of selected atoms
Definition at line 535 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.fragViewer, and denoptim.gui.FragmentViewPanel.getAtomsSelectedFromJMol().
Referenced by denoptim.gui.GUIVertexInspector.initialize().
getLoadedStructure()
Vertex denoptim.gui.VertexViewPanel.getLoadedStructure ()
Returns the currently loaded vertex.
In case of mismatch between the system loaded into the Jmol viewer and the one in the local memory, we take that from Jmol and made it be The 'current fragment'. Previously set references to the previous 'current fragment' will make no sense anymore.
Returns
the chemical representation of what is currently visualised. Can be empty and null.
Definition at line 322 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.FragmentViewPanel.getLoadedStructure(), denoptim.gui.VertexViewPanel.switchToMolecularViewer(), and denoptim.gui.VertexViewPanel.vertex.
Referenced by denoptim.gui.GUIVertexInspector.importStructureFromFile(), denoptim.gui.GUIVertexInspector.importStructureFromSMILES(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.gui.GUIVertexInspector.saveUnsavedChanges().
getSelectedAPIDs()
ArrayList< Integer > denoptim.gui.VertexViewPanel.getSelectedAPIDs ()
Identifies which attachment points are selected in the currently active viewer.
Returns
the list of attachment points indexes
Definition at line 524 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, and denoptim.gui.IVertexAPSelection.getSelectedAPIDs().
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
hasUnsavedAPEdits()
boolean denoptim.gui.VertexViewPanel.hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
Returns
true if there are unsaved edits
Definition at line 212 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.alteredAPData.
Referenced by denoptim.gui.GUIVertexInspector.removeCurrentVrtx(), and denoptim.gui.GUIVertexInspector.saveUnsavedChanges().
initialize()
void denoptim.gui.VertexViewPanel.initialize () private
Definition at line 114 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.alteredAPData, denoptim.gui.IVertexAPSelection.APDATACHANGEEVENT, denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, denoptim.gui.VertexViewPanel.centralPanel, denoptim.gui.VertexViewPanel.editableAPTable, denoptim.gui.VertexViewPanel.EMPTYCARDNAME, denoptim.gui.VertexViewPanel.emptyViewerCard, denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.VertexViewPanel.graphNodeViewer, denoptim.gui.VertexViewPanel.GRAPHVIEWERCARDNAME, denoptim.gui.VertexViewPanel.labTitle, denoptim.gui.VertexViewPanel.MOLVIEWERCARDNAME, denoptim.gui.VertexViewPanel.switchTo2DViewer(), denoptim.gui.VertexViewPanel.switchToEmptyCard(), denoptim.gui.VertexViewPanel.switchToGraphNodeViewer(), denoptim.gui.VertexViewPanel.switchToMolecularViewer(), denoptim.gui.VertexViewPanel.titlePanel, denoptim.gui.VertexViewPanel.twoDimViewer, and denoptim.gui.VertexViewPanel.TWODVIEWERCARDNAME.
Referenced by denoptim.gui.VertexViewPanel.VertexViewPanel().
loadEmptyVertexToViewer()
void denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer (EmptyVertex ev) private
Loads the given empty vertex to this viewer.
This type of vertex does not have any associated molecular data, but does have attachment points (APs) that are listed in table of APs.
Parameters
ev the vertex to visualize
Definition at line 387 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, denoptim.gui.VertexViewPanel.graphNodeViewer, denoptim.gui.VertexAsGraphViewPanel.loadVertexToViewer(), denoptim.gui.VertexViewPanel.switchbleByVertexType, and denoptim.gui.VertexViewPanel.switchToGraphNodeViewer().
Referenced by denoptim.gui.VertexViewPanel.loadVertexToViewer().
loadFragmentToViewer()
void denoptim.gui.VertexViewPanel.loadFragmentToViewer (Fragment frag) private
Loads the given fragments to this viewer.
The molecular data is loaded in the Jmol viewer, and the attachment point (AP) information in the the list of APs. Jmol is not aware of AP-related information, so this also launches the generation of the graphical objects representing the APs.
Parameters
frag the fragment to visualize
Definition at line 407 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.VertexViewPanel.graphNodeViewer, denoptim.graph.Fragment.is3D(), denoptim.gui.FragmentViewPanel.loadFragmentToViewer(), denoptim.gui.VertexAsGraphViewPanel.loadVertexToViewer(), denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer(), denoptim.gui.VertexViewPanel.switchbleByVertexType, denoptim.gui.VertexViewPanel.switchTo2DViewer(), denoptim.gui.VertexViewPanel.switchToMolecularViewer(), and denoptim.gui.VertexViewPanel.twoDimViewer.
Referenced by denoptim.gui.VertexViewPanel.loadTemplateToViewer(), and denoptim.gui.VertexViewPanel.loadVertexToViewer().
loadPlainStructure()
void denoptim.gui.VertexViewPanel.loadPlainStructure (IAtomContainer mol)
Loads a structure in the Jmol viewer.
Parameters
mol the structure to load
Definition at line 341 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.FragmentViewPanel.loadPlainStructure(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
Referenced by denoptim.gui.GUIVertexInspector.importStructureFromFile().
loadSMILES()
boolean denoptim.gui.VertexViewPanel.loadSMILES (String smiles)
Loads a molecule build from a smiles string.
The 3D geometry is either taken from remote CACTUS service (requires connection to the Internet) or built with CDK tools, as a fall-back. The CDK builder, however will produce a somewhat lower quality conformation than that obtained from on online generator.
Parameters
smiles the SMILES of the molecule to load
Returns
true if the SMILES could be converted into a 3D structure
Exceptions
DENOPTIMException
Definition at line 305 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.fragViewer, denoptim.gui.FragmentViewPanel.loadSMILES(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
Referenced by denoptim.gui.GUIVertexInspector.importStructureFromSMILES().
loadTemplateToViewer()
void denoptim.gui.VertexViewPanel.loadTemplateToViewer (Template tmpl) private
Loads the given template to this viewer.
Parameters
tmpl the template to visualize
Definition at line 430 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, denoptim.gui.FragmentViewPanel.clearAll(), denoptim.graph.Template.containsAtoms(), denoptim.gui.VertexViewPanel.fragViewer, denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Template.getIAtomContainer(), denoptim.graph.Vertex.getVertexId(), denoptim.gui.VertexViewPanel.graphNodeViewer, denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexAsGraphViewPanel.loadVertexToViewer(), denoptim.gui.VertexAsGraphViewPanel.setVertexSpecificEditableAPTable(), denoptim.gui.VertexViewPanel.switchbleByVertexType, and denoptim.gui.VertexViewPanel.switchToGraphNodeViewer().
Referenced by denoptim.gui.VertexViewPanel.loadVertexToViewer().
loadVertexToViewer()
void denoptim.gui.VertexViewPanel.loadVertexToViewer (Vertex v)
Loads the given vertex to this viewer.
The molecular data is loaded in the Jmol viewer, and the attachment point (AP) information in the the list of APs. Jmol is not aware of AP-related information, so this also launches the generation of the graphical objects representing the APs.
Parameters
frag the fragment to visualize
Definition at line 357 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.labTitle, denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.gui.VertexViewPanel.switchToEmptyCard(), and denoptim.gui.VertexViewPanel.vertex.
Referenced by denoptim.gui.GUIVertexInspector.initialize(), denoptim.gui.GUIVertexInspector.loadCurrentVrtxIdxToViewer(), and denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer().
setSwitchable()
void denoptim.gui.VertexViewPanel.setSwitchable (boolean switchable)
Enable/disable switch-able view.
Does not overwrite the control set upon loading a vertex
Definition at line 236 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, and denoptim.gui.VertexViewPanel.switchbleByVertexType.
Referenced by denoptim.gui.GUIVertexInspector.deprotectEditedSystem(), and denoptim.gui.GUIVertexInspector.protectEditedSystem().
switchTo2DViewer()
void denoptim.gui.VertexViewPanel.switchTo2DViewer () private
Definition at line 285 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, denoptim.gui.VertexViewPanel.centralPanel, denoptim.gui.VertexViewPanel.twoDimViewer, and denoptim.gui.VertexViewPanel.TWODVIEWERCARDNAME.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.loadFragmentToViewer().
switchToEmptyCard()
void denoptim.gui.VertexViewPanel.switchToEmptyCard () private
Definition at line 255 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer, denoptim.gui.VertexViewPanel.btnSwitchToMolViewer, denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer, denoptim.gui.VertexViewPanel.centralPanel, and denoptim.gui.VertexViewPanel.EMPTYCARDNAME.
Referenced by denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.loadVertexToViewer().
switchToGraphNodeViewer()
void denoptim.gui.VertexViewPanel.switchToGraphNodeViewer () private
Definition at line 267 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, denoptim.gui.VertexViewPanel.centralPanel, denoptim.gui.VertexViewPanel.graphNodeViewer, and denoptim.gui.VertexViewPanel.GRAPHVIEWERCARDNAME.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), and denoptim.gui.VertexViewPanel.loadTemplateToViewer().
switchToMolecularViewer()
void denoptim.gui.VertexViewPanel.switchToMolecularViewer () private
Definition at line 276 of file VertexViewPanel.java.
References denoptim.gui.VertexViewPanel.activeViewer, denoptim.gui.VertexViewPanel.centralPanel, denoptim.gui.VertexViewPanel.fragViewer, and denoptim.gui.VertexViewPanel.MOLVIEWERCARDNAME.
Referenced by denoptim.gui.VertexViewPanel.getLoadedStructure(), denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadPlainStructure(), and denoptim.gui.VertexViewPanel.loadSMILES().
Member Data Documentation
activeViewer
IVertexAPSelection denoptim.gui.VertexViewPanel.activeViewer private
Definition at line 84 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.getActiveMapAPs(), denoptim.gui.VertexViewPanel.getAPTableModel(), denoptim.gui.VertexViewPanel.getSelectedAPIDs(), denoptim.gui.VertexViewPanel.switchTo2DViewer(), denoptim.gui.VertexViewPanel.switchToEmptyCard(), denoptim.gui.VertexViewPanel.switchToGraphNodeViewer(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
alteredAPData
boolean denoptim.gui.VertexViewPanel.alteredAPData = false
Flag signalling that data about APs has been changed in the GUI.
Definition at line 69 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.deprotectEdits(), denoptim.gui.VertexViewPanel.hasUnsavedAPEdits(), and denoptim.gui.VertexViewPanel.initialize().
btnSwitchTo2DViewer
JButton denoptim.gui.VertexViewPanel.btnSwitchTo2DViewer private
Definition at line 76 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.gui.VertexViewPanel.setSwitchable(), and denoptim.gui.VertexViewPanel.switchToEmptyCard().
btnSwitchToMolViewer
JButton denoptim.gui.VertexViewPanel.btnSwitchToMolViewer private
Definition at line 75 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.gui.VertexViewPanel.setSwitchable(), and denoptim.gui.VertexViewPanel.switchToEmptyCard().
btnSwitchToNodeViewer
JButton denoptim.gui.VertexViewPanel.btnSwitchToNodeViewer private
Definition at line 74 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.gui.VertexViewPanel.setSwitchable(), and denoptim.gui.VertexViewPanel.switchToEmptyCard().
centralPanel
JPanel denoptim.gui.VertexViewPanel.centralPanel private
Definition at line 78 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.switchTo2DViewer(), denoptim.gui.VertexViewPanel.switchToEmptyCard(), denoptim.gui.VertexViewPanel.switchToGraphNodeViewer(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
editableAPTable
boolean denoptim.gui.VertexViewPanel.editableAPTable = false private
Definition at line 90 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize().
EMPTYCARDNAME
final String denoptim.gui.VertexViewPanel.EMPTYCARDNAME = "emptyCard" protected
Definition at line 85 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.switchToEmptyCard().
emptyViewerCard
JPanel denoptim.gui.VertexViewPanel.emptyViewerCard private
Definition at line 80 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize().
fragViewer
FragmentViewPanel denoptim.gui.VertexViewPanel.fragViewer private
Definition at line 81 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.activateTabEditsListener(), denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.VertexViewPanel.clearMolecularViewer(), denoptim.gui.VertexViewPanel.deprotectEdits(), denoptim.gui.VertexViewPanel.dispose(), denoptim.gui.VertexViewPanel.getAtomsSelectedFromJMol(), denoptim.gui.VertexViewPanel.getLoadedStructure(), denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadPlainStructure(), denoptim.gui.VertexViewPanel.loadSMILES(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
graphNodeViewer
VertexAsGraphViewPanel denoptim.gui.VertexViewPanel.graphNodeViewer private
Definition at line 82 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.VertexViewPanel.deprotectEdits(), denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), and denoptim.gui.VertexViewPanel.switchToGraphNodeViewer().
GRAPHVIEWERCARDNAME
final String denoptim.gui.VertexViewPanel.GRAPHVIEWERCARDNAME = "emptyVertesCard" protected
Definition at line 86 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.switchToGraphNodeViewer().
labTitle
JLabel denoptim.gui.VertexViewPanel.labTitle private
Definition at line 73 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.loadVertexToViewer().
MOLVIEWERCARDNAME
final String denoptim.gui.VertexViewPanel.MOLVIEWERCARDNAME = "fragViewerCard" protected
Definition at line 87 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.switchToMolecularViewer().
serialVersionUID
final long denoptim.gui.VertexViewPanel.serialVersionUID = 1L static private
Version UID.
Definition at line 59 of file VertexViewPanel.java.
switchbleByVertexType
boolean denoptim.gui.VertexViewPanel.switchbleByVertexType = true private
Flag enabling/disabling the capability to switch between mol- and graph-based viewer.
Definition at line 96 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.loadEmptyVertexToViewer(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), and denoptim.gui.VertexViewPanel.setSwitchable().
titlePanel
JPanel denoptim.gui.VertexViewPanel.titlePanel private
Definition at line 71 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize().
twoDimViewer
VertexAsTwoDimStructureViewPanel denoptim.gui.VertexViewPanel.twoDimViewer private
Definition at line 83 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.VertexViewPanel.loadFragmentToViewer(), and denoptim.gui.VertexViewPanel.switchTo2DViewer().
TWODVIEWERCARDNAME
final String denoptim.gui.VertexViewPanel.TWODVIEWERCARDNAME = "twoDimViewerCard" protected
Definition at line 88 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.initialize(), and denoptim.gui.VertexViewPanel.switchTo2DViewer().
vertex
Vertex denoptim.gui.VertexViewPanel.vertex private
The currently loaded vertex.
Definition at line 64 of file VertexViewPanel.java.
Referenced by denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.VertexViewPanel.getLoadedStructure(), and denoptim.gui.VertexViewPanel.loadVertexToViewer().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/VertexViewPanel.java