DENOPTIM: denoptim.graph.SymmetricAPs Class Reference
denoptim.graph.SymmetricAPs Class Reference
A collection of AttachmentPoints that are related by a relation that we call "symmetry", even though this class does not define what such relation is.
Classes
class SymmetricAPsSerializer
Public Member Functions
SymmetricAPs ()
SymmetricAPs (List< AttachmentPoint > symAPs)
String toString ()
SymmetricAPs getSameAs (Set< SymmetricAPs > others)
Identifies a set of symmetric APs that, although it contains references to different instances of AttachmentPoints, it is analogous to this one in the sense defined by SymmetricAPs#sameAs(SymmetricAPs) method.
Set< SymmetricAPs > getAllSameAs (Set< SymmetricAPs > others)
Identifies any set of symmetric APs that, although it contains references to different instances of AttachmentPoints, it is analogous to this one in the sense defined by SymmetricAPs#sameAs(SymmetricAPs) method.
boolean sameAs (SymmetricAPs other)
Checks if this collection SymmetricAPs is analogous to the other one, i.e., they contain AttachmentPoints that satisfy the AttachmentPoint#sameAs(AttachmentPoint) method in the same order.
Public Member Functions inherited from denoptim.graph.SymmetricSet< AttachmentPoint >
boolean add (T item)
Adds an item to this list, if not already present.
Static Private Attributes
static final long serialVersionUID = 4L
Version ID.
Detailed Description
A collection of AttachmentPoints that are related by a relation that we call "symmetry", even though this class does not define what such relation is.
Therefore, any elsewhere-defined relation may characterize the items collected in instances of this class.
Definition at line 20 of file SymmetricAPs.java.
Constructor & Destructor Documentation
SymmetricAPs() [1/2]
denoptim.graph.SymmetricAPs.SymmetricAPs ()
Definition at line 30 of file SymmetricAPs.java.
SymmetricAPs() [2/2]
denoptim.graph.SymmetricAPs.SymmetricAPs (List< AttachmentPoint > symAPs)
Definition at line 37 of file SymmetricAPs.java.
Member Function Documentation
getAllSameAs()
Set< SymmetricAPs > denoptim.graph.SymmetricAPs.getAllSameAs (Set< SymmetricAPs > others)
Identifies any set of symmetric APs that, although it contains references to different instances of AttachmentPoints, it is analogous to this one in the sense defined by SymmetricAPs#sameAs(SymmetricAPs) method.
Parameters
others
Returns
the first found SymmetricAPs that is same as this one or null if no such object is found in the given set.
Definition at line 89 of file SymmetricAPs.java.
References denoptim.graph.SymmetricAPs.sameAs().
getSameAs()
SymmetricAPs denoptim.graph.SymmetricAPs.getSameAs (Set< SymmetricAPs > others)
Identifies a set of symmetric APs that, although it contains references to different instances of AttachmentPoints, it is analogous to this one in the sense defined by SymmetricAPs#sameAs(SymmetricAPs) method.
Parameters
others
Returns
the first found SymmetricAPs that is same as this one or null if no such object is found in the given set.
Definition at line 70 of file SymmetricAPs.java.
References denoptim.graph.SymmetricAPs.sameAs().
Referenced by denoptim.graph.SymmetricAPsTest.testGetSameAsThis().
sameAs()
boolean denoptim.graph.SymmetricAPs.sameAs (SymmetricAPs other)
Checks if this collection SymmetricAPs is analogous to the other one, i.e., they contain AttachmentPoints that satisfy the AttachmentPoint#sameAs(AttachmentPoint) method in the same order.
Parameters
other
Returns
true if this and other are same (not equal!).
Definition at line 108 of file SymmetricAPs.java.
Referenced by denoptim.graph.SymmetricAPs.getAllSameAs(), denoptim.graph.SymmetricAPs.getSameAs(), and denoptim.graph.SymmetricAPsTest.testSameAs().
toString()
String denoptim.graph.SymmetricAPs.toString ()
Definition at line 45 of file SymmetricAPs.java.
Member Data Documentation
serialVersionUID
final long denoptim.graph.SymmetricAPs.serialVersionUID = 4L static private
Version ID.
Definition at line 26 of file SymmetricAPs.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/SymmetricAPs.java