DENOPTIM: denoptim.fragmenter.FragmentClustererTest Class Reference
denoptim.fragmenter.FragmentClustererTest Class Reference
Unit test for fragmenter's tools.
Public Member Functions
void testDistanceAsRMSD ()
void testGetRMSDStatsOfNoisyDistorsions ()
void testCluster () throws Exception
void testCluster2 () throws Exception
Private Member Functions
IAtomContainer getMol (Fragment frag)
Converts the fragment into a collection of atoms where attachment points are converted into atoms that can be visualized with any molecular viewer.
Point3d getNoisyPoint (Point3d p, double noiseMagnitude)
The noise magnitude is to be interpreted as half of the overall magnitude.
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Randomizer rng = new Randomizer(1L)
Random number generator.
Detailed Description
Unit test for fragmenter's tools.
Definition at line 38 of file FragmentClustererTest.java.
Member Function Documentation
getMol()
IAtomContainer denoptim.fragmenter.FragmentClustererTest.getMol (Fragment frag) private
Converts the fragment into a collection of atoms where attachment points are converted into atoms that can be visualized with any molecular viewer.
Definition at line 507 of file FragmentClustererTest.java.
References denoptim.graph.Fragment.atoms(), denoptim.fragmenter.FragmentClustererTest.builder, and denoptim.graph.Fragment.getAttachmentPoints().
Referenced by denoptim.fragmenter.FragmentClustererTest.testCluster().
getNoisyPoint()
Point3d denoptim.fragmenter.FragmentClustererTest.getNoisyPoint (Point3d p, double noiseMagnitude) private
The noise magnitude is to be interpreted as half of the overall magnitude.
And the distribution of noise is uniform in [-noiseMagnitude,noiseMagnitude].
Definition at line 607 of file FragmentClustererTest.java.
References denoptim.utils.Randomizer.getNoisyPoint(), and denoptim.fragmenter.FragmentClustererTest.rng.
Referenced by denoptim.fragmenter.FragmentClustererTest.testCluster(), and denoptim.fragmenter.FragmentClustererTest.testCluster2().
testCluster()
void denoptim.fragmenter.FragmentClustererTest.testCluster () throws Exception
Definition at line 188 of file FragmentClustererTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.fragmenter.ClusterableFragment.allCoords, denoptim.graph.Fragment.atoms(), denoptim.fragmenter.FragmentClustererTest.builder, denoptim.fragmenter.FragmentClusterer.cluster(), denoptim.fragmenter.ClusterableFragment.convertToPointArray(), denoptim.graph.Vertex.getAP(), denoptim.graph.Fragment.getAtom(), denoptim.graph.Fragment.getAttachmentPoints(), denoptim.fragmenter.FragmentClusterer.getClusterCentroids(), denoptim.fragmenter.FragmentClusterer.getClusters(), denoptim.graph.AttachmentPoint.getDirectionVector(), denoptim.fragmenter.FragmentClustererTest.getMol(), denoptim.fragmenter.FragmentClustererTest.getNoisyPoint(), denoptim.fragmenter.FragmentClusterer.getTransformedClusters(), denoptim.graph.APClass.make(), denoptim.fragmenter.ClusterableFragment.setNaturalNodeOrder(), denoptim.programs.RunTimeParameters.setVerbosity(), denoptim.programs.RunTimeParameters.startConsoleLogger(), denoptim.graph.Vertex.BBType.UNDEFINED, denoptim.files.FileFormat.VRTXSDF, denoptim.io.DenoptimIO.writeSDFFile(), and denoptim.io.DenoptimIO.writeVertexesToFile().
testCluster2()
void denoptim.fragmenter.FragmentClustererTest.testCluster2 () throws Exception
Definition at line 520 of file FragmentClustererTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.fragmenter.FragmentClustererTest.builder, denoptim.fragmenter.FragmentClusterer.cluster(), denoptim.fragmenter.FragmentClusterer.getClusters(), denoptim.fragmenter.FragmentClustererTest.getNoisyPoint(), denoptim.graph.APClass.make(), denoptim.fragmenter.ClusterableFragment.setNaturalNodeOrder(), and denoptim.graph.Vertex.BBType.UNDEFINED.
testDistanceAsRMSD()
void denoptim.fragmenter.FragmentClustererTest.testDistanceAsRMSD ()
Definition at line 54 of file FragmentClustererTest.java.
References denoptim.fragmenter.FragmentClusterer.DistanceAsRMSD.compute().
testGetRMSDStatsOfNoisyDistorsions()
void denoptim.fragmenter.FragmentClustererTest.testGetRMSDStatsOfNoisyDistorsions ()
Definition at line 120 of file FragmentClustererTest.java.
References denoptim.fragmenter.FragmentClusterer.getRMSDStatsOfNoisyDistorsions().
Member Data Documentation
builder
IChemObjectBuilder denoptim.fragmenter.FragmentClustererTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 44 of file FragmentClustererTest.java.
Referenced by denoptim.fragmenter.FragmentClustererTest.getMol(), denoptim.fragmenter.FragmentClustererTest.testCluster(), and denoptim.fragmenter.FragmentClustererTest.testCluster2().
rng
Randomizer denoptim.fragmenter.FragmentClustererTest.rng = new Randomizer(1L) private
Random number generator.
Definition at line 49 of file FragmentClustererTest.java.
Referenced by denoptim.fragmenter.FragmentClustererTest.getNoisyPoint().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragmenter/FragmentClustererTest.java