DENOPTIM: denoptim.utils.FormulaUtilsTest Class Reference
denoptim.utils.FormulaUtilsTest Class Reference
Unit test for tools manipulating molecular formulae.
Public Member Functions
void testParseFormula () throws Exception
void testParsingOfCSDFormula () throws Exception
void testCompareFormulaAndElementalAnalysis () throws Exception
Private Member Functions
String convertSimpleToString (Map< String, Double > elCounts)
String convertToString (Map< String, ArrayList< Double > > elCounts)
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Detailed Description
Unit test for tools manipulating molecular formulae.
Author
Marco Foscato
Definition at line 43 of file FormulaUtilsTest.java.
Member Function Documentation
convertSimpleToString()
String denoptim.utils.FormulaUtilsTest.convertSimpleToString (Map< String, Double > elCounts) private
Definition at line 149 of file FormulaUtilsTest.java.
References denoptim.utils.GeneralUtils.getEnglishFormattedDecimal().
Referenced by denoptim.utils.FormulaUtilsTest.testParseFormula().
convertToString()
String denoptim.utils.FormulaUtilsTest.convertToString (Map< String, ArrayList< Double > > elCounts) private
Definition at line 165 of file FormulaUtilsTest.java.
References denoptim.utils.GeneralUtils.getEnglishFormattedDecimal().
Referenced by denoptim.utils.FormulaUtilsTest.testParsingOfCSDFormula().
testCompareFormulaAndElementalAnalysis()
void denoptim.utils.FormulaUtilsTest.testCompareFormulaAndElementalAnalysis () throws Exception
Definition at line 185 of file FormulaUtilsTest.java.
References denoptim.utils.FormulaUtilsTest.builder, and denoptim.utils.FormulaUtils.compareFormulaAndElementalAnalysis().
testParseFormula()
void denoptim.utils.FormulaUtilsTest.testParseFormula () throws Exception
Definition at line 54 of file FormulaUtilsTest.java.
References denoptim.utils.FormulaUtilsTest.convertSimpleToString(), and denoptim.utils.FormulaUtils.parseFormula().
testParsingOfCSDFormula()
void denoptim.utils.FormulaUtilsTest.testParsingOfCSDFormula () throws Exception
Definition at line 81 of file FormulaUtilsTest.java.
References denoptim.utils.FormulaUtilsTest.convertToString(), and denoptim.utils.FormulaUtils.parseCSDFormula().
Member Data Documentation
builder
IChemObjectBuilder denoptim.utils.FormulaUtilsTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 49 of file FormulaUtilsTest.java.
Referenced by denoptim.utils.FormulaUtilsTest.testCompareFormulaAndElementalAnalysis().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/utils/FormulaUtilsTest.java