DENOPTIM: denoptim.ga.EAUtilsTest Class Reference
denoptim.ga.EAUtilsTest Class Reference
Unit test.
Public Member Functions
void testBuildGraphFromTemplateScaffold () throws Exception
void testAvoidRedundantXOver () throws Exception
void testBuildByXOver_SubGraph () throws Exception
void testBuildByXOver_Embedded_Free () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
void testBuildByXOver_Embedded_FreeBackwards () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
void testBuildByXOver_Embedded_FixedStructure () throws Exception
void testCandidateGenerationMethod () throws Exception
void testCandidateGenerationMethodReproducibility () throws Exception
void testCrowdingProbability () throws Exception
void testSelectNonScaffoldNonCapVertex () throws Exception
void testChooseNumberOfSitesToMutate () throws Exception
void testMakeGraphFromFragmentationOfMol () throws Exception
void testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy () throws Exception
void testMakeGraphFromFragmentationOfMol_Symmetry () throws Exception
void testMakeGraphFromFragmentationOfMol_linearities () throws Exception
void testMakeGraphFromFragmentationOfMol_symmetry () throws Exception
Test the detection of "some" symmetry.
void testMakeGraphFromFragmentationOfMol_cappingGroups () throws Exception
void testSearchForApPairsSuitableToRingFusion () throws Exception
void testFusionSiteDetection_ImposeSymmetry () throws Exception
void testGetUsableAromaticBridges () throws Exception
void testGetUsableAliphaticBridges () throws Exception
Static Public Member Functions
static void replaceHatomWithAP (Fragment frag, int srcId, APClass apc)
Static Package Attributes
static File tempDir
Private Member Functions
FragmentSpaceParameters prepare () throws DENOPTIMException
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Static Private Attributes
static APClass APCA
static APClass APCB
static APClass APCC
static String a ="A"
static String b ="B"
static String c ="C"
static final String SEP = System.getProperty("file.separator")
static final String NL = System.getProperty("line.separator")
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 87 of file EAUtilsTest.java.
Member Function Documentation
prepare()
FragmentSpaceParameters denoptim.ga.EAUtilsTest.prepare () throws DENOPTIMException private
Definition at line 106 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.a, denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.ga.EAUtilsTest.APCA, denoptim.ga.EAUtilsTest.APCB, denoptim.ga.EAUtilsTest.APCC, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.ga.EAUtilsTest.b, denoptim.ga.EAUtilsTest.c, denoptim.graph.Template.ContractLevel.FIXED_STRUCT, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.graph.Edge.BondType.SINGLE.
Referenced by denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), and denoptim.ga.EAUtilsTest.testBuildGraphFromTemplateScaffold().
replaceHatomWithAP()
static void denoptim.ga.EAUtilsTest.replaceHatomWithAP (Fragment frag, int srcId, APClass apc) static
Definition at line 2373 of file EAUtilsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.getAtom(), denoptim.graph.Fragment.getConnectedAtomsList(), denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), and denoptim.graph.Fragment.removeAtom().
Referenced by denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry(), denoptim.ga.EAUtilsTest.testGetUsableAliphaticBridges(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
testAvoidRedundantXOver()
void denoptim.ga.EAUtilsTest.testAvoidRedundantXOver () throws Exception
Definition at line 230 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.programs.RunTimeParameters.setParameters().
testBuildByXOver_Embedded_FixedStructure()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure () throws Exception
Definition at line 456 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FIXED_STRUCT, denoptim.graph.Candidate.getGraph(), denoptim.graph.Template.getInnerGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.Template.setContractLevel().
testBuildByXOver_Embedded_Free()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_Free () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
Note that the order of APs in on the templates changes as a result of the crossover. For this reason, the backwards crossover of the graphs from getPairOfTestGraphsBxo() does not produce the graphs from getPairOfTestGraphsB(), but those from getPairOfTestGraphsBxoxo().
Definition at line 348 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FREE, denoptim.graph.Candidate.getGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.DGraph.sameAs().
testBuildByXOver_Embedded_FreeBackwards()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FreeBackwards () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
Note that the order of APs in on the templates changes as a result of the crossover. For this reason, the backwards crossover of the graphs from getPairOfTestGraphsBxo() does not produce the graphs from getPairOfTestGraphsB(), but those from getPairOfTestGraphsBxoxo().
Definition at line 407 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FREE, denoptim.graph.Candidate.getGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.DGraph.sameAs().
testBuildByXOver_SubGraph()
void denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph () throws Exception
Definition at line 271 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.Candidate.getGraph(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.Candidate.setFitness().
testBuildGraphFromTemplateScaffold()
void denoptim.ga.EAUtilsTest.testBuildGraphFromTemplateScaffold () throws Exception
Definition at line 200 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.buildGraph(), denoptim.graph.Template.getMutationSites(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.EAUtilsTest.prepare(), and denoptim.programs.RunTimeParameters.setParameters().
testCandidateGenerationMethod()
void denoptim.ga.EAUtilsTest.testCandidateGenerationMethod () throws Exception
Definition at line 565 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.c, and denoptim.ga.EAUtils.pickNewCandidateGenerationMode().
testCandidateGenerationMethodReproducibility()
void denoptim.ga.EAUtilsTest.testCandidateGenerationMethodReproducibility () throws Exception
Definition at line 605 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.pickNewCandidateGenerationMode().
testChooseNumberOfSitesToMutate()
void denoptim.ga.EAUtilsTest.testChooseNumberOfSitesToMutate () throws Exception
Definition at line 731 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.chooseNumberOfSitesToMutate().
testCrowdingProbability()
void denoptim.ga.EAUtilsTest.testCrowdingProbability () throws Exception
Definition at line 654 of file EAUtilsTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.ga.EAUtils.getCrowdingProbability(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.DGraphTest.makeTestGraphA().
testFusionSiteDetection_ImposeSymmetry()
void denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry () throws Exception
Definition at line 2288 of file EAUtilsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.DGraph.addVertex(), denoptim.ga.EAUtilsTest.builder, denoptim.utils.MoleculeUtils.explicitHydrogens(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.APClass.make(), denoptim.ga.EAUtilsTest.replaceHatomWithAP(), denoptim.ga.EAUtils.searchRingFusionSites(), denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.fragspace.FragmentSpace.setSymmConstraints().
testGetUsableAliphaticBridges()
void denoptim.ga.EAUtilsTest.testGetUsableAliphaticBridges () throws Exception
Definition at line 2495 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.builder, denoptim.utils.MoleculeUtils.explicitHydrogens(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.ga.EAUtils.getUsableAliphaticBridges(), denoptim.graph.APClass.make(), denoptim.ga.EAUtilsTest.replaceHatomWithAP(), and denoptim.graph.Vertex.setBuildingBlockId().
testGetUsableAromaticBridges()
void denoptim.ga.EAUtilsTest.testGetUsableAromaticBridges () throws Exception
Definition at line 2394 of file EAUtilsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.ga.EAUtils.getUsableAromaticBridges(), and denoptim.graph.APClass.make().
testMakeGraphFromFragmentationOfMol()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol () throws Exception
Definition at line 757 of file EAUtilsTest.java.
References denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.Template.ContractLevel.FIXED, denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Template.getContractLevel(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.Template.getInnerGraph(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.NL, denoptim.io.DenoptimIO.readSDFFile(), denoptim.graph.GraphPattern.RING, denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.ga.EAUtilsTest.SEP, denoptim.ga.EAUtilsTest.tempDir, and denoptim.io.DenoptimIO.writeData().
testMakeGraphFromFragmentationOfMol_cappingGroups()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_cappingGroups () throws Exception
Definition at line 1227 of file EAUtilsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.ga.EAUtilsTest.builder, denoptim.utils.MoleculeUtils.explicitHydrogens(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getVertexCount(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, denoptim.graph.APClass.make(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.programs.RunTimeParameters.setParameters().
testMakeGraphFromFragmentationOfMol_linearities()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities () throws Exception
Definition at line 1037 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.a, denoptim.ga.EAUtilsTest.builder, denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.graph.DGraph.getEdgeCount(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getRingCount(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, and denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol().
testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy () throws Exception
Definition at line 886 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.builder, denoptim.fragmenter.ScaffoldingPolicy.ELEMENT, denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.Vertex.getIAtomContainer(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
testMakeGraphFromFragmentationOfMol_Symmetry()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry () throws Exception
Definition at line 941 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.builder, denoptim.fragmenter.ScaffoldingPolicy.ELEMENT, denoptim.graph.DGraph.getEdgeCount(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexCount(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, and denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol().
testMakeGraphFromFragmentationOfMol_symmetry()
void denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_symmetry () throws Exception
Test the detection of "some" symmetry.
: a topology that would result in something close to a C3 point group geometry. Three symmetric branches that form a three-cyclic system. This method tests the capacity to detect that vertexes that have no sym set of APs but can be flagged as symmetric because they are part of a chain rooted on a vertex with sym APs (i.e., the bridge head).
Definition at line 1134 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.builder, denoptim.fragmenter.ScaffoldingPolicy.ELEMENT, denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getVertexWithId(), denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, and denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol().
testSearchForApPairsSuitableToRingFusion()
void denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion () throws Exception
Definition at line 1295 of file EAUtilsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.RelatedAPPair.apA, denoptim.graph.RelatedAPPair.apB, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.ga.EAUtilsTest.builder, denoptim.utils.MoleculeUtils.explicitHydrogens(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.Fragment.getAttachmentPoints(), denoptim.fragspace.FragmentSpace.getPolarizedRCV(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.APClass.make(), denoptim.graph.RelatedAPPair.propID, denoptim.ga.EAUtilsTest.replaceHatomWithAP(), denoptim.ga.EAUtils.searchRingFusionSites(), denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.graph.Vertex.setVertexId().
testSelectNonScaffoldNonCapVertex()
void denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex () throws Exception
Definition at line 681 of file EAUtilsTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.ga.EAUtils.selectNonScaffoldNonCapVertex(), and denoptim.graph.Vertex.setBuildingBlockType().
Member Data Documentation
a
String denoptim.ga.EAUtilsTest.a ="A" static private
Definition at line 91 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare(), and denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities().
APCA
APClass denoptim.ga.EAUtilsTest.APCA static private
Definition at line 90 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
APCB
APClass denoptim.ga.EAUtilsTest.APCB static private
Definition at line 90 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
APCC
APClass denoptim.ga.EAUtilsTest.APCC static private
Definition at line 90 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
b
String denoptim.ga.EAUtilsTest.b ="B" static private
Definition at line 91 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
builder
IChemObjectBuilder denoptim.ga.EAUtilsTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 99 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry(), denoptim.ga.EAUtilsTest.testGetUsableAliphaticBridges(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_cappingGroups(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_symmetry(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
c
String denoptim.ga.EAUtilsTest.c ="C" static private
Definition at line 91 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare(), and denoptim.ga.EAUtilsTest.testCandidateGenerationMethod().
NL
final String denoptim.ga.EAUtilsTest.NL = System.getProperty("line.separator") static private
Definition at line 94 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol().
SEP
final String denoptim.ga.EAUtilsTest.SEP = System.getProperty("file.separator") static private
Definition at line 93 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol().
tempDir
File denoptim.ga.EAUtilsTest.tempDir static package
Definition at line 102 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/ga/EAUtilsTest.java