DENOPTIM: denoptim.integration.tinker.TinkerAtom Class Reference
denoptim.integration.tinker.TinkerAtom Class Reference
Based on the code from ffx.kenai.com Michael J.
Public Member Functions
TinkerAtom ()
TinkerAtom (int xyzIndex, String atomStr, int ffAtomType, double[] xyz, int[] atmNb, double[] distAngles)
void setAtomNeighbours (int[] atmNb)
int[] getAtomNeighbours ()
void setDistAngle (double[] distAngles)
double[] getDistAngle ()
void moveTo (double[] d)
Add a vector to the Atom's current position vector.
void moveTo (double a, double b, double c)
void setXYZ (double[] xyz)
double[] getXYZ ()
void getXYZ (double[] x)
int getXYZIndex ()
Gets the XYZ Index.
void setXYZIndex (int xyzIndex)
String getAtomString ()
void setAtomString (String atomStr)
int getAtomType ()
void setAtomType (int ffAtomType)
void setVertexId (long vidx)
long getVertexId ()
boolean usesProperTorsion ()
Evaluates whether this TinkerAtom's line refers to a torsion (chiral flag is 0) or to an inproper torsion (chiral flag is +/-1).
String toString ()
Private Attributes
int ffAtomType
String atomStr
double[] xyz
int xyzIndex
double[] distAngles
int[] atmNb
long vtxId
Detailed Description
Based on the code from ffx.kenai.com Michael J.
Schnieders
Author
Vishwesh Venkatraman
Definition at line 25 of file TinkerAtom.java.
Constructor & Destructor Documentation
TinkerAtom() [1/2]
denoptim.integration.tinker.TinkerAtom.TinkerAtom ()
Definition at line 66 of file TinkerAtom.java.
TinkerAtom() [2/2]
denoptim.integration.tinker.TinkerAtom.TinkerAtom (int xyzIndex, String atomStr, int ffAtomType, double[] xyz, int[] atmNb, double[] distAngles)
Definition at line 72 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atmNb, denoptim.integration.tinker.TinkerAtom.atomStr, denoptim.integration.tinker.TinkerAtom.distAngles, denoptim.integration.tinker.TinkerAtom.ffAtomType, denoptim.integration.tinker.TinkerAtom.xyz, and denoptim.integration.tinker.TinkerAtom.xyzIndex.
Member Function Documentation
getAtomNeighbours()
int[] denoptim.integration.tinker.TinkerAtom.getAtomNeighbours ()
Definition at line 100 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atmNb.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.getConnectedAtoms(), denoptim.integration.tinker.TinkerMolecule.isConnected(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.integration.tinker.TinkerUtils.writeIC().
getAtomString()
String denoptim.integration.tinker.TinkerAtom.getAtomString ()
Definition at line 210 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atomStr.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.molecularmodeling.RingClosureTool.setTinkerTypes(), denoptim.integration.tinker.TinkerUtils.setTinkerTypes(), and denoptim.integration.tinker.TinkerUtils.writeIC().
getAtomType()
int denoptim.integration.tinker.TinkerAtom.getAtomType ()
Definition at line 224 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.ffAtomType.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.TinkerMolecule.printIC(), and denoptim.integration.tinker.TinkerUtils.writeIC().
getDistAngle()
double[] denoptim.integration.tinker.TinkerAtom.getDistAngle ()
Definition at line 114 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.distAngles.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.integration.tinker.TinkerUtils.writeIC().
getVertexId()
long denoptim.integration.tinker.TinkerAtom.getVertexId ()
Definition at line 245 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.vtxId.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy().
getXYZ() [1/2]
double[] denoptim.integration.tinker.TinkerAtom.getXYZ ()
getXYZ
Returns
an array of double.
Definition at line 169 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyz.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy().
getXYZ() [2/2]
void denoptim.integration.tinker.TinkerAtom.getXYZ (double[] x)
getXYZ
Parameters
x an array of double.
Definition at line 181 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyz.
getXYZIndex()
int denoptim.integration.tinker.TinkerAtom.getXYZIndex ()
Gets the XYZ Index.
Returns
XYZ Index
Definition at line 195 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyzIndex.
Referenced by denoptim.integration.tinker.TinkerMolecule.getAtom(), denoptim.integration.tinker.TinkerMolecule.getConnectedAtoms(), denoptim.integration.tinker.TinkerMolecule.printIC(), denoptim.integration.tinker.TinkerBond.TinkerBond(), and denoptim.integration.tinker.TinkerUtils.writeIC().
moveTo() [1/2]
void denoptim.integration.tinker.TinkerAtom.moveTo (double a, double b, double c)
moveTo
Parameters
a a double.
b a double.
c a double.
Definition at line 142 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyz.
moveTo() [2/2]
void denoptim.integration.tinker.TinkerAtom.moveTo (double[] d)
Add a vector to the Atom's current position vector.
Parameters
d Vector to add to the current position
Definition at line 126 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyz.
Referenced by denoptim.integration.tinker.TinkerMolecule.set3DCoordinates(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
setAtomNeighbours()
void denoptim.integration.tinker.TinkerAtom.setAtomNeighbours (int[] atmNb)
Definition at line 93 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atmNb.
setAtomString()
void denoptim.integration.tinker.TinkerAtom.setAtomString (String atomStr)
Definition at line 217 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atomStr.
Referenced by denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor().
setAtomType()
void denoptim.integration.tinker.TinkerAtom.setAtomType (int ffAtomType)
Definition at line 231 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.ffAtomType.
Referenced by denoptim.molecularmodeling.RingClosureTool.setTinkerTypes(), and denoptim.integration.tinker.TinkerUtils.setTinkerTypes().
setDistAngle()
void denoptim.integration.tinker.TinkerAtom.setDistAngle (double[] distAngles)
Definition at line 107 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.distAngles.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), and denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor().
setVertexId()
void denoptim.integration.tinker.TinkerAtom.setVertexId (long vidx)
Definition at line 238 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerMolecule.deepCopy(), and denoptim.integration.tinker.TinkerUtils.getICFromIAC().
setXYZ()
void denoptim.integration.tinker.TinkerAtom.setXYZ (double[] xyz)
setXYZ
Parameters
xyz an array of double.
Definition at line 157 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyz.
setXYZIndex()
void denoptim.integration.tinker.TinkerAtom.setXYZIndex (int xyzIndex)
Definition at line 202 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.xyzIndex.
toString()
String denoptim.integration.tinker.TinkerAtom.toString ()
Definition at line 275 of file TinkerAtom.java.
References denoptim.integration.tinker.TinkerAtom.atmNb, denoptim.integration.tinker.TinkerAtom.atomStr, denoptim.integration.tinker.TinkerAtom.distAngles, denoptim.integration.tinker.TinkerAtom.ffAtomType, denoptim.integration.tinker.TinkerAtom.vtxId, denoptim.integration.tinker.TinkerAtom.xyz, and denoptim.integration.tinker.TinkerAtom.xyzIndex.
Referenced by denoptim.integration.tinker.TinkerUtils.getICFromIAC().
usesProperTorsion()
boolean denoptim.integration.tinker.TinkerAtom.usesProperTorsion ()
Evaluates whether this TinkerAtom's line refers to a torsion (chiral flag is 0) or to an inproper torsion (chiral flag is +/-1).
For the position to be defined by a proper torsion, all 3 neighbouring atoms has to be defined (!= 0).
Returns
true if this TinkerAtom makes use of a proper torsion
Definition at line 261 of file TinkerAtom.java.
Member Data Documentation
atmNb
int [] denoptim.integration.tinker.TinkerAtom.atmNb private
Definition at line 57 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getAtomNeighbours(), denoptim.integration.tinker.TinkerAtom.setAtomNeighbours(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
atomStr
String denoptim.integration.tinker.TinkerAtom.atomStr private
Definition at line 35 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getAtomString(), denoptim.integration.tinker.TinkerAtom.setAtomString(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
distAngles
double [] denoptim.integration.tinker.TinkerAtom.distAngles private
Definition at line 50 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getDistAngle(), denoptim.integration.tinker.TinkerAtom.setDistAngle(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
ffAtomType
int denoptim.integration.tinker.TinkerAtom.ffAtomType private
Definition at line 30 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getAtomType(), denoptim.integration.tinker.TinkerAtom.setAtomType(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
vtxId
long denoptim.integration.tinker.TinkerAtom.vtxId private
Definition at line 62 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getVertexId(), and denoptim.integration.tinker.TinkerAtom.toString().
xyz
double [] denoptim.integration.tinker.TinkerAtom.xyz private
Definition at line 40 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getXYZ(), denoptim.integration.tinker.TinkerAtom.moveTo(), denoptim.integration.tinker.TinkerAtom.setXYZ(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
xyzIndex
int denoptim.integration.tinker.TinkerAtom.xyzIndex private
Definition at line 45 of file TinkerAtom.java.
Referenced by denoptim.integration.tinker.TinkerAtom.getXYZIndex(), denoptim.integration.tinker.TinkerAtom.setXYZIndex(), denoptim.integration.tinker.TinkerAtom.TinkerAtom(), and denoptim.integration.tinker.TinkerAtom.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/integration/tinker/TinkerAtom.java