DENOPTIM: denoptim.fragspace.GraphLinkFinderTest Class Reference
denoptim.fragspace.GraphLinkFinderTest Class Reference
Unit test.
Public Member Functions
void testLinkFromVertex () throws Exception
void testLinkFromEdge () throws Exception
void testLinkFromEdgeOneMatch () throws Exception
void testLinkFromEdgeNoMatch () throws Exception
Private Member Functions
FragmentSpace prepare () throws DENOPTIMException
DGraph makeTestGraphA () throws DENOPTIMException
Creates a test graph that looks like this: v0(A)-(A)v1(B)-(B)v2.
DGraph makeTestGraphE () throws DENOPTIMException
Creates a test graph that looks like this: v0(E)-(E)v1.
DGraph makeTestGraphF () throws DENOPTIMException
Creates a test graph that looks like this: v0(F)-(F)v1.
void ensureConsistencyWithExpectations (Map< Integer, List< APClass > > expected, Map< Vertex, List< APMapping > > actual)
Static Private Attributes
static APClass APCA
static APClass APCB
static APClass APCC
static APClass APCD
static APClass APCE
static APClass APCF
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 52 of file GraphLinkFinderTest.java.
Member Function Documentation
ensureConsistencyWithExpectations()
void denoptim.fragspace.GraphLinkFinderTest.ensureConsistencyWithExpectations (Map< Integer, List< APClass > > expected, Map< Vertex, List< APMapping > > actual) private
Definition at line 416 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeNoMatch(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch().
makeTestGraphA()
DGraph denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA () throws DENOPTIMException private
Creates a test graph that looks like this: v0(A)-(A)v1(B)-(B)v2.
Exceptions
DENOPTIMException
Definition at line 230 of file GraphLinkFinderTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromVertex().
makeTestGraphE()
DGraph denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE () throws DENOPTIMException private
Creates a test graph that looks like this: v0(E)-(E)v1.
Exceptions
DENOPTIMException
Definition at line 253 of file GraphLinkFinderTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.GraphLinkFinderTest.prepare(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch().
makeTestGraphF()
DGraph denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF () throws DENOPTIMException private
Creates a test graph that looks like this: v0(F)-(F)v1.
Exceptions
DENOPTIMException
Definition at line 273 of file GraphLinkFinderTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.GraphLinkFinderTest.prepare(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeNoMatch().
prepare()
FragmentSpace denoptim.fragspace.GraphLinkFinderTest.prepare () throws DENOPTIMException private
Definition at line 58 of file GraphLinkFinderTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.fragspace.GraphLinkFinderTest.APCA, denoptim.fragspace.GraphLinkFinderTest.APCB, denoptim.fragspace.GraphLinkFinderTest.APCC, denoptim.fragspace.GraphLinkFinderTest.APCD, denoptim.fragspace.GraphLinkFinderTest.APCE, denoptim.fragspace.GraphLinkFinderTest.APCF, denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.fragspace.FragmentSpace.groupAndClassifyFragments(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.graph.Vertex.setBuildingBlockType().
Referenced by denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeNoMatch(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromVertex().
testLinkFromEdge()
void denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge () throws Exception
Definition at line 325 of file GraphLinkFinderTest.java.
References denoptim.fragspace.GraphLinkFinderTest.APCB, denoptim.fragspace.GraphLinkFinderTest.APCC, denoptim.fragspace.GraphLinkFinderTest.ensureConsistencyWithExpectations(), denoptim.fragspace.GraphLinkFinder.getAllAlternativesFound(), denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), and denoptim.fragspace.GraphLinkFinderTest.prepare().
testLinkFromEdgeNoMatch()
void denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeNoMatch () throws Exception
Definition at line 396 of file GraphLinkFinderTest.java.
References denoptim.fragspace.GraphLinkFinderTest.ensureConsistencyWithExpectations(), denoptim.fragspace.GraphLinkFinder.getAllAlternativesFound(), denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), and denoptim.fragspace.GraphLinkFinderTest.prepare().
testLinkFromEdgeOneMatch()
void denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch () throws Exception
Definition at line 371 of file GraphLinkFinderTest.java.
References denoptim.fragspace.GraphLinkFinderTest.APCE, denoptim.fragspace.GraphLinkFinderTest.ensureConsistencyWithExpectations(), denoptim.fragspace.GraphLinkFinder.getAllAlternativesFound(), denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), and denoptim.fragspace.GraphLinkFinderTest.prepare().
testLinkFromVertex()
void denoptim.fragspace.GraphLinkFinderTest.testLinkFromVertex () throws Exception
Definition at line 289 of file GraphLinkFinderTest.java.
References denoptim.fragspace.GraphLinkFinder.getAllAlternativesFound(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), and denoptim.fragspace.GraphLinkFinderTest.prepare().
Member Data Documentation
APCA
APClass denoptim.fragspace.GraphLinkFinderTest.APCA static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare().
APCB
APClass denoptim.fragspace.GraphLinkFinderTest.APCB static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge().
APCC
APClass denoptim.fragspace.GraphLinkFinderTest.APCC static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge().
APCD
APClass denoptim.fragspace.GraphLinkFinderTest.APCD static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare().
APCE
APClass denoptim.fragspace.GraphLinkFinderTest.APCE static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch().
APCF
APClass denoptim.fragspace.GraphLinkFinderTest.APCF static private
Definition at line 54 of file GraphLinkFinderTest.java.
Referenced by denoptim.fragspace.GraphLinkFinderTest.prepare().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragspace/GraphLinkFinderTest.java