DENOPTIM: denoptim.json.DENOPTIMgsonTest Class Reference
denoptim.json.DENOPTIMgsonTest Class Reference
Unit test for DENOPTIMgson.
Public Member Functions
void testIAtomContainerToJSONAndBack () throws Exception
void testTemplateSerialization () throws Exception
void testMolecularFragmentSerialization () throws Exception
Private Member Functions
boolean areCloseEnough (double a, double b)
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Detailed Description
Unit test for DENOPTIMgson.
Author
Marco Foscato
Definition at line 54 of file DENOPTIMgsonTest.java.
Member Function Documentation
areCloseEnough()
boolean denoptim.json.DENOPTIMgsonTest.areCloseEnough (double a, double b) private
Definition at line 261 of file DENOPTIMgsonTest.java.
Referenced by denoptim.json.DENOPTIMgsonTest.testIAtomContainerToJSONAndBack(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), and denoptim.json.DENOPTIMgsonTest.testTemplateSerialization().
testIAtomContainerToJSONAndBack()
void denoptim.json.DENOPTIMgsonTest.testIAtomContainerToJSONAndBack () throws Exception
Definition at line 61 of file DENOPTIMgsonTest.java.
References denoptim.json.DENOPTIMgsonTest.areCloseEnough(), denoptim.json.DENOPTIMgsonTest.builder, denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.json.DENOPTIMgson.getReader(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), and denoptim.json.DENOPTIMgson.getWriter().
testMolecularFragmentSerialization()
void denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization () throws Exception
Definition at line 185 of file DENOPTIMgsonTest.java.
References denoptim.json.DENOPTIMgsonTest.areCloseEnough(), denoptim.graph.Vertex.BBType.CAP, denoptim.utils.MutationType.CHANGEBRANCH, denoptim.utils.MutationType.CHANGELINK, denoptim.graph.Vertex.fromJson(), denoptim.graph.Fragment.getAPCountOnAtom(), denoptim.graph.Fragment.getAttachmentPoints(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.graph.Vertex.getIAtomContainer(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.json.DENOPTIMgson.getReader(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.Vertex.getVertexId(), denoptim.json.DENOPTIMgson.getWriter(), denoptim.graph.Vertex.isRCV, denoptim.graph.FragmentTest.makeFragment(), denoptim.graph.Vertex.removeMutationType(), denoptim.graph.Vertex.setBuildingBlockId(), and denoptim.graph.Vertex.setBuildingBlockType().
testTemplateSerialization()
void denoptim.json.DENOPTIMgsonTest.testTemplateSerialization () throws Exception
Definition at line 117 of file DENOPTIMgsonTest.java.
References denoptim.json.DENOPTIMgsonTest.areCloseEnough(), denoptim.graph.Vertex.BBType.CAP, denoptim.utils.MutationType.CHANGEBRANCH, denoptim.utils.MutationType.CHANGELINK, denoptim.graph.Vertex.fromJson(), denoptim.graph.Template.getAttachmentPoints(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Template.getIAtomContainer(), denoptim.graph.Vertex.getIAtomContainer(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.utils.MoleculeUtils.getPoint3d(), denoptim.json.DENOPTIMgson.getReader(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.TemplateTest.getTestAmideTemplate(), denoptim.graph.Vertex.getVertexId(), denoptim.json.DENOPTIMgson.getWriter(), denoptim.graph.Vertex.isRCV, denoptim.graph.Vertex.removeMutationType(), denoptim.graph.Vertex.setBuildingBlockId(), and denoptim.graph.Vertex.setBuildingBlockType().
Member Data Documentation
builder
IChemObjectBuilder denoptim.json.DENOPTIMgsonTest.builder = SilentChemObjectBuilder.getInstance() private
Definition at line 56 of file DENOPTIMgsonTest.java.
Referenced by denoptim.json.DENOPTIMgsonTest.testIAtomContainerToJSONAndBack().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/json/DENOPTIMgsonTest.java