DENOPTIM: denoptim.fragmenter.ConformerExtractorTaskTest Class Reference
denoptim.fragmenter.ConformerExtractorTaskTest Class Reference
Unit test for fragmenter's tools.
Public Member Functions
void testExtractClusterableFragments () throws Exception
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Detailed Description
Unit test for fragmenter's tools.
Definition at line 27 of file ConformerExtractorTaskTest.java.
Member Function Documentation
testExtractClusterableFragments()
void denoptim.fragmenter.ConformerExtractorTaskTest.testExtractClusterableFragments () throws Exception
Definition at line 38 of file ConformerExtractorTaskTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.atoms(), denoptim.fragmenter.ConformerExtractorTaskTest.builder, denoptim.graph.Fragment.clone(), denoptim.fragmenter.ConformerExtractorTask.extractClusterableFragments(), denoptim.graph.Fragment.getAttachmentPoints(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.constants.DENOPTIMConstants.ISOMORPHICFAMILYID, denoptim.graph.APClass.make(), denoptim.graph.Vertex.setProperty(), and denoptim.graph.Vertex.BBType.UNDEFINED.
Member Data Documentation
builder
IChemObjectBuilder denoptim.fragmenter.ConformerExtractorTaskTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 33 of file ConformerExtractorTaskTest.java.
Referenced by denoptim.fragmenter.ConformerExtractorTaskTest.testExtractClusterableFragments().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragmenter/ConformerExtractorTaskTest.java