DENOPTIM: denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent Class Reference
denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent Class Reference
Public Member Functions
GraphSpinnerChangeEvent ()
void setEnabled (boolean var)
Enables/disable the listener.
void stateChanged (ChangeEvent event)
Private Attributes
boolean inEnabled = true
Detailed Description
Definition at line 1863 of file GUIGraphHandler.java.
Constructor & Destructor Documentation
GraphSpinnerChangeEvent()
denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.GraphSpinnerChangeEvent ()
Definition at line 1867 of file GUIGraphHandler.java.
Member Function Documentation
setEnabled()
void denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.setEnabled (boolean var)
Enables/disable the listener.
Parameters
var true to activate listener, false to disable.
Definition at line 1875 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), and denoptim.gui.GUIGraphHandler.protectEditedSystem().
stateChanged()
void denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.stateChanged (ChangeEvent event)
Definition at line 1881 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.graphNavigSpinner, denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.inEnabled, and denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer().
Member Data Documentation
inEnabled
boolean denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.inEnabled = true private
Definition at line 1865 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.stateChanged().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIGraphHandler.java