DENOPTIM: denoptim.programs.combinatorial.CEBLParameters Class Reference
denoptim.programs.combinatorial.CEBLParameters Class Reference
Parameters controlling execution of the combinatorial algorithm for exploration of a fragment space by layer (CEBL).
Public Member Functions
CEBLParameters ()
Constructor.
ArrayList< DGraph > getRootGraphs ()
String getUIDFileName ()
boolean submitFitnessTask ()
String getDBRoot ()
void setDBRoot (String pathname)
int getNumberOfCPU ()
long getMaxWait ()
long getWaitStep ()
int getMaxLevel ()
boolean useGivenRoots ()
int getCheckPointStep ()
String getCheckPointName ()
CheckPoint getCheckPoint ()
boolean restartFromCheckPoint ()
boolean prepareFilesForTests ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Private Member Functions
void createWorkingDirectory ()
Private Attributes
String rootGraphsFile = null
File with user defined list of root graphs.
boolean useGivenRoots = false
Flag declaring that generation of graphs will use a given list of graphs as starting points for the exploration.
ArrayList< DGraph > rootGraphs
User defined list of root graphs.
String uidFile = "UID.txt"
Unique identifier file.
boolean runFitnessTask = false
Flag: optionally perform an evaluation of the fitness/descriptors on each accepted graph.
String dbRootDir = "."
Folder containing DENOPTIMGraphs sorted by level and reported as Strings.
int numCPU = 1
Number of processors.
long maxWait = 600000L
Maximum wait for completion of a level (millisec)
long waitStep = 5000L
Time step between each check for completion of a level (millisec)
int maxLevel = 2
Maximum level accepted: number of frag-frag bond from the origin (i.e., the scaffolds)
int chkptStep = 100
Number of combinations between every check out of the current position into a checkpoint file.
CheckPoint chkpt = null
Checkpoint for restarting an interrupted FSE run.
String chkptFile = null
Name of checkpoint file for restarting an interrupted FSE run.
boolean chkptRestart = false
Flag defining a restart from checkpoint file.
boolean prepareChkAndSerForTests = false
Flag requiring generation of the checkpoint files for the testing suite.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Detailed Description
Parameters controlling execution of the combinatorial algorithm for exploration of a fragment space by layer (CEBL).
Author
Marco Foscato
Definition at line 48 of file CEBLParameters.java.
Constructor & Destructor Documentation
CEBLParameters()
denoptim.programs.combinatorial.CEBLParameters.CEBLParameters ()
Constructor.
Definition at line 138 of file CEBLParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.CEBL_PARAMS.
Member Function Documentation
checkParameters()
void denoptim.programs.combinatorial.CEBLParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 363 of file CEBLParameters.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.files.FileUtils.checkExists(), denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.combinatorial.CEBLParameters.chkptFile, denoptim.programs.combinatorial.CEBLParameters.chkptStep, denoptim.programs.combinatorial.CEBLParameters.dbRootDir, denoptim.programs.RunTimeParameters.ParametersType.FIT_PARAMS, denoptim.programs.combinatorial.CEBLParameters.maxLevel, denoptim.programs.combinatorial.CEBLParameters.numCPU, denoptim.programs.RunTimeParameters.otherParameters, denoptim.programs.combinatorial.CEBLParameters.rootGraphsFile, denoptim.programs.combinatorial.CEBLParameters.runFitnessTask, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.combinatorial.FragSpaceExplorer.runProgram().
createWorkingDirectory()
void denoptim.programs.combinatorial.CEBLParameters.createWorkingDirectory () private
Definition at line 478 of file CEBLParameters.java.
References denoptim.files.FileUtils.addToRecentFiles(), denoptim.files.FileUtils.createDirectory(), denoptim.programs.combinatorial.CEBLParameters.dbRootDir, denoptim.files.FileFormat.FSE_RUN, denoptim.programs.RunTimeParameters.logFile, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.combinatorial.CEBLParameters.processParameters().
getCheckPoint()
CheckPoint denoptim.programs.combinatorial.CEBLParameters.getCheckPoint ()
Definition at line 229 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.chkpt.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel(), denoptim.combinatorial.CombinatorialExplorerByLayer.makeCheckPoint(), and denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getCheckPointName()
String denoptim.programs.combinatorial.CEBLParameters.getCheckPointName ()
Definition at line 222 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.chkptFile.
getCheckPointStep()
int denoptim.programs.combinatorial.CEBLParameters.getCheckPointStep ()
Definition at line 215 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.chkptStep.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel().
getDBRoot()
String denoptim.programs.combinatorial.CEBLParameters.getDBRoot ()
Definition at line 166 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.dbRootDir.
Referenced by denoptim.combinatorial.CEBLUtils.getNameOfStorageDir(), denoptim.combinatorial.CEBLUtils.getNameOfStorageFile(), and denoptim.combinatorial.CEBLUtils.getNameOfStorageIndexFile().
getMaxLevel()
int denoptim.programs.combinatorial.CEBLParameters.getMaxLevel ()
Definition at line 201 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.maxLevel.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getMaxWait()
long denoptim.programs.combinatorial.CEBLParameters.getMaxWait ()
Definition at line 187 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.maxWait.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
getNumberOfCPU()
int denoptim.programs.combinatorial.CEBLParameters.getNumberOfCPU ()
Definition at line 180 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.numCPU.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.CombinatorialExplorerByLayer().
getPrintedList()
String denoptim.programs.combinatorial.CEBLParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 506 of file CEBLParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getRootGraphs()
ArrayList< DGraph > denoptim.programs.combinatorial.CEBLParameters.getRootGraphs ()
Definition at line 145 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.rootGraphs.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel().
getUIDFileName()
String denoptim.programs.combinatorial.CEBLParameters.getUIDFileName ()
Definition at line 152 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.uidFile.
Referenced by denoptim.combinatorial.GraphBuildingTask.sendToFitnessProvider().
getWaitStep()
long denoptim.programs.combinatorial.CEBLParameters.getWaitStep ()
Definition at line 194 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.waitStep.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.run().
interpretKeyword()
void denoptim.programs.combinatorial.CEBLParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 256 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.chkptFile, denoptim.programs.combinatorial.CEBLParameters.chkptRestart, denoptim.programs.combinatorial.CEBLParameters.chkptStep, denoptim.programs.combinatorial.CEBLParameters.dbRootDir, denoptim.programs.combinatorial.CEBLParameters.maxLevel, denoptim.programs.combinatorial.CEBLParameters.maxWait, denoptim.programs.combinatorial.CEBLParameters.numCPU, denoptim.programs.combinatorial.CEBLParameters.prepareChkAndSerForTests, denoptim.programs.combinatorial.CEBLParameters.rootGraphsFile, denoptim.programs.combinatorial.CEBLParameters.uidFile, denoptim.programs.combinatorial.CEBLParameters.useGivenRoots, denoptim.programs.RunTimeParameters.verbosity, denoptim.programs.combinatorial.CEBLParameters.waitStep, and denoptim.programs.RunTimeParameters.workDir.
prepareFilesForTests()
boolean denoptim.programs.combinatorial.CEBLParameters.prepareFilesForTests ()
Definition at line 243 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.prepareChkAndSerForTests.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel().
processParameters()
void denoptim.programs.combinatorial.CEBLParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 436 of file CEBLParameters.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.combinatorial.CEBLParameters.chkpt, denoptim.programs.combinatorial.CEBLParameters.chkptFile, denoptim.programs.combinatorial.CEBLParameters.chkptRestart, denoptim.programs.combinatorial.CEBLParameters.createWorkingDirectory(), denoptim.combinatorial.CEBLUtils.deserializeCheckpoint(), denoptim.constants.DENOPTIMConstants.EOL, denoptim.programs.RunTimeParameters.isMaster, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.RunTimeParameters.processOtherParameters(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.programs.combinatorial.CEBLParameters.rootGraphs, denoptim.programs.combinatorial.CEBLParameters.rootGraphsFile, denoptim.programs.combinatorial.CEBLParameters.useGivenRoots, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.combinatorial.FragSpaceExplorer.runProgram().
restartFromCheckPoint()
boolean denoptim.programs.combinatorial.CEBLParameters.restartFromCheckPoint ()
Definition at line 236 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.chkptRestart.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.CombinatorialExplorerByLayer().
setDBRoot()
void denoptim.programs.combinatorial.CEBLParameters.setDBRoot (String pathname)
Definition at line 173 of file CEBLParameters.java.
submitFitnessTask()
boolean denoptim.programs.combinatorial.CEBLParameters.submitFitnessTask ()
Definition at line 159 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.runFitnessTask.
Referenced by denoptim.combinatorial.GraphBuildingTask.call().
useGivenRoots()
boolean denoptim.programs.combinatorial.CEBLParameters.useGivenRoots ()
Definition at line 208 of file CEBLParameters.java.
References denoptim.programs.combinatorial.CEBLParameters.useGivenRoots.
Member Data Documentation
chkpt
CheckPoint denoptim.programs.combinatorial.CEBLParameters.chkpt = null private
Checkpoint for restarting an interrupted FSE run.
Definition at line 113 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.getCheckPoint(), and denoptim.programs.combinatorial.CEBLParameters.processParameters().
chkptFile
String denoptim.programs.combinatorial.CEBLParameters.chkptFile = null private
Name of checkpoint file for restarting an interrupted FSE run.
Definition at line 118 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.getCheckPointName(), denoptim.programs.combinatorial.CEBLParameters.interpretKeyword(), and denoptim.programs.combinatorial.CEBLParameters.processParameters().
chkptRestart
boolean denoptim.programs.combinatorial.CEBLParameters.chkptRestart = false private
Flag defining a restart from checkpoint file.
Definition at line 123 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.interpretKeyword(), denoptim.programs.combinatorial.CEBLParameters.processParameters(), and denoptim.programs.combinatorial.CEBLParameters.restartFromCheckPoint().
chkptStep
int denoptim.programs.combinatorial.CEBLParameters.chkptStep = 100 private
Number of combinations between every check out of the current position into a checkpoint file.
Definition at line 108 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.getCheckPointStep(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
dbRootDir
String denoptim.programs.combinatorial.CEBLParameters.dbRootDir = "." private
Folder containing DENOPTIMGraphs sorted by level and reported as Strings.
Definition at line 81 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.createWorkingDirectory(), denoptim.programs.combinatorial.CEBLParameters.getDBRoot(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
maxLevel
int denoptim.programs.combinatorial.CEBLParameters.maxLevel = 2 private
Maximum level accepted: number of frag-frag bond from the origin (i.e., the scaffolds)
Definition at line 102 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.getMaxLevel(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
maxWait
long denoptim.programs.combinatorial.CEBLParameters.maxWait = 600000L private
Maximum wait for completion of a level (millisec)
Definition at line 91 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.getMaxWait(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
numCPU
int denoptim.programs.combinatorial.CEBLParameters.numCPU = 1 private
Number of processors.
Definition at line 86 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.getNumberOfCPU(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
prepareChkAndSerForTests
boolean denoptim.programs.combinatorial.CEBLParameters.prepareChkAndSerForTests = false private
Flag requiring generation of the checkpoint files for the testing suite.
When true allows to stop the asyncronous, parallelized exploration of a fragment space so that checkpoint files and serialized graphs can be generated and used to prepare the test suite.
Definition at line 131 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.interpretKeyword(), and denoptim.programs.combinatorial.CEBLParameters.prepareFilesForTests().
rootGraphs
ArrayList<DGraph> denoptim.programs.combinatorial.CEBLParameters.rootGraphs private
User defined list of root graphs.
Definition at line 64 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.getRootGraphs(), and denoptim.programs.combinatorial.CEBLParameters.processParameters().
rootGraphsFile
String denoptim.programs.combinatorial.CEBLParameters.rootGraphsFile = null private
File with user defined list of root graphs.
Definition at line 53 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.interpretKeyword(), and denoptim.programs.combinatorial.CEBLParameters.processParameters().
runFitnessTask
boolean denoptim.programs.combinatorial.CEBLParameters.runFitnessTask = false private
Flag: optionally perform an evaluation of the fitness/descriptors on each accepted graph.
Definition at line 75 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.checkParameters(), and denoptim.programs.combinatorial.CEBLParameters.submitFitnessTask().
uidFile
String denoptim.programs.combinatorial.CEBLParameters.uidFile = "UID.txt" private
Unique identifier file.
Definition at line 69 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.getUIDFileName(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
useGivenRoots
boolean denoptim.programs.combinatorial.CEBLParameters.useGivenRoots = false private
Flag declaring that generation of graphs will use a given list of graphs as starting points for the exploration.
Definition at line 59 of file CEBLParameters.java.
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel(), denoptim.programs.combinatorial.CEBLParameters.interpretKeyword(), denoptim.programs.combinatorial.CEBLParameters.processParameters(), and denoptim.programs.combinatorial.CEBLParameters.useGivenRoots().
waitStep
long denoptim.programs.combinatorial.CEBLParameters.waitStep = 5000L private
Time step between each check for completion of a level (millisec)
Definition at line 96 of file CEBLParameters.java.
Referenced by denoptim.programs.combinatorial.CEBLParameters.getWaitStep(), and denoptim.programs.combinatorial.CEBLParameters.interpretKeyword().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/combinatorial/CEBLParameters.java