DENOPTIM: denoptim.graph.Candidate Class Reference
denoptim.graph.Candidate Class Reference
A candidate is the combination of a denoptim graph with molecular representation and may include also fitness/error, and possibly other stuff.
Public Member Functions
Candidate ()
Candidate (DGraph graph)
Candidate (String name, DGraph graph)
Candidate (String name, DGraph graph, double fitness, String uid, String smiles)
Candidate (IAtomContainer iac, boolean useFragSpace) throws DENOPTIMException
Builds a candidate from the SDF representation of an atom container.
Candidate (IAtomContainer iac, boolean useFragSpace, boolean allowNoUID) throws DENOPTIMException
Builds a candidate from the SDF representation of an atom container.
void setChemicalRepresentation (IAtomContainer iac)
Just place the argument in the IAtomContainer field of this object.
IAtomContainer getChemicalRepresentation ()
Returns the atom container representing this candidate.
IAtomContainer getFitnessProviderOutputRepresentation () throws DENOPTIMException
Returns an atom container representing this item in a way that is compatible for writing this item to an SDF file.
void setComments (String str)
String getComments ()
void setSDFFile (String molFile)
void setImageFile (String imgFile)
void setGraph (DGraph graph)
void setUID (String uid)
void setSmiles (String smiles)
void setFitness (double fitness)
void setError (String error)
void setName (String name)
String getName ()
String getError ()
String getUID ()
String getSmiles ()
String getSDFFile ()
String getImageFile ()
DGraph getGraph ()
double getFitness ()
boolean hasFitness ()
void setGeneration (int genId)
int getGeneration ()
The generation this candidate belong to is that in which it was generated.
void setLevel (int lev)
Sets level that generated this graph in a fragment space exploration experiment.
int getLevel ()
Returns the level that generated this graph in a fragment space exploration experiment.
int compareTo (Candidate other)
String toString ()
void cleanup ()
Clear the graph describing this candidate.
Candidate clone ()
Static Public Member Functions
static Candidate fromAtomContainerNoGraph (IAtomContainer iac, boolean allowNoUID) throws DENOPTIMException
Wraps an atom container as a candidate even if a graph is not available.
Private Member Functions
Candidate (String name, DGraph graph, String uid, String smiles, String molFile, String imgFile, String comment, int generationId, int level)
Private Attributes
String uid
Unique identifier of this candidate.
DGraph graph
Graph representation.
IAtomContainer iac
Chemical object representation.
String smiles
SMILES representation.
double fitness
fitness value
String sdfFile
Pathname to SDF file.
String imgFile
Pathname to an image (i.e., PNG file)
String comment
Any comments.
String error
Error that prevented calculation of the fitness.
boolean hasFitness
Flag signaling the presence of a fitness value associated.
int generationId = -1
ID of the generation at which this candidate was generated.
String name
Name of this candidate (not guaranteed to be unique)
int level
Level that generated this graph in fragment space exploration.
Detailed Description
A candidate is the combination of a denoptim graph with molecular representation and may include also fitness/error, and possibly other stuff.
Definition at line 39 of file Candidate.java.
Constructor & Destructor Documentation
Candidate() [1/7]
denoptim.graph.Candidate.Candidate ()
Definition at line 110 of file Candidate.java.
References denoptim.graph.Candidate.hasFitness, denoptim.graph.Candidate.name, denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
Referenced by denoptim.graph.Candidate.clone(), and denoptim.graph.Candidate.fromAtomContainerNoGraph().
Candidate() [2/7]
denoptim.graph.Candidate.Candidate (DGraph graph)
Definition at line 120 of file Candidate.java.
References denoptim.graph.Candidate.graph, denoptim.graph.Candidate.hasFitness, denoptim.graph.DGraph.setCandidateOwner(), denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
Candidate() [3/7]
denoptim.graph.Candidate.Candidate (String name, DGraph graph)
Definition at line 132 of file Candidate.java.
References denoptim.graph.Candidate.graph, denoptim.graph.Candidate.hasFitness, denoptim.graph.Candidate.name, denoptim.graph.DGraph.setCandidateOwner(), denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
Candidate() [4/7]
denoptim.graph.Candidate.Candidate (String name, DGraph graph, double fitness, String uid, String smiles)
Definition at line 145 of file Candidate.java.
References denoptim.graph.Candidate.fitness, denoptim.graph.Candidate.graph, denoptim.graph.Candidate.hasFitness, denoptim.graph.Candidate.name, denoptim.graph.DGraph.setCandidateOwner(), denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
Candidate() [5/7]
denoptim.graph.Candidate.Candidate (String name, DGraph graph, String uid, String smiles, String molFile, String imgFile, String comment, int generationId, int level) private
Definition at line 160 of file Candidate.java.
References denoptim.graph.Candidate.comment, denoptim.graph.Candidate.generationId, denoptim.graph.Candidate.graph, denoptim.graph.Candidate.imgFile, denoptim.graph.Candidate.level, denoptim.graph.Candidate.name, denoptim.graph.DGraph.setCandidateOwner(), denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
Candidate() [6/7]
denoptim.graph.Candidate.Candidate (IAtomContainer iac, boolean useFragSpace) throws DENOPTIMException
Builds a candidate from the SDF representation of an atom container.
This method does interpret the properties of the atom container object and used them to define the various field values that define this candidate.
Parameters
iac the container to read and interpret.
useFragSpace set true to enable usage of the building block space when reading in the string-encoder graph representation of this object. Use false when a building block space is undefined and the graph representation can only be built assuming that there are as many APs as used in this graph, while other information on the graph building blocks cannot be inferred.
Exceptions
DENOPTIMException
Definition at line 193 of file Candidate.java.
References denoptim.graph.Candidate.iac.
Candidate() [7/7]
denoptim.graph.Candidate.Candidate (IAtomContainer iac, boolean useFragSpace, boolean allowNoUID) throws DENOPTIMException
Builds a candidate from the SDF representation of an atom container.
This method does interpret the properties of the atom container object and used them to define the various field values that define this candidate.
Parameters
iac the container to read and interpret.
useFragSpace set true to enable usage of the building block space when reading in the string-encoder graph representation of this object. Use false when a building block space is undefined and the graph representation can only be built assuming that there are as many APs as used in this graph, while other information on the graph building blocks cannot be inferred.
allowNoUID use true to allow creation on a candidate that has no unique identifier.
Exceptions
DENOPTIMException
Definition at line 217 of file Candidate.java.
References denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.constants.DENOPTIMConstants.GRAPHLEVELTAG, denoptim.graph.Candidate.iac, denoptim.utils.MoleculeUtils.makeSameAs(), denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.io.DenoptimIO.readGraphFromSDFileIAC(), denoptim.graph.DGraph.setCandidateOwner(), denoptim.constants.DENOPTIMConstants.SMILESTAG, and denoptim.constants.DENOPTIMConstants.UNIQUEIDTAG.
Member Function Documentation
cleanup()
void denoptim.graph.Candidate.cleanup ()
Clear the graph describing this candidate.
Definition at line 670 of file Candidate.java.
References denoptim.graph.DGraph.cleanup(), and denoptim.graph.Candidate.graph.
clone()
Candidate denoptim.graph.Candidate.clone ()
Definition at line 678 of file Candidate.java.
References denoptim.graph.Candidate.Candidate(), denoptim.graph.DGraph.clone(), denoptim.graph.Candidate.comment, denoptim.graph.Candidate.error, denoptim.graph.Candidate.fitness, denoptim.graph.Candidate.generationId, denoptim.graph.Candidate.graph, denoptim.graph.Candidate.hasFitness, denoptim.graph.Candidate.imgFile, denoptim.graph.Candidate.level, denoptim.utils.MoleculeUtils.makeSameAs(), denoptim.graph.Candidate.name, denoptim.graph.Candidate.sdfFile, denoptim.graph.Candidate.setChemicalRepresentation(), denoptim.graph.Candidate.setError(), denoptim.graph.Candidate.setFitness(), denoptim.graph.Candidate.smiles, and denoptim.graph.Candidate.uid.
compareTo()
int denoptim.graph.Candidate.compareTo (Candidate other)
Returns
a negative integer, 0, or a positive integer depending on whether this object is less than, equal to, or greater than the other object given as argument.
Definition at line 621 of file Candidate.java.
References denoptim.graph.Candidate.fitness, denoptim.graph.Candidate.graph, denoptim.graph.DGraph.graphId, and denoptim.graph.Candidate.hasFitness.
fromAtomContainerNoGraph()
static Candidate denoptim.graph.Candidate.fromAtomContainerNoGraph (IAtomContainer iac, boolean allowNoUID) throws DENOPTIMException static
Wraps an atom container as a candidate even if a graph is not available.
Essentially, this method produces a candidate that has as much info as available in the atom container, but ignores the lack of a valid graph definition.
Parameters
iac the atom container to be wrapped.
allowNoUID use true to allow creation on a candidate that has no unique identifier.
Returns
a new candidate with no graph but with a molecular representation.
Exceptions
DENOPTIMException if the UID is required but not found.
Definition at line 301 of file Candidate.java.
References denoptim.graph.Candidate.Candidate(), denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.constants.DENOPTIMConstants.GRAPHLEVELTAG, denoptim.graph.Candidate.iac, denoptim.utils.MoleculeUtils.makeSameAs(), denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.constants.DENOPTIMConstants.SMILESTAG, and denoptim.constants.DENOPTIMConstants.UNIQUEIDTAG.
Referenced by denoptim.gui.MoleculeViewPanel.loadChemicalStructureFromFile().
getChemicalRepresentation()
IAtomContainer denoptim.graph.Candidate.getChemicalRepresentation ()
Returns the atom container representing this candidate.
Returns
the atom container.
Definition at line 389 of file Candidate.java.
References denoptim.graph.Candidate.iac.
Referenced by denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), and denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
getComments()
String denoptim.graph.Candidate.getComments ()
Definition at line 438 of file Candidate.java.
References denoptim.graph.Candidate.comment.
Referenced by denoptim.gui.MoleculeViewPanel.fillDataTable().
getError()
String denoptim.graph.Candidate.getError ()
Definition at line 509 of file Candidate.java.
References denoptim.graph.Candidate.error.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), and denoptim.gui.MoleculeViewPanel.fillDataTable().
getFitness()
double denoptim.graph.Candidate.getFitness ()
Definition at line 551 of file Candidate.java.
References denoptim.graph.Candidate.fitness.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.gui.MoleculeViewPanel.fillDataTable(), denoptim.ga.Population.getMaxFitness(), denoptim.ga.Population.getMinFitness(), denoptim.ga.Population.getMinFitnessMember(), denoptim.ga.EAUtils.outputPopulationDetails(), and denoptim.ga.SelectionHelper.performRWS().
getFitnessProviderOutputRepresentation()
IAtomContainer denoptim.graph.Candidate.getFitnessProviderOutputRepresentation () throws DENOPTIMException
Returns an atom container representing this item in a way that is compatible for writing this item to an SDF file.
Returns
a decorated atom container.
Exceptions
DENOPTIMException when conversion of graph to json fails.
Definition at line 402 of file Candidate.java.
References denoptim.graph.Candidate.error, denoptim.graph.Candidate.fitness, denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.constants.DENOPTIMConstants.GCODETAG, denoptim.graph.DGraph.getGraphId(), denoptim.graph.DGraph.getLocalMsg(), denoptim.graph.Candidate.graph, denoptim.constants.DENOPTIMConstants.GRAPHJSONTAG, denoptim.constants.DENOPTIMConstants.GRAPHTAG, denoptim.graph.Candidate.hasFitness, denoptim.graph.Candidate.iac, denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.graph.Candidate.name, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.graph.Candidate.smiles, denoptim.constants.DENOPTIMConstants.SMILESTAG, denoptim.graph.DGraph.toJson(), denoptim.graph.DGraph.toString(), denoptim.graph.Candidate.uid, and denoptim.constants.DENOPTIMConstants.UNIQUEIDTAG.
getGeneration()
int denoptim.graph.Candidate.getGeneration ()
The generation this candidate belong to is that in which it was generated.
In asynchronous experiments, the generation at which a candidate is generated and that when it enters the population may be different.
Returns
the generation at which a candidate is generated.
Definition at line 578 of file Candidate.java.
References denoptim.graph.Candidate.generationId.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), and denoptim.gui.MoleculeViewPanel.fillDataTable().
getGraph()
DGraph denoptim.graph.Candidate.getGraph ()
Definition at line 544 of file Candidate.java.
References denoptim.graph.Candidate.graph.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.programs.fitnessevaluator.FitnessEvaluationTask.call(), denoptim.task.FitnessTask.FitnessTask(), denoptim.ga.Population.getXoverPartners(), denoptim.ga.EvolutionaryAlgorithm.makeOffspringB(), denoptim.ga.EAUtils.outputPopulationDetails(), denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_Free(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FreeBackwards(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
getImageFile()
String denoptim.graph.Candidate.getImageFile ()
Definition at line 537 of file Candidate.java.
References denoptim.graph.Candidate.imgFile.
Referenced by denoptim.ga.EAUtils.outputFinalResults().
getLevel()
int denoptim.graph.Candidate.getLevel ()
Returns the level that generated this graph in a fragment space exploration experiment.
Returns
the level that generated this graph in a fragment space exploration experiment.
Definition at line 603 of file Candidate.java.
References denoptim.graph.Candidate.level.
getName()
String denoptim.graph.Candidate.getName ()
Definition at line 502 of file Candidate.java.
References denoptim.graph.Candidate.name.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.ga.PopulationTest.compareSizeOfSites(), denoptim.gui.MoleculeViewPanel.fillDataTable(), denoptim.ga.Population.getXoverPartners(), denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), denoptim.ga.EAUtils.outputFinalResults(), denoptim.ga.EAUtils.outputPopulationDetails(), denoptim.ga.EAUtils.readCandidateFromFile(), denoptim.task.FitnessTask.runExternalFitness(), denoptim.task.FitnessTask.runInternalFitness(), and denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
getSDFFile()
String denoptim.graph.Candidate.getSDFFile ()
Definition at line 530 of file Candidate.java.
References denoptim.graph.Candidate.sdfFile.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.outputFinalResults(), denoptim.ga.EAUtils.outputPopulationDetails(), and denoptim.gui.MoleculeViewPanel.showPopup().
getSmiles()
String denoptim.graph.Candidate.getSmiles ()
Definition at line 523 of file Candidate.java.
References denoptim.graph.Candidate.smiles.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), and denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask().
getUID()
String denoptim.graph.Candidate.getUID ()
Definition at line 516 of file Candidate.java.
References denoptim.graph.Candidate.uid.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), denoptim.gui.MoleculeViewPanel.fillDataTable(), denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), denoptim.ga.EAUtils.outputPopulationDetails(), and denoptim.ga.EAUtils.selectBasedOnFitness().
hasFitness()
boolean denoptim.graph.Candidate.hasFitness ()
Definition at line 558 of file Candidate.java.
References denoptim.graph.Candidate.hasFitness.
setChemicalRepresentation()
void denoptim.graph.Candidate.setChemicalRepresentation (IAtomContainer iac)
Just place the argument in the IAtomContainer field of this object.
We do not read and interpret the input argument as done in Candidate(IAtomContainer) or Candidate(IAtomContainer, boolean).
Parameters
iac new value of IAtomContainer field
Definition at line 378 of file Candidate.java.
References denoptim.graph.Candidate.iac.
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.graph.Candidate.clone(), denoptim.ga.EAUtils.readCandidateFromFile(), denoptim.task.FitnessTask.runExternalFitness(), and denoptim.task.FitnessTask.runFitnessProvider().
setComments()
void denoptim.graph.Candidate.setComments (String str)
Definition at line 431 of file Candidate.java.
setError()
void denoptim.graph.Candidate.setError (String error)
Definition at line 488 of file Candidate.java.
References denoptim.graph.Candidate.error.
Referenced by denoptim.graph.Candidate.clone(), denoptim.task.FitnessTask.runExternalFitness(), and denoptim.task.FitnessTask.runInternalFitness().
setFitness()
void denoptim.graph.Candidate.setFitness (double fitness)
Definition at line 480 of file Candidate.java.
References denoptim.graph.Candidate.fitness.
Referenced by denoptim.graph.Candidate.clone(), denoptim.task.FitnessTask.runExternalFitness(), denoptim.task.FitnessTask.runInternalFitness(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), denoptim.ga.PopulationTest.testGetMinMax(), denoptim.ga.PopulationTest.testIsInPercentile(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
setGeneration()
void denoptim.graph.Candidate.setGeneration (int genId)
Definition at line 565 of file Candidate.java.
References denoptim.graph.Candidate.generationId.
Referenced by denoptim.ga.EvolutionaryAlgorithm.evolvePopulation(), and denoptim.io.DenoptimIO.readCandidates().
setGraph()
void denoptim.graph.Candidate.setGraph (DGraph graph)
Definition at line 459 of file Candidate.java.
References denoptim.graph.Candidate.graph.
Referenced by denoptim.combinatorial.GraphBuildingTask.call().
setImageFile()
void denoptim.graph.Candidate.setImageFile (String imgFile)
Definition at line 452 of file Candidate.java.
References denoptim.graph.Candidate.imgFile.
Referenced by denoptim.task.FitnessTask.runFitnessProvider().
setLevel()
void denoptim.graph.Candidate.setLevel (int lev)
Sets level that generated this graph in a fragment space exploration experiment.
Parameters
lev the level index
Definition at line 590 of file Candidate.java.
References denoptim.graph.Candidate.level.
setName()
void denoptim.graph.Candidate.setName (String name)
Definition at line 495 of file Candidate.java.
References denoptim.graph.Candidate.name.
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), denoptim.ga.EAUtils.readCandidateFromFile(), and denoptim.combinatorial.GraphBuildingTask.sendToFitnessProvider().
setSDFFile()
void denoptim.graph.Candidate.setSDFFile (String molFile)
Definition at line 445 of file Candidate.java.
Referenced by denoptim.ga.EAUtils.outputFinalResults(), denoptim.io.DenoptimIO.readCandidates(), denoptim.task.FitnessTask.runFitnessProvider(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
setSmiles()
void denoptim.graph.Candidate.setSmiles (String smiles)
Definition at line 473 of file Candidate.java.
References denoptim.graph.Candidate.smiles.
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), denoptim.ga.EAUtils.readCandidateFromFile(), and denoptim.combinatorial.GraphBuildingTask.sendToFitnessProvider().
setUID()
void denoptim.graph.Candidate.setUID (String uid)
Definition at line 466 of file Candidate.java.
References denoptim.graph.Candidate.uid.
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.OffspringEvaluationTask.OffspringEvaluationTask(), denoptim.ga.EAUtils.readCandidateFromFile(), denoptim.task.FitnessTask.runExternalFitness(), denoptim.combinatorial.GraphBuildingTask.sendToFitnessProvider(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
toString()
String denoptim.graph.Candidate.toString ()
Definition at line 650 of file Candidate.java.
References denoptim.graph.Candidate.fitness, denoptim.graph.Candidate.name, denoptim.graph.Candidate.sdfFile, and denoptim.graph.Candidate.uid.
Member Data Documentation
comment
String denoptim.graph.Candidate.comment private
Any comments.
Definition at line 79 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), and denoptim.graph.Candidate.getComments().
error
String denoptim.graph.Candidate.error private
Error that prevented calculation of the fitness.
Definition at line 84 of file Candidate.java.
Referenced by denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getError(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), and denoptim.graph.Candidate.setError().
fitness
double denoptim.graph.Candidate.fitness private
fitness value
Definition at line 64 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.compareTo(), denoptim.graph.Candidate.getFitness(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.Candidate.setFitness(), and denoptim.graph.Candidate.toString().
generationId
int denoptim.graph.Candidate.generationId = -1 private
ID of the generation at which this candidate was generated.
This may not be the generation at which this candidate entered the population!
Definition at line 95 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getGeneration(), and denoptim.graph.Candidate.setGeneration().
graph
DGraph denoptim.graph.Candidate.graph private
Graph representation.
Definition at line 49 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.cleanup(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.compareTo(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.Candidate.getGraph(), and denoptim.graph.Candidate.setGraph().
hasFitness
boolean denoptim.graph.Candidate.hasFitness private
Flag signaling the presence of a fitness value associated.
Definition at line 89 of file Candidate.java.
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.compareTo(), denoptim.gui.MoleculeViewPanel.fillDataTable(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), and denoptim.graph.Candidate.hasFitness().
iac
IAtomContainer denoptim.graph.Candidate.iac private
Chemical object representation.
Definition at line 54 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.fromAtomContainerNoGraph(), denoptim.graph.Candidate.getChemicalRepresentation(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), and denoptim.graph.Candidate.setChemicalRepresentation().
imgFile
String denoptim.graph.Candidate.imgFile private
Pathname to an image (i.e., PNG file)
Definition at line 74 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getImageFile(), and denoptim.graph.Candidate.setImageFile().
level
int denoptim.graph.Candidate.level private
Level that generated this graph in fragment space exploration.
Definition at line 105 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getLevel(), and denoptim.graph.Candidate.setLevel().
name
String denoptim.graph.Candidate.name private
Name of this candidate (not guaranteed to be unique)
Definition at line 100 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.Candidate.getName(), denoptim.graph.Candidate.setName(), and denoptim.graph.Candidate.toString().
sdfFile
String denoptim.graph.Candidate.sdfFile private
Pathname to SDF file.
Definition at line 69 of file Candidate.java.
Referenced by denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getSDFFile(), and denoptim.graph.Candidate.toString().
smiles
String denoptim.graph.Candidate.smiles private
SMILES representation.
Definition at line 59 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.Candidate.getSmiles(), and denoptim.graph.Candidate.setSmiles().
uid
String denoptim.graph.Candidate.uid private
Unique identifier of this candidate.
Definition at line 44 of file Candidate.java.
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.graph.Candidate.clone(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.Candidate.getUID(), denoptim.graph.Candidate.setUID(), and denoptim.graph.Candidate.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/Candidate.java