DENOPTIM: denoptim.fragmenter.TopoTemplateProducer Class Reference
denoptim.fragmenter.TopoTemplateProducer Class Reference
Public Member Functions
TopoTemplateProducer (IAtomContainer originalIAC)
Constructor.
IAtomContainer getTemplateWithBufferShell (int bufferShellSize)
Produced a new IAtomContainer containing all the atoms needed to define the topology of the original graph plus all the atoms that are connected by the number of bonds fedined by the buffer shell size.
Package Attributes
Set< IAtom > topoCriticalAtoms = new HashSet<>()
topology-critical atoms
IAtomContainer originalIAC
The original IAtomContainer to produce a topology-critical template for.
boolean produceHDepleted = false
Flag recording whether we could only produce a H-depleted template.
Private Member Functions
void initialize ()
Detailed Description
Definition at line 20 of file TopoTemplateProducer.java.
Constructor & Destructor Documentation
TopoTemplateProducer()
denoptim.fragmenter.TopoTemplateProducer.TopoTemplateProducer (IAtomContainer originalIAC)
Constructor.
Parameters
originalIAC the original IAtomContainer to produce a topology-critical template for.
Definition at line 45 of file TopoTemplateProducer.java.
References denoptim.fragmenter.TopoTemplateProducer.initialize(), and denoptim.fragmenter.TopoTemplateProducer.originalIAC.
Member Function Documentation
getTemplateWithBufferShell()
IAtomContainer denoptim.fragmenter.TopoTemplateProducer.getTemplateWithBufferShell (int bufferShellSize)
Produced a new IAtomContainer containing all the atoms needed to define the topology of the original graph plus all the atoms that are connected by the number of bonds fedined by the buffer shell size.
Parameters
bufferShellSize the number of bonds to consider when defining the depth of the buffer shell around the topology-critical atoms.
Returns
a new IAtomContainer containing all the atoms needed to define the topology of the original graph plus all the atoms that are connected by the number of bonds fedined by the buffer shell size.
Definition at line 185 of file TopoTemplateProducer.java.
References denoptim.utils.MoleculeUtils.isElement(), denoptim.fragmenter.TopoTemplateProducer.originalIAC, and denoptim.fragmenter.TopoTemplateProducer.topoCriticalAtoms.
Referenced by denoptim.fragmenter.FragmenterTools.fragmentation().
initialize()
void denoptim.fragmenter.TopoTemplateProducer.initialize () private
Definition at line 53 of file TopoTemplateProducer.java.
References denoptim.constants.DENOPTIMConstants.ATMPROPAPS, denoptim.constants.DENOPTIMConstants.ATMPROPVERTEXID, denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.utils.MoleculeUtils.findShortestPath(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.fragmenter.TopoTemplateProducer.originalIAC, denoptim.fragmenter.TopoTemplateProducer.produceHDepleted, and denoptim.fragmenter.TopoTemplateProducer.topoCriticalAtoms.
Referenced by denoptim.fragmenter.TopoTemplateProducer.TopoTemplateProducer().
Member Data Documentation
originalIAC
IAtomContainer denoptim.fragmenter.TopoTemplateProducer.originalIAC package
The original IAtomContainer to produce a topology-critical template for.
Definition at line 31 of file TopoTemplateProducer.java.
Referenced by denoptim.fragmenter.TopoTemplateProducer.getTemplateWithBufferShell(), denoptim.fragmenter.TopoTemplateProducer.initialize(), and denoptim.fragmenter.TopoTemplateProducer.TopoTemplateProducer().
produceHDepleted
boolean denoptim.fragmenter.TopoTemplateProducer.produceHDepleted = false package
Flag recording whether we could only produce a H-depleted template.
Definition at line 36 of file TopoTemplateProducer.java.
Referenced by denoptim.fragmenter.TopoTemplateProducer.initialize().
topoCriticalAtoms
Set<IAtom> denoptim.fragmenter.TopoTemplateProducer.topoCriticalAtoms = new HashSet<>() package
topology-critical atoms
Definition at line 26 of file TopoTemplateProducer.java.
Referenced by denoptim.fragmenter.TopoTemplateProducer.getTemplateWithBufferShell(), and denoptim.fragmenter.TopoTemplateProducer.initialize().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragmenter/TopoTemplateProducer.java