DENOPTIM: denoptim.programs.fragmenter.FragmenterParameters Class Reference
denoptim.programs.fragmenter.FragmenterParameters Class Reference
Parameters controlling execution of the fragmenter.
Public Member Functions
FragmenterParameters ()
Constructor.
int getNumTasks ()
void setNumTasks (int numParallelTasks)
Sets the number of parallel tasks to run.
String getStructuresFile ()
void setStructuresFile (String structuresFile)
Sets the pathname of the file containing input structures.
void setFormulaeFile (String formulaeFile)
Sets the pathname of the file containing molecular formula with a format respecting Cambridge Structural Database format).
String getFormulaeFile ()
List< CuttingRule > getCuttingRules ()
void setCuttingRules (List< CuttingRule > cuttingRules)
Assigns the cutting rules loaded from the input.
void setCuttingRulesFilePathname (String pathname)
Assigns the pathname to the cutting rules file.
String getCuttingRulesFilePathname ()
LinkedHashMap< String, String > getFormulae ()
boolean doCheckFormula ()
void setCheckFormula (boolean checkFormula)
Sets the value of the flag controlling the execution of elemental analysis on the structures.
boolean doPreFilter ()
Set< String > getPreFiltrationSMARTS ()
boolean doFragmentation ()
boolean doRejectWeirdIsotopes ()
boolean doAddDuOnLinearity ()
Set< String > getRejectedElements ()
Map< String, Double > getRejectedFormulaLessThan ()
Set< Map< String, Double > > getRejectedFormulaMoreThan ()
Set< String > getRejectedAPClasses ()
Set< String[]> getRejectedAPClassCombinations ()
int getMaxFragHeavyAtomCount ()
int getMinFragHeavyAtomCount ()
Map< String, String > getFragRejectionSMARTS ()
Map< String, String > getFragRetentionSMARTS ()
void setRejectWeirdIsotopes (boolean doRejectWeirdIsotopes)
void setRejectedElements (Set< String > rejectedElements)
void setRejectedFormulaLessThan (Map< String, Double > formulaMax)
void setRejectedFormulaMoreThan (Set< Map< String, Double > > formulaCriteriaMoreThan)
void setRejectedAPClasses (Set< String > rejectedAPClasses)
void setRejectedAPClassCombinations (Set< String[]> rejectedAPClassCombinations)
void setMaxFragHeavyAtomCount (int maxFragHeavyAtomCount)
void setMinFragHeavyAtomCount (int minFragHeavyAtomCount)
void setFragRejectionSMARTS (Map< String, String > fragRejectionSMARTS)
void setFragRetentionSMARTS (Map< String, String > fragRetentionSMARTS)
ArrayList< Vertex > getIgnorableFragments ()
ArrayList< Vertex > getTargetFragments ()
boolean doManageIsomorphicFamilies ()
int getIsomorphicSampleSize ()
void setIsomorphicSampleSize (int isomorphicSampleSize)
int getMWSlotSize ()
void setMWSlotSize (int mwSlotSize)
Map< String, File > getMWSlotToAllFragsFile ()
void setMWSlotToAllFragsFile (Map< String, File > mwSlotToAllFragsFile)
Map< String, File > getMWSlotToUnqFragsFile ()
File getMWSlotFileNameUnqFrags (String mwSlotId)
Builds the pathname of the file meant to hold unique fragments from within a given MW slot, i.e., holding the unique version of isomorphic fragment families.
File getMWSlotFileNameAllFrags (String mwSlotId)
Builds the pathname of the file meant to hold all isomorphic fragments from a given MW slot.
Map< String, Integer > getIsomorphsCount ()
String newIsomorphicFamilyID ()
Produced a new unique identifier for a family of isomorphic fragments.
boolean doFiltering ()
boolean addExplicitH ()
void setAddExplicitH (boolean addExplicitH)
Give true to add explicit H atoms on all atoms.
boolean acceptUnsetToSingeBO ()
void setEmbedRingsInTemplate (boolean embedRingsInTemplate)
boolean embedRingsInTemplate ()
void setEmbeddedRingsContract (ContractLevel embeddedRingsContract)
ContractLevel getEmbeddedRingsContract ()
void setScaffoldingPolicy (ScaffoldingPolicy sp)
ScaffoldingPolicy getScaffoldingPolicy ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
double getLinearAngleLimit ()
void setLinearAngleLimit (double linearAngleLimit)
Sets the upper limit for an angle before it is treated as "flat" angle, i.e., close enough to 180 DEG.
boolean doExtactRepresentativeConformer ()
int getSizeUnimodalPop ()
void setSizeUnimodalPop (int sizeUnimodalPop)
Sets the size of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
double getMaxNoiseUnimodalPop ()
void setMaxNoiseUnimodalPop (double maxNoiseUnimodalPop)
Sets the maximum noise of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
double getFactorForSDOnStatsOfUnimodalPop ()
void setFactorForSDOnStatsOfUnimodalPop (double factorForSDOnStatsOfUnimodalPop)
Sets the weight of the standard deviation when calculating the RMSD threshold from the statistics of the RMSD over the population of normally distributed noise-distorted points with unimodal distribution of geometric distortions.
boolean isUseCentroidsAsRepresentativeConformer ()
void setUseCentroidsAsRepresentativeConformer (boolean useCentroidsAsRepresentativeConformer)
boolean isSaveClustersOfConformerToFile ()
void setSaveClustersOfConformerToFile (boolean saveClustersOfConformerToFile)
Sets the flag requesting to print clusters of fragments to file upon extraction of the most representative conformers.
boolean isStandaloneFragmentClustering ()
boolean isWorkingIn3D ()
void setWorkingIn3D (boolean workingIn3D)
Sets boolean variable workingIn3D.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Public Attributes
final Object MANAGEMWSLOTSSLOCK = new Object()
Synchronization lock for manipulating a) the collections (i.e., MW slots) of fragments produced by multiple threads and b) the relative information (i.e., isomorphic family size).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Static Public Attributes
static final int MAXISOMORPHICSAMPLESIZE = 50
Maximum isomorphic sample size.
Protected Attributes
boolean embedRingsInTemplate = false
Flag that enables the embedding of rings in templates upon conversion of molecules into DGraph.
ContractLevel embeddedRingsContract = ContractLevel.FREE
Type of constrain defined for any template generated upon conversion of molecules into DGraph.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Package Attributes
List< CuttingRule > cuttingRules
List of cutting rules sorted by priority.
Private Member Functions
void createWorkingDirectory ()
Private Attributes
String structuresFile
Pathname to the file containing the structures of the molecules to fragment.
String formulaeFile
Pathname to the file containing the formulae of the molecules to fragment.
LinkedHashMap< String, String > formulae
Molecular formula read-in from CSD file.
String cutRulesFile
Pathname to the file containing the cutting rules.
int numParallelTasks = 1
Number of parallel tasks to run.
boolean checkFormula = false
Flag requesting the execution of elemental analysis and comparison of the content of the structure file against a given molecular formula.
boolean acceptUnsetToSingeBOApprox = false
Flag requesting to force-accepting the approximation that converts all unset bond orders to single bond orders.
boolean addExplicitH = false
Flag requesting to add explicit H atoms.
boolean preFilter = false
Fag requesting the pre-fragmentation filtering of the structures.
Set< String > preFilterSMARTS = new HashSet<String>()
SMARTS identifying substructures that lead to rejection of a structure before fragmentation.
boolean doFragmentation = false
Fag requesting the fragmentation of the structures.
boolean doFiltering = false
Flag requesting to do post-fragmentation processing of fragments, i.e., application of all filtration and rejection rules that can be applied after fragmentation, though starting from an input that is already a collection of fragments.
boolean doRejectWeirdIsotopes = true
Flag requesting to reject fragments with minor isotopes.
Set< String > rejectedElements = new HashSet<String>()
Symbols of elements that lead to rejection of a fragment.
Map< String, Double > formulaCriteriaLessThan
Lower limits of formula-based criteria for fragment rejection.
Set< Map< String, Double > > formulaCriteriaMoreThan
Upper limits of formula-based criteria for fragment rejection.
Set< String > rejectedAPClasses = new HashSet<String>()
The initial part of APClasses that lead to rejection of a fragment.
Set< String[]> rejectedAPClassCombinations = new HashSet<String[]>()
Combination of strings matching the beginning of APClass names that lead to rejection of a fragment.
int maxFragHeavyAtomCount = -1
Upper limit for number of non-H atoms in fragments.
int minFragHeavyAtomCount = -1
Lower limit for number of non-H atoms in fragments.
Map< String, String > fragRejectionSMARTS = new HashMap<String, String>()
SMARTS leading to rejection of a fragment.
Map< String, String > fragRetentionSMARTS = new HashMap<String, String>()
SMARTS leading to retention of a fragment.
boolean doAddDuOnLinearity = true
Flag requesting to add dummy atoms on linearities.
double linearAngleLimit = 170.0
Upper limit for an angle before it is treated as "flat" ("linear") angle, i.e., close enough to 180 DEG.
String ignorableFragmentsFile = ""
Pathname to file with fragments that can be ignored.
ArrayList< Vertex > ignorableFragments = new ArrayList<Vertex>()
List of fragment that can be rejected.
String targetFragmentsFile = ""
Pathname to file with fragments that will be retained, i.e., any isomorphic fragment of any of these will be kept, all the rest rejected.
ArrayList< Vertex > targetFragments = new ArrayList<Vertex>()
List of fragment that will be retained, i.e., any isomorphic fragment of any of these will be kept, all the rest rejected.
boolean doManageIsomorphicFamilies = false
int isomorphicSampleSize = 1
Size of the sample of isomorphic fragments to collect.
int mwSlotSize = 10
Molecular weight slot width for collecting fragments.
Map< String, File > mwSlotToAllFragsFile = new HashMap<String,File>()
Mapping of the molecular weight slot identifier to the file collecting all collected fragments belonging to that MW slot.
Map< String, File > mwSlotToUnqFragsFile = new HashMap<String,File>()
Mapping of the molecular weight slot identifier to the file collecting unique fragments belonging to that MW slot.
Map< String, Integer > isomorphsCount = new HashMap<String,Integer>()
Counts of isomorphic versions of each known fragment generated in a fragmentation process.
AtomicInteger unqIsomorphicFamilyId = new AtomicInteger(0)
Unique identifier of a family of isomorphic versions of a fragment,.
boolean doExtactRepresentativeConformer = false
Flag signaling the request to analyze each isomorphic family to extract the most representative fragment and make it be the champion of that family.
int sizeUnimodalPop = 20
Size of on-the-fly generated, normally distributed noise-distorted population of geometries used to determine properties of unimodal population of distorted points around an N-dimensional point.
double maxNoiseUnimodalPop = 0.2
Maximum amount of absolute noise used to generate normally distributed noise-distorted population of points around an N-dimensional point.
double factorForSDOnStatsOfUnimodalPop = 1.0
Factor used to multiply the standard deviation when adding it to the mean of the RMSD for a unimodal population of distorted of points around an N-dimensional point, thus defining a threshold for deciding whether a query point belong to that population or not.
boolean useCentroidsAsRepresentativeConformer = true
Flag requesting to same cluster centroids rather than the actual fragments that are closest to the centroids.
boolean saveClustersOfConformerToFile = false
Flag requesting to print clusters of fragments to file.
boolean isStandaloneFragmentClustering = false
Flag requesting to run fragment clusterer in stand-alone fashion.
boolean workingIn3D = true
Flag activating operations depending on 3D structure.
ScaffoldingPolicy scaffoldingPolicy
The policy for defining the scaffold vertex in a graph that does not have such a BBType.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Detailed Description
Parameters controlling execution of the fragmenter.
Author
Marco Foscato
Definition at line 57 of file FragmenterParameters.java.
Constructor & Destructor Documentation
FragmenterParameters()
denoptim.programs.fragmenter.FragmenterParameters.FragmenterParameters ()
Constructor.
Definition at line 391 of file FragmenterParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS.
Member Function Documentation
acceptUnsetToSingeBO()
boolean denoptim.programs.fragmenter.FragmenterParameters.acceptUnsetToSingeBO ()
Returns
true if we are want to ignore the fact we have translated unset bond orders to single-order bonds.
Definition at line 955 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.acceptUnsetToSingeBOApprox.
Referenced by denoptim.fragmenter.FragmenterTools.prepareMolToFragmentation().
addExplicitH()
boolean denoptim.programs.fragmenter.FragmenterParameters.addExplicitH ()
Returns
true if we are asked to add explicit H atoms.
Definition at line 933 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.addExplicitH.
checkParameters()
void denoptim.programs.fragmenter.FragmenterParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1313 of file FragmenterParameters.java.
References denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.fragmenter.FragmenterParameters.cutRulesFile, denoptim.programs.RunTimeParameters.ensureFileExists(), denoptim.programs.RunTimeParameters.ensureFileExistsIfSet(), denoptim.programs.RunTimeParameters.ensureIsPositive(), denoptim.programs.fragmenter.FragmenterParameters.formulaeFile, denoptim.programs.fragmenter.FragmenterParameters.ignorableFragmentsFile, denoptim.programs.fragmenter.FragmenterParameters.isomorphicSampleSize, denoptim.programs.fragmenter.FragmenterParameters.mwSlotSize, denoptim.programs.fragmenter.FragmenterParameters.numParallelTasks, denoptim.programs.fragmenter.FragmenterParameters.structuresFile, denoptim.programs.fragmenter.FragmenterParameters.targetFragmentsFile, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.fragmenter.Fragmenter.runProgram(), and denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
createWorkingDirectory()
void denoptim.programs.fragmenter.FragmenterParameters.createWorkingDirectory () private
Definition at line 1397 of file FragmenterParameters.java.
References denoptim.files.FileUtils.addToRecentFiles(), denoptim.files.FileUtils.createDirectory(), denoptim.files.FileFormat.FRG_RUN, denoptim.programs.RunTimeParameters.logFile, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.processParameters().
doAddDuOnLinearity()
boolean denoptim.programs.fragmenter.FragmenterParameters.doAddDuOnLinearity ()
Returns
true if we want to add dummy atoms to resolve linearities in internal coordinates.
Definition at line 585 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doAddDuOnLinearity.
doCheckFormula()
boolean denoptim.programs.fragmenter.FragmenterParameters.doCheckFormula ()
Returns
true if we are asked to perform the comparison of each element (i.e., elemental analysis) present in the structure file (structuresFile) against that of a given molecular formula, which comes from the formulaeFile.
Definition at line 519 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.checkFormula.
Referenced by denoptim.fragmenter.FragmenterTask.call(), and denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads().
doExtactRepresentativeConformer()
boolean denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer ()
Returns
true if we want to extract the most representative conformer from each isomorphic family.
Definition at line 1475 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer.
doFiltering()
boolean denoptim.programs.fragmenter.FragmenterParameters.doFiltering ()
Returns
true if we want to do post-processing (i.e., filter and reject or collect fragments) on a given list of fragments (i.e., the input), thus skipping any fragmentation.
Definition at line 923 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doFiltering.
doFragmentation()
boolean denoptim.programs.fragmenter.FragmenterParameters.doFragmentation ()
Returns
true if we are asked to fragment structures.
Definition at line 563 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doFragmentation.
doManageIsomorphicFamilies()
boolean denoptim.programs.fragmenter.FragmenterParameters.doManageIsomorphicFamilies ()
One needs to manage isomorphic families, i.e., manage duplicate fragments if we want to identify isomorphic fragments and keep only one isomorphic fragment (i.e., remove all duplicate fragments), or more then more isomorphic fragment. In the latter case, we essentially want to sample the isomorphic family. The extent of this, i.e., the size of the sample is controlled by isomorphicSampleSize).
Also, if we run multiple threads and want to remove duplicate fragments , each of thread may generate a new fragment that the others have not yet found. Thus, the existence of the new fragment must be communicated to the other threads avoiding concurrent generation of the same fragment from different threads.
The management of isomorphic families involves:
Splitting fragments according to molecular weight (MW) to limit the operations on the list of fragments to a small portion of the entire list of fragments.
Separate collection of unique versions of a fragment (the first found) and of the sample of the family of fragments isomorphic to the first.
Thread-safe manipulation of the two MW-split collections: the unique, and the family sample.
Unification of the MW-split collections to obtain the overall result.
Returns
true if we need to manage isomorphic families.
Definition at line 806 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doManageIsomorphicFamilies.
doPreFilter()
boolean denoptim.programs.fragmenter.FragmenterParameters.doPreFilter ()
Returns
true if we are asked to filter initial structures.
Definition at line 542 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.preFilter.
Referenced by denoptim.fragmenter.FragmenterTask.call().
doRejectWeirdIsotopes()
boolean denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes ()
Returns
true if we want to remove fragments that contain isotopes that are not the major isotope for that element.
Definition at line 574 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes.
embedRingsInTemplate()
boolean denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate ()
Returns
the flag that enables the embedding of rings in templates upon conversion of molecules into DGraph .
Definition at line 977 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate.
getCuttingRules()
List< CuttingRule > denoptim.programs.fragmenter.FragmenterParameters.getCuttingRules ()
Returns
the cutting rules currently configured in this set of parameters.
Definition at line 466 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.cuttingRules.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.programs.mol2graph.Mol2GraphParameters.getCuttingRules(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.programs.mol2graph.Mol2GraphParameters.processParameters().
getCuttingRulesFilePathname()
String denoptim.programs.fragmenter.FragmenterParameters.getCuttingRulesFilePathname ()
Returns
the pathname to the cutting rules file.
Definition at line 496 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.cutRulesFile.
Referenced by denoptim.gui.GUIVertexInspector.dialogToDefineCuttingRules(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIVertexInspector.initialize().
getEmbeddedRingsContract()
ContractLevel denoptim.programs.fragmenter.FragmenterParameters.getEmbeddedRingsContract ()
Returns
the type of constrain defined for any template generated upon conversion of molecules into DGraph.
Definition at line 1000 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.embeddedRingsContract.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), and denoptim.programs.mol2graph.Mol2GraphParameters.getEmbeddedRingsContract().
getFactorForSDOnStatsOfUnimodalPop()
double denoptim.programs.fragmenter.FragmenterParameters.getFactorForSDOnStatsOfUnimodalPop ()
Returns
the weight of the standard deviation when calculating the RMSD threshold from the statistics of the RMSD over the population of normally distributed noise-distorted points with unimodal distribution of geometric distortions.
Definition at line 1538 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.factorForSDOnStatsOfUnimodalPop.
Referenced by denoptim.fragmenter.FragmentClusterer.mergeClusters().
getFormulae()
LinkedHashMap< String, String > denoptim.programs.fragmenter.FragmenterParameters.getFormulae ()
Returns
the list of molecular formulae read-in from text file.
Definition at line 506 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulae.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads().
getFormulaeFile()
String denoptim.programs.fragmenter.FragmenterParameters.getFormulaeFile ()
Returns
the pathname to the file containing the molecular formulae to work with.
Definition at line 456 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulaeFile.
getFragRejectionSMARTS()
Map< String, String > denoptim.programs.fragmenter.FragmenterParameters.getFragRejectionSMARTS ()
Returns
the SMARTS that lead to rejection of a fragment.
Definition at line 667 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.fragRejectionSMARTS.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getFragRetentionSMARTS()
Map< String, String > denoptim.programs.fragmenter.FragmenterParameters.getFragRetentionSMARTS ()
Returns
the SMARTS that lead to retention of a fragment.
Definition at line 677 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.fragRetentionSMARTS.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getIgnorableFragments()
ArrayList< Vertex > denoptim.programs.fragmenter.FragmenterParameters.getIgnorableFragments ()
Returns
list of fragment that can be rejected.
Definition at line 760 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.ignorableFragments.
getIsomorphicSampleSize()
int denoptim.programs.fragmenter.FragmenterParameters.getIsomorphicSampleSize ()
Definition at line 813 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.isomorphicSampleSize.
getIsomorphsCount()
Map< String, Integer > denoptim.programs.fragmenter.FragmenterParameters.getIsomorphsCount ()
Returns
the counts of isomorphic versions of each fragment.
Definition at line 900 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.isomorphsCount.
getLinearAngleLimit()
double denoptim.programs.fragmenter.FragmenterParameters.getLinearAngleLimit ()
Returns
the upper limit for an angle before it is treated as "flat" angle, i.e., close enough to 180 DEG.
Definition at line 1452 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.linearAngleLimit.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.programs.mol2graph.Mol2GraphParameters.getLinearAngleLimit(), and denoptim.gui.GUIVertexInspector.initialize().
getMaxFragHeavyAtomCount()
int denoptim.programs.fragmenter.FragmenterParameters.getMaxFragHeavyAtomCount ()
Returns
the max number of heavy atoms to retain a fragment.
Definition at line 647 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.maxFragHeavyAtomCount.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getMaxNoiseUnimodalPop()
double denoptim.programs.fragmenter.FragmenterParameters.getMaxNoiseUnimodalPop ()
Returns
the maximum noise of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
Definition at line 1512 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.maxNoiseUnimodalPop.
Referenced by denoptim.fragmenter.FragmentClusterer.mergeClusters().
getMinFragHeavyAtomCount()
int denoptim.programs.fragmenter.FragmenterParameters.getMinFragHeavyAtomCount ()
Returns
the min number of heavy atoms to retain a fragment.
Definition at line 657 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.minFragHeavyAtomCount.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getMWSlotFileNameAllFrags()
File denoptim.programs.fragmenter.FragmenterParameters.getMWSlotFileNameAllFrags (String mwSlotId)
Builds the pathname of the file meant to hold all isomorphic fragments from a given MW slot.
Parameters
mwSlotId the identifier of the MW slot.
Returns
the file collecting all isomorphic fragment families in the MW range of interest.
Definition at line 887 of file FragmenterParameters.java.
References denoptim.io.DenoptimIO.FS, denoptim.files.FileFormat.getExtension(), denoptim.programs.RunTimeParameters.getWorkDirectory(), denoptim.constants.DENOPTIMConstants.MWSLOTFRAGSALLFILENANEEND, denoptim.constants.DENOPTIMConstants.MWSLOTFRAGSFILENAMEROOT, and denoptim.constants.DENOPTIMConstants.TMPFRAGFILEFORMAT.
Referenced by denoptim.fragmenter.ConformerExtractorTask.ConformerExtractorTask().
getMWSlotFileNameUnqFrags()
File denoptim.programs.fragmenter.FragmenterParameters.getMWSlotFileNameUnqFrags (String mwSlotId)
Builds the pathname of the file meant to hold unique fragments from within a given MW slot, i.e., holding the unique version of isomorphic fragment families.
Parameters
mwSlotId the identifier of the MW slot.
Returns
the file collecting the unique version of isomorphic fragment families in the MW range of interest.
Definition at line 870 of file FragmenterParameters.java.
References denoptim.io.DenoptimIO.FS, denoptim.files.FileFormat.getExtension(), denoptim.programs.RunTimeParameters.getWorkDirectory(), denoptim.constants.DENOPTIMConstants.MWSLOTFRAGSFILENAMEROOT, denoptim.constants.DENOPTIMConstants.MWSLOTFRAGSUNQFILENANEEND, and denoptim.constants.DENOPTIMConstants.TMPFRAGFILEFORMAT.
getMWSlotSize()
int denoptim.programs.fragmenter.FragmenterParameters.getMWSlotSize ()
Definition at line 827 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.mwSlotSize.
Referenced by denoptim.fragmenter.ConformerExtractorTask.ConformerExtractorTask().
getMWSlotToAllFragsFile()
Map< String, File > denoptim.programs.fragmenter.FragmenterParameters.getMWSlotToAllFragsFile ()
Definition at line 841 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.mwSlotToAllFragsFile.
getMWSlotToUnqFragsFile()
Map< String, File > denoptim.programs.fragmenter.FragmenterParameters.getMWSlotToUnqFragsFile ()
Definition at line 855 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.mwSlotToUnqFragsFile.
getNumTasks()
int denoptim.programs.fragmenter.FragmenterParameters.getNumTasks ()
Returns
the number of parallel tasks to run. Default is 1.
Definition at line 401 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.numParallelTasks.
Referenced by denoptim.fragmenter.FragmenterTask.call(), denoptim.fragmenter.ParallelFragmentationAlgorithm.createAndSubmitTasks(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPreFlightOperations(), denoptim.fragmenter.ParallelConformerExtractionAlgorithm.ParallelConformerExtractionAlgorithm(), denoptim.fragmenter.ParallelFragmentationAlgorithm.ParallelFragmentationAlgorithm(), and denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads().
getPreFiltrationSMARTS()
Set< String > denoptim.programs.fragmenter.FragmenterParameters.getPreFiltrationSMARTS ()
Returns
the SMARTS queries identifying substructures that lead to rejection of a structure before fragmentation.
Definition at line 553 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.preFilterSMARTS.
Referenced by denoptim.fragmenter.FragmenterTask.call().
getPrintedList()
String denoptim.programs.fragmenter.FragmenterParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1421 of file FragmenterParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getRejectedAPClassCombinations()
Set< String[]> denoptim.programs.fragmenter.FragmenterParameters.getRejectedAPClassCombinations ()
Returns
the combinations of classes leading to rejection of a fragment.
Definition at line 637 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClassCombinations.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getRejectedAPClasses()
Set< String > denoptim.programs.fragmenter.FragmenterParameters.getRejectedAPClasses ()
Returns
the classes leading to rejection of a fragment.
Definition at line 627 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClasses.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getRejectedElements()
Set< String > denoptim.programs.fragmenter.FragmenterParameters.getRejectedElements ()
Returns
the elemental symbols leading to rejection of a fragment.
Definition at line 595 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedElements.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getRejectedFormulaLessThan()
Map< String, Double > denoptim.programs.fragmenter.FragmenterParameters.getRejectedFormulaLessThan ()
Returns
the formula-based criteria to reject a fragment if there are too few atoms of a certain element.
Definition at line 606 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaLessThan.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getRejectedFormulaMoreThan()
Set< Map< String, Double > > denoptim.programs.fragmenter.FragmenterParameters.getRejectedFormulaMoreThan ()
Returns
the formula-based criteria to reject a fragment if there are too many atoms of a certain element.
Definition at line 617 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaMoreThan.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
getScaffoldingPolicy()
ScaffoldingPolicy denoptim.programs.fragmenter.FragmenterParameters.getScaffoldingPolicy ()
Returns
the policy for defining the scaffold vertex in a graph that does not have such a BBType.
Definition at line 1022 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.scaffoldingPolicy.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), and denoptim.programs.mol2graph.Mol2GraphParameters.getScaffoldingPolicy().
getSizeUnimodalPop()
int denoptim.programs.fragmenter.FragmenterParameters.getSizeUnimodalPop ()
Returns
the size of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
Definition at line 1487 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.sizeUnimodalPop.
Referenced by denoptim.fragmenter.FragmentClusterer.mergeClusters().
getStructuresFile()
String denoptim.programs.fragmenter.FragmenterParameters.getStructuresFile ()
Returns
the pathname to the file containing the structures to work with.
Definition at line 422 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.structuresFile.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.doPreFlightOperations(), denoptim.programs.fragmenter.Fragmenter.runProgram(), denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads(), and denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
getTargetFragments()
ArrayList< Vertex > denoptim.programs.fragmenter.FragmenterParameters.getTargetFragments ()
Returns
the list of fragment that will be retained, i.e., any isomorphic fragment of any of these will be kept, all the rest rejected.
Definition at line 771 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.targetFragments.
interpretKeyword()
void denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1035 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.acceptUnsetToSingeBOApprox, denoptim.programs.fragmenter.FragmenterParameters.addExplicitH, denoptim.programs.fragmenter.FragmenterParameters.checkFormula, denoptim.programs.fragmenter.FragmenterParameters.cutRulesFile, denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer, denoptim.programs.fragmenter.FragmenterParameters.doFiltering, denoptim.programs.fragmenter.FragmenterParameters.doFragmentation, denoptim.programs.fragmenter.FragmenterParameters.doManageIsomorphicFamilies, denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes, denoptim.fragmenter.ScaffoldingPolicy.ELEMENT, denoptim.programs.fragmenter.FragmenterParameters.embeddedRingsContract, denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate, denoptim.programs.fragmenter.FragmenterParameters.factorForSDOnStatsOfUnimodalPop, denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaLessThan, denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaMoreThan, denoptim.programs.fragmenter.FragmenterParameters.formulaeFile, denoptim.programs.fragmenter.FragmenterParameters.fragRejectionSMARTS, denoptim.programs.fragmenter.FragmenterParameters.fragRetentionSMARTS, denoptim.programs.fragmenter.FragmenterParameters.ignorableFragmentsFile, denoptim.programs.fragmenter.FragmenterParameters.isomorphicSampleSize, denoptim.programs.fragmenter.FragmenterParameters.maxFragHeavyAtomCount, denoptim.programs.fragmenter.FragmenterParameters.maxNoiseUnimodalPop, denoptim.programs.fragmenter.FragmenterParameters.minFragHeavyAtomCount, denoptim.programs.fragmenter.FragmenterParameters.mwSlotSize, denoptim.programs.fragmenter.FragmenterParameters.numParallelTasks, denoptim.utils.FormulaUtils.parseFormula(), denoptim.programs.fragmenter.FragmenterParameters.preFilter, denoptim.programs.fragmenter.FragmenterParameters.preFilterSMARTS, denoptim.programs.RunTimeParameters.readYesNoTrueFalse(), denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClassCombinations, denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClasses, denoptim.programs.fragmenter.FragmenterParameters.rejectedElements, denoptim.programs.fragmenter.FragmenterParameters.saveClustersOfConformerToFile, denoptim.programs.fragmenter.FragmenterParameters.scaffoldingPolicy, denoptim.programs.fragmenter.FragmenterParameters.sizeUnimodalPop, denoptim.programs.fragmenter.FragmenterParameters.structuresFile, denoptim.programs.fragmenter.FragmenterParameters.targetFragmentsFile, denoptim.programs.fragmenter.FragmenterParameters.useCentroidsAsRepresentativeConformer, denoptim.programs.RunTimeParameters.verbosity, and denoptim.programs.RunTimeParameters.workDir.
isSaveClustersOfConformerToFile()
boolean denoptim.programs.fragmenter.FragmenterParameters.isSaveClustersOfConformerToFile ()
Returns
true if we are asked to print clusters of fragments to file upon extraction of the most representative conformers.
Definition at line 1594 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.saveClustersOfConformerToFile.
Referenced by denoptim.fragmenter.ConformerExtractorTask.call().
isStandaloneFragmentClustering()
boolean denoptim.programs.fragmenter.FragmenterParameters.isStandaloneFragmentClustering ()
Returns
true if we are asked to run only the clustering of fragments from a given list of fragment.
Definition at line 1619 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.isStandaloneFragmentClustering.
isUseCentroidsAsRepresentativeConformer()
boolean denoptim.programs.fragmenter.FragmenterParameters.isUseCentroidsAsRepresentativeConformer ()
Returns
true if we are asked to save cluster centroids rather than the actual fragments that are closest to the centroids upon extraction of the most representative conformers.
Definition at line 1566 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.useCentroidsAsRepresentativeConformer.
Referenced by denoptim.fragmenter.ConformerExtractorTask.call().
isWorkingIn3D()
boolean denoptim.programs.fragmenter.FragmenterParameters.isWorkingIn3D ()
Returns
true if we are dealing with 3D structures
Definition at line 1630 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.workingIn3D.
Referenced by denoptim.fragmenter.FragmenterTools.filterFragment().
newIsomorphicFamilyID()
String denoptim.programs.fragmenter.FragmenterParameters.newIsomorphicFamilyID ()
Produced a new unique identifier for a family of isomorphic fragments.
Returns
the unique ID.
Definition at line 911 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.unqIsomorphicFamilyId.
processParameters()
void denoptim.programs.fragmenter.FragmenterParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 1339 of file FragmenterParameters.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.fragmenter.FragmenterParameters.createWorkingDirectory(), denoptim.programs.fragmenter.FragmenterParameters.cutRulesFile, denoptim.programs.fragmenter.FragmenterParameters.cuttingRules, denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer, denoptim.programs.fragmenter.FragmenterParameters.doFragmentation, denoptim.constants.DENOPTIMConstants.EOL, denoptim.programs.fragmenter.FragmenterParameters.formulae, denoptim.programs.fragmenter.FragmenterParameters.formulaeFile, denoptim.programs.fragmenter.FragmenterParameters.ignorableFragments, denoptim.programs.fragmenter.FragmenterParameters.ignorableFragmentsFile, denoptim.programs.RunTimeParameters.isMaster, denoptim.programs.fragmenter.FragmenterParameters.isStandaloneFragmentClustering, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.RunTimeParameters.processOtherParameters(), denoptim.io.DenoptimIO.readCSDFormulae(), denoptim.io.DenoptimIO.readCuttingRules(), denoptim.io.DenoptimIO.readVertexes(), denoptim.programs.fragmenter.FragmenterParameters.targetFragments, denoptim.programs.fragmenter.FragmenterParameters.targetFragmentsFile, denoptim.graph.Vertex.BBType.UNDEFINED, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.fragmenter.Fragmenter.runProgram(), and denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
setAddExplicitH()
void denoptim.programs.fragmenter.FragmenterParameters.setAddExplicitH (boolean addExplicitH)
Give true to add explicit H atoms on all atoms.
Useful, when importing molecules with implicit H notation.
Definition at line 944 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.addExplicitH.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule().
setCheckFormula()
void denoptim.programs.fragmenter.FragmenterParameters.setCheckFormula (boolean checkFormula)
Sets the value of the flag controlling the execution of elemental analysis on the structures.
Parameters
checkFormula use true to request the elemental analysis.
Definition at line 531 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.checkFormula.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
setCuttingRules()
void denoptim.programs.fragmenter.FragmenterParameters.setCuttingRules (List< CuttingRule > cuttingRules)
Assigns the cutting rules loaded from the input.
Definition at line 476 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.cuttingRules.
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.processParameters(), and denoptim.gui.CuttingRulesSelectionDialog.saveResults().
setCuttingRulesFilePathname()
void denoptim.programs.fragmenter.FragmenterParameters.setCuttingRulesFilePathname (String pathname)
Assigns the pathname to the cutting rules file.
Definition at line 486 of file FragmenterParameters.java.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.saveResults().
setEmbeddedRingsContract()
void denoptim.programs.fragmenter.FragmenterParameters.setEmbeddedRingsContract (ContractLevel embeddedRingsContract)
Parameters
embeddedRingsContract the type of constrain defined for any template generated upon conversion of molecules into DGraph.
Definition at line 989 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.embeddedRingsContract.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
setEmbedRingsInTemplate()
void denoptim.programs.fragmenter.FragmenterParameters.setEmbedRingsInTemplate (boolean embedRingsInTemplate)
Parameters
embedRingsInTemplate the flag that enables the embedding of rings in templates upon conversion of molecules into DGraph .
Definition at line 966 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
setFactorForSDOnStatsOfUnimodalPop()
void denoptim.programs.fragmenter.FragmenterParameters.setFactorForSDOnStatsOfUnimodalPop (double factorForSDOnStatsOfUnimodalPop)
Sets the weight of the standard deviation when calculating the RMSD threshold from the statistics of the RMSD over the population of normally distributed noise-distorted points with unimodal distribution of geometric distortions.
Definition at line 1552 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.factorForSDOnStatsOfUnimodalPop.
setFormulaeFile()
void denoptim.programs.fragmenter.FragmenterParameters.setFormulaeFile (String formulaeFile)
Sets the pathname of the file containing molecular formula with a format respecting Cambridge Structural Database format).
Parameters
formulaeFile
Definition at line 445 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulaeFile.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
setFragRejectionSMARTS()
void denoptim.programs.fragmenter.FragmenterParameters.setFragRejectionSMARTS (Map< String, String > fragRejectionSMARTS)
Definition at line 743 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.fragRejectionSMARTS.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setFragRetentionSMARTS()
void denoptim.programs.fragmenter.FragmenterParameters.setFragRetentionSMARTS (Map< String, String > fragRetentionSMARTS)
Definition at line 750 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.fragRetentionSMARTS.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setIsomorphicSampleSize()
void denoptim.programs.fragmenter.FragmenterParameters.setIsomorphicSampleSize (int isomorphicSampleSize)
Definition at line 820 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.isomorphicSampleSize.
setLinearAngleLimit()
void denoptim.programs.fragmenter.FragmenterParameters.setLinearAngleLimit (double linearAngleLimit)
Sets the upper limit for an angle before it is treated as "flat" angle, i.e., close enough to 180 DEG.
Parameters
linearAngleLimit the new value.
Definition at line 1464 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.linearAngleLimit.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.saveResults().
setMaxFragHeavyAtomCount()
void denoptim.programs.fragmenter.FragmenterParameters.setMaxFragHeavyAtomCount (int maxFragHeavyAtomCount)
Definition at line 729 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.maxFragHeavyAtomCount.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setMaxNoiseUnimodalPop()
void denoptim.programs.fragmenter.FragmenterParameters.setMaxNoiseUnimodalPop (double maxNoiseUnimodalPop)
Sets the maximum noise of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
Definition at line 1525 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.maxNoiseUnimodalPop.
setMinFragHeavyAtomCount()
void denoptim.programs.fragmenter.FragmenterParameters.setMinFragHeavyAtomCount (int minFragHeavyAtomCount)
Definition at line 736 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.minFragHeavyAtomCount.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setMWSlotSize()
void denoptim.programs.fragmenter.FragmenterParameters.setMWSlotSize (int mwSlotSize)
Definition at line 834 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.mwSlotSize.
setMWSlotToAllFragsFile()
void denoptim.programs.fragmenter.FragmenterParameters.setMWSlotToAllFragsFile (Map< String, File > mwSlotToAllFragsFile)
Definition at line 848 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.mwSlotToAllFragsFile.
setNumTasks()
void denoptim.programs.fragmenter.FragmenterParameters.setNumTasks (int numParallelTasks)
Sets the number of parallel tasks to run.
Parameters
numParallelTasks
Definition at line 412 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.numParallelTasks.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
setRejectedAPClassCombinations()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClassCombinations (Set< String[]> rejectedAPClassCombinations)
Definition at line 721 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClassCombinations.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setRejectedAPClasses()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClasses (Set< String > rejectedAPClasses)
Definition at line 714 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClasses.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setRejectedElements()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectedElements (Set< String > rejectedElements)
Definition at line 691 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.rejectedElements.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setRejectedFormulaLessThan()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectedFormulaLessThan (Map< String, Double > formulaMax)
Definition at line 698 of file FragmenterParameters.java.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setRejectedFormulaMoreThan()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectedFormulaMoreThan (Set< Map< String, Double > > formulaCriteriaMoreThan)
Definition at line 706 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaMoreThan.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setRejectWeirdIsotopes()
void denoptim.programs.fragmenter.FragmenterParameters.setRejectWeirdIsotopes (boolean doRejectWeirdIsotopes)
Definition at line 684 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testFilterFragment().
setSaveClustersOfConformerToFile()
void denoptim.programs.fragmenter.FragmenterParameters.setSaveClustersOfConformerToFile (boolean saveClustersOfConformerToFile)
Sets the flag requesting to print clusters of fragments to file upon extraction of the most representative conformers.
Parameters
saveClustersOfConformerToFile use true to request printing clusters of fragments to file.
Definition at line 1607 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.saveClustersOfConformerToFile.
setScaffoldingPolicy()
void denoptim.programs.fragmenter.FragmenterParameters.setScaffoldingPolicy (ScaffoldingPolicy sp)
Parameters
sp the policy for defining the scaffold vertex in a graph that does not have such a BBType.
Definition at line 1011 of file FragmenterParameters.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
setSizeUnimodalPop()
void denoptim.programs.fragmenter.FragmenterParameters.setSizeUnimodalPop (int sizeUnimodalPop)
Sets the size of the population of normally distributed noise-distorted population used to define the threshold RMSD of a unimodal distribution of geometric distortions.
Definition at line 1499 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.sizeUnimodalPop.
setStructuresFile()
void denoptim.programs.fragmenter.FragmenterParameters.setStructuresFile (String structuresFile)
Sets the pathname of the file containing input structures.
Parameters
structuresFile the pathname.
Definition at line 433 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.structuresFile.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
setUseCentroidsAsRepresentativeConformer()
void denoptim.programs.fragmenter.FragmenterParameters.setUseCentroidsAsRepresentativeConformer (boolean useCentroidsAsRepresentativeConformer)
Parameters
useCentroidsAsRepresentativeConformer set to true to request saving cluster centroids rather than the actual fragments that are closest to the centroids upon extraction of the most representative conformers.
Definition at line 1580 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.useCentroidsAsRepresentativeConformer.
setWorkingIn3D()
void denoptim.programs.fragmenter.FragmenterParameters.setWorkingIn3D (boolean workingIn3D)
Sets boolean variable workingIn3D.
Parameters
workingIn3D
Definition at line 1641 of file FragmenterParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.workingIn3D.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPreFlightOperations(), and denoptim.ga.EvolutionaryAlgorithm.initializePopulation().
Member Data Documentation
acceptUnsetToSingeBOApprox
boolean denoptim.programs.fragmenter.FragmenterParameters.acceptUnsetToSingeBOApprox = false private
Flag requesting to force-accepting the approximation that converts all unset bond orders to single bond orders.
This to signify 'a bond exist' between atoms for which there is no proper bond order. Still, considerations based on evaluating the bond order will be misguided.
Definition at line 105 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.acceptUnsetToSingeBO(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
addExplicitH
boolean denoptim.programs.fragmenter.FragmenterParameters.addExplicitH = false private
Flag requesting to add explicit H atoms.
Definition at line 110 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.addExplicitH(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), denoptim.fragmenter.FragmenterTools.prepareMolToFragmentation(), and denoptim.programs.fragmenter.FragmenterParameters.setAddExplicitH().
checkFormula
boolean denoptim.programs.fragmenter.FragmenterParameters.checkFormula = false private
Flag requesting the execution of elemental analysis and comparison of the content of the structure file against a given molecular formula.
This task is meant to identify structures with missing atoms.
Definition at line 97 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doCheckFormula(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setCheckFormula().
cutRulesFile
String denoptim.programs.fragmenter.FragmenterParameters.cutRulesFile private
Pathname to the file containing the cutting rules.
Definition at line 80 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getCuttingRulesFilePathname(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
cuttingRules
List<CuttingRule> denoptim.programs.fragmenter.FragmenterParameters.cuttingRules package
List of cutting rules sorted by priority.
Definition at line 85 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getCuttingRules(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), and denoptim.programs.fragmenter.FragmenterParameters.setCuttingRules().
doAddDuOnLinearity
boolean denoptim.programs.fragmenter.FragmenterParameters.doAddDuOnLinearity = true private
Flag requesting to add dummy atoms on linearities.
This to enable 3D-modeling of the system with internal coordinates.
Definition at line 202 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doAddDuOnLinearity().
doExtactRepresentativeConformer
boolean denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer = false private
Flag signaling the request to analyze each isomorphic family to extract the most representative fragment and make it be the champion of that family.
Definition at line 318 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doExtactRepresentativeConformer(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
doFiltering
boolean denoptim.programs.fragmenter.FragmenterParameters.doFiltering = false private
Flag requesting to do post-fragmentation processing of fragments, i.e., application of all filtration and rejection rules that can be applied after fragmentation, though starting from an input that is already a collection of fragments.
Essentially, skip fragmentation and filter the given fragments
Definition at line 136 of file FragmenterParameters.java.
Referenced by denoptim.fragmenter.FragmenterTask.call(), denoptim.programs.fragmenter.FragmenterParameters.doFiltering(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
doFragmentation
boolean denoptim.programs.fragmenter.FragmenterParameters.doFragmentation = false private
Fag requesting the fragmentation of the structures.
Definition at line 127 of file FragmenterParameters.java.
Referenced by denoptim.fragmenter.FragmenterTask.call(), denoptim.programs.fragmenter.FragmenterParameters.doFragmentation(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
doManageIsomorphicFamilies
boolean denoptim.programs.fragmenter.FragmenterParameters.doManageIsomorphicFamilies = false private
Flag signaling the need to manage isomorphic families, i.e., manage duplicate fragments. This is needed if we want to identify isomorphic fragments and keep only one isomorphic fragment (i.e., remove all duplicate fragments), or more then one isomorphic fragment. In the latter case, we essentially want to sample the isomorphic family. The extent of this, i.e., the size of the sample is controlled by isomorphicSampleSize).
Also, if we run multiple threads and want to remove duplicate fragments , each thread may generate a new fragment that the others have not yet found. Thus, the existence of the new fragment must be communicated to the other threads avoiding concurrent generation of the same fragment from different threads.
The management of isomorphic families involves:
Splitting fragments according to molecular weight (MW) to limit the operations on the list of fragments to a small portion of the entire list of fragments.
Separate collection of unique versions of a fragment (the first found) and of the sample of the family of fragments isomorphic to the first.
Thread-safe manipulation of the two MW-split collections: the unique, and the family sample.
Unification of the MW-split collections to obtain the overall result.
Definition at line 259 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doManageIsomorphicFamilies(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
doRejectWeirdIsotopes
boolean denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes = true private
Flag requesting to reject fragments with minor isotopes.
Definition at line 141 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doRejectWeirdIsotopes(), denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setRejectWeirdIsotopes().
embeddedRingsContract
ContractLevel denoptim.programs.fragmenter.FragmenterParameters.embeddedRingsContract = ContractLevel.FREE protected
Type of constrain defined for any template generated upon conversion of molecules into DGraph.
Definition at line 383 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getEmbeddedRingsContract(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setEmbeddedRingsContract().
embedRingsInTemplate
boolean denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate = false protected
Flag that enables the embedding of rings in templates upon conversion of molecules into DGraph.
Definition at line 377 of file FragmenterParameters.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate(), denoptim.programs.mol2graph.Mol2GraphParameters.embedRingsInTemplate(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setEmbedRingsInTemplate().
factorForSDOnStatsOfUnimodalPop
double denoptim.programs.fragmenter.FragmenterParameters.factorForSDOnStatsOfUnimodalPop = 1.0 private
Factor used to multiply the standard deviation when adding it to the mean of the RMSD for a unimodal population of distorted of points around an N-dimensional point, thus defining a threshold for deciding whether a query point belong to that population or not.
Used by FragmentClusterer.
Definition at line 343 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getFactorForSDOnStatsOfUnimodalPop(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setFactorForSDOnStatsOfUnimodalPop().
formulaCriteriaLessThan
Map<String,Double> denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaLessThan private
Initial value:
=
            new HashMap<String,Double>()
Lower limits of formula-based criteria for fragment rejection.
I.e., if a fragment has a formula that counts less then what defined here, it is rejected.
Definition at line 153 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getRejectedFormulaLessThan(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
formulaCriteriaMoreThan
Set<Map<String,Double> > denoptim.programs.fragmenter.FragmenterParameters.formulaCriteriaMoreThan private
Initial value:
=
            new HashSet<Map<String,Double>>()
Upper limits of formula-based criteria for fragment rejection.
I.e., if a fragment has a formula that counts more then what defined here, it is rejected.
Definition at line 161 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getRejectedFormulaMoreThan(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setRejectedFormulaMoreThan().
formulae
LinkedHashMap<String, String> denoptim.programs.fragmenter.FragmenterParameters.formulae private
Molecular formula read-in from CSD file.
Data collected by CSD refcode.
Definition at line 75 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getFormulae(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
formulaeFile
String denoptim.programs.fragmenter.FragmenterParameters.formulaeFile private
Pathname to the file containing the formulae of the molecules to fragment.
Definition at line 69 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getFormulaeFile(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), and denoptim.programs.fragmenter.FragmenterParameters.setFormulaeFile().
fragRejectionSMARTS
Map<String, String> denoptim.programs.fragmenter.FragmenterParameters.fragRejectionSMARTS = new HashMap<String, String>() private
SMARTS leading to rejection of a fragment.
Definition at line 190 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getFragRejectionSMARTS(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setFragRejectionSMARTS().
fragRetentionSMARTS
Map<String, String> denoptim.programs.fragmenter.FragmenterParameters.fragRetentionSMARTS = new HashMap<String, String>() private
SMARTS leading to retention of a fragment.
All fragments not matching one of these are rejected.
Definition at line 196 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getFragRetentionSMARTS(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setFragRetentionSMARTS().
ignorableFragments
ArrayList<Vertex> denoptim.programs.fragmenter.FragmenterParameters.ignorableFragments = new ArrayList<Vertex>() private
List of fragment that can be rejected.
Definition at line 218 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getIgnorableFragments(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
ignorableFragmentsFile
String denoptim.programs.fragmenter.FragmenterParameters.ignorableFragmentsFile = "" private
Pathname to file with fragments that can be ignored.
Definition at line 213 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
isomorphicSampleSize
int denoptim.programs.fragmenter.FragmenterParameters.isomorphicSampleSize = 1 private
Size of the sample of isomorphic fragments to collect.
When this number N is larger then one, we will collect the first N isomorphic forms of each fragment. A value of 1 corresponds to saying "remove all isomorphic duplicates".
Definition at line 267 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getIsomorphicSampleSize(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setIsomorphicSampleSize().
isomorphsCount
Map<String,Integer> denoptim.programs.fragmenter.FragmenterParameters.isomorphsCount = new HashMap<String,Integer>() private
Counts of isomorphic versions of each known fragment generated in a fragmentation process.
The key is a string that identifies the vertex without having to hold the entire data structure of it.
Definition at line 296 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getIsomorphsCount().
isStandaloneFragmentClustering
boolean denoptim.programs.fragmenter.FragmenterParameters.isStandaloneFragmentClustering = false private
Flag requesting to run fragment clusterer in stand-alone fashion.
Definition at line 359 of file FragmenterParameters.java.
Referenced by denoptim.fragmenter.ConformerExtractorTask.call(), denoptim.programs.fragmenter.FragmenterParameters.isStandaloneFragmentClustering(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), and denoptim.programs.fragmenter.Fragmenter.runProgram().
linearAngleLimit
double denoptim.programs.fragmenter.FragmenterParameters.linearAngleLimit = 170.0 private
Upper limit for an angle before it is treated as "flat" ("linear") angle, i.e., close enough to 180 DEG.
Definition at line 208 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getLinearAngleLimit(), and denoptim.programs.fragmenter.FragmenterParameters.setLinearAngleLimit().
MANAGEMWSLOTSSLOCK
final Object denoptim.programs.fragmenter.FragmenterParameters.MANAGEMWSLOTSSLOCK = new Object()
Synchronization lock for manipulating a) the collections (i.e., MW slots) of fragments produced by multiple threads and b) the relative information (i.e., isomorphic family size).
Definition at line 311 of file FragmenterParameters.java.
maxFragHeavyAtomCount
int denoptim.programs.fragmenter.FragmenterParameters.maxFragHeavyAtomCount = -1 private
Upper limit for number of non-H atoms in fragments.
Negative number is used to disable checking of the number of atoms.
Definition at line 179 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getMaxFragHeavyAtomCount(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setMaxFragHeavyAtomCount().
MAXISOMORPHICSAMPLESIZE
final int denoptim.programs.fragmenter.FragmenterParameters.MAXISOMORPHICSAMPLESIZE = 50 static
Maximum isomorphic sample size.
Definition at line 272 of file FragmenterParameters.java.
Referenced by denoptim.fragmenter.ConformerExtractorTask.extractClusterableFragments().
maxNoiseUnimodalPop
double denoptim.programs.fragmenter.FragmenterParameters.maxNoiseUnimodalPop = 0.2 private
Maximum amount of absolute noise used to generate normally distributed noise-distorted population of points around an N-dimensional point.
Used by FragmentClusterer.
Definition at line 333 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getMaxNoiseUnimodalPop(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setMaxNoiseUnimodalPop().
minFragHeavyAtomCount
int denoptim.programs.fragmenter.FragmenterParameters.minFragHeavyAtomCount = -1 private
Lower limit for number of non-H atoms in fragments.
Negative number is used to disable checking of the number of atoms.
Definition at line 185 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getMinFragHeavyAtomCount(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setMinFragHeavyAtomCount().
mwSlotSize
int denoptim.programs.fragmenter.FragmenterParameters.mwSlotSize = 10 private
Molecular weight slot width for collecting fragments.
Definition at line 277 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getMWSlotSize(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setMWSlotSize().
mwSlotToAllFragsFile
Map<String,File> denoptim.programs.fragmenter.FragmenterParameters.mwSlotToAllFragsFile = new HashMap<String,File>() private
Mapping of the molecular weight slot identifier to the file collecting all collected fragments belonging to that MW slot.
Definition at line 283 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getMWSlotToAllFragsFile(), and denoptim.programs.fragmenter.FragmenterParameters.setMWSlotToAllFragsFile().
mwSlotToUnqFragsFile
Map<String,File> denoptim.programs.fragmenter.FragmenterParameters.mwSlotToUnqFragsFile = new HashMap<String,File>() private
Mapping of the molecular weight slot identifier to the file collecting unique fragments belonging to that MW slot.
Definition at line 289 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getMWSlotToUnqFragsFile().
numParallelTasks
int denoptim.programs.fragmenter.FragmenterParameters.numParallelTasks = 1 private
Number of parallel tasks to run.
Definition at line 90 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getNumTasks(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setNumTasks().
preFilter
boolean denoptim.programs.fragmenter.FragmenterParameters.preFilter = false private
Fag requesting the pre-fragmentation filtering of the structures.
Definition at line 115 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.doPreFilter(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
preFilterSMARTS
Set<String> denoptim.programs.fragmenter.FragmenterParameters.preFilterSMARTS = new HashSet<String>() private
SMARTS identifying substructures that lead to rejection of a structure before fragmentation.
I.e., structures matching any of these queries will not be fragmented.
Definition at line 122 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getPreFiltrationSMARTS(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
rejectedAPClassCombinations
Set<String[]> denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClassCombinations = new HashSet<String[]>() private
Combination of strings matching the beginning of APClass names that lead to rejection of a fragment.
Definition at line 173 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getRejectedAPClassCombinations(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClassCombinations().
rejectedAPClasses
Set<String> denoptim.programs.fragmenter.FragmenterParameters.rejectedAPClasses = new HashSet<String>() private
The initial part of APClasses that lead to rejection of a fragment.
Definition at line 167 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getRejectedAPClasses(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClasses().
rejectedElements
Set<String> denoptim.programs.fragmenter.FragmenterParameters.rejectedElements = new HashSet<String>() private
Symbols of elements that lead to rejection of a fragment.
Definition at line 146 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getRejectedElements(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setRejectedElements().
saveClustersOfConformerToFile
boolean denoptim.programs.fragmenter.FragmenterParameters.saveClustersOfConformerToFile = false private
Flag requesting to print clusters of fragments to file.
Definition at line 354 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), denoptim.programs.fragmenter.FragmenterParameters.isSaveClustersOfConformerToFile(), and denoptim.programs.fragmenter.FragmenterParameters.setSaveClustersOfConformerToFile().
scaffoldingPolicy
ScaffoldingPolicy denoptim.programs.fragmenter.FragmenterParameters.scaffoldingPolicy private
Initial value:
=
            ScaffoldingPolicy.LARGEST_FRAGMENT
The policy for defining the scaffold vertex in a graph that does not have such a BBType.
Definition at line 370 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getScaffoldingPolicy(), and denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword().
sizeUnimodalPop
int denoptim.programs.fragmenter.FragmenterParameters.sizeUnimodalPop = 20 private
Size of on-the-fly generated, normally distributed noise-distorted population of geometries used to determine properties of unimodal population of distorted points around an N-dimensional point.
Used by FragmentClusterer.
Definition at line 326 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getSizeUnimodalPop(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setSizeUnimodalPop().
structuresFile
String denoptim.programs.fragmenter.FragmenterParameters.structuresFile private
Pathname to the file containing the structures of the molecules to fragment.
Definition at line 63 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.getStructuresFile(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.setStructuresFile().
targetFragments
ArrayList<Vertex> denoptim.programs.fragmenter.FragmenterParameters.targetFragments = new ArrayList<Vertex>() private
List of fragment that will be retained, i.e., any isomorphic fragment of any of these will be kept, all the rest rejected.
Definition at line 230 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.getTargetFragments(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
targetFragmentsFile
String denoptim.programs.fragmenter.FragmenterParameters.targetFragmentsFile = "" private
Pathname to file with fragments that will be retained, i.e., any isomorphic fragment of any of these will be kept, all the rest rejected.
Definition at line 224 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), and denoptim.programs.fragmenter.FragmenterParameters.processParameters().
unqIsomorphicFamilyId
AtomicInteger denoptim.programs.fragmenter.FragmenterParameters.unqIsomorphicFamilyId = new AtomicInteger(0) private
Unique identifier of a family of isomorphic versions of a fragment,.
Definition at line 304 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.newIsomorphicFamilyID().
useCentroidsAsRepresentativeConformer
boolean denoptim.programs.fragmenter.FragmenterParameters.useCentroidsAsRepresentativeConformer = true private
Flag requesting to same cluster centroids rather than the actual fragments that are closest to the centroids.
Definition at line 349 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.interpretKeyword(), denoptim.programs.fragmenter.FragmenterParameters.isUseCentroidsAsRepresentativeConformer(), and denoptim.programs.fragmenter.FragmenterParameters.setUseCentroidsAsRepresentativeConformer().
workingIn3D
boolean denoptim.programs.fragmenter.FragmenterParameters.workingIn3D = true private
Flag activating operations depending on 3D structure.
Definition at line 364 of file FragmenterParameters.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.isWorkingIn3D(), and denoptim.programs.fragmenter.FragmenterParameters.setWorkingIn3D().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/fragmenter/FragmenterParameters.java