DENOPTIM: denoptim.gui.HomePanel Class Reference
denoptim.gui.HomePanel Class Reference
The home panel contains shortcuts buttons to perform the most common tasks.
Public Member Functions
HomePanel (GUIMainPanel mainPanel)
Constructor.
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Private Member Functions
void initialize ()
Initialize the panel with figure and shortcuts and credit panels.
Static Private Attributes
static final long serialVersionUID = 5512821342651489833L
Version.
Additional Inherited Members
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Detailed Description
The home panel contains shortcuts buttons to perform the most common tasks.
Definition at line 52 of file HomePanel.java.
Constructor & Destructor Documentation
HomePanel()
denoptim.gui.HomePanel.HomePanel (GUIMainPanel mainPanel)
Constructor.
Definition at line 65 of file HomePanel.java.
References denoptim.gui.HomePanel.initialize(), and denoptim.gui.GUICardPanel.mainPanel.
Member Function Documentation
initialize()
void denoptim.gui.HomePanel.initialize () private
Initialize the panel with figure and shortcuts and credit panels.
Definition at line 75 of file HomePanel.java.
References denoptim.gui.GUIMainPanel.add(), denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectGARun.importGARunData(), denoptim.gui.GUICardPanel.mainPanel, and denoptim.gui.GUIFileOpener.pickFolder().
Referenced by denoptim.gui.HomePanel.HomePanel().
Member Data Documentation
serialVersionUID
final long denoptim.gui.HomePanel.serialVersionUID = 5512821342651489833L static private
Version.
Definition at line 58 of file HomePanel.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/HomePanel.java