DENOPTIM: denoptim.programs.fitnessevaluator.FPRunner Class Reference
denoptim.programs.fitnessevaluator.FPRunner Class Reference
Runs a fitness provider task as defined in the static parameters.
Public Member Functions
FPRunner (FRParameters settings)
Constructor.
void stopRun ()
Stops all subtasks and shutdown executor.
void run () throws Exception
Create and run the fitness task.
Package Attributes
final Map< FitnessTask, Future< Object > > futures
Storage of references to the submitted subtasks as Future.
final List< FitnessTask > submitted
Storage of references to the submitted subtasks.
final ThreadPoolExecutor tpe
Asynchronous tasks manager.
Private Member Functions
void cleanupCompleted ()
Removes only tasks that are marked as completed.
void cleanup ()
clean all reference to submitted tasks
Private Attributes
FRParameters settings
The parameters controlling the.
int numThreads = 1
Number of parallel fitness evaluations we run.
Detailed Description
Runs a fitness provider task as defined in the static parameters.
This class is meant to execute fitness provider tasks from the GUI or the CLI in a stand-alone fashion, i.e., without running GARunner or FragSpaceExplorer.
Author
Marco Foscato
Definition at line 56 of file FPRunner.java.
Constructor & Destructor Documentation
FPRunner()
denoptim.programs.fitnessevaluator.FPRunner.FPRunner (FRParameters settings)
Constructor.
Definition at line 91 of file FPRunner.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FPRunner.numThreads, denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.programs.fitnessevaluator.FPRunner.settings, denoptim.programs.fitnessevaluator.FPRunner.submitted, and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Member Function Documentation
cleanup()
void denoptim.programs.fitnessevaluator.FPRunner.cleanup () private
clean all reference to submitted tasks
Definition at line 270 of file FPRunner.java.
References denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FPRunner.submitted, and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
cleanupCompleted()
void denoptim.programs.fitnessevaluator.FPRunner.cleanupCompleted () private
Removes only tasks that are marked as completed.
Definition at line 246 of file FPRunner.java.
References denoptim.programs.fitnessevaluator.FPRunner.futures, and denoptim.programs.fitnessevaluator.FPRunner.submitted.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.run().
run()
void denoptim.programs.fitnessevaluator.FPRunner.run () throws Exception
Create and run the fitness task.
Exceptions
Exception
Definition at line 171 of file FPRunner.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.fitnessevaluator.FPRunner.cleanupCompleted(), denoptim.constants.DENOPTIMConstants.EOL, denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FRParameters.getInputFile(), denoptim.programs.fitnessevaluator.FRParameters.getOutputFile(), denoptim.programs.fitnessevaluator.FRParameters.getWallTime(), denoptim.programs.RunTimeParameters.getWorkDirectory(), denoptim.programs.fitnessevaluator.FPRunner.numThreads, denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.io.DenoptimIO.readSDFFile(), denoptim.io.DenoptimIO.readText(), denoptim.programs.fitnessevaluator.FPRunner.settings, denoptim.programs.fitnessevaluator.FPRunner.submitted, denoptim.programs.fitnessevaluator.FPRunner.tpe, and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FitnessRunner.runProgram().
stopRun()
void denoptim.programs.fitnessevaluator.FPRunner.stopRun ()
Stops all subtasks and shutdown executor.
Definition at line 158 of file FPRunner.java.
References denoptim.programs.fitnessevaluator.FPRunner.cleanup(), and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Referenced by denoptim.programs.fitnessevaluator.FitnessRunner.handleThrowable().
Member Data Documentation
futures
final Map<FitnessTask,Future<Object> > denoptim.programs.fitnessevaluator.FPRunner.futures package
Storage of references to the submitted subtasks as Future.
Definition at line 61 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.cleanupCompleted(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.run().
numThreads
int denoptim.programs.fitnessevaluator.FPRunner.numThreads = 1 private
Number of parallel fitness evaluations we run.
Definition at line 83 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.run().
settings
FRParameters denoptim.programs.fitnessevaluator.FPRunner.settings private
The parameters controlling the.
Definition at line 76 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.run().
submitted
final List<FitnessTask> denoptim.programs.fitnessevaluator.FPRunner.submitted package
Storage of references to the submitted subtasks.
Definition at line 66 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.cleanupCompleted(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.run().
tpe
final ThreadPoolExecutor denoptim.programs.fitnessevaluator.FPRunner.tpe package
Asynchronous tasks manager.
Definition at line 71 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), denoptim.programs.fitnessevaluator.FPRunner.run(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/fitnessevaluator/FPRunner.java