DENOPTIM: denoptim.graph.AttachmentPointTest Class Reference
denoptim.graph.AttachmentPointTest Class Reference
Unit test for DENOPTIMAttachmentPoint.
Public Member Functions
void testParsingofSdfAPString () throws Exception
void testGetEmbeddedAP () throws Exception
void testAvailableThrougout () throws Exception
void testGetEdbeUserThrougout () throws Exception
void testIsSrcInUser () throws Exception
void testGetLinkedAP () throws Exception
void testConstructorsAndSDFString () throws Exception
void testConstructorsAndSDFStringNoDirVec () throws Exception
void testSortAPs () throws Exception
void testSameAs ()
void testSameAs_DiffSrcAtm ()
void testSameAs_DiffAPClass () throws Exception
void testClone () throws Exception
void testHasSameSrcAtom () throws Exception
void testHasConnectedSrcAtom () throws Exception
Private Member Functions
void checkIdentityOfEmbeddedAP (int expectedMAtches, List< AttachmentPoint > deepAPs, Vertex v)
void checkAvailNT (int expN, int expNTm, int level, Vertex v)
void checkGetEdgeUserThroughput (Vertex v, List< Vertex > onion)
Private Attributes
final String APRULE = "MyRule"
final String APSUBRULE = "1"
final String APCLASS
final Point3d DIRVEC = new Point3d(1.1, 2.2, 3.3)
Detailed Description
Unit test for DENOPTIMAttachmentPoint.
Author
Marco Foscato
Definition at line 47 of file AttachmentPointTest.java.
Member Function Documentation
checkAvailNT()
void denoptim.graph.AttachmentPointTest.checkAvailNT (int expN, int expNTm, int level, Vertex v) private
Definition at line 323 of file AttachmentPointTest.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.graph.AttachmentPointTest.testAvailableThrougout().
checkGetEdgeUserThroughput()
void denoptim.graph.AttachmentPointTest.checkGetEdgeUserThroughput (Vertex v, List< Vertex > onion) private
Definition at line 375 of file AttachmentPointTest.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Edge.getSrcAP(), and denoptim.graph.Edge.getTrgAP().
Referenced by denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout().
checkIdentityOfEmbeddedAP()
void denoptim.graph.AttachmentPointTest.checkIdentityOfEmbeddedAP (int expectedMAtches, List< AttachmentPoint > deepAPs, Vertex v) private
Definition at line 261 of file AttachmentPointTest.java.
References denoptim.graph.Vertex.getAttachmentPoints(), and denoptim.graph.AttachmentPoint.getEmbeddedAP().
Referenced by denoptim.graph.AttachmentPointTest.testGetEmbeddedAP().
testAvailableThrougout()
void denoptim.graph.AttachmentPointTest.testAvailableThrougout () throws Exception
Definition at line 280 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.AttachmentPointTest.checkAvailNT(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.NONE, and denoptim.graph.Template.setInnerGraph().
testClone()
void denoptim.graph.AttachmentPointTest.testClone () throws Exception
Definition at line 594 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.AttachmentPoint.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.AttachmentPoint.getAtomPositionNumber(), denoptim.graph.AttachmentPoint.getDirectionVector(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.AttachmentPoint.getID(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.APClass.make(), and denoptim.graph.AttachmentPoint.setDirectionVector().
testConstructorsAndSDFString()
void denoptim.graph.AttachmentPointTest.testConstructorsAndSDFString () throws Exception
Definition at line 458 of file AttachmentPointTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.AttachmentPointTest.DIRVEC, denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getSingleAPStringSDF(), and denoptim.graph.APClass.make().
testConstructorsAndSDFStringNoDirVec()
void denoptim.graph.AttachmentPointTest.testConstructorsAndSDFStringNoDirVec () throws Exception
Definition at line 476 of file AttachmentPointTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.AttachmentPointTest.DIRVEC, denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getSingleAPStringSDF(), denoptim.graph.APClass.make(), denoptim.constants.DENOPTIMConstants.SEPARATORAPPROPAAP, and denoptim.graph.AttachmentPoint.toStringNoId().
testGetEdbeUserThrougout()
void denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout () throws Exception
Definition at line 341 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.AttachmentPointTest.checkGetEdgeUserThroughput(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.NONE, and denoptim.graph.Template.setInnerGraph().
testGetEmbeddedAP()
void denoptim.graph.AttachmentPointTest.testGetEmbeddedAP () throws Exception
Definition at line 104 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.AttachmentPointTest.checkIdentityOfEmbeddedAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.EmptyVertex.getAttachmentPoints(), denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.graph.Edge.getSrcAPThroughout(), denoptim.graph.Edge.getTrgAPThroughout(), denoptim.graph.Vertex.BBType.NONE, and denoptim.graph.Template.setInnerGraph().
testGetLinkedAP()
void denoptim.graph.AttachmentPointTest.testGetLinkedAP () throws Exception
Definition at line 433 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getLinkedAP(), and denoptim.graph.APClass.make().
testHasConnectedSrcAtom()
void denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom () throws Exception
Definition at line 680 of file AttachmentPointTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.AttachmentPoint.hasConnectedSrcAtom(), denoptim.graph.APClass.make(), denoptim.graph.Template.setInnerGraph(), and denoptim.graph.Vertex.setVertexId().
testHasSameSrcAtom()
void denoptim.graph.AttachmentPointTest.testHasSameSrcAtom () throws Exception
Definition at line 628 of file AttachmentPointTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.DGraph.addVertex(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.Fragment.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.hasSameSrcAtom(), denoptim.graph.APClass.make(), and denoptim.graph.Template.setInnerGraph().
testIsSrcInUser()
void denoptim.graph.AttachmentPointTest.testIsSrcInUser () throws Exception
Definition at line 408 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.isSrcInUser(), and denoptim.graph.APClass.make().
testParsingofSdfAPString()
void denoptim.graph.AttachmentPointTest.testParsingofSdfAPString () throws Exception
Definition at line 58 of file AttachmentPointTest.java.
References denoptim.graph.APClass.DEFAULTBT, denoptim.graph.Edge.BondType.DOUBLE, denoptim.graph.APClass.getBondType(), denoptim.graph.AttachmentPoint.processSdfString(), and denoptim.graph.Edge.BondType.UNDEFINED.
testSameAs()
void denoptim.graph.AttachmentPointTest.testSameAs ()
Definition at line 544 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.AttachmentPoint.compareTo(), denoptim.graph.Vertex.getAP(), and denoptim.graph.AttachmentPoint.sameAs().
testSameAs_DiffAPClass()
void denoptim.graph.AttachmentPointTest.testSameAs_DiffAPClass () throws Exception
Definition at line 578 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.APClass.make(), denoptim.graph.AttachmentPoint.sameAs(), and denoptim.graph.AttachmentPoint.setAPClass().
testSameAs_DiffSrcAtm()
void denoptim.graph.AttachmentPointTest.testSameAs_DiffSrcAtm ()
Definition at line 564 of file AttachmentPointTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Vertex.getAP(), and denoptim.graph.AttachmentPoint.sameAs().
testSortAPs()
void denoptim.graph.AttachmentPointTest.testSortAPs () throws Exception
Definition at line 500 of file AttachmentPointTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.AttachmentPointTest.APCLASS, denoptim.graph.AttachmentPointTest.DIRVEC, denoptim.graph.Vertex.getAP(), denoptim.graph.Fragment.getAttachmentPoints(), and denoptim.graph.APClass.make().
Member Data Documentation
APCLASS
final String denoptim.graph.AttachmentPointTest.APCLASS private
Initial value:
= APRULE
            + DENOPTIMConstants.SEPARATORAPPROPSCL + APSUBRULE
Definition at line 51 of file AttachmentPointTest.java.
Referenced by denoptim.graph.AttachmentPointTest.testClone(), denoptim.graph.AttachmentPointTest.testConstructorsAndSDFString(), denoptim.graph.AttachmentPointTest.testConstructorsAndSDFStringNoDirVec(), denoptim.graph.AttachmentPointTest.testGetLinkedAP(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), denoptim.graph.AttachmentPointTest.testHasSameSrcAtom(), denoptim.graph.AttachmentPointTest.testIsSrcInUser(), and denoptim.graph.AttachmentPointTest.testSortAPs().
APRULE
final String denoptim.graph.AttachmentPointTest.APRULE = "MyRule" private
Definition at line 49 of file AttachmentPointTest.java.
APSUBRULE
final String denoptim.graph.AttachmentPointTest.APSUBRULE = "1" private
Definition at line 50 of file AttachmentPointTest.java.
DIRVEC
final Point3d denoptim.graph.AttachmentPointTest.DIRVEC = new Point3d(1.1, 2.2, 3.3) private
Definition at line 53 of file AttachmentPointTest.java.
Referenced by denoptim.graph.AttachmentPointTest.testConstructorsAndSDFString(), denoptim.graph.AttachmentPointTest.testConstructorsAndSDFStringNoDirVec(), and denoptim.graph.AttachmentPointTest.testSortAPs().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/AttachmentPointTest.java