DENOPTIM: denoptim.programs.denovo.GAParametersTest Class Reference
denoptim.programs.denovo.GAParametersTest Class Reference
Unit test.
Public Member Functions
void testYesNoTrueFalseKeyword () throws Exception
void testInterpretationOfKeywords () throws Exception
void testLogging () throws Exception
Package Attributes
File tempDir
Private Attributes
final String SEP = System.getProperty("file.separator")
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 45 of file GAParametersTest.java.
Member Function Documentation
testInterpretationOfKeywords()
void denoptim.programs.denovo.GAParametersTest.testInterpretationOfKeywords () throws Exception
Definition at line 79 of file GAParametersTest.java.
References denoptim.programs.denovo.GAParameters.getMultiSiteMutationWeights(), and denoptim.programs.denovo.GAParameters.interpretKeyword().
testLogging()
void denoptim.programs.denovo.GAParametersTest.testLogging () throws Exception
Definition at line 104 of file GAParametersTest.java.
References denoptim.files.FileUtils.checkExists(), denoptim.files.FileUtils.createDirectory(), denoptim.programs.RunTimeParameters.ParametersType.GA_PARAMS, denoptim.programs.denovo.GAParameters.getDataDirectory(), denoptim.programs.RunTimeParameters.getLogFilePathname(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.programs.denovo.GAParameters.processParameters(), denoptim.io.DenoptimIO.readList(), denoptim.programs.RunTimeParameters.readParameterLine(), denoptim.programs.denovo.GAParametersTest.SEP, denoptim.programs.denovo.GAParameters.setWorkingDirectory(), denoptim.programs.RunTimeParameters.startProgramSpecificLogger(), and denoptim.programs.denovo.GAParametersTest.tempDir.
testYesNoTrueFalseKeyword()
void denoptim.programs.denovo.GAParametersTest.testYesNoTrueFalseKeyword () throws Exception
Definition at line 55 of file GAParametersTest.java.
References denoptim.programs.denovo.GAParameters.interpretKeyword(), and denoptim.programs.denovo.GAParameters.mutatedGraphFailedEvalTolerant.
Member Data Documentation
SEP
final String denoptim.programs.denovo.GAParametersTest.SEP = System.getProperty("file.separator") private
Definition at line 47 of file GAParametersTest.java.
Referenced by denoptim.programs.denovo.GAParametersTest.testLogging().
tempDir
File denoptim.programs.denovo.GAParametersTest.tempDir package
Definition at line 50 of file GAParametersTest.java.
Referenced by denoptim.programs.denovo.GAParametersTest.testLogging().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/programs/denovo/GAParametersTest.java