DENOPTIM: denoptim.graph.VertexQueryTest Class Reference
denoptim.graph.VertexQueryTest Class Reference
Unit tests for VertexQuery#matches(Vertex).
Public Member Functions
void setUp () throws DENOPTIMException
void testMatchesAllNullCriteria ()
void testMatchesVertexId ()
void testMatchesVertexType ()
void testMatchesBuildingBlockTypeAndId ()
void testMatchesLevel ()
void testMatchesIncomingEdgeQuery () throws DENOPTIMException
void testMatchesOutgoingEdgeQuery () throws DENOPTIMException
void testMatchesIncomingAndOutgoingEdgeQueries () throws DENOPTIMException
void testMatchesAttachmentPointQueries () throws DENOPTIMException
void testEmptyEdgeQueryFiltersVertices ()
void testFindVerticesUsesMatches ()
Private Attributes
DGraph graph
Detailed Description
Unit tests for VertexQuery#matches(Vertex).
Definition at line 32 of file VertexQueryTest.java.
Member Function Documentation
setUp()
void denoptim.graph.VertexQueryTest.setUp () throws DENOPTIMException
Definition at line 37 of file VertexQueryTest.java.
References denoptim.graph.VertexQueryTest.graph, and denoptim.graph.DGraphTest.makeTestGraphA2().
testEmptyEdgeQueryFiltersVertices()
void denoptim.graph.VertexQueryTest.testEmptyEdgeQueryFiltersVertices ()
Definition at line 209 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexList(), denoptim.graph.VertexQueryTest.graph, and denoptim.graph.VertexQuery.matches().
testFindVerticesUsesMatches()
void denoptim.graph.VertexQueryTest.testFindVerticesUsesMatches ()
Definition at line 230 of file VertexQueryTest.java.
References denoptim.graph.DGraph.findVertices(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.VertexQuery.matches(), and denoptim.graph.Vertex.BBType.UNDEFINED.
testMatchesAllNullCriteria()
void denoptim.graph.VertexQueryTest.testMatchesAllNullCriteria ()
Definition at line 45 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexList(), denoptim.graph.VertexQueryTest.graph, and denoptim.graph.VertexQuery.matches().
testMatchesAttachmentPointQueries()
void denoptim.graph.VertexQueryTest.testMatchesAttachmentPointQueries () throws DENOPTIMException
Definition at line 185 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.VertexQuery.matches().
testMatchesBuildingBlockTypeAndId()
void denoptim.graph.VertexQueryTest.testMatchesBuildingBlockTypeAndId ()
Definition at line 86 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.VertexQuery.matches(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
testMatchesIncomingAndOutgoingEdgeQueries()
void denoptim.graph.VertexQueryTest.testMatchesIncomingAndOutgoingEdgeQueries () throws DENOPTIMException
Definition at line 163 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.VertexQuery.matches().
testMatchesIncomingEdgeQuery()
void denoptim.graph.VertexQueryTest.testMatchesIncomingEdgeQuery () throws DENOPTIMException
Definition at line 125 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.VertexQuery.matches().
testMatchesLevel()
void denoptim.graph.VertexQueryTest.testMatchesLevel ()
Definition at line 105 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, and denoptim.graph.VertexQuery.matches().
testMatchesOutgoingEdgeQuery()
void denoptim.graph.VertexQueryTest.testMatchesOutgoingEdgeQuery () throws DENOPTIMException
Definition at line 144 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, denoptim.graph.APClass.make(), and denoptim.graph.VertexQuery.matches().
testMatchesVertexId()
void denoptim.graph.VertexQueryTest.testMatchesVertexId ()
Definition at line 58 of file VertexQueryTest.java.
References denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.VertexQueryTest.graph, and denoptim.graph.VertexQuery.matches().
testMatchesVertexType()
void denoptim.graph.VertexQueryTest.testMatchesVertexType ()
Definition at line 71 of file VertexQueryTest.java.
References denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.VertexQueryTest.graph, and denoptim.graph.VertexQuery.matches().
Member Data Documentation
graph
DGraph denoptim.graph.VertexQueryTest.graph private
Definition at line 34 of file VertexQueryTest.java.
Referenced by denoptim.graph.VertexQueryTest.setUp(), denoptim.graph.VertexQueryTest.testEmptyEdgeQueryFiltersVertices(), denoptim.graph.VertexQueryTest.testFindVerticesUsesMatches(), denoptim.graph.VertexQueryTest.testMatchesAllNullCriteria(), denoptim.graph.VertexQueryTest.testMatchesAttachmentPointQueries(), denoptim.graph.VertexQueryTest.testMatchesBuildingBlockTypeAndId(), denoptim.graph.VertexQueryTest.testMatchesIncomingAndOutgoingEdgeQueries(), denoptim.graph.VertexQueryTest.testMatchesIncomingEdgeQuery(), denoptim.graph.VertexQueryTest.testMatchesLevel(), denoptim.graph.VertexQueryTest.testMatchesOutgoingEdgeQuery(), denoptim.graph.VertexQueryTest.testMatchesVertexId(), and denoptim.graph.VertexQueryTest.testMatchesVertexType().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/VertexQueryTest.java