DENOPTIM: denoptim.graph.Vertex Class Reference
denoptim.graph.Vertex Class Reference abstract
A vertex is a data structure that has an identity and holds a list of AttachmentPoints.
Classes
enum BBType
The type of building block.
class DENOPTIMVertexDeserializer
enum VertexType
Flag declaring the type of Vertex implementation.
Public Member Functions
Vertex (VertexType vertexType)
Constructor for an empty vertex.
Vertex (VertexType vertexType, long id)
Constructor for an identified vertex without attachment points.
abstract List< AttachmentPoint > getAttachmentPoints ()
List< AttachmentPoint > getAPsWithAPClassStartingWith (String root)
Finds only APs that have APClass starting with the given string.
void setAsRCV (boolean isRCV)
void setVertexId (long vertexId2)
long getVertexId ()
int getBuildingBlockId ()
Returns the index of the building block that should correspond to the position of the building block in the library of building blocks of its kind.
void setBuildingBlockId (int buildingBlockId)
Vertex.BBType getBuildingBlockType ()
void setBuildingBlockType (Vertex.BBType buildingBlockType)
abstract List< SymmetricAPs > getSymmetricAPSets ()
SymmetricAPs getSymmetricAPs (AttachmentPoint ap)
For the given attachment point index locate the symmetric partners i.e.
int getNumberOfAPs ()
int getFreeAPCount ()
ArrayList< AttachmentPoint > getFreeAPThroughout ()
Gets attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
int getFreeAPCountThroughout ()
Counts the number of attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
ArrayList< AttachmentPoint > getCappedAPs ()
Gets attachment points that are used by capping groups.
ArrayList< AttachmentPoint > getCappedAPsThroughout ()
Gets attachment points that are used by capping groups throughout the graph levels, i.e., checks also across the inner graph template boundary.
int getCappedAPCountThroughout ()
Counts the number of attachment points that are used by BBType#CAP vertex.
boolean hasFreeAP ()
boolean isRCV ()
boolean isAromaticBridge ()
Checks if this vertex is meant to be a piece of an aromatic system.
boolean isConnectedToAromaticBridge ()
Checks if this vertex is connected to any vertex meant to be a piece of an aromatic system.
boolean hasSymmetricAP ()
String toString ()
Produces a human readable, short string to represent the vertex by its vertex ID, building block ID (1-based), building block type, and level in the graph (if any).
void cleanup ()
abstract Vertex clone ()
Returns a deep-copy of this vertex.
boolean sameAs (Vertex other)
Compares this and another vertex ignoring vertex IDs.
boolean sameAs (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
boolean sameVertexFeatures (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
abstract int getHeavyAtomsCount ()
abstract boolean containsAtoms ()
abstract IAtomContainer getIAtomContainer ()
abstract IAtomContainer getIAtomContainer (Logger logger, Randomizer rng, boolean removeUsedRCAs, boolean rebuild)
Method meant to trigger regeneration of the chemical representation, typically needed to drop a low quality structure that is good enough for most cheminformatic tasks, and replace it with a better quality structure that is suitable to be fed to molecular modeling tasks.
ArrayList< APClass > getAllAPClasses ()
Returns the list of all APClasses present on this vertex.
ArrayList< APClass > getAllAvailableAPClasses ()
Returns the list of all APClasses present on free attachment point on this vertex.
void resetGraphOwner ()
void setGraphOwner (DGraph owner)
DGraph getGraphOwner ()
Returns the graph this vertex belongs to or null.
List< Vertex > getMutationSites ()
A list of mutation sites from within this vertex.
abstract List< Vertex > getMutationSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this vertex.
void setMutationTypes (List< MutationType > lst)
boolean removeMutationType (MutationType mt)
Removes the specified mutation type.
List< MutationType > getMutationTypes ()
Returns the list of mutation types.
List< MutationType > getMutationTypes (List< MutationType > excludedTypes)
Returns the list of mutation types.
AttachmentPoint getAP (int i)
Get attachment point i on this vertex.
AttachmentPoint getAPWithId (int i)
Get attachment point that has the given identifier, or null.
int getIndexOfAP (AttachmentPoint ap)
Returns the position of the given AP in the list of APs of this vertex.
Edge getEdgeToParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the edge that has this vertex as the target, i.e., the edge to the parent vertex.
Vertex getParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the vertex which is the source of the edge in which this vertex is the target.
ArrayList< AttachmentPoint > getAPsFromChildren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of attachment point on child vertices that form an edge with any of the APs of this vertex.
ArrayList< Vertex > getChildrenThroughout ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
ArrayList< Vertex > getChilddren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
void setUniquefyingProperty (String key)
Add the given key among the properties that are checked for equality when comparing vertices with the Vertex#sameAs(Vertex, StringBuilder) method.
Map< Object, Object > getProperties ()
boolean hasProperty (Object property)
Object getProperty (Object property)
void setProperty (Object key, Object property)
void removeProperty (Object key)
void setProperties (Map< Object, Object > properties)
VertexType getVertexType ()
Returns the value of the vertex type.
String[] getPathIDs (AttachmentPoint apA, AttachmentPoint apB)
Produces a pair of strings that identify the "path" between two given attachment points.
boolean connectedTo (Vertex other)
Checks if this and another vertex are directly connected by an edge within the same graph recursion level, i.e., both vertices must belong to the same graph.
Edge getEdgeWith (Vertex other)
Finds the edge between this and the other vertex, if it exists.
Static Public Member Functions
static Vertex newVertexFromLibrary (int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException
Builds a new molecular fragment kind of vertex.
static Vertex newVertexFromLibrary (long vertexId, int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException
Make a new vertex that is a copy of a vertex in the fragment space.
static Vertex fromJson (String json)
static Vertex convertIACToVertex (IAtomContainer iac, Vertex.BBType bbt) throws DENOPTIMException
Processes an IAtomContainer and builds a Vertex that is an instance of Fragment.
static Vertex parseVertexFromSDFFormat (IAtomContainer mol, Gson reader, BBType bbt) throws DENOPTIMException
Created a Vertex from the SDF representation, i.e., from an IAtomContainer.
Protected Member Functions
abstract void setSymmetricAPSets (List< SymmetricAPs > sAPs)
abstract void addSymmetricAPSet (SymmetricAPs symAPs)
int getUniqueAPIndex ()
List< MutationType > getUnfilteredMutationTypes ()
Returns the mutation types that are constitutionally configures for this vertex irrespectively on the graph or the context in which this vertex is included.
Map< Object, Object > copyStringBasedProperties ()
Copies all the string-based properties and properties defined in the Vertex#uniquefyingPropertyKeys set.
Protected Attributes
int buildingBlockId = -99
Index of this building block in the library of building blocks, or negative if this vertex is not part of a library.
BBType buildingBlockType = Vertex.BBType.UNDEFINED
Map< Object, Object > properties
Map of customizable properties.
Set< String > uniquefyingPropertyKeys = new HashSet<String>()
List of properties required to make Vertex#sameAs(Vertex, StringBuilder) method return false when property values differ.
final VertexType vertexType
Field distinguishing implementations of Vertex when deserializing JSON representations.
Private Attributes
DGraph owner
Graph that includes this vertex.
long vertexId
Unique identifier associated with the vertex instance.
boolean isRCV
List< MutationType > allowedMutationTypes
List of mutations that we can perform on this vertex.
Detailed Description
A vertex is a data structure that has an identity and holds a list of AttachmentPoints.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 61 of file Vertex.java.
Constructor & Destructor Documentation
Vertex() [1/2]
denoptim.graph.Vertex.Vertex (VertexType vertexType)
Constructor for an empty vertex.
Definition at line 184 of file Vertex.java.
References denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.Vertex.isRCV, denoptim.graph.Vertex.vertexId, and denoptim.graph.Vertex.vertexType.
Vertex() [2/2]
denoptim.graph.Vertex.Vertex (VertexType vertexType, long id)
Constructor for an identified vertex without attachment points.
Parameters
id the VertedID of the vertex to construct. Note that this ID should be unique within a graph. To generate unique IDs either use GraphUtils#getUniqueVertexIndex() or use constructor DENOPTIMVertex().
Definition at line 200 of file Vertex.java.
References denoptim.graph.Vertex.vertexId, and denoptim.graph.Vertex.vertexType.
Member Function Documentation
addSymmetricAPSet()
abstract void denoptim.graph.Vertex.addSymmetricAPSet (SymmetricAPs symAPs) abstract protected
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.graph.Vertex.DENOPTIMVertexDeserializer.deserialize().
cleanup()
void denoptim.graph.Vertex.cleanup ()
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 640 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), and denoptim.graph.Vertex.getSymmetricAPSets().
clone()
abstract Vertex denoptim.graph.Vertex.clone () abstract
Returns a deep-copy of this vertex.
Subclasses override this method.
Returns
a deep-copy
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.clone(), denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.graph.rings.PathSubGraph.findPath(), denoptim.ga.EAUtils.getUsableAliphaticBridges(), denoptim.ga.EAUtils.getUsableAromaticBridges(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.gui.VertexAsGraphViewPanel.loadVertexStructure(), denoptim.graph.rings.PathSubGraph.PathSubGraph(), and denoptim.gui.GraphVertexMolViewerPanel.visualizeVertexInNestedViewer().
connectedTo()
boolean denoptim.graph.Vertex.connectedTo (Vertex other)
Checks if this and another vertex are directly connected by an edge within the same graph recursion level, i.e., both vertices must belong to the same graph.
Parameters
other
Returns
true
Definition at line 1495 of file Vertex.java.
References denoptim.graph.Vertex.getParent().
containsAtoms()
abstract boolean denoptim.graph.Vertex.containsAtoms () abstract
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), and denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer().
convertIACToVertex()
static Vertex denoptim.graph.Vertex.convertIACToVertex (IAtomContainer iac, Vertex.BBType bbt) throws DENOPTIMException static
Processes an IAtomContainer and builds a Vertex that is an instance of Fragment.
This method does not consider any JSON definition that might be embedded in the container properties. This because this method is meant to convert an IAtomContainer with AttachmentPoints defined in the IAtomContainer's properties.
Parameters
iac the atom containers.
bbt the type of building block.
Returns
the vertex.
Exceptions
DENOPTIMException if the atom container could not be converted into a Fragment.
Definition at line 1433 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.rings.RingClosingAttractor.RCAAPCLASSSET, and denoptim.graph.Vertex.setAsRCV().
Referenced by denoptim.graph.Vertex.parseVertexFromSDFFormat().
copyStringBasedProperties()
Map< Object, Object > denoptim.graph.Vertex.copyStringBasedProperties () protected
Copies all the string-based properties and properties defined in the Vertex#uniquefyingPropertyKeys set.
Returns
the map of cloned properties.
Definition at line 1262 of file Vertex.java.
References denoptim.graph.Vertex.properties, and denoptim.graph.Vertex.uniquefyingPropertyKeys.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), and denoptim.graph.Template.clone().
fromJson()
static Vertex denoptim.graph.Vertex.fromJson (String json) static
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Definition at line 1290 of file Vertex.java.
References denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.graph.Vertex.parseVertexFromSDFFormat(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile(), denoptim.graph.VertexTest.testFromToJSON_minimal(), denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), and denoptim.json.DENOPTIMgsonTest.testTemplateSerialization().
getAllAPClasses()
ArrayList< APClass > denoptim.graph.Vertex.getAllAPClasses ()
Returns the list of all APClasses present on this vertex.
Returns
the list of APClassess
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 793 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.fragspace.FragmentSpace.getCompatibleCappingFragments(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses(), denoptim.graph.Vertex.isAromaticBridge(), and denoptim.graph.VertexTest.testClone().
getAllAvailableAPClasses()
ArrayList< APClass > denoptim.graph.Vertex.getAllAvailableAPClasses ()
Returns the list of all APClasses present on free attachment point on this vertex.
Returns
the list of APClassess
Definition at line 815 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
getAP()
AttachmentPoint denoptim.graph.Vertex.getAP (int i)
Get attachment point i on this vertex.
Parameters
i index of attachment point on this vertex
Returns
attachment point i on this vertex
Definition at line 1008 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.graph.DGraph.addCappingGroups(), denoptim.ga.GraphOperations.addFusedRing(), denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.appendGraphOnAP(), denoptim.ga.EAUtils.appendVertexesToGraphFollowingEdges(), denoptim.ga.GraphOperations.attachFragmentInClosableChain(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.ga.GraphOperations.extendGraph(), denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.graph.DGraph.fixEdgeDirections(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.graph.TemplateTest.getNestedTemplate(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.TemplateTest.getTemplateDeepTest(), denoptim.graph.TemplateTest.getTestAmideTemplate(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.graph.Template.getTestTemplate(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.fragmenter.ClusterableFragment.getTransformedCopy(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.graph.FragmentTest.makeFragment(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphA(), denoptim.graph.rings.RingSizeManagerTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.graph.rings.PathSubGraph.PathSubGraph(), denoptim.ga.GraphOperations.performCrossover(), denoptim.ga.EAUtilsTest.prepare(), denoptim.ga.XoverSite.projectToClonedGraphs(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.graph.DGraph.replaceVertex(), denoptim.graph.Vertex.sameVertexFeatures(), denoptim.graph.EdgeTest.setUpClass(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained(), denoptim.graph.AttachmentPointTest.testAvailableThrougout(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.graph.AttachmentPointTest.testClone(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.fragmenter.FragmentClustererTest.testCluster(), denoptim.graph.AttachmentPointTest.testConstructorsAndSDFString(), denoptim.graph.AttachmentPointTest.testConstructorsAndSDFStringNoDirVec(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.FragmentTest.testConversionToIAC(), denoptim.ga.EAUtilsTest.testCrowdingProbability(), denoptim.graph.RelatedAPPairTest.testEquals(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsCorrectNumberOfAPs(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout(), denoptim.graph.AttachmentPointTest.testGetEmbeddedAP(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass(), denoptim.graph.DGraphTest.testGetInterfaceAPs(), denoptim.graph.AttachmentPointTest.testGetLinkedAP(), denoptim.graph.DGraphTest.testGetSubgraphAPs(), denoptim.fragmenter.ClusterableFragmentTest.testGetTransformedCopy(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), denoptim.graph.AttachmentPointTest.testHasSameSrcAtom(), denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.FragmentIsomorphismInspectorTest.testIsomorphismExists(), denoptim.graph.AttachmentPointTest.testIsSrcInUser(), denoptim.graph.DGraphTest.testRemoveCapping(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testReplaceSubGraph(), denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate(), denoptim.graph.TemplateTest.testSameAPClass(), denoptim.graph.AttachmentPointTest.testSameAs(), denoptim.graph.AttachmentPointTest.testSameAs_DiffAPClass(), denoptim.graph.DGraphTest.testSameAs_DiffRings(), denoptim.graph.AttachmentPointTest.testSameAs_DiffSrcAtm(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_DiffVertex(), denoptim.graph.DGraphTest.testSameAs_DisorderRings(), denoptim.graph.DGraphTest.testSameAs_Equal(), denoptim.graph.DGraphTest.testSameAs_SameRings(), denoptim.graph.DGraphTest.testSameAs_SameSymmSet(), denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion(), denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex(), denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs(), denoptim.graph.AttachmentPointTest.testSortAPs(), denoptim.graph.EdgeTest.testUndirectedComparison(), denoptim.graph.UndirectedEdgeRelationTest.testUndirectedComparison(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
getAPsFromChildren()
ArrayList< AttachmentPoint > denoptim.graph.Vertex.getAPsFromChildren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of attachment point on child vertices that form an edge with any of the APs of this vertex.
Searches also beyond template boundaries, i.e., an AP can be free in the graph owning this vertex and be projected of the surface of the template that embeds such graph, so that the apparently free AP can be used in the outside of the template (a.k.a., beyond template's boundaries).
Returns
the list of APs on child vertices (can be empty list, but not null)
Definition at line 1114 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Edge.getSrcAPThroughout(), and denoptim.graph.Edge.getTrgAPThroughout().
getAPsWithAPClassStartingWith()
List< AttachmentPoint > denoptim.graph.Vertex.getAPsWithAPClassStartingWith (String root)
Finds only APs that have APClass starting with the given string.
Parameters
root the beginning of the APClass string to search for.
Returns
a list of APs that belong to this vertex and have APClass starting with the given string.
Definition at line 261 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.ga.GraphOperations.addFusedRing(), and denoptim.graph.VertexTest.testGetAPsWithAPClassStartingWith().
getAPWithId()
AttachmentPoint denoptim.graph.Vertex.getAPWithId (int i)
Get attachment point that has the given identifier, or null.
Parameters
i the identifier of the attachment point to fetch.
Returns
the attachment point with the given ID, or null
Definition at line 1019 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.graph.Vertex.DENOPTIMVertexDeserializer.deserialize().
getAttachmentPoints()
abstract List< AttachmentPoint > denoptim.graph.Vertex.getAttachmentPoints () abstract
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.fragspace.APMapFinder.APMapFinder(), denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.ga.EAUtils.appendVertexesToGraphFollowingEdges(), denoptim.graph.DGraph.EdgeFinder.apply(), denoptim.ga.GraphOperationsTest.buildGraph(), denoptim.graph.AttachmentPointTest.checkAvailNT(), denoptim.graph.AttachmentPointTest.checkGetEdgeUserThroughput(), denoptim.graph.AttachmentPointTest.checkIdentityOfEmbeddedAP(), denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.graph.Vertex.cleanup(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.graph.Vertex.convertIACToVertex(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.rings.RingSizeManager.evaluateRCVPair(), denoptim.graph.rings.PathSubGraph.findPath(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.graph.Vertex.getAllAPClasses(), denoptim.graph.Vertex.getAllAvailableAPClasses(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getAPClassForFragment(), denoptim.graph.Vertex.getAPsFromChildren(), denoptim.graph.Vertex.getAPsWithAPClassStartingWith(), denoptim.graph.Vertex.getAPWithId(), denoptim.graph.Vertex.getCappedAPs(), denoptim.graph.Vertex.getCappedAPsThroughout(), denoptim.graph.Vertex.getChilddren(), denoptim.graph.Vertex.getChildrenThroughout(), denoptim.ga.EAUtils.getCrowdedness(), denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.Vertex.getEdgeWith(), denoptim.graph.Vertex.getFreeAPCount(), denoptim.graph.Vertex.getFreeAPThroughout(), denoptim.graph.Vertex.getIndexOfAP(), denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.Vertex.getParent(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.graph.Vertex.hasFreeAP(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.setScaffold(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsAPsWithTemplateAsOwner(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates(), denoptim.gui.VertexAsTwoDimStructureViewPanel.TwoDimStructurePanel.TwoDimStructurePanel(), denoptim.gui.VertexAsGraphViewPanel.updateAPsMapAndTable(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
getBuildingBlockId()
int denoptim.graph.Vertex.getBuildingBlockId ()
Returns the index of the building block that should correspond to the position of the building block in the library of building blocks of its kind.
Since the index is saved and disconnected from the library, changes to the library my make this value inconsistent with the actual position of this building block in the library.
Returns
the presumed index of this building block in the library of building blocks
Definition at line 305 of file Vertex.java.
References denoptim.graph.Vertex.buildingBlockId.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.gui.GraphViewerPanel.VertexLabelTransformer.apply(), denoptim.ga.EAUtils.buildGraph(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.Edge.compareAsUndirected(), denoptim.ga.GraphOperations.extendLink(), denoptim.ga.GraphOperations.getFragmentForClosableChain(), denoptim.graph.Template.getPathIDs(), denoptim.graph.Vertex.getPathIDs(), denoptim.ga.GraphOperations.getRCVForSrcAp(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.simplified.UndirectedEdge.makeInvariant(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.Template.sameAs(), denoptim.graph.Vertex.sameVertexFeatures(), denoptim.ga.GraphOperations.substituteLink(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), and denoptim.graph.Fragment.toString().
getBuildingBlockType()
Vertex.BBType denoptim.graph.Vertex.getBuildingBlockType ()
Definition at line 319 of file Vertex.java.
References denoptim.graph.Vertex.buildingBlockType.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.Edge.compareAsUndirected(), denoptim.ga.GraphOperations.extendLink(), denoptim.graph.Vertex.getCappedAPs(), denoptim.graph.Vertex.getCappedAPsThroughout(), denoptim.ga.GraphOperations.getFragmentForClosableChain(), denoptim.graph.EmptyVertex.getMutationSites(), denoptim.graph.Fragment.getMutationSites(), denoptim.graph.Template.getMutationSites(), denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Template.getMutationTypes(), denoptim.graph.Template.getPathIDs(), denoptim.graph.Vertex.getPathIDs(), denoptim.ga.GraphOperations.getRCVForSrcAp(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.gui.GraphViewerPanel.JVertex.JVertex(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.graph.simplified.UndirectedEdge.makeInvariant(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.Vertex.sameVertexFeatures(), denoptim.ga.GraphOperations.substituteLink(), denoptim.graph.FragmentTest.testClone(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), and denoptim.graph.Fragment.toString().
getCappedAPCountThroughout()
int denoptim.graph.Vertex.getCappedAPCountThroughout ()
Counts the number of attachment points that are used by BBType#CAP vertex.
This method does account for embedding of the vertex in a template, i.e., APs can be available in the graph owning this vertex, but if the graph is itself the inner graph of a template, the AP is then projected on the template's surface and used to make an edge that uses the template as a single vertex.
Returns
the number of APs of this vertex that are used to bind a BBType#CAP vertex, whether within the graph owning this vertex (if any) or within a graph owning the template embedding the graph that owns this vertex.
Definition at line 514 of file Vertex.java.
References denoptim.graph.Vertex.getCappedAPsThroughout().
Referenced by denoptim.graph.Vertex.getMutationTypes(), and denoptim.graph.DGraph.removeChainUpToBranching().
getCappedAPs()
ArrayList< AttachmentPoint > denoptim.graph.Vertex.getCappedAPs ()
Gets attachment points that are used by capping groups.
This method does NOT account for embedding of the vertex in a template, i.e., APs can be available in the graph owning this vertex, but if the graph is itself the inner graph of a template, the AP is then projected on the template's surface and can be used. To account for this possibility use Vertex#getCappedAPsThroughout().
Returns
the APs of this vertex that are used to bind a BBType#CAP vertex.
Definition at line 449 of file Vertex.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.AttachmentPoint.getLinkedAP(), and denoptim.graph.AttachmentPoint.getOwner().
Referenced by denoptim.graph.Vertex.getMutationTypes().
getCappedAPsThroughout()
ArrayList< AttachmentPoint > denoptim.graph.Vertex.getCappedAPsThroughout ()
Gets attachment points that are used by capping groups throughout the graph levels, i.e., checks also across the inner graph template boundary.
This method does account for embedding of the vertex in a template, i.e., APs can be available in the graph owning this vertex, but if the graph is itself the inner graph of a template, the AP is then projected on the template's surface and used to make an edge that uses the template as a single vertex. To ignore this possibility and consider only edges that belong to the graph owning this vertex, use Vertex#getCappedAPs().
Returns
the APs of this vertex that are used to bind a BBType#CAP vertex, whether within the graph owning this vertex (if any) or within a graph owning the template embedding the graph that owns this vertex.
Definition at line 483 of file Vertex.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.AttachmentPoint.getLinkedAPThroughout(), and denoptim.graph.AttachmentPoint.getOwner().
Referenced by denoptim.graph.Vertex.getCappedAPCountThroughout().
getChilddren()
ArrayList< Vertex > denoptim.graph.Vertex.getChilddren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
Only the directly connected children are considered (no recursion). This method does not cross template boundaries, thus all children belong to the same graph.
Returns
the list of child vertices (can be empty list, but not null)
Definition at line 1173 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Edge.getSrcAP(), and denoptim.graph.Edge.getTrgAP().
Referenced by denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.graph.DGraph.getChildVertices(), denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Template.getMutationTypes(), denoptim.ga.GraphOperations.performMutation(), denoptim.graph.DGraph.removeChainUpToBranching(), and denoptim.graph.DGraph.replaceSubGraph().
getChildrenThroughout()
ArrayList< Vertex > denoptim.graph.Vertex.getChildrenThroughout ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
Only the directly connected children are considered (no recursion). This method does cross template boundaries, thus it includes also children belonging to uprooted graph, but does not get into embedded graph at the child side, i.e., each child is the outermost recursion levels.
Returns
the list of child vertices (can be empty list, but not null)
Definition at line 1145 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.graph.Edge.getTrgAP().
Referenced by denoptim.graph.DGraph.removeChainUpToBranching().
getEdgeToParent()
Edge denoptim.graph.Vertex.getEdgeToParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the edge that has this vertex as the target, i.e., the edge to the parent vertex.
We assume there is only one such edge.
Returns
the edge to the parent.
Definition at line 1060 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), and denoptim.graph.Edge.getTrgAP().
Referenced by denoptim.graph.rings.RingSizeManager.addRingClosingBond(), denoptim.graph.DGraph.EdgeFinder.apply(), denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.graph.rings.RingSizeManager.evaluateRCVPair(), denoptim.graph.DGraph.getAPOnLeftVertexID(), denoptim.graph.DGraph.getEdgeWithParent(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.graph.DGraph.getParent(), denoptim.graph.rings.RandomCombOfRingsIterator.next(), and denoptim.graph.DGraph.removeChainUpToBranching().
getEdgeWith()
Edge denoptim.graph.Vertex.getEdgeWith (Vertex other)
Finds the edge between this and the other vertex, if it exists.
Parameters
other the vertex we expect to be linked to this vertex.
Returns
the edge or null if no connection exists between the two.
Definition at line 1507 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.graph.Vertex.owner.
Referenced by denoptim.graph.DGraph.removeChainUpToBranching().
getFreeAPCount()
int denoptim.graph.Vertex.getFreeAPCount ()
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 375 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment(), and denoptim.graph.TemplateTest.testClone().
getFreeAPCountThroughout()
int denoptim.graph.Vertex.getFreeAPCountThroughout ()
Counts the number of attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
This method does account for embedding of the vertex in a template, i.e., APs can be available in the graph owning this vertex, but if the graph is itself the inner graph of a template, the AP is then projected on the template's surface and used to make an edge that uses the template as a single vertex. To ignore this possibility and consider only edges that belong to the graph owning this vertex, use Vertex#getFreeAPCount().
Returns
the number of APs that are not used by any edge, whether within the graph owning this vertex (if any) or within a graph owning the template embedding the graph that owns this vertex.
Definition at line 431 of file Vertex.java.
References denoptim.graph.Vertex.getFreeAPThroughout().
Referenced by denoptim.graph.Vertex.getMutationTypes(), and denoptim.graph.DGraph.removeChainUpToBranching().
getFreeAPThroughout()
ArrayList< AttachmentPoint > denoptim.graph.Vertex.getFreeAPThroughout ()
Gets attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
This method does account for embedding of the vertex in a template, i.e., APs can be available in the graph owning this vertex, but if the graph is itself the inner graph of a template, the AP is then projected on the template's surface and used to make an edge that uses the template as a single vertex. To ignore this possibility and consider only edges that belong to the graph owning this vertex, use Vertex#getFreeAPCount().
Returns
the APs of this vertex that are not used by any edge, whether within the graph owning this vertex (if any) or within a graph owning the template embedding the graph that owns this vertex.
Definition at line 403 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.Vertex.getFreeAPCountThroughout(), and denoptim.graph.DGraph.removeSingleVertexAndWeld().
getGraphOwner()
DGraph denoptim.graph.Vertex.getGraphOwner ()
Returns the graph this vertex belongs to or null.
Returns
the graph this vertex belongs to or null.
Definition at line 852 of file Vertex.java.
References denoptim.graph.Vertex.owner.
Referenced by denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.fragspace.APMapFinder.APMapFinder(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.EAUtils.getCrowdedness(), denoptim.graph.AttachmentPoint.getEdgeUserThroughout(), denoptim.graph.DGraph.getEmbeddingPath(), denoptim.utils.GraphUtils.getLabel(), denoptim.graph.DGraph.getOutermostGraphOwner(), denoptim.graph.AttachmentPoint.isAvailableThroughout(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.ga.GraphOperations.processPermutationOfEndPoints(), denoptim.graph.Template.removeProjectionOfInnerAP(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.setScaffold(), and denoptim.graph.DGraphTest.testRemoveCapping().
getHeavyAtomsCount()
abstract int denoptim.graph.Vertex.getHeavyAtomsCount () abstract
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.ga.GraphOperations.extendGraph(), and denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol().
getIAtomContainer() [1/2]
abstract IAtomContainer denoptim.graph.Vertex.getIAtomContainer () abstract
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.fragmenter.FragmenterTools.getMWSlotIdentifier(), denoptim.gui.GUIVertexInspector.initialize(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.TwoDimStructurePanel.TwoDimStructurePanel().
getIAtomContainer() [2/2]
abstract IAtomContainer denoptim.graph.Vertex.getIAtomContainer (Logger logger, Randomizer rng, boolean removeUsedRCAs, boolean rebuild) abstract
Method meant to trigger regeneration of the chemical representation, typically needed to drop a low quality structure that is good enough for most cheminformatic tasks, and replace it with a better quality structure that is suitable to be fed to molecular modeling tasks.
tasks,
Parameters
logger
rng
removeUsedRCAs
rebuild
Returns
the generated structure
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
getIndexOfAP()
int denoptim.graph.Vertex.getIndexOfAP (AttachmentPoint ap)
Returns the position of the given AP in the list of APs of this vertex.
Parameters
ap the AP to find in the list of APs
Returns
the index (0-n) of ap or -1 if that AP does not belong to this vertex.
Definition at line 1037 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.graph.DGraph.clone(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.Template.getPathIDs(), denoptim.graph.Vertex.getPathIDs(), denoptim.graph.Edge.getSrcAPID(), denoptim.fragmenter.ClusterableFragment.getTransformedCopy(), and denoptim.graph.Edge.getTrgAPID().
getMutationSites() [1/2]
List< Vertex > denoptim.graph.Vertex.getMutationSites ()
A list of mutation sites from within this vertex.
Returns
the list of vertices that allow any mutation type.
Definition at line 863 of file Vertex.java.
References denoptim.graph.Vertex.getMutationSites().
Referenced by denoptim.graph.Vertex.getMutationSites(), denoptim.graph.Template.getMutationSites(), and denoptim.graph.VertexTest.testGetMutationSites().
getMutationSites() [2/2]
abstract List< Vertex > denoptim.graph.Vertex.getMutationSites (List< MutationType > ignoredTypes) abstract
A list of mutation sites from within this vertex.
Parameters
ignoredTypes a collection of mutation types to ignore. vertices that allow only ignored types of mutation will not be considered mutation sites.
Returns
the list of vertices that allow any non-ignored mutation type.
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
getMutationTypes() [1/2]
List< MutationType > denoptim.graph.Vertex.getMutationTypes ()
Returns the list of mutation types.
Returns
the list of mutation types.
Definition at line 919 of file Vertex.java.
References denoptim.graph.Vertex.getMutationTypes().
Referenced by denoptim.graph.EmptyVertex.getMutationSites(), denoptim.graph.Fragment.getMutationSites(), denoptim.graph.Template.getMutationSites(), and denoptim.graph.Vertex.getMutationTypes().
getMutationTypes() [2/2]
List< MutationType > denoptim.graph.Vertex.getMutationTypes (List< MutationType > excludedTypes)
Returns the list of mutation types.
Parameters
excludedTypes list of mutation types to purge from before returning the list.
Returns
the purged list of mutation types.
Reimplemented in denoptim.graph.Template.
Definition at line 932 of file Vertex.java.
References denoptim.utils.MutationType.ADDFUSEDRING, denoptim.utils.MutationType.ADDLINK, denoptim.utils.MutationType.ADDRING, denoptim.graph.Vertex.allowedMutationTypes, denoptim.utils.MutationType.CHANGEBRANCH, denoptim.utils.MutationType.CHANGELINK, denoptim.utils.MutationType.DELETE, denoptim.utils.MutationType.DELETECHAIN, denoptim.utils.MutationType.DELETELINK, denoptim.utils.MutationType.EXTEND, denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.getCappedAPCountThroughout(), denoptim.graph.Vertex.getCappedAPs(), denoptim.graph.Vertex.getChilddren(), denoptim.graph.Vertex.getFreeAPCountThroughout(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.Vertex.isAromaticBridge(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.Vertex.owner, and denoptim.graph.Vertex.BBType.SCAFFOLD.
getNumberOfAPs()
int denoptim.graph.Vertex.getNumberOfAPs ()
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 368 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.graph.Vertex.convertIACToVertex(), denoptim.graph.DGraph.fixEdgeDirections(), denoptim.graph.Fragment.Fragment(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.graph.Template.getMutationTypes(), denoptim.graph.Vertex.getUniqueAPIndex(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.Vertex.sameVertexFeatures(), denoptim.gui.GUIVertexInspector.saveUnsavedChanges(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.graph.FragmentTest.testConversionToIAC(), denoptim.fragmenter.ClusterableFragmentTest.testGetTransformedCopy(), denoptim.graph.FragmentTest.testHandlingAPsAsObjOrProperty(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), and denoptim.json.DENOPTIMgsonTest.testTemplateSerialization().
getParent()
Vertex denoptim.graph.Vertex.getParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the vertex which is the source of the edge in which this vertex is the target.
Returns
the vertex parent to this or null.
Definition at line 1084 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Edge.getSrcAP(), and denoptim.graph.Edge.getTrgAP().
Referenced by denoptim.graph.Vertex.connectedTo(), denoptim.graph.DGraph.editGraph(), denoptim.graph.rings.RingSizeManager.evaluateRCVPair(), denoptim.ga.GraphOperations.getFragmentForClosableChain(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), and denoptim.ga.GraphOperations.locateCompatibleXOverPoints().
getPathIDs()
String[] denoptim.graph.Vertex.getPathIDs (AttachmentPoint apA, AttachmentPoint apB)
Produces a pair of strings that identify the "path" between two given attachment points.
The two strings represent one the reverse path of the other. So they identify the path when starting from each of the two APs.
Parameters
apA
apB
Returns
a pair of strings that identify the "path" between two given attachment points.
Reimplemented in denoptim.graph.Template.
Definition at line 1403 of file Vertex.java.
References denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), and denoptim.graph.Vertex.getIndexOfAP().
Referenced by denoptim.graph.rings.PathSubGraph.PathSubGraph().
getProperties()
Map< Object, Object > denoptim.graph.Vertex.getProperties ()
Definition at line 1207 of file Vertex.java.
References denoptim.graph.Vertex.properties.
getProperty()
Object denoptim.graph.Vertex.getProperty (Object property)
Definition at line 1224 of file Vertex.java.
References denoptim.graph.Vertex.properties.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.DGraph.dfsEncodePaths(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.utils.GraphUtils.getLabel(), denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings(), denoptim.fragmenter.FragmenterTools.manageFragmentCollection(), denoptim.graph.Vertex.parseVertexFromSDFFormat(), denoptim.gui.FragmentViewPanel.preSelectAPs(), denoptim.gui.VertexAsGraphViewPanel.preSelectAPs(), denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs(), denoptim.graph.Fragment.projectPropertyToAP(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.graph.FragmentTest.testHandlingAPsAsObjOrProperty(), and denoptim.graph.DGraphTest.testSymmetricSetLabels().
getSymmetricAPs()
SymmetricAPs denoptim.graph.Vertex.getSymmetricAPs (AttachmentPoint ap)
For the given attachment point index locate the symmetric partners i.e.
those with similar environments and class types.
Parameters
apIdx index of the attachment point which we want to get the symmetrically related partners of.
Returns
the list of attachment point IDs, which include apIdx or an empty list if no partners present
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 354 of file Vertex.java.
References denoptim.graph.Vertex.getSymmetricAPSets().
Referenced by denoptim.graph.Template.getSymmetricAPSets(), denoptim.ga.EAUtils.searchRingFusionSites(), and denoptim.graph.FragmentTest.testConversionToIAC().
getSymmetricAPSets()
abstract List< SymmetricAPs > denoptim.graph.Vertex.getSymmetricAPSets () abstract
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
Referenced by denoptim.graph.Vertex.cleanup(), denoptim.graph.Vertex.getSymmetricAPs(), denoptim.graph.Vertex.hasSymmetricAP(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.graph.SymmetricSetWithModeTest.testEquals(), denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs(), denoptim.graph.SymmetricAPsTest.testGetSameAsThis(), denoptim.graph.SymmetricSetWithModeTest.testHashCode(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.graph.SymmetricAPsTest.testSameAs(), denoptim.fragspace.FragmentSpaceTest.testSymmetry(), and denoptim.json.DENOPTIMgsonTest.testTemplateSerialization().
getUnfilteredMutationTypes()
List< MutationType > denoptim.graph.Vertex.getUnfilteredMutationTypes () protected
Returns the mutation types that are constitutionally configures for this vertex irrespectively on the graph or the context in which this vertex is included.
Returns
the list of allowed mutation types as configured upon vertex constitution.
Definition at line 896 of file Vertex.java.
References denoptim.graph.Vertex.allowedMutationTypes.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), and denoptim.graph.Template.clone().
getUniqueAPIndex()
int denoptim.graph.Vertex.getUniqueAPIndex () protected
Definition at line 533 of file Vertex.java.
References denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.DGraph.getUniqueAPIndex(), and denoptim.graph.Vertex.owner.
Referenced by denoptim.graph.AttachmentPoint.AttachmentPoint().
getVertexId()
long denoptim.graph.Vertex.getVertexId ()
Definition at line 289 of file Vertex.java.
References denoptim.graph.Vertex.vertexId.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.ga.EAUtils.canBeUsedForRingFusion(), denoptim.graph.DGraph.clone(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.rings.CyclicGraphHandler.combineCompatPathSubGraphs(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.graph.rings.PathSubGraph.findPath(), denoptim.graph.DGraph.fixEdgeDirections(), denoptim.graph.DGraph.getBondingAPIndex(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings(), denoptim.graph.Edge.getSrcVertex(), denoptim.graph.Edge.getTrgVertex(), denoptim.graph.DGraph.indexOfVertexWithID(), denoptim.gui.GraphViewerPanel.JEdge.JEdge(), denoptim.gui.GraphViewerPanel.JVertex.JVertex(), denoptim.gui.VertexViewPanel.loadTemplateToViewer(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.ga.GraphOperations.performCrossover(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.programs.genetweeker.GeneOpsRunner.runMutation(), denoptim.programs.genetweeker.GeneOpsRunner.runXOver(), denoptim.graph.Ring.DENOPTIMRingSerializer.serialize(), denoptim.graph.Template.setIAtomContainer(), denoptim.graph.DGraph.setScaffold(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.graph.DGraphTest.testFindVertex(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), denoptim.graph.DGraphTest.testGetSymmetricSubGraphs(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.graph.APMapping.toIntMappig(), denoptim.graph.Edge.toString(), denoptim.graph.EmptyVertex.toString(), denoptim.graph.Fragment.toString(), and denoptim.graph.simplified.UndirectedEdge.toString().
getVertexType()
VertexType denoptim.graph.Vertex.getVertexType ()
Returns the value of the vertex type.
Note the returned object is independent from the object holding the information about the type of this vertex.
Returns
the value of the vertex type
Definition at line 1304 of file Vertex.java.
References denoptim.graph.Vertex.vertexType.
hasFreeAP()
boolean denoptim.graph.Vertex.hasFreeAP ()
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 521 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints().
Referenced by denoptim.ga.EAUtils.buildGraph().
hasProperty()
boolean denoptim.graph.Vertex.hasProperty (Object property)
Definition at line 1214 of file Vertex.java.
References denoptim.graph.Vertex.properties.
Referenced by denoptim.utils.GraphUtils.getLabel().
hasSymmetricAP()
boolean denoptim.graph.Vertex.hasSymmetricAP ()
Returns
true if vertex has symmetric APs
Reimplemented in denoptim.graph.EmptyVertex.
Definition at line 614 of file Vertex.java.
References denoptim.graph.Vertex.getSymmetricAPSets().
Referenced by denoptim.fragspace.FragsCombinationIterator.next().
isAromaticBridge()
boolean denoptim.graph.Vertex.isAromaticBridge ()
Checks if this vertex is meant to be a piece of an aromatic system.
Returns
true if this vertex has AttachmentPoints with any APClass reserved for aromatic system fragments. See APClass#APCAROMBRIDGES.
Definition at line 564 of file Vertex.java.
References denoptim.graph.APClass.APCAROMBRIDGES, and denoptim.graph.Vertex.getAllAPClasses().
Referenced by denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), and denoptim.graph.VertexTest.testIsConnectedToAromaticBridge().
isConnectedToAromaticBridge()
boolean denoptim.graph.Vertex.isConnectedToAromaticBridge ()
Checks if this vertex is connected to any vertex meant to be a piece of an aromatic system.
The connection may be direct or via a pair of RCVs.
Returns
true if this vertex has AttachmentPoints linked to any other AttachmentPoints with any APClass reserved for aromatic system fragments. See APClass#APCAROMBRIDGES.
Definition at line 583 of file Vertex.java.
References denoptim.graph.APClass.APCAROMBRIDGES, denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.AttachmentPoint.getLinkedAPThroughout(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.Ring.getSize(), denoptim.graph.Ring.getVertexAtPosition(), denoptim.graph.Vertex.isAromaticBridge(), and denoptim.graph.Vertex.isRCV.
Referenced by denoptim.graph.Vertex.getMutationTypes(), and denoptim.graph.VertexTest.testIsConnectedToAromaticBridge().
isRCV()
boolean denoptim.graph.Vertex.isRCV ()
Returns
true if vertex is a ring closing vertex
Definition at line 550 of file Vertex.java.
References denoptim.graph.Vertex.isRCV.
newVertexFromLibrary() [1/2]
static Vertex denoptim.graph.Vertex.newVertexFromLibrary (int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException static
Builds a new molecular fragment kind of vertex.
Parameters
bbId 0-based index of building block in the library
bbt the type of building block 0:scaffold, 1:fragment, 2:capping group
Exceptions
DENOPTIMException
Definition at line 215 of file Vertex.java.
References denoptim.utils.GraphUtils.getUniqueVertexIndex(), and denoptim.graph.Vertex.newVertexFromLibrary().
Referenced by denoptim.graph.DGraph.addCappingGroups(), denoptim.ga.GraphOperations.attachFragmentInClosableChain(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.GraphOperations.extendGraph(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.fragspace.FragmentSpace.makeRandomScaffold(), denoptim.graph.DGraphTest.makeTestGraph0(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraph.replaceVertex(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.combinatorial.CombinatorialExplorerByLayer.startNewGraphFromScaffold(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), and denoptim.fragspace.FragmentSpaceTest.testSymmetry().
newVertexFromLibrary() [2/2]
static Vertex denoptim.graph.Vertex.newVertexFromLibrary (long vertexId, int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException static
Make a new vertex that is a copy of a vertex in the fragment space.
Parameters
vertexId unique identified of the vertex
bbId 0-based index of building block in the library
bbt the type of building block
Exceptions
DENOPTIMException when index is not within the range.
Definition at line 232 of file Vertex.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.rings.RingClosingAttractor.RCAAPCLASSSET, denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setVertexId(), and denoptim.graph.Vertex.vertexId.
parseVertexFromSDFFormat()
static Vertex denoptim.graph.Vertex.parseVertexFromSDFFormat (IAtomContainer mol, Gson reader, BBType bbt) throws DENOPTIMException static
Created a Vertex from the SDF representation, i.e., from an IAtomContainer.
Parameters
mol the container to parse.
reader a converted able to deserialize a vertex from a JSON string.
bbt the type of building block we want to generate.
Returns
a vertex
Definition at line 1454 of file Vertex.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.graph.Vertex.convertIACToVertex(), denoptim.graph.Vertex.fromJson(), denoptim.graph.Vertex.getProperty(), denoptim.constants.DENOPTIMConstants.GRAPHJSONTAG, denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.constants.DENOPTIMConstants.VERTEXJSONTAG.
Referenced by denoptim.io.DenoptimIO.readDENOPTIMVertexesFromSDFile().
removeMutationType()
boolean denoptim.graph.Vertex.removeMutationType (MutationType mt)
Removes the specified mutation type.
Parameters
mt the element to remove.
Returns
true if this list contained the specified element.
Definition at line 908 of file Vertex.java.
References denoptim.graph.Vertex.allowedMutationTypes.
Referenced by denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), and denoptim.graph.Template.updateMutTypeToFixedSTructure().
removeProperty()
void denoptim.graph.Vertex.removeProperty (Object key)
Definition at line 1247 of file Vertex.java.
References denoptim.graph.Vertex.properties.
resetGraphOwner()
void denoptim.graph.Vertex.resetGraphOwner ()
Definition at line 834 of file Vertex.java.
Referenced by denoptim.graph.DGraph.removeVertex().
sameAs() [1/2]
boolean denoptim.graph.Vertex.sameAs (Vertex other)
Compares this and another vertex ignoring vertex IDs.
Parameters
other
Returns
true if the two vertices represent the same graph node even if the vertex IDs are different.
Definition at line 670 of file Vertex.java.
References denoptim.graph.Vertex.sameAs().
Referenced by denoptim.graph.DGraph.isIsomorphicTo(), and denoptim.graph.Vertex.sameAs().
sameAs() [2/2]
boolean denoptim.graph.Vertex.sameAs (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
Parameters
other
reason string builder used to build the message clarifying the reason for returning false.
Returns
true if the two vertices represent the same graph node even if the vertex IDs are different.
Definition at line 685 of file Vertex.java.
References denoptim.graph.Vertex.sameVertexFeatures().
sameVertexFeatures()
boolean denoptim.graph.Vertex.sameVertexFeatures (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
Parameters
other
reason string builder used to build the message clarifying the reason for returning false.
Returns
true if the two vertices represent the same graph node even if the vertex IDs are different.
Definition at line 717 of file Vertex.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.getNumberOfAPs(), and denoptim.graph.AttachmentPoint.sameAs().
Referenced by denoptim.graph.EmptyVertex.sameAs(), denoptim.graph.Fragment.sameAs(), denoptim.graph.Template.sameAs(), and denoptim.graph.Vertex.sameAs().
setAsRCV()
void denoptim.graph.Vertex.setAsRCV (boolean isRCV)
Definition at line 275 of file Vertex.java.
References denoptim.graph.Vertex.isRCV.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Vertex.convertIACToVertex(), denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.Fragment.Fragment(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.fragspace.FragmentSpace.getPolarizedRCV(), denoptim.fragmenter.FragmenterTools.getRCVForAP(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.graph.FragmentTest.makeFragment(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphA(), denoptim.graph.rings.RingSizeManagerTest.makeTestGraphA(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphB(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.fragspace.FragmentSpaceTest.testGetRCVsForAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetRCVsWithAPClass(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
setBuildingBlockId()
void denoptim.graph.Vertex.setBuildingBlockId (int buildingBlockId)
Definition at line 312 of file Vertex.java.
References denoptim.graph.Vertex.buildingBlockId.
Referenced by denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.RingTest.testGetCloserVertex(), denoptim.graph.RingTest.testGetDistance(), denoptim.ga.EAUtilsTest.testGetUsableAliphaticBridges(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.graph.EdgeTest.testUndirectedComparison(), denoptim.graph.RingTest.testUndirectedComparison(), and denoptim.graph.UndirectedEdgeRelationTest.testUndirectedComparison().
setBuildingBlockType()
void denoptim.graph.Vertex.setBuildingBlockType (Vertex.BBType buildingBlockType)
Definition at line 326 of file Vertex.java.
References denoptim.graph.Vertex.buildingBlockType.
Referenced by denoptim.ga.EAUtils.appendVertexesToGraphFollowingEdges(), denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Fragment.Fragment(), denoptim.graph.FragmentTest.makeFragment(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.graph.Vertex.parseVertexFromSDFFormat(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.Template.Template(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), denoptim.graph.EdgeTest.testUndirectedComparison(), and denoptim.graph.UndirectedEdgeRelationTest.testUndirectedComparison().
setGraphOwner()
void denoptim.graph.Vertex.setGraphOwner (DGraph owner)
Definition at line 841 of file Vertex.java.
References denoptim.graph.Vertex.owner.
setMutationTypes()
void denoptim.graph.Vertex.setMutationTypes (List< MutationType > lst)
Definition at line 882 of file Vertex.java.
References denoptim.graph.Vertex.allowedMutationTypes.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.DGraph.replaceVertex(), and denoptim.graph.VertexTest.testGetMutationSites().
setProperties()
void denoptim.graph.Vertex.setProperties (Map< Object, Object > properties)
Definition at line 1283 of file Vertex.java.
References denoptim.graph.Vertex.properties.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), and denoptim.graph.Template.clone().
setProperty()
void denoptim.graph.Vertex.setProperty (Object key, Object property)
Definition at line 1236 of file Vertex.java.
References denoptim.graph.Vertex.properties.
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.Fragment.Fragment(), denoptim.graph.DGraph.getChildrenTree(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.ga.EAUtils.getUsableAliphaticBridges(), denoptim.ga.EAUtils.getUsableAromaticBridges(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.fragmenter.FragmenterTools.manageFragmentCollection(), denoptim.graph.simplified.Node.Node(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.programs.genetweeker.GeneOpsRunner.runMutation(), denoptim.ga.PopulationTest.testClone(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), denoptim.fragmenter.ConformerExtractorTaskTest.testExtractClusterableFragments(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.FragmentTest.testHandlingAPsAsObjOrProperty(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.ga.GraphOperationsTest.testLocateCompatibleXOverPoints(), denoptim.graph.VertexTest.testSameAs_Equal(), and denoptim.ga.PopulationTest.testXOverCompatibility().
setSymmetricAPSets()
abstract void denoptim.graph.Vertex.setSymmetricAPSets (List< SymmetricAPs > sAPs) abstract protected
Reimplemented in denoptim.graph.EmptyVertex, denoptim.graph.Fragment, and denoptim.graph.Template.
setUniquefyingProperty()
void denoptim.graph.Vertex.setUniquefyingProperty (String key)
Add the given key among the properties that are checked for equality when comparing vertices with the Vertex#sameAs(Vertex, StringBuilder) method.
Parameters
key
Definition at line 1200 of file Vertex.java.
References denoptim.graph.Vertex.uniquefyingPropertyKeys.
Referenced by denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.ga.PopulationTest.testClone(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.ga.GraphOperationsTest.testLocateCompatibleXOverPoints(), denoptim.graph.VertexTest.testSameAs_Equal(), and denoptim.ga.PopulationTest.testXOverCompatibility().
setVertexId()
void denoptim.graph.Vertex.setVertexId (long vertexId2)
Definition at line 282 of file Vertex.java.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.ga.GraphOperations.addRing(), denoptim.ga.EAUtils.appendVertexesToGraphFollowingEdges(), denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.graph.TemplateTest.getTemplateDeepTest(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.graph.FragmentTest.makeFragment(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.rings.RingSizeManagerTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
toString()
String denoptim.graph.Vertex.toString ()
Produces a human readable, short string to represent the vertex by its vertex ID, building block ID (1-based), building block type, and level in the graph (if any).
This is the old syntax used up to version 2 for reporting a vertex in the string representation of a graph. Such notation cannot hold all the information needed to define a template, and is, therefore, obsolete. Use JSON format to serialize a graph that may contain templates.
Reimplemented in denoptim.graph.EmptyVertex, and denoptim.graph.Fragment.
Definition at line 632 of file Vertex.java.
References denoptim.graph.Vertex.buildingBlockId, denoptim.graph.Vertex.buildingBlockType, denoptim.graph.Vertex.BBType.toOldInt(), and denoptim.graph.Vertex.vertexId.
Referenced by denoptim.graph.DGraph.dfsEncodePaths().
Member Data Documentation
allowedMutationTypes
List<MutationType> denoptim.graph.Vertex.allowedMutationTypes private
Initial value:
=
            new ArrayList<MutationType>(Arrays.asList(MutationType.values()))
List of mutations that we can perform on this vertex.
Definition at line 160 of file Vertex.java.
Referenced by denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Vertex.getUnfilteredMutationTypes(), denoptim.graph.Vertex.removeMutationType(), and denoptim.graph.Vertex.setMutationTypes().
buildingBlockId
int denoptim.graph.Vertex.buildingBlockId = -99 protected
Index of this building block in the library of building blocks, or negative if this vertex is not part of a library.
Definition at line 77 of file Vertex.java.
Referenced by denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.setBuildingBlockId(), and denoptim.graph.Vertex.toString().
buildingBlockType
BBType denoptim.graph.Vertex.buildingBlockType = Vertex.BBType.UNDEFINED protected
Definition at line 138 of file Vertex.java.
Referenced by denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.graph.Vertex.toString().
isRCV
boolean denoptim.graph.Vertex.isRCV private
Definition at line 143 of file Vertex.java.
Referenced by denoptim.molecularmodeling.ThreeDimTreeBuilder.append3DFragmentsViaEdges(), denoptim.ga.EAUtils.appendVertexesToGraphFollowingEdges(), denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.Fragment.Fragment(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.Vertex.isRCV(), denoptim.gui.GraphViewerPanel.JVertex.JVertex(), denoptim.graph.simplified.Node.Node(), denoptim.graph.Vertex.setAsRCV(), denoptim.graph.FragmentTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization(), denoptim.json.DENOPTIMgsonTest.testTemplateSerialization(), and denoptim.graph.Vertex.Vertex().
owner
DGraph denoptim.graph.Vertex.owner private
Graph that includes this vertex.
Definition at line 66 of file Vertex.java.
Referenced by denoptim.graph.Vertex.getEdgeWith(), denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.Vertex.getMutationTypes(), denoptim.graph.Vertex.getUniqueAPIndex(), and denoptim.graph.Vertex.setGraphOwner().
properties
Map<Object, Object> denoptim.graph.Vertex.properties protected
Map of customizable properties.
Definition at line 148 of file Vertex.java.
Referenced by denoptim.graph.Vertex.copyStringBasedProperties(), denoptim.graph.Vertex.getProperties(), denoptim.graph.Vertex.getProperty(), denoptim.graph.Vertex.hasProperty(), denoptim.graph.Vertex.removeProperty(), denoptim.graph.EmptyVertex.sameAs(), denoptim.graph.Vertex.setProperties(), and denoptim.graph.Vertex.setProperty().
uniquefyingPropertyKeys
Set<String> denoptim.graph.Vertex.uniquefyingPropertyKeys = new HashSet<String>() protected
List of properties required to make Vertex#sameAs(Vertex, StringBuilder) method return false when property values differ.
Definition at line 155 of file Vertex.java.
Referenced by denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Template.clone(), denoptim.graph.Vertex.copyStringBasedProperties(), denoptim.graph.EmptyVertex.sameAs(), and denoptim.graph.Vertex.setUniquefyingProperty().
vertexId
long denoptim.graph.Vertex.vertexId private
Unique identifier associated with the vertex instance.
Definition at line 71 of file Vertex.java.
Referenced by denoptim.graph.Fragment.Fragment(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.Vertex.toString(), and denoptim.graph.Vertex.Vertex().
vertexType
final VertexType denoptim.graph.Vertex.vertexType protected
Field distinguishing implementations of Vertex when deserializing JSON representations.
See DENOPTIMgson.
Definition at line 167 of file Vertex.java.
Referenced by denoptim.graph.Vertex.getVertexType(), denoptim.graph.VertexTest.testFromToJSON_minimal(), and denoptim.graph.Vertex.Vertex().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/Vertex.java