DENOPTIM: denoptim.fragspace.IdFragmentAndAP Class Reference
denoptim.fragspace.IdFragmentAndAP Class Reference
Data structure containing information that identifies a single AP of a vertex/fragment.
Public Member Functions
IdFragmentAndAP ()
IdFragmentAndAP (long vIdx, int molId, BBType molTyp, int apId, int vSymSetId, int apSymSetId)
long getVertexId ()
int getVertexMolId ()
BBType getVertexMolType ()
int getApId ()
int getVrtSymSetId ()
int getApSymSetId ()
void setVrtSymSetId (int vSymSetId)
boolean sameFragAndAp (IdFragmentAndAP other)
Compares this and another identifier considering solely the fragment ID in the type-specific fragment library, and the attachment point ID in that fragment.
String toString ()
Private Attributes
long vId = -1
the ID of the vertex containing the fragment.
int molId = -1
the index of the fragment in that library.
BBType molTyp = BBType.UNDEFINED
the type of library containing the fragment.
int apId = -1
the index of a specific attachment point.
int vSymSetId = -1
the index of the symmetric set the vertex belongs to.
int apSymSetId = -1
the index of the symmetric set the AP belongs to.
Detailed Description
Data structure containing information that identifies a single AP of a vertex/fragment.
Author
Marco Foscato
Definition at line 32 of file IdFragmentAndAP.java.
Constructor & Destructor Documentation
IdFragmentAndAP() [1/2]
denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP ()
Definition at line 66 of file IdFragmentAndAP.java.
IdFragmentAndAP() [2/2]
denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP (long vIdx, int molId, BBType molTyp, int apId, int vSymSetId, int apSymSetId)
Definition at line 72 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.apId, denoptim.fragspace.IdFragmentAndAP.apSymSetId, denoptim.fragspace.IdFragmentAndAP.molId, denoptim.fragspace.IdFragmentAndAP.molTyp, and denoptim.fragspace.IdFragmentAndAP.vSymSetId.
Member Function Documentation
getApId()
int denoptim.fragspace.IdFragmentAndAP.getApId ()
Definition at line 106 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.apId.
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.GraphOperations.extendGraph(), denoptim.fragspace.FragmentSpace.getAPClassForFragment(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.fragspace.IdFragmentAndAP.sameFragAndAp(), and denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs().
getApSymSetId()
int denoptim.fragspace.IdFragmentAndAP.getApSymSetId ()
Definition at line 120 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.apSymSetId.
getVertexId()
long denoptim.fragspace.IdFragmentAndAP.getVertexId ()
Definition at line 85 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.vId.
Referenced by denoptim.combinatorial.GraphBuildingTask.call().
getVertexMolId()
int denoptim.fragspace.IdFragmentAndAP.getVertexMolId ()
Definition at line 92 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.molId.
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.GraphOperations.extendGraph(), denoptim.fragspace.FragmentSpace.getAPClassForFragment(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.fragspace.IdFragmentAndAP.sameFragAndAp(), and denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs().
getVertexMolType()
BBType denoptim.fragspace.IdFragmentAndAP.getVertexMolType ()
Definition at line 99 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.molTyp.
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), denoptim.fragspace.FragmentSpace.getAPClassForFragment(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.fragspace.IdFragmentAndAP.sameFragAndAp(), and denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs().
getVrtSymSetId()
int denoptim.fragspace.IdFragmentAndAP.getVrtSymSetId ()
Definition at line 113 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.vSymSetId.
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), and denoptim.fragspace.FragsCombinationIterator.next().
sameFragAndAp()
boolean denoptim.fragspace.IdFragmentAndAP.sameFragAndAp (IdFragmentAndAP other)
Compares this and another identifier considering solely the fragment ID in the type-specific fragment library, and the attachment point ID in that fragment.
Parameters
other the other identified to be compared with this.
Returns
true if this and the other identify the same fragment and AP ID.
Definition at line 142 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.getApId(), denoptim.fragspace.IdFragmentAndAP.getVertexMolId(), and denoptim.fragspace.IdFragmentAndAP.getVertexMolType().
setVrtSymSetId()
void denoptim.fragspace.IdFragmentAndAP.setVrtSymSetId (int vSymSetId)
Definition at line 127 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.vSymSetId.
Referenced by denoptim.fragspace.FragsCombinationIterator.next().
toString()
String denoptim.fragspace.IdFragmentAndAP.toString ()
Definition at line 156 of file IdFragmentAndAP.java.
References denoptim.fragspace.IdFragmentAndAP.apId, denoptim.fragspace.IdFragmentAndAP.apSymSetId, denoptim.fragspace.IdFragmentAndAP.molId, denoptim.fragspace.IdFragmentAndAP.molTyp, denoptim.fragspace.IdFragmentAndAP.vId, and denoptim.fragspace.IdFragmentAndAP.vSymSetId.
Member Data Documentation
apId
int denoptim.fragspace.IdFragmentAndAP.apId = -1 private
the index of a specific attachment point.
Definition at line 52 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getApId(), denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP(), and denoptim.fragspace.IdFragmentAndAP.toString().
apSymSetId
int denoptim.fragspace.IdFragmentAndAP.apSymSetId = -1 private
the index of the symmetric set the AP belongs to.
Definition at line 62 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getApSymSetId(), denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP(), and denoptim.fragspace.IdFragmentAndAP.toString().
molId
int denoptim.fragspace.IdFragmentAndAP.molId = -1 private
the index of the fragment in that library.
Definition at line 42 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getVertexMolId(), denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP(), and denoptim.fragspace.IdFragmentAndAP.toString().
molTyp
BBType denoptim.fragspace.IdFragmentAndAP.molTyp = BBType.UNDEFINED private
the type of library containing the fragment.
Definition at line 47 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getVertexMolType(), denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP(), and denoptim.fragspace.IdFragmentAndAP.toString().
vId
long denoptim.fragspace.IdFragmentAndAP.vId = -1 private
the ID of the vertex containing the fragment.
Definition at line 37 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getVertexId(), and denoptim.fragspace.IdFragmentAndAP.toString().
vSymSetId
int denoptim.fragspace.IdFragmentAndAP.vSymSetId = -1 private
the index of the symmetric set the vertex belongs to.
Definition at line 57 of file IdFragmentAndAP.java.
Referenced by denoptim.fragspace.IdFragmentAndAP.getVrtSymSetId(), denoptim.fragspace.IdFragmentAndAP.IdFragmentAndAP(), denoptim.fragspace.IdFragmentAndAP.setVrtSymSetId(), and denoptim.fragspace.IdFragmentAndAP.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragspace/IdFragmentAndAP.java