DENOPTIM: denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest Class Reference
denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest Class Reference
Unit test for ZMatrixAtom.
Public Member Functions
void testEquals () throws Exception
void testZMatrixAtomHashCode () throws Exception
void testZMatrixBondEquals () throws Exception
void testZMatrixBondHashCode () throws Exception
Static Public Member Functions
static ZMatrixAtom getTestZMatrixAtom ()
Detailed Description
Unit test for ZMatrixAtom.
Author
Marco Foscato
Definition at line 34 of file ZMatrixAtomTest.java.
Member Function Documentation
getTestZMatrixAtom()
static ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.getTestZMatrixAtom () static
Definition at line 38 of file ZMatrixAtomTest.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixAtomHashCode().
testEquals()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals () throws Exception
Definition at line 54 of file ZMatrixAtomTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.getTestZMatrixAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2Value(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleValue(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondLength(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setChiralFlag(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setSymbol(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setType().
testZMatrixAtomHashCode()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixAtomHashCode () throws Exception
Definition at line 106 of file ZMatrixAtomTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.getTestZMatrixAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setId().
testZMatrixBondEquals()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixBondEquals () throws Exception
Definition at line 124 of file ZMatrixAtomTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals().
testZMatrixBondHashCode()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixBondHashCode () throws Exception
Definition at line 151 of file ZMatrixAtomTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.hashCode().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/molecularmodeling/zmatrix/ZMatrixAtomTest.java