DENOPTIM: denoptim.graph.SymmetricAPsTest Class Reference
denoptim.graph.SymmetricAPsTest Class Reference
Public Member Functions
void testSameAs () throws Exception
void testGetSameAsThis () throws Exception
Detailed Description
Definition at line 33 of file SymmetricAPsTest.java.
Member Function Documentation
testGetSameAsThis()
void denoptim.graph.SymmetricAPsTest.testGetSameAsThis () throws Exception
Definition at line 68 of file SymmetricAPsTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.getAtom(), denoptim.graph.SymmetricAPs.getSameAs(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.APClass.make(), and denoptim.graph.FragmentTest.makeFragmentA().
testSameAs()
void denoptim.graph.SymmetricAPsTest.testSameAs () throws Exception
Definition at line 39 of file SymmetricAPsTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.getAtom(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.APClass.make(), denoptim.graph.FragmentTest.makeFragmentA(), and denoptim.graph.SymmetricAPs.sameAs().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/SymmetricAPsTest.java