DENOPTIM: denoptim.integration.tinker.ConformationalSearchPSSROT Class Reference
denoptim.integration.tinker.ConformationalSearchPSSROT Class Reference
Toolkit to perform conformational search via Tinker PSSROT program.
Static Public Member Functions
static void performPSSROT (ArrayList< ChemicalObjectModel > mols, String runLabel, String ffFilePathName, List< String > keyFileLines, List< String > subParamsInit, List< String > subParamsRest, String pssExePathName, String xyzintPathName, String workDir, int taskId, Logger logger) throws DENOPTIMException, TinkerException
Performs PSSROT conformational search for all chemical objects in the list.
static void performPSSROT (ChemicalObjectModel chemObj, int idm, String runLabel, String ffFilePathName, List< String > keyFileLines, List< String > subParamsInit, List< String > subParamsRest, String pssrotPathName, String xyzintPathName, String workDir, int taskId, Logger logger) throws DENOPTIMException, TinkerException
Performs PSSROT conformational search on the given chemical object.
static void fixLongeLinesInXYZ (String filename) throws DENOPTIMException
The XYZ file generated by Tinker for molecules having atoms with many Neighbors is corrupted: the line of the atom with long list of connected atoms is split in two lines.
Static Private Attributes
static final String FSEP = System.getProperty("file.separator")
File separator.
static final String NL = DENOPTIMConstants.EOL
Newline character.
Detailed Description
Toolkit to perform conformational search via Tinker PSSROT program.
Author
Marco Foscato
Definition at line 40 of file ConformationalSearchPSSROT.java.
Member Function Documentation
fixLongeLinesInXYZ()
static void denoptim.integration.tinker.ConformationalSearchPSSROT.fixLongeLinesInXYZ (String filename) throws DENOPTIMException static
The XYZ file generated by Tinker for molecules having atoms with many Neighbors is corrupted: the line of the atom with long list of connected atoms is split in two lines.
This method fixes the XYZ file displaying this problem for the given filename.
Parameters
filename the pathname of the file to fix.
Definition at line 324 of file ConformationalSearchPSSROT.java.
References denoptim.integration.tinker.ConformationalSearchPSSROT.NL, denoptim.io.DenoptimIO.readList(), and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
performPSSROT() [1/2]
static void denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT (ArrayList< ChemicalObjectModel > mols, String runLabel, String ffFilePathName, List< String > keyFileLines, List< String > subParamsInit, List< String > subParamsRest, String pssExePathName, String xyzintPathName, String workDir, int taskId, Logger logger) throws DENOPTIMException, TinkerException static
Performs PSSROT conformational search for all chemical objects in the list.
The objects will be modifier: no cloning.
Parameters
mols the list of object to modify.
runLabel a string to identify the type of run in log messages (e.g., "cs" for conformational search, "rc" for ring closing conformational search).
ffFilePathName the pathname of the force-field parameters file to use in the PSSROT job.
keyFileLines the lines of Tinker's key file (if the parameters line is included it will be ignored as the name of the parameters file is given explicitly.
subParamsInit the initial part of Tinker's job submission parameters: the responses to the first two question.
subParamsRest the remaining part of Tinker's job submission parameters.
pssExePathName pathname to Tinker pssrot executable.
xyzintPathName pathname to Tinker xyzint executable.
workDir the pathname of the file system location where we are going to create files and work with Tinker.
taskId a number identifying the overall task. Useful for logging.
logger the tool dealing with log messages.
Returns
the list of generated conformations.
Exceptions
DENOPTIMException
TinkerException if tinker fails.
Definition at line 80 of file ConformationalSearchPSSROT.java.
References denoptim.constants.DENOPTIMConstants.MOLERRORTAG, and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptRingClosure(), denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
performPSSROT() [2/2]
static void denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT (ChemicalObjectModel chemObj, int idm, String runLabel, String ffFilePathName, List< String > keyFileLines, List< String > subParamsInit, List< String > subParamsRest, String pssrotPathName, String xyzintPathName, String workDir, int taskId, Logger logger) throws DENOPTIMException, TinkerException static
Performs PSSROT conformational search on the given chemical object.
The object is modified directly, no cloning.
Parameters
chemObj the object to perform conformational search on.
idm index to distinguish molecules with same name (e.g., multiple models starting from the same ChemicalObjectModel.
runLabel a string to identify the type of run in log messages (e.g., "cs" for conformational search, "rc" for ring closing conformational search).
ffFilePathName the pathname of the force-field parameters file to use in the PSSROT job.
keyFileLines the lines of Tinker's key file (if the parameters line is included it will be ignored as the name of the parameters file is given explicitly.
subParamsInit the initial part of Tinker's job submission parameters: the responses to the first two question.
subParamsRest the remaining part of Tinker's job submission parameters.
pssrotPathName pathname to Tinker pssrot executable.
xyzintPathName pathname to Tinker xyzint executable.
workDir the pathname of the file system location where we are going to create files and work with Tinker.
taskId a number identifying the overall task. Useful for logging.
logger the tool dealing with log messages.
Returns
the new conformation of the molecular system
Exceptions
DENOPTIMException
TinkerException
Definition at line 137 of file ConformationalSearchPSSROT.java.
References denoptim.files.FileUtils.deleteFilesContaining(), denoptim.integration.tinker.TinkerUtils.ensureOutputExistsOrRelayError(), denoptim.integration.tinker.ConformationalSearchPSSROT.fixLongeLinesInXYZ(), denoptim.integration.tinker.ConformationalSearchPSSROT.FSEP, denoptim.integration.tinker.TinkerMolecule.getAtom(), denoptim.integration.tinker.TinkerMolecule.getAtoms(), denoptim.integration.tinker.TinkerAtom.getDistAngle(), denoptim.task.ProcessHandler.getErrorOutput(), denoptim.task.ProcessHandler.getExitCode(), denoptim.integration.tinker.TinkerMolecule.getName(), denoptim.integration.tinker.TinkerUtils.getNameLastCycleFile(), denoptim.integration.tinker.ConformationalSearchPSSROT.NL, denoptim.integration.tinker.TinkerUtils.readTinkerIC(), denoptim.task.ProcessHandler.runProcessInBASH(), denoptim.integration.tinker.TinkerAtom.setDistAngle(), denoptim.io.DenoptimIO.writeData(), and denoptim.integration.tinker.TinkerUtils.writeIC().
Member Data Documentation
FSEP
final String denoptim.integration.tinker.ConformationalSearchPSSROT.FSEP = System.getProperty("file.separator") static private
File separator.
Definition at line 45 of file ConformationalSearchPSSROT.java.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
NL
final String denoptim.integration.tinker.ConformationalSearchPSSROT.NL = DENOPTIMConstants.EOL static private
Newline character.
Definition at line 50 of file ConformationalSearchPSSROT.java.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.fixLongeLinesInXYZ(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/integration/tinker/ConformationalSearchPSSROT.java