DENOPTIM: denoptim.gui.GUIMainPanel Class Reference
denoptim.gui.GUIMainPanel Class Reference
The main panel is a deck of cards that occupies all the GUI frame.
Public Member Functions
GUIMainPanel (MainToolBar toolBar)
Component add (Component comp)
Add a component and a reference to such component in the main tool bar.
void removeCard (Component comp)
Remove a panel (i.e., a card) from the pile of cards (i.e., card deck)
boolean hasUnsavedChanges ()
Checks is any card has unsaved changes.
Package Attributes
MainToolBar toolBar
Reference to the main tool bar of the GUI.
Static Private Attributes
static final long serialVersionUID = 9090055883771428756L
Version.
Detailed Description
The main panel is a deck of cards that occupies all the GUI frame.
Only the main menu bar of the GUI resides outside of this main panel, and this class keeps a reference to that tool bar.
Definition at line 32 of file GUIMainPanel.java.
Constructor & Destructor Documentation
GUIMainPanel()
denoptim.gui.GUIMainPanel.GUIMainPanel (MainToolBar toolBar)
Definition at line 46 of file GUIMainPanel.java.
References denoptim.gui.GUIMainPanel.toolBar.
Member Function Documentation
add()
Component denoptim.gui.GUIMainPanel.add (Component comp)
Add a component and a reference to such component in the main tool bar.
The reference is added only if the component if an instance of GUICardPanel. Other components are added according to superclass method.
Definition at line 61 of file GUIMainPanel.java.
References denoptim.gui.MainToolBar.addActiveTab(), and denoptim.gui.GUIMainPanel.toolBar.
Referenced by denoptim.gui.GUIInspectFSERun.initialize(), denoptim.gui.GUIInspectGARun.initialize(), denoptim.gui.HomePanel.initialize(), denoptim.gui.MainToolBar.initialize(), denoptim.gui.MainToolBar.openFile(), and denoptim.gui.GUI.run().
hasUnsavedChanges()
boolean denoptim.gui.GUIMainPanel.hasUnsavedChanges ()
Checks is any card has unsaved changes.
Returns
true if there is at least one card with unsaved changes
Definition at line 112 of file GUIMainPanel.java.
References denoptim.gui.GUIMainPanel.hasUnsavedChanges().
Referenced by denoptim.gui.GUI.closeIfAllSaved(), and denoptim.gui.GUIMainPanel.hasUnsavedChanges().
removeCard()
void denoptim.gui.GUIMainPanel.removeCard (Component comp)
Remove a panel (i.e., a card) from the pile of cards (i.e., card deck)
Parameters
comp the component to remove
Definition at line 84 of file GUIMainPanel.java.
References denoptim.gui.MainToolBar.removeActiveTab(), and denoptim.gui.GUIMainPanel.toolBar.
Referenced by denoptim.gui.GUICardPanel.removeCardActionListener.actionPerformed().
Member Data Documentation
serialVersionUID
final long denoptim.gui.GUIMainPanel.serialVersionUID = 9090055883771428756L static private
Version.
Definition at line 37 of file GUIMainPanel.java.
toolBar
MainToolBar denoptim.gui.GUIMainPanel.toolBar package
Reference to the main tool bar of the GUI.
Definition at line 42 of file GUIMainPanel.java.
Referenced by denoptim.gui.GUIMainPanel.add(), denoptim.gui.GUIMainPanel.GUIMainPanel(), and denoptim.gui.GUIMainPanel.removeCard().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIMainPanel.java