DENOPTIM: denoptim.gui.MolToGraphParametersDialog Class Reference
denoptim.gui.MolToGraphParametersDialog Class Reference
Public Member Functions
MolToGraphParametersDialog (List< CuttingRule > defaultCuttingRules, List< CuttingRule > customCuttingRules, boolean preselectDefault, Component refForPlacement, FragmenterParameters settings)
boolean getEmbedRingsInTemplate ()
ScaffoldingPolicy getScaffoldingPolicy ()
ContractLevel getEmbeddedRingsContract ()
Public Member Functions inherited from denoptim.gui.CuttingRulesSelectionDialog
CuttingRulesSelectionDialog (List< CuttingRule > defaultCuttingRules, List< CuttingRule > customCuttingRules, boolean preselectDefault, Component refForPlacement, FragmenterParameters settings)
Constructor.
Public Member Functions inherited from denoptim.gui.GUIModalDialog
GUIModalDialog (Component refForPlacement)
Constructor.
GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Object showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
void addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
void addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Protected Member Functions
void saveResults ()
Protected Member Functions inherited from denoptim.gui.CuttingRulesSelectionDialog
void saveResults ()
void appendToCentralPanel (JComponent panel)
Method to append a panel to the bottom of the central panel.
Protected Member Functions inherited from denoptim.gui.GUIModalDialog
void close ()
Closes the dialog window.
Private Attributes
JPanel lineEmbTmpl
JRadioButton rdbEmbTmpl
JPanel lineScaffoldingPolicy
JLabel lblScaffoldingPolicy
JComboBox< String > cmbScaffoldingPolicy
JTextField txtScaffoldingPolicy
JPanel lineTemplateContract
JLabel lblTemplateContract
JComboBox< String > cmbTemplateContract
Static Private Attributes
static final long serialVersionUID = 1L
Version ID.
Additional Inherited Members
Protected Attributes inherited from denoptim.gui.CuttingRulesSelectionDialog
JPanel centralPanel = new JPanel(new BorderLayout())
The panel in the central part of the dialog.
File lastUsedCutRulFile = null
The file where we last saved cutting rules different from the default.
final int preferredHeight
Default text field height.
final Dimension strFieldSize = new Dimension(200, preferredHeight)
Default sizes for mid-long text.
JTextField txtLinearity
User-controlled definition of the linearity limit.
List< CuttingRule > chosenOnes
Chosen set of rules.
FragmenterParameters frgParams
Parameter storage were we store parameters.
Protected Attributes inherited from denoptim.gui.GUIModalDialog
JButton btnDone
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
JButton btnCanc
The button that is used to close the dialog without processing any input.
JButton btnExtra
The button that can be used for any action that does not close the dialog.
Object result = null
The result to be returned once the dialog is closed.
Detailed Description
Definition at line 22 of file MolToGraphParametersDialog.java.
Constructor & Destructor Documentation
MolToGraphParametersDialog()
denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog (List< CuttingRule > defaultCuttingRules, List< CuttingRule > customCuttingRules, boolean preselectDefault, Component refForPlacement, FragmenterParameters settings)
Definition at line 44 of file MolToGraphParametersDialog.java.
References denoptim.gui.CuttingRulesSelectionDialog.appendToCentralPanel(), denoptim.gui.MolToGraphParametersDialog.cmbScaffoldingPolicy, denoptim.gui.MolToGraphParametersDialog.cmbTemplateContract, denoptim.fragmenter.ScaffoldingPolicy.ELEMENT, denoptim.graph.Template.ContractLevel.FREE, denoptim.fragmenter.ScaffoldingPolicy.LARGEST_FRAGMENT, denoptim.gui.MolToGraphParametersDialog.lblScaffoldingPolicy, denoptim.gui.MolToGraphParametersDialog.lblTemplateContract, denoptim.gui.MolToGraphParametersDialog.lineEmbTmpl, denoptim.gui.MolToGraphParametersDialog.lineScaffoldingPolicy, denoptim.gui.MolToGraphParametersDialog.lineTemplateContract, denoptim.gui.MolToGraphParametersDialog.rdbEmbTmpl, denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.gui.CuttingRulesSelectionDialog.strFieldSize, and denoptim.gui.MolToGraphParametersDialog.txtScaffoldingPolicy.
Member Function Documentation
getEmbeddedRingsContract()
ContractLevel denoptim.gui.MolToGraphParametersDialog.getEmbeddedRingsContract ()
Definition at line 173 of file MolToGraphParametersDialog.java.
References denoptim.gui.MolToGraphParametersDialog.cmbTemplateContract.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
getEmbedRingsInTemplate()
boolean denoptim.gui.MolToGraphParametersDialog.getEmbedRingsInTemplate ()
Definition at line 156 of file MolToGraphParametersDialog.java.
References denoptim.gui.MolToGraphParametersDialog.rdbEmbTmpl.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
getScaffoldingPolicy()
ScaffoldingPolicy denoptim.gui.MolToGraphParametersDialog.getScaffoldingPolicy ()
Definition at line 163 of file MolToGraphParametersDialog.java.
References denoptim.gui.MolToGraphParametersDialog.cmbScaffoldingPolicy, and denoptim.gui.MolToGraphParametersDialog.txtScaffoldingPolicy.
Referenced by denoptim.gui.MolToGraphParametersDialog.saveResults().
saveResults()
void denoptim.gui.MolToGraphParametersDialog.saveResults () protected
Reimplemented from denoptim.gui.CuttingRulesSelectionDialog.
Definition at line 146 of file MolToGraphParametersDialog.java.
References denoptim.gui.CuttingRulesSelectionDialog.frgParams, denoptim.gui.MolToGraphParametersDialog.getEmbeddedRingsContract(), denoptim.gui.MolToGraphParametersDialog.getEmbedRingsInTemplate(), denoptim.gui.MolToGraphParametersDialog.getScaffoldingPolicy(), denoptim.programs.fragmenter.FragmenterParameters.setEmbeddedRingsContract(), denoptim.programs.fragmenter.FragmenterParameters.setEmbedRingsInTemplate(), and denoptim.programs.fragmenter.FragmenterParameters.setScaffoldingPolicy().
Member Data Documentation
cmbScaffoldingPolicy
JComboBox<String> denoptim.gui.MolToGraphParametersDialog.cmbScaffoldingPolicy private
Definition at line 35 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.getScaffoldingPolicy(), and denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
cmbTemplateContract
JComboBox<String> denoptim.gui.MolToGraphParametersDialog.cmbTemplateContract private
Definition at line 40 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.getEmbeddedRingsContract(), and denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
lblScaffoldingPolicy
JLabel denoptim.gui.MolToGraphParametersDialog.lblScaffoldingPolicy private
Definition at line 34 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
lblTemplateContract
JLabel denoptim.gui.MolToGraphParametersDialog.lblTemplateContract private
Definition at line 39 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
lineEmbTmpl
JPanel denoptim.gui.MolToGraphParametersDialog.lineEmbTmpl private
Definition at line 30 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
lineScaffoldingPolicy
JPanel denoptim.gui.MolToGraphParametersDialog.lineScaffoldingPolicy private
Definition at line 33 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
lineTemplateContract
JPanel denoptim.gui.MolToGraphParametersDialog.lineTemplateContract private
Definition at line 38 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
rdbEmbTmpl
JRadioButton denoptim.gui.MolToGraphParametersDialog.rdbEmbTmpl private
Definition at line 31 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.getEmbedRingsInTemplate(), and denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
serialVersionUID
final long denoptim.gui.MolToGraphParametersDialog.serialVersionUID = 1L static private
Version ID.
Definition at line 28 of file MolToGraphParametersDialog.java.
txtScaffoldingPolicy
JTextField denoptim.gui.MolToGraphParametersDialog.txtScaffoldingPolicy private
Definition at line 36 of file MolToGraphParametersDialog.java.
Referenced by denoptim.gui.MolToGraphParametersDialog.getScaffoldingPolicy(), and denoptim.gui.MolToGraphParametersDialog.MolToGraphParametersDialog().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/MolToGraphParametersDialog.java