DENOPTIM: denoptim.graph.EmptyVertex Class Reference
denoptim.graph.EmptyVertex Class Reference
An empty vertex has the behaviors of a vertex, but has no molecular structure.
Public Member Functions
EmptyVertex ()
Constructor for an empty vertex.
EmptyVertex (BBType type)
Constructor for an identified vertex without attachment points.
EmptyVertex (long id)
Constructor for an identified vertex without attachment points.
EmptyVertex (long id, ArrayList< AttachmentPoint > lstAPs, ArrayList< SymmetricAPs > lstSymAPs, boolean isRCV)
Constructor for an identified vertex.
List< AttachmentPoint > getAttachmentPoints ()
void setSymmetricAP (List< SymmetricAPs > sAPs)
List< SymmetricAPs > getSymmetricAP ()
SymmetricAPs getSymmetricAPs (AttachmentPoint ap)
For the given attachment point index locate the symmetric partners i.e.
int getNumberOfAPs ()
ArrayList< Integer > getFreeAPList ()
int getFreeAPCount ()
boolean hasFreeAP ()
boolean hasSymmetricAP ()
String toString ()
Produces a human readable, short string to represent the vertex by its vertex ID, building block ID (1-based), building block type, and level in the graph (if any).
void cleanup ()
EmptyVertex clone ()
Returns a deep-copy of this vertex.
void addAP ()
Adds an attachment point with no APClass or other attribute.
void addAP (APClass apClass)
Adds an attachment point with the specified APClass.
boolean sameAs (EmptyVertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
int getHeavyAtomsCount ()
boolean containsAtoms ()
IAtomContainer getIAtomContainer ()
Although empty vertex do not contain atoms, by definitions, we allow the generation of an SDF representation that uses an empty atom list.
IAtomContainer getIAtomContainer (Logger logger, Randomizer rng, boolean removeUsedRCAs, boolean rebuild)
Although empty vertex do not contain atoms, by definitions, we allow the generation of an SDF representation that uses an empty atom list.
String toJson ()
Produces a string that represents this vertex and that adheres to the JSON format.
ArrayList< APClass > getAllAPClasses ()
Returns the list of all APClasses on present on this fragment.
List< SymmetricAPs > getSymmetricAPSets ()
List< Vertex > getMutationSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this vertex.
Public Member Functions inherited from denoptim.graph.Vertex
Vertex (VertexType vertexType)
Constructor for an empty vertex.
Vertex (VertexType vertexType, long id)
Constructor for an identified vertex without attachment points.
abstract List< AttachmentPoint > getAttachmentPoints ()
List< AttachmentPoint > getAPsWithAPClassStartingWith (String root)
Finds only APs that have APClass starting with the given string.
void setAsRCV (boolean isRCV)
void setVertexId (long vertexId2)
long getVertexId ()
int getBuildingBlockId ()
Returns the index of the building block that should correspond to the position of the building block in the library of building blocks of its kind.
void setBuildingBlockId (int buildingBlockId)
Vertex.BBType getBuildingBlockType ()
void setBuildingBlockType (Vertex.BBType buildingBlockType)
abstract List< SymmetricAPs > getSymmetricAPSets ()
SymmetricAPs getSymmetricAPs (AttachmentPoint ap)
For the given attachment point index locate the symmetric partners i.e.
int getNumberOfAPs ()
int getFreeAPCount ()
ArrayList< AttachmentPoint > getFreeAPThroughout ()
Gets attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
int getFreeAPCountThroughout ()
Counts the number of attachment points that are availability throughout the graph level, i.e., checks also across the inner graph template boundary.
ArrayList< AttachmentPoint > getCappedAPs ()
Gets attachment points that are used by capping groups.
ArrayList< AttachmentPoint > getCappedAPsThroughout ()
Gets attachment points that are used by capping groups throughout the graph levels, i.e., checks also across the inner graph template boundary.
int getCappedAPCountThroughout ()
Counts the number of attachment points that are used by BBType#CAP vertex.
boolean hasFreeAP ()
boolean isRCV ()
boolean isAromaticBridge ()
Checks if this vertex is meant to be a piece of an aromatic system.
boolean isConnectedToAromaticBridge ()
Checks if this vertex is connected to any vertex meant to be a piece of an aromatic system.
boolean hasSymmetricAP ()
String toString ()
Produces a human readable, short string to represent the vertex by its vertex ID, building block ID (1-based), building block type, and level in the graph (if any).
void cleanup ()
abstract Vertex clone ()
Returns a deep-copy of this vertex.
boolean sameAs (Vertex other)
Compares this and another vertex ignoring vertex IDs.
boolean sameAs (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
boolean sameVertexFeatures (Vertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
abstract int getHeavyAtomsCount ()
abstract boolean containsAtoms ()
abstract IAtomContainer getIAtomContainer ()
abstract IAtomContainer getIAtomContainer (Logger logger, Randomizer rng, boolean removeUsedRCAs, boolean rebuild)
Method meant to trigger regeneration of the chemical representation, typically needed to drop a low quality structure that is good enough for most cheminformatic tasks, and replace it with a better quality structure that is suitable to be fed to molecular modeling tasks.
ArrayList< APClass > getAllAPClasses ()
Returns the list of all APClasses present on this vertex.
ArrayList< APClass > getAllAvailableAPClasses ()
Returns the list of all APClasses present on free attachment point on this vertex.
void resetGraphOwner ()
void setGraphOwner (DGraph owner)
DGraph getGraphOwner ()
Returns the graph this vertex belongs to or null.
List< Vertex > getMutationSites ()
A list of mutation sites from within this vertex.
abstract List< Vertex > getMutationSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this vertex.
void setMutationTypes (List< MutationType > lst)
boolean removeMutationType (MutationType mt)
Removes the specified mutation type.
List< MutationType > getMutationTypes ()
Returns the list of mutation types.
List< MutationType > getMutationTypes (List< MutationType > excludedTypes)
Returns the list of mutation types.
AttachmentPoint getAP (int i)
Get attachment point i on this vertex.
AttachmentPoint getAPWithId (int i)
Get attachment point that has the given identifier, or null.
int getIndexOfAP (AttachmentPoint ap)
Returns the position of the given AP in the list of APs of this vertex.
Edge getEdgeToParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the edge that has this vertex as the target, i.e., the edge to the parent vertex.
Vertex getParent ()
Looks into the edges that use any of the APs that belong to this vertex and returns the vertex which is the source of the edge in which this vertex is the target.
ArrayList< AttachmentPoint > getAPsFromChildren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of attachment point on child vertices that form an edge with any of the APs of this vertex.
ArrayList< Vertex > getChildrenThroughout ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
ArrayList< Vertex > getChilddren ()
Looks into the edges that use any of the APs that belong to this vertex and returns the list of vertices which are target of any edge departing from this vertex.
void setUniquefyingProperty (String key)
Add the given key among the properties that are checked for equality when comparing vertices with the Vertex#sameAs(Vertex, StringBuilder) method.
Map< Object, Object > getProperties ()
boolean hasProperty (Object property)
Object getProperty (Object property)
void setProperty (Object key, Object property)
void removeProperty (Object key)
void setProperties (Map< Object, Object > properties)
VertexType getVertexType ()
Returns the value of the vertex type.
String[] getPathIDs (AttachmentPoint apA, AttachmentPoint apB)
Produces a pair of strings that identify the "path" between two given attachment points.
boolean connectedTo (Vertex other)
Checks if this and another vertex are directly connected by an edge within the same graph recursion level, i.e., both vertices must belong to the same graph.
Edge getEdgeWith (Vertex other)
Finds the edge between this and the other vertex, if it exists.
Static Public Member Functions
static EmptyVertex fromJson (String json)
Reads a JSON string and returns an instance of this class.
Static Public Member Functions inherited from denoptim.graph.Vertex
static Vertex newVertexFromLibrary (int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException
Builds a new molecular fragment kind of vertex.
static Vertex newVertexFromLibrary (long vertexId, int bbId, Vertex.BBType bbt, FragmentSpace fragSpace) throws DENOPTIMException
Make a new vertex that is a copy of a vertex in the fragment space.
static Vertex fromJson (String json)
static Vertex convertIACToVertex (IAtomContainer iac, Vertex.BBType bbt) throws DENOPTIMException
Processes an IAtomContainer and builds a Vertex that is an instance of Fragment.
static Vertex parseVertexFromSDFFormat (IAtomContainer mol, Gson reader, BBType bbt) throws DENOPTIMException
Created a Vertex from the SDF representation, i.e., from an IAtomContainer.
Protected Member Functions
void setSymmetricAPSets (List< SymmetricAPs > sAPs)
void addSymmetricAPSet (SymmetricAPs symAPs)
Protected Member Functions inherited from denoptim.graph.Vertex
abstract void setSymmetricAPSets (List< SymmetricAPs > sAPs)
abstract void addSymmetricAPSet (SymmetricAPs symAPs)
int getUniqueAPIndex ()
List< MutationType > getUnfilteredMutationTypes ()
Returns the mutation types that are constitutionally configures for this vertex irrespectively on the graph or the context in which this vertex is included.
Map< Object, Object > copyStringBasedProperties ()
Copies all the string-based properties and properties defined in the Vertex#uniquefyingPropertyKeys set.
Private Attributes
List< AttachmentPoint > lstAPs
Attachment points on this vertex.
List< SymmetricAPs > lstSymAPs
List of AP sets that are related to each other, so that we call them "symmetric" (though symmetry is a fuzzy concept here).
Additional Inherited Members
Protected Attributes inherited from denoptim.graph.Vertex
int buildingBlockId = -99
Index of this building block in the library of building blocks, or negative if this vertex is not part of a library.
BBType buildingBlockType = Vertex.BBType.UNDEFINED
Map< Object, Object > properties
Map of customizable properties.
Set< String > uniquefyingPropertyKeys = new HashSet<String>()
List of properties required to make Vertex#sameAs(Vertex, StringBuilder) method return false when property values differ.
final VertexType vertexType
Field distinguishing implementations of Vertex when deserializing JSON representations.
Detailed Description
An empty vertex has the behaviors of a vertex, but has no molecular structure.
It has attachment points, as well as relations between those attachment points, but has no atoms.
Definition at line 44 of file EmptyVertex.java.
Constructor & Destructor Documentation
EmptyVertex() [1/4]
denoptim.graph.EmptyVertex.EmptyVertex ()
Constructor for an empty vertex.
Definition at line 62 of file EmptyVertex.java.
References denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.EmptyVertex.lstAPs, and denoptim.graph.EmptyVertex.lstSymAPs.
Referenced by denoptim.graph.EmptyVertex.clone().
EmptyVertex() [2/4]
denoptim.graph.EmptyVertex.EmptyVertex (BBType type)
Constructor for an identified vertex without attachment points.
Parameters
id the VertedID of the vertex to construct. Note that this ID should be unique within a graph. To generate unique IDs either use GraphUtils#getUniqueVertexIndex() or use constructor EmptyVertex().
Definition at line 78 of file EmptyVertex.java.
References denoptim.graph.Vertex.buildingBlockType, denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.EmptyVertex.lstAPs, and denoptim.graph.EmptyVertex.lstSymAPs.
EmptyVertex() [3/4]
denoptim.graph.EmptyVertex.EmptyVertex (long id)
Constructor for an identified vertex without attachment points.
Parameters
id the VertedID of the vertex to construct. Note that this ID should be unique within a graph. To generate unique IDs either use GraphUtils#getUniqueVertexIndex() or use constructor EmptyVertex().
Definition at line 95 of file EmptyVertex.java.
References denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.EmptyVertex.lstAPs, and denoptim.graph.EmptyVertex.lstSymAPs.
EmptyVertex() [4/4]
denoptim.graph.EmptyVertex.EmptyVertex (long id, ArrayList< AttachmentPoint > lstAPs, ArrayList< SymmetricAPs > lstSymAPs, boolean isRCV)
Constructor for an identified vertex.
Parameters
id the VertedID of the vertex to construct. Note that this ID should be unique within a graph. To generate unique IDs either use
lstAPs the list of attachment point on this vertex.
lstSymAPs the list of symmetric sets of APs.
isRCV set true to mark this vertex as a ring-closing vertex.
Definition at line 113 of file EmptyVertex.java.
References denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.Vertex.isRCV, denoptim.graph.EmptyVertex.lstAPs, denoptim.graph.EmptyVertex.lstSymAPs, and denoptim.graph.Vertex.setAsRCV().
Member Function Documentation
addAP() [1/2]
void denoptim.graph.EmptyVertex.addAP ()
Adds an attachment point with no APClass or other attribute.
This is used only for testing purposes.
Definition at line 298 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.getAttachmentPoints().
Referenced by denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.Template.getTestTemplate(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.EdgeTest.setUpClass(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained(), denoptim.graph.TemplateTest.testAtLeastSameNumberOfAPs(), denoptim.graph.AttachmentPointTest.testAvailableThrougout(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.graph.AttachmentPointTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.VertexTest.testClone(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.RelatedAPPairTest.testEquals(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs(), denoptim.graph.VertexTest.testGetAPsWithAPClassStartingWith(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsAPsWithTemplateAsOwner(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsCorrectNumberOfAPs(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout(), denoptim.graph.AttachmentPointTest.testGetEmbeddedAP(), denoptim.graph.AttachmentPointTest.testGetLinkedAP(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.AttachmentPointTest.testIsSrcInUser(), denoptim.graph.AttachmentPointTest.testSameAs(), denoptim.graph.AttachmentPointTest.testSameAs_DiffAPClass(), denoptim.graph.VertexTest.testSameAs_DiffAPNum(), denoptim.graph.AttachmentPointTest.testSameAs_DiffSrcAtm(), denoptim.graph.VertexTest.testSameAs_Equal(), denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex(), denoptim.graph.TemplateTest.testSetInnerGraph_throws_on_graph_incompatible_w_requiredAPs(), denoptim.graph.EdgeTest.testUndirectedComparison(), and denoptim.graph.UndirectedEdgeRelationTest.testUndirectedComparison().
addAP() [2/2]
void denoptim.graph.EmptyVertex.addAP (APClass apClass)
Adds an attachment point with the specified APClass.
Parameters
apClass the APClass
Definition at line 309 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.getAttachmentPoints().
addSymmetricAPSet()
void denoptim.graph.EmptyVertex.addSymmetricAPSet (SymmetricAPs symAPs) protected
Reimplemented from denoptim.graph.Vertex.
Definition at line 459 of file EmptyVertex.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), and denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs().
cleanup()
void denoptim.graph.EmptyVertex.cleanup ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 237 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs, and denoptim.graph.EmptyVertex.lstSymAPs.
clone()
EmptyVertex denoptim.graph.EmptyVertex.clone ()
Returns a deep-copy of this vertex.
Returns
a deep-copy
Reimplemented from denoptim.graph.Vertex.
Definition at line 256 of file EmptyVertex.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.Vertex.copyStringBasedProperties(), denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.getUnfilteredMutationTypes(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.Vertex.isRCV, denoptim.graph.EmptyVertex.lstAPs, denoptim.graph.EmptyVertex.lstSymAPs, denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setBuildingBlockId(), denoptim.graph.Vertex.setBuildingBlockType(), denoptim.graph.AttachmentPoint.setCutId(), denoptim.graph.AttachmentPoint.setID(), denoptim.graph.Vertex.setMutationTypes(), denoptim.graph.Vertex.setProperties(), denoptim.graph.EmptyVertex.setSymmetricAPSets(), and denoptim.graph.Vertex.uniquefyingPropertyKeys.
Referenced by denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.graph.VertexTest.testClone(), denoptim.graph.AttachmentPointTest.testSameAs(), and denoptim.graph.AttachmentPointTest.testSameAs_DiffAPClass().
containsAtoms()
boolean denoptim.graph.EmptyVertex.containsAtoms ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 354 of file EmptyVertex.java.
fromJson()
static EmptyVertex denoptim.graph.EmptyVertex.fromJson (String json) static
Reads a JSON string and returns an instance of this class.
Parameters
json the string to parse.
Returns
a new instance of this class.
Reimplemented from denoptim.graph.Vertex.
Definition at line 416 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.fromJson(), denoptim.graph.EmptyVertex.getAttachmentPoints(), and denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.graph.Vertex.DENOPTIMVertexDeserializer.deserialize(), and denoptim.graph.EmptyVertex.fromJson().
getAllAPClasses()
ArrayList< APClass > denoptim.graph.EmptyVertex.getAllAPClasses ()
Returns the list of all APClasses on present on this fragment.
Returns
the list of APClassess
Reimplemented from denoptim.graph.Vertex.
Definition at line 434 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
getAttachmentPoints()
List< AttachmentPoint > denoptim.graph.EmptyVertex.getAttachmentPoints ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 124 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
Referenced by denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.fromJson(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), and denoptim.graph.AttachmentPointTest.testGetEmbeddedAP().
getFreeAPCount()
int denoptim.graph.EmptyVertex.getFreeAPCount ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 194 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
getFreeAPList()
ArrayList< Integer > denoptim.graph.EmptyVertex.getFreeAPList ()
Returns
list of attachment points that have free valences
Definition at line 181 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
getHeavyAtomsCount()
int denoptim.graph.EmptyVertex.getHeavyAtomsCount ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 347 of file EmptyVertex.java.
getIAtomContainer() [1/2]
IAtomContainer denoptim.graph.EmptyVertex.getIAtomContainer ()
Although empty vertex do not contain atoms, by definitions, we allow the generation of an SDF representation that uses an empty atom list.
Returns
an empty atom container that contains the definition of the vertex in the JSON-formatted property.
Reimplemented from denoptim.graph.Vertex.
Definition at line 369 of file EmptyVertex.java.
References denoptim.constants.DENOPTIMConstants.APSTAG, and denoptim.constants.DENOPTIMConstants.VERTEXJSONTAG.
Referenced by denoptim.graph.EmptyVertex.getIAtomContainer().
getIAtomContainer() [2/2]
IAtomContainer denoptim.graph.EmptyVertex.getIAtomContainer (Logger logger, Randomizer rng, boolean removeUsedRCAs, boolean rebuild)
Although empty vertex do not contain atoms, by definitions, we allow the generation of an SDF representation that uses an empty atom list.
However, this method is ignoring all the parameters and calling getIAtomContainer()
Reimplemented from denoptim.graph.Vertex.
Definition at line 387 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.getIAtomContainer().
getMutationSites()
List< Vertex > denoptim.graph.EmptyVertex.getMutationSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this vertex.
Parameters
ignoredTypes a collection of mutation types to ignore. vertices that allow only ignored types of mutation will not be considered mutation sites.
Returns
the list of vertices that allow any non-ignored mutation type.
Reimplemented from denoptim.graph.Vertex.
Definition at line 487 of file EmptyVertex.java.
References denoptim.graph.Vertex.getBuildingBlockType(), and denoptim.graph.Vertex.getMutationTypes().
getNumberOfAPs()
int denoptim.graph.EmptyVertex.getNumberOfAPs ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 169 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
Referenced by denoptim.graph.VertexTest.testClone().
getSymmetricAP()
List< SymmetricAPs > denoptim.graph.EmptyVertex.getSymmetricAP ()
Definition at line 138 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstSymAPs.
getSymmetricAPs()
SymmetricAPs denoptim.graph.EmptyVertex.getSymmetricAPs (AttachmentPoint ap)
For the given attachment point index locate the symmetric partners i.e.
those with similar environments and class types.
Parameters
ap index of the attachment point which we want to get the symmetrically related partners of.
Returns
the list of attachment point IDs, which include apIdx or null if no partners present
Reimplemented from denoptim.graph.Vertex.
Definition at line 155 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstSymAPs.
getSymmetricAPSets()
List< SymmetricAPs > denoptim.graph.EmptyVertex.getSymmetricAPSets ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 471 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstSymAPs.
Referenced by denoptim.graph.VertexTest.testClone().
hasFreeAP()
boolean denoptim.graph.EmptyVertex.hasFreeAP ()
Reimplemented from denoptim.graph.Vertex.
Definition at line 206 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstAPs.
hasSymmetricAP()
boolean denoptim.graph.EmptyVertex.hasSymmetricAP ()
Returns
true if vertex has symmetric APs
Reimplemented from denoptim.graph.Vertex.
Definition at line 222 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstSymAPs.
sameAs()
boolean denoptim.graph.EmptyVertex.sameAs (EmptyVertex other, StringBuilder reason)
Compares this and another vertex ignoring vertex IDs.
A difference in any property that has been marked as an uniquefying property with the {} method makes this method return false.
Parameters
other
reason string builder used to build the message clarifying the reason for returning false.
Returns
true if the two vertices represent the same graph node even if the vertex IDs are different.
Definition at line 328 of file EmptyVertex.java.
References denoptim.graph.Vertex.properties, denoptim.graph.Vertex.sameVertexFeatures(), and denoptim.graph.Vertex.uniquefyingPropertyKeys.
Referenced by denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.graph.VertexTest.testSameAs_DiffAPNum(), and denoptim.graph.VertexTest.testSameAs_Equal().
setSymmetricAP()
void denoptim.graph.EmptyVertex.setSymmetricAP (List< SymmetricAPs > sAPs)
Definition at line 131 of file EmptyVertex.java.
References denoptim.graph.EmptyVertex.lstSymAPs.
setSymmetricAPSets()
void denoptim.graph.EmptyVertex.setSymmetricAPSets (List< SymmetricAPs > sAPs) protected
Reimplemented from denoptim.graph.Vertex.
Definition at line 451 of file EmptyVertex.java.
Referenced by denoptim.graph.EmptyVertex.clone().
toJson()
String denoptim.graph.EmptyVertex.toJson ()
Produces a string that represents this vertex and that adheres to the JSON format.
Returns
the JSON format as a single string
Definition at line 401 of file EmptyVertex.java.
References denoptim.json.DENOPTIMgson.getWriter().
Referenced by denoptim.graph.VertexTest.testFromToJSON_minimal(), and denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs().
toString()
String denoptim.graph.EmptyVertex.toString ()
Produces a human readable, short string to represent the vertex by its vertex ID, building block ID (1-based), building block type, and level in the graph (if any).
This is the old syntax used up to version 2 for reporting a vertex in the string representation of a graph. Such notation cannot hold all the information needed to define a template, and is, therefore, obsolete. Use JSON format to serialize a graph that may contain templates.
Reimplemented from denoptim.graph.Vertex.
Definition at line 230 of file EmptyVertex.java.
References denoptim.graph.Vertex.getVertexId().
Member Data Documentation
lstAPs
List<AttachmentPoint> denoptim.graph.EmptyVertex.lstAPs private
Attachment points on this vertex.
Definition at line 49 of file EmptyVertex.java.
Referenced by denoptim.graph.EmptyVertex.cleanup(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.EmptyVertex.getAllAPClasses(), denoptim.graph.EmptyVertex.getAttachmentPoints(), denoptim.graph.EmptyVertex.getFreeAPCount(), denoptim.graph.EmptyVertex.getFreeAPList(), denoptim.graph.EmptyVertex.getNumberOfAPs(), and denoptim.graph.EmptyVertex.hasFreeAP().
lstSymAPs
List<SymmetricAPs> denoptim.graph.EmptyVertex.lstSymAPs private
List of AP sets that are related to each other, so that we call them "symmetric" (though symmetry is a fuzzy concept here).
Definition at line 55 of file EmptyVertex.java.
Referenced by denoptim.graph.EmptyVertex.cleanup(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.EmptyVertex.EmptyVertex(), denoptim.graph.EmptyVertex.getSymmetricAP(), denoptim.graph.EmptyVertex.getSymmetricAPs(), denoptim.graph.EmptyVertex.getSymmetricAPSets(), denoptim.graph.EmptyVertex.hasSymmetricAP(), and denoptim.graph.EmptyVertex.setSymmetricAP().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/EmptyVertex.java