DENOPTIM: denoptim.graph.simplified.Node Class Reference
denoptim.graph.simplified.Node Class Reference
This class represents a subgraph feature that defined the structure of a graph.
Public Member Functions
Node (Vertex v)
Node (AttachmentPoint ap)
Vertex getDNPVertex ()
int compare (Node other)
String toString ()
Public Attributes
String invariant = null
Invariant representation used to compare.
Static Public Attributes
static final String REFTOVERTEXKERNEL = "REFTOVERTEXKERNEL"
Property if Vertex used to store the reference to the corresponding Node.
Private Attributes
Vertex vertex = null
Reference to the vertex we might be representing.
Detailed Description
This class represents a subgraph feature that defined the structure of a graph.
Namely, it represents either a Vertex or a AttachmentPoint that needs to exist for the structure of a subgraph to be retained.
Definition at line 31 of file Node.java.
Constructor & Destructor Documentation
Node() [1/2]
denoptim.graph.simplified.Node.Node (Vertex v)
Definition at line 51 of file Node.java.
References denoptim.graph.Vertex.isRCV, denoptim.graph.simplified.Node.REFTOVERTEXKERNEL, and denoptim.graph.Vertex.setProperty().
Node() [2/2]
denoptim.graph.simplified.Node.Node (AttachmentPoint ap)
Definition at line 62 of file Node.java.
References denoptim.graph.AttachmentPoint.getAPClass(), and denoptim.graph.APClass.toString().
Member Function Documentation
compare()
int denoptim.graph.simplified.Node.compare (Node other)
Definition at line 76 of file Node.java.
References denoptim.graph.simplified.Node.invariant, and denoptim.graph.simplified.Node.vertex.
Referenced by denoptim.graph.DGraph.isIsostructuralTo().
getDNPVertex()
Vertex denoptim.graph.simplified.Node.getDNPVertex ()
Definition at line 69 of file Node.java.
References denoptim.graph.simplified.Node.vertex.
Referenced by denoptim.graph.DGraph.isIsostructuralTo().
toString()
String denoptim.graph.simplified.Node.toString ()
Definition at line 89 of file Node.java.
References denoptim.graph.simplified.Node.invariant.
Member Data Documentation
invariant
String denoptim.graph.simplified.Node.invariant = null
Invariant representation used to compare.
Definition at line 41 of file Node.java.
Referenced by denoptim.graph.simplified.Node.compare(), and denoptim.graph.simplified.Node.toString().
REFTOVERTEXKERNEL
final String denoptim.graph.simplified.Node.REFTOVERTEXKERNEL = "REFTOVERTEXKERNEL" static
Property if Vertex used to store the reference to the corresponding Node.
Definition at line 47 of file Node.java.
Referenced by denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.DGraph.isIsostructuralTo(), and denoptim.graph.simplified.Node.Node().
vertex
Vertex denoptim.graph.simplified.Node.vertex = null private
Reference to the vertex we might be representing.
Definition at line 36 of file Node.java.
Referenced by denoptim.graph.simplified.Node.compare(), and denoptim.graph.simplified.Node.getDNPVertex().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/simplified/Node.java