DENOPTIM: denoptim.fragspace.FragmentSpace Class Reference
denoptim.fragspace.FragmentSpace Class Reference
Class defining a space of building blocks.
Public Member Functions
FragmentSpace ()
Creates an empty fragment space, which is marked as invalid.
FragmentSpace (FragmentSpaceParameters settings, String scaffFile, String fragFile, String capFile, String cpmFile) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
FragmentSpace (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
FragmentSpace (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
FragmentSpace (FragmentSpaceParameters settings, String scaffFile, String fragFile, String capFile, String cpmFile, String rcpmFile, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
boolean isDefined ()
Checks for valid definition of this fragment space.
Randomizer getRandomizer ()
Returns the program-specific randomizer that is associated with this program-specific fragment space.
void setAPclassBasedApproach (boolean useAPC)
Set the fragment space to behave according to APClass-based approach.
boolean useAPclassBasedApproach ()
Check usage of APClass-based approach, i.e., uses attachment points with annotated data (i.e., the APClass) to evaluate compatibilities between attachment points.
APClass getAPClassForFragment (IdFragmentAndAP apId)
Search for a specific AP on a specific fragment and finds out its class.
Vertex getVertexFromLibrary (Vertex.BBType bbType, int bbIdx) throws DENOPTIMException
Returns a clone of the requested building block.
int getCappingFragment (APClass rcnCap)
Select a compatible capping group for the given APClass.
ArrayList< Integer > getCompatibleCappingFragments (APClass cmpReac)
Retrieve a list of compatible capping groups.
Vertex makeRandomScaffold ()
Randomly select a scaffold and return a fully configured clone of it.
ArrayList< Vertex > getScaffoldLibrary ()
ArrayList< Vertex > getFragmentLibrary ()
ArrayList< Vertex > getCappingLibrary ()
ArrayList< Integer > getCappingGroupsWithAPClass (APClass capApCls)
Vertex getCappingVertexWithAPClass (APClass capApCls)
void importCompatibilityMatrixFromFile (String inFile) throws DENOPTIMException
Load info from a compatibility matrix file.
void importRCCompatibilityMatrixFromFile (String inFile) throws DENOPTIMException
Load info for ring closures compatibilities from a compatibility matrix file.
HashMap< APClass, ArrayList< APClass > > getCompatibilityMatrix ()
ArrayList< APClass > getCompatibleAPClasses (APClass apc)
Returns a list of APClasses compatible with the given APClass.
HashMap< APClass, ArrayList< APClass > > getRCCompatibilityMatrix ()
Returns the compatibility matrix for ring closing fragment-fragment connections or null if not provided in the parameters file.
HashMap< APClass, APClass > getCappingMap ()
APClass getAPClassOfCappingVertex (APClass srcApClass)
Set< APClass > getForbiddenEndList ()
Set< APClass > getAllAPClassesFromCPMap ()
Return the set of APClasses that used in the compatibility matrix for the growing graph APs.
HashMap< Integer, ArrayList< Integer > > getMapOfFragsPerNumAps ()
ArrayList< Integer > getFragsWithNumAps (int nAps)
Returns the list of fragments with given number of APs.
ArrayList< APClass > getAPClassesPerFragment (int fragId)
Returns the APclasses associated with a given fragment.
ArrayList< IdFragmentAndAP > getFragsWithAPClass (APClass apc)
Returns the list of attachment points with the given class.
ArrayList< Vertex > getVerticesWithAPClass (APClass apc)
Returns the list of vertexes with attachment points of the given class.
List< Vertex > getVerticesWithAPClasses (Set< APClass > apcs)
Returns the list of vertexes with at least one attachment point of each of the given classes.
List< Vertex > getVerticesWithAPFingerprint (Map< APClass, Integer > apcCounts)
Returns the list of vertexes that have the specified number of AttachmentPoints with the given APClasses.
List< Vertex > getVerticesWithAPClassStartingWith (String root)
Extracts vertexes from the collection of vertexes defined by this FragmentSpace.
ArrayList< Vertex > getFragmentsCompatibleWithTheseAPs (ArrayList< IdFragmentAndAP > srcAPs)
Searches for all building blocks that are compatible with the given list of APs.
List< Vertex > getRCVsWithAPClass (APClass apc)
Searches for all building blocks that are ring-closing vertexes and hold an AP with the given class.
List< Vertex > getRCVsForAPClass (APClass apc)
Searches for all building blocks that are ring-closing vertexes and are compatible with the given AP.
ArrayList< AttachmentPoint > getAPsCompatibleWithThese (ArrayList< AttachmentPoint > srcAPs)
Searches for all attachment points that are compatible with the given list of attachment points.
ArrayList< IdFragmentAndAP > getFragAPsCompatibleWithTheseAPs (ArrayList< IdFragmentAndAP > srcAPs)
Searches for all APs that are compatible with the given list of APs.
ArrayList< AttachmentPoint > getAPsCompatibleWithClass (APClass aPC1)
Returns the list of attachment points found in the fragment space and that are compatible with a given AP class.
ArrayList< IdFragmentAndAP > getFragAPsCompatibleWithClass (APClass aPC1)
Returns the list of attachment points found in the fragment space and that are compatible with a given AP class.
boolean imposeSymmetryOnAPsOfClass (APClass apClass)
Checks if the symmetry settings impose use of symmetry on attachment points of the given AP class.
boolean hasSymmetryConstrain (APClass apClass)
Checks if there is a constraint on the constitutional symmetry probability for the given AP class.
double getSymmetryConstrain (APClass apClass)
Return the constitutional symmetry constrain for the given APclass, or null.
void setScaffoldLibrary (ArrayList< Vertex > lib)
void setFragmentLibrary (ArrayList< Vertex > lib)
void setCappingLibrary (ArrayList< Vertex > lib)
void setCompatibilityMatrix (HashMap< APClass, ArrayList< APClass > > map)
void setRCCompatibilityMatrix (HashMap< APClass, ArrayList< APClass > > map)
void setCappingMap (HashMap< APClass, APClass > map)
void setForbiddenEndList (Set< APClass > lst)
void setSymmConstraints (HashMap< APClass, Double > map)
void clearAll ()
Clears all settings of this fragment space.
void appendVerticesToLibrary (ArrayList< Vertex > list, Vertex.BBType bbt, ArrayList< Vertex > library)
Takes a list of vertices and add them to a given library.
void appendVertexToLibrary (Vertex v, Vertex.BBType bbt, ArrayList< Vertex > library)
Takes a vertex and add it to a given library.
void addFusedRingsToFragmentLibrary (DGraph graph)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
void addFusedRingsToFragmentLibrary (DGraph graph, boolean addIfScaffold, boolean addIfFragment)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
void addFusedRingsToFragmentLibrary (DGraph graph, boolean addIfScaffold, boolean addIfFragment, IAtomContainer wholeMol)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
boolean hasIsomorph (DGraph graph, BBType type)
Checks if a graph is isomorphic to another template's inner graph in its appropriate fragment space library (inferred from BBType).
void registerRCV (Vertex v)
Adds the reference to a ring-closing vertex (RCV) to the quick-access list of RCVs known in this building block space.
ArrayList< Vertex > getRCVs ()
Returns the list of registered ring-closing vertexes (RCVs).
List< APMapping > mapAPClassCompatibilities (List< AttachmentPoint > listA, List< AttachmentPoint > listB, int maxCombinations)
Given two lists of APs this method maps the APClass-compatibilities from between the two lists considering the APs in the first list the for the role of source AP in the hypothetical edge.
void classifyFragment (Vertex frg, int fragId)
Classify a fragment in terms of the number of APs and possibly their type (AP-Class).
void groupAndClassifyFragments (boolean apClassBasedApproch) throws DENOPTIMException
Performs grouping and classification operations on the library of building blocks of BBType#FRAGMENT.
Static Public Member Functions
static Vertex getPolarizedRCV (boolean polarity)
Returns a newly-built vertex that can play the role of a ring-closing vertex even when working with 3D building blocks.
Private Member Functions
void define (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException
Define all components of this fragment space.
Private Attributes
ArrayList< Vertex > scaffoldLib = null
Data structure containing the molecular representation of building blocks: scaffolds section - fragments that can be used as seeds to grow a new molecule.
ArrayList< Vertex > fragmentLib = null
Data structure containing the molecular representation of building blocks: fragment section - fragments for general use.
ArrayList< Vertex > cappingLib = null
Data structure containing the molecular representation of building blocks: capping group section - fragments with only one attachment point used to saturate unused attachment points on a graph.
HashMap< APClass, ArrayList< APClass > > apClassCompatibilityMatrix
Data structure that stored the true entries of the attachment point classes compatibility matrix.
ArrayList< Vertex > rcvs = new ArrayList<Vertex>()
Store references to the Ring-Closing Vertexes found in the library of fragments.
HashMap< APClass, ArrayList< APClass > > rcCompatMap
Data structure that stores compatible APclasses for joining APs in ring-closing bonds.
HashMap< APClass, APClass > cappingMap
Data structure that stores the AP-classes to be used to cap unused APS on the growing molecule.
Set< APClass > forbiddenEndList
Data structure that stores AP classes that cannot be held unused.
HashMap< Integer, ArrayList< Integer > > fragPoolPerNumAP
Clusters of fragments based on the number of APs.
HashMap< Integer, ArrayList< APClass > > apClassesPerFrag
List of APClasses per each fragment.
HashMap< APClass, ArrayList< ArrayList< Integer > > > fragsApsPerApClass
Clusters of fragments'AP based on AP classes.
final Object LOCK = new Object()
Lock for synchronizing tasks.
HashMap< APClass, Double > symmConstraints
APclass-specific constraints to constitutional symmetry.
boolean apClassBasedApproch = false
Flag defining use of AP class-based approach.
boolean isValid = false
Flag signaling that this fragment space was built and validated.
FragmentSpaceParameters settings = null
Settings used to configure this fragment space.
Detailed Description
Class defining a space of building blocks.
The space comprises of the lists of building blocks and the rules governing the connection of building blocks to forms a DGraph.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 67 of file FragmentSpace.java.
Constructor & Destructor Documentation
FragmentSpace() [1/5]
denoptim.fragspace.FragmentSpace.FragmentSpace ()
Creates an empty fragment space, which is marked as invalid.
Such fragment space has very limited functionality, but can be used to manipulate information related to fragment spaces, such as, handling compatibility rules even without having any defined vertex in it.
Definition at line 180 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingLib, denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.fragspace.FragmentSpace.scaffoldLib, and denoptim.fragspace.FragmentSpace.settings.
FragmentSpace() [2/5]
denoptim.fragspace.FragmentSpace.FragmentSpace (FragmentSpaceParameters settings, String scaffFile, String fragFile, String capFile, String cpmFile) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
Parameters
scaffFile pathname to library of fragments used to start the construction of any new graph (i.e., seed or root fragments, a.k.a. scaffolds).
fragFile pathname to the library of fragments for general purpose.
capFile pathname to the library of single-AP fragments used to cap free attachment points (i.e., the capping groups).
cpmFile pathname to the compatibility matrix, bond type mapping, capping, and forbidden ends rules.
Exceptions
DENOPTIMException
Definition at line 205 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.settings.
FragmentSpace() [3/5]
denoptim.fragspace.FragmentSpace.FragmentSpace (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
Parameters
scaffLib library of fragments used to start the construction of any new graph (i.e., seed or root fragments, a.k.a. scaffolds).
fragLib library of fragments for general purpose.
cappLib library of single-AP fragments used to cap free attachment points (i.e., the capping groups).
cpMap the APClass compatibility map. This data structure is a map of the APClass-on-growing-graph (key) to list of permitted APClasses on incoming fragment (values).
capMap the capping rules. This data structure is a map of APClass-to-cap (keys) to APClass-of-capping-group (values).
forbEnds the list of forbidden ends, i.e., APClasses that cannot be left unused neither capped.
rcCpMap the APClass compatibility matrix for ring closures.
Exceptions
DENOPTIMException
Definition at line 236 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.settings.
FragmentSpace() [4/5]
denoptim.fragspace.FragmentSpace.FragmentSpace (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
Parameters
scaffLib library of fragments used to start the construction of any new graph (i.e., seed or root fragments, a.k.a. scaffolds).
fragLib library of fragments for general purpose.
cappLib library of single-AP fragments used to cap free attachment points (i.e., the capping groups).
cpMap the APClass compatibility map. This data structure is a map of the APClass-on-growing-graph (key) to list of permitted APClasses on incoming fragment (values).
capMap the capping rules. This data structure is a map of APClass-to-cap (keys) to APClass-of-capping-group (values).
forbEnds the list of forbidden ends, i.e., APClasses that cannot be left unused neither capped.
rcCpMap the APClass compatibility matrix for ring closures.
symCntrMap map of symmetry probability constraints.
Exceptions
DENOPTIMException
Definition at line 274 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.settings.
FragmentSpace() [5/5]
denoptim.fragspace.FragmentSpace.FragmentSpace (FragmentSpaceParameters settings, String scaffFile, String fragFile, String capFile, String cpmFile, String rcpmFile, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException
Define all components of a fragment space that implements the attachment point class-approach.
Parameters
scaffFile pathname to library of fragments used to start the construction of any new graph (i.e., seed or root fragments, a.k.a. scaffolds). Can be null or empty in which case no scaffold is imported.
fragFile pathname to the library of fragments for general purpose. Can be null or empty in which case no fragment is imported.
capFile pathname to the library of single-AP fragments used to cap free attachment points (i.e., the capping groups).
cpmFile pathname to the compatibility matrix, capping, and forbidden ends rules.
rcpmFile the APClass compatibility matrix for ring closures.
symCntrMap map of symmetry probability constraints.
Exceptions
DENOPTIMException
Definition at line 310 of file FragmentSpace.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.fragspace.FragmentSpace.define(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.io.DenoptimIO.readCompatibilityMatrix(), denoptim.io.DenoptimIO.readRCCompatibilityMatrix(), denoptim.io.DenoptimIO.readVertexes(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.fragspace.FragmentSpace.settings.
Member Function Documentation
addFusedRingsToFragmentLibrary() [1/3]
void denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary (DGraph graph)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
This method does not create any molecular geometry in the building block that is stores in the library. See FragmentSpace#addFusedRingsToFragmentLibrary(DGraph, boolean, boolean, IAtomContainer) to include a molecular representation on the stored building block. WARNING Expanding the libraries of building blocks on-the-fly has the potential to overload the memory.
Definition at line 1629 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.programs.fitnessevaluator.FitnessEvaluationTask.call(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
addFusedRingsToFragmentLibrary() [2/3]
void denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary (DGraph graph, boolean addIfScaffold, boolean addIfFragment)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
WARNING Expanding the libraries of building blocks on-the-fly has the potential to overload the memory.
Parameters
graph the graph to analyze and possibly chop.
addIfScaffold use true to enable saving of new ring systems that contain any scaffold vertexes as new scaffolds.
addIfFragment use true to enable saving of new ring systems that do NOT contain any scaffold vertexes as new fragments.
Definition at line 1648 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary().
addFusedRingsToFragmentLibrary() [3/3]
void denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary (DGraph graph, boolean addIfScaffold, boolean addIfFragment, IAtomContainer wholeMol)
Extracts a system of one or more fused rings and adds them to the fragment space if not already present.
WARNING Expanding the libraries of building blocks on-the-fly has the potential to overload the memory.
Parameters
graph the graph to analyze and possibly chop.
addIfScaffold use true to enable saving of new ring systems that contain any scaffold vertexes as new scaffolds.
addIfFragment use true to enable saving of new ring systems that do NOT contain any scaffold vertexes as new fragments.
wholeMol the complete molecular representation of graph. If this parameter is not null, then we'll try to use the geometry found in this parameter to define the geometry of the fused-rings templates. The atoms in this container are expected to have property DENOPTIMConstants#ATMPROPVERTEXID that defines the ID of the vertex from which each atom comes from.
Definition at line 1681 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.utils.MoleculeUtils.extractIACForSubgraph(), denoptim.graph.DGraph.extractPattern(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.graph.DGraph.getCandidateOwner(), denoptim.graph.DGraph.getGraphId(), denoptim.graph.Template.getInnerGraph(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.Candidate.getName(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedFragments(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedScaffolds(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.fragspace.FragmentSpace.hasIsomorph(), denoptim.fragspace.FragmentSpace.LOCK, denoptim.graph.GraphPattern.RING, denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.scaffoldLib, denoptim.graph.Template.setIAtomContainer(), denoptim.graph.Template.setInnerGraph(), denoptim.fragspace.FragmentSpace.settings, denoptim.io.DenoptimIO.writeGraphsToJSON(), denoptim.io.DenoptimIO.writeGraphToSDF(), and denoptim.io.DenoptimIO.writeSDFFile().
appendVertexToLibrary()
void denoptim.fragspace.FragmentSpace.appendVertexToLibrary (Vertex v, Vertex.BBType bbt, ArrayList< Vertex > library)
Takes a vertex and add it to a given library.
Each vertex is assigned the building block type and ID.
Parameters
v vertex to import.
bbt the type of building block the vertex should be set to.
library where to import the vertex to.
Definition at line 1597 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.setBuildingBlockId(), and denoptim.graph.Vertex.setBuildingBlockType().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.appendVerticesToLibrary(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
appendVerticesToLibrary()
void denoptim.fragspace.FragmentSpace.appendVerticesToLibrary (ArrayList< Vertex > list, Vertex.BBType bbt, ArrayList< Vertex > library)
Takes a list of vertices and add them to a given library.
Each vertex is assigned the building block type and ID.
Parameters
list of vertices to import.
bbt the type of building block the vertices should be set to.
library where to import the vertices to.
Definition at line 1577 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.appendVertexToLibrary().
Referenced by denoptim.fragspace.FragmentSpace.setCappingLibrary(), denoptim.fragspace.FragmentSpace.setFragmentLibrary(), and denoptim.fragspace.FragmentSpace.setScaffoldLibrary().
classifyFragment()
void denoptim.fragspace.FragmentSpace.classifyFragment (Vertex frg, int fragId)
Classify a fragment in terms of the number of APs and possibly their type (AP-Class).
Parameters
frg the building block to classify
id the index of the fragment in the library
Exceptions
DENOPTIMException
Definition at line 1927 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassesPerFrag, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, denoptim.graph.Vertex.getAllAPClasses(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.fragspace.FragmentSpace.getFragsWithNumAps(), denoptim.graph.Vertex.getFreeAPCount(), denoptim.fragspace.FragmentSpace.getMapOfFragsPerNumAps(), denoptim.graph.AttachmentPoint.isAvailable(), denoptim.graph.Vertex.isRCV, denoptim.fragspace.FragmentSpace.LOCK, denoptim.fragspace.FragmentSpace.registerRCV(), and denoptim.fragspace.FragmentSpace.useAPclassBasedApproach().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), and denoptim.fragspace.FragmentSpace.groupAndClassifyFragments().
clearAll()
void denoptim.fragspace.FragmentSpace.clearAll ()
Clears all settings of this fragment space.
All fields changed to null.
Definition at line 1550 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix, denoptim.fragspace.FragmentSpace.apClassesPerFrag, denoptim.fragspace.FragmentSpace.cappingLib, denoptim.fragspace.FragmentSpace.cappingMap, denoptim.fragspace.FragmentSpace.forbiddenEndList, denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.fragspace.FragmentSpace.fragPoolPerNumAP, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, denoptim.fragspace.FragmentSpace.isValid, denoptim.fragspace.FragmentSpace.rcCompatMap, denoptim.fragspace.FragmentSpace.scaffoldLib, and denoptim.fragspace.FragmentSpace.symmConstraints.
define()
void denoptim.fragspace.FragmentSpace.define (FragmentSpaceParameters settings, ArrayList< Vertex > scaffLib, ArrayList< Vertex > fragLib, ArrayList< Vertex > cappLib, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > forbEnds, HashMap< APClass, ArrayList< APClass > > rcCpMap, HashMap< APClass, Double > symCntrMap) throws DENOPTIMException private
Define all components of this fragment space.
Parameters
scaffLib library of fragments used to start the construction of any new graph (i.e., seed or root fragments, a.k.a. scaffolds).
fragLib library of fragments for general purpose.
cappLib library of single-AP fragments used to cap free attachment points (i.e., the capping groups).
cpMap the APClass compatibility map. This data structure is a map of the APClass-on-growing-graph (key) to list of permitted APClasses on incoming fragment (values).
capMap the capping rules. This data structure is a map of APClass-to-cap (keys) to APClass-of-capping-group (values).
forbEnds the list of forbidden ends, i.e., APClasses that cannot be left unused neither capped.
rcCpMap the APClass compatibility matrix for ring closures.
symCntrMap map of symmetry probability constraints.
Exceptions
DENOPTIMException
Definition at line 415 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassBasedApproch, denoptim.fragspace.FragmentSpace.groupAndClassifyFragments(), denoptim.fragspace.FragmentSpace.isValid, denoptim.fragspace.FragmentSpace.setCappingLibrary(), denoptim.fragspace.FragmentSpace.setCappingMap(), denoptim.fragspace.FragmentSpace.setCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.setForbiddenEndList(), denoptim.fragspace.FragmentSpace.setFragmentLibrary(), denoptim.fragspace.FragmentSpaceParameters.setFragmentSpace(), denoptim.fragspace.FragmentSpace.setRCCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.setScaffoldLibrary(), denoptim.fragspace.FragmentSpace.setSymmConstraints(), and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.fragspace.FragmentSpace.FragmentSpace().
getAllAPClassesFromCPMap()
Set< APClass > denoptim.fragspace.FragmentSpace.getAllAPClassesFromCPMap ()
Return the set of APClasses that used in the compatibility matrix for the growing graph APs.
Note these APClasses do include subclasses. For example, for AP with class MyAPClass:0 the 0 is the subclass.
Returns
the lst of APClasses
Definition at line 915 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix.
Referenced by denoptim.gui.FSParametersForm.FSParametersForm().
getAPClassesPerFragment()
ArrayList< APClass > denoptim.fragspace.FragmentSpace.getAPClassesPerFragment (int fragId)
Returns the APclasses associated with a given fragment.
Parameters
fragId the index of the fragment in the library
Returns
the list of APclasses found of the fragment
Definition at line 955 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassesPerFrag, and denoptim.fragspace.FragmentSpace.LOCK.
getAPClassForFragment()
APClass denoptim.fragspace.FragmentSpace.getAPClassForFragment (IdFragmentAndAP apId)
Search for a specific AP on a specific fragment and finds out its class.
Parameters
apId the identified of a specific attachment point.
Returns
the AP class or null
Definition at line 502 of file FragmentSpace.java.
References denoptim.fragspace.IdFragmentAndAP.getApId(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.IdFragmentAndAP.getVertexMolId(), and denoptim.fragspace.IdFragmentAndAP.getVertexMolType().
Referenced by denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithTheseAPs().
getAPClassOfCappingVertex()
APClass denoptim.fragspace.FragmentSpace.getAPClassOfCappingVertex (APClass srcApClass)
Parameters
srcApClass the attachment point class of the attachment point to be capped
Returns
the APClass of the capping group or null
Definition at line 892 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingMap.
Referenced by denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), and denoptim.graph.DGraph.graphNeedsCappingGroups().
getAPsCompatibleWithClass()
ArrayList< AttachmentPoint > denoptim.fragspace.FragmentSpace.getAPsCompatibleWithClass (APClass aPC1)
Returns the list of attachment points found in the fragment space and that are compatible with a given AP class.
Multiple APs can be found for each fragment.
Parameters
aPC1 the AP class for which we want compatible APs.
Definition at line 1351 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getCompatibleAPClasses(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClass(), and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.fragspace.FragmentSpace.getAPsCompatibleWithThese().
getAPsCompatibleWithThese()
ArrayList< AttachmentPoint > denoptim.fragspace.FragmentSpace.getAPsCompatibleWithThese (ArrayList< AttachmentPoint > srcAPs)
Searches for all attachment points that are compatible with the given list of attachment points.
Parameters
srcAPs attachment points meant to results have to be compatible with.
Returns
a list of compatible attachment points found in the library of fragments.
Definition at line 1247 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getAPsCompatibleWithClass().
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs().
getCappingFragment()
int denoptim.fragspace.FragmentSpace.getCappingFragment (APClass rcnCap)
Select a compatible capping group for the given APClass.
Parameters
rcnCap the class of the attachment point to be capped.
Returns
the index of capping group
Definition at line 670 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getCompatibleCappingFragments(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.utils.Randomizer.randomlyChooseOne(), and denoptim.fragspace.FragmentSpace.settings.
getCappingGroupsWithAPClass()
ArrayList< Integer > denoptim.fragspace.FragmentSpace.getCappingGroupsWithAPClass (APClass capApCls)
Parameters
capApCls the APClass of the attachment point on the capping group
Returns
all the capping groups which have the given APClass.
Definition at line 759 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingLib, and denoptim.graph.APClass.equals().
Referenced by denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator().
getCappingLibrary()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getCappingLibrary ()
Definition at line 747 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingLib.
Referenced by denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.fragspace.FragmentSpace.getCompatibleCappingFragments(), and denoptim.graph.DGraphTest.prepare().
getCappingMap()
HashMap< APClass, APClass > denoptim.fragspace.FragmentSpace.getCappingMap ()
Definition at line 879 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingMap.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), and denoptim.ga.EAUtils.buildCandidatesByXOver().
getCappingVertexWithAPClass()
Vertex denoptim.fragspace.FragmentSpace.getCappingVertexWithAPClass (APClass capApCls)
Parameters
capApCls the APClass of the attachment point on the capping group.
Returns
a clone of the first 'capping group' having the given APClass, or null if none was found.
Definition at line 782 of file FragmentSpace.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.fragspace.FragmentSpace.cappingLib, denoptim.graph.APClass.equals(), and denoptim.fragspace.FragmentSpace.getVertexFromLibrary().
getCompatibilityMatrix()
HashMap< APClass, ArrayList< APClass > > denoptim.fragspace.FragmentSpace.getCompatibilityMatrix ()
Definition at line 841 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix.
Referenced by denoptim.fragspace.FragmentSpace.getRCVsForAPClass().
getCompatibleAPClasses()
ArrayList< APClass > denoptim.fragspace.FragmentSpace.getCompatibleAPClasses (APClass apc)
Returns a list of APClasses compatible with the given APClass.
The compatibility among classes is defined by the compatibility matrix
Parameters
apc
Returns
the list of compatible APClasses. Can be empty but not null.
Definition at line 854 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix.
Referenced by denoptim.fragspace.FragmentSpace.getAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithClass(), denoptim.ga.EAUtils.getUsableAliphaticBridges(), and denoptim.graph.APClass.isCPMapCompatibleWith().
getCompatibleCappingFragments()
ArrayList< Integer > denoptim.fragspace.FragmentSpace.getCompatibleCappingFragments (APClass cmpReac)
Retrieve a list of compatible capping groups.
Parameters
cmpReac
Returns
a list of compatible capping groups
Definition at line 694 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingLib, denoptim.graph.Vertex.getAllAPClasses(), and denoptim.fragspace.FragmentSpace.getCappingLibrary().
Referenced by denoptim.fragspace.FragmentSpace.getCappingFragment().
getForbiddenEndList()
Set< APClass > denoptim.fragspace.FragmentSpace.getForbiddenEndList ()
Definition at line 899 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.forbiddenEndList.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.EAUtils.foundForbiddenEnd(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), and denoptim.graph.DGraph.hasForbiddenEnd().
getFragAPsCompatibleWithClass()
ArrayList< IdFragmentAndAP > denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithClass (APClass aPC1)
Returns the list of attachment points found in the fragment space and that are compatible with a given AP class.
Multiple APs can be found for each fragment.
Parameters
aPC1 the AP class for which we want compatible APs.
Definition at line 1398 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getCompatibleAPClasses(), and denoptim.fragspace.FragmentSpace.getFragsWithAPClass().
Referenced by denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithTheseAPs(), and denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass().
getFragAPsCompatibleWithTheseAPs()
ArrayList< IdFragmentAndAP > denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithTheseAPs (ArrayList< IdFragmentAndAP > srcAPs)
Searches for all APs that are compatible with the given list of APs.
Parameters
srcAPs the identifiers of APs meant to hold any of the desired fragments.
Returns
a list of identifiers for APs on fragments in the library.
Definition at line 1298 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getAPClassForFragment(), and denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithClass().
Referenced by denoptim.fragspace.FragmentSpace.getFragmentsCompatibleWithTheseAPs(), and denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs().
getFragmentLibrary()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getFragmentLibrary ()
Definition at line 740 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragmentLib.
Referenced by denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.fragspace.GraphLinkFinder.getCandidateBBs(), denoptim.fragspace.FragmentSpace.groupAndClassifyFragments(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
getFragmentsCompatibleWithTheseAPs()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getFragmentsCompatibleWithTheseAPs (ArrayList< IdFragmentAndAP > srcAPs)
Searches for all building blocks that are compatible with the given list of APs.
Parameters
srcAPs the identifiers of APs meant to hold any of the desired fragments.
Returns
a list of fragments.
Definition at line 1133 of file FragmentSpace.java.
References denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithTheseAPs(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.fragspace.FragmentSpaceTest.testGetFragmentsCompatibleWithTheseAPs().
getFragsWithAPClass()
ArrayList< IdFragmentAndAP > denoptim.fragspace.FragmentSpace.getFragsWithAPClass (APClass apc)
Returns the list of attachment points with the given class.
The returned identifiers have vertex_id=-1 because these APs are only on the individual fragments held in the library and do not belong to any graph.
Parameters
apc
Returns
the list of AP identifiers.
Definition at line 975 of file FragmentSpace.java.
References denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, and denoptim.fragspace.FragmentSpace.LOCK.
Referenced by denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithClass(), and denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass().
getFragsWithNumAps()
ArrayList< Integer > denoptim.fragspace.FragmentSpace.getFragsWithNumAps (int nAps)
Returns the list of fragments with given number of APs.
Parameters
nAps the number of attachment points
Returns
the list of fragments as indexes in the library of fragments.
Definition at line 936 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragPoolPerNumAP.
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment().
getMapOfFragsPerNumAps()
HashMap< Integer, ArrayList< Integer > > denoptim.fragspace.FragmentSpace.getMapOfFragsPerNumAps ()
Definition at line 922 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragPoolPerNumAP.
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment().
getPolarizedRCV()
static Vertex denoptim.fragspace.FragmentSpace.getPolarizedRCV (boolean polarity) static
Returns a newly-built vertex that can play the role of a ring-closing vertex even when working with 3D building blocks.
Parameters
polarity use true to get an RCV with attachment point class APClass#ATPLUSS and false to get APClass#ATMINUS.
Returns
the ring-closing vertex.
Definition at line 2017 of file FragmentSpace.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.APClass.RCACLASSMINUS, denoptim.graph.APClass.RCACLASSPLUS, denoptim.graph.rings.RingClosingAttractor.RCALABELPERAPCLASS, and denoptim.graph.Vertex.setAsRCV().
Referenced by denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
getRandomizer()
Randomizer denoptim.fragspace.FragmentSpace.getRandomizer ()
Returns the program-specific randomizer that is associated with this program-specific fragment space.
Returns
the program-specific randomizer.
Definition at line 463 of file FragmentSpace.java.
References denoptim.programs.RunTimeParameters.getRandomizer(), and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.fragspace.APMapFinder.findAllMappings().
getRCCompatibilityMatrix()
HashMap< APClass, ArrayList< APClass > > denoptim.fragspace.FragmentSpace.getRCCompatibilityMatrix ()
Returns the compatibility matrix for ring closing fragment-fragment connections or null if not provided in the parameters file.
Returns
Definition at line 872 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.rcCompatMap.
Referenced by denoptim.ga.EAUtils.canBeUsedForRingFusion(), and denoptim.graph.rings.RingSizeManager.evaluateRCVPair().
getRCVs()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getRCVs ()
Returns the list of registered ring-closing vertexes (RCVs).
Returns
the list of registered ring-closing vertexes (RCVs).
Definition at line 1844 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.rcvs.
Referenced by denoptim.fragspace.FragmentSpace.getRCVsForAPClass(), and denoptim.fragspace.FragmentSpace.getRCVsWithAPClass().
getRCVsForAPClass()
List< Vertex > denoptim.fragspace.FragmentSpace.getRCVsForAPClass (APClass apc)
Searches for all building blocks that are ring-closing vertexes and are compatible with the given AP.
Parameters
apc the class of the attachment point meant to hold the RCV.
Returns
a list of vertexes ready to be used (i.e., clones of the vertexes stored in the library). The list can be empty.
Definition at line 1207 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.getRCVs(), and denoptim.fragspace.FragmentSpace.getVertexFromLibrary().
Referenced by denoptim.fragspace.FragmentSpaceTest.testGetRCVsForAPClass().
getRCVsWithAPClass()
List< Vertex > denoptim.fragspace.FragmentSpace.getRCVsWithAPClass (APClass apc)
Searches for all building blocks that are ring-closing vertexes and hold an AP with the given class.
Parameters
apc the desired class of the attachment point.
Returns
a list of vertexes ready to be used (i.e., clones of the vertexes stored in the library). The list can be empty.
Definition at line 1172 of file FragmentSpace.java.
References denoptim.graph.APClass.equals(), denoptim.fragspace.FragmentSpace.getRCVs(), and denoptim.fragspace.FragmentSpace.getVertexFromLibrary().
Referenced by denoptim.fragspace.FragmentSpaceTest.testGetRCVsWithAPClass().
getScaffoldLibrary()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getScaffoldLibrary ()
Definition at line 733 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.scaffoldLib.
Referenced by denoptim.fragspace.GraphLinkFinder.getCandidateBBs(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
getSymmetryConstrain()
double denoptim.fragspace.FragmentSpace.getSymmetryConstrain (APClass apClass)
Return the constitutional symmetry constrain for the given APclass, or null.
The constrain is a fixed probability that is not dependent on the distance from the root of the DENOPTIMGraph (i.e. the level).
Parameters
apClass the attachment point class
Returns
the constrained value of the symmetric substitution probability (0.0 - 1.0).
Definition at line 1481 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.symmConstraints.
Referenced by denoptim.fragspace.FragmentSpace.imposeSymmetryOnAPsOfClass().
getVertexFromLibrary()
Vertex denoptim.fragspace.FragmentSpace.getVertexFromLibrary (Vertex.BBType bbType, int bbIdx) throws DENOPTIMException
Returns a clone of the requested building block.
The type of vertex returned depends on the type stored in the library.
Parameters
bbType the type of building block. This basically selects the sub library from which the building block is taken: 0 for scaffold (i.e., building blocks that can be used to start a new graph), 1 for standard building blocks (i.e., can be used freely to grow or modify an existing graph), or 2 for capping group (i.e., can be used only to saturate attachment points that cannot remain unused in a finished graph).
bbIdx the index (0-based) of the building block in the corresponding library defied by the type of building block 'bbType'
Returns
a clone of the chosen building block.
Exceptions
DENOPTIMException when the given indexes cannot be used, for example, any of the indexes is out of range.
Definition at line 539 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingLib, denoptim.graph.Vertex.clone(), denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.graph.Vertex.getBuildingBlockId(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.fragspace.FragmentSpace.scaffoldLib, denoptim.graph.Vertex.setBuildingBlockId(), denoptim.fragspace.FragmentSpace.settings, and denoptim.graph.Vertex.setVertexId().
Referenced by denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.fragspace.FragmentSpace.getAPClassForFragment(), denoptim.fragspace.GraphLinkFinder.getCandidateBBs(), denoptim.fragspace.FragmentSpace.getCappingVertexWithAPClass(), denoptim.fragspace.FragmentSpace.getFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpace.getRCVsForAPClass(), denoptim.fragspace.FragmentSpace.getRCVsWithAPClass(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
getVerticesWithAPClass()
ArrayList< Vertex > denoptim.fragspace.FragmentSpace.getVerticesWithAPClass (APClass apc)
Returns the list of vertexes with attachment points of the given class.
Parameters
apc the attachment point class to search.
Returns
the list of matching vertexes from the library.
Definition at line 1005 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, and denoptim.fragspace.FragmentSpace.LOCK.
Referenced by denoptim.fragspace.FragmentSpace.getAPsCompatibleWithClass(), and denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClass().
getVerticesWithAPClasses()
List< Vertex > denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses (Set< APClass > apcs)
Returns the list of vertexes with at least one attachment point of each of the given classes.
Parameters
apcs the wanted attachment point classes.
Returns
the list of matching vertexes from the library.
Definition at line 1032 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, denoptim.graph.Vertex.getAllAPClasses(), and denoptim.fragspace.FragmentSpace.LOCK.
Referenced by denoptim.fragspace.FragmentSpace.getVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses().
getVerticesWithAPClassStartingWith()
List< Vertex > denoptim.fragspace.FragmentSpace.getVerticesWithAPClassStartingWith (String root)
Extracts vertexes from the collection of vertexes defined by this FragmentSpace.
Parameters
root the initial part of the APClass full name.
Returns
the available vertexes that have AttachmentPoints that start with the given string. The returned vertexes are the original ones, not clones!
Definition at line 1103 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.fragspace.FragmentSpace.fragsApsPerApClass, and denoptim.fragspace.FragmentSpace.LOCK.
Referenced by denoptim.ga.EAUtils.getUsableAromaticBridges(), and denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClassStartingWith().
getVerticesWithAPFingerprint()
List< Vertex > denoptim.fragspace.FragmentSpace.getVerticesWithAPFingerprint (Map< APClass, Integer > apcCounts)
Returns the list of vertexes that have the specified number of AttachmentPoints with the given APClasses.
Parameters
apcCounts specifies for each APClass the desired minimum number of AttachmentPoints.
Returns
the list of matching vertexes from the library.
Definition at line 1070 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses().
Referenced by denoptim.ga.EAUtils.getUsableAliphaticBridges(), and denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint().
groupAndClassifyFragments()
void denoptim.fragspace.FragmentSpace.groupAndClassifyFragments (boolean apClassBasedApproch) throws DENOPTIMException
Performs grouping and classification operations on the library of building blocks of BBType#FRAGMENT.
Parameters
apClassBasedApproch true if you are using class based approach
Definition at line 1997 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.classifyFragment(), and denoptim.fragspace.FragmentSpace.getFragmentLibrary().
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.GraphLinkFinderTest.prepare().
hasIsomorph()
boolean denoptim.fragspace.FragmentSpace.hasIsomorph (DGraph graph, BBType type)
Checks if a graph is isomorphic to another template's inner graph in its appropriate fragment space library (inferred from BBType).
Parameters
graph to check if has an isomorph in the fragment space.
type specifying which fragment library to check for isomorphs in.
Returns
true if there is an isomorph template in the library of the specified type.
Definition at line 1817 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.fragmentLib, denoptim.graph.Template.getInnerGraph(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.fragspace.FragmentSpace.scaffoldLib.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary().
hasSymmetryConstrain()
boolean denoptim.fragspace.FragmentSpace.hasSymmetryConstrain (APClass apClass)
Checks if there is a constraint on the constitutional symmetry probability for the given AP class.
Parameters
apClass the attachment point class
Returns
true if there is a constraint on the constitutional symmetry probability for the given AP class.
Definition at line 1462 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.symmConstraints.
Referenced by denoptim.fragspace.FragmentSpace.imposeSymmetryOnAPsOfClass().
importCompatibilityMatrixFromFile()
void denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile (String inFile) throws DENOPTIMException
Load info from a compatibility matrix file.
This method imports information such as the compatibility matrix, bond order map, and forbidden ends from a compatibility matrix file (i.e., a formatted text file using DENOPTIM keyword. This overrides any previous setting of such information in this FragmentSpace.
Parameters
inFile the pathname of the compatibility matrix file
Definition at line 813 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix, denoptim.fragspace.FragmentSpace.cappingMap, denoptim.fragspace.FragmentSpace.forbiddenEndList, denoptim.io.DenoptimIO.readCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.setCappingMap(), denoptim.fragspace.FragmentSpace.setCompatibilityMatrix(), and denoptim.fragspace.FragmentSpace.setForbiddenEndList().
Referenced by denoptim.gui.FSParametersForm.FSParametersForm().
importRCCompatibilityMatrixFromFile()
void denoptim.fragspace.FragmentSpace.importRCCompatibilityMatrixFromFile (String inFile) throws DENOPTIMException
Load info for ring closures compatibilities from a compatibility matrix file.
Parameters
inFile the pathname of the RC-compatibility matrix file
Definition at line 832 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.rcCompatMap, denoptim.io.DenoptimIO.readRCCompatibilityMatrix(), and denoptim.fragspace.FragmentSpace.setRCCompatibilityMatrix().
imposeSymmetryOnAPsOfClass()
boolean denoptim.fragspace.FragmentSpace.imposeSymmetryOnAPsOfClass (APClass apClass)
Checks if the symmetry settings impose use of symmetry on attachment points of the given AP class.
The value returned is the result of the action of symmetry-related keyword affecting the definition of this FragmentSpace.
Parameters
apClass the attachment point class
Returns
true if symmetry has the applied on APs of the given class
Definition at line 1431 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpaceParameters.enforceSymmetry, denoptim.constants.DENOPTIMConstants.FLOATCOMPARISONTOLERANCE, denoptim.fragspace.FragmentSpace.getSymmetryConstrain(), denoptim.fragspace.FragmentSpace.hasSymmetryConstrain(), and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.ga.GraphOperations.attachFragmentInClosableChain(), denoptim.ga.GraphOperations.extendGraph(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), and denoptim.fragspace.FragsCombinationIterator.next().
isDefined()
boolean denoptim.fragspace.FragmentSpace.isDefined ()
Checks for valid definition of this fragment space.
Returns
true if this fragment space has been defined
Definition at line 451 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.isValid.
Referenced by denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClassStartingWith(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testSymmetry().
makeRandomScaffold()
Vertex denoptim.fragspace.FragmentSpace.makeRandomScaffold ()
Randomly select a scaffold and return a fully configured clone of it.
Returns
a scaffold-type building block ready to be used in a new graph.
Exceptions
DENOPTIMException
Definition at line 715 of file FragmentSpace.java.
References denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.utils.Randomizer.nextInt(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.scaffoldLib, and denoptim.fragspace.FragmentSpace.settings.
Referenced by denoptim.ga.EAUtils.buildGraph().
mapAPClassCompatibilities()
List< APMapping > denoptim.fragspace.FragmentSpace.mapAPClassCompatibilities (List< AttachmentPoint > listA, List< AttachmentPoint > listB, int maxCombinations)
Given two lists of APs this method maps the APClass-compatibilities from between the two lists considering the APs in the first list the for the role of source AP in the hypothetical edge.
Parameters
listA list of candidate source APs
listB list of candidate target APs
maxCombinations a maximum limit; if reached we are happy we give up finding more combination.
Returns
Definition at line 1861 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpaceUtils.recursiveCombiner(), and denoptim.fragspace.FragmentSpace.useAPclassBasedApproach().
registerRCV()
void denoptim.fragspace.FragmentSpace.registerRCV (Vertex v)
Adds the reference to a ring-closing vertex (RCV) to the quick-access list of RCVs known in this building block space.
Parameters
v the RCV to add to the list.
Definition at line 1833 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.rcvs.
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment().
setAPclassBasedApproach()
void denoptim.fragspace.FragmentSpace.setAPclassBasedApproach (boolean useAPC)
Set the fragment space to behave according to APClass-based approach.
Definition at line 473 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassBasedApproch.
Referenced by denoptim.fragspace.APMapFinderTest.prepare(), denoptim.fragspace.GraphLinkFinderTest.prepare(), denoptim.ga.EAUtilsTest.prepare(), denoptim.ga.GraphOperationsTest.prepare(), denoptim.ga.PopulationTest.prepare(), denoptim.graph.DGraphTest.prepare(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry(), denoptim.fragspace.FragmentSpaceTest.testGetRCVsForAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetRCVsWithAPClass(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_cappingGroups(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
setCappingLibrary()
void denoptim.fragspace.FragmentSpace.setCappingLibrary (ArrayList< Vertex > lib)
Definition at line 1502 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.appendVerticesToLibrary(), denoptim.graph.Vertex.BBType.CAP, and denoptim.fragspace.FragmentSpace.cappingLib.
Referenced by denoptim.fragspace.FragmentSpace.define().
setCappingMap()
void denoptim.fragspace.FragmentSpace.setCappingMap (HashMap< APClass, APClass > map)
Definition at line 1525 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.cappingMap.
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile().
setCompatibilityMatrix()
void denoptim.fragspace.FragmentSpace.setCompatibilityMatrix (HashMap< APClass, ArrayList< APClass > > map)
Definition at line 1510 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix.
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile().
setForbiddenEndList()
void denoptim.fragspace.FragmentSpace.setForbiddenEndList (Set< APClass > lst)
Definition at line 1532 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.forbiddenEndList.
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile().
setFragmentLibrary()
void denoptim.fragspace.FragmentSpace.setFragmentLibrary (ArrayList< Vertex > lib)
Definition at line 1494 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.appendVerticesToLibrary(), denoptim.graph.Vertex.BBType.FRAGMENT, and denoptim.fragspace.FragmentSpace.fragmentLib.
Referenced by denoptim.fragspace.FragmentSpace.define().
setRCCompatibilityMatrix()
void denoptim.fragspace.FragmentSpace.setRCCompatibilityMatrix (HashMap< APClass, ArrayList< APClass > > map)
Definition at line 1517 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.rcCompatMap.
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.importRCCompatibilityMatrixFromFile().
setScaffoldLibrary()
void denoptim.fragspace.FragmentSpace.setScaffoldLibrary (ArrayList< Vertex > lib)
Definition at line 1488 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.appendVerticesToLibrary(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.fragspace.FragmentSpace.scaffoldLib.
Referenced by denoptim.fragspace.FragmentSpace.define().
setSymmConstraints()
void denoptim.fragspace.FragmentSpace.setSymmConstraints (HashMap< APClass, Double > map)
Definition at line 1539 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.symmConstraints.
Referenced by denoptim.fragspace.FragmentSpace.define(), and denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry().
useAPclassBasedApproach()
boolean denoptim.fragspace.FragmentSpace.useAPclassBasedApproach ()
Check usage of APClass-based approach, i.e., uses attachment points with annotated data (i.e., the APClass) to evaluate compatibilities between attachment points.
Returns
true if this fragment space makes use of APClass-based approach
Definition at line 488 of file FragmentSpace.java.
References denoptim.fragspace.FragmentSpace.apClassBasedApproch.
Referenced by denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.DGraph.checkConsistency(), denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.fragspace.APMapFinder.findMappingCompatibileAPs(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.fragspace.FragmentSpace.mapAPClassCompatibilities(), denoptim.ga.Population.Population(), and denoptim.ga.EAUtils.setupRings().
Member Data Documentation
apClassBasedApproch
boolean denoptim.fragspace.FragmentSpace.apClassBasedApproch = false private
Flag defining use of AP class-based approach.
Definition at line 159 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.define(), denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.fragspace.FragmentSpace.useAPclassBasedApproach().
apClassCompatibilityMatrix
HashMap<APClass, ArrayList<APClass> > denoptim.fragspace.FragmentSpace.apClassCompatibilityMatrix private
Data structure that stored the true entries of the attachment point classes compatibility matrix.
Definition at line 101 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getAllAPClassesFromCPMap(), denoptim.fragspace.FragmentSpace.getCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.getCompatibleAPClasses(), denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile(), and denoptim.fragspace.FragmentSpace.setCompatibilityMatrix().
apClassesPerFrag
HashMap<Integer, ArrayList<APClass> > denoptim.fragspace.FragmentSpace.apClassesPerFrag private
Initial value:
=
            new HashMap<Integer,ArrayList<APClass>>()
List of APClasses per each fragment.
Definition at line 135 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.fragspace.FragmentSpace.clearAll(), and denoptim.fragspace.FragmentSpace.getAPClassesPerFragment().
cappingLib
ArrayList<Vertex> denoptim.fragspace.FragmentSpace.cappingLib = null private
Data structure containing the molecular representation of building blocks: capping group section - fragments with only one attachment point used to saturate unused attachment points on a graph.
WARNING! The objects stores in the library do not have a meaningful value for the two indexes representing the type of building block and the position of the list of all building blocks of that type.
Definition at line 95 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.fragspace.FragmentSpace.getCappingGroupsWithAPClass(), denoptim.fragspace.FragmentSpace.getCappingLibrary(), denoptim.fragspace.FragmentSpace.getCappingVertexWithAPClass(), denoptim.fragspace.FragmentSpace.getCompatibleCappingFragments(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), and denoptim.fragspace.FragmentSpace.setCappingLibrary().
cappingMap
HashMap<APClass, APClass> denoptim.fragspace.FragmentSpace.cappingMap private
Data structure that stores the AP-classes to be used to cap unused APS on the growing molecule.
Definition at line 119 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getAPClassOfCappingVertex(), denoptim.fragspace.FragmentSpace.getCappingMap(), denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile(), and denoptim.fragspace.FragmentSpace.setCappingMap().
forbiddenEndList
Set<APClass> denoptim.fragspace.FragmentSpace.forbiddenEndList private
Data structure that stores AP classes that cannot be held unused.
Definition at line 124 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getForbiddenEndList(), denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile(), and denoptim.fragspace.FragmentSpace.setForbiddenEndList().
fragmentLib
ArrayList<Vertex> denoptim.fragspace.FragmentSpace.fragmentLib = null private
Data structure containing the molecular representation of building blocks: fragment section - fragments for general use.
WARNING! The objects stores in the library do not have a meaningful value for the two indexes representing the type of building block and the position of the list of all building blocks of that type.
Definition at line 85 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClass(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClassStartingWith(), denoptim.fragspace.FragmentSpace.hasIsomorph(), and denoptim.fragspace.FragmentSpace.setFragmentLibrary().
fragPoolPerNumAP
HashMap<Integer, ArrayList<Integer> > denoptim.fragspace.FragmentSpace.fragPoolPerNumAP private
Initial value:
=
            new HashMap<Integer,ArrayList<Integer>>()
Clusters of fragments based on the number of APs.
Definition at line 129 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getFragsWithNumAps(), and denoptim.fragspace.FragmentSpace.getMapOfFragsPerNumAps().
fragsApsPerApClass
HashMap<APClass, ArrayList<ArrayList<Integer> > > denoptim.fragspace.FragmentSpace.fragsApsPerApClass private
Initial value:
=
            new HashMap<APClass,ArrayList<ArrayList<Integer>>>()
Clusters of fragments'AP based on AP classes.
The inner list of indexes is a ordered pair defining at position 0 the index of the vertex, and
the index of the AP at position 1.
Definition at line 143 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getFragsWithAPClass(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClass(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses(), and denoptim.fragspace.FragmentSpace.getVerticesWithAPClassStartingWith().
isValid
boolean denoptim.fragspace.FragmentSpace.isValid = false private
Flag signaling that this fragment space was built and validated.
Definition at line 164 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.define(), and denoptim.fragspace.FragmentSpace.isDefined().
LOCK
final Object denoptim.fragspace.FragmentSpace.LOCK = new Object() private
Lock for synchronizing tasks.
Definition at line 149 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.classifyFragment(), denoptim.fragspace.FragmentSpace.getAPClassesPerFragment(), denoptim.fragspace.FragmentSpace.getFragsWithAPClass(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClass(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses(), and denoptim.fragspace.FragmentSpace.getVerticesWithAPClassStartingWith().
rcCompatMap
HashMap<APClass, ArrayList<APClass> > denoptim.fragspace.FragmentSpace.rcCompatMap private
Data structure that stores compatible APclasses for joining APs in ring-closing bonds.
Symmetric, purpose specific compatibility matrix.
Definition at line 113 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getRCCompatibilityMatrix(), denoptim.fragspace.FragmentSpace.importRCCompatibilityMatrixFromFile(), and denoptim.fragspace.FragmentSpace.setRCCompatibilityMatrix().
rcvs
ArrayList<Vertex> denoptim.fragspace.FragmentSpace.rcvs = new ArrayList<Vertex>() private
Store references to the Ring-Closing Vertexes found in the library of fragments.
Definition at line 107 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.getRCVs(), and denoptim.fragspace.FragmentSpace.registerRCV().
scaffoldLib
ArrayList<Vertex> denoptim.fragspace.FragmentSpace.scaffoldLib = null private
Data structure containing the molecular representation of building blocks: scaffolds section - fragments that can be used as seeds to grow a new molecule.
WARNING! The objects stores in the library do not have a meaningful value for the two indexes representing the type of building block and the position of the list of all building blocks of that type.
Definition at line 76 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.FragmentSpace.hasIsomorph(), denoptim.fragspace.FragmentSpace.makeRandomScaffold(), and denoptim.fragspace.FragmentSpace.setScaffoldLibrary().
settings
FragmentSpaceParameters denoptim.fragspace.FragmentSpace.settings = null private
Settings used to configure this fragment space.
Contains the default values unless its value is reassigned.
Definition at line 170 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpace.define(), denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.fragspace.FragmentSpace.getAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpace.getCappingFragment(), denoptim.fragspace.FragmentSpace.getFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpace.getRandomizer(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.fragspace.FragmentSpace.imposeSymmetryOnAPsOfClass(), and denoptim.fragspace.FragmentSpace.makeRandomScaffold().
symmConstraints
HashMap<APClass, Double> denoptim.fragspace.FragmentSpace.symmConstraints private
APclass-specific constraints to constitutional symmetry.
Definition at line 154 of file FragmentSpace.java.
Referenced by denoptim.fragspace.FragmentSpace.clearAll(), denoptim.fragspace.FragmentSpace.getSymmetryConstrain(), denoptim.fragspace.FragmentSpace.hasSymmetryConstrain(), and denoptim.fragspace.FragmentSpace.setSymmConstraints().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragspace/FragmentSpace.java