DENOPTIM: denoptim.gui.GUIPrepareFitnessRunner Class Reference
denoptim.gui.GUIPrepareFitnessRunner Class Reference
Form that allows to test the configuration of a fitness provider.
Classes
class InputForm
Public Member Functions
GUIPrepareFitnessRunner (GUIMainPanel mainPanel)
Constructor.
Public Member Functions inherited from denoptim.gui.GUIPrepare
GUIPrepare (GUIMainPanel mainPanel, String newPanelName)
Constructor.
File prepareWorkSpace () throws DENOPTIMException
void importParametersFromDenoptimParamsFile (File file)
boolean hasUnsavedChanges ()
Check whether any of the parameter forms (i.e., a tab) in this list of tabs has unsaved changes.
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Static Public Attributes
static AtomicInteger testFitnessTabUID = new AtomicInteger(1)
Unique identified for instances of this form.
Private Member Functions
void initialize ()
Initialize the contents of the frame.
Static Private Attributes
static final long serialVersionUID = 2579606720045728971L
Version UID.
Additional Inherited Members
Public Attributes inherited from denoptim.gui.GUIPrepare
ArrayList< IParametersForm > allParams
Storage of parameters.
Protected Attributes inherited from denoptim.gui.GUIPrepare
JTabbedPane tabbedPane
Parameters for the various components are divided in TABs.
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Detailed Description
Form that allows to test the configuration of a fitness provider.
Author
Marco Foscato
Definition at line 48 of file GUIPrepareFitnessRunner.java.
Constructor & Destructor Documentation
GUIPrepareFitnessRunner()
denoptim.gui.GUIPrepareFitnessRunner.GUIPrepareFitnessRunner (GUIMainPanel mainPanel)
Constructor.
Definition at line 66 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.GUIPrepareFitnessRunner.initialize(), denoptim.gui.GUICardPanel.mainPanel, and denoptim.gui.GUIPrepareFitnessRunner.testFitnessTabUID.
Member Function Documentation
initialize()
void denoptim.gui.GUIPrepareFitnessRunner.initialize () private
Initialize the contents of the frame.
Reimplemented from denoptim.gui.GUIPrepare.
Definition at line 76 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.GUICardPanel.mainPanel.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.GUIPrepareFitnessRunner().
Member Data Documentation
serialVersionUID
final long denoptim.gui.GUIPrepareFitnessRunner.serialVersionUID = 2579606720045728971L static private
Version UID.
Definition at line 54 of file GUIPrepareFitnessRunner.java.
testFitnessTabUID
AtomicInteger denoptim.gui.GUIPrepareFitnessRunner.testFitnessTabUID = new AtomicInteger(1) static
Unique identified for instances of this form.
Definition at line 59 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.GUIPrepareFitnessRunner().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIPrepareFitnessRunner.java