DENOPTIM: denoptim.graph.DGraph Class Reference
denoptim.graph.DGraph Class Reference
Container for the list of vertices and the edges that connect them.
Classes
class DENOPTIMGraphDeserializer
class DENOPTIMGraphSerializer
We expect unique IDs for vertices.
class EdgeFinder
Utility to make selection of edges to a vertex tunable by a parameter.
enum StringFormat
Identifier for the format of string representations of a graph.
Public Member Functions
DGraph (List< Vertex > gVertices, List< Edge > gEdges)
DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings)
DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings, List< SymmetricVertexes > symSets)
DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings, List< ClosableChain > closableChains, List< SymmetricVertexes > symVertices)
DGraph ()
void setCandidateOwner (Candidate candidate)
Sets the reference to the candidate item that is defined by this graph.
Candidate getCandidateOwner ()
Returns the reference of the candidate item that is defined by this graph.
void setGraphId (int id)
int getGraphId ()
void setLocalMsg (String msg)
String getLocalMsg ()
boolean hasSymmetricAP ()
boolean hasSymmetryInvolvingVertex (Vertex v)
int getSymmetricSetCount ()
Returns the number of symmetric sets of vertices.
Iterator< SymmetricVertexes > getSymSetsIterator ()
Get an iterator for the sets of symmetrically related vertices.
List< Vertex > getSymVerticesForVertex (Vertex v)
boolean detectSymVertexSets () throws DENOPTIMException
Detects and groups symmetric sets of Vertexes in the graph based on unique identification and path encoding.
void removeSymmetrySet (SymmetricVertexes ss)
Tries to determine the set of symmetric vertices in this graph based on finding compatible Vertexes that are either using symmetric AttachmentPoints (NB: all symmetric APs must be in use by vertexes that are compatible with each other) or that are downstream (i.e., according to edge direction) w.r.t Vertexes that are using symmetric AttachmentPoints.The compatibility of the vertexes is determined by these criteria:
SymmetricVertexes getSymSetForVertex (Vertex v)
Returns the set of vertexes symmetric to the given one.
void setSymmetricVertexSets (List< SymmetricVertexes > symVertices)
void addSymmetricSetOfVertices (SymmetricVertexes symSet) throws DENOPTIMException
Adds a symmetric set of vertices to this graph.
void setVertexList (ArrayList< Vertex > vertices)
void setEdgeList (ArrayList< Edge > edges)
void setRings (ArrayList< Ring > rings)
void setCandidateClosableChains (ArrayList< ClosableChain > closableChains)
List< ClosableChain > getClosableChains ()
List< Vertex > getVertexList ()
Vertex getSourceVertex ()
Identifies and return the vertex from which the spanning tree originates.
List< Edge > getEdgeList ()
List< Ring > getRings ()
List< Edge > getEdgesWithSrc (Vertex v)
Returns the list of edges that depart from the given vertex, i.e., edges where the srcAP is owned by the given vertex.
List< Edge > getEdgesWithTrg (Vertex v)
Returns the list of edges that arrive from the given vertex, i.e., edges where the trgAP is owned by the given vertex.
ArrayList< Ring > getRingsInvolvingVertex (Vertex v)
Returns the list of rings that include the given vertex in their fundamental cycle.
ArrayList< Ring > getRingsInvolvingVertex (Vertex[] vs)
Returns the list of rings that include the given list of vertices in their fundamental cycle.
ArrayList< Ring > getRingsInvolvingVertexID (int vid)
boolean hasRings ()
Check for rings in this graph.
boolean hasOrEmbedsRings ()
Check for rings in this graph and in any graph that is embedded at any level in any vertex of this graph.
boolean isVertexIDInRing (int vid)
boolean isVertexInRing (Vertex v)
ArrayList< Vertex > getRCVertices ()
Search for ring closing vertices: vertices that contain only a RingClosingAttractor
ArrayList< Vertex > getFreeRCVertices ()
Search for unused ring closing vertices: vertices that contain only a RingClosingAttractor and are not part of any DENOPTIMRing
ArrayList< Vertex > getUsedRCVertices ()
Search for used ring closing vertices: vertices that contain only a RingClosingAttractor and are part of a DENOPTIMRing.
void addEdge (Edge edge)
Adds the edge to the list of edges belonging to this graph.
void addRing (Ring ring)
void addRing (Vertex vI, Vertex vJ) throws DENOPTIMException
Adds a chord between the given vertices, thus adding a ring in this graph.
void addRing (Vertex vI, Vertex vJ, BondType bndTyp)
Adds a chord between the given vertices, thus adding a ring in this graph.
void addVertex (Vertex vertex) throws DENOPTIMException
Appends a vertex to this graph without creating any edge.
void removeVertex (Vertex vertex)
Remove a vertex from this graph.
boolean removeVertexAndWeld (Vertex vertex, FragmentSpace fragSpace) throws DENOPTIMException
Remove a given vertex belonging to this graph and re-connects the resulting graph branches as much as possible.
boolean removeSingleVertexAndWeld (Vertex vertex, FragmentSpace fragSpace) throws DENOPTIMException
Remove a given vertex belonging to this graph and re-connects the resulting graph branches as much as possible.
void replaceUnusedRCVsWithCapps (FragmentSpace fragSpace) throws DENOPTIMException
Removes unused ring-closing vertices.
boolean replaceSubGraph (List< Vertex > subGrpVrtxs, DGraph incomingGraph, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap, FragmentSpace fragSpace) throws DENOPTIMException
Replaced the subgraph represented by a given collection of vertices that belong to this graph.
List< List< Vertex > > getSymmetricSubGraphs (List< Vertex > subGrpVrtxs) throws DENOPTIMException
We assume that the subgraph is a continuously connected, directed graph.
boolean replaceSingleSubGraph (List< Vertex > subGrpVrtxs, DGraph newSubGraph, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap) throws DENOPTIMException
Replaced the subgraph represented by a given collection of vertices that belong to this graph.
boolean replaceVertex (Vertex vertex, int bbId, BBType bbt, LinkedHashMap< Integer, Integer > apIdMap, FragmentSpace fragSpace) throws DENOPTIMException
Replaced a given vertex belonging to this graph with a new vertex generated specifically for this purpose.
boolean replaceVertex (Vertex vertex, int bbId, BBType bbt, LinkedHashMap< Integer, Integer > apIdMap, boolean symmetry, FragmentSpace fragSpace) throws DENOPTIMException
Replaced a given vertex belonging to this graph with a new vertex generated specifically for this purpose.
boolean insertVertex (Edge edge, int bbId, BBType bbt, LinkedHashMap< AttachmentPoint, Integer > apMap, FragmentSpace fragSpace) throws DENOPTIMException
Inserts a given vertex in between two vertices connected by the given edge.
boolean insertSingleVertex (Edge edge, Vertex newLink, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap) throws DENOPTIMException
Inserts a given vertex in between two vertices connected by the given edge.
Vertex getVertexAtPosition (int pos)
Returns the vertex that is in the given position of the list of vertices belonging to this graph.
boolean containsOrEmbedsVertex (Vertex v)
Check if the specified vertex is contained in this graph as a node or in any inner graphs that may be embedded in Template-kind vertex belonging to this graph.
boolean containsVertex (Vertex v)
Check if this graph contains the specified vertex.
int indexOf (Vertex v)
Returns the index of a vertex in the list of vertices of this graph.
Vertex getVertexWithId (long vid)
Searches for a vertex with the given identifier.
int indexOfVertexWithID (long vid)
Returns the position of the first vertex that has the given ID.
void removeEdge (Edge edge)
Removes an edge and update the free valences of the attachment points that were originally involved in this edge.
void removeRing (Ring ring)
Edge getEdgeAtPosition (int pos)
int getEdgeCount ()
int getRingCount ()
int getVertexCount ()
String toString ()
int getBondingAPIndex (Vertex srcVert, int dapidx, Vertex dstVert)
ArrayList< Vertex > getChildVertices (Vertex vertex)
void getChildrenTree (Vertex vertex, List< Vertex > children)
Gets all the children of the current vertex recursively.
void getChildrenTree (Vertex vertex, List< Vertex > children, boolean markBranches)
Gets all the children of the current vertex recursively.
void getChildrenTree (Vertex vertex, List< Vertex > children, AtomicInteger branchIdGenerator, List< Integer > prevBranchId)
Gets all the children of the current vertex recursively.
void getChildrenTree (Vertex vertex, List< Vertex > children, int numLayers, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively.
List< Integer > getBranchIdOfVertexAtPosition (int i)
Returns the branch identifier.
List< Integer > getBranchIdOfVertex (Vertex v)
Returns the branch identifier.
String getBranchIdOfVertexAsStr (Vertex v)
Returns the branch identifier as a literal string.
boolean directedPathExists (Vertex src, Vertex trg)
Uses branch identifiers to define is two vertices are in such a relation that allows the drawing of a directed path from one to the other.
void getChildTreeLimited (Vertex vertex, List< Vertex > children, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively.
void getChildTreeLimited (Vertex vertex, List< Vertex > children, Set< Vertex > limits)
Gets all the children of the current vertex recursively until it finds one of the vertices listed as limit.
void getChildTreeLimited (Vertex vertex, List< Vertex > children, List< Vertex > limitsInClone, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively until it finds one of the vertices listed as limit.
Vertex getDeepestAmongThese (List< Vertex > list)
Identify the oldest ancestor (i.e., most great grandparent) in the given collection.
void getParentTree (Vertex vertex, List< Vertex > parentTree)
Traverse the graph until it identifies the source of the directed path reachable from the given vertex recursively.
Vertex getParent (Vertex v)
DGraph clone ()
Returns almost "deep-copy" of this graph.
Edge getEdgeWithParent (long l)
Looks for an edge that points to a vertex with the given vertex id.
ArrayList< Integer > getIndexOfEdgesWithChild (int vid)
ArrayList< Edge > getEdgesWithChild (int vid)
long getMaxVertexId ()
boolean containsVertexID (long l)
Checks if a number is already used as VertexIDs within the graph.
void cleanup ()
Wipes the data in this graph.
boolean isIsomorphicTo (DGraph other)
Checks if this graph is "DENOPTIM-isomorphic" to the other one given.
boolean isIsostructuralTo (DGraph other)
Checks if this graph is "DENOPTIM-isostructural" to the other one given.
boolean sameAs (DGraph other, StringBuilder reason)
Compare this and another graph ignoring the vertex IDs.
boolean containsAtoms ()
Returns true if this graph has any vertex that contains atoms.
int getHeavyAtomsCount ()
Calculate the number of atoms from the graph representation.
ArrayList< AttachmentPoint > getAttachmentPoints ()
Returns the list of all attachment points contained in this graph.
ArrayList< AttachmentPoint > getAvailableAPs ()
Returns the list of available attachment points contained in this graph.
List< AttachmentPoint > getAvailableAPsThroughout ()
Returns the list of attachment points contained in this graph that are available throughout the template barrier, i.e., are free in this graph an in any embedding graph that containing this one.
AttachmentPoint getAPWithId (int id)
Returns the attachment point with the given identifier, or null if no AP is found with the given identifier.
boolean graphNeedsCappingGroups (FragmentSpace fragSpace)
Checks the graph for unused APs that need to be capped.
void removeCappingGroupsOn (Vertex vertex)
Remove capping groups on the given vertex of this graph.
void removeCappingGroups (List< Vertex > lstVerts)
Remove capping groups that belong to this graph and are in the given list.
void removeCappingGroupsFromChilds (List< Vertex > lstVerts)
void removeCappingGroups ()
Remove all capping groups on this graph.
void addCappingGroups (FragmentSpace fragSpace) throws DENOPTIMException
Add a capping groups on free unused attachment points.
void addCappingGroups (List< Vertex > vertexAddedToThis, FragmentSpace fragSpace) throws DENOPTIMException
Add a capping group on the given vertices, if needed.
DGraph extractSubgraph (int index) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
DGraph extractSubgraph (Vertex seed) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
DGraph extractSubgraph (Vertex seed, int numLayers, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex and visiting at most a given number of vertex layers, and optionally stopping the exploration of a branch before including any ring-closing vertex.
DGraph extractSubgraph (Vertex seed, List< Vertex > limits, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex and stopping the exploration at the given end vertices (i.e., limits).
DGraph extractSubgraph (Vertex seed, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
List< DGraph > extractPattern (GraphPattern pattern) throws DENOPTIMException
Extracts subgraphs that match the provided pattern.
Map< DGraph, ObjectPair > extractPattern (GraphPattern pattern, boolean recordConnectivity) throws DENOPTIMException
Extracts subgraphs that match the provided pattern.
DGraph extractSubgraph (Collection< Vertex > definedOn)
Returns a clone of the subgraph defined by the a collection of vertices belonging to this graph.
DGraph extractSubgraph (Collection< Vertex > definedOn, Set< Edge > connectionToSubgraph, Set< Edge > connectionFromSubgraph)
Returns a clone of the subgraph defined by the a collection of vertices belonging to this graph.
DGraph embedPatternsInTemplates (GraphPattern pattern, FragmentSpace fragSpace) throws DENOPTIMException
Searches for the given pattern type and generated a new graph where each set of (clones of) vertexes that define one such patterns is embedded in a single template.
DGraph embedPatternsInTemplates (GraphPattern pattern, FragmentSpace fragSpace, ContractLevel contract) throws DENOPTIMException
Searches for the given pattern type and generated a new graph where each set of (clones of) vertexes that define one such patterns is embedded in a single template.
boolean removeBranchStartingAt (Vertex v, boolean symmetry) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
boolean removeBranchStartingAt (Vertex v) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
boolean removeOrphanBranchStartingAt (Vertex v) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
boolean removeChainUpToBranching (Vertex v, FragmentSpace fragSpace) throws DENOPTIMException
Mutates the graph by removing the chain where a given vertex is located up to the first branching (i.e., to non-capping group) on either side.
void changeSignOfVertexID ()
Change all vertex IDs to the corresponding negative value.
void renumberGraphVertices ()
Reassign vertex IDs to all vertices of this graph.
Map< Long, Long > renumberVerticesGetMap ()
Reassign vertex IDs to a graph.
int getLevel (Vertex v)
Calculates the level of a vertex in this graph.
Object[] checkConsistency (RunTimeParameters settings) throws DENOPTIMException
Peeks into this graph to derive a preliminary chemical representation with SMILES and InChIKey.
Object[] checkConsistency (RunTimeParameters settings, boolean permissive) throws DENOPTIMException
Peeks into this graph to derive a preliminary chemical representation with SMILES and InChIKey.
ArrayList< DGraph > makeAllGraphsWithDifferentRingSets (RunTimeParameters settings) throws DENOPTIMException
Evaluates the possibility of closing rings in this graph and generates all alternative graphs resulting by different combinations of rings.
boolean hasForbiddenEnd (FragmentSpaceParameters fsSettings)
Check if there are forbidden ends: free attachment points that are not suitable for capping and not allowed to stay unused.
void appendGraphOnGraph (List< Vertex > parentVertices, List< Integer > parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, boolean onAllSymmAPs) throws DENOPTIMException
Append a graph (incoming=I) onto this (receiving=R).
void appendVertexOnAP (AttachmentPoint srcAP, AttachmentPoint trgAP) throws DENOPTIMException
Append a vertex to this graph: adds the new vertex to the list of vertices belonging to the graph, and adds the resulting edge to the graph.
void appendGraphOnAP (AttachmentPoint apOnThisGraph, AttachmentPoint apOnIncomingGraph, BondType bndType) throws DENOPTIMException
Appends a graph onto this graph.
void appendGraphOnAP (Vertex parentVertex, int parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, Map< Vertex, SymmetricVertexes > newSymSets) throws DENOPTIMException
Append a subgraph (I) to this graph (R) specifying which vertex and attachment point to use for the connection.
void appendGraphOnGraph (Vertex parentVertex, int parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, Map< Vertex, SymmetricVertexes > newSymSets, boolean onAllSymmAPs) throws DENOPTIMException
Append a graph (incoming=I) onto this graph (receiving=R).
List< Long > findVerticesIds (VertexQuery query, Logger logger)
Search a graph for vertices that match the criteria defined in a query vertex.
ArrayList< Vertex > findVertices (VertexQuery vrtxQuery, Logger logger)
Filters a list of vertices according to a query.
ArrayList< Vertex > findVertices (VertexQuery vrtxQuery, boolean purgeSym, Logger logger)
Filters a list of vertices according to a query.
void removeSymmetryRedundance (List< Vertex > list)
Remove all but one of the symmetry-related partners in a list of vertices.
void removeSymmetryRedundantIds (ArrayList< Long > list)
Remove all but one of the symmetry-related partners in a given list of vertex IDs.
DGraph editGraph (ArrayList< GraphEdit > edits, boolean symmetry, FragmentSpace fragSpace, Logger logger) throws DENOPTIMException
Edit this graph according to a given list of edit tasks.
List< Vertex > getMutableSites ()
A list of mutation sites from within this graph.
List< Vertex > getMutableSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this graph.
List< Vertex > getSelectedMutableSites (MutationType requestedType)
A list of mutation sites from within this graph.
String toJson ()
Produces a string that represents this graph and that adheres to the JSON format.
boolean hasScaffoldTypeVertex ()
Checks if this graph contains a scaffold vertex.
void setTemplateJacket (Template template)
Sets the reference to a template that embeds this graph, i.e., this graph's "jacket" template.
Template getTemplateJacket ()
DGraph getOutermostGraphOwner ()
List< Template > getEmbeddingPath ()
Find the path that one has to traverse to reach this graph from any template-embedding structure.
void storeCurrentVertexIDs ()
Copies the current vertexID of each vertex into a property of the vertex itself.
AttachmentPoint getAPOnLeftVertexID (long nbrVid, long vid)
Finds the AP that is on the first given parameter and that is used to make a connection to the second vertex, no matter the direction of the edge.
boolean isReversible (FragmentSpace fragSpace)
Checks is the every edge in the graph can be defined in the opposite direction according to the APClass compatibility rules.
List< AttachmentPoint > getInterfaceAPs (List< Vertex > subGraphB)
Searches for all AttachmentPoints that represent the interface between a subgraph, identified by the given list of vertices, and any other vertex, i.e., either belonging to the same graph but not to the same subgraph, or belonging to an outer embedding level.
List< AttachmentPoint > getSubgraphAPs (List< Vertex > subGraphB)
Searches for all AttachmentPoints that are owned by vertices in a subgraph but either available or used by vertices that do not belong to the subgraph.
Static Public Member Functions
static boolean compareGraphNodes (Vertex thisV, DGraph thisG, Vertex otherV, DGraph otherG) throws DENOPTIMException
Compares graphs by spanning vertices starting from the given vertex and following the direction of edges.
static DGraph fromJson (String json)
Reads a JSON string and returns an instance of this class.
static DGraph fromJson (Reader reader)
Reads a JSON string and returns an instance of this class.
static void setScaffold (Vertex v)
Update the graph so that the vertex argument is at the scaffold level i.e.
static DGraph getEmbeddedGraphInClone (DGraph graphY, DGraph graphB, List< Template > path)
Searches for a graphs (X) embedded at any level in a graph (Y) by knowing.
Protected Member Functions
void reassignSymmetricLabels ()
Marks the vertices of this graph with a string that is consistent for all vertices that belong to symmetric sets.
void convertSymmetricLabelsToSymmetricSets ()
Looks for any symmetric labels, creates symmetric sets that collect the same information, and removes the original symmetric labels.
int getUniqueAPIndex ()
void ensureUniqueApIDs ()
Package Attributes
List< Vertex > gVertices
The vertices belonging to this graph.
List< Edge > gEdges
The edges belonging to this graph.
List< Ring > gRings
The rings defined in this graph.
List< ClosableChain > closableChains
The potentially closable chains of vertices.
int graphId
String localMsg
A free-format string used to record simple properties in the graph.
Candidate candidate
Reference to the candidate entity owning this graph, or null.
Template templateJacket
Reference to the Template embedding this graph.
Private Member Functions
void dfsEncodePaths (Vertex current, String currentPath, Set< Vertex > visited, Map< String, List< Vertex > > pathMap) throws DENOPTIMException
Performs a depth-first search (DFS) starting from a given Vertex to encode paths in the graph.
boolean sameAsRings (StringBuilder reason, Map< Vertex, Vertex > vertexMap, Ring rT, Vertex vhT, Vertex vtT, Ring rO)
Static Private Member Functions
static boolean compareGraphNodes (Vertex seedOnA, DGraph gA, Vertex seedOnB, DGraph gB, Map< Vertex, Vertex > vertexMap, StringBuilder reason) throws DENOPTIMException
Compares graphs by spanning vertices starting from the given vertex and following the direction of edges.
static void reorderVertexList (DGraph g)
Sets the vertex at the lowest level as the scaffold, changes the
directions of edges so that the scaffold is the source, and changes the levels of the graph's other vertices to be consistent with the new scaffold.
static void fixEdgeDirections (DGraph graph)
Flips edges in the graph so that the scaffold is the only source vertex.
static void fixEdgeDirections (Vertex v, Set< Long > visited)
Recursive utility method for fixEdgeDirections(graph).
Private Attributes
List< SymmetricVertexes > symVertices
DefaultUndirectedGraph< Vertex, UndirectedEdge > jGraph = null
JGraph representation used to detect DENOPTIM-isomorphism.
DefaultUndirectedGraph< Node, NodeConnection > jGraphKernel = null
JGraph representation used to detect DENOPTIM-isostructural graphs.
AtomicInteger apCounter = new AtomicInteger(1)
Generator of unique AP identifiers within this graph.
Static Private Attributes
static final String SYM_ID = "symmetryKey"
Key used to uniquely identify vertices and attachment points for symmetry detection.
Detailed Description
Container for the list of vertices and the edges that connect them.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 101 of file DGraph.java.
Constructor & Destructor Documentation
DGraph() [1/5]
denoptim.graph.DGraph.DGraph (List< Vertex > gVertices, List< Edge > gEdges)
Definition at line 182 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.localMsg, and denoptim.graph.DGraph.symVertices.
DGraph() [2/5]
denoptim.graph.DGraph.DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings)
Definition at line 196 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.localMsg, and denoptim.graph.DGraph.symVertices.
DGraph() [3/5]
denoptim.graph.DGraph.DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings, List< SymmetricVertexes > symSets)
Definition at line 207 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.localMsg.
DGraph() [4/5]
denoptim.graph.DGraph.DGraph (List< Vertex > gVertices, List< Edge > gEdges, List< Ring > gRings, List< ClosableChain > closableChains, List< SymmetricVertexes > symVertices)
Definition at line 218 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.localMsg, and denoptim.graph.DGraph.symVertices.
DGraph() [5/5]
denoptim.graph.DGraph.DGraph ()
Definition at line 229 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.localMsg, and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.embedPatternsInTemplates(), and denoptim.graph.DGraph.replaceVertex().
Member Function Documentation
addCappingGroups() [1/2]
void denoptim.graph.DGraph.addCappingGroups (FragmentSpace fragSpace) throws DENOPTIMException
Add a capping groups on free unused attachment points.
Addition of Capping groups does not update the symmetry table for a symmetric graph.
Definition at line 4398 of file DGraph.java.
References denoptim.graph.DGraph.addCappingGroups(), and denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.addCappingGroups(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.EAUtils.buildGraph(), and denoptim.graph.DGraph.replaceSubGraph().
addCappingGroups() [2/2]
void denoptim.graph.DGraph.addCappingGroups (List< Vertex > vertexAddedToThis, FragmentSpace fragSpace) throws DENOPTIMException
Add a capping group on the given vertices, if needed.
The need for such groups is manifest when an attachment point that is not used in this or any embedding lever (i.e., attachment point is AttachmentPoint#isAvailableThroughout()) has and APClass that demands to be capped. Addition of Capping groups does not update the symmetry table for a symmetric graph.
Parameters
vertexAddedToThis list of vertices to operate on. They must belong to this graph.
Exceptions
DENOPTIMException if the addition of capping groups cannot be performed.
Definition at line 4421 of file DGraph.java.
References denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.getAP(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), and denoptim.graph.Vertex.newVertexFromLibrary().
addEdge()
void denoptim.graph.DGraph.addEdge (Edge edge)
Adds the edge to the list of edges belonging to this graph.
Parameters
edge to be included in the list of edges
Definition at line 1249 of file DGraph.java.
References denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.Template.getTestTemplate(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.EdgeTest.testConnectionDeconnectionLoop(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), denoptim.graph.DGraphTest.testRemoveCapping(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testSameAs_DiffRings(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_DiffVertex(), denoptim.graph.DGraphTest.testSameAs_DisorderRings(), denoptim.graph.DGraphTest.testSameAs_Equal(), denoptim.graph.DGraphTest.testSameAs_SameRings(), denoptim.graph.DGraphTest.testSameAs_SameSymmSet(), denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
addRing() [1/3]
void denoptim.graph.DGraph.addRing (Ring ring)
Definition at line 1258 of file DGraph.java.
References denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.gui.GUIGraphHandler.addChordOnGraph(), denoptim.ga.GraphOperations.addFusedRing(), denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.addRing(), denoptim.ga.GraphOperationsTest.addRings(), denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testSameAs_DiffRings(), denoptim.graph.DGraphTest.testSameAs_DisorderRings(), denoptim.graph.DGraphTest.testSameAs_SameRings(), denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion(), denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
addRing() [2/3]
void denoptim.graph.DGraph.addRing (Vertex vI, Vertex vJ) throws DENOPTIMException
Adds a chord between the given vertices, thus adding a ring in this graph.
Parameters
vI one of the ring-closing vertices.
vJ the other of the ring-closing vertices.
Exceptions
DENOPTIMException if the two vertices do not have consistent bond types to their parents and, therefore, we cannot infer the bond type of the chord.
Definition at line 1275 of file DGraph.java.
References denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
addRing() [3/3]
void denoptim.graph.DGraph.addRing (Vertex vI, Vertex vJ, BondType bndTyp)
Adds a chord between the given vertices, thus adding a ring in this graph.
Parameters
vI one of the ring-closing vertices.
vJ the other of the ring-closing vertices.
bndTyp the bond type the chord corresponds to.
Definition at line 1303 of file DGraph.java.
References denoptim.graph.DGraph.addRing(), denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, and denoptim.graph.Ring.setBondType().
addSymmetricSetOfVertices()
void denoptim.graph.DGraph.addSymmetricSetOfVertices (SymmetricVertexes symSet) throws DENOPTIMException
Adds a symmetric set of vertices to this graph.
Parameters
symSet the set to add
Exceptions
DENOPTIMException is the symmetric set being added contains an id that is already contained in another set already present.
Definition at line 889 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.ga.GraphOperations.extendGraph(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.DGraphTest.testClone(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_SameSymmSet(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
addVertex()
void denoptim.graph.DGraph.addVertex (Vertex vertex) throws DENOPTIMException
Appends a vertex to this graph without creating any edge.
This is a good way to add the first vertex, but can be used also if you intend to add edges manually.
Parameters
vertex the vertex that will be added (no cloning).
Exceptions
DENOPTIMException in the vertex has an ID that is already present in the current list of vertices of this graph, if any.
Definition at line 1325 of file DGraph.java.
References denoptim.graph.DGraph.containsVertexID(), denoptim.graph.DGraph.getGraphId(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.ga.EAUtils.buildGraph(), denoptim.ga.GraphOperationsTest.buildGraph(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.rings.PathSubGraph.findPath(), denoptim.graph.TemplateTest.getNestedTemplate(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.TemplateTest.getTemplateDeepTest(), denoptim.graph.TemplateTest.getTestAmideTemplate(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.graph.Template.getTestTemplate(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.gui.VertexAsGraphViewPanel.loadVertexStructure(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraph0(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphA(), denoptim.graph.rings.RingSizeManagerTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.rings.PathSubGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.combinatorial.CombinatorialExplorerByLayer.startNewGraphFromScaffold(), denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.graph.TemplateTest.testAtLeastSameNumberOfAPs(), denoptim.graph.AttachmentPointTest.testAvailableThrougout(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.EdgeTest.testConnectionDeconnectionLoop(), denoptim.molecularmodeling.ThreeDimTreeBuilderTest.testConversionTo3dTree(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), denoptim.ga.EAUtilsTest.testFusionSiteDetection_ImposeSymmetry(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsAPsWithTemplateAsOwner(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsCorrectNumberOfAPs(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout(), denoptim.graph.AttachmentPointTest.testGetEmbeddedAP(), denoptim.graph.AttachmentPointTest.testGetLinkedAP(), denoptim.graph.DGraphTest.testGetMutationSites(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.AttachmentPointTest.testHasConnectedSrcAtom(), denoptim.graph.AttachmentPointTest.testHasSameSrcAtom(), denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.AttachmentPointTest.testIsSrcInUser(), denoptim.graph.DGraphTest.testRemoveCapping(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion(), denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex(), denoptim.graph.TemplateTest.testSetInnerGraph_throws_on_graph_incompatible_w_requiredAPs(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
appendGraphOnAP() [1/2]
void denoptim.graph.DGraph.appendGraphOnAP (AttachmentPoint apOnThisGraph, AttachmentPoint apOnIncomingGraph, BondType bndType) throws DENOPTIMException
Appends a graph onto this graph.
The operation is not projected by symmetry, and the incoming graph is not cloned/copied.
Parameters
apOnThisGraph where to append to on this growing graph.
apOnIncomingGraph where to connect this graph into the incoming one.
bndType the bond type of the new edge created.
Exceptions
DENOPTIMException
Definition at line 6058 of file DGraph.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.DGraph.getRings(), denoptim.graph.DGraph.getVertexList(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraph.appendGraphOnGraph().
appendGraphOnAP() [2/2]
void denoptim.graph.DGraph.appendGraphOnAP (Vertex parentVertex, int parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, Map< Vertex, SymmetricVertexes > newSymSets) throws DENOPTIMException
Append a subgraph (I) to this graph (R) specifying which vertex and attachment point to use for the connection.
Does not project on symmetrically related vertices or attachment points. No change in symmetric sets, apart from importing those sets that are already defined in the subgraph.
Parameters
parentVertex the vertex of R on which a copy of I is to be attached.
parentAPIdx the attachment point on R's vertex to be used to attach I
subGraph the incoming graph I, or child graph.
childVertex the vertex of I that is to be connected to R
childAPIdx the index of the attachment point on the vertex of I that is to be connected to R
bndType the bond type between R and I
newSymSets of symmetric sets. This parameter is only used to keep track of the symmetric copies of I. Simply provide an empty data structure.
Definition at line 6112 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.DGraph.getRings(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.getVertexWithId(), and denoptim.graph.DGraph.renumberGraphVertices().
appendGraphOnGraph() [1/2]
void denoptim.graph.DGraph.appendGraphOnGraph (List< Vertex > parentVertices, List< Integer > parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, boolean onAllSymmAPs) throws DENOPTIMException
Append a graph (incoming=I) onto this (receiving=R).
Can append one or more copies of the same graph. The corresponding vertex and attachment point ID for each connection are given in separated arrays.
Parameters
parentVertices the list of source vertices of R on which a copy of I is to be attached.
parentAPIdx the list of attachment points on R's vertices to be used to attach I
subGraph the incoming graph I, or child
childVertex the vertex of I that is to be connected to R
childAPIdx the index of the attachment point on the vertex of I that is to be connected to R
bndType the bond type between R and I
onAllSymmAPs set to true to require the same graph I to be attached on all available and symmetric APs on the same vertex of the AP indicated in the list.
Definition at line 5972 of file DGraph.java.
References denoptim.graph.DGraph.appendGraphOnGraph().
Referenced by denoptim.graph.DGraph.appendGraphOnGraph(), and denoptim.graph.DGraph.editGraph().
appendGraphOnGraph() [2/2]
void denoptim.graph.DGraph.appendGraphOnGraph (Vertex parentVertex, int parentAPIdx, DGraph subGraph, Vertex childVertex, int childAPIdx, BondType bndType, Map< Vertex, SymmetricVertexes > newSymSets, boolean onAllSymmAPs) throws DENOPTIMException
Append a graph (incoming=I) onto this graph (receiving=R).
Parameters
parentVertex the vertex of R on which the a copy of I is to be attached.
parentAPIdx the attachment point on R's vertex to be used to attach I
subGraph the incoming graph I, or child
childVertex the vertex of I that is to be connected to R
childAPIdx the index of the attachment point on the vertex of I that is to be connected to R
bndType the bond type between R and I
newSymSets this parameter is only used to keep track of the symmetric copies of I. Simply provide an empty data structure.
onAllSymmAPs set to true to require the same graph I to be attached on all available and symmetric APs on the same vertex of the AP indicated in the list.
Definition at line 6237 of file DGraph.java.
References denoptim.graph.DGraph.appendGraphOnAP().
appendVertexOnAP()
void denoptim.graph.DGraph.appendVertexOnAP (AttachmentPoint srcAP, AttachmentPoint trgAP) throws DENOPTIMException
Append a vertex to this graph: adds the new vertex to the list of vertices belonging to the graph, and adds the resulting edge to the graph.
Does not clone the incoming vertex. Does not project on symmetrically related vertices or attachment points. No change in symmetric sets, apart from importing those sets that are already defined in the incoming vertex.
Parameters
srcAP the attachment point on this graph (source AP).
trgAP the attachment point on the incoming vertex (target AP).
Exceptions
DENOPTIMException
Definition at line 6005 of file DGraph.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Edge.BondType.ANY, denoptim.graph.Edge.BondType.UNDEFINED, and denoptim.io.DenoptimIO.writeGraphToJSON().
Referenced by denoptim.graph.DGraph.addCappingGroups(), denoptim.ga.GraphOperations.addFusedRing(), denoptim.ga.GraphOperations.addRing(), denoptim.ga.GraphOperationsTest.buildGraph(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.rings.PathSubGraph.findPath(), denoptim.graph.TemplateTest.getNestedTemplate(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.TemplateTest.getTemplateDeepTest(), denoptim.graph.TemplateTest.getTestAmideTemplate(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.rings.RingSizeManagerTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.graph.AttachmentPointTest.testAvailableThrougout(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs(), denoptim.graph.TemplateTest.testGetAttachmentPoints_returnsCorrectNumberOfAPs(), denoptim.graph.AttachmentPointTest.testGetEdbeUserThrougout(), denoptim.graph.AttachmentPointTest.testGetEmbeddedAP(), denoptim.graph.AttachmentPointTest.testGetLinkedAP(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.VertexTest.testIsConnectedToAromaticBridge(), denoptim.graph.AttachmentPointTest.testIsSrcInUser(), denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion(), and denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex().
changeSignOfVertexID()
void denoptim.graph.DGraph.changeSignOfVertexID ()
Change all vertex IDs to the corresponding negative value.
For instance if the vertex ID is 12 this method changes it into -12.
Definition at line 5481 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Edge.getSrcAP(), denoptim.graph.Edge.getSrcVertex(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.Edge.getTrgVertex(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), and denoptim.graph.Vertex.setVertexId().
checkConsistency() [1/2]
Object[] denoptim.graph.DGraph.checkConsistency (RunTimeParameters settings) throws DENOPTIMException
Peeks into this graph to derive a preliminary chemical representation with SMILES and InChIKey.
The chemical entity is evaluated also against the criteria defined by the given settings WARNING Although Cartesian coordinates are assigned to each atom and pseudo-atom in the molecular representation, such coordinates do NOT represent a valid 3D model. As a consequence stereochemical descriptors in the INCHI representation are not consistent with the actual arrangement of fragments.
Parameters
settings the collection of settings defining the criteria with which we evaluate the graph.
Returns
an object array containing the InChI key, the SMILES string and the 2D representation of the molecule. null is returned if any check or conversion fails.
Exceptions
DENOPTIMException
Definition at line 5582 of file DGraph.java.
References denoptim.graph.DGraph.checkConsistency().
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.DGraph.checkConsistency(), and denoptim.ga.EAUtils.readCandidateFromFile().
checkConsistency() [2/2]
Object[] denoptim.graph.DGraph.checkConsistency (RunTimeParameters settings, boolean permissive) throws DENOPTIMException
Peeks into this graph to derive a preliminary chemical representation with SMILES and InChIKey.
The chemical entity is evaluated also against the criteria defined by the given settings WARNING Although Cartesian coordinates are assigned to each atom and pseudo-atom in the molecular representation, such coordinates do NOT represent a valid 3D model. As a consequence stereochemical descriptors in the INCHI representation are not consistent with the actual arrangement of fragments.
Parameters
settings the collection of settings defining the criteria with which we evaluate the graph.
permissive use true to ignore some of the most strict filtering criteria. This is typically done only when reading graphs from the user, thus assuming the user does intend to by-pass some filters when inspecting a graph that might not be possible to generate from the given settings,
Returns
an object array containing the InChI key, the SMILES string and the 2D representation of the molecule. null is returned if any check or conversion fails.
Exceptions
DENOPTIMException
Definition at line 5613 of file DGraph.java.
References denoptim.graph.rings.RingClosureParameters.allowRingClosures(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.programs.RunTimeParameters.ParametersType.FS_PARAMS, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.utils.MoleculeUtils.getHeavyAtomCount(), denoptim.utils.MoleculeUtils.getInChIKeyForMolecule(), denoptim.fragspace.FragmentSpaceParameters.getMaxHeavyAtom(), denoptim.fragspace.FragmentSpaceParameters.getMaxMW(), denoptim.graph.rings.RingClosureParameters.getMaxRcaPerType(), denoptim.fragspace.FragmentSpaceParameters.getMaxRotatableBond(), denoptim.graph.rings.RingClosureParameters.getMinRcaPerType(), denoptim.graph.rings.RingClosureParameters.getMinRingClosures(), denoptim.utils.MoleculeUtils.getMolecularWeight(), denoptim.utils.MoleculeUtils.getNumberOfRotatableBonds(), denoptim.programs.RunTimeParameters.getParameters(), denoptim.graph.DGraph.getRCVertices(), denoptim.utils.MoleculeUtils.getSMILESForMolecule(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.graph.DGraph.hasForbiddenEnd(), denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.graph.rings.RingClosingAttractor.RCATYPEMAP, denoptim.molecularmodeling.ThreeDimTreeBuilder.setAlignBBsIn3D(), denoptim.graph.DGraph.toString(), and denoptim.fragspace.FragmentSpace.useAPclassBasedApproach().
cleanup()
void denoptim.graph.DGraph.cleanup ()
Wipes the data in this graph.
Definition at line 3597 of file DGraph.java.
References denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.graph.Candidate.cleanup(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.ga.EAUtils.readCandidateFromFile(), and denoptim.task.FitnessTask.runExternalFitness().
clone()
DGraph denoptim.graph.DGraph.clone ()
Returns almost "deep-copy" of this graph.
Only the APCLass members of member of this class should remain references to the original APClasses. The vertex IDs are not changed, so you might want to renumber the graph.
Definition at line 3415 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.Ring.addVertex(), denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.clone(), denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.gEdges, denoptim.graph.AttachmentPoint.getBondType(), denoptim.graph.Vertex.getIndexOfAP(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.getVertexWithId(), denoptim.graph.DGraph.graphId, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.localMsg, denoptim.graph.Ring.setBondType(), denoptim.graph.DGraph.setCandidateClosableChains(), denoptim.graph.DGraph.setGraphId(), denoptim.graph.DGraph.setLocalMsg(), denoptim.graph.DGraph.setRings(), denoptim.graph.DGraph.setSymmetricVertexSets(), and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.appendGraphOnAP(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.programs.fitnessevaluator.FitnessEvaluationTask.call(), denoptim.graph.Candidate.clone(), denoptim.graph.DGraph.clone(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.DGraph.extractSubgraph(), denoptim.ga.GraphOperationsTest.getExpectedSubgraphs(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.ga.GraphOperations.performMutation(), denoptim.ga.XoverSite.projectToClonedGraphs(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.ga.EAUtils.searchRingFusionSites(), denoptim.combinatorial.CEBLUtils.storeAllGraphsOfLevel(), denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), denoptim.graph.DGraphTest.testClone(), denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce(), denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
compareGraphNodes() [1/2]
static boolean denoptim.graph.DGraph.compareGraphNodes (Vertex seedOnA, DGraph gA, Vertex seedOnB, DGraph gB, Map< Vertex, Vertex > vertexMap, StringBuilder reason) throws DENOPTIMException static private
Compares graphs by spanning vertices starting from the given vertex and following the direction of edges.
Parameters
seedOnA initial vertex on the first graph.
gA the first graph.
seedOnB initial vertex on the second graph.
gB the second graph.
vertexMap vertex mapping.
reason a string recording the reason for returning false.
Returns
true if the graphs are same at this node.
Exceptions
DENOPTIMException
Definition at line 4078 of file DGraph.java.
References denoptim.graph.DGraph.compareGraphNodes(), and denoptim.graph.Edge.getTrgVertex().
compareGraphNodes() [2/2]
static boolean denoptim.graph.DGraph.compareGraphNodes (Vertex thisV, DGraph thisG, Vertex otherV, DGraph otherG) throws DENOPTIMException static
Compares graphs by spanning vertices starting from the given vertex and following the direction of edges.
Parameters
thisV starting vertex of first graph
thisG first graph
otherV starting vertex of second graph
otherG second graph
Returns
true if the graphs are same at this node
Exceptions
DENOPTIMException
Definition at line 4054 of file DGraph.java.
References denoptim.graph.DGraph.compareGraphNodes().
Referenced by denoptim.graph.DGraph.compareGraphNodes(), denoptim.graph.DGraph.sameAs(), and denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem().
containsAtoms()
boolean denoptim.graph.DGraph.containsAtoms ()
Returns true if this graph has any vertex that contains atoms.
Returns
true if this graph has any vertex that contains atoms.
Definition at line 4164 of file DGraph.java.
References denoptim.graph.DGraph.getVertexList().
Referenced by denoptim.graph.Template.containsAtoms(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
containsOrEmbedsVertex()
boolean denoptim.graph.DGraph.containsOrEmbedsVertex (Vertex v)
Check if the specified vertex is contained in this graph as a node or in any inner graphs that may be embedded in Template-kind vertex belonging to this graph.
Parameters
v the vertex.
Returns
true if the vertex belongs to this graph or is anyhow embedded in it.
Definition at line 2759 of file DGraph.java.
References denoptim.graph.DGraph.containsOrEmbedsVertex(), denoptim.graph.Template.getInnerGraph(), and denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.EAUtils.buildGraph(), and denoptim.graph.DGraph.containsOrEmbedsVertex().
containsVertex()
boolean denoptim.graph.DGraph.containsVertex (Vertex v)
Check if this graph contains the specified vertex.
Does not consider inner graphs that may be embedded in Template-kind vertex belonging to this graph.
Parameters
v the vertex.
Returns
true if the vertex belongs to this graph.
Definition at line 2786 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraphTest.testRemoveCapping(), and denoptim.graph.DGraphTest.testReplaceVertex().
containsVertexID()
boolean denoptim.graph.DGraph.containsVertexID (long l)
Checks if a number is already used as VertexIDs within the graph.
Returns
true if the number is already used.
Definition at line 3578 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.addVertex().
convertSymmetricLabelsToSymmetricSets()
void denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets () protected
Looks for any symmetric labels, creates symmetric sets that collect the same information, and removes the original symmetric labels.
Definition at line 1828 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.hasSymmetryInvolvingVertex(), and denoptim.constants.DENOPTIMConstants.VRTSYMMSETID.
Referenced by denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), and denoptim.graph.DGraphTest.testReplaceSubGraph().
detectSymVertexSets()
boolean denoptim.graph.DGraph.detectSymVertexSets () throws DENOPTIMException
Detects and groups symmetric sets of Vertexes in the graph based on unique identification and path encoding.
This function first identifies unique Vertexes and their AttachmentPoints, assigns them unique identifiers, and uses depth-first search (DFS) to encode paths to these Vertexes starting from the designated scaffold. Vertexes with identical path encodings are considered symmetric and are grouped together.
Returns
true if some symmetric set of vertex has been found.
Exceptions
DENOPTIMException
Definition at line 368 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.dfsEncodePaths(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getProperty(), denoptim.graph.Vertex.getProperty(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.AttachmentPoint.setProperty(), denoptim.graph.Vertex.setProperty(), denoptim.graph.DGraph.SYM_ID, and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), and denoptim.graph.DGraphTest.testDetectSymVertexSets().
dfsEncodePaths()
void denoptim.graph.DGraph.dfsEncodePaths (Vertex current, String currentPath, Set< Vertex > visited, Map< String, List< Vertex > > pathMap) throws DENOPTIMException private
Performs a depth-first search (DFS) starting from a given Vertex to encode paths in the graph.
This method appends the unique identifier of each Vertex and its AttachmentPoints to the current path string as it traverses the graph. Each unique path is stored in a map, with Vertexes collected under their respective path encodings. This encoding helps in identifying symmetric Vertexes based on shared path signatures.
Parameters
current The current vertex from which the DFS is initiated.
currentPath The encoded path string accumulated up to the current vertex.
visited A set of visited vertices to avoid re-visitation.
pathMap A map that aggregates vertices under their unique path encodings.
Exceptions
DENOPTIMException
Definition at line 487 of file DGraph.java.
References denoptim.graph.DGraph.dfsEncodePaths(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getProperty(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.DGraph.SYM_ID, and denoptim.graph.Vertex.toString().
Referenced by denoptim.graph.DGraph.detectSymVertexSets(), and denoptim.graph.DGraph.dfsEncodePaths().
directedPathExists()
boolean denoptim.graph.DGraph.directedPathExists (Vertex src, Vertex trg)
Uses branch identifiers to define is two vertices are in such a relation that allows the drawing of a directed path from one to the other.
You must run getChildrenTree(Vertex, List, AtomicInteger, List) on any parent of either graph to generate the bran branch labeling.
Parameters
src the "from" in the directed path relation.
trg the "to" in the directed path relation.
Returns
true if the relation exists, false is if doesn't OR if the branch labeling has not been found.
Definition at line 3229 of file DGraph.java.
References denoptim.graph.DGraph.getBranchIdOfVertex().
Referenced by denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier().
editGraph()
DGraph denoptim.graph.DGraph.editGraph (ArrayList< GraphEdit > edits, boolean symmetry, FragmentSpace fragSpace, Logger logger) throws DENOPTIMException
Edit this graph according to a given list of edit tasks.
This method assumes the vertex IDs are unique.
Parameters
edits the list of edit tasks.
symmetry if true the same operation is performed on vertices related by symmetry.
fragSpace the space of building blocks needed to perform the graph editing tasks. It may or may not be the space that generated the original version of the graph to edit.
logger the logger to use
Returns
the modified graph.
Definition at line 6685 of file DGraph.java.
References denoptim.graph.DGraph.appendGraphOnGraph(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.DGraph.findVertices(), denoptim.graph.DGraph.getAPWithId(), denoptim.graph.DGraph.getAvailableAPs(), denoptim.graph.Edge.getBondType(), denoptim.graph.DGraph.getGraphId(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getParent(), denoptim.graph.Edge.getSrcAPID(), denoptim.utils.GraphEdit.getType(), denoptim.graph.DGraph.removeBranchStartingAt(), denoptim.graph.DGraph.renumberGraphVertices(), denoptim.graph.DGraph.replaceSingleSubGraph(), and denoptim.graph.DGraph.replaceVertex().
Referenced by denoptim.programs.grapheditor.GraphEditor.runProgram().
embedPatternsInTemplates() [1/2]
DGraph denoptim.graph.DGraph.embedPatternsInTemplates (GraphPattern pattern, FragmentSpace fragSpace) throws DENOPTIMException
Searches for the given pattern type and generated a new graph where each set of (clones of) vertexes that define one such patterns is embedded in a single template.
Parameters
pattern type of pattern to embed in template.
Returns
a new graph where the vertexes defining each pattern are replaced by a template that embeds the subgraph of the pattern.
Exceptions
DENOPTIMException
Definition at line 4845 of file DGraph.java.
References denoptim.graph.DGraph.embedPatternsInTemplates(), and denoptim.graph.Template.ContractLevel.FREE.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), and denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol().
embedPatternsInTemplates() [2/2]
DGraph denoptim.graph.DGraph.embedPatternsInTemplates (GraphPattern pattern, FragmentSpace fragSpace, ContractLevel contract) throws DENOPTIMException
Searches for the given pattern type and generated a new graph where each set of (clones of) vertexes that define one such patterns is embedded in a single template.
Parameters
pattern type of pattern to embed in template.
fragSpace the fragment space that defines how we manipulate fragments.
contract the level of constraint to set for any template that embeds one of the patterns.
Returns
a new graph where the vertexes defining each pattern are replaced by a template that embeds the subgraph of the pattern.
Exceptions
DENOPTIMException
Definition at line 4866 of file DGraph.java.
References denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.ensureUniqueApIDs(), denoptim.graph.DGraph.extractPattern(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.DGraph.getAPWithId(), denoptim.graph.AttachmentPoint.getID(), denoptim.graph.Template.getOuterAPFromInnerAP(), denoptim.graph.Vertex.getProperty(), denoptim.graph.DGraph.getVertexWithId(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.hasScaffoldTypeVertex(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.Template.setContractLevel(), denoptim.graph.Template.setInnerGraph(), and denoptim.constants.DENOPTIMConstants.STOREDVID.
ensureUniqueApIDs()
void denoptim.graph.DGraph.ensureUniqueApIDs () protected
Definition at line 6935 of file DGraph.java.
References denoptim.graph.DGraph.apCounter, and denoptim.graph.DGraph.getAttachmentPoints().
Referenced by denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), and denoptim.graph.Template.toJson().
extractPattern() [1/2]
List< DGraph > denoptim.graph.DGraph.extractPattern (GraphPattern pattern) throws DENOPTIMException
Extracts subgraphs that match the provided pattern.
Parameters
pattern to match against.
Returns
The subgraphs matching the provided pattern. These contain clones of the vertexes in this graph.
Exceptions
DENOPTIMException
Definition at line 4686 of file DGraph.java.
References denoptim.graph.DGraph.extractPattern().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.DGraph.extractPattern(), denoptim.ga.GraphOperationsTest.testExtractPattern_fusedRings(), denoptim.ga.GraphOperationsTest.testExtractPattern_returnsEmptyListIfNoRings(), and denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem().
extractPattern() [2/2]
Map< DGraph, ObjectPair > denoptim.graph.DGraph.extractPattern (GraphPattern pattern, boolean recordConnectivity) throws DENOPTIMException
Extracts subgraphs that match the provided pattern.
This method offers the possibility to record the connections that cross the border of each subgraph.
Parameters
pattern to match against.
recordConnectivity if true makes this method collect the edges of this graph that cross the subgraph borders. If false the resulting map will have only keys and null values.
Returns
The subgraphs matching the provided pattern. Each such subgraph contains clones of the vertexes in this graph. Each value of the returned map contains two lists defining which edges cross the subgraph border: first, the list of incoming edges (i.e., the source AttachmentPoint belongs to a vertex that does not belong the subgraph), second, the list of outgoing edges (i.e., the source AttachmentPoint belongs to a vertex that does belong the subgraph). Note that the owners of the AttachmentPoints are NOT the Vertex instances that are container in the map's key, but are their clones.
Exceptions
DENOPTIMException
Definition at line 4717 of file DGraph.java.
References denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.Ring.getVertices(), denoptim.graph.DGraph.reorderVertexList(), denoptim.graph.GraphPattern.RING, and denoptim.utils.GeneralUtils.unionOfIntersectingSets().
extractSubgraph() [1/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Collection< Vertex > definedOn)
Returns a clone of the subgraph defined by the a collection of vertices belonging to this graph.
Parameters
definedOn Set of vertices that defined the subgraph.
Returns
a clone of the subgraph of this graph.
Definition at line 4768 of file DGraph.java.
References denoptim.graph.DGraph.extractSubgraph().
extractSubgraph() [2/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Collection< Vertex > definedOn, Set< Edge > connectionToSubgraph, Set< Edge > connectionFromSubgraph)
Returns a clone of the subgraph defined by the a collection of vertices belonging to this graph.
It also collects which Edges exists between the subgraph and the rest of the graph.
Parameters
definedOn Set of vertices that defined the subgraph.
connectionToSubgraph container for the collection of edges that arrive at the subgraph.
connectionFromSubgraph container for the collection of edges that depart from the subgraph.
Returns
Subgraph of graph defined on set of vertices.
Definition at line 4787 of file DGraph.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.DGraph.getVertexList(), and denoptim.graph.DGraph.removeVertex().
extractSubgraph() [3/7]
DGraph denoptim.graph.DGraph.extractSubgraph (int index) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
Only the seed vertex and all child vertices (and further successors) are considered part of the subgraph, which includes also rings and symmetric sets. All rings that include vertices not belonging to the subgraph are lost.
Parameters
index the position of the seed vertex in the list of vertices of this graph.
Returns
a new graph that corresponds to the subgraph of this graph.
Definition at line 4487 of file DGraph.java.
References denoptim.graph.DGraph.extractSubgraph(), and denoptim.graph.DGraph.getVertexAtPosition().
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.graph.DGraph.extractPattern(), denoptim.graph.DGraph.extractSubgraph(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.ga.GraphOperations.performCrossover(), denoptim.ga.GraphOperations.processPermutationOfEndPoints(), denoptim.graph.DGraphTest.testExtractSubgraph(), and denoptim.graph.DGraphTest.testExtractSubgraphFromCollection().
extractSubgraph() [4/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Vertex seed) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
Only the seed vertex and all child vertices (and further successors) are considered part of the subgraph, which includes also rings and symmetric sets. All rings that include vertices not belonging to the subgraph are lost.
Parameters
seed the vertex from which the extraction has to start.
Returns
a new graph that corresponds to the subgraph of this graph.
Definition at line 4506 of file DGraph.java.
References denoptim.graph.DGraph.extractSubgraph().
extractSubgraph() [5/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Vertex seed, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex.
Optionally, you can ask to stop the exploration of a branch before including any ring-closing vertex. Only the seed vertex and all child vertices (and further successors) are considered part of the subgraph, which includes also rings and symmetric sets. All rings that include vertices not belonging to the subgraph are lost.
Parameters
seed the vertex from which the extraction has to start.
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Returns
a new graph that corresponds to the subgraph of this graph.
Definition at line 4643 of file DGraph.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.getChildTreeLimited(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.indexOf(), and denoptim.graph.DGraph.removeVertex().
extractSubgraph() [6/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Vertex seed, int numLayers, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex and visiting at most a given number of vertex layers, and optionally stopping the exploration of a branch before including any ring-closing vertex.
Only the seed vertex and all child vertices (and further successors) are considered part of the subgraph, which includes also rings and symmetric sets. All rings that include vertices not belonging to the subgraph are lost.
Parameters
seed the vertex from which the extraction has to start.
numLayers the maximum number of vertex layers after the seen vertex that we want to consider before stopping. If this value is 2, we will explore three layers: the seed, and two more layers away from it.
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Returns
a new graph that corresponds to the subgraph of this graph.
Definition at line 4532 of file DGraph.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.indexOf(), and denoptim.graph.DGraph.removeVertex().
extractSubgraph() [7/7]
DGraph denoptim.graph.DGraph.extractSubgraph (Vertex seed, List< Vertex > limits, boolean stopBeforeRCVs) throws DENOPTIMException
Creates a new graph that corresponds to the subgraph of this graph when exploring the spanning tree from a given seed vertex and stopping the exploration at the given end vertices (i.e., limits).
Optionally, you can ask to stop the exploration of a branch before including any ring-closing vertex. Only the seed vertex and all child vertices (and further successors) are considered part of the subgraph, which includes also rings and symmetric sets. All rings that include vertices not belonging to the subgraph are lost.
Parameters
seed the vertex from which the extraction has to start.
limits the vertices playing the role of subgraph end-points that stop the exploration of the graph.
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Returns
a new graph that corresponds to the subgraph of this graph.
Definition at line 4583 of file DGraph.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getChildTreeLimited(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.indexOf(), and denoptim.graph.DGraph.removeVertex().
findVertices() [1/2]
ArrayList< Vertex > denoptim.graph.DGraph.findVertices (VertexQuery vrtxQuery, boolean purgeSym, Logger logger)
Filters a list of vertices according to a query.
vertex.
Parameters
vrtxQuery the query defining what is that we want to find.
purgeSym use true to remove symmetrically redundant matches.
logger manager of log
Returns
the list of vertices that match the query.
Definition at line 6311 of file DGraph.java.
References denoptim.graph.DGraph.EdgeFinder.apply(), denoptim.graph.EdgeQuery.getBondType(), denoptim.graph.VertexQuery.getInEdgeQuery(), denoptim.graph.DGraph.getLevel(), denoptim.graph.VertexQuery.getOutEdgeQuery(), denoptim.graph.EdgeQuery.getSourceAPClass(), denoptim.graph.EdgeQuery.getSourceAPIdx(), denoptim.graph.EdgeQuery.getSourceVertexId(), denoptim.graph.EdgeQuery.getTargetAPClass(), denoptim.graph.EdgeQuery.getTargetAPIdx(), denoptim.graph.EdgeQuery.getTargetVertexId(), denoptim.graph.VertexQuery.getVertexBBIDQuery(), denoptim.graph.VertexQuery.getVertexBBTypeQuery(), denoptim.graph.VertexQuery.getVertexIDQuery(), denoptim.graph.VertexQuery.getVertexLevelQuery(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.VertexQuery.getVertexTypeQuery(), and denoptim.graph.DGraph.removeSymmetryRedundance().
findVertices() [2/2]
ArrayList< Vertex > denoptim.graph.DGraph.findVertices (VertexQuery vrtxQuery, Logger logger)
Filters a list of vertices according to a query.
vertex. Always removed symmetry-redundant matches.
Parameters
vrtxQuery the query defining what is that we want to find.
logger manager of log
Returns
the list of vertices that match the query.
Definition at line 6294 of file DGraph.java.
References denoptim.graph.DGraph.findVertices().
Referenced by denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.findVertices(), denoptim.graph.DGraph.findVerticesIds(), and denoptim.graph.DGraphTest.testFindVertex().
findVerticesIds()
List< Long > denoptim.graph.DGraph.findVerticesIds (VertexQuery query, Logger logger)
Search a graph for vertices that match the criteria defined in a query vertex.
Parameters
query the query
logger manager of log
Returns
the list of matches
Definition at line 6274 of file DGraph.java.
References denoptim.graph.DGraph.findVertices().
fixEdgeDirections() [1/2]
static void denoptim.graph.DGraph.fixEdgeDirections (DGraph graph) static private
Flips edges in the graph so that the scaffold is the only source vertex.
Parameters
graph to fix edges of.
Definition at line 4962 of file DGraph.java.
References denoptim.graph.DGraph.fixEdgeDirections(), and denoptim.graph.DGraph.getSourceVertex().
Referenced by denoptim.graph.DGraph.fixEdgeDirections(), and denoptim.graph.DGraph.reorderVertexList().
fixEdgeDirections() [2/2]
static void denoptim.graph.DGraph.fixEdgeDirections (Vertex v, Set< Long > visited) static private
Recursive utility method for fixEdgeDirections(graph).
Parameters
v current vertex
Definition at line 4974 of file DGraph.java.
References denoptim.graph.DGraph.fixEdgeDirections(), denoptim.graph.Edge.flipEdge(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Edge.getSrcVertex(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.Edge.getTrgVertex(), and denoptim.graph.Vertex.getVertexId().
fromJson() [1/2]
static DGraph denoptim.graph.DGraph.fromJson (Reader reader) static
Reads a JSON string and returns an instance of this class.
Parameters
json the string to parse.
Returns
a new instance of this class.
Definition at line 6966 of file DGraph.java.
References denoptim.graph.DGraph.fromJson(), and denoptim.json.DENOPTIMgson.getReader().
fromJson() [2/2]
static DGraph denoptim.graph.DGraph.fromJson (String json) static
Reads a JSON string and returns an instance of this class.
Parameters
json the string to parse.
Returns
a new instance of this class.
Definition at line 6951 of file DGraph.java.
References denoptim.graph.DGraph.fromJson(), and denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.fromJson(), denoptim.graph.Template.fromJson(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), denoptim.io.DenoptimIO.readGraphFromSDFileIAC(), and denoptim.graph.DGraphTest.testFromToJSON().
getAPOnLeftVertexID()
AttachmentPoint denoptim.graph.DGraph.getAPOnLeftVertexID (long nbrVid, long vid)
Finds the AP that is on the first given parameter and that is used to make a connection to the second vertex, no matter the direction of the edge.
If the two vertices are connected by a chord, i.e., there is a pair of RCVs in between the two vertices, we still work out the AP on the vertex on the left, even if in the graph it is actually used to bind the RCV that defines the chord and that eventually connects the vertex on the left with that on the right.
Parameters
nbrVid vertex ID of one vertex.
vid vertex ID of another vertex.
Returns
the AttachmentPoint or null is the two vertex IDs are not connected in this graph.
Definition at line 7271 of file DGraph.java.
References denoptim.graph.DGraph.getChildVertices(), denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.Edge.getSrcAP(), denoptim.graph.Edge.getTrgAP(), and denoptim.graph.DGraph.getVertexWithId().
getAPWithId()
AttachmentPoint denoptim.graph.DGraph.getAPWithId (int id)
Returns the attachment point with the given identifier, or null if no AP is found with the given identifier.
Parameters
id identifier of the attachment point to return
Returns
the attachment point with the given identifier, or null if no AP is found with the given identifier.
Definition at line 4264 of file DGraph.java.
References denoptim.graph.DGraph.getAttachmentPoints().
Referenced by denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.embedPatternsInTemplates(), and denoptim.graph.Template.updateInnerToOuter().
getAttachmentPoints()
ArrayList< AttachmentPoint > denoptim.graph.DGraph.getAttachmentPoints ()
Returns the list of all attachment points contained in this graph.
Returns
list of attachment points.
Definition at line 4199 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.ensureUniqueApIDs(), denoptim.graph.DGraph.getAPWithId(), denoptim.graph.DGraph.getAvailableAPs(), denoptim.graph.DGraph.getAvailableAPsThroughout(), denoptim.ga.EAUtilsTest.testCrowdingProbability(), and denoptim.ga.EAUtilsTest.testSearchForApPairsSuitableToRingFusion().
getAvailableAPs()
ArrayList< AttachmentPoint > denoptim.graph.DGraph.getAvailableAPs ()
Returns the list of available attachment points contained in this graph.
Returns
list of attachment points.
Definition at line 4217 of file DGraph.java.
References denoptim.graph.DGraph.getAttachmentPoints().
Referenced by denoptim.graph.DGraph.editGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.Template.isValidInnerGraph(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.Template.setInnerGraph(), denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getAvailableAPsThroughout()
List< AttachmentPoint > denoptim.graph.DGraph.getAvailableAPsThroughout ()
Returns the list of attachment points contained in this graph that are available throughout the template barrier, i.e., are free in this graph an in any embedding graph that containing this one.
Returns
list of attachment points.
Definition at line 4240 of file DGraph.java.
References denoptim.graph.DGraph.getAttachmentPoints().
Referenced by denoptim.ga.GraphOperations.addRing().
getBondingAPIndex()
int denoptim.graph.DGraph.getBondingAPIndex (Vertex srcVert, int dapidx, Vertex dstVert)
Parameters
srcVert
dapidx the AP corresponding to the source fragment
dstVert
Returns
the AP index of the destination fragment
Deprecated:
this depends on vertedID rather than reference
Definition at line 2954 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.Edge.getSrcAPID(), denoptim.graph.Edge.getSrcVertex(), denoptim.graph.Edge.getTrgAPID(), denoptim.graph.Edge.getTrgVertex(), and denoptim.graph.Vertex.getVertexId().
getBranchIdOfVertex()
List< Integer > denoptim.graph.DGraph.getBranchIdOfVertex (Vertex v)
Returns the branch identifier.
Parameters
i the position of the vertex to analyze.
Returns
the branch identifier or null if the vertex does not belong to this graph or if such property is not available. In the latter case, you should run getChildrenTree(Vertex, List, AtomicInteger, List) on any of the parent vertices.
Definition at line 3187 of file DGraph.java.
References denoptim.constants.DENOPTIMConstants.GRAPHBRANCHID, and denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.directedPathExists(), denoptim.graph.DGraph.getBranchIdOfVertexAsStr(), and denoptim.graph.DGraph.getBranchIdOfVertexAtPosition().
getBranchIdOfVertexAsStr()
String denoptim.graph.DGraph.getBranchIdOfVertexAsStr (Vertex v)
Returns the branch identifier as a literal string.
Parameters
i the position of the vertex to analyze.
Returns
the branch identifier expressed as a string or null if the vertex does not belong to this graph or if such property is not available. In the latter case, you should run getChildrenTree(Vertex, List, AtomicInteger, List) on any of the parent vertices.
Definition at line 3207 of file DGraph.java.
References denoptim.graph.DGraph.getBranchIdOfVertex().
Referenced by denoptim.ga.GraphOperations.locateCompatibleXOverPoints().
getBranchIdOfVertexAtPosition()
List< Integer > denoptim.graph.DGraph.getBranchIdOfVertexAtPosition (int i)
Returns the branch identifier.
Parameters
i the position of the vertex to analyze.
Returns
the branch identifier or null if such property is not available. In such case, you should run getChildrenTree(Vertex, List, AtomicInteger, List) on any of the parent vertices.
Definition at line 3170 of file DGraph.java.
References denoptim.graph.DGraph.getBranchIdOfVertex(), and denoptim.graph.DGraph.getVertexAtPosition().
Referenced by denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier().
getCandidateOwner()
Candidate denoptim.graph.DGraph.getCandidateOwner ()
Returns the reference of the candidate item that is defined by this graph.
Returns
the reference to the owner or null.
Definition at line 257 of file DGraph.java.
References denoptim.graph.DGraph.candidate.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), and denoptim.ga.EAUtils.buildCandidatesByXOver().
getChildrenTree() [1/4]
void denoptim.graph.DGraph.getChildrenTree (Vertex vertex, List< Vertex > children)
Gets all the children of the current vertex recursively.
This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
Definition at line 3000 of file DGraph.java.
References denoptim.graph.DGraph.getChildrenTree(), and denoptim.graph.DGraph.getChildVertices().
Referenced by denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getChildrenTree(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.graph.DGraph.removeOrphanBranchStartingAt(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), denoptim.graph.DGraphTest.testGetChildrenTree(), and denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier().
getChildrenTree() [2/4]
void denoptim.graph.DGraph.getChildrenTree (Vertex vertex, List< Vertex > children, AtomicInteger branchIdGenerator, List< Integer > prevBranchId)
Gets all the children of the current vertex recursively.
All vertices belonging to the children tree are labelled by a property that identifies which branches they belong to (DENOPTIMConstants.GRAPHBRANCHID). This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
branchIdGenerator the generator of branch identifiers
prevBranchId the identifier of the branch holding the given vertex belongs.
Definition at line 3090 of file DGraph.java.
References denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getChildVertices(), and denoptim.constants.DENOPTIMConstants.GRAPHBRANCHID.
getChildrenTree() [3/4]
void denoptim.graph.DGraph.getChildrenTree (Vertex vertex, List< Vertex > children, boolean markBranches)
Gets all the children of the current vertex recursively.
All vertices belonging to the children tree can be labelled by a property that identifies which branches they belong to (DENOPTIMConstants.GRAPHBRANCHID). This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
markBranches true to set the DENOPTIMConstants.GRAPHBRANCHID property to vertices, including the initial one. vertex belongs.
Definition at line 3033 of file DGraph.java.
References denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getChildVertices(), denoptim.constants.DENOPTIMConstants.GRAPHBRANCHID, and denoptim.graph.Vertex.setProperty().
getChildrenTree() [4/4]
void denoptim.graph.DGraph.getChildrenTree (Vertex vertex, List< Vertex > children, int numLayers, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively.
This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
numLayers the maximum number of vertex layers after the seen vertex that we want to consider before stopping. If this value is 2, we will explore three layers: the seed, and two more layers away from it.
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Definition at line 3135 of file DGraph.java.
References denoptim.graph.DGraph.getChildrenTree(), and denoptim.graph.DGraph.getChildVertices().
getChildTreeLimited() [1/3]
void denoptim.graph.DGraph.getChildTreeLimited (Vertex vertex, List< Vertex > children, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively.
This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Definition at line 3257 of file DGraph.java.
References denoptim.graph.DGraph.getChildTreeLimited(), and denoptim.graph.DGraph.getChildVertices().
Referenced by denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getChildTreeLimited(), denoptim.graph.DGraph.getSymmetricSubGraphs(), denoptim.ga.GraphOperations.processPermutationOfEndPoints(), and denoptim.programs.genetweeker.GeneOpsRunner.runXOver().
getChildTreeLimited() [2/3]
void denoptim.graph.DGraph.getChildTreeLimited (Vertex vertex, List< Vertex > children, List< Vertex > limitsInClone, boolean stopBeforeRCVs)
Gets all the children of the current vertex recursively until it finds one of the vertices listed as limit.
This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
limitsInClone the list of vertices where exploration should stop.
stopBeforeRCVs set true to make the exploration of each branch stop before including ring closing vertices.
Definition at line 3321 of file DGraph.java.
References denoptim.graph.DGraph.getChildTreeLimited(), and denoptim.graph.DGraph.getChildVertices().
getChildTreeLimited() [3/3]
void denoptim.graph.DGraph.getChildTreeLimited (Vertex vertex, List< Vertex > children, Set< Vertex > limits)
Gets all the children of the current vertex recursively until it finds one of the vertices listed as limit.
This method does not cross template boundaries, thus all children belong to the same graph.
Parameters
vertex the vertex whose children are to be located
children list containing the references to all the children
limits the list of vertices where exploration should stop.
Definition at line 3289 of file DGraph.java.
References denoptim.graph.DGraph.getChildTreeLimited(), and denoptim.graph.DGraph.getChildVertices().
getChildVertices()
ArrayList< Vertex > denoptim.graph.DGraph.getChildVertices (Vertex vertex)
Parameters
vertex the vertex for which the first level of child vertices need to be found.
Returns
list of child vertices.
Definition at line 2986 of file DGraph.java.
References denoptim.graph.Vertex.getChilddren().
Referenced by denoptim.graph.DGraph.getAPOnLeftVertexID(), denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getChildTreeLimited(), denoptim.graph.DGraph.removeCappingGroupsFromChilds(), and denoptim.graph.DGraph.removeCappingGroupsOn().
getClosableChains()
List< ClosableChain > denoptim.graph.DGraph.getClosableChains ()
Definition at line 940 of file DGraph.java.
References denoptim.graph.DGraph.closableChains.
getDeepestAmongThese()
Vertex denoptim.graph.DGraph.getDeepestAmongThese (List< Vertex > list)
Identify the oldest ancestor (i.e., most great grandparent) in the given collection.
In case of two vertices being at the same level, this returns the first.
Returns
the vertex that has the shortest path to the source.
Definition at line 3352 of file DGraph.java.
References denoptim.graph.DGraph.getParentTree().
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites().
getEdgeAtPosition()
Edge denoptim.graph.DGraph.getEdgeAtPosition (int pos)
Definition at line 2878 of file DGraph.java.
References denoptim.graph.DGraph.gEdges.
Referenced by denoptim.graph.DGraph.getEdgesWithChild(), denoptim.graph.DGraph.getIndexOfEdgesWithChild(), denoptim.graph.AttachmentPointTest.testGetEmbeddedAP(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdge(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeNoMatch(), and denoptim.fragspace.GraphLinkFinderTest.testLinkFromEdgeOneMatch().
getEdgeCount()
int denoptim.graph.DGraph.getEdgeCount ()
Definition at line 2887 of file DGraph.java.
References denoptim.graph.DGraph.gEdges.
Referenced by denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.graph.DGraph.getBondingAPIndex(), denoptim.graph.DGraph.getEdgesWithChild(), denoptim.graph.DGraph.getIndexOfEdgesWithChild(), denoptim.graph.DGraph.sameAs(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), and denoptim.graph.DGraphTest.testRemoveVertex().
getEdgeList()
List< Edge > denoptim.graph.DGraph.getEdgeList ()
Definition at line 992 of file DGraph.java.
References denoptim.graph.DGraph.gEdges.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.gui.GraphViewerPanel.convertDnGraphToGSGraph(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getBondingAPIndex(), denoptim.graph.DGraph.getEdgesWithSrc(), denoptim.graph.DGraph.getEdgesWithTrg(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), and denoptim.graph.DGraph.getSourceVertex().
getEdgesWithChild()
ArrayList< Edge > denoptim.graph.DGraph.getEdgesWithChild (int vid)
Parameters
vid
Returns
the edge whose source vertex is same as vid
Definition at line 3543 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.graph.DGraph.getEdgeCount(), and denoptim.graph.Edge.getSrcVertex().
getEdgesWithSrc()
List< Edge > denoptim.graph.DGraph.getEdgesWithSrc (Vertex v)
Returns the list of edges that depart from the given vertex, i.e., edges where the srcAP is owned by the given vertex.
Parameters
v the given vertex.
Returns
the list of edges departing from the given vertex.
Definition at line 1012 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeList().
Referenced by denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg().
getEdgesWithTrg()
List< Edge > denoptim.graph.DGraph.getEdgesWithTrg (Vertex v)
Returns the list of edges that arrive from the given vertex, i.e., edges where the trgAP is owned by the given vertex.
Parameters
v the given vertex.
Returns
the list of edges arriving to the given vertex.
Definition at line 1033 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeList().
Referenced by denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg().
getEdgeWithParent()
Edge denoptim.graph.DGraph.getEdgeWithParent (long l)
Looks for an edge that points to a vertex with the given vertex id.
Parameters
l
Returns
the edge whose target vertex has ID same as vid, or null
Definition at line 3502 of file DGraph.java.
References denoptim.graph.Vertex.getEdgeToParent(), and denoptim.graph.DGraph.getVertexWithId().
Referenced by denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph().
getEmbeddedGraphInClone()
static DGraph denoptim.graph.DGraph.getEmbeddedGraphInClone (DGraph graphY, DGraph graphB, List< Template > path) static
Searches for a graphs (X) embedded at any level in a graph (Y) by knowing.
the embedding path (p) of another graph A that is embedded in graph B
and that graph Y is a unmodified clone of graph B, which implies that X is a clone of A.
Parameters
graphY where we want to find the analogous of graphA.
graphB the graph graphB where path points to graphA.
path the embedding path of graphA in graphB.
Returns
the graph embedded in graphY, i.e., graphX.
Definition at line 7351 of file DGraph.java.
References denoptim.graph.Template.getInnerGraph(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.DGraph.indexOf().
Referenced by denoptim.ga.XoverSite.projectToClonedGraphs(), and denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone().
getEmbeddingPath()
List< Template > denoptim.graph.DGraph.getEmbeddingPath ()
Find the path that one has to traverse to reach this graph from any template-embedding structure.
In practice, for a graph that is embedded a template jacket T1, which is part of another graph which is itself embedded in a template T2, which is again part of another graph, and so on it returns the references to the embedding templates stating from the outermost to the template that embeds this graph (Outermost reference come first in the resulting list). Instead a graph that is not embedded returns an empty path.
Returns
the path of references that allow to reach this graph from the outermost level of embedding.
Definition at line 7231 of file DGraph.java.
References denoptim.graph.DGraph.getEmbeddingPath(), denoptim.graph.Vertex.getGraphOwner(), and denoptim.graph.DGraph.templateJacket.
Referenced by denoptim.graph.DGraph.getEmbeddingPath(), denoptim.ga.XoverSite.projectToClonedGraphs(), denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone(), and denoptim.graph.DGraphTest.testGetEmbeddingPath().
getFreeRCVertices()
ArrayList< Vertex > denoptim.graph.DGraph.getFreeRCVertices ()
Search for unused ring closing vertices: vertices that contain only a RingClosingAttractor and are not part of any DENOPTIMRing
Returns
the list of unused ring closing vertices
Definition at line 1212 of file DGraph.java.
References denoptim.graph.DGraph.getRCVertices(), and denoptim.graph.DGraph.isVertexInRing().
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.graph.DGraph.getUsedRCVertices(), and denoptim.graph.rings.RingSizeManager.initialize().
getGraphId()
int denoptim.graph.DGraph.getGraphId ()
Definition at line 271 of file DGraph.java.
References denoptim.graph.DGraph.graphId.
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.graph.DGraph.addVertex(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.graph.DGraph.editGraph(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.utils.GraphUtils.getLabel(), denoptim.combinatorial.GraphBuildingTask.GraphBuildingTask(), denoptim.ga.EAUtils.outputPopulationDetails(), and denoptim.ga.GraphOperations.performMutation().
getHeavyAtomsCount()
int denoptim.graph.DGraph.getHeavyAtomsCount ()
Calculate the number of atoms from the graph representation.
Returns
number of heavy atoms in the molecule
Definition at line 4182 of file DGraph.java.
References denoptim.graph.DGraph.getVertexList().
Referenced by denoptim.graph.Template.getHeavyAtomsCount(), and denoptim.ga.EAUtils.getMolSizeProbability().
getIndexOfEdgesWithChild()
ArrayList< Integer > denoptim.graph.DGraph.getIndexOfEdgesWithChild (int vid)
Parameters
vid
Returns
the indices of all edges whose source vertex is same as vid
Definition at line 3520 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.graph.DGraph.getEdgeCount(), and denoptim.graph.Edge.getSrcVertex().
getInterfaceAPs()
List< AttachmentPoint > denoptim.graph.DGraph.getInterfaceAPs (List< Vertex > subGraphB)
Searches for all AttachmentPoints that represent the interface between a subgraph, identified by the given list of vertices, and any other vertex, i.e., either belonging to the same graph but not to the same subgraph, or belonging to an outer embedding level.
Parameters
subGraphB list of vertices belonging to the subgraph.
Returns
the list of attachment points at the interface of the subgraph.
Definition at line 7379 of file DGraph.java.
Referenced by denoptim.fragspace.APMapFinder.APMapFinder(), denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.graph.DGraphTest.testGetInterfaceAPs(), and denoptim.ga.XoverSite.XoverSite().
getLevel()
int denoptim.graph.DGraph.getLevel (Vertex v)
Calculates the level of a vertex in this graph.
Parameters
v the vertex for which we want the level.
Returns
the level, i.e., an integer that is -1 for the seed vertex of this graph and increases by one unit per each edge that has to be traversed to reach the vertex given as argument via a direct path.
Definition at line 5555 of file DGraph.java.
References denoptim.graph.DGraph.getParentTree().
Referenced by denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.DGraph.findVertices(), denoptim.graph.DGraph.removeChainUpToBranching(), and denoptim.graph.DGraphTest.testGetLevel().
getLocalMsg()
String denoptim.graph.DGraph.getLocalMsg ()
Definition at line 287 of file DGraph.java.
References denoptim.graph.DGraph.localMsg.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), and denoptim.ga.GraphOperations.performMutation().
getMaxVertexId()
long denoptim.graph.DGraph.getMaxVertexId ()
Returns
the maximum value of vertex Id found in this graph.
Definition at line 3563 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.GraphOperations.addFusedRing(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraph.removeVertexAndWeld(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), and denoptim.ga.EAUtils.setVertexCounterValue().
getMutableSites() [1/2]
List< Vertex > denoptim.graph.DGraph.getMutableSites ()
A list of mutation sites from within this graph.
This method does not consider MutationType#ADDFUSEDRING sited because their identification is heavily dependent on settings that are beyond the DGraph class and pertain the RingClosureParameters.
Returns
the list of vertices that allow any mutation type.
Definition at line 6858 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.EAUtils.buildGraph(), and denoptim.graph.DGraphTest.testGetMutationSites().
getMutableSites() [2/2]
List< Vertex > denoptim.graph.DGraph.getMutableSites (List< MutationType > ignoredTypes)
A list of mutation sites from within this graph.
This method does not consider MutationType#ADDFUSEDRING sited because their identification is heavily dependent on settings that are beyond the DGraph class and pertain the RingClosureParameters.
Parameters
ignoredTypes a collection of mutation types to ignore. Vertices that allow only ignored types of mutation will not be considered mutation sites.
Returns
the list of vertices that allow any non-ignored mutation type.
Definition at line 6882 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
getOutermostGraphOwner()
DGraph denoptim.graph.DGraph.getOutermostGraphOwner ()
Returns
the outermost graph object that can be reached from this possibly embedded graph.
Definition at line 7209 of file DGraph.java.
References denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.DGraph.getOutermostGraphOwner(), and denoptim.graph.DGraph.templateJacket.
Referenced by denoptim.ga.EAUtils.buildCandidatesByXOver(), and denoptim.graph.DGraph.getOutermostGraphOwner().
getParent()
Vertex denoptim.graph.DGraph.getParent (Vertex v)
Definition at line 3397 of file DGraph.java.
References denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.graph.Edge.getSrcAP().
Referenced by denoptim.graph.DGraph.getParentTree().
getParentTree()
void denoptim.graph.DGraph.getParentTree (Vertex vertex, List< Vertex > parentTree)
Traverse the graph until it identifies the source of the directed path reachable from the given vertex recursively.
Parameters
vertex the child vertex from which we start traversing the graph.
parentTree list containing the references to all the parents recursively visited so far.
Definition at line 3378 of file DGraph.java.
References denoptim.graph.DGraph.getParent(), and denoptim.graph.DGraph.getParentTree().
Referenced by denoptim.graph.DGraph.getDeepestAmongThese(), denoptim.graph.DGraph.getLevel(), denoptim.graph.DGraph.getParentTree(), denoptim.graph.DGraph.getSourceVertex(), and denoptim.graph.rings.PathSubGraph.PathSubGraph().
getRCVertices()
ArrayList< Vertex > denoptim.graph.DGraph.getRCVertices ()
Search for ring closing vertices: vertices that contain only a RingClosingAttractor
Returns
the list of ring closing vertices
Definition at line 1190 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.checkConsistency(), denoptim.graph.DGraph.getFreeRCVertices(), denoptim.graph.DGraph.getUsedRCVertices(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability(), denoptim.graph.rings.RingSizeManagerTest.testEvaluateRCVPair(), and denoptim.graph.DGraphTest.testRemoveUnusedRCVs().
getRingCount()
int denoptim.graph.DGraph.getRingCount ()
Definition at line 2894 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
Referenced by denoptim.graph.DGraph.sameAs(), denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.GraphOperationsTest.testAddRing(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem(), denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testReplaceSubGraph(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getRings()
List< Ring > denoptim.graph.DGraph.getRings ()
Definition at line 999 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.gui.GraphViewerPanel.convertDnGraphToGSGraph(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.DGraph.sameAs(), denoptim.graph.TemplateTest.testClone(), denoptim.ga.GraphOperationsTest.testExtractPattern_returnsEmptyListIfNoRings(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getRingsInvolvingVertex() [1/2]
ArrayList< Ring > denoptim.graph.DGraph.getRingsInvolvingVertex (Vertex v)
Returns the list of rings that include the given vertex in their fundamental cycle.
Parameters
v the vertex to search for.
Returns
the list of rings of an empty list.
Definition at line 1054 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), and denoptim.graph.DGraph.sameAs().
getRingsInvolvingVertex() [2/2]
ArrayList< Ring > denoptim.graph.DGraph.getRingsInvolvingVertex (Vertex[] vs)
Returns the list of rings that include the given list of vertices in their fundamental cycle.
Parameters
vs the collection of vertices to search for.
Returns
the list of rings of an empty list.
Definition at line 1075 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
getRingsInvolvingVertexID()
ArrayList< Ring > denoptim.graph.DGraph.getRingsInvolvingVertexID (int vid)
Definition at line 1099 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
getSelectedMutableSites()
List< Vertex > denoptim.graph.DGraph.getSelectedMutableSites (MutationType requestedType)
A list of mutation sites from within this graph.
This method does not consider MutationType#ADDFUSEDRING sited because their identification is heavily dependent on settings that are beyond the DGraph class and pertain the RingClosureParameters.
Parameters
requestedTypes a collection of mutation types to seek for. Vertices that do not allow only one of types of mutation types will not be considered mutation sites.
Returns
the list of vertices that allow any specified mutation type.
Definition at line 6905 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.programs.genetweeker.GeneOpsRunner.runMutation().
getSourceVertex()
Vertex denoptim.graph.DGraph.getSourceVertex ()
Identifies and return the vertex from which the spanning tree originates.
This is typically the first vertex in the list, but it is possible to programmatically build graphs that do not follow this convention. Therefore, here we test if the first vertex is a seed (i.e., it only has departing edges) and, if not, we search for the closest seed. WARNING: the graph is assumed to be an healthy spanning tree, in that it has only one seed that is reachable from any vertex by a inverse directed path. The result null for disconnected graphs or otherwise unhealthy spanning trees.
Returns
the seed/root of the spanning tree
Definition at line 968 of file DGraph.java.
References denoptim.graph.DGraph.getEdgeList(), denoptim.graph.DGraph.getParentTree(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.fixEdgeDirections(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.reorderVertexList(), denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem(), denoptim.graph.DGraphTest.testGetSourceVertex(), and denoptim.graph.DGraphTest.testReplaceSubGraph().
getSubgraphAPs()
List< AttachmentPoint > denoptim.graph.DGraph.getSubgraphAPs (List< Vertex > subGraphB)
Searches for all AttachmentPoints that are owned by vertices in a subgraph but either available or used by vertices that do not belong to the subgraph.
Parameters
subGraphB list of vertices belonging to the subgraph.
Returns
the list of attachment points originating from the subgraph.
Definition at line 7414 of file DGraph.java.
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.ga.GraphOperations.performCrossover(), and denoptim.graph.DGraphTest.testGetSubgraphAPs().
getSymmetricSetCount()
int denoptim.graph.DGraph.getSymmetricSetCount ()
Returns the number of symmetric sets of vertices.
Returns
the number of symmetric sets of vertices
Definition at line 321 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.sameAs(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraphTest.testDetectSymVertexSets(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_symmetry(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testReplaceSubGraph(), and denoptim.graph.DGraphTest.testReplaceVertex().
getSymmetricSubGraphs()
List< List< Vertex > > denoptim.graph.DGraph.getSymmetricSubGraphs (List< Vertex > subGrpVrtxs) throws DENOPTIMException
We assume that the subgraph is a continuously connected, directed graph.
By contract, the source of the symmetric subgraph's spanning tree is always the first vertex in each returned list. Also, note that symmetry does not pertain capping groups, so capping groups are not expected to be among the vertices in the given list and will not be present in the resulting subgraphs.
Parameters
subGrpVrtxs
Returns
a collection of subgraphs, each represented by a list of vertices belonging to it.
Exceptions
DENOPTIMException if capping groups are present in the list.
Definition at line 2045 of file DGraph.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraph.getChildTreeLimited(), and denoptim.graph.DGraph.getSymVerticesForVertex().
Referenced by denoptim.graph.DGraph.replaceSubGraph(), and denoptim.graph.DGraphTest.testGetSymmetricSubGraphs().
getSymSetForVertex()
SymmetricVertexes denoptim.graph.DGraph.getSymSetForVertex (Vertex v)
Returns the set of vertexes symmetric to the given one.
Parameters
v the vertex for which we seek the symmetric vertexes.
Returns
either the collector of vertexes symmetric to the given one, which also includes the given one, or an empty collector.
Definition at line 861 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.ga.GraphOperations.deleteChain(), denoptim.ga.GraphOperations.deleteFragment(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.graph.DGraph.removeBranchStartingAt(), denoptim.graph.DGraph.sameAs(), denoptim.graph.DGraphTest.testDetectSymVertexSets(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_symmetry(), and denoptim.graph.DGraphTest.testReplaceVertex().
getSymSetsIterator()
Iterator< SymmetricVertexes > denoptim.graph.DGraph.getSymSetsIterator ()
Get an iterator for the sets of symmetrically related vertices.
Definition at line 332 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.DGraph.reassignSymmetricLabels(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeSymmetryRedundance(), denoptim.graph.DGraph.sameAs(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), and denoptim.graph.DGraphTest.testReplaceVertex().
getSymVerticesForVertex()
List< Vertex > denoptim.graph.DGraph.getSymVerticesForVertex (Vertex v)
Parameters
v the vertex for which we want the list of symmetric vertices.
Returns
a list that includes v but can be empty.
Definition at line 343 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.DGraph.getSymmetricSubGraphs(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraph.removeVertexAndWeld(), denoptim.graph.DGraph.replaceVertex(), and denoptim.ga.GraphOperationsTest.testExtendGraph().
getTemplateJacket()
Template denoptim.graph.DGraph.getTemplateJacket ()
Returns
the template that contains this graph or null.
Definition at line 7198 of file DGraph.java.
References denoptim.graph.DGraph.templateJacket.
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), and denoptim.ga.GraphOperations.performMutation().
getUniqueAPIndex()
int denoptim.graph.DGraph.getUniqueAPIndex () protected
Definition at line 4280 of file DGraph.java.
References denoptim.graph.DGraph.apCounter.
Referenced by denoptim.graph.Vertex.getUniqueAPIndex().
getUsedRCVertices()
ArrayList< Vertex > denoptim.graph.DGraph.getUsedRCVertices ()
Search for used ring closing vertices: vertices that contain only a RingClosingAttractor and are part of a DENOPTIMRing.
Returns
the list of ring closing vertices
Definition at line 1235 of file DGraph.java.
References denoptim.graph.DGraph.getFreeRCVertices(), and denoptim.graph.DGraph.getRCVertices().
Referenced by denoptim.ga.EAUtils.getCrowdedness().
getVertexAtPosition()
Vertex denoptim.graph.DGraph.getVertexAtPosition (int pos)
Returns the vertex that is in the given position of the list of vertices belonging to this graph.
Parameters
pos the position in the list.
Returns
the vertex in the given position.
Definition at line 2743 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getBranchIdOfVertexAtPosition(), denoptim.graph.DGraph.getEmbeddedGraphInClone(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.utils.GraphUtils.getLabel(), denoptim.graph.DGraph.getSourceVertex(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.ga.EAUtilsTest.prepare(), denoptim.ga.XoverSite.projectToClonedGraphs(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.graph.DGraph.sameAs(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_Free(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FreeBackwards(), denoptim.ga.EAUtilsTest.testBuildGraphFromTemplateScaffold(), denoptim.ga.PopulationTest.testClone(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), denoptim.ga.EAUtilsTest.testCrowdingProbability(), denoptim.graph.DGraphTest.testDetectSymVertexSets(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.graph.DGraphTest.testExtractSubgraphFromCollection(), denoptim.graph.DGraphTest.testFindVertex(), denoptim.graph.DGraphTest.testGetChildrenTree(), denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier(), denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg(), denoptim.graph.DGraphTest.testGetInterfaceAPs(), denoptim.utils.GraphConversionToolTest.testGetJGraphKernelFromGraph(), denoptim.graph.DGraphTest.testGetLevel(), denoptim.graph.DGraphTest.testGetSourceVertex(), denoptim.graph.DGraphTest.testGetSubgraphAPs(), denoptim.graph.DGraphTest.testGetSymmetricSubGraphs(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.fragspace.GraphLinkFinderTest.testLinkFromVertex(), denoptim.ga.GraphOperationsTest.testLocateCompatibleXOverPoints(), denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph(), denoptim.ga.XoverSiteTest.testProjectToClonedGraphs(), denoptim.graph.DGraphTest.testReplaceSubGraph(), denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.graph.DGraphTest.testReplaceVertex_inRing(), denoptim.graph.TemplateTest.testSameAPClass(), denoptim.graph.DGraphTest.testSymmetricSetLabels(), and denoptim.ga.PopulationTest.testXOverCompatibility().
getVertexCount()
int denoptim.graph.DGraph.getVertexCount ()
Definition at line 2901 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.EAUtils.buildGraph(), denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.ga.GraphOperations.deleteChain(), denoptim.ga.GraphOperations.deleteFragment(), denoptim.graph.Vertex.getMutationTypes(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.graph.DGraph.sameAs(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.TemplateTest.testClone(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), denoptim.ga.GraphOperationsTest.testExtendGraph(), denoptim.ga.GraphOperationsTest.testExtractPattern_singleRingSystem(), denoptim.graph.DGraphTest.testExtractSubgraphFromCollection(), denoptim.graph.DGraphTest.testGetLevel(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_cappingGroups(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_Symmetry(), denoptim.graph.DGraphTest.testRemoveCapping(), denoptim.graph.DGraphTest.testRemoveUnusedRCVs(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate(), and denoptim.ga.PopulationTest.testXOverCompatibility().
getVertexList()
List< Vertex > denoptim.graph.DGraph.getVertexList ()
Definition at line 947 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.graph.DGraph.containsAtoms(), denoptim.gui.GraphViewerPanel.convertDnGraphToGSGraph(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.findVertices(), denoptim.ga.EAUtils.foundForbiddenEnd(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.ga.GraphOperationsTest.getExpectedSubgraphs(), denoptim.graph.DGraph.getHeavyAtomsCount(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.DGraph.graphNeedsCappingGroups(), denoptim.graph.DGraph.hasForbiddenEnd(), denoptim.graph.DGraph.hasScaffoldTypeVertex(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.ga.EAUtils.selectNonScaffoldNonCapVertex(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.ga.GraphOperationsTest.testAddFusedRings(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure(), denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), denoptim.graph.DGraphTest.testFindVertex(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_linearities(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_ScaffoldingPolicy(), denoptim.graph.DGraphTest.testReplaceVertex(), and denoptim.graph.DGraphTest.testSymmetricSetLabels().
getVertexWithId()
Vertex denoptim.graph.DGraph.getVertexWithId (long vid)
Searches for a vertex with the given identifier.
Parameters
vid the identifier
Returns
the first vertex found with such identifier, or null if no such identifier is found.
Definition at line 2811 of file DGraph.java.
References denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.indexOfVertexWithID().
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.DGraph.clone(), denoptim.ga.GraphOperations.deleteChain(), denoptim.ga.GraphOperations.deleteFragment(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.DGraph.getAPOnLeftVertexID(), denoptim.graph.DGraph.getEdgeWithParent(), denoptim.programs.genetweeker.GeneOpsRunner.getEmbeddedVertex(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.ga.GraphOperations.performCrossover(), denoptim.ga.GraphOperations.rebuildBranch(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeOrphanBranchStartingAt(), denoptim.graph.DGraph.removeSymmetryRedundantIds(), denoptim.graph.DGraphTest.testExtractSubgraphFromCollection(), and denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_symmetry().
graphNeedsCappingGroups()
boolean denoptim.graph.DGraph.graphNeedsCappingGroups (FragmentSpace fragSpace)
Checks the graph for unused APs that need to be capped.
Returns
true if the graph has at least one AP that needs to be capped
Definition at line 4293 of file DGraph.java.
References denoptim.fragspace.FragmentSpace.getAPClassOfCappingVertex(), and denoptim.graph.DGraph.getVertexList().
Referenced by denoptim.combinatorial.GraphBuildingTask.call().
hasForbiddenEnd()
boolean denoptim.graph.DGraph.hasForbiddenEnd (FragmentSpaceParameters fsSettings)
Check if there are forbidden ends: free attachment points that are not suitable for capping and not allowed to stay unused.
Returns
true if a forbidden end is found
Definition at line 5915 of file DGraph.java.
References denoptim.fragspace.FragmentSpace.getForbiddenEndList(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.DGraph.getVertexList(), and denoptim.graph.APClass.toString().
Referenced by denoptim.graph.DGraph.checkConsistency().
hasOrEmbedsRings()
boolean denoptim.graph.DGraph.hasOrEmbedsRings ()
Check for rings in this graph and in any graph that is embedded at any level in any vertex of this graph.
Does not consider any graph that embeds this graph.
Returns
true if there are rings in this graph or in embedded graphs.
Definition at line 1134 of file DGraph.java.
References denoptim.graph.Template.getInnerGraph(), denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.hasOrEmbedsRings().
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), and denoptim.graph.DGraph.hasOrEmbedsRings().
hasRings()
boolean denoptim.graph.DGraph.hasRings ()
Check for rings in this graph.
Does not cross the template-barrier, i.e., ignores any ring that is embedded at any level in any vertex of this graph, neither in any graph that embeds this graph.
Returns
true if there are rings in this graph.
Definition at line 1120 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
hasScaffoldTypeVertex()
boolean denoptim.graph.DGraph.hasScaffoldTypeVertex ()
Checks if this graph contains a scaffold vertex.
Returns
true if there is a scaffold vertex.
Definition at line 7175 of file DGraph.java.
References denoptim.graph.DGraph.getVertexList(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraph.embedPatternsInTemplates().
hasSymmetricAP()
boolean denoptim.graph.DGraph.hasSymmetricAP ()
Definition at line 294 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.fragspace.FragsCombinationIterator.next().
hasSymmetryInvolvingVertex()
boolean denoptim.graph.DGraph.hasSymmetryInvolvingVertex (Vertex v)
Definition at line 301 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.ga.GraphOperations.deleteChain(), denoptim.ga.GraphOperations.deleteFragment(), denoptim.ga.GraphOperations.extendGraph(), denoptim.ga.GraphOperations.rebuildBranch(), and denoptim.graph.DGraph.removeBranchStartingAt().
indexOf()
int denoptim.graph.DGraph.indexOf (Vertex v)
Returns the index of a vertex in the list of vertices of this graph.
Parameters
v the vertex to search
Returns
the index of the vertex in the list of vertices.
Definition at line 2798 of file DGraph.java.
References denoptim.graph.DGraph.gVertices.
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getEmbeddedGraphInClone(), denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.ga.GraphOperations.performMutation(), and denoptim.ga.GraphOperationsTest.testLocateCompatibleXOverPoints().
indexOfVertexWithID()
int denoptim.graph.DGraph.indexOfVertexWithID (long vid)
Returns the position of the first vertex that has the given ID.
Parameters
vid the vertedID of the vertex we are looking for.
Returns
the index in the list of vertices.
Definition at line 2827 of file DGraph.java.
References denoptim.graph.Vertex.getVertexId(), and denoptim.graph.DGraph.gVertices.
Referenced by denoptim.graph.DGraph.getVertexWithId().
insertSingleVertex()
boolean denoptim.graph.DGraph.insertSingleVertex (Edge edge, Vertex newLink, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap) throws DENOPTIMException
Inserts a given vertex in between two vertices connected by the given edge.
This method reproduces the change of vertex on all symmetric sites.
Parameters
edge the edge where to insert the new vertex.
newLink the new vertex to be inserted.
apMap the mapping of attachment points needed to install the new vertex and connect it to the rest of the graph. The syntax of this map must be:
keys: the APs originally involved in making the edge given as parameter,
values: the APs in the new vertex.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException
Definition at line 2669 of file DGraph.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.DGraph.gEdges, denoptim.graph.AttachmentPoint.getBondType(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.isVertexInRing(), denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, denoptim.graph.DGraph.removeEdge(), and denoptim.graph.DGraph.templateJacket.
Referenced by denoptim.graph.DGraph.insertVertex().
insertVertex()
boolean denoptim.graph.DGraph.insertVertex (Edge edge, int bbId, BBType bbt, LinkedHashMap< AttachmentPoint, Integer > apMap, FragmentSpace fragSpace) throws DENOPTIMException
Inserts a given vertex in between two vertices connected by the given edge.
This method reproduces the change of vertex on all symmetric sites.
Parameters
edge the edge where to insert the new vertex.
bbId the building block Id of the building blocks that will be inserted.
bbt the type of building block to be inserted.
apMap the mapping of attachment points needed to install the new building block and connect it to the rest of the graph. The syntax of this map must be:
keys: the APs originally involved in making the edge given as parameter,
values: the 0-based index of the AP in the new building block that will be inserted.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException
Definition at line 2589 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.utils.GraphUtils.ensureVertexIDConsistency(), denoptim.graph.DGraph.gEdges, denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.Edge.getSrcAP(), denoptim.graph.DGraph.getSymVerticesForVertex(), denoptim.graph.Edge.getTrgAP(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.DGraph.insertSingleVertex(), and denoptim.graph.Vertex.newVertexFromLibrary().
Referenced by denoptim.ga.GraphOperations.extendLink().
isIsomorphicTo()
boolean denoptim.graph.DGraph.isIsomorphicTo (DGraph other)
Checks if this graph is "DENOPTIM-isomorphic" to the other one given.
"DENOPTIM-isomorphic" is a DENOPTIM-specific definition of
graph isomorphism that differs from the most common meaning of isomorphism in graph theory. In general, graph are considered undirected when evaluating DENOPTIM-isomorphism. Next, since a graph is effectively a spanning tree (ST_i={{vertices}, {acyclic edges}}) with a set of fundamental cycles (FC_i={C_1, C_2,...C_n}), any graph G={ST_i,FC_i} that contains one or more cycles can be represented in multiple ways, G={ST_j,FC_j} or G={ST_k,FC_k}, that differ by the position of the chord/s and by the corresponding pair of ring-closing vertices between which each chord is defined. The DENOPTIM-isomorphism for two graph G1 and G2 is given by the common graph theory isomorphism between two undirected graphs U1 and U2 build respectively from G1 and G2 with the convention defined in GraphConversionTool#getJGraphFromGraph(DGraph). Finally,
vertices are compared excluding their vertex ID, i.e., Vertex#sameAs()
edges are considered undirected and compared considering the BondType and the identity of the attachment points connected thereby. This latter point has an important implication: two apparently equal graphs (same vertices that are connected to each other forming the same vertex-chains) can be non-isomorphic when the APs used to connect two vertices are not the same. Chemically, this means the stereochemistry around one or both vertices, is different in the two graphs. Therefore two otherwise equal-looking graphs can very well be, de facto, not isomorphic.
This method makes use of the Vento-Foggia VF2 algorithm (see DOI:10.1109/TPAMI.2004.75) as provided by JGraphT library in VF2GraphIsomorphismInspector.
Detection of isomorphism can be very slow for pathological cases and for graphs with large symmetric systems! TODO: consider adding a runtime limit or a further simplification/speed-up exploiting symmetry. The symmetry, however, does not help detecting isomorphism between a graph with symmetric branches and its isomorphic analog that is fully asymmetric.
Parameters
other the graph to be compared with this.
Returns
true is this graph is isomorphic to the other.
Definition at line 3682 of file DGraph.java.
References denoptim.graph.simplified.UndirectedEdge.compare(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getGraphOwner(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.jGraph, and denoptim.graph.Vertex.sameAs().
Referenced by denoptim.ga.GraphOperations.locateCompatibleXOverPoints(), denoptim.ga.GraphOperations.processPermutationOfEndPoints(), denoptim.programs.graphlisthandler.GraphListsHandler.runProgram(), denoptim.programs.isomorphism.Isomorphism.runProgram(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure(), denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.DGraphTest.testReplaceSubGraph(), and denoptim.graph.DGraphTest.testReplaceVertex_inRing().
isIsostructuralTo()
boolean denoptim.graph.DGraph.isIsostructuralTo (DGraph other)
Checks if this graph is "DENOPTIM-isostructural" to the other one given.
"DENOPTIM-isostructural" means that the two graphs are isomorfic when:
the comparison of the vertices considers any implementation of Vertex equals to itself unless two vertices differ by the return value of Vertex#isRCV(),
the comparison of the vertices considers only the type of bond the edge corresponds to (if any),
free AttachmentPoints that are marked as required in either graph are reflected in the other.
Parameters
other
Returns
Definition at line 3809 of file DGraph.java.
References denoptim.graph.simplified.Node.compare(), denoptim.graph.simplified.NodeConnection.compare(), denoptim.graph.simplified.Node.getDNPVertex(), denoptim.graph.Vertex.getGraphOwner(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.jGraphKernel, and denoptim.graph.simplified.Node.REFTOVERTEXKERNEL.
Referenced by denoptim.ga.GraphOperations.checkAndAddXoverSites(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
isReversible()
boolean denoptim.graph.DGraph.isReversible (FragmentSpace fragSpace)
Checks is the every edge in the graph can be defined in the opposite direction according to the APClass compatibility rules.
Note that the reversions operation on a branched subgraph generates a graph with multiple source vertices, which is not allowed. Yet, the reversion is formally possible.
Returns
true if the all edges can be reverted and retain consistency with APClass compatibility rules.
Definition at line 7320 of file DGraph.java.
References denoptim.graph.DGraph.gEdges.
isVertexIDInRing()
boolean denoptim.graph.DGraph.isVertexIDInRing (int vid)
Definition at line 1152 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
isVertexInRing()
boolean denoptim.graph.DGraph.isVertexInRing (Vertex v)
Definition at line 1168 of file DGraph.java.
References denoptim.graph.DGraph.gRings.
Referenced by denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.graph.DGraph.getFreeRCVertices(), denoptim.utils.GraphConversionTool.getJGraphFromGraph(), denoptim.utils.GraphConversionTool.getJGraphKernelFromGraph(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeCappingGroupsOn(), and denoptim.graph.DGraph.removeVertex().
makeAllGraphsWithDifferentRingSets()
ArrayList< DGraph > denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets (RunTimeParameters settings) throws DENOPTIMException
Evaluates the possibility of closing rings in this graph and generates all alternative graphs resulting by different combinations of rings.
Returns
true unless no ring can be set up even if required
Exceptions
denoptim.exception.DENOPTIMException
Definition at line 5818 of file DGraph.java.
References denoptim.graph.DGraph.addRing(), denoptim.graph.Ring.addVertex(), denoptim.graph.rings.RingClosureParameters.allowRingClosures(), denoptim.graph.rings.RingClosureParameters.buildChelatesMode, denoptim.graph.rings.CyclicGraphHandler.checkChelatesGraph(), denoptim.graph.DGraph.clone(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.programs.RunTimeParameters.ParametersType.FS_PARAMS, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.programs.RunTimeParameters.getParameters(), denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings(), denoptim.fragspace.FragmentSpaceParameters.getRotSpaceDefFile(), denoptim.utils.GraphUtils.getUniqueGraphIndex(), denoptim.graph.DGraph.getVertexWithId(), denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.graph.DGraph.renumberVerticesGetMap(), denoptim.molecularmodeling.ThreeDimTreeBuilder.setAlignBBsIn3D(), denoptim.graph.Ring.setBondType(), denoptim.graph.DGraph.setGraphId(), denoptim.graph.DGraph.setRings(), and denoptim.fragspace.FragmentSpace.useAPclassBasedApproach().
Referenced by denoptim.combinatorial.GraphBuildingTask.call().
reassignSymmetricLabels()
void denoptim.graph.DGraph.reassignSymmetricLabels () protected
Marks the vertices of this graph with a string that is consistent for all vertices that belong to symmetric sets.
All vertices will get a label, whether they belong to a symmetric set or not. The label is places in the vertex property DENOPTIMConstants#VRTSYMMSETID. Any previous labeling is ignored and overwritten.
Definition at line 1796 of file DGraph.java.
References denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.gVertices, and denoptim.constants.DENOPTIMConstants.VRTSYMMSETID.
Referenced by denoptim.graph.DGraph.replaceVertex(), denoptim.graph.DGraphTest.testReplaceSubGraph(), and denoptim.graph.DGraphTest.testSymmetricSetLabels().
removeBranchStartingAt() [1/2]
boolean denoptim.graph.DGraph.removeBranchStartingAt (Vertex v) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
Updates symmetry accordingly, but does not remove symmetric branches.
Parameters
vid the vertexID of the root of the branch. We'll remove also this vertex.
Returns
true if operation is successful
Exceptions
DENOPTIMException
Definition at line 5050 of file DGraph.java.
References denoptim.graph.DGraph.removeEdge(), and denoptim.graph.DGraph.removeOrphanBranchStartingAt().
removeBranchStartingAt() [2/2]
boolean denoptim.graph.DGraph.removeBranchStartingAt (Vertex v, boolean symmetry) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
Parameters
vid the vertexID of the root of the branch. We'll remove also this vertex.
symmetry use true to enforce deletion of all symmetric vertices.
Returns
true if operation is successful.
Exceptions
DENOPTIMException
Definition at line 5017 of file DGraph.java.
References denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.hasSymmetryInvolvingVertex(), and denoptim.graph.DGraph.removeBranchStartingAt().
Referenced by denoptim.ga.GraphOperations.deleteFragment(), denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.removeBranchStartingAt(), and denoptim.graph.Template.removeProjectionOfInnerAP().
removeCappingGroups() [1/2]
void denoptim.graph.DGraph.removeCappingGroups ()
Remove all capping groups on this graph.
Definition at line 4385 of file DGraph.java.
References denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.removeCappingGroups().
Referenced by denoptim.graph.DGraph.removeCappingGroups(), and denoptim.graph.DGraph.removeCappingGroupsFromChilds().
removeCappingGroups() [2/2]
void denoptim.graph.DGraph.removeCappingGroups (List< Vertex > lstVerts)
Remove capping groups that belong to this graph and are in the given list.
Parameters
lstVerts the list of vertices to analyze.
Definition at line 4343 of file DGraph.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.getVertexWithId(), denoptim.graph.DGraph.isVertexInRing(), and denoptim.graph.DGraph.removeVertex().
Referenced by denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol_cappingGroups(), and denoptim.graph.DGraphTest.testRemoveCapping().
removeCappingGroupsFromChilds()
void denoptim.graph.DGraph.removeCappingGroupsFromChilds (List< Vertex > lstVerts)
Definition at line 4371 of file DGraph.java.
References denoptim.graph.DGraph.getChildVertices(), and denoptim.graph.DGraph.removeCappingGroups().
Referenced by denoptim.graph.DGraph.replaceSubGraph().
removeCappingGroupsOn()
void denoptim.graph.DGraph.removeCappingGroupsOn (Vertex vertex)
Remove capping groups on the given vertex of this graph.
Definition at line 4313 of file DGraph.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraph.getChildVertices(), denoptim.graph.DGraph.isVertexInRing(), and denoptim.graph.DGraph.removeVertex().
Referenced by denoptim.graph.DGraphTest.testRemoveCapping().
removeChainUpToBranching()
boolean denoptim.graph.DGraph.removeChainUpToBranching (Vertex v, FragmentSpace fragSpace) throws DENOPTIMException
Mutates the graph by removing the chain where a given vertex is located up to the first branching (i.e., to non-capping group) on either side.
The graph is updated accordingly. In particular, the direction of edges in the surviving graph and the definition of fundamental cycles are changed to reflect the change of spanning tree.
Parameters
v the vertex from which we start detecting a chain
Returns
true if successful.
Exceptions
DENOPTIMException is any assumption on the healthy structure of this graph is not verified.
Definition at line 5107 of file DGraph.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.graph.DGraph.addRing(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.Template.getAttachmentPoints(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.DGraph.getAvailableAPs(), denoptim.graph.Edge.getBondType(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.getCappedAPCountThroughout(), denoptim.graph.Vertex.getChilddren(), denoptim.graph.Vertex.getChildrenThroughout(), denoptim.graph.Vertex.getEdgeToParent(), denoptim.graph.Vertex.getEdgeWith(), denoptim.graph.Vertex.getFreeAPCountThroughout(), denoptim.graph.Template.getInnerAPFromOuterAP(), denoptim.graph.DGraph.getLevel(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Ring.getPositionOf(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.Ring.getSize(), denoptim.graph.Edge.getSrcAP(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.Ring.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.APClass.isCPMapCompatibleWith(), denoptim.graph.DGraph.removeEdge(), denoptim.graph.Template.removeProjectionOfInnerAP(), denoptim.graph.DGraph.removeRing(), denoptim.graph.DGraph.removeSymmetrySet(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.DGraph.templateJacket, and denoptim.io.DenoptimIO.writeGraphToJSON().
Referenced by denoptim.ga.GraphOperations.deleteChain().
removeEdge()
void denoptim.graph.DGraph.removeEdge (Edge edge)
Removes an edge and update the free valences of the attachment points that were originally involved in this edge.
Parameters
edge
Definition at line 2849 of file DGraph.java.
References denoptim.graph.DGraph.gEdges, denoptim.graph.Edge.getSrcAP(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, and denoptim.graph.AttachmentPoint.setUser().
Referenced by denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.removeBranchStartingAt(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.replaceSingleSubGraph(), and denoptim.graph.EdgeTest.testConnectionDeconnectionLoop().
removeOrphanBranchStartingAt()
boolean denoptim.graph.DGraph.removeOrphanBranchStartingAt (Vertex v) throws DENOPTIMException
Deletes the branch, i.e., the specified vertex and its children.
This method does not cross template boundaries, thus all children belong to the same graph. Symmetry relations are updated accordingly.
Parameters
vid the vertexID of the root of the branch. We'll remove also this vertex.
allowOrphan use true to allow removal of branches starting with a vertex that has no edge to a parent.
Returns
true if operation is successful
Exceptions
DENOPTIMException
Definition at line 5076 of file DGraph.java.
References denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getVertexWithId(), and denoptim.graph.DGraph.removeVertex().
Referenced by denoptim.graph.DGraph.removeBranchStartingAt(), and denoptim.graph.DGraph.removeSingleVertexAndWeld().
removeRing()
void denoptim.graph.DGraph.removeRing (Ring ring)
Definition at line 2866 of file DGraph.java.
References denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), and denoptim.ga.GraphOperationsTest.testExtractPattern_returnsEmptyListIfNoRings().
removeSingleVertexAndWeld()
boolean denoptim.graph.DGraph.removeSingleVertexAndWeld (Vertex vertex, FragmentSpace fragSpace) throws DENOPTIMException
Remove a given vertex belonging to this graph and re-connects the resulting graph branches as much as possible.
Parameters
vertex the vertex currently belonging to this graph and to be replaced.
Returns
true if the operation is successful.
Exceptions
DENOPTIMException
Definition at line 1475 of file DGraph.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.APClass.getBondType(), denoptim.graph.Vertex.getFreeAPThroughout(), denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.AttachmentPoint.getLinkedAPThroughout(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.DGraph.getSourceVertex(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, denoptim.graph.DGraph.removeEdge(), denoptim.graph.DGraph.removeOrphanBranchStartingAt(), denoptim.graph.Template.removeProjectionOfInnerAP(), denoptim.graph.DGraph.removeRing(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.symVertices, denoptim.graph.DGraph.templateJacket, and denoptim.graph.Template.updateInnerApID().
Referenced by denoptim.graph.DGraph.removeSingleVertexAndWeld(), and denoptim.graph.DGraph.removeVertexAndWeld().
removeSymmetryRedundance()
void denoptim.graph.DGraph.removeSymmetryRedundance (List< Vertex > list)
Remove all but one of the symmetry-related partners in a list of vertices.
The vertices must belong to this graph.
Parameters
list vertices to be purged.
Definition at line 6624 of file DGraph.java.
References denoptim.graph.DGraph.getSymSetsIterator().
Referenced by denoptim.graph.DGraph.findVertices(), and denoptim.graph.DGraph.removeSymmetryRedundantIds().
removeSymmetryRedundantIds()
void denoptim.graph.DGraph.removeSymmetryRedundantIds (ArrayList< Long > list)
Remove all but one of the symmetry-related partners in a given list of vertex IDs.
The vertices must belong to this graph.
Parameters
list the list of vertex IDs to be purged.
Definition at line 6658 of file DGraph.java.
References denoptim.graph.DGraph.getVertexWithId(), and denoptim.graph.DGraph.removeSymmetryRedundance().
removeSymmetrySet()
void denoptim.graph.DGraph.removeSymmetrySet (SymmetricVertexes ss)
Tries to determine the set of symmetric vertices in this graph based on finding compatible Vertexes that are either using symmetric AttachmentPoints (NB: all symmetric APs must be in use by vertexes that are compatible with each other) or that are downstream (i.e., according to edge direction) w.r.t Vertexes that are using symmetric AttachmentPoints.The compatibility of the vertexes is determined by these criteria:
the AP used to link the parent vertex must have the same features as defined by the AttachmentPoint#sameAs(Vertex) method.
the vertex must have the same features as defined by the Vertex#sameAs(Vertex) method. Effectively, this means they are instances of the same building block in the fragment space, or are graph building blocks that are not part of the fragment space, in which case the last condition applies,
vertexes have same features and isomorphic internal structure as from the Fragment#isIsomorphicTo(Vertex) method.
Returns
true if some symmetric set of vertex has been found.
Exceptions
DENOPTIMException Removed the given symmetric set, if present.
Parameters
ss the symmetric relation to be removed.
Definition at line 848 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.removeChainUpToBranching().
removeVertex()
void denoptim.graph.DGraph.removeVertex (Vertex vertex)
Remove a vertex from this graph.
This method removes also edges and rings that involve the given vertex. Symmetric sets of vertices are corrected accordingly: they are removed if there is only one remaining vertex in the set, or purged from the vertex being removed.
Parameters
vertex the vertex to remove.
Definition at line 1347 of file DGraph.java.
References denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.Edge.getSrcVertex(), denoptim.graph.Edge.getTrgVertex(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.isVertexInRing(), denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, denoptim.graph.DGraph.removeEdge(), denoptim.graph.DGraph.removeRing(), denoptim.graph.Vertex.resetGraphOwner(), and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.DGraph.extractSubgraph(), denoptim.ga.GraphOperationsTest.getExpectedSubgraphs(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeCappingGroupsOn(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeOrphanBranchStartingAt(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), and denoptim.graph.DGraphTest.testRemoveVertex().
removeVertexAndWeld()
boolean denoptim.graph.DGraph.removeVertexAndWeld (Vertex vertex, FragmentSpace fragSpace) throws DENOPTIMException
Remove a given vertex belonging to this graph and re-connects the resulting graph branches as much as possible.
This method reproduces the change of vertex on all symmetric sites.
Parameters
oldLink the vertex currently belonging to this graph and to be replaced.
Returns
true if the operation is successful.
Exceptions
DENOPTIMException
Definition at line 1423 of file DGraph.java.
References denoptim.utils.GraphUtils.ensureVertexIDConsistency(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.DGraph.getSymVerticesForVertex(), denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.AttachmentPoint.hasConnectedSrcAtom(), denoptim.graph.AttachmentPoint.hasSameSrcAtom(), and denoptim.graph.DGraph.removeSingleVertexAndWeld().
Referenced by denoptim.ga.GraphOperations.deleteLink().
renumberGraphVertices()
void denoptim.graph.DGraph.renumberGraphVertices ()
Reassign vertex IDs to all vertices of this graph.
The old IDs are stored in the vertex property DENOPTIMConstants#STOREDVID.
Definition at line 5512 of file DGraph.java.
References denoptim.graph.DGraph.renumberVerticesGetMap().
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.graph.DGraph.editGraph(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.ga.GraphOperationsTest.getFusedRings(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.ga.GraphOperationsTest.getThreeCycle(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphB(), denoptim.ga.PopulationTest.makeGraphC(), denoptim.ga.PopulationTest.makeGraphD(), denoptim.ga.PopulationTest.makeGraphF(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphA(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphE(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.fragspace.GraphLinkFinderTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.ga.XoverSite.projectToClonedGraphs(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.programs.genetweeker.GeneOpsRunner.runXOver(), and denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize().
renumberVerticesGetMap()
Map< Long, Long > denoptim.graph.DGraph.renumberVerticesGetMap ()
Reassign vertex IDs to a graph.
The old IDs are stored in the vertex property DENOPTIMConstants#STOREDVID.
Returns
map with old IDs as key and new IDs as values.
Definition at line 5525 of file DGraph.java.
References denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.Vertex.setProperty(), denoptim.graph.Vertex.setVertexId(), and denoptim.constants.DENOPTIMConstants.STOREDVID.
Referenced by denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), and denoptim.graph.DGraph.renumberGraphVertices().
reorderVertexList()
static void denoptim.graph.DGraph.reorderVertexList (DGraph g) static private
Sets the vertex at the lowest level as the scaffold, changes the
directions of edges so that the scaffold is the source, and changes the levels of the graph's other vertices to be consistent with the new scaffold.
Parameters
g Graph to fix.
Definition at line 4946 of file DGraph.java.
References denoptim.graph.DGraph.fixEdgeDirections(), denoptim.graph.DGraph.getSourceVertex(), and denoptim.graph.DGraph.setScaffold().
Referenced by denoptim.graph.DGraph.extractPattern().
replaceSingleSubGraph()
boolean denoptim.graph.DGraph.replaceSingleSubGraph (List< Vertex > subGrpVrtxs, DGraph newSubGraph, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap) throws DENOPTIMException
Replaced the subgraph represented by a given collection of vertices that belong to this graph.
This method does not project the change of vertex on symmetric sites, and does not alter the symmetric sets. To properly manage symmetry, you should run DGraph#reassignSymmetricLabels() on newSubGraph prior to calling this method, and, after running this method, call DGraph#convertSymmetricLabelsToSymmetricSets() on this graph. This strategy reflects the fact that multiple sub-graph replacements can introduce vertices that are symmetric throughout these newly inserted subgraphs, thus a single subgraph replacement cannot know the complete list of symmetric vertices. Therefore, the handling of the symmetry is left outside of the subgraph replacement operation.
Parameters
subGrpVrtxs the vertices currently belonging to this graph and to be replaced. We assume these collection of vertices is a connected subgraph, i.e., all vertices are reachable by one single vertex via a directed path that does not involve any other vertex not included in this collections.
newSubGraph the graph that will be attached on this graph. No copying or cloning: such graph contains the actual vertices that will become part of this graph.
apMap mapping of attachment points belonging to any vertex in subGrpVrtxs to attachment points in newSubGraph.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException
Definition at line 2183 of file DGraph.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Template.clearIAtomContainer(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.Edge.getBondType(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.DGraph.gVertices, denoptim.graph.AttachmentPoint.isAvailable(), denoptim.graph.DGraph.jGraph, denoptim.graph.DGraph.jGraphKernel, denoptim.graph.DGraph.removeEdge(), denoptim.graph.Template.removeProjectionOfInnerAP(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.templateJacket, and denoptim.graph.Template.updateInnerApID().
Referenced by denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.DGraphTest.testReplaceSubGraph(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
replaceSubGraph()
boolean denoptim.graph.DGraph.replaceSubGraph (List< Vertex > subGrpVrtxs, DGraph incomingGraph, LinkedHashMap< AttachmentPoint, AttachmentPoint > apMap, FragmentSpace fragSpace) throws DENOPTIMException
Replaced the subgraph represented by a given collection of vertices that belong to this graph.
This method reproduces the change of vertex on all symmetric sites, where a site is identified by a symmetrically identified reflection of the subgraph to replace, which are identified using symmetric sets.
Parameters
subGrpVrtxs the vertices currently belonging to this graph and to
be replaced. We assume these collection of vertices is a connected graph, i.e., all vertices are reachable by one single vertex via a directed path that does not involve any other vertex not included in this collections.
newSubGraph the graph that will be used to create the new branch replacing the old one. Vertices of such branch will be cloned to create the new vertices to be added to this graph.
apMap mapping of attachment points belonging to any vertex in subGrpVrtxs to attachment points in newSubGraph.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException is capping groups are the only vertices in the subgraph.
Definition at line 1909 of file DGraph.java.
References denoptim.graph.DGraph.addCappingGroups(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.utils.GraphUtils.ensureVertexIDConsistency(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getChilddren(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.DGraph.getSymmetricSubGraphs(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.removeCappingGroupsFromChilds(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.DGraph.replaceSingleSubGraph().
Referenced by denoptim.graph.DGraph.embedPatternsInTemplates(), and denoptim.ga.GraphOperations.performCrossover().
replaceUnusedRCVsWithCapps()
void denoptim.graph.DGraph.replaceUnusedRCVsWithCapps (FragmentSpace fragSpace) throws DENOPTIMException
Removes unused ring-closing vertices.
If the resulting free AP needs to be capped, then the proper capping group is places where a ring-closing vertex once stood.
Parameters
fragSpace the fragment space defining how capping is configured.
Exceptions
DENOPTIMException
Definition at line 1754 of file DGraph.java.
References denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.graph.DGraph.getRCVertices(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.removeVertex(), and denoptim.graph.Vertex.setVertexId().
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.programs.fitnessevaluator.FitnessEvaluationTask.call(), and denoptim.graph.DGraphTest.testRemoveUnusedRCVs().
replaceVertex() [1/2]
boolean denoptim.graph.DGraph.replaceVertex (Vertex vertex, int bbId, BBType bbt, LinkedHashMap< Integer, Integer > apIdMap, boolean symmetry, FragmentSpace fragSpace) throws DENOPTIMException
Replaced a given vertex belonging to this graph with a new vertex generated specifically for this purpose.
Parameters
vertex the vertex currently belonging to this graph and to be replaced.
bbId the building block Id of the building blocks that will replace the original vertex.
bbt the type of building block to be used to replace the original vertex.
apMap the mapping of attachment points needed to install the new vertex in the slot of the old one and recreate the edges to the rest of the graph.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException
Definition at line 2511 of file DGraph.java.
References denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraph.DGraph(), denoptim.utils.GraphUtils.ensureVertexIDConsistency(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.DGraph.getSymVerticesForVertex(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.gVertices, denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.reassignSymmetricLabels(), denoptim.graph.DGraph.renumberGraphVertices(), denoptim.graph.DGraph.replaceSingleSubGraph(), and denoptim.graph.Vertex.setMutationTypes().
replaceVertex() [2/2]
boolean denoptim.graph.DGraph.replaceVertex (Vertex vertex, int bbId, BBType bbt, LinkedHashMap< Integer, Integer > apIdMap, FragmentSpace fragSpace) throws DENOPTIMException
Replaced a given vertex belonging to this graph with a new vertex generated specifically for this purpose.
This method reproduces the change of vertex on all symmetric sites.
Parameters
vertex the vertex currently belonging to this graph and to be replaced.
bbId the building block Id of the building blocks that will replace the original vertex.
bbt the type of building block to be used to replace the original vertex.
apMap the mapping of attachment points needed to install the new vertex in the slot of the old one and recreate the edges to the rest of the graph.
Returns
true if the substitution is successful.
Exceptions
DENOPTIMException
Definition at line 2487 of file DGraph.java.
References denoptim.graph.DGraph.replaceVertex().
Referenced by denoptim.graph.DGraph.editGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.ga.GraphOperations.substituteLink(), denoptim.graph.DGraphTest.testReplaceVertex(), and denoptim.graph.DGraphTest.testReplaceVertex_inRing().
sameAs()
boolean denoptim.graph.DGraph.sameAs (DGraph other, StringBuilder reason)
Compare this and another graph ignoring the vertex IDs.
This method looks into the structure of the graphs to determine if the two graphs have the same spanning tree, same symmetric sets, and same rings set, despite having different vertex IDs. Does not check for alternative permutations nor alternatives spanning trees so it returns false for isomorphic graphs that are represented by different spanning trees.
Parameters
other the other graph to be compared with this graph
Returns
true if the two graphs represent the same system
Definition at line 3894 of file DGraph.java.
References denoptim.graph.DGraph.compareGraphNodes(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getRings(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), and denoptim.graph.DGraph.sameAsRings().
Referenced by denoptim.ga.Population.getXoverPartners(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_Free(), denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FreeBackwards(), denoptim.graph.DGraphTest.testSameAs_DiffRings(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_DiffVertex(), denoptim.graph.DGraphTest.testSameAs_DisorderRings(), denoptim.graph.DGraphTest.testSameAs_Equal(), denoptim.graph.DGraphTest.testSameAs_SameRings(), denoptim.graph.DGraphTest.testSameAs_SameSymmSet(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
sameAsRings()
boolean denoptim.graph.DGraph.sameAsRings (StringBuilder reason, Map< Vertex, Vertex > vertexMap, Ring rT, Vertex vhT, Vertex vtT, Ring rO) private
Definition at line 4004 of file DGraph.java.
References denoptim.graph.Ring.getHeadVertex(), denoptim.graph.Ring.getSize(), denoptim.graph.Ring.getTailVertex(), and denoptim.graph.Ring.getVertexAtPosition().
Referenced by denoptim.graph.DGraph.sameAs().
setCandidateClosableChains()
void denoptim.graph.DGraph.setCandidateClosableChains (ArrayList< ClosableChain > closableChains)
Definition at line 933 of file DGraph.java.
References denoptim.graph.DGraph.closableChains.
Referenced by denoptim.ga.EAUtils.buildGraph(), and denoptim.graph.DGraph.clone().
setCandidateOwner()
void denoptim.graph.DGraph.setCandidateOwner (Candidate candidate)
Sets the reference to the candidate item that is defined by this graph.
Parameters
candidate the candidate owner.
Definition at line 245 of file DGraph.java.
References denoptim.graph.DGraph.candidate.
Referenced by denoptim.graph.Candidate.Candidate().
setEdgeList()
void denoptim.graph.DGraph.setEdgeList (ArrayList< Edge > edges)
Definition at line 915 of file DGraph.java.
References denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
setGraphId()
void denoptim.graph.DGraph.setGraphId (int id)
Definition at line 264 of file DGraph.java.
References denoptim.graph.DGraph.graphId.
Referenced by denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.EAUtils.buildGraph(), denoptim.graph.DGraph.clone(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.ga.GraphOperationsTest.getPairOfTestGraphs(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.combinatorial.GraphBuildingTask.GraphBuildingTask(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), denoptim.combinatorial.CombinatorialExplorerByLayer.startNewGraphFromScaffold(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
setLocalMsg()
void denoptim.graph.DGraph.setLocalMsg (String msg)
Definition at line 279 of file DGraph.java.
References denoptim.graph.DGraph.localMsg.
Referenced by denoptim.ga.EAUtils.buildCandidateByFragmentingMolecule(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.ga.EAUtils.buildCandidateFromScratch(), denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.ga.EAUtils.buildGraph(), denoptim.graph.DGraph.clone(), denoptim.ga.EvolutionaryAlgorithm.makeOffspringB(), denoptim.ga.GraphOperations.performMutation(), denoptim.ga.EAUtils.readCandidateFromFile(), and denoptim.combinatorial.CombinatorialExplorerByLayer.startNewGraphFromScaffold().
setRings()
void denoptim.graph.DGraph.setRings (ArrayList< Ring > rings)
Definition at line 924 of file DGraph.java.
References denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.graph.DGraph.clone(), and denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets().
setScaffold()
static void denoptim.graph.DGraph.setScaffold (Vertex v) static
Update the graph so that the vertex argument is at the scaffold level i.e.
is the source of this graph. The vertex list of this graph will also be reordered in a way that corresponds to the BFS.
Parameters
v vertex to set as scaffold
Definition at line 7129 of file DGraph.java.
References denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.Vertex.getVertexId(), and denoptim.graph.DGraph.setVertexList().
Referenced by denoptim.ga.GraphOperationsTest.getFusedRings(), and denoptim.graph.DGraph.reorderVertexList().
setSymmetricVertexSets()
void denoptim.graph.DGraph.setSymmetricVertexSets (List< SymmetricVertexes > symVertices)
Definition at line 875 of file DGraph.java.
References denoptim.graph.DGraph.symVertices.
Referenced by denoptim.graph.DGraph.clone().
setTemplateJacket()
void denoptim.graph.DGraph.setTemplateJacket (Template template)
Sets the reference to a template that embeds this graph, i.e., this graph's "jacket" template.
Parameters
denoptimTemplate the jacket template
Definition at line 7188 of file DGraph.java.
Referenced by denoptim.graph.Template.setInnerGraph().
setVertexList()
void denoptim.graph.DGraph.setVertexList (ArrayList< Vertex > vertices)
Definition at line 906 of file DGraph.java.
References denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.jGraph, and denoptim.graph.DGraph.jGraphKernel.
Referenced by denoptim.graph.DGraph.setScaffold().
storeCurrentVertexIDs()
void denoptim.graph.DGraph.storeCurrentVertexIDs ()
Copies the current vertexID of each vertex into a property of the vertex itself.
Use this to keep a memory of the vertex IDs in any given moment.
Definition at line 7248 of file DGraph.java.
References denoptim.graph.DGraph.gVertices, and denoptim.constants.DENOPTIMConstants.STOREDVID.
toJson()
String denoptim.graph.DGraph.toJson ()
Produces a string that represents this graph and that adheres to the JSON format.
Returns
the JSON format as a single string
Definition at line 6926 of file DGraph.java.
References denoptim.json.DENOPTIMgson.getWriter().
Referenced by denoptim.ga.OffspringEvaluationTask.call(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.graph.DGraphTest.testFromToJSON(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
toString()
String denoptim.graph.DGraph.toString ()
Definition at line 2909 of file DGraph.java.
References denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.graphId, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.symVertices.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), denoptim.ga.OffspringEvaluationTask.call(), denoptim.graph.DGraph.checkConsistency(), denoptim.graph.Candidate.getFitnessProviderOutputRepresentation(), denoptim.programs.genetweeker.GeneOpsRunner.runMutation(), and denoptim.programs.graphlisthandler.GraphListsHandler.runProgram().
Member Data Documentation
apCounter
AtomicInteger denoptim.graph.DGraph.apCounter = new AtomicInteger(1) private
Generator of unique AP identifiers within this graph.
Definition at line 172 of file DGraph.java.
Referenced by denoptim.graph.DGraph.ensureUniqueApIDs(), and denoptim.graph.DGraph.getUniqueAPIndex().
candidate
Candidate denoptim.graph.DGraph.candidate package
Reference to the candidate entity owning this graph, or null.
Definition at line 145 of file DGraph.java.
Referenced by denoptim.graph.DGraph.getCandidateOwner(), and denoptim.graph.DGraph.setCandidateOwner().
closableChains
List<ClosableChain> denoptim.graph.DGraph.closableChains package
The potentially closable chains of vertices.
Definition at line 121 of file DGraph.java.
Referenced by denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.getClosableChains(), denoptim.graph.DGraph.setCandidateClosableChains(), and denoptim.graph.DGraphTest.testClone().
gEdges
List<Edge> denoptim.graph.DGraph.gEdges package
The edges belonging to this graph.
Definition at line 111 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.getEdgeAtPosition(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getEdgeList(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraph.isReversible(), denoptim.graph.DGraph.removeEdge(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.graph.DGraph.setEdgeList(), denoptim.graph.DGraphTest.testClone(), and denoptim.graph.DGraph.toString().
graphId
int denoptim.graph.DGraph.graphId package
Definition at line 126 of file DGraph.java.
Referenced by denoptim.graph.DGraph.clone(), denoptim.graph.Candidate.compareTo(), denoptim.graph.DGraph.getGraphId(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.graph.DGraph.setGraphId(), denoptim.graph.DGraphTest.testClone(), and denoptim.graph.DGraph.toString().
gRings
List<Ring> denoptim.graph.DGraph.gRings package
The rings defined in this graph.
Definition at line 116 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getRings(), denoptim.graph.DGraph.getRingsInvolvingVertex(), denoptim.graph.DGraph.getRingsInvolvingVertexID(), denoptim.graph.DGraph.hasOrEmbedsRings(), denoptim.graph.DGraph.hasRings(), denoptim.graph.DGraph.isVertexIDInRing(), denoptim.graph.DGraph.isVertexInRing(), denoptim.graph.DGraph.removeRing(), denoptim.graph.DGraph.removeVertexAndWeld(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.graph.DGraph.setRings(), denoptim.graph.DGraphTest.testClone(), and denoptim.graph.DGraph.toString().
gVertices
List<Vertex> denoptim.graph.DGraph.gVertices package
The vertices belonging to this graph.
Definition at line 106 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addCappingGroups(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.containsOrEmbedsVertex(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.DGraph.containsVertexID(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.graph.DGraph.getBranchIdOfVertex(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.DGraph.getMutableSites(), denoptim.graph.Template.getMutationSites(), denoptim.graph.DGraph.getRCVertices(), denoptim.graph.DGraph.getSelectedMutableSites(), denoptim.graph.DGraph.getSourceVertex(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.getVertexWithId(), denoptim.graph.DGraph.hasOrEmbedsRings(), denoptim.graph.DGraph.indexOf(), denoptim.graph.DGraph.indexOfVertexWithID(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.reassignSymmetricLabels(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.removeVertexAndWeld(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.replaceSubGraph(), denoptim.graph.DGraph.replaceVertex(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.graph.DGraph.setVertexList(), denoptim.graph.DGraph.storeCurrentVertexIDs(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.graph.DGraph.toString(), and denoptim.graph.Template.updateMutTypeToFixedSTructure().
jGraph
DefaultUndirectedGraph<Vertex, UndirectedEdge> denoptim.graph.DGraph.jGraph = null private
JGraph representation used to detect DENOPTIM-isomorphism.
Definition at line 156 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.removeEdge(), denoptim.graph.DGraph.removeRing(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.setEdgeList(), denoptim.graph.DGraph.setRings(), and denoptim.graph.DGraph.setVertexList().
jGraphKernel
DefaultUndirectedGraph<Node, NodeConnection> denoptim.graph.DGraph.jGraphKernel = null private
JGraph representation used to detect DENOPTIM-isostructural graphs.
Definition at line 162 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.graph.DGraph.removeEdge(), denoptim.graph.DGraph.removeRing(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.DGraph.setEdgeList(), denoptim.graph.DGraph.setRings(), and denoptim.graph.DGraph.setVertexList().
localMsg
String denoptim.graph.DGraph.localMsg package
A free-format string used to record simple properties in the graph.
For instance, whether this graph comes from a given initial population or is generated anew from scratch, or from mutation/crossover.
Definition at line 140 of file DGraph.java.
Referenced by denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.getLocalMsg(), denoptim.graph.DGraph.setLocalMsg(), and denoptim.graph.DGraphTest.testClone().
SYM_ID
final String denoptim.graph.DGraph.SYM_ID = "symmetryKey" static private
Key used to uniquely identify vertices and attachment points for symmetry detection.
Definition at line 178 of file DGraph.java.
Referenced by denoptim.graph.DGraph.detectSymVertexSets(), and denoptim.graph.DGraph.dfsEncodePaths().
symVertices
List<SymmetricVertexes> denoptim.graph.DGraph.symVertices private
Definition at line 132 of file DGraph.java.
Referenced by denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.cleanup(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.DGraph.DGraph(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getSymVerticesForVertex(), denoptim.graph.DGraph.hasSymmetricAP(), denoptim.graph.DGraph.hasSymmetryInvolvingVertex(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeSymmetrySet(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize(), denoptim.graph.DGraph.setSymmetricVertexSets(), and denoptim.graph.DGraph.toString().
templateJacket
Template denoptim.graph.DGraph.templateJacket package
Reference to the Template embedding this graph.
Definition at line 150 of file DGraph.java.
Referenced by denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.graph.AttachmentPoint.getEdgeUserThroughout(), denoptim.graph.DGraph.getEmbeddingPath(), denoptim.graph.DGraph.getOutermostGraphOwner(), denoptim.graph.DGraph.getTemplateJacket(), denoptim.graph.DGraph.insertSingleVertex(), denoptim.graph.AttachmentPoint.isAvailableThroughout(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.Template.removeProjectionOfInnerAP(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), and denoptim.graph.DGraph.replaceSingleSubGraph().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/DGraph.java