DENOPTIM: denoptim.fragspace.FragmentSpaceUtils Class Reference
denoptim.fragspace.FragmentSpaceUtils Class Reference
Utility class for the fragment space.
Static Public Member Functions
static boolean recursiveCombiner (List< AttachmentPoint > keys, int currentKey, Map< AttachmentPoint, List< AttachmentPoint > > possibilities, APMapping combination, List< APMapping > completeCombinations, boolean screenAll, int maxCombs)
Search for all possible combinations of compatible APs.
Detailed Description
Utility class for the fragment space.
Author
Marco Foscato
Definition at line 33 of file FragmentSpaceUtils.java.
Member Function Documentation
recursiveCombiner()
static boolean denoptim.fragspace.FragmentSpaceUtils.recursiveCombiner (List< AttachmentPoint > keys, int currentKey, Map< AttachmentPoint, List< AttachmentPoint > > possibilities, APMapping combination, List< APMapping > completeCombinations, boolean screenAll, int maxCombs) static
Search for all possible combinations of compatible APs.
Parameters
keys sorted list of keys in the 'possibilities' argument.
currentKey index of the currently active key in 'keys'
possibilities the mapping of all APs from listB that are compatible with a specific AP from list A.
combination the combination currently under construction.
completeCombinations the storage of all valid combination; this is effectively the output of this method.
screenAll flag requiring comprehensive exploration of all combinations
maxCombs maximum number of combinations to consider. If this number is reached then we stop searching for more.
Returns
a flag indicating whether execution was stopper or not.
Definition at line 53 of file FragmentSpaceUtils.java.
References denoptim.graph.APMapping.clone(), and denoptim.fragspace.FragmentSpaceUtils.recursiveCombiner().
Referenced by denoptim.fragspace.APMapFinder.findAllMappings(), denoptim.fragspace.GraphLinkFinder.GraphLinkFinder(), denoptim.fragspace.FragmentSpace.mapAPClassCompatibilities(), and denoptim.fragspace.FragmentSpaceUtils.recursiveCombiner().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fragspace/FragmentSpaceUtils.java