DENOPTIM: denoptim.molecularmodeling.zmatrix.ZMatrixAtom Class Reference
denoptim.molecularmodeling.zmatrix.ZMatrixAtom Class Reference
Representation of an atom in the ZMatrix.
Public Member Functions
ZMatrixAtom (int id, String symbol, String type, ZMatrixAtom bondRefAtom, ZMatrixAtom angleRefAtom, ZMatrixAtom angle2RefAtom, Double bondLength, Double angleValue, Double angle2Value, Integer chiralFlag)
Constructor for ZMatrixAtom.
int getId ()
Get the id of the atom.
void setId (int id)
Set the id of the atom.
String getSymbol ()
Get the symbol of the atom.
void setSymbol (String symbol)
Set the symbol of the atom.
String getType ()
Get the type of the atom.
void setType (String type)
Set the type of the atom.
ZMatrixAtom getBondRefAtom ()
Get the bond reference atom.
ZMatrixAtom getAngleRefAtom ()
Get the angle reference atom.
ZMatrixAtom getAngle2RefAtom ()
Get the angle2 reference atom.
Double getBondLength ()
Get the bond length.
Double getAngleValue ()
Get the angle value.
Double getAngle2Value ()
Get the angle2 value.
void setBondLength (Double bondLength)
Set the bond length.
void setAngleValue (Double angleValue)
Set the angle value.
void setAngle2Value (Double angle2Value)
Set the angle2 value.
void setChiralFlag (Integer chiralFlag)
Set the chiral flag.
Integer getChiralFlag ()
Get the chiral flag.
boolean usesProperTorsion ()
Check if the atom uses proper torsion.
boolean equals (Object o)
Get the string representation of the atom.
int hashCode ()
String toString ()
Package Functions
void setBondRefAtom (ZMatrixAtom bondRefAtom)
Package-private setter for bond reference atom (used for cloning).
void setAngleRefAtom (ZMatrixAtom angleRefAtom)
Package-private setter for angle reference atom (used for cloning).
void setAngle2RefAtom (ZMatrixAtom angle2RefAtom)
Package-private setter for angle2 reference atom (used for cloning).
Private Attributes
int id
String symbol
String type
ZMatrixAtom bondRefAtom
ZMatrixAtom angleRefAtom
ZMatrixAtom angle2RefAtom
Double bondLength
Double angleValue
Double angle2Value
Integer chiralFlag
Detailed Description
Representation of an atom in the ZMatrix.
Definition at line 8 of file ZMatrixAtom.java.
Constructor & Destructor Documentation
ZMatrixAtom()
denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom (int id, String symbol, String type, ZMatrixAtom bondRefAtom, ZMatrixAtom angleRefAtom, ZMatrixAtom angle2RefAtom, Double bondLength, Double angleValue, Double angle2Value, Integer chiralFlag)
Constructor for ZMatrixAtom.
Parameters
id The id of the atom
symbol The symbol of the atom
type The type of the atom
bondRefAtom The bond reference atom
angleRefAtom The angle reference atom
angle2RefAtom The angle2 reference atom
bondLength The bond length
angleValue The angle value
angle2Value The angle2 value
chiralFlag The chiral flag
Definition at line 36 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals().
Member Function Documentation
equals()
boolean denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals (Object o)
Get the string representation of the atom.
Returns
The string representation of the atom
Definition at line 290 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag, denoptim.constants.DENOPTIMConstants.FLOATCOMPARISONTOLERANCE, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals().
getAngle2RefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2RefAtom ()
Get the angle2 reference atom.
Returns
The angle2 reference atom or null if not set
Definition at line 147 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtom().
getAngle2Value()
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2Value ()
Get the angle2 value.
Returns
The angle2 value or null if not set
Definition at line 180 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2Value(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getAngleRefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleRefAtom ()
Get the angle reference atom.
Returns
The angle reference atom or null if not set
Definition at line 136 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtom().
getAngleValue()
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleValue ()
Get the angle value.
Returns
The angle value or null if not set
Definition at line 169 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleValue(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getBondLength()
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondLength ()
Get the bond length.
Returns
The bond length or null if not set
Definition at line 158 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getBondLength(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getBondRefAtom()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondRefAtom ()
Get the bond reference atom.
Returns
The bond reference atom or null if not set
Definition at line 125 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtom(), and denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel().
getChiralFlag()
Integer denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getChiralFlag ()
Get the chiral flag.
Returns
The chiral flag or null if not set
Definition at line 235 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag(), and denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT().
getId()
int denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId ()
Get the id of the atom.
Returns
The id of the atom
Definition at line 59 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondsToDel(), denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.toString(), and denoptim.integration.tinker.TinkerUtils.writeTinkerINT().
getSymbol()
String denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getSymbol ()
Get the symbol of the atom.
Returns
The symbol of the atom
Definition at line 81 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol.
Referenced by denoptim.integration.rcoserver.RCOSocketServerClient.getZMatrixAsJsonArray(), denoptim.integration.tinker.ConformationalSearchPSSROT.setTinkerTypes(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), and denoptim.integration.tinker.TinkerUtils.writeTinkerINT().
getType()
String denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getType ()
Get the type of the atom.
Returns
The type of the atom
Definition at line 103 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), and denoptim.integration.tinker.TinkerUtils.writeTinkerINT().
hashCode()
int denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode ()
Definition at line 393 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixAtomHashCode().
setAngle2RefAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2RefAtom (ZMatrixAtom angle2RefAtom) package
Package-private setter for angle2 reference atom (used for cloning).
Definition at line 276 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setAngle2Value()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2Value (Double angle2Value)
Set the angle2 value.
Parameters
angle2Value The angle2 value to set
Definition at line 213 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.rcoserver.RCOSocketServerClient.runConformationalOptimization(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setAngleRefAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleRefAtom (ZMatrixAtom angleRefAtom) package
Package-private setter for angle reference atom (used for cloning).
Definition at line 266 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setAngleValue()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleValue (Double angleValue)
Set the angle value.
Parameters
angleValue The angle value to set
Definition at line 202 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.rcoserver.RCOSocketServerClient.runConformationalOptimization(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setBondLength()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondLength (Double bondLength)
Set the bond length.
Parameters
bondLength The bond length to set
Definition at line 191 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.rcoserver.RCOSocketServerClient.runConformationalOptimization(), denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setBondRefAtom()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondRefAtom (ZMatrixAtom bondRefAtom) package
Package-private setter for bond reference atom (used for cloning).
Definition at line 256 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setChiralFlag()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setChiralFlag (Integer chiralFlag)
Set the chiral flag.
Parameters
chiralFlag The chiral flag to set
Definition at line 224 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.integration.rcoserver.RCOSocketServerClient.runConformationalOptimization(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setId()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setId (int id)
Set the id of the atom.
Parameters
id The id of the atom to set
Definition at line 70 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixAtomHashCode().
setSymbol()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setSymbol (String symbol)
Set the symbol of the atom.
Parameters
symbol The symbol of the atom to set
Definition at line 92 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol.
Referenced by denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
setType()
void denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setType (String type)
Set the type of the atom.
Parameters
type The type of the atom to set
Definition at line 114 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type.
Referenced by denoptim.integration.tinker.ConformationalSearchPSSROT.setTinkerTypes(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testEquals().
toString()
String denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString ()
Definition at line 412 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type.
usesProperTorsion()
boolean denoptim.molecularmodeling.zmatrix.ZMatrixAtom.usesProperTorsion ()
Check if the atom uses proper torsion.
Returns
True if the atom uses proper torsion, false otherwise
Definition at line 246 of file ZMatrixAtom.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag.
Member Data Documentation
angle2RefAtom
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2RefAtom private
Definition at line 15 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2RefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
angle2Value
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angle2Value private
Definition at line 18 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngle2Value(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngle2Value(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
angleRefAtom
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleRefAtom private
Definition at line 14 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
angleValue
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.angleValue private
Definition at line 17 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getAngleValue(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setAngleValue(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
bondLength
Double denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondLength private
Definition at line 16 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondLength(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondLength(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
bondRefAtom
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixAtom.bondRefAtom private
Definition at line 13 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setBondRefAtom(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
chiralFlag
Integer denoptim.molecularmodeling.zmatrix.ZMatrixAtom.chiralFlag private
Definition at line 19 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getChiralFlag(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setChiralFlag(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.usesProperTorsion(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
id
int denoptim.molecularmodeling.zmatrix.ZMatrixAtom.id private
Definition at line 10 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setId(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
symbol
String denoptim.molecularmodeling.zmatrix.ZMatrixAtom.symbol private
Definition at line 11 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getSymbol(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setSymbol(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
type
String denoptim.molecularmodeling.zmatrix.ZMatrixAtom.type private
Definition at line 12 of file ZMatrixAtom.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getType(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.setType(), denoptim.molecularmodeling.zmatrix.ZMatrixAtom.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.ZMatrixAtom().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/zmatrix/ZMatrixAtom.java