DENOPTIM: denoptim.graph.DGraph.DENOPTIMGraphSerializer Class Reference
denoptim.graph.DGraph.DENOPTIMGraphSerializer Class Reference
We expect unique IDs for vertices.
Public Member Functions
JsonElement serialize (DGraph g, Type typeOfSrc, JsonSerializationContext context)
Detailed Description
We expect unique IDs for vertices.
Definition at line 6978 of file DGraph.java.
Member Function Documentation
serialize()
JsonElement denoptim.graph.DGraph.DENOPTIMGraphSerializer.serialize (DGraph g, Type typeOfSrc, JsonSerializationContext context)
Definition at line 6982 of file DGraph.java.
References denoptim.graph.DGraph.ensureUniqueApIDs(), denoptim.graph.DGraph.gEdges, denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.graphId, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.DGraph.symVertices.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/DGraph.java