DENOPTIM: denoptim.gui.JUNGGraphSnapshot Class Reference
denoptim.gui.JUNGGraphSnapshot Class Reference
This class collects information on how a graph was displayed in a JUNG visialisation server (i.e., node positions and visible labels).
Public Member Functions
JUNGGraphSnapshot (Graph< JVertex, JEdge > graph, DNPSpringLayout< JVertex, JEdge > layout)
JUNGGraphSnapshot (Graph< JVertex, JEdge > graph, ISOMLayout< JVertex, JEdge > layout)
ArrayList< String > getVertexeIDsWithLabel (LabelType labelName)
ArrayList< String > getEdgeIDsWithLabel (LabelType labelName)
Package Attributes
Map< String, Point2D > vertexPosition = new HashMap<String,Point2D>()
Positions of nodes.
Private Member Functions
void processVertex (JVertex v, LabelType lt)
void processEdge (JEdge e, LabelType lt)
Private Attributes
Map< LabelType, ArrayList< String > > vertexesWithLabels
The collection of vertexes with labels (by label type)
Map< LabelType, ArrayList< String > > edgesWithLabels
The collection of edges with labels (by label type)
Detailed Description
This class collects information on how a graph was displayed in a JUNG visialisation server (i.e., node positions and visible labels).
Definition at line 38 of file JUNGGraphSnapshot.java.
Constructor & Destructor Documentation
JUNGGraphSnapshot() [1/2]
denoptim.gui.JUNGGraphSnapshot.JUNGGraphSnapshot (Graph< JVertex, JEdge > graph, DNPSpringLayout< JVertex, JEdge > layout)
Definition at line 59 of file JUNGGraphSnapshot.java.
References denoptim.gui.GraphViewerPanel.LabelType.APC, denoptim.gui.GraphViewerPanel.LabelType.BBID, denoptim.gui.GraphViewerPanel.LabelType.BT, denoptim.gui.DNPSpringLayout< V, E >.getVertexPosition(), denoptim.gui.JUNGGraphSnapshot.processEdge(), denoptim.gui.JUNGGraphSnapshot.processVertex(), and denoptim.gui.JUNGGraphSnapshot.vertexPosition.
JUNGGraphSnapshot() [2/2]
denoptim.gui.JUNGGraphSnapshot.JUNGGraphSnapshot (Graph< JVertex, JEdge > graph, ISOMLayout< JVertex, JEdge > layout)
Definition at line 97 of file JUNGGraphSnapshot.java.
References denoptim.gui.JUNGGraphSnapshot.vertexPosition.
Member Function Documentation
getEdgeIDsWithLabel()
ArrayList< String > denoptim.gui.JUNGGraphSnapshot.getEdgeIDsWithLabel (LabelType labelName)
Definition at line 147 of file JUNGGraphSnapshot.java.
References denoptim.gui.JUNGGraphSnapshot.edgesWithLabels.
Referenced by denoptim.gui.GraphViewerPanel.inheritFeatures().
getVertexeIDsWithLabel()
ArrayList< String > denoptim.gui.JUNGGraphSnapshot.getVertexeIDsWithLabel (LabelType labelName)
Definition at line 137 of file JUNGGraphSnapshot.java.
References denoptim.gui.JUNGGraphSnapshot.vertexesWithLabels.
Referenced by denoptim.gui.GraphViewerPanel.inheritFeatures().
processEdge()
void denoptim.gui.JUNGGraphSnapshot.processEdge (JEdge e, LabelType lt) private
Definition at line 123 of file JUNGGraphSnapshot.java.
References denoptim.gui.JUNGGraphSnapshot.edgesWithLabels, and denoptim.gui.GraphViewerPanel.JEdge.id.
Referenced by denoptim.gui.JUNGGraphSnapshot.JUNGGraphSnapshot().
processVertex()
void denoptim.gui.JUNGGraphSnapshot.processVertex (JVertex v, LabelType lt) private
Definition at line 109 of file JUNGGraphSnapshot.java.
References denoptim.gui.GraphViewerPanel.JVertex.idStr, and denoptim.gui.JUNGGraphSnapshot.vertexesWithLabels.
Referenced by denoptim.gui.JUNGGraphSnapshot.JUNGGraphSnapshot().
Member Data Documentation
edgesWithLabels
Map<LabelType,ArrayList<String> > denoptim.gui.JUNGGraphSnapshot.edgesWithLabels private
Initial value:
=
                    new HashMap<LabelType,ArrayList<String>>()
The collection of edges with labels (by label type)
Definition at line 49 of file JUNGGraphSnapshot.java.
Referenced by denoptim.gui.JUNGGraphSnapshot.getEdgeIDsWithLabel(), and denoptim.gui.JUNGGraphSnapshot.processEdge().
vertexesWithLabels
Map<LabelType,ArrayList<String> > denoptim.gui.JUNGGraphSnapshot.vertexesWithLabels private
Initial value:
=
                    new HashMap<LabelType,ArrayList<String>>()
The collection of vertexes with labels (by label type)
Definition at line 43 of file JUNGGraphSnapshot.java.
Referenced by denoptim.gui.JUNGGraphSnapshot.getVertexeIDsWithLabel(), and denoptim.gui.JUNGGraphSnapshot.processVertex().
vertexPosition
Map<String,Point2D> denoptim.gui.JUNGGraphSnapshot.vertexPosition = new HashMap<String,Point2D>() package
Positions of nodes.
Definition at line 55 of file JUNGGraphSnapshot.java.
Referenced by denoptim.gui.GraphViewerPanel.inheritFeatures(), and denoptim.gui.JUNGGraphSnapshot.JUNGGraphSnapshot().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/JUNGGraphSnapshot.java