DENOPTIM: denoptim.graph.CandidateLW Class Reference
denoptim.graph.CandidateLW Class Reference
A light-weight candidate is a very low-demanding collection of data upon a specific candidate item.
Public Member Functions
CandidateLW (String uid, String name, String pathNameToFile)
void setFitness (double fitness)
double getFitness ()
void setError (String error)
String getError ()
String getName ()
String getUid ()
String getPathToFile ()
boolean hasFitness ()
void setGeneration (int genId)
int getGeneration ()
void setGeneratingSource (String source)
String getGeneratingSource ()
void setLevel (int lev)
Sets level that generated this graph in a fragment space exploration experiment.
int getLevel ()
Returns the level that generated this graph in a fragment space exploration experiment.
boolean equals (Object o)
Private Attributes
String uid
Unique identifier of this candidate.
String name
Name of this candidate (not guaranteed to be unique).
String pathNameToFile
Pathname to file defining this item in detail.
Double fitness
fThe fitness value or null;
String error
Error that prevented calculation of the fitness or null.
Integer generationId
ID of the generation this molecule belong to (or null)
Integer level
Level that generated this graph in fragment space exploration (or null)
String generatingSource
A statement defining how this item was generated.
Detailed Description
A light-weight candidate is a very low-demanding collection of data upon a specific candidate item.
This does NOT include the DGraph or any molecular representation. The purpose of this class is to encapsulate only the lowest possible amount of information needed manipulate the item in a larger list of items (e.g., when plotting evolution plots). Note that only the name and UID are used to check for equality.
Definition at line 31 of file CandidateLW.java.
Constructor & Destructor Documentation
CandidateLW()
denoptim.graph.CandidateLW.CandidateLW (String uid, String name, String pathNameToFile)
Definition at line 75 of file CandidateLW.java.
References denoptim.graph.CandidateLW.name, denoptim.graph.CandidateLW.pathNameToFile, and denoptim.graph.CandidateLW.uid.
Referenced by denoptim.graph.CandidateLW.equals().
Member Function Documentation
equals()
boolean denoptim.graph.CandidateLW.equals (Object o)
Definition at line 194 of file CandidateLW.java.
References denoptim.graph.CandidateLW.CandidateLW(), denoptim.graph.CandidateLW.name, and denoptim.graph.CandidateLW.uid.
getError()
String denoptim.graph.CandidateLW.getError ()
Definition at line 105 of file CandidateLW.java.
References denoptim.graph.CandidateLW.error.
getFitness()
double denoptim.graph.CandidateLW.getFitness ()
Definition at line 91 of file CandidateLW.java.
References denoptim.graph.CandidateLW.fitness.
Referenced by denoptim.gui.GUIInspectGARun.PlottedCandidatesComparator.compare(), denoptim.gui.GUIInspectGARun.getOverlappingItems(), denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectGARun.importGARunData(), denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem(), and denoptim.gui.GUIInspectGARun.renderViewWithSelectedItem().
getGeneratingSource()
String denoptim.graph.CandidateLW.getGeneratingSource ()
Definition at line 161 of file CandidateLW.java.
References denoptim.graph.CandidateLW.generatingSource.
getGeneration()
int denoptim.graph.CandidateLW.getGeneration ()
Definition at line 147 of file CandidateLW.java.
References denoptim.graph.CandidateLW.generationId.
Referenced by denoptim.gui.GUIInspectGARun.PlottedCandidatesComparator.compare(), denoptim.gui.GUIInspectGARun.getOverlappingItems(), denoptim.gui.GUIInspectGARun.importGARunData(), denoptim.gui.GUIInspectGARun.readOneGeneration(), and denoptim.gui.GUIInspectGARun.renderViewWithSelectedItem().
getLevel()
int denoptim.graph.CandidateLW.getLevel ()
Returns the level that generated this graph in a fragment space exploration experiment.
Returns
the level that generated this graph in a fragment space exploration experiment.
Definition at line 186 of file CandidateLW.java.
References denoptim.graph.CandidateLW.level.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
getName()
String denoptim.graph.CandidateLW.getName ()
Definition at line 112 of file CandidateLW.java.
References denoptim.graph.CandidateLW.name.
getPathToFile()
String denoptim.graph.CandidateLW.getPathToFile ()
Definition at line 126 of file CandidateLW.java.
References denoptim.graph.CandidateLW.pathNameToFile.
Referenced by denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem(), and denoptim.gui.GUIInspectGARun.renderViewWithSelectedItem().
getUid()
String denoptim.graph.CandidateLW.getUid ()
Definition at line 119 of file CandidateLW.java.
References denoptim.graph.CandidateLW.uid.
hasFitness()
boolean denoptim.graph.CandidateLW.hasFitness ()
Definition at line 133 of file CandidateLW.java.
References denoptim.graph.CandidateLW.fitness.
Referenced by denoptim.gui.GUIInspectGARun.PlottedCandidatesComparator.compare(), denoptim.gui.GUIInspectGARun.getOverlappingItems(), denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectGARun.importGARunData(), and denoptim.gui.GUIInspectGARun.readOneGeneration().
setError()
void denoptim.graph.CandidateLW.setError (String error)
Definition at line 98 of file CandidateLW.java.
References denoptim.graph.CandidateLW.error.
Referenced by denoptim.io.DenoptimIO.readLightWeightCandidate().
setFitness()
void denoptim.graph.CandidateLW.setFitness (double fitness)
Definition at line 84 of file CandidateLW.java.
References denoptim.graph.CandidateLW.fitness.
Referenced by denoptim.io.DenoptimIO.readLightWeightCandidate(), and denoptim.io.DenoptimIO.readPopulationMembersTraces().
setGeneratingSource()
void denoptim.graph.CandidateLW.setGeneratingSource (String source)
Definition at line 154 of file CandidateLW.java.
References denoptim.graph.CandidateLW.generatingSource.
Referenced by denoptim.io.DenoptimIO.readLightWeightCandidate().
setGeneration()
void denoptim.graph.CandidateLW.setGeneration (int genId)
Definition at line 140 of file CandidateLW.java.
References denoptim.graph.CandidateLW.generationId.
Referenced by denoptim.gui.GUIInspectGARun.readOneGeneration().
setLevel()
void denoptim.graph.CandidateLW.setLevel (int lev)
Sets level that generated this graph in a fragment space exploration experiment.
Parameters
lev the level index
Definition at line 173 of file CandidateLW.java.
References denoptim.graph.CandidateLW.level.
Referenced by denoptim.io.DenoptimIO.readLightWeightCandidate().
Member Data Documentation
error
String denoptim.graph.CandidateLW.error private
Error that prevented calculation of the fitness or null.
Definition at line 56 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.getError(), and denoptim.graph.CandidateLW.setError().
fitness
Double denoptim.graph.CandidateLW.fitness private
fThe fitness value or null;
Definition at line 51 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.getFitness(), denoptim.graph.CandidateLW.hasFitness(), and denoptim.graph.CandidateLW.setFitness().
generatingSource
String denoptim.graph.CandidateLW.generatingSource private
A statement defining how this item was generated.
Definition at line 71 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.getGeneratingSource(), and denoptim.graph.CandidateLW.setGeneratingSource().
generationId
Integer denoptim.graph.CandidateLW.generationId private
ID of the generation this molecule belong to (or null)
Definition at line 61 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.getGeneration(), and denoptim.graph.CandidateLW.setGeneration().
level
Integer denoptim.graph.CandidateLW.level private
Level that generated this graph in fragment space exploration (or null)
Definition at line 66 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.getLevel(), and denoptim.graph.CandidateLW.setLevel().
name
String denoptim.graph.CandidateLW.name private
Name of this candidate (not guaranteed to be unique).
Definition at line 41 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.CandidateLW(), denoptim.graph.CandidateLW.equals(), and denoptim.graph.CandidateLW.getName().
pathNameToFile
String denoptim.graph.CandidateLW.pathNameToFile private
Pathname to file defining this item in detail.
Definition at line 46 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.CandidateLW(), and denoptim.graph.CandidateLW.getPathToFile().
uid
String denoptim.graph.CandidateLW.uid private
Unique identifier of this candidate.
Definition at line 36 of file CandidateLW.java.
Referenced by denoptim.graph.CandidateLW.CandidateLW(), denoptim.graph.CandidateLW.equals(), and denoptim.graph.CandidateLW.getUid().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/CandidateLW.java