DENOPTIM: denoptim.utils.CartesianSpaceUtils Class Reference
denoptim.utils.CartesianSpaceUtils Class Reference
Utilities for working in the Cartesian space.
Static Public Member Functions
static void translateOrigin (Vector3d v, Point3d newOrigin)
Changes the origin of a vector.
static Vector3d getVectorFromTo (Point3d a, Point3d b)
Creates an object Vector3d that originates from point a and goes to point b.
static Vector3d getSumOfVector (Vector3d A, Vector3d B)
Get sum of vector A and B.
static Vector3d getDiffOfVector (Vector3d A, Vector3d B)
Calculates the vector difference of vectors A and B.
static Vector3d getNormalDirection (Vector3d dir)
Generate a vector that is perpendicular to the given one.
static void rotatedVectorWAxisAngle (Vector3d v, Vector3d axis, double ang)
Rotate a vector according to a given rotation axis and angle.
Detailed Description
Utilities for working in the Cartesian space.
Author
Marco Foscato
Definition at line 15 of file CartesianSpaceUtils.java.
Member Function Documentation
getDiffOfVector()
static Vector3d denoptim.utils.CartesianSpaceUtils.getDiffOfVector (Vector3d A, Vector3d B) static
Calculates the vector difference of vectors A and B.
Parameters
A vector A
B vector B
Returns
the vector difference
Definition at line 71 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
getNormalDirection()
static Vector3d denoptim.utils.CartesianSpaceUtils.getNormalDirection (Vector3d dir) static
Generate a vector that is perpendicular to the given one.
No control over which perpendicular direction will be chosen.
Parameters
dir input direction
Returns
a perpendicular/normal direction
Definition at line 84 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
getSumOfVector()
static Vector3d denoptim.utils.CartesianSpaceUtils.getSumOfVector (Vector3d A, Vector3d B) static
Get sum of vector A and B.
Parameters
A vector A
B vector B
Returns
the vector sum
Definition at line 58 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
getVectorFromTo()
static Vector3d denoptim.utils.CartesianSpaceUtils.getVectorFromTo (Point3d a, Point3d b) static
Creates an object Vector3d that originates from point a and goes to point b.
Parameters
a starting point
b termination point
Returns
the vector that goes from a to b
Definition at line 41 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
rotatedVectorWAxisAngle()
static void denoptim.utils.CartesianSpaceUtils.rotatedVectorWAxisAngle (Vector3d v, Vector3d axis, double ang) static
Rotate a vector according to a given rotation axis and angle.
Parameters
v original vector to be rotated
axis rotation axis
ang rotation angle
Definition at line 137 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
translateOrigin()
static void denoptim.utils.CartesianSpaceUtils.translateOrigin (Vector3d v, Point3d newOrigin) static
Changes the origin of a vector.
Parameters
v the original vector.
newOrigin the new origin as a point in Cartesian space
Definition at line 25 of file CartesianSpaceUtils.java.
Referenced by denoptim.utils.DummyAtomHandler.getDummyInSafeDirection().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/utils/CartesianSpaceUtils.java