DENOPTIM: denoptim.molecularmodeling.ChemicalObjectModelTest Class Reference
denoptim.molecularmodeling.ChemicalObjectModelTest Class Reference
Unit test for ChemicalObjectModel.
Public Member Functions
void testUpdateXYZFromINT_FirstAtomAtOrigin () throws Exception
void testUpdateXYZFromINT_SecondAtomAlongZAxis () throws Exception
void testUpdateXYZFromINT_ThirdAtomWithAngle () throws Exception
void testUpdateXYZFromINT_FourthAtomWithDihedral () throws Exception
void testUpdateXYZFromINT_ChiralityOne () throws Exception
void testUpdateXYZFromINT_ChiralityMinusOne () throws Exception
void testUpdateXYZFromINT () throws Exception
Private Attributes
Logger logger = Logger.getLogger("TestLogger")
Detailed Description
Unit test for ChemicalObjectModel.
Author
Marco Foscato
Definition at line 47 of file ChemicalObjectModelTest.java.
Member Function Documentation
testUpdateXYZFromINT()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT () throws Exception
Definition at line 336 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.constants.DENOPTIMConstants.FLOATCOMPARISONTOLERANCE, denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_ChiralityMinusOne()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityMinusOne () throws Exception
Definition at line 289 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_ChiralityOne()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityOne () throws Exception
Definition at line 239 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_FirstAtomAtOrigin()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FirstAtomAtOrigin () throws Exception
Definition at line 54 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_FourthAtomWithDihedral()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FourthAtomWithDihedral () throws Exception
Definition at line 183 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_SecondAtomAlongZAxis()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_SecondAtomAlongZAxis () throws Exception
Definition at line 85 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
testUpdateXYZFromINT_ThirdAtomWithAngle()
void denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ThirdAtomWithAngle () throws Exception
Definition at line 127 of file ChemicalObjectModelTest.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addAtom(), denoptim.molecularmodeling.ChemicalObjectModelTest.logger, and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
Member Data Documentation
logger
Logger denoptim.molecularmodeling.ChemicalObjectModelTest.logger = Logger.getLogger("TestLogger") private
Definition at line 49 of file ChemicalObjectModelTest.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityMinusOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FirstAtomAtOrigin(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FourthAtomWithDihedral(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_SecondAtomAlongZAxis(), and denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ThirdAtomWithAngle().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/molecularmodeling/ChemicalObjectModelTest.java