DENOPTIM: denoptim.gui.GUIModalDialog Class Reference
denoptim.gui.GUIModalDialog Class Reference
Public Member Functions
GUIModalDialog (Component refForPlacement)
Constructor.
GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Object showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
void addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
void addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Protected Member Functions
void close ()
Closes the dialog window.
Protected Attributes
JButton btnDone
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
JButton btnCanc
The button that is used to close the dialog without processing any input.
JButton btnExtra
The button that can be used for any action that does not close the dialog.
Object result = null
The result to be returned once the dialog is closed.
Private Member Functions
void initialize (boolean useExtraButton)
Private Attributes
JPanel pnlControls
Static Private Attributes
static final long serialVersionUID = 8562693062507200623L
Version UID.
Detailed Description
Definition at line 34 of file GUIModalDialog.java.
Constructor & Destructor Documentation
GUIModalDialog() [1/2]
denoptim.gui.GUIModalDialog.GUIModalDialog (Component refForPlacement)
Constructor.
Parameters
refForPlacement a component close to which the dialog window should be opened.
Definition at line 74 of file GUIModalDialog.java.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton().
GUIModalDialog() [2/2]
denoptim.gui.GUIModalDialog.GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Parameters
refForPlacement a component close to which the dialog window should be opened.
useExtraButton use true to make a dialog with three buttons, which you can edit afterwards.
Definition at line 88 of file GUIModalDialog.java.
References denoptim.gui.GUIModalDialog.initialize().
Member Function Documentation
addToCentralPane()
void denoptim.gui.GUIModalDialog.addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Parameters
comp the component to be added.
Definition at line 166 of file GUIModalDialog.java.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.FSParamsDialog.FSParamsDialog(), denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton().
addToNorthPane()
void denoptim.gui.GUIModalDialog.addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
Parameters
comp the component to be added.
Definition at line 155 of file GUIModalDialog.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
close()
void denoptim.gui.GUIModalDialog.close () protected
Closes the dialog window.
Definition at line 176 of file GUIModalDialog.java.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.FSParamsDialog.FSParamsDialog(), denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.gui.GUIPreferencesDialog.GUIPreferencesDialog(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.GUIModalDialog.initialize().
initialize()
void denoptim.gui.GUIModalDialog.initialize (boolean useExtraButton) private
Definition at line 98 of file GUIModalDialog.java.
References denoptim.gui.GUIModalDialog.btnCanc, denoptim.gui.GUIModalDialog.btnDone, denoptim.gui.GUIModalDialog.btnExtra, denoptim.gui.GUIModalDialog.close(), denoptim.gui.GUIModalDialog.pnlControls, and denoptim.gui.GUIModalDialog.result.
Referenced by denoptim.gui.GUIModalDialog.GUIModalDialog().
showDialog()
Object denoptim.gui.GUIModalDialog.showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
Definition at line 142 of file GUIModalDialog.java.
References denoptim.gui.GUIModalDialog.result.
Referenced by denoptim.gui.GUIVertexInspector.choseOrCreateNewAPClass(), denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.gui.FitnessParametersForm.FitnessParametersForm(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIInspectGARun.initialize(), denoptim.gui.GUIVertexInspector.initialize(), denoptim.gui.GUIVertexInspector.saveUnsavedChanges(), denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
Member Data Documentation
btnCanc
JButton denoptim.gui.GUIModalDialog.btnCanc protected
The button that is used to close the dialog without processing any input.
Definition at line 52 of file GUIModalDialog.java.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.FSParamsDialog.FSParamsDialog(), denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.gui.GUIPreferencesDialog.GUIPreferencesDialog(), denoptim.gui.GUIModalDialog.initialize(), and denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton().
btnDone
JButton denoptim.gui.GUIModalDialog.btnDone protected
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
Definition at line 46 of file GUIModalDialog.java.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.FSParamsDialog.FSParamsDialog(), denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.gui.GUIPreferencesDialog.GUIPreferencesDialog(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.gui.GUIModalDialog.initialize().
btnExtra
JButton denoptim.gui.GUIModalDialog.btnExtra protected
The button that can be used for any action that does not close the dialog.
Definition at line 58 of file GUIModalDialog.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector(), denoptim.gui.GUIModalDialog.initialize(), and denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton().
pnlControls
JPanel denoptim.gui.GUIModalDialog.pnlControls private
Definition at line 60 of file GUIModalDialog.java.
Referenced by denoptim.gui.GUIModalDialog.initialize().
result
Object denoptim.gui.GUIModalDialog.result = null protected
The result to be returned once the dialog is closed.
Definition at line 65 of file GUIModalDialog.java.
Referenced by denoptim.gui.GUIVertexSelector.appendToResult(), denoptim.gui.GUIVertexInspector.dialogToDefineCuttingRules(), denoptim.gui.FitnessParametersForm.FitnessParametersForm(), denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), denoptim.gui.GUIEmptyVertexMaker.GUIEmptyVertexMaker(), denoptim.gui.GUIModalDialog.initialize(), denoptim.gui.CuttingRulesSelectionDialog.saveResults(), and denoptim.gui.GUIModalDialog.showDialog().
serialVersionUID
final long denoptim.gui.GUIModalDialog.serialVersionUID = 8562693062507200623L static private
Version UID.
Definition at line 40 of file GUIModalDialog.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIModalDialog.java