DENOPTIM: denoptim.graph.rings.RingClosuresArchive Class Reference
denoptim.graph.rings.RingClosuresArchive Class Reference
Data structure to store and handle information about sub-structures (i.e., chains of fragments) and ring closure capability.
Public Member Functions
RingClosuresArchive ()
Construct an empty archive.
RingClosuresArchive (RingClosureParameters settings) throws DENOPTIMException
Construct the library of ring closing substructures from an existing index file.
void storeEntry (String chainId, boolean closable, RingClosingConformations rcc)
Append a new closable chain entry to the archive.
ArrayList< ClosableChain > getCCFromTurningPointId (int tpId)
Returns the library of closable chains having the given turning point (i.e., the fragments involved in the ring that has lower level).
String containsChain (PathSubGraph chain)
boolean getClosabilityOfChain (String chainId)
RingClosingConformations getRCCsOfChain (String chainId)
RingClosingConformations getRCCsFromArchive (int rccId)
Get serialized RingClosingConformations from archive.
Private Member Functions
void readLibraryOfRCCs (String filename) throws DENOPTIMException
void addRecord (String chainId, String rccIdNum, String closability) throws DENOPTIMException
Private Attributes
int nextRccId = 0
Index of the next entry to be added to the archive.
HashMap< String, ArrayList< String > > rccsPerChainId
Data structure containing the main information about the RingClosingConformations (values) per each ClosableChain (keys).
HashMap< Integer, ArrayList< ClosableChain > > libCCxTPIdx
Data structure containing the library of ClosableChains per each fragment that can act as a turning point fragment (TP; i.e., the fragments involved in the ring that has lower level in the DENOPTIMGraph).
RingClosureParameters settings
Parameters.
Detailed Description
Data structure to store and handle information about sub-structures (i.e., chains of fragments) and ring closure capability.
Author
Marco Foscato
Definition at line 48 of file RingClosuresArchive.java.
Constructor & Destructor Documentation
RingClosuresArchive() [1/2]
denoptim.graph.rings.RingClosuresArchive.RingClosuresArchive ()
Construct an empty archive.
Definition at line 88 of file RingClosuresArchive.java.
RingClosuresArchive() [2/2]
denoptim.graph.rings.RingClosuresArchive.RingClosuresArchive (RingClosureParameters settings) throws DENOPTIMException
Construct the library of ring closing substructures from an existing index file.
Parameters
rccIndex the index file.
Definition at line 98 of file RingClosuresArchive.java.
References denoptim.files.FileUtils.checkExists(), denoptim.graph.rings.RingClosureParameters.getRCCLibraryIndexFile(), denoptim.graph.rings.RingClosuresArchive.readLibraryOfRCCs(), and denoptim.graph.rings.RingClosuresArchive.settings.
Member Function Documentation
addRecord()
void denoptim.graph.rings.RingClosuresArchive.addRecord (String chainId, String rccIdNum, String closability) throws DENOPTIMException private
Definition at line 173 of file RingClosuresArchive.java.
References denoptim.graph.rings.ClosableChain.getTurningPointIdx(), denoptim.graph.rings.RingClosuresArchive.libCCxTPIdx, denoptim.graph.rings.RingClosuresArchive.nextRccId, and denoptim.graph.rings.RingClosuresArchive.rccsPerChainId.
Referenced by denoptim.graph.rings.RingClosuresArchive.readLibraryOfRCCs(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
containsChain()
String denoptim.graph.rings.RingClosuresArchive.containsChain (PathSubGraph chain)
Parameters
chain the candidate chain
Returns
the already visited chainId that correspond to the same chain of fragments of chain, otherwise an empty string is returned.
Definition at line 360 of file RingClosuresArchive.java.
References denoptim.graph.rings.PathSubGraph.getAllAlternativeChainIDs(), and denoptim.graph.rings.RingClosuresArchive.rccsPerChainId.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
getCCFromTurningPointId()
ArrayList< ClosableChain > denoptim.graph.rings.RingClosuresArchive.getCCFromTurningPointId (int tpId)
Returns the library of closable chains having the given turning point (i.e., the fragments involved in the ring that has lower level).
Parameters
tpId the turning point molecule Id in the libraries.
Definition at line 342 of file RingClosuresArchive.java.
References denoptim.graph.rings.RingClosuresArchive.libCCxTPIdx.
Referenced by denoptim.ga.EAUtils.buildGraph().
getClosabilityOfChain()
boolean denoptim.graph.rings.RingClosuresArchive.getClosabilityOfChain (String chainId)
Returns
the closability of a chain
Definition at line 380 of file RingClosuresArchive.java.
References denoptim.graph.rings.RingClosuresArchive.rccsPerChainId.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
getRCCsFromArchive()
RingClosingConformations denoptim.graph.rings.RingClosuresArchive.getRCCsFromArchive (int rccId)
Get serialized RingClosingConformations from archive.
Parameters
rccId the index identifying the RingClosingConformations in the archive
Definition at line 429 of file RingClosuresArchive.java.
References denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.rings.RingClosureParameters.getRCCLibraryFolder(), and denoptim.graph.rings.RingClosuresArchive.settings.
Referenced by denoptim.graph.rings.RingClosuresArchive.getRCCsOfChain().
getRCCsOfChain()
RingClosingConformations denoptim.graph.rings.RingClosuresArchive.getRCCsOfChain (String chainId)
Returns
the RingClosingConformations of a chain as stored in the archive
Definition at line 394 of file RingClosuresArchive.java.
References denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.rings.RingClosuresArchive.getRCCsFromArchive(), denoptim.graph.rings.RingClosureParameters.getVerbosity(), denoptim.graph.rings.RingClosuresArchive.rccsPerChainId, and denoptim.graph.rings.RingClosuresArchive.settings.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
readLibraryOfRCCs()
void denoptim.graph.rings.RingClosuresArchive.readLibraryOfRCCs (String filename) throws DENOPTIMException private
Definition at line 108 of file RingClosuresArchive.java.
References denoptim.graph.rings.RingClosuresArchive.addRecord(), denoptim.graph.rings.RingClosuresArchive.nextRccId, and denoptim.graph.rings.RingClosuresArchive.rccsPerChainId.
Referenced by denoptim.graph.rings.RingClosuresArchive.RingClosuresArchive().
storeEntry()
void denoptim.graph.rings.RingClosuresArchive.storeEntry (String chainId, boolean closable, RingClosingConformations rcc)
Append a new closable chain entry to the archive.
Parameters
chainId the string representing the chain of fragments
closable true for verified closable chains
rcc the ensemble of RingClosingConformations of the chain
Definition at line 218 of file RingClosuresArchive.java.
References denoptim.graph.rings.RingClosuresArchive.addRecord(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.rings.RingClosureParameters.getRCCLibraryFolder(), denoptim.graph.rings.RingClosureParameters.getRCCLibraryIndexFile(), denoptim.graph.rings.RingClosuresArchive.nextRccId, denoptim.graph.rings.RingClosuresArchive.rccsPerChainId, denoptim.graph.rings.RingClosureParameters.serializeRCCs, and denoptim.graph.rings.RingClosuresArchive.settings.
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
Member Data Documentation
libCCxTPIdx
HashMap<Integer,ArrayList<ClosableChain> > denoptim.graph.rings.RingClosuresArchive.libCCxTPIdx private
Initial value:
=
                                                             new HashMap<>()
Data structure containing the library of ClosableChains per each fragment that can act as a turning point fragment (TP; i.e., the fragments involved in the ring that has lower level in the DENOPTIMGraph).
The possible TPs are
identified by the molecular fragment Id in the proper library of fragments.
Definition at line 75 of file RingClosuresArchive.java.
Referenced by denoptim.graph.rings.RingClosuresArchive.addRecord(), and denoptim.graph.rings.RingClosuresArchive.getCCFromTurningPointId().
nextRccId
int denoptim.graph.rings.RingClosuresArchive.nextRccId = 0 private
Index of the next entry to be added to the archive.
Definition at line 53 of file RingClosuresArchive.java.
Referenced by denoptim.graph.rings.RingClosuresArchive.addRecord(), denoptim.graph.rings.RingClosuresArchive.readLibraryOfRCCs(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
rccsPerChainId
HashMap<String,ArrayList<String> > denoptim.graph.rings.RingClosuresArchive.rccsPerChainId private
Initial value:
=
                                 new HashMap<>()
Data structure containing the main information about the RingClosingConformations (values) per each ClosableChain (keys).
Each value identifies (i) a unique Id that permits to retrieve the list ring-closing conformations from the archive of serialized objects, and (ii) the closability of the chain.
Definition at line 63 of file RingClosuresArchive.java.
Referenced by denoptim.graph.rings.RingClosuresArchive.addRecord(), denoptim.graph.rings.RingClosuresArchive.containsChain(), denoptim.graph.rings.RingClosuresArchive.getClosabilityOfChain(), denoptim.graph.rings.RingClosuresArchive.getRCCsOfChain(), denoptim.graph.rings.RingClosuresArchive.readLibraryOfRCCs(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
settings
RingClosureParameters denoptim.graph.rings.RingClosuresArchive.settings private
Parameters.
Definition at line 81 of file RingClosuresArchive.java.
Referenced by denoptim.graph.rings.RingClosuresArchive.getRCCsFromArchive(), denoptim.graph.rings.RingClosuresArchive.getRCCsOfChain(), denoptim.graph.rings.RingClosuresArchive.RingClosuresArchive(), and denoptim.graph.rings.RingClosuresArchive.storeEntry().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/RingClosuresArchive.java