DENOPTIM: denoptim.io.DenoptimIOTest Class Reference
denoptim.io.DenoptimIOTest Class Reference
Unit test for input/output.
Public Member Functions
void testReadAllAtomContainersFromCIF () throws Exception
void testIOEmptyVertex () throws Exception
void testIOMolFragment () throws Exception
void testIOTemplate () throws Exception
void testReadGenerationFromSummary () throws Exception
void testReadLightWeightCandidate () throws Exception
void testSerializeDeserializeDENOPTIMGraphs () throws Exception
void testReadAllAPClasses () throws Exception
void testAppendToJSON () throws Exception
void testDetectFileFormat () throws Exception
void testReadCuttingRulsedDefault () throws Exception
void testIOCuttingRules () throws Exception
void testReadCSDFormulae () throws Exception
Package Attributes
File tempDir
Private Member Functions
void buildVertexAndConnectToGraph (EmptyVertex v, int apCount, DGraph graph) throws DENOPTIMException
Private Attributes
final String SEP = System.getProperty("file.separator")
final String NL = System.getProperty("line.separator")
Static Private Attributes
static final BondType BT = BondType.SINGLE
Detailed Description
Unit test for input/output.
Author
Marco Foscato
Definition at line 80 of file DenoptimIOTest.java.
Member Function Documentation
buildVertexAndConnectToGraph()
void denoptim.io.DenoptimIOTest.buildVertexAndConnectToGraph (EmptyVertex v, int apCount, DGraph graph) throws DENOPTIMException private
Definition at line 524 of file DenoptimIOTest.java.
Referenced by denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
testAppendToJSON()
void denoptim.io.DenoptimIOTest.testAppendToJSON () throws Exception
Definition at line 474 of file DenoptimIOTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.getAtom(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.files.FileFormat.VRTXJSON, and denoptim.io.DenoptimIO.writeVertexesToFile().
testDetectFileFormat()
void denoptim.io.DenoptimIOTest.testDetectFileFormat () throws Exception
Definition at line 536 of file DenoptimIOTest.java.
References denoptim.constants.DENOPTIMConstants.APSTAG, denoptim.programs.RunTimeParameters.ParametersType.CEBL_PARAMS, denoptim.files.FileFormat.COMP_MAP, denoptim.files.FileUtils.createDirectory(), denoptim.files.FileUtils.detectFileFormat(), denoptim.files.FileFormat.FSE_PARAM, denoptim.files.FileFormat.FSE_RUN, denoptim.constants.DENOPTIMConstants.FSEIDXNAMEROOT, denoptim.files.FileFormat.GA_PARAM, denoptim.programs.RunTimeParameters.ParametersType.GA_PARAMS, denoptim.files.FileFormat.GA_RUN, denoptim.constants.DENOPTIMConstants.GAGENDIRNAMEROOT, denoptim.constants.DENOPTIMConstants.GAGENSUMMARYHEADER, denoptim.files.FileFormat.GENSUMMARY, denoptim.constants.DENOPTIMConstants.GRAPHJSONTAG, denoptim.files.FileFormat.GRAPHSDF, denoptim.io.DenoptimIOTest.NL, denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.constants.DENOPTIMConstants.VERTEXJSONTAG, denoptim.files.FileFormat.VRTXSDF, and denoptim.io.DenoptimIO.writeData().
testIOCuttingRules()
void denoptim.io.DenoptimIOTest.testIOCuttingRules () throws Exception
Definition at line 629 of file DenoptimIOTest.java.
References denoptim.io.DenoptimIO.readCuttingRules(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, and denoptim.io.DenoptimIO.writeCuttingRules().
testIOEmptyVertex()
void denoptim.io.DenoptimIOTest.testIOEmptyVertex () throws Exception
Definition at line 137 of file DenoptimIOTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.APClass.make(), denoptim.io.DenoptimIO.readVertexes(), denoptim.graph.EmptyVertex.sameAs(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.graph.Vertex.BBType.UNDEFINED, denoptim.files.FileFormat.VRTXJSON, denoptim.files.FileFormat.VRTXSDF, and denoptim.io.DenoptimIO.writeVertexesToFile().
testIOMolFragment()
void denoptim.io.DenoptimIOTest.testIOMolFragment () throws Exception
Definition at line 171 of file DenoptimIOTest.java.
References denoptim.graph.FragmentTest.makeFragment(), denoptim.io.DenoptimIO.readVertexes(), denoptim.graph.Fragment.sameAs(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.files.FileFormat.VRTXJSON, denoptim.files.FileFormat.VRTXSDF, and denoptim.io.DenoptimIO.writeVertexesToFile().
testIOTemplate()
void denoptim.io.DenoptimIOTest.testIOTemplate () throws Exception
Definition at line 201 of file DenoptimIOTest.java.
References denoptim.graph.TemplateTest.getTestAmideTemplate(), denoptim.io.DenoptimIO.readVertexes(), denoptim.graph.Template.sameAs(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.graph.Vertex.BBType.UNDEFINED, denoptim.files.FileFormat.VRTXJSON, denoptim.files.FileFormat.VRTXSDF, and denoptim.io.DenoptimIO.writeVertexesToFile().
testReadAllAPClasses()
void denoptim.io.DenoptimIOTest.testReadAllAPClasses () throws Exception
Definition at line 419 of file DenoptimIOTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.files.FileUtils.getTempFolder(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.io.DenoptimIO.readAllAPClasses(), and denoptim.io.DenoptimIO.writeVertexesToSDF().
testReadAllAtomContainersFromCIF()
void denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF () throws Exception
Definition at line 94 of file DenoptimIOTest.java.
References denoptim.io.DenoptimIOTest.NL, denoptim.io.DenoptimIO.readAllAtomContainers(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, and denoptim.io.DenoptimIO.writeData().
testReadCSDFormulae()
void denoptim.io.DenoptimIOTest.testReadCSDFormulae () throws Exception
Definition at line 653 of file DenoptimIOTest.java.
References denoptim.io.DenoptimIOTest.NL, denoptim.io.DenoptimIO.readCSDFormulae(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, and denoptim.io.DenoptimIO.writeData().
testReadCuttingRulsedDefault()
void denoptim.io.DenoptimIOTest.testReadCuttingRulsedDefault () throws Exception
Definition at line 609 of file DenoptimIOTest.java.
References denoptim.io.DenoptimIO.readCuttingRules().
testReadGenerationFromSummary()
void denoptim.io.DenoptimIOTest.testReadGenerationFromSummary () throws Exception
Definition at line 231 of file DenoptimIOTest.java.
References denoptim.ga.Population.add(), denoptim.files.FileUtils.createDirectory(), denoptim.graph.Candidate.getGraph(), denoptim.ga.EAUtils.getPathNameToGenerationDetailsFile(), denoptim.ga.EAUtils.getPathNameToGenerationFolder(), denoptim.ga.EAUtils.outputPopulationDetails(), denoptim.io.DenoptimIO.readGenerationFromSummary(), denoptim.io.DenoptimIOTest.SEP, denoptim.graph.Candidate.setFitness(), denoptim.graph.DGraph.setGraphId(), denoptim.programs.RunTimeParameters.setParameters(), denoptim.programs.denovo.GAParameters.setPopulationSize(), denoptim.graph.Candidate.setSDFFile(), denoptim.graph.Candidate.setUID(), denoptim.programs.denovo.GAParameters.setWorkingDirectory(), denoptim.io.DenoptimIOTest.tempDir, and denoptim.io.DenoptimIO.writeCandidateToFile().
testReadLightWeightCandidate()
void denoptim.io.DenoptimIOTest.testReadLightWeightCandidate () throws Exception
Definition at line 296 of file DenoptimIOTest.java.
References denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.constants.DENOPTIMConstants.GRAPHLEVELTAG, denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.io.DenoptimIO.readLightWeightCandidate(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.constants.DENOPTIMConstants.UNIQUEIDTAG, and denoptim.io.DenoptimIO.writeSDFFile().
testSerializeDeserializeDENOPTIMGraphs()
void denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs () throws Exception
Definition at line 353 of file DenoptimIOTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.io.DenoptimIOTest.BT, denoptim.io.DenoptimIOTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), denoptim.graph.DGraph.sameAs(), denoptim.io.DenoptimIOTest.SEP, denoptim.io.DenoptimIOTest.tempDir, denoptim.graph.DGraph.toJson(), and denoptim.io.DenoptimIO.writeData().
Member Data Documentation
BT
final BondType denoptim.io.DenoptimIOTest.BT = BondType.SINGLE static private
Definition at line 83 of file DenoptimIOTest.java.
Referenced by denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
NL
final String denoptim.io.DenoptimIOTest.NL = System.getProperty("line.separator") private
Definition at line 86 of file DenoptimIOTest.java.
Referenced by denoptim.io.DenoptimIOTest.testDetectFileFormat(), denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF(), and denoptim.io.DenoptimIOTest.testReadCSDFormulae().
SEP
final String denoptim.io.DenoptimIOTest.SEP = System.getProperty("file.separator") private
Definition at line 85 of file DenoptimIOTest.java.
Referenced by denoptim.io.DenoptimIOTest.testAppendToJSON(), denoptim.io.DenoptimIOTest.testDetectFileFormat(), denoptim.io.DenoptimIOTest.testIOCuttingRules(), denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.io.DenoptimIOTest.testIOMolFragment(), denoptim.io.DenoptimIOTest.testIOTemplate(), denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF(), denoptim.io.DenoptimIOTest.testReadCSDFormulae(), denoptim.io.DenoptimIOTest.testReadGenerationFromSummary(), denoptim.io.DenoptimIOTest.testReadLightWeightCandidate(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
tempDir
File denoptim.io.DenoptimIOTest.tempDir package
Definition at line 89 of file DenoptimIOTest.java.
Referenced by denoptim.io.DenoptimIOTest.testAppendToJSON(), denoptim.io.DenoptimIOTest.testDetectFileFormat(), denoptim.io.DenoptimIOTest.testIOCuttingRules(), denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.io.DenoptimIOTest.testIOMolFragment(), denoptim.io.DenoptimIOTest.testIOTemplate(), denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF(), denoptim.io.DenoptimIOTest.testReadCSDFormulae(), denoptim.io.DenoptimIOTest.testReadGenerationFromSummary(), denoptim.io.DenoptimIOTest.testReadLightWeightCandidate(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/io/DenoptimIOTest.java