DENOPTIM: denoptim.graph.EdgeTest Class Reference
denoptim.graph.EdgeTest Class Reference
Unit test for DENOPTIMEdge.
Public Member Functions
void setUpClass ()
void testUndirectedComparison () throws Exception
void testConnectionDeconnectionLoop () throws Exception
void testSameAs_Equal () throws Exception
void testSameAs_DiffBndTyp () throws Exception
Private Attributes
EmptyVertex dummyVertexA
EmptyVertex dummyVertexB
StringBuilder reason = new StringBuilder()
AttachmentPoint dummyApA1
AttachmentPoint dummyApA2
AttachmentPoint dummyApB
Detailed Description
Unit test for DENOPTIMEdge.
Author
Marco Foscato
Definition at line 38 of file EdgeTest.java.
Member Function Documentation
setUpClass()
void denoptim.graph.EdgeTest.setUpClass ()
Definition at line 49 of file EdgeTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EdgeTest.dummyApA1, denoptim.graph.EdgeTest.dummyApA2, denoptim.graph.EdgeTest.dummyApB, denoptim.graph.EdgeTest.dummyVertexA, denoptim.graph.EdgeTest.dummyVertexB, and denoptim.graph.Vertex.getAP().
testConnectionDeconnectionLoop()
void denoptim.graph.EdgeTest.testConnectionDeconnectionLoop () throws Exception
Definition at line 225 of file EdgeTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.EdgeTest.dummyApA1, denoptim.graph.EdgeTest.dummyApB, denoptim.graph.EdgeTest.dummyVertexA, denoptim.graph.EdgeTest.dummyVertexB, denoptim.graph.AttachmentPoint.getEdgeUser(), denoptim.graph.Edge.getSrcAP(), denoptim.graph.Edge.getTrgAP(), denoptim.graph.Edge.BondType.NONE, and denoptim.graph.DGraph.removeEdge().
testSameAs_DiffBndTyp()
void denoptim.graph.EdgeTest.testSameAs_DiffBndTyp () throws Exception
Definition at line 264 of file EdgeTest.java.
References denoptim.graph.Edge.BondType.DOUBLE, denoptim.graph.EdgeTest.dummyApA1, denoptim.graph.EdgeTest.dummyApA2, denoptim.graph.EdgeTest.reason, denoptim.graph.Edge.sameAs(), and denoptim.graph.Edge.BondType.SINGLE.
testSameAs_Equal()
void denoptim.graph.EdgeTest.testSameAs_Equal () throws Exception
Definition at line 251 of file EdgeTest.java.
References denoptim.graph.EdgeTest.dummyApA1, denoptim.graph.EdgeTest.dummyApA2, denoptim.graph.EdgeTest.reason, denoptim.graph.Edge.sameAs(), and denoptim.graph.Edge.BondType.UNDEFINED.
testUndirectedComparison()
void denoptim.graph.EdgeTest.testUndirectedComparison () throws Exception
Definition at line 64 of file EdgeTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Edge.compareAsUndirected(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockId(), denoptim.graph.Vertex.setBuildingBlockType(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.graph.Edge.BondType.UNDEFINED.
Member Data Documentation
dummyApA1
AttachmentPoint denoptim.graph.EdgeTest.dummyApA1 private
Definition at line 42 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.setUpClass(), denoptim.graph.EdgeTest.testConnectionDeconnectionLoop(), denoptim.graph.EdgeTest.testSameAs_DiffBndTyp(), and denoptim.graph.EdgeTest.testSameAs_Equal().
dummyApA2
AttachmentPoint denoptim.graph.EdgeTest.dummyApA2 private
Definition at line 43 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.setUpClass(), denoptim.graph.EdgeTest.testSameAs_DiffBndTyp(), and denoptim.graph.EdgeTest.testSameAs_Equal().
dummyApB
AttachmentPoint denoptim.graph.EdgeTest.dummyApB private
Definition at line 44 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.setUpClass(), and denoptim.graph.EdgeTest.testConnectionDeconnectionLoop().
dummyVertexA
EmptyVertex denoptim.graph.EdgeTest.dummyVertexA private
Definition at line 39 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.setUpClass(), and denoptim.graph.EdgeTest.testConnectionDeconnectionLoop().
dummyVertexB
EmptyVertex denoptim.graph.EdgeTest.dummyVertexB private
Definition at line 40 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.setUpClass(), and denoptim.graph.EdgeTest.testConnectionDeconnectionLoop().
reason
StringBuilder denoptim.graph.EdgeTest.reason = new StringBuilder() private
Definition at line 41 of file EdgeTest.java.
Referenced by denoptim.graph.EdgeTest.testSameAs_DiffBndTyp(), and denoptim.graph.EdgeTest.testSameAs_Equal().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/EdgeTest.java