DENOPTIM: denoptim.graph.SymmetricSet< T > Class Template Reference
denoptim.graph.SymmetricSet< T > Class Template Reference
Class representing a list of references pointing to instances that are related by some conventional criterion that is referred to as "symmetry relation".
Public Member Functions
boolean add (T item)
Adds an item to this list, if not already present.
Static Private Attributes
static final long serialVersionUID = 4L
Version ID.
Detailed Description
Class representing a list of references pointing to instances that are related by some conventional criterion that is referred to as "symmetry relation".
Note that the actual criterion that defined a "symmetry" relation is not defined here. So, this list does not know what is the criterion that puts its entries in relation with each other. Moreover, the list does not know what the entries are.
Author
Marco Foscato
Definition at line 39 of file SymmetricSet.java.
Member Function Documentation
add()
boolean denoptim.graph.SymmetricSet< T >.add (T item)
Adds an item to this list, if not already present.
Parameters
item the item to add.
Returns
as for Collection#add(Object)
Definition at line 55 of file SymmetricSet.java.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.DGraph.clone(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.detectSymVertexSets(), denoptim.ga.GraphOperations.extendGraph(), denoptim.utils.GraphConversionTool.getGraphFromString(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.Fragment.identifySymmetryRelatedAPSets(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.FragmentTest.makeFragment(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraphTest.testClone(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_SameSymmSet(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
Member Data Documentation
serialVersionUID
final long denoptim.graph.SymmetricSet< T >.serialVersionUID = 4L static private
Version ID.
Definition at line 45 of file SymmetricSet.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/SymmetricSet.java