DENOPTIM: denoptim.graph.rings.ChainLink Class Reference
denoptim.graph.rings.ChainLink Class Reference
ChainLink represents a vertex in a closable chain.
Public Member Functions
ChainLink ()
Constructs an empty ChainLink.
ChainLink (int molID, Vertex.BBType ftype, int apLeft, int apRight)
Constructs a ChainLink from the involved points.
int getIdx ()
Vertex.BBType getFragType ()
int getApIdToLeft ()
int getApIdToRight ()
ChainLink clone ()
Returns a deep-clone.
String toString ()
Private Attributes
int idx
Fragment ID in library.
Vertex.BBType ftype
Fragment type.
int apLeft
Index of AP towards left.
int apRight
Index of AP towards right.
Detailed Description
ChainLink represents a vertex in a closable chain.
This data structure stores information as to the corresponding molecule ID in the library of fragments, the type of fragment and the identify of the AP linking to the chain link before and after
Author
Marco Foscato
Definition at line 32 of file ChainLink.java.
Constructor & Destructor Documentation
ChainLink() [1/2]
denoptim.graph.rings.ChainLink.ChainLink ()
Constructs an empty ChainLink.
Definition at line 61 of file ChainLink.java.
Referenced by denoptim.graph.rings.ChainLink.clone().
ChainLink() [2/2]
denoptim.graph.rings.ChainLink.ChainLink (int molID, Vertex.BBType ftype, int apLeft, int apRight)
Constructs a ChainLink from the involved points.
Definition at line 71 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.apLeft, denoptim.graph.rings.ChainLink.apRight, and denoptim.graph.rings.ChainLink.ftype.
Member Function Documentation
clone()
ChainLink denoptim.graph.rings.ChainLink.clone ()
Returns a deep-clone.
Returns
a deep-clone
Definition at line 131 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.apLeft, denoptim.graph.rings.ChainLink.apRight, denoptim.graph.rings.ChainLink.ChainLink(), denoptim.graph.rings.ChainLink.ftype, and denoptim.graph.rings.ChainLink.idx.
getApIdToLeft()
int denoptim.graph.rings.ChainLink.getApIdToLeft ()
Returns
the index of the attachment point directed to the left side of the chain from this link
Definition at line 108 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.apLeft.
Referenced by denoptim.ga.GraphOperations.getFragmentForClosableChain(), and denoptim.graph.rings.ClosableChain.involvesVertexAndAP().
getApIdToRight()
int denoptim.graph.rings.ChainLink.getApIdToRight ()
Returns
the index of the attachment point directed to the right side of the chain from this link
Definition at line 120 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.apRight.
Referenced by denoptim.ga.GraphOperations.getFragmentForClosableChain(), and denoptim.graph.rings.ClosableChain.involvesVertexAndAP().
getFragType()
Vertex.BBType denoptim.graph.rings.ChainLink.getFragType ()
Returns
the type of fragment library
Definition at line 96 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.ftype.
Referenced by denoptim.ga.GraphOperations.getFragmentForClosableChain(), denoptim.graph.rings.ClosableChain.involvesVertex(), and denoptim.graph.rings.ClosableChain.involvesVertexAndAP().
getIdx()
int denoptim.graph.rings.ChainLink.getIdx ()
Returns
the index of the fragment in the fragment library
Definition at line 85 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.idx.
Referenced by denoptim.ga.GraphOperations.getFragmentForClosableChain(), denoptim.graph.rings.ClosableChain.getTurningPointIdx(), denoptim.graph.rings.ClosableChain.involvesVertex(), and denoptim.graph.rings.ClosableChain.involvesVertexAndAP().
toString()
String denoptim.graph.rings.ChainLink.toString ()
Returns
the string representation of this ChainLink
Definition at line 143 of file ChainLink.java.
References denoptim.graph.rings.ChainLink.apLeft, denoptim.graph.rings.ChainLink.apRight, denoptim.graph.rings.ChainLink.ftype, and denoptim.graph.rings.ChainLink.idx.
Member Data Documentation
apLeft
int denoptim.graph.rings.ChainLink.apLeft private
Index of AP towards left.
Definition at line 47 of file ChainLink.java.
Referenced by denoptim.graph.rings.ChainLink.ChainLink(), denoptim.graph.rings.ChainLink.clone(), denoptim.graph.rings.ChainLink.getApIdToLeft(), and denoptim.graph.rings.ChainLink.toString().
apRight
int denoptim.graph.rings.ChainLink.apRight private
Index of AP towards right.
Definition at line 52 of file ChainLink.java.
Referenced by denoptim.graph.rings.ChainLink.ChainLink(), denoptim.graph.rings.ChainLink.clone(), denoptim.graph.rings.ChainLink.getApIdToRight(), and denoptim.graph.rings.ChainLink.toString().
ftype
Vertex.BBType denoptim.graph.rings.ChainLink.ftype private
Fragment type.
Definition at line 42 of file ChainLink.java.
Referenced by denoptim.graph.rings.ChainLink.ChainLink(), denoptim.graph.rings.ChainLink.clone(), denoptim.graph.rings.ChainLink.getFragType(), and denoptim.graph.rings.ChainLink.toString().
idx
int denoptim.graph.rings.ChainLink.idx private
Fragment ID in library.
Definition at line 37 of file ChainLink.java.
Referenced by denoptim.graph.rings.ChainLink.clone(), denoptim.graph.rings.ChainLink.getIdx(), and denoptim.graph.rings.ChainLink.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/ChainLink.java