DENOPTIM: denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton Class Reference
denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton Class Reference
A button that opens a modal dialog displaying the PNGs with a visual representation of SMARTS queries that are selected in the table given upon construction.
Public Member Functions
SMARTSVisualizationButton (JTable table, DefaultTableModel tabModel)
Private Attributes
Component refToThis
A reference to this very instance.
String templateURL
Detailed Description
A button that opens a modal dialog displaying the PNGs with a visual representation of SMARTS queries that are selected in the table given upon construction.
Definition at line 642 of file CuttingRulesSelectionDialog.java.
Constructor & Destructor Documentation
SMARTSVisualizationButton()
denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.SMARTSVisualizationButton (JTable table, DefaultTableModel tabModel)
Definition at line 658 of file CuttingRulesSelectionDialog.java.
References denoptim.gui.GUIModalDialog.addToCentralPane(), denoptim.gui.GUIModalDialog.btnCanc, denoptim.gui.GUIModalDialog.btnExtra, denoptim.gui.CuttingRulesSelectionDialog.escapeCharactersForSMARTSViewer(), denoptim.gui.GUIModalDialog.GUIModalDialog(), and denoptim.gui.GUIModalDialog.showDialog().
Member Data Documentation
refToThis
Component denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.refToThis private
A reference to this very instance.
Only needed to place child dialogs.
Definition at line 647 of file CuttingRulesSelectionDialog.java.
templateURL
String denoptim.gui.CuttingRulesSelectionDialog.SMARTSVisualizationButton.templateURL private
Initial value:
= "https://smarts.plus/smartsview/"
                + "download_rest?smarts="
                + "SMARTS;"
                + "filetype=svg;"
                + "vmode=0;"
                + "textdesc=1;"
                + "depsymbols=1;"
                + "smartsheading=0"
Definition at line 649 of file CuttingRulesSelectionDialog.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/CuttingRulesSelectionDialog.java