DENOPTIM: denoptim.gui.GUIAPClassDefinitionDialog Class Reference
denoptim.gui.GUIAPClassDefinitionDialog Class Reference
Public Member Functions
GUIAPClassDefinitionDialog (Component refForPlacement, boolean askForBO)
void setPreDefinedAPClass (String text)
Sets the content of the text field with the given predefined text.
Public Member Functions inherited from denoptim.gui.GUIModalDialog
GUIModalDialog (Component refForPlacement)
Constructor.
GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Object showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
void addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
void addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Package Attributes
final Dimension fileLabelSize = new Dimension(250,28)
Default sizes for file pathname labels.
final int preferredHeight
Default text field height.
final Dimension strFieldSize = new Dimension(500,preferredHeight)
Private Attributes
JPanel centralPanel
String apcStringSyntax
JPanel pnlAPCName
JLabel lblAPCName
JTextField txtAPCName
JPanel pnlAPC2BO
JComboBox< BondType > cmbAPC2BO
JLabel lblAPC2BO
Static Private Attributes
static final long serialVersionUID = 3L
Version UID.
Additional Inherited Members
Protected Member Functions inherited from denoptim.gui.GUIModalDialog
void close ()
Closes the dialog window.
Protected Attributes inherited from denoptim.gui.GUIModalDialog
JButton btnDone
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
JButton btnCanc
The button that is used to close the dialog without processing any input.
JButton btnExtra
The button that can be used for any action that does not close the dialog.
Object result = null
The result to be returned once the dialog is closed.
Detailed Description
Definition at line 39 of file GUIAPClassDefinitionDialog.java.
Constructor & Destructor Documentation
GUIAPClassDefinitionDialog()
denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog (Component refForPlacement, boolean askForBO)
Definition at line 82 of file GUIAPClassDefinitionDialog.java.
References denoptim.gui.GUIModalDialog.addToCentralPane(), denoptim.gui.GUIAPClassDefinitionDialog.apcStringSyntax, denoptim.gui.GUIModalDialog.btnCanc, denoptim.gui.GUIModalDialog.btnDone, denoptim.gui.GUIAPClassDefinitionDialog.centralPanel, denoptim.gui.GUIModalDialog.close(), denoptim.gui.GUIAPClassDefinitionDialog.cmbAPC2BO, denoptim.graph.APClass.DEFAULTBT, denoptim.graph.APClass.isValidAPClassString(), denoptim.gui.GUIAPClassDefinitionDialog.lblAPC2BO, denoptim.gui.GUIAPClassDefinitionDialog.lblAPCName, denoptim.gui.GUIAPClassDefinitionDialog.pnlAPC2BO, denoptim.gui.GUIAPClassDefinitionDialog.pnlAPCName, denoptim.gui.GUIModalDialog.result, denoptim.gui.GUIAPClassDefinitionDialog.strFieldSize, and denoptim.gui.GUIAPClassDefinitionDialog.txtAPCName.
Member Function Documentation
setPreDefinedAPClass()
void denoptim.gui.GUIAPClassDefinitionDialog.setPreDefinedAPClass (String text)
Sets the content of the text field with the given predefined text.
Parameters
text
Definition at line 160 of file GUIAPClassDefinitionDialog.java.
References denoptim.gui.GUIAPClassDefinitionDialog.txtAPCName.
Referenced by denoptim.gui.GUIVertexInspector.saveUnsavedChanges().
Member Data Documentation
apcStringSyntax
String denoptim.gui.GUIAPClassDefinitionDialog.apcStringSyntax private
Initial value:
= "The valid syntax for APClass "
            + "strings is:<br><br><code>rule"
            + DENOPTIMConstants.SEPARATORAPPROPSCL
            + "subClass</code><br><br> where "
            + "<ul><li><code>rule</code>"
            + " is a string with no spaces</li>"
            + "<li><code>subClass</code> is "
            + "an integer</li></ul><br>"
Definition at line 62 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
centralPanel
JPanel denoptim.gui.GUIAPClassDefinitionDialog.centralPanel private
Definition at line 60 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
cmbAPC2BO
JComboBox<BondType> denoptim.gui.GUIAPClassDefinitionDialog.cmbAPC2BO private
Definition at line 76 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
fileLabelSize
final Dimension denoptim.gui.GUIAPClassDefinitionDialog.fileLabelSize = new Dimension(250,28) package
Default sizes for file pathname labels.
Definition at line 50 of file GUIAPClassDefinitionDialog.java.
lblAPC2BO
JLabel denoptim.gui.GUIAPClassDefinitionDialog.lblAPC2BO private
Definition at line 77 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
lblAPCName
JLabel denoptim.gui.GUIAPClassDefinitionDialog.lblAPCName private
Definition at line 72 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
pnlAPC2BO
JPanel denoptim.gui.GUIAPClassDefinitionDialog.pnlAPC2BO private
Definition at line 75 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
pnlAPCName
JPanel denoptim.gui.GUIAPClassDefinitionDialog.pnlAPCName private
Definition at line 71 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
preferredHeight
final int denoptim.gui.GUIAPClassDefinitionDialog.preferredHeight package
Initial value:
=
            (int) (new JTextField()).getPreferredSize().getHeight()
Default text field height.
Definition at line 55 of file GUIAPClassDefinitionDialog.java.
serialVersionUID
final long denoptim.gui.GUIAPClassDefinitionDialog.serialVersionUID = 3L static private
Version UID.
Definition at line 45 of file GUIAPClassDefinitionDialog.java.
strFieldSize
final Dimension denoptim.gui.GUIAPClassDefinitionDialog.strFieldSize = new Dimension(500,preferredHeight) package
Definition at line 58 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog().
txtAPCName
JTextField denoptim.gui.GUIAPClassDefinitionDialog.txtAPCName private
Definition at line 73 of file GUIAPClassDefinitionDialog.java.
Referenced by denoptim.gui.GUIAPClassDefinitionDialog.GUIAPClassDefinitionDialog(), and denoptim.gui.GUIAPClassDefinitionDialog.setPreDefinedAPClass().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIAPClassDefinitionDialog.java