DENOPTIM: denoptim.programs.isomorphism.IsomorphismParameters Class Reference
denoptim.programs.isomorphism.IsomorphismParameters Class Reference
Parameters controlling execution of Isomorphism main class.
Public Member Functions
IsomorphismParameters ()
Constructor.
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Protected Attributes
String inpFileGraphA
Input file containing graph A.
String inpFileGraphB
Input file containing graph B.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Detailed Description
Parameters controlling execution of Isomorphism main class.
Author
Marco Foscato
Definition at line 34 of file IsomorphismParameters.java.
Constructor & Destructor Documentation
IsomorphismParameters()
denoptim.programs.isomorphism.IsomorphismParameters.IsomorphismParameters ()
Constructor.
Definition at line 51 of file IsomorphismParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.ISO_PARAMS.
Member Function Documentation
checkParameters()
void denoptim.programs.isomorphism.IsomorphismParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 92 of file IsomorphismParameters.java.
References denoptim.files.FileUtils.checkExists(), denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphA, and denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphB.
Referenced by denoptim.programs.isomorphism.Isomorphism.runProgram().
getPrintedList()
String denoptim.programs.isomorphism.IsomorphismParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 131 of file IsomorphismParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
interpretKeyword()
void denoptim.programs.isomorphism.IsomorphismParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 65 of file IsomorphismParameters.java.
References denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphA, and denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphB.
processParameters()
void denoptim.programs.isomorphism.IsomorphismParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 118 of file IsomorphismParameters.java.
References denoptim.programs.RunTimeParameters.processOtherParameters().
Referenced by denoptim.programs.isomorphism.Isomorphism.runProgram().
Member Data Documentation
inpFileGraphA
String denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphA protected
Input file containing graph A.
Definition at line 39 of file IsomorphismParameters.java.
Referenced by denoptim.programs.isomorphism.IsomorphismParameters.checkParameters(), denoptim.programs.isomorphism.IsomorphismParameters.interpretKeyword(), and denoptim.programs.isomorphism.Isomorphism.runProgram().
inpFileGraphB
String denoptim.programs.isomorphism.IsomorphismParameters.inpFileGraphB protected
Input file containing graph B.
Definition at line 44 of file IsomorphismParameters.java.
Referenced by denoptim.programs.isomorphism.IsomorphismParameters.checkParameters(), denoptim.programs.isomorphism.IsomorphismParameters.interpretKeyword(), and denoptim.programs.isomorphism.Isomorphism.runProgram().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/isomorphism/IsomorphismParameters.java