DENOPTIM: denoptim.programs.mol2graph.Mol2GraphParameters Class Reference
denoptim.programs.mol2graph.Mol2GraphParameters Class Reference
Parameters controlling execution of GraphEditor.
Public Member Functions
Mol2GraphParameters ()
Constructor.
int getInputMolsCount ()
IAtomContainer getInputMol (int i)
String getOutFile ()
FileFormat getOutFormat ()
List< CuttingRule > getCuttingRules ()
ScaffoldingPolicy getScaffoldingPolicy ()
boolean embedRingsInTemplate ()
ContractLevel getEmbeddedRingsContract ()
double getLinearAngleLimit ()
FragmentSpace getFragmentSpace ()
void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Public Member Functions inherited from denoptim.programs.RunTimeParameters
RunTimeParameters (ParametersType paramType)
Constructor.
String paramTypeName ()
Returns a string defining the type the parameters collected here.
String getWorkDirectory ()
Gets the pathname to the working directory.
void setWorkDirectory (String pathname)
Gets the pathname to the working directory.
String getLogFilePathname ()
Gets the pathname to the log file.
void setLogFilePathname (String pathname)
Sets the pathname to the log file.
Logger getLogger ()
Get the name of the program specific logger.
Logger startProgramSpecificLogger (String loggerIdentifier) throws SecurityException, IOException
Starts a logger with the given name.
Logger startProgramSpecificLogger (String loggerIdentifier, boolean toLogFile) throws SecurityException, IOException
Starts a logger with the given name.
Logger startConsoleLogger (String loggerIdentifier)
Starts a program-specific logger that prints to System.err stream.
int getVerbosity ()
Returns the level of verbosity, i.e., the amount of log that we want to print.
void setVerbosity (int l)
Set the level of verbosity.
Randomizer getRandomizer ()
Returns the current program-specific randomizer.
long getRandomSeed ()
Returns the seed.
void setRandomizer (Randomizer rng)
Sets the randomizer.
Randomizer startRandomizer ()
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
Randomizer startRandomizer (long seed)
Starts a program specific randomizer, i.e., a tool for generating random numbers and taking random decisions.
void readParameterFile (String infile) throws DENOPTIMException
Read the parameter TXT file line by line and interpret its content.
void readParameterLine (String line) throws DENOPTIMException
boolean containsParameters (ParametersType type)
RunTimeParameters getParameters (ParametersType type)
void setParameters (RunTimeParameters otherParams)
void interpretKeyword (String line) throws DENOPTIMException
Processes a string looking for keyword and a possibly associated value.
abstract void interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
abstract void checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
abstract void processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
abstract String getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
void printParameters ()
Print all parameters.
Private Member Functions
void ensureFragmenterParams ()
void ensureFragSpareParams ()
Private Attributes
String inFile
File with input graphs.
List< IAtomContainer > inMols
Input molecular objects.
String outGraphsFile = null
File with output graphs.
FileFormat outGraphsFormat = FileFormat.GRAPHSDF
Additional Inherited Members
Static Public Member Functions inherited from denoptim.programs.RunTimeParameters
static boolean readYesNoTrueFalse (String s)
Reads a string searching for any common way to say either yes/true (including shorthand t/y) or no/false (including shorthand f/n either).
Public Attributes inherited from denoptim.programs.RunTimeParameters
final String NL = System.getProperty("line.separator")
New line character.
Protected Member Functions inherited from denoptim.programs.RunTimeParameters
void checkOtherParameters () throws DENOPTIMException
Checks any of the parameter collections contained in this instance.
void processOtherParameters () throws DENOPTIMException
Processes any of the parameter collections contained in this instance.
void ensureFileExistsIfSet (String pathname)
Ensures a pathname is not empty nor null and that it does lead to an existing file or triggers an error.
void ensureFileExists (String pathname)
Ensures a pathname does lead to an existing file or triggers an error.
void ensureNotNull (String paramName, String param, String paramKey)
Ensures that a parameter is not null or triggers an error.
void ensureIsPositive (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureIsPositiveOrZero (String paramName, int value, String paramKey)
Ensures that a parameter is a positive number (x>=0) or triggers an error.
void ensureInRange (String paramName, int value, int min, int max, String paramKey)
Ensures that a parameter is within a range or triggers an error.
Protected Attributes inherited from denoptim.programs.RunTimeParameters
boolean isMaster = true
Flag signaling this is the master collection of parameters.
String workDir = System.getProperty("user.dir")
Working directory.
String logFile = "unset"
Log file.
int verbosity = 0
Verbosity level for logger.
Map< ParametersType, RunTimeParameters > otherParameters
Collection of other parameters by type.
Detailed Description
Parameters controlling execution of GraphEditor.
Author
Marco Foscato
Definition at line 49 of file Mol2GraphParameters.java.
Constructor & Destructor Documentation
Mol2GraphParameters()
denoptim.programs.mol2graph.Mol2GraphParameters.Mol2GraphParameters ()
Constructor.
Definition at line 72 of file Mol2GraphParameters.java.
References denoptim.programs.RunTimeParameters.ParametersType.M2G_PARAMS.
Member Function Documentation
checkParameters()
void denoptim.programs.mol2graph.Mol2GraphParameters.checkParameters () throws DENOPTIMException
Evaluate consistency of input parameters.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 283 of file Mol2GraphParameters.java.
References denoptim.files.FileUtils.checkExists(), denoptim.programs.RunTimeParameters.checkOtherParameters(), denoptim.programs.mol2graph.Mol2GraphParameters.inFile, denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFile, and denoptim.programs.RunTimeParameters.workDir.
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
embedRingsInTemplate()
boolean denoptim.programs.mol2graph.Mol2GraphParameters.embedRingsInTemplate ()
Definition at line 127 of file Mol2GraphParameters.java.
References denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate, denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, and denoptim.programs.RunTimeParameters.getParameters().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
ensureFragmenterParams()
void denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams () private
Definition at line 167 of file Mol2GraphParameters.java.
References denoptim.programs.RunTimeParameters.containsParameters(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, and denoptim.programs.RunTimeParameters.setParameters().
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.embedRingsInTemplate(), denoptim.programs.mol2graph.Mol2GraphParameters.getCuttingRules(), denoptim.programs.mol2graph.Mol2GraphParameters.getEmbeddedRingsContract(), denoptim.programs.mol2graph.Mol2GraphParameters.getLinearAngleLimit(), denoptim.programs.mol2graph.Mol2GraphParameters.getScaffoldingPolicy(), and denoptim.programs.mol2graph.Mol2GraphParameters.processParameters().
ensureFragSpareParams()
void denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragSpareParams () private
Definition at line 177 of file Mol2GraphParameters.java.
References denoptim.programs.RunTimeParameters.containsParameters(), denoptim.programs.RunTimeParameters.ParametersType.FS_PARAMS, and denoptim.programs.RunTimeParameters.setParameters().
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.getFragmentSpace(), and denoptim.programs.mol2graph.Mol2GraphParameters.processParameters().
getCuttingRules()
List< CuttingRule > denoptim.programs.mol2graph.Mol2GraphParameters.getCuttingRules ()
Definition at line 107 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, denoptim.programs.fragmenter.FragmenterParameters.getCuttingRules(), and denoptim.programs.RunTimeParameters.getParameters().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getEmbeddedRingsContract()
ContractLevel denoptim.programs.mol2graph.Mol2GraphParameters.getEmbeddedRingsContract ()
Definition at line 137 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, denoptim.programs.fragmenter.FragmenterParameters.getEmbeddedRingsContract(), and denoptim.programs.RunTimeParameters.getParameters().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getFragmentSpace()
FragmentSpace denoptim.programs.mol2graph.Mol2GraphParameters.getFragmentSpace ()
Definition at line 157 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragSpareParams(), denoptim.programs.RunTimeParameters.ParametersType.FS_PARAMS, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), and denoptim.programs.RunTimeParameters.getParameters().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getInputMol()
IAtomContainer denoptim.programs.mol2graph.Mol2GraphParameters.getInputMol (int i)
Definition at line 86 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.inMols.
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getInputMolsCount()
int denoptim.programs.mol2graph.Mol2GraphParameters.getInputMolsCount ()
Definition at line 79 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.inMols.
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getLinearAngleLimit()
double denoptim.programs.mol2graph.Mol2GraphParameters.getLinearAngleLimit ()
Definition at line 147 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, denoptim.programs.fragmenter.FragmenterParameters.getLinearAngleLimit(), and denoptim.programs.RunTimeParameters.getParameters().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getOutFile()
String denoptim.programs.mol2graph.Mol2GraphParameters.getOutFile ()
Definition at line 93 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFile.
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getOutFormat()
FileFormat denoptim.programs.mol2graph.Mol2GraphParameters.getOutFormat ()
Definition at line 100 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFormat.
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
getPrintedList()
String denoptim.programs.mol2graph.Mol2GraphParameters.getPrintedList ()
Returns the list of parameters in a string with newline characters as delimiters.
Returns
the list of parameters in a string with newline characters as delimiters.
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 251 of file Mol2GraphParameters.java.
References denoptim.programs.RunTimeParameters.NL, denoptim.programs.RunTimeParameters.otherParameters, and denoptim.programs.RunTimeParameters.paramTypeName().
getScaffoldingPolicy()
ScaffoldingPolicy denoptim.programs.mol2graph.Mol2GraphParameters.getScaffoldingPolicy ()
Definition at line 117 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, denoptim.programs.RunTimeParameters.getParameters(), and denoptim.programs.fragmenter.FragmenterParameters.getScaffoldingPolicy().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
interpretKeyword()
void denoptim.programs.mol2graph.Mol2GraphParameters.interpretKeyword (String key, String value) throws DENOPTIMException
Processes a keyword/value pair and assign the related parameters.
Parameters
key the keyword as string
value the value as a string
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 194 of file Mol2GraphParameters.java.
References denoptim.files.FileFormat.GRAPHJSON, denoptim.files.FileFormat.GRAPHSDF, denoptim.programs.mol2graph.Mol2GraphParameters.inFile, denoptim.programs.RunTimeParameters.logFile, denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFile, denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFormat, denoptim.programs.RunTimeParameters.verbosity, and denoptim.programs.RunTimeParameters.workDir.
processParameters()
void denoptim.programs.mol2graph.Mol2GraphParameters.processParameters () throws DENOPTIMException
Processes all parameters and initialize related objects.
Exceptions
DENOPTIMException
Reimplemented from denoptim.programs.RunTimeParameters.
Definition at line 320 of file Mol2GraphParameters.java.
References denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragmenterParams(), denoptim.programs.mol2graph.Mol2GraphParameters.ensureFragSpareParams(), denoptim.programs.RunTimeParameters.ParametersType.FRG_PARAMS, denoptim.programs.fragmenter.FragmenterParameters.getCuttingRules(), denoptim.programs.RunTimeParameters.getParameters(), denoptim.programs.mol2graph.Mol2GraphParameters.inFile, denoptim.programs.mol2graph.Mol2GraphParameters.inMols, denoptim.programs.RunTimeParameters.processOtherParameters(), denoptim.io.DenoptimIO.readAllAtomContainers(), denoptim.io.DenoptimIO.readCuttingRules(), and denoptim.programs.fragmenter.FragmenterParameters.setCuttingRules().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
Member Data Documentation
inFile
String denoptim.programs.mol2graph.Mol2GraphParameters.inFile private
File with input graphs.
Definition at line 54 of file Mol2GraphParameters.java.
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.checkParameters(), denoptim.programs.mol2graph.Mol2GraphParameters.interpretKeyword(), and denoptim.programs.mol2graph.Mol2GraphParameters.processParameters().
inMols
List<IAtomContainer> denoptim.programs.mol2graph.Mol2GraphParameters.inMols private
Input molecular objects.
Definition at line 59 of file Mol2GraphParameters.java.
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.getInputMol(), denoptim.programs.mol2graph.Mol2GraphParameters.getInputMolsCount(), and denoptim.programs.mol2graph.Mol2GraphParameters.processParameters().
outGraphsFile
String denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFile = null private
File with output graphs.
Definition at line 64 of file Mol2GraphParameters.java.
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.checkParameters(), denoptim.programs.mol2graph.Mol2GraphParameters.getOutFile(), and denoptim.programs.mol2graph.Mol2GraphParameters.interpretKeyword().
outGraphsFormat
FileFormat denoptim.programs.mol2graph.Mol2GraphParameters.outGraphsFormat = FileFormat.GRAPHSDF private
Definition at line 65 of file Mol2GraphParameters.java.
Referenced by denoptim.programs.mol2graph.Mol2GraphParameters.getOutFormat(), and denoptim.programs.mol2graph.Mol2GraphParameters.interpretKeyword().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/mol2graph/Mol2GraphParameters.java