DENOPTIM: denoptim.fragmenter.ParallelFragmentationAlgorithmTest Class Reference
denoptim.fragmenter.ParallelFragmentationAlgorithmTest Class Reference
Unit test for fparallel ragmentation algorithm components.
Public Member Functions
void testSplitInputForThreads () throws Exception
Static Package Attributes
static File tempDir
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Static Private Attributes
static final String SEP = System.getProperty("file.separator")
static final String NL = System.getProperty("line.separator")
Detailed Description
Unit test for fparallel ragmentation algorithm components.
Author
Marco Foscato
Definition at line 45 of file ParallelFragmentationAlgorithmTest.java.
Member Function Documentation
testSplitInputForThreads()
void denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads () throws Exception
Definition at line 61 of file ParallelFragmentationAlgorithmTest.java.
References denoptim.fragmenter.ParallelFragmentationAlgorithmTest.builder, denoptim.programs.fragmenter.FragmenterParameters.checkParameters(), denoptim.constants.DENOPTIMConstants.FORMULASTR, denoptim.fragmenter.ParallelFragmentationAlgorithm.getStructureFileNameBatch(), denoptim.programs.fragmenter.FragmenterParameters.getStructuresFile(), denoptim.fragmenter.ParallelFragmentationAlgorithmTest.NL, denoptim.programs.fragmenter.FragmenterParameters.processParameters(), denoptim.io.DenoptimIO.readList(), denoptim.fragmenter.ParallelFragmentationAlgorithmTest.SEP, denoptim.programs.fragmenter.FragmenterParameters.setCheckFormula(), denoptim.programs.fragmenter.FragmenterParameters.setFormulaeFile(), denoptim.programs.fragmenter.FragmenterParameters.setNumTasks(), denoptim.programs.fragmenter.FragmenterParameters.setStructuresFile(), denoptim.programs.RunTimeParameters.setWorkDirectory(), denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads(), denoptim.fragmenter.ParallelFragmentationAlgorithmTest.tempDir, denoptim.io.DenoptimIO.writeData(), and denoptim.io.DenoptimIO.writeSDFFile().
Member Data Documentation
builder
IChemObjectBuilder denoptim.fragmenter.ParallelFragmentationAlgorithmTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 53 of file ParallelFragmentationAlgorithmTest.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
NL
final String denoptim.fragmenter.ParallelFragmentationAlgorithmTest.NL = System.getProperty("line.separator") static private
Definition at line 48 of file ParallelFragmentationAlgorithmTest.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
SEP
final String denoptim.fragmenter.ParallelFragmentationAlgorithmTest.SEP = System.getProperty("file.separator") static private
Definition at line 47 of file ParallelFragmentationAlgorithmTest.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
tempDir
File denoptim.fragmenter.ParallelFragmentationAlgorithmTest.tempDir static package
Definition at line 56 of file ParallelFragmentationAlgorithmTest.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragmenter/ParallelFragmentationAlgorithmTest.java