DENOPTIM: denoptim.utils.RandomizerTest Class Reference
denoptim.utils.RandomizerTest Class Reference
Unit test.
Public Member Functions
void testRandomizerReproducibility () throws Exception
void tesGetNoisyPoint () throws Exception
void testRandomlyChooseOne () throws Exception
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 37 of file RandomizerTest.java.
Member Function Documentation
tesGetNoisyPoint()
void denoptim.utils.RandomizerTest.tesGetNoisyPoint () throws Exception
Definition at line 73 of file RandomizerTest.java.
References denoptim.utils.Randomizer.getNoisyPoint().
testRandomizerReproducibility()
void denoptim.utils.RandomizerTest.testRandomizerReproducibility () throws Exception
Definition at line 43 of file RandomizerTest.java.
References denoptim.utils.Randomizer.nextDouble().
testRandomlyChooseOne()
void denoptim.utils.RandomizerTest.testRandomlyChooseOne () throws Exception
Definition at line 89 of file RandomizerTest.java.
References denoptim.utils.Randomizer.randomlyChooseOne().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/utils/RandomizerTest.java