DENOPTIM: denoptim.gui.CompatibilityMatrixForm Class Reference
denoptim.gui.CompatibilityMatrixForm Class Reference
Classes
class CompatibilityRuleLine
Single line in the list of APClass compatibility rules.
class CompatRulesHeader
class TargetAPClassToken
class TrgRemovalListener
Listens for clicks that require removal of a compatible APClass (i.e., the target APClass) from the existing rule of a source APClass.
Public Member Functions
CompatibilityMatrixForm ()
void writeCopatibilityMatrixFile (JComponent parent, File outFile)
Writes all the compatibility matrix data to the given file.
void importAllAPClassesFromCappingGroupLibs (Set< File > fragLibs, boolean cleanup)
Reads all the APClasses found in a list of files.
void importAllAPClassesFromFragmentLibs (Set< File > fragLibs, boolean cleanup)
Reads all the APClasses found in a list of files.
Protected Member Functions
void clearSearchMatches ()
void searchAPClass (String query)
void importCPMapFromFile (JComponent parent, File inFile)
Static Protected Attributes
static final String REMOVETRGAPC = "REMOVETRGAPC"
Property used to trigger removal of a target APClass.
Private Member Functions
void updateAPClassCompatibilitiesList ()
void updateCappingRulesTable ()
void updateForbiddenEndsTable ()
void importAllAPClassesFromCPMatrix (boolean cleanup)
Reads all the APClasses found in the currently loaded compatibility matrix.
void importAllCappingGroupsAPClassesFromCPMatrix (boolean cleanup)
Reads all the APClasses of capping groups as found in the currently loaded capping rules.
Private Attributes
SortedSet< APClass > allAPClasses = new TreeSet<APClass>()
List of all APClasses.
SortedSet< String > allAPRules = new TreeSet<String>()
List of all APRules.
SortedSet< APClass > allCapAPClasses = new TreeSet<APClass>()
List of APClasses of capping groups.
SortedSet< APClass > allAPClsInCPMap = new TreeSet<APClass>()
Sorted list of APClasses in the map of compatibility rules.
HashMap< APClass, ArrayList< APClass > > compatMap
Data structure that stored the true entries of the attachment point classes compatibility matrix.
HashMap< APClass, APClass > cappingMap
Data structure that stores the AP-classes to be used to cap unused APS on the growing molecule.
HashSet< APClass > forbiddenEndList = new HashSet<APClass>()
Data structure that stores AP classes that cannot be held unused.
JTabbedPane tabbedPane
JPanel panelCPMap
JButton btnAddCompRul
JButton btnDelCompRul
JButton btnCopyCompRul
JButton btnClearMatch
JButton btnHelpCPMap
JPanel panelCPRules
JScrollPane scrollPanelCPMap
JTextField txtSearch
JLabel matchCounter
JPanel panelCapping
DefaultTableModel tabModCapping
JTable tableCapping
JButton btnAddCapping
JButton btnDelCapping
JButton btnSortCapping
JButton btnHelpCapping
JPanel panelFrbEnd
DefaultTableModel tabModFrbEnd
JTable tableFrbEnd
JButton btnAddFrbEnd
JButton btnDelFrbEnd
JButton btnSortFrbEnd
JButton btnHelpFrbEnd
Static Private Attributes
static final long serialVersionUID = -8042143358823563589L
Version UID.
Detailed Description
Definition at line 70 of file CompatibilityMatrixForm.java.
Constructor & Destructor Documentation
CompatibilityMatrixForm()
denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm ()
Definition at line 158 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClasses, denoptim.gui.CompatibilityMatrixForm.allAPClsInCPMap, denoptim.gui.CompatibilityMatrixForm.allAPRules, denoptim.gui.CompatibilityMatrixForm.allCapAPClasses, denoptim.gui.CompatibilityMatrixForm.btnAddCapping, denoptim.gui.CompatibilityMatrixForm.btnAddCompRul, denoptim.gui.CompatibilityMatrixForm.btnAddFrbEnd, denoptim.gui.CompatibilityMatrixForm.btnClearMatch, denoptim.gui.CompatibilityMatrixForm.btnCopyCompRul, denoptim.gui.CompatibilityMatrixForm.btnDelCapping, denoptim.gui.CompatibilityMatrixForm.btnDelCompRul, denoptim.gui.CompatibilityMatrixForm.btnDelFrbEnd, denoptim.gui.CompatibilityMatrixForm.btnHelpCapping, denoptim.gui.CompatibilityMatrixForm.btnHelpCPMap, denoptim.gui.CompatibilityMatrixForm.btnHelpFrbEnd, denoptim.gui.CompatibilityMatrixForm.btnSortCapping, denoptim.gui.CompatibilityMatrixForm.btnSortFrbEnd, denoptim.gui.CompatibilityMatrixForm.cappingMap, denoptim.gui.CompatibilityMatrixForm.clearSearchMatches(), denoptim.gui.CompatibilityMatrixForm.compatMap, denoptim.gui.CompatibilityMatrixForm.forbiddenEndList, denoptim.graph.APClass.getRule(), denoptim.graph.APClass.make(), denoptim.gui.CompatibilityMatrixForm.matchCounter, denoptim.gui.CompatibilityMatrixForm.panelCapping, denoptim.gui.CompatibilityMatrixForm.panelCPMap, denoptim.gui.CompatibilityMatrixForm.panelCPRules, denoptim.gui.CompatibilityMatrixForm.panelFrbEnd, denoptim.gui.CompatibilityMatrixForm.scrollPanelCPMap, denoptim.gui.CompatibilityMatrixForm.searchAPClass(), denoptim.gui.GUIModalDialog.showDialog(), denoptim.gui.CompatibilityMatrixForm.tabbedPane, denoptim.gui.CompatibilityMatrixForm.tableCapping, denoptim.gui.CompatibilityMatrixForm.tableFrbEnd, denoptim.gui.CompatibilityMatrixForm.tabModCapping, denoptim.gui.CompatibilityMatrixForm.tabModFrbEnd, denoptim.gui.CompatibilityMatrixForm.txtSearch, denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList(), denoptim.gui.CompatibilityMatrixForm.updateCappingRulesTable(), and denoptim.gui.CompatibilityMatrixForm.updateForbiddenEndsTable().
Member Function Documentation
clearSearchMatches()
void denoptim.gui.CompatibilityMatrixForm.clearSearchMatches () protected
Definition at line 1092 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.panelCPRules.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.searchAPClass().
importAllAPClassesFromCappingGroupLibs()
void denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCappingGroupLibs (Set< File > fragLibs, boolean cleanup)
Reads all the APClasses found in a list of files.
Parameters
fragLibs the list of file to inspect.
cleanup set true to cleanup previous listing of APclasses.
Definition at line 1330 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPRules, denoptim.gui.CompatibilityMatrixForm.allCapAPClasses, and denoptim.io.DenoptimIO.readAllAPClasses().
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
importAllAPClassesFromCPMatrix()
void denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCPMatrix (boolean cleanup) private
Reads all the APClasses found in the currently loaded compatibility matrix.
Parameters
cleanup set true to cleanup previous listing of APclasses.
Definition at line 1278 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClasses, denoptim.gui.CompatibilityMatrixForm.allAPRules, and denoptim.gui.CompatibilityMatrixForm.compatMap.
Referenced by denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
importAllAPClassesFromFragmentLibs()
void denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromFragmentLibs (Set< File > fragLibs, boolean cleanup)
Reads all the APClasses found in a list of files.
Parameters
fragLibs the list of file to inspect.
cleanup set true to cleanup previous listing of APclasses.
Definition at line 1363 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClasses, denoptim.gui.CompatibilityMatrixForm.allAPRules, and denoptim.io.DenoptimIO.readAllAPClasses().
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
importAllCappingGroupsAPClassesFromCPMatrix()
void denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix (boolean cleanup) private
Reads all the APClasses of capping groups as found in the currently loaded capping rules.
Parameters
cleanup set true to cleanup previous listing of APclasses.
Definition at line 1307 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClasses, denoptim.gui.CompatibilityMatrixForm.allAPRules, denoptim.gui.CompatibilityMatrixForm.allCapAPClasses, and denoptim.gui.CompatibilityMatrixForm.cappingMap.
Referenced by denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
importCPMapFromFile()
void denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile (JComponent parent, File inFile) protected
Definition at line 1139 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClsInCPMap, denoptim.gui.CompatibilityMatrixForm.cappingMap, denoptim.gui.CompatibilityMatrixForm.compatMap, denoptim.gui.CompatibilityMatrixForm.forbiddenEndList, denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCPMatrix(), denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix(), denoptim.io.DenoptimIO.readCompatibilityMatrix(), denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList(), denoptim.gui.CompatibilityMatrixForm.updateCappingRulesTable(), and denoptim.gui.CompatibilityMatrixForm.updateForbiddenEndsTable().
Referenced by denoptim.gui.GUICompatibilityMatrixTab.importCPMapFromFile(), and denoptim.gui.GUICompatibilityMatrixTab.initialize().
searchAPClass()
void denoptim.gui.CompatibilityMatrixForm.searchAPClass (String query) protected
Definition at line 1105 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.btnClearMatch, denoptim.gui.CompatibilityMatrixForm.clearSearchMatches(), denoptim.gui.CompatibilityMatrixForm.matchCounter, denoptim.gui.CompatibilityMatrixForm.panelCPRules, and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
updateAPClassCompatibilitiesList()
void denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList () private
Definition at line 1201 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClsInCPMap, and denoptim.gui.CompatibilityMatrixForm.panelCPRules.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), and denoptim.gui.CompatibilityMatrixForm.TrgRemovalListener.propertyChange().
updateCappingRulesTable()
void denoptim.gui.CompatibilityMatrixForm.updateCappingRulesTable () private
Definition at line 1222 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.cappingMap, and denoptim.gui.CompatibilityMatrixForm.tabModCapping.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
updateForbiddenEndsTable()
void denoptim.gui.CompatibilityMatrixForm.updateForbiddenEndsTable () private
Definition at line 1247 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.forbiddenEndList, and denoptim.gui.CompatibilityMatrixForm.tabModFrbEnd.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
writeCopatibilityMatrixFile()
void denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile (JComponent parent, File outFile)
Writes all the compatibility matrix data to the given file.
this methods writes all data, that is, compatibility rules, APClass-to- bond type, capping rules, and definition of forbidden ends.
Parameters
parent the component to which the dialog should be bound.
outFile where to write
Definition at line 1183 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.cappingMap, denoptim.gui.CompatibilityMatrixForm.compatMap, denoptim.gui.CompatibilityMatrixForm.forbiddenEndList, and denoptim.io.DenoptimIO.writeCompatibilityMatrix().
Referenced by denoptim.gui.GUICompatibilityMatrixTab.initialize().
Member Data Documentation
allAPClasses
SortedSet<APClass> denoptim.gui.CompatibilityMatrixForm.allAPClasses = new TreeSet<APClass>() private
List of all APClasses.
These can be found in a fragment space or collected from fragment libraries
Definition at line 87 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCPMatrix(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromFragmentLibs(), and denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix().
allAPClsInCPMap
SortedSet<APClass> denoptim.gui.CompatibilityMatrixForm.allAPClsInCPMap = new TreeSet<APClass>() private
Sorted list of APClasses in the map of compatibility rules.
Definition at line 105 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), and denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList().
allAPRules
SortedSet<String> denoptim.gui.CompatibilityMatrixForm.allAPRules = new TreeSet<String>() private
List of all APRules.
This list can be edited by creating/removing an APRule or by creating/removing an APClass.
Definition at line 93 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCappingGroupLibs(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCPMatrix(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromFragmentLibs(), and denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix().
allCapAPClasses
SortedSet<APClass> denoptim.gui.CompatibilityMatrixForm.allCapAPClasses = new TreeSet<APClass>() private
List of APClasses of capping groups.
These can be found in a fragment space or collected from the capping group library
Definition at line 100 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCappingGroupLibs(), and denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix().
btnAddCapping
JButton denoptim.gui.CompatibilityMatrixForm.btnAddCapping private
Definition at line 142 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnAddCompRul
JButton denoptim.gui.CompatibilityMatrixForm.btnAddCompRul private
Definition at line 129 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnAddFrbEnd
JButton denoptim.gui.CompatibilityMatrixForm.btnAddFrbEnd private
Definition at line 150 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnClearMatch
JButton denoptim.gui.CompatibilityMatrixForm.btnClearMatch private
Definition at line 132 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.searchAPClass().
btnCopyCompRul
JButton denoptim.gui.CompatibilityMatrixForm.btnCopyCompRul private
Definition at line 131 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnDelCapping
JButton denoptim.gui.CompatibilityMatrixForm.btnDelCapping private
Definition at line 143 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnDelCompRul
JButton denoptim.gui.CompatibilityMatrixForm.btnDelCompRul private
Definition at line 130 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnDelFrbEnd
JButton denoptim.gui.CompatibilityMatrixForm.btnDelFrbEnd private
Definition at line 151 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnHelpCapping
JButton denoptim.gui.CompatibilityMatrixForm.btnHelpCapping private
Definition at line 145 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnHelpCPMap
JButton denoptim.gui.CompatibilityMatrixForm.btnHelpCPMap private
Definition at line 133 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnHelpFrbEnd
JButton denoptim.gui.CompatibilityMatrixForm.btnHelpFrbEnd private
Definition at line 153 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnSortCapping
JButton denoptim.gui.CompatibilityMatrixForm.btnSortCapping private
Definition at line 144 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
btnSortFrbEnd
JButton denoptim.gui.CompatibilityMatrixForm.btnSortFrbEnd private
Definition at line 152 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
cappingMap
HashMap<APClass, APClass> denoptim.gui.CompatibilityMatrixForm.cappingMap private
Initial value:
=
            new HashMap<APClass, APClass>()
Data structure that stores the AP-classes to be used to cap unused APS on the growing molecule.
Definition at line 118 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.importAllCappingGroupsAPClassesFromCPMatrix(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), denoptim.gui.CompatibilityMatrixForm.updateCappingRulesTable(), and denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile().
compatMap
HashMap<APClass, ArrayList<APClass> > denoptim.gui.CompatibilityMatrixForm.compatMap private
Initial value:
=
                new HashMap<APClass, ArrayList<APClass>>()
Data structure that stored the true entries of the attachment point classes compatibility matrix.
Definition at line 111 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCPMatrix(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), denoptim.gui.CompatibilityMatrixForm.TrgRemovalListener.propertyChange(), and denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile().
forbiddenEndList
HashSet<APClass> denoptim.gui.CompatibilityMatrixForm.forbiddenEndList = new HashSet<APClass>() private
Data structure that stores AP classes that cannot be held unused.
Definition at line 124 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile(), denoptim.gui.CompatibilityMatrixForm.updateForbiddenEndsTable(), and denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile().
matchCounter
JLabel denoptim.gui.CompatibilityMatrixForm.matchCounter private
Definition at line 137 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.searchAPClass().
panelCapping
JPanel denoptim.gui.CompatibilityMatrixForm.panelCapping private
Definition at line 139 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
panelCPMap
JPanel denoptim.gui.CompatibilityMatrixForm.panelCPMap private
Definition at line 128 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
panelCPRules
JPanel denoptim.gui.CompatibilityMatrixForm.panelCPRules private
Definition at line 134 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.clearSearchMatches(), denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), denoptim.gui.CompatibilityMatrixForm.searchAPClass(), and denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList().
panelFrbEnd
JPanel denoptim.gui.CompatibilityMatrixForm.panelFrbEnd private
Definition at line 147 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
REMOVETRGAPC
final String denoptim.gui.CompatibilityMatrixForm.REMOVETRGAPC = "REMOVETRGAPC" static protected
Property used to trigger removal of a target APClass.
Definition at line 80 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), and denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.TargetAPClassToken().
scrollPanelCPMap
JScrollPane denoptim.gui.CompatibilityMatrixForm.scrollPanelCPMap private
Definition at line 135 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
serialVersionUID
final long denoptim.gui.CompatibilityMatrixForm.serialVersionUID = -8042143358823563589L static private
Version UID.
Definition at line 75 of file CompatibilityMatrixForm.java.
tabbedPane
JTabbedPane denoptim.gui.CompatibilityMatrixForm.tabbedPane private
Definition at line 126 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
tableCapping
JTable denoptim.gui.CompatibilityMatrixForm.tableCapping private
Definition at line 141 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
tableFrbEnd
JTable denoptim.gui.CompatibilityMatrixForm.tableFrbEnd private
Definition at line 149 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
tabModCapping
DefaultTableModel denoptim.gui.CompatibilityMatrixForm.tabModCapping private
Definition at line 140 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.updateCappingRulesTable().
tabModFrbEnd
DefaultTableModel denoptim.gui.CompatibilityMatrixForm.tabModFrbEnd private
Definition at line 148 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm(), and denoptim.gui.CompatibilityMatrixForm.updateForbiddenEndsTable().
txtSearch
JTextField denoptim.gui.CompatibilityMatrixForm.txtSearch private
Definition at line 136 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityMatrixForm().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/CompatibilityMatrixForm.java