DENOPTIM: denoptim.gui.GUIFileSaver Class Reference
denoptim.gui.GUIFileSaver Class Reference
GUI component to provide pathname where to save stuff.
Static Public Member Functions
static FileAndFormat pickFileForSavingGraphs (Component parent)
static FileAndFormat pickFileForSavingVertexes (Component parent)
static FileAndFormat pickFileForSavingCuttingRules (Component parent)
Static Private Member Functions
static File getSystemRoot ()
Static Private Attributes
static JFileChooser fileChooser = new JFileChooser(getSystemRoot())
Detailed Description
GUI component to provide pathname where to save stuff.
Definition at line 36 of file GUIFileSaver.java.
Member Function Documentation
getSystemRoot()
static File denoptim.gui.GUIFileSaver.getSystemRoot () static private
Definition at line 42 of file GUIFileSaver.java.
pickFileForSavingCuttingRules()
static FileAndFormat denoptim.gui.GUIFileSaver.pickFileForSavingCuttingRules (Component parent) static
Definition at line 105 of file GUIFileSaver.java.
References denoptim.files.FileFormat.CUTRULE, and denoptim.gui.GUIFileSaver.fileChooser.
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog().
pickFileForSavingGraphs()
static FileAndFormat denoptim.gui.GUIFileSaver.pickFileForSavingGraphs (Component parent) static
Definition at line 53 of file GUIFileSaver.java.
References denoptim.gui.GUIFileSaver.fileChooser, denoptim.files.FileFormat.fromString(), and denoptim.files.FileFormat.DataKind.GRAPH.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
pickFileForSavingVertexes()
static FileAndFormat denoptim.gui.GUIFileSaver.pickFileForSavingVertexes (Component parent) static
Definition at line 79 of file GUIFileSaver.java.
References denoptim.gui.GUIFileSaver.fileChooser, denoptim.files.FileFormat.fromString(), and denoptim.files.FileFormat.DataKind.VERTEX.
Referenced by denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIVertexInspector.initialize().
Member Data Documentation
fileChooser
JFileChooser denoptim.gui.GUIFileSaver.fileChooser = new JFileChooser(getSystemRoot()) static private
Definition at line 38 of file GUIFileSaver.java.
Referenced by denoptim.gui.GUIFileSaver.pickFileForSavingCuttingRules(), denoptim.gui.GUIFileSaver.pickFileForSavingGraphs(), and denoptim.gui.GUIFileSaver.pickFileForSavingVertexes().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIFileSaver.java