DENOPTIM: denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken Class Reference
denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken Class Reference
Public Member Functions
TargetAPClassToken (APClass trgAPClass)
boolean matchesAPClass (String regex)
void renderAsSelected (boolean selected)
Private Attributes
APClass trgAPClass
JTextField trgAPClLabel
JButton btnDel
final Color BTNPRESS = Color.decode("#fbae9d")
final Color BTNDEF = Color.decode("#f74922")
final Color SELECTEDBACKGROUND = Color.BLUE
final Color DEFAULTBACKGROUND
Detailed Description
Definition at line 1722 of file CompatibilityMatrixForm.java.
Constructor & Destructor Documentation
TargetAPClassToken()
denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.TargetAPClassToken (APClass trgAPClass)
Definition at line 1735 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.REMOVETRGAPC, and denoptim.graph.APClass.toString().
Member Function Documentation
matchesAPClass()
boolean denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.matchesAPClass (String regex)
Definition at line 1789 of file CompatibilityMatrixForm.java.
References denoptim.graph.APClass.toString().
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
renderAsSelected()
void denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.renderAsSelected (boolean selected)
Definition at line 1796 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
Member Data Documentation
BTNDEF
final Color denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.BTNDEF = Color.decode("#f74922") private
Definition at line 1729 of file CompatibilityMatrixForm.java.
btnDel
JButton denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.btnDel private
Definition at line 1726 of file CompatibilityMatrixForm.java.
BTNPRESS
final Color denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.BTNPRESS = Color.decode("#fbae9d") private
Definition at line 1728 of file CompatibilityMatrixForm.java.
DEFAULTBACKGROUND
final Color denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.DEFAULTBACKGROUND private
Initial value:
=
                UIManager.getLookAndFeelDefaults().getColor("Panel.background")
Definition at line 1732 of file CompatibilityMatrixForm.java.
SELECTEDBACKGROUND
final Color denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.SELECTEDBACKGROUND = Color.BLUE private
Definition at line 1731 of file CompatibilityMatrixForm.java.
trgAPClass
APClass denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.trgAPClass private
Definition at line 1724 of file CompatibilityMatrixForm.java.
trgAPClLabel
JTextField denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.trgAPClLabel private
Definition at line 1725 of file CompatibilityMatrixForm.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/CompatibilityMatrixForm.java