DENOPTIM: denoptim.graph.rings.RandomCombOfRingsIterator Class Reference
denoptim.graph.rings.RandomCombOfRingsIterator Class Reference
A class for iterating over sets of ring combinations generated by considering any constrain and setting defined in the fragment space and ring-closure settings and by randomly picking candidates when no criterion can be used to take an informed decision.
Public Member Functions
RandomCombOfRingsIterator (IAtomContainer iac, DGraph molGraph, int maxRingClosures, FragmentSpace fragSpace, RingClosureParameters rcParams) throws DENOPTIMException
Constructs an iterator.
boolean hasNext ()
Always returns true because we allow duplicates.
List< Ring > next ()
Private Attributes
IAtomContainer originalMol
Chemical representation of the system we work with.
DGraph molGraph
Graph representation of the system we work with.
int maxRingClosures = -1
Max number of ring closures to consider in a valid combination of rings.
FragmentSpace fragSpace
Space of building blocks.
RingClosureParameters settings
Parameters related to rings.
Detailed Description
A class for iterating over sets of ring combinations generated by considering any constrain and setting defined in the fragment space and ring-closure settings and by randomly picking candidates when no criterion can be used to take an informed decision.
Note this iterator loops infinitely, i.e., hasNext() returns always true.
Definition at line 26 of file RandomCombOfRingsIterator.java.
Constructor & Destructor Documentation
RandomCombOfRingsIterator()
denoptim.graph.rings.RandomCombOfRingsIterator.RandomCombOfRingsIterator (IAtomContainer iac, DGraph molGraph, int maxRingClosures, FragmentSpace fragSpace, RingClosureParameters rcParams) throws DENOPTIMException
Constructs an iterator.
Parameters
inMol
molGraph
maxRingClosures
Exceptions
DENOPTIMException
Definition at line 63 of file RandomCombOfRingsIterator.java.
References denoptim.graph.rings.RandomCombOfRingsIterator.fragSpace, denoptim.graph.rings.RandomCombOfRingsIterator.maxRingClosures, and denoptim.graph.rings.RandomCombOfRingsIterator.molGraph.
Member Function Documentation
hasNext()
boolean denoptim.graph.rings.RandomCombOfRingsIterator.hasNext ()
Always returns true because we allow duplicates.
Definition at line 80 of file RandomCombOfRingsIterator.java.
next()
List< Ring > denoptim.graph.rings.RandomCombOfRingsIterator.next ()
Definition at line 88 of file RandomCombOfRingsIterator.java.
References denoptim.graph.rings.RingSizeManager.addRingClosingBond(), denoptim.graph.rings.RandomCombOfRingsIterator.fragSpace, denoptim.graph.Edge.getBondType(), denoptim.graph.Vertex.getEdgeToParent(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.graph.rings.RingSizeManager.getRSBiasedListOfCandidates(), denoptim.graph.rings.PathSubGraph.getVertecesPath(), denoptim.graph.rings.RingSizeManager.initialize(), denoptim.graph.rings.PathClosabilityTools.isCloseable(), denoptim.graph.rings.RandomCombOfRingsIterator.maxRingClosures, denoptim.graph.rings.RandomCombOfRingsIterator.molGraph, denoptim.utils.Randomizer.nextInt(), denoptim.graph.rings.RandomCombOfRingsIterator.originalMol, denoptim.graph.Ring.setBondType(), denoptim.graph.rings.RandomCombOfRingsIterator.settings, and denoptim.graph.rings.RingSizeManager.setVertexAsDone().
Referenced by denoptim.ga.GraphOperations.addRing(), denoptim.graph.rings.CyclicGraphHandler.getRandomCombinationOfRings(), and denoptim.graph.rings.RandomCombOfRingIteratorTest.testEvaluateConstitutionalClosability().
Member Data Documentation
fragSpace
FragmentSpace denoptim.graph.rings.RandomCombOfRingsIterator.fragSpace private
Space of building blocks.
Definition at line 46 of file RandomCombOfRingsIterator.java.
Referenced by denoptim.graph.rings.RandomCombOfRingsIterator.next(), and denoptim.graph.rings.RandomCombOfRingsIterator.RandomCombOfRingsIterator().
maxRingClosures
int denoptim.graph.rings.RandomCombOfRingsIterator.maxRingClosures = -1 private
Max number of ring closures to consider in a valid combination of rings.
Definition at line 41 of file RandomCombOfRingsIterator.java.
Referenced by denoptim.graph.rings.RandomCombOfRingsIterator.next(), and denoptim.graph.rings.RandomCombOfRingsIterator.RandomCombOfRingsIterator().
molGraph
DGraph denoptim.graph.rings.RandomCombOfRingsIterator.molGraph private
Graph representation of the system we work with.
Definition at line 36 of file RandomCombOfRingsIterator.java.
Referenced by denoptim.graph.rings.RandomCombOfRingsIterator.next(), and denoptim.graph.rings.RandomCombOfRingsIterator.RandomCombOfRingsIterator().
originalMol
IAtomContainer denoptim.graph.rings.RandomCombOfRingsIterator.originalMol private
Chemical representation of the system we work with.
Definition at line 31 of file RandomCombOfRingsIterator.java.
Referenced by denoptim.graph.rings.RandomCombOfRingsIterator.next().
settings
RingClosureParameters denoptim.graph.rings.RandomCombOfRingsIterator.settings private
Parameters related to rings.
Definition at line 51 of file RandomCombOfRingsIterator.java.
Referenced by denoptim.graph.rings.RandomCombOfRingsIterator.next().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/RandomCombOfRingsIterator.java