DENOPTIM: denoptim.gui.GUIVertexSelector Class Reference
denoptim.gui.GUIVertexSelector Class Reference
A modal dialog with a viewer that understands the different types of DENOPTIM vertex and allows to select vertices and, if needed, attachment points.
Classes
class VrtxSpinnerChangeEvent
Public Member Functions
GUIVertexSelector (Component refForPlacement, boolean use3rd)
Constructor for an empty modal panel meant for selection of vertexes.
void load (List< Vertex > fragments, int initialId)
Load the list of vertexes to choose from.
void setRequireApSelection (boolean enforced)
Allows to control whether confirming the selection of a vertex without having selected an attachment point is permitted or not.
Public Member Functions inherited from denoptim.gui.GUIModalDialog
GUIModalDialog (Component refForPlacement)
Constructor.
GUIModalDialog (Component refForPlacement, boolean useExtraButton)
Constructor.
Object showDialog ()
Shows the dialog and restrains the modality to it, until the dialog gets closed.
void addToNorthPane (JComponent comp)
Adds a component to the topmost part of this dialog frame.
void addToCentralPane (JComponent comp)
Adds a component to the central part of this dialog frame.
Static Public Attributes
static final String PRESELECTEDAPSFIELD = "pre-SelectedAPs"
Property used to pre-select APs.
static final String PRESELECTEDAPSFIELDSEP = "pre-SelectedAPs"
Separator in property used to pre-select APs.
Protected Attributes
JPanel ctrlPane
Protected Attributes inherited from denoptim.gui.GUIModalDialog
JButton btnDone
The button that is used to launch the processing of the data given to the open dialog, and close the dialog window.
JButton btnCanc
The button that is used to close the dialog without processing any input.
JButton btnExtra
The button that can be used for any action that does not close the dialog.
Object result = null
The result to be returned once the dialog is closed.
Private Member Functions
void appendToResult (int vrtxId, int apId)
void loadCurrentVrtxIdxToViewer ()
Loads the vertices corresponding to the field index.
void updateVrtxListSpinner ()
void clearCurrentSystem ()
void activateTabEditsListener (boolean var)
Private Attributes
List< Vertex > vertexLibrary
The currently loaded list of vertices.
Vertex vertex
The currently loaded vertex.
int currVrtxIdx = 0
The index of the currently loaded vertex [0–(n-1)}.
int currApIdx = -1
The index of the selected AP [0-(n-1)].
VertexViewPanel vertexViewer
JPanel navigPanel
JPanel navigPanel2
JSpinner navigSpinner
JLabel totalVerticesLabel
final VrtxSpinnerChangeEvent vrtxSpinnerListener
boolean enforceAPSelection = false
Static Private Attributes
static final long serialVersionUID = 912850110991449553L
Version UID.
Additional Inherited Members
Protected Member Functions inherited from denoptim.gui.GUIModalDialog
void close ()
Closes the dialog window.
Detailed Description
A modal dialog with a viewer that understands the different types of DENOPTIM vertex and allows to select vertices and, if needed, attachment points.
Author
Marco Foscato
Definition at line 48 of file GUIVertexSelector.java.
Constructor & Destructor Documentation
GUIVertexSelector()
denoptim.gui.GUIVertexSelector.GUIVertexSelector (Component refForPlacement, boolean use3rd)
Constructor for an empty modal panel meant for selection of vertexes.
Parameters
use3rd set true to request the third button in the control panel.
Definition at line 105 of file GUIVertexSelector.java.
References denoptim.gui.GUIModalDialog.addToCentralPane(), denoptim.gui.GUIModalDialog.addToNorthPane(), denoptim.gui.GUIVertexSelector.appendToResult(), denoptim.gui.GUIModalDialog.btnDone, denoptim.gui.GUIModalDialog.btnExtra, denoptim.gui.GUIModalDialog.close(), denoptim.gui.GUIVertexSelector.ctrlPane, denoptim.gui.GUIVertexSelector.currApIdx, denoptim.gui.GUIVertexSelector.currVrtxIdx, denoptim.gui.VertexViewPanel.dispose(), denoptim.gui.GUIVertexSelector.enforceAPSelection, denoptim.graph.Vertex.getNumberOfAPs(), denoptim.gui.VertexViewPanel.getSelectedAPIDs(), denoptim.gui.GUIVertexSelector.navigPanel, denoptim.gui.GUIVertexSelector.navigPanel2, denoptim.gui.GUIVertexSelector.navigSpinner, denoptim.gui.GUIVertexSelector.totalVerticesLabel, denoptim.gui.GUIVertexSelector.vertex, denoptim.gui.GUIVertexSelector.vertexViewer, and denoptim.gui.GUIVertexSelector.vrtxSpinnerListener.
Member Function Documentation
activateTabEditsListener()
void denoptim.gui.GUIVertexSelector.activateTabEditsListener (boolean var) private
Definition at line 363 of file GUIVertexSelector.java.
References denoptim.gui.VertexViewPanel.activateTabEditsListener(), and denoptim.gui.GUIVertexSelector.vertexViewer.
Referenced by denoptim.gui.GUIVertexSelector.VrtxSpinnerChangeEvent.stateChanged().
appendToResult()
void denoptim.gui.GUIVertexSelector.appendToResult (int vrtxId, int apId) private
Definition at line 247 of file GUIVertexSelector.java.
References denoptim.gui.GUIModalDialog.result.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
clearCurrentSystem()
void denoptim.gui.GUIVertexSelector.clearCurrentSystem () private
Definition at line 322 of file GUIVertexSelector.java.
References denoptim.gui.VertexViewPanel.clearCurrentSystem(), denoptim.gui.GUIVertexSelector.vertex, and denoptim.gui.GUIVertexSelector.vertexViewer.
Referenced by denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer().
load()
void denoptim.gui.GUIVertexSelector.load (List< Vertex > fragments, int initialId)
Load the list of vertexes to choose from.
Parameters
fragments the list of vertexes among which the usel will be allowed to chose.
initialId the index of the one vertex that should be displayed when showing the dialog.
Definition at line 234 of file GUIVertexSelector.java.
References denoptim.gui.GUIVertexSelector.currVrtxIdx, denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer(), denoptim.gui.GUIVertexSelector.updateVrtxListSpinner(), and denoptim.gui.GUIVertexSelector.vertexLibrary.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
loadCurrentVrtxIdxToViewer()
void denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer () private
Loads the vertices corresponding to the field index.
The molecular data is loaded in the Jmol viewer, and the attachment point (AP) information in the the list of APs. Jmol is not aware of AP-related information, so this also launches the generation of the graphical objects representing the APs.
Definition at line 294 of file GUIVertexSelector.java.
References denoptim.gui.GUIVertexSelector.clearCurrentSystem(), denoptim.gui.GUIVertexSelector.currVrtxIdx, denoptim.gui.VertexViewPanel.loadVertexToViewer(), denoptim.gui.GUIVertexSelector.vertex, denoptim.gui.GUIVertexSelector.vertexLibrary, and denoptim.gui.GUIVertexSelector.vertexViewer.
Referenced by denoptim.gui.GUIVertexSelector.load(), and denoptim.gui.GUIVertexSelector.VrtxSpinnerChangeEvent.stateChanged().
setRequireApSelection()
void denoptim.gui.GUIVertexSelector.setRequireApSelection (boolean enforced)
Allows to control whether confirming the selection of a vertex without having selected an attachment point is permitted or not.
Parameters
enforced use true to enforce the selection of an AP.
Definition at line 280 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.gui.GUIVertexInspector.initialize(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
updateVrtxListSpinner()
void denoptim.gui.GUIVertexSelector.updateVrtxListSpinner () private
Definition at line 313 of file GUIVertexSelector.java.
References denoptim.gui.GUIVertexSelector.currVrtxIdx, denoptim.gui.GUIVertexSelector.navigSpinner, denoptim.gui.GUIVertexSelector.totalVerticesLabel, and denoptim.gui.GUIVertexSelector.vertexLibrary.
Referenced by denoptim.gui.GUIVertexSelector.load().
Member Data Documentation
ctrlPane
JPanel denoptim.gui.GUIVertexSelector.ctrlPane protected
Definition at line 77 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.GUIVertexInspector.initialize().
currApIdx
int denoptim.gui.GUIVertexSelector.currApIdx = -1 private
The index of the selected AP [0-(n-1)].
Definition at line 74 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
currVrtxIdx
int denoptim.gui.GUIVertexSelector.currVrtxIdx = 0 private
The index of the currently loaded vertex [0–(n-1)}.
Definition at line 69 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector(), denoptim.gui.GUIVertexSelector.load(), denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer(), denoptim.gui.GUIVertexSelector.VrtxSpinnerChangeEvent.stateChanged(), and denoptim.gui.GUIVertexSelector.updateVrtxListSpinner().
enforceAPSelection
boolean denoptim.gui.GUIVertexSelector.enforceAPSelection = false private
Definition at line 86 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
navigPanel
JPanel denoptim.gui.GUIVertexSelector.navigPanel private
Definition at line 78 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
navigPanel2
JPanel denoptim.gui.GUIVertexSelector.navigPanel2 private
Definition at line 79 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
navigSpinner
JSpinner denoptim.gui.GUIVertexSelector.navigSpinner private
Definition at line 81 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector(), denoptim.gui.GUIVertexSelector.VrtxSpinnerChangeEvent.stateChanged(), and denoptim.gui.GUIVertexSelector.updateVrtxListSpinner().
PRESELECTEDAPSFIELD
final String denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELD = "pre-SelectedAPs" static
Property used to pre-select APs.
Definition at line 91 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.gui.FragmentViewPanel.preSelectAPs(), denoptim.gui.VertexAsGraphViewPanel.preSelectAPs(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs().
PRESELECTEDAPSFIELDSEP
final String denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELDSEP = "pre-SelectedAPs" static
Separator in property used to pre-select APs.
Definition at line 96 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.gui.FragmentViewPanel.preSelectAPs(), denoptim.gui.VertexAsGraphViewPanel.preSelectAPs(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs().
serialVersionUID
final long denoptim.gui.GUIVertexSelector.serialVersionUID = 912850110991449553L static private
Version UID.
Definition at line 53 of file GUIVertexSelector.java.
totalVerticesLabel
JLabel denoptim.gui.GUIVertexSelector.totalVerticesLabel private
Definition at line 82 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.GUIVertexSelector.updateVrtxListSpinner().
vertex
Vertex denoptim.gui.GUIVertexSelector.vertex private
The currently loaded vertex.
Definition at line 64 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.clearCurrentSystem(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer().
vertexLibrary
List<Vertex> denoptim.gui.GUIVertexSelector.vertexLibrary private
Initial value:
=
            new ArrayList<Vertex>()
The currently loaded list of vertices.
Definition at line 58 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.load(), denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer(), and denoptim.gui.GUIVertexSelector.updateVrtxListSpinner().
vertexViewer
VertexViewPanel denoptim.gui.GUIVertexSelector.vertexViewer private
Definition at line 76 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.activateTabEditsListener(), denoptim.gui.GUIVertexSelector.clearCurrentSystem(), denoptim.gui.GUIVertexSelector.GUIVertexSelector(), and denoptim.gui.GUIVertexSelector.loadCurrentVrtxIdxToViewer().
vrtxSpinnerListener
final VrtxSpinnerChangeEvent denoptim.gui.GUIVertexSelector.vrtxSpinnerListener private
Initial value:
=
            new VrtxSpinnerChangeEvent()
Definition at line 83 of file GUIVertexSelector.java.
Referenced by denoptim.gui.GUIVertexSelector.GUIVertexSelector().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIVertexSelector.java