DENOPTIM: denoptim.molecularmodeling.MultiMolecularModelBuilder Class Reference
denoptim.molecularmodeling.MultiMolecularModelBuilder Class Reference
Public Member Functions
MultiMolecularModelBuilder (String molName, DGraph molGraph, MMBuilderParameters settings)
ArrayList< IAtomContainer > buildMulti3DStructure () throws DENOPTIMException, TinkerException
Given the graph representation of the molecular constitution, along with the 3D coordinates of the fragments and direction vectors, create 3D structures by merging internal coordinates.
ChemicalObjectModel build3DTree () throws DENOPTIMException
Generate 3D structure by assembling 3D fragments according to attachment point vector and following the tree-like structure of the graph.
Private Attributes
String molName
DGraph molGraph
MMBuilderParameters settings
Logger logger
Program-specific logger.
Detailed Description
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 51 of file MultiMolecularModelBuilder.java.
Constructor & Destructor Documentation
MultiMolecularModelBuilder()
denoptim.molecularmodeling.MultiMolecularModelBuilder.MultiMolecularModelBuilder (String molName, DGraph molGraph, MMBuilderParameters settings)
Definition at line 65 of file MultiMolecularModelBuilder.java.
References denoptim.programs.RunTimeParameters.getLogger(), denoptim.molecularmodeling.MultiMolecularModelBuilder.molGraph, denoptim.molecularmodeling.MultiMolecularModelBuilder.molName, and denoptim.molecularmodeling.MultiMolecularModelBuilder.settings.
Member Function Documentation
build3DTree()
ChemicalObjectModel denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree () throws DENOPTIMException
Generate 3D structure by assembling 3D fragments according to attachment point vector and following the tree-like structure of the graph.
Exceptions
DENOPTIMException
Definition at line 232 of file MultiMolecularModelBuilder.java.
References denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.utils.RotationalSpaceUtils.defineRotatableBonds(), denoptim.programs.RunTimeParameters.ParametersType.FS_PARAMS, denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getAtomOrderingScheme(), denoptim.integration.tinker.TinkerUtils.getICFromIAC(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.utils.AtomOrganizer.getNewToOldOrder(), denoptim.utils.AtomOrganizer.getOldToNewOrder(), denoptim.programs.RunTimeParameters.getParameters(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTinkerMap(), denoptim.molecularmodeling.MultiMolecularModelBuilder.logger, denoptim.molecularmodeling.MultiMolecularModelBuilder.molGraph, denoptim.molecularmodeling.MultiMolecularModelBuilder.molName, denoptim.utils.AtomOrganizer.reorderStartingFrom(), denoptim.utils.AtomOrganizer.setScheme(), denoptim.molecularmodeling.MultiMolecularModelBuilder.settings, denoptim.integration.tinker.TinkerUtils.setTinkerTypes(), and denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
buildMulti3DStructure()
ArrayList< IAtomContainer > denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure () throws DENOPTIMException, TinkerException
Given the graph representation of the molecular constitution, along with the 3D coordinates of the fragments and direction vectors, create 3D structures by merging internal coordinates.
More than one structure can be obtained if the provided graph allows for isomerism for example by multiple possibility of ring formation or conformational isomerism (not implemented yet).
Exceptions
TinkerException if Tinker fails
Definition at line 87 of file MultiMolecularModelBuilder.java.
References denoptim.graph.rings.RingClosureParameters.allowRingClosures(), denoptim.constants.DENOPTIMConstants.ATMPROPVERTEXID, denoptim.molecularmodeling.RingClosureTool.attemptAllRingClosures(), denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), denoptim.programs.RunTimeParameters.containsParameters(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.molecularmodeling.ChemicalObjectModel.getGraph(), denoptim.molecularmodeling.ChemicalObjectModel.getIAtomContainer(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getInitPSSROTParams(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeepDummyFlag(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getKeyFileParams(), denoptim.programs.RunTimeParameters.getParameters(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getParamFile(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getPSSROTTool(), denoptim.molecularmodeling.ChemicalObjectModel.getRCACombinations(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getRestPSSROTParams(), denoptim.molecularmodeling.ChemicalObjectModel.getRotatableBonds(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getTaskID(), denoptim.graph.DGraph.getVertexList(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getWorkingDirectory(), denoptim.programs.moldecularmodelbuilder.MMBuilderParameters.getXYZINTTool(), denoptim.graph.DGraph.hasOrEmbedsRings(), denoptim.molecularmodeling.MultiMolecularModelBuilder.logger, denoptim.utils.AtomOrganizer.makeReorderedCopy(), denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.molecularmodeling.MultiMolecularModelBuilder.molGraph, denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.programs.RunTimeParameters.ParametersType.RC_PARAMS, denoptim.utils.DummyAtomHandler.removeDummy(), denoptim.utils.DummyAtomHandler.removeDummyInHapto(), denoptim.graph.rings.RingClosureParameters.requireCompleteRingclosure, denoptim.molecularmodeling.RingClosureTool.saturateRingClosingAttractor(), denoptim.molecularmodeling.MultiMolecularModelBuilder.settings, and denoptim.graph.DGraph.toString().
Referenced by denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
Member Data Documentation
logger
Logger denoptim.molecularmodeling.MultiMolecularModelBuilder.logger private
Program-specific logger.
Definition at line 61 of file MultiMolecularModelBuilder.java.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
molGraph
DGraph denoptim.molecularmodeling.MultiMolecularModelBuilder.molGraph private
Definition at line 54 of file MultiMolecularModelBuilder.java.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.MultiMolecularModelBuilder().
molName
String denoptim.molecularmodeling.MultiMolecularModelBuilder.molName private
Definition at line 53 of file MultiMolecularModelBuilder.java.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.MultiMolecularModelBuilder().
settings
MMBuilderParameters denoptim.molecularmodeling.MultiMolecularModelBuilder.settings private
Definition at line 56 of file MultiMolecularModelBuilder.java.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.MultiMolecularModelBuilder().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/MultiMolecularModelBuilder.java