DENOPTIM: denoptim.logging.StaticLogger Class Reference
denoptim.logging.StaticLogger Class Reference
Logger class for DENOPTIM.
Public Member Functions
final Object clone () throws CloneNotSupportedException
Clone is not supported!
Static Public Member Functions
static synchronized StaticLogger getInstance ()
Static Public Attributes
static final Logger appLogger = Logger.getLogger("DENOPTIMLogger")
Private Member Functions
StaticLogger ()
Static Private Attributes
static StaticLogger uniqInstance = null
Detailed Description
Logger class for DENOPTIM.
Author
Vishwesh Venkatraman
Definition at line 29 of file StaticLogger.java.
Constructor & Destructor Documentation
StaticLogger()
denoptim.logging.StaticLogger.StaticLogger () private
Definition at line 36 of file StaticLogger.java.
Referenced by denoptim.logging.StaticLogger.getInstance().
Member Function Documentation
clone()
final Object denoptim.logging.StaticLogger.clone () throws CloneNotSupportedException
Clone is not supported!
Returns
Exceptions
CloneNotSupportedException
Definition at line 60 of file StaticLogger.java.
getInstance()
static synchronized StaticLogger denoptim.logging.StaticLogger.getInstance () static
Definition at line 43 of file StaticLogger.java.
References denoptim.logging.StaticLogger.StaticLogger(), and denoptim.logging.StaticLogger.uniqInstance.
Member Data Documentation
appLogger
final Logger denoptim.logging.StaticLogger.appLogger = Logger.getLogger("DENOPTIMLogger") static
Definition at line 31 of file StaticLogger.java.
Referenced by denoptim.files.FileUtils.addToRecentFiles(), denoptim.task.ProgramTask.call(), denoptim.graph.rings.RingClosureParameters.checkParameters(), denoptim.programs.combinatorial.CEBLParameters.checkParameters(), denoptim.utils.MoleculeUtils.ensureNoUnsetBondOrdersSilent(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), denoptim.graph.Vertex.parseVertexFromSDFFormat(), denoptim.task.ProgramTask.printErrorToFile(), denoptim.programs.combinatorial.CEBLParameters.processParameters(), denoptim.programs.denovo.GAParameters.processParameters(), denoptim.programs.fitnessevaluator.FRParameters.processParameters(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), denoptim.programs.grapheditor.GraphEdParameters.readInputGraphs(), denoptim.io.DenoptimIO.readRecentFilesMap(), denoptim.ga.ExternalCmdsListener.run(), and denoptim.programs.fitnessevaluator.FPRunner.run().
uniqInstance
StaticLogger denoptim.logging.StaticLogger.uniqInstance = null static private
Definition at line 32 of file StaticLogger.java.
Referenced by denoptim.logging.StaticLogger.getInstance().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/logging/StaticLogger.java