DENOPTIM: denoptim.graph.APTreeMap Class Reference
denoptim.graph.APTreeMap Class Reference
Attachment point mapping where keys are sorted by natural ordering, i.e., by AttachmentPoint#compareTo(AttachmentPoint).
Classes
class APMapSerializer
Method that serializes this class without creating loops of references.
Public Member Functions
AttachmentPoint put (AttachmentPoint key, AttachmentPoint value)
AttachmentPoint remove (Object key)
AttachmentPoint get (Object key)
Static Private Attributes
static final long serialVersionUID = 3L
Version identifier.
Detailed Description
Attachment point mapping where keys are sorted by natural ordering, i.e., by AttachmentPoint#compareTo(AttachmentPoint).
Since there can be attachment points that have the same identifier, but are indeed diverse instances, this class overwrites the TreeMap#put(Object, Object) method to ensure that keys a and b that return false at a == b are updated to acquire unique identifiers.
Definition at line 42 of file APTreeMap.java.
Member Function Documentation
get()
AttachmentPoint denoptim.graph.APTreeMap.get (Object key)
Definition at line 95 of file APTreeMap.java.
Referenced by denoptim.graph.Template.getOuterAPFromInnerAP(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.Template.removeProjectionOfInnerAP(), and denoptim.graph.Template.updateInnerApID().
put()
AttachmentPoint denoptim.graph.APTreeMap.put (AttachmentPoint key, AttachmentPoint value)
Definition at line 79 of file APTreeMap.java.
Referenced by denoptim.graph.Template.addInnerToOuterAPMapping(), denoptim.graph.Template.updateInnerApID(), and denoptim.graph.Template.updateInnerToOuter().
remove()
AttachmentPoint denoptim.graph.APTreeMap.remove (Object key)
Definition at line 87 of file APTreeMap.java.
Referenced by denoptim.graph.Template.removeProjectionOfInnerAP(), and denoptim.graph.Template.updateInnerApID().
Member Data Documentation
serialVersionUID
final long denoptim.graph.APTreeMap.serialVersionUID = 3L static private
Version identifier.
Definition at line 47 of file APTreeMap.java.
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/APTreeMap.java