DENOPTIM: denoptim.graph.FragmentIsomorphismInspector Class Reference
denoptim.graph.FragmentIsomorphismInspector Class Reference
Public Member Functions
FragmentIsomorphismInspector (Fragment fragA, Fragment fragB)
Constructs a default inspector with a timeout runtime of 60 seconds.
FragmentIsomorphismInspector (Fragment fragA, Fragment fragB, boolean ignoreAPClasses)
Constructs a default inspector with a timeout runtime of 60 seconds.
FragmentIsomorphismInspector (Fragment fragA, Fragment fragB, int timeout, boolean ignoreAPClasses)
Constructs an inspector with a custom timeout limit.
boolean isomorphismExists ()
Checks if an isomorphism exists between the two fragments.
Iterator< GraphMapping< FragIsomorphNode, FragIsomorphEdge > > getMappings ()
Protected Attributes
boolean reportTimeoutIncidents = true
Flag indicating if we print earning in case of timeout or not.
Package Attributes
VF2GraphIsomorphismInspector< FragIsomorphNode, FragIsomorphEdge > vf2
Implementation of the Vento-Foggia 2 algorithm.
Private Attributes
int timeout
The maximum time we give the VF2 algorithm (seconds)
Fragment fragA
One fragment being analyzed.
Fragment fragB
The other fragment being analyzed.
Detailed Description
Inspector for isomorphism on fragments. The graph representation considered is one where both atoms and AttachmentPoints are represented as graph nodes, and edges are either bonds or atom-to-attachment point connections.
Effectively, this class considers the composition and connectivity (including that of AttachmentPoints when comparing the fragments. Geometry and stereochemistry are not considered.
This works with the VF2GraphIsomorphismInspector, see the dedicated documentation for information of pathological cases.
Author
Marco Foscato
Definition at line 34 of file FragmentIsomorphismInspector.java.
Constructor & Destructor Documentation
FragmentIsomorphismInspector() [1/3]
denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector (Fragment fragA, Fragment fragB)
Constructs a default inspector with a timeout runtime of 60 seconds.
Parameters
fragA
fragB
Definition at line 69 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.fragA, and denoptim.graph.FragmentIsomorphismInspector.fragB.
FragmentIsomorphismInspector() [2/3]
denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector (Fragment fragA, Fragment fragB, boolean ignoreAPClasses)
Constructs a default inspector with a timeout runtime of 60 seconds.
Parameters
fragA
fragB
ignoreAPClasses
Definition at line 82 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.fragA, and denoptim.graph.FragmentIsomorphismInspector.fragB.
FragmentIsomorphismInspector() [3/3]
denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector (Fragment fragA, Fragment fragB, int timeout, boolean ignoreAPClasses)
Constructs an inspector with a custom timeout limit.
Parameters
fragA one fragment to compare
fragB the other fragment to compare
timeout maximum amount of time (milliseconds) given to the inspector for performing any task. associated with returning from any public method in this class.
Definition at line 99 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.fragA, denoptim.graph.FragmentIsomorphismInspector.fragB, denoptim.graph.Fragment.getJGraphFragIsomorphism(), denoptim.graph.FragIsomorphNode.isAtm, denoptim.graph.FragIsomorphEdge.label, denoptim.graph.FragIsomorphNode.label, denoptim.graph.FragmentIsomorphismInspector.timeout, and denoptim.graph.FragmentIsomorphismInspector.vf2.
Member Function Documentation
getMappings()
Iterator< GraphMapping< FragIsomorphNode, FragIsomorphEdge > > denoptim.graph.FragmentIsomorphismInspector.getMappings ()
Definition at line 192 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.fragA, denoptim.graph.FragmentIsomorphismInspector.fragB, denoptim.graph.FragmentIsomorphismInspector.reportTimeoutIncidents, denoptim.graph.FragmentIsomorphismInspector.timeout, denoptim.graph.Fragment.toJson(), denoptim.graph.FragmentIsomorphismInspector.vf2, and denoptim.io.DenoptimIO.writeVertexesToSDF().
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement().
isomorphismExists()
boolean denoptim.graph.FragmentIsomorphismInspector.isomorphismExists ()
Checks if an isomorphism exists between the two fragments.
Returns
true is an isomorphism has been found.
Definition at line 145 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.fragA, denoptim.graph.FragmentIsomorphismInspector.fragB, denoptim.graph.FragmentIsomorphismInspector.reportTimeoutIncidents, denoptim.graph.FragmentIsomorphismInspector.timeout, denoptim.graph.Fragment.toJson(), denoptim.graph.FragmentIsomorphismInspector.vf2, and denoptim.io.DenoptimIO.writeVertexesToSDF().
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement(), denoptim.graph.Fragment.isIsomorphicTo(), denoptim.graph.FragmentIsomorphismInspectorTest.testIsomorphismExists(), and denoptim.graph.FragmentIsomorphismInspectorTest.testTimeout().
Member Data Documentation
fragA
Fragment denoptim.graph.FragmentIsomorphismInspector.fragA private
One fragment being analyzed.
Definition at line 44 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
fragB
Fragment denoptim.graph.FragmentIsomorphismInspector.fragB private
The other fragment being analyzed.
Definition at line 49 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
reportTimeoutIncidents
boolean denoptim.graph.FragmentIsomorphismInspector.reportTimeoutIncidents = true protected
Flag indicating if we print earning in case of timeout or not.
Definition at line 54 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
timeout
int denoptim.graph.FragmentIsomorphismInspector.timeout private
The maximum time we give the VF2 algorithm (seconds)
Definition at line 39 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
vf2
VF2GraphIsomorphismInspector<FragIsomorphNode, FragIsomorphEdge> denoptim.graph.FragmentIsomorphismInspector.vf2 package
Implementation of the Vento-Foggia 2 algorithm.
Definition at line 59 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/FragmentIsomorphismInspector.java