DENOPTIM: denoptim.graph.rings.PathClosabilityToolsTest Class Reference
denoptim.graph.rings.PathClosabilityToolsTest Class Reference
Unit test for path closability tools.
Public Member Functions
void testEvaluateConstitutionalClosability () throws Exception
Detailed Description
Unit test for path closability tools.
Author
Marco Foscato
Definition at line 61 of file PathClosabilityToolsTest.java.
Member Function Documentation
testEvaluateConstitutionalClosability()
void denoptim.graph.rings.PathClosabilityToolsTest.testEvaluateConstitutionalClosability () throws Exception
Definition at line 67 of file PathClosabilityToolsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Fragment.clone(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getRCVertices(), denoptim.graph.rings.PathClosabilityTools.isCloseable(), denoptim.graph.APClass.make(), denoptim.graph.APClass.RCACLASSMINUS, denoptim.graph.APClass.RCACLASSPLUS, denoptim.graph.rings.RingClosingAttractor.RCALABELPERAPCLASS, denoptim.molecularmodeling.ThreeDimTreeBuilder.setAlignBBsIn3D(), denoptim.graph.Vertex.setAsRCV(), denoptim.graph.rings.RingClosureParameters.setConstitutionalClosabilityConds(), and denoptim.graph.Vertex.setVertexId().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/rings/PathClosabilityToolsTest.java