DENOPTIM: denoptim.molecularmodeling.ChemicalObjectModel Class Reference
denoptim.molecularmodeling.ChemicalObjectModel Class Reference
Collector of molecular information, related to a single chemical object, that is deployed within the 3D builder.
Public Member Functions
ChemicalObjectModel (DGraph molGraph, IAtomContainer fmol, ZMatrix zmat, String molName, List< ObjectPair > rotatableBnds, List< RingClosingAttractor > attractors, Map< RingClosingAttractor, Integer > attToAtmID, List< Set< ObjectPair > > allRCACombs, List< RingClosure > ringClosures, List< Integer > oldToNewOrder, List< Integer > newToOldOrder, Logger logger)
Constructs an item specifying all its features.
ChemicalObjectModel (DGraph molGraph, IAtomContainer fmol, ZMatrix zmat, String molName, List< ObjectPair > rotatableBnds, List< Integer > oldToNewOrder, List< Integer > newToOldOrder, Logger logger) throws DENOPTIMException
Constructs a Molecule3DBuilder specifying all its features.
List< Integer > getOldToNewOrder ()
List< Integer > getNewToOldOrder ()
void updateXYZ (List< Point3d > newCoords) throws DENOPTIMException
currently loaded internal coordinates into Cartesian overwriting the current XYZ.
void updateXYZFromINT () throws DENOPTIMException
Converts currently loaded internal coordinates into Cartesian overwriting the current XYZ.
DGraph getGraph ()
Returns the graph representation of this molecule as it was originally generated by DEOPTIM.
IAtomContainer getIAtomContainer ()
Returns the CDK representation of the molecular system.
ZMatrix getZMatrix ()
Returns the ZMatrix representation of the molecule.
List< RingClosingAttractor > getAttractorsList ()
Returns the list of RuingClosingAttractors.
RingClosingAttractor getAttractor (int i)
Returns the attractor given its position in the list of attractors.
int getZMatIdxOfRCA (RingClosingAttractor rca)
int getZMatIdxOfRCASrc (RingClosingAttractor rca)
List< Set< ObjectPair > > getRCACombinations ()
Returns the list of combinations of RingClosingAttractor.
List< ObjectPair > getRotatableBonds ()
Returns the list of rotatable bonds.
int getNumberRotatableBonds ()
Returns the size of the current list of rotatable bonds.
List< RingClosure > getNewRingClosures ()
Return the list of RingClosures that have been identified as closable head/tail of atom chains during RC-PSSROT conformational adaptation.
double getNewRingClosuresQuality ()
Return the overal evaluation of the whole list of RingClosures.
double getAtomOverlapScore ()
Return the atoms overlap score which is calculated for all atoms pairs not in 1-4 or lower relationship.
String getName ()
Return the name of this molecule.
void addBond (IAtom atmA, IAtom atmB, RingClosure nRc, BondType bndTyp)
Modify the molecule adding a cyclic bond between two atoms.
void purgeListRotatableBonds () throws DENOPTIMException
Remove the cyclic bonds from the list of rotatable bonds.
ChemicalObjectModel deepcopy () throws DENOPTIMException
Return a new Molecule3DBuilder having exactly the same features of this Molecule3DBuilder.
Private Member Functions
void findAttractors ()
void convertRingsToRCACombinations ()
Private Attributes
DGraph molGraph
DENOPTIM representation.
IAtomContainer fmol
CDK representation.
ZMatrix zmat
ZMatrix representation.
String molName
Reference name.
List< RingClosingAttractor > attractors
List of RingClosingAttractors.
Map< RingClosingAttractor, Integer > attToAtmID
Relation between RingClosingAttractor and index in the ZMatrix.
List< Set< ObjectPair > > allRCACombs
List of combinations of RingClosingAttractor (i.e., possible set of rings to create)
List< ObjectPair > rotatableBnds
List of rotatable bonds.
List< RingClosure > newRingClosures
List of new ring closing environments.
double overalRCScore = Double.NaN
Quality score of the list of ring closures.
double atmOveralScore = Double.NaN
Atom overlap score (for atoms not is 1-4 or lower relationship)
Logger logger
Program-specific logger.
List< Integer > oldToNewOrder
List< Integer > newToOldOrder
Detailed Description
Collector of molecular information, related to a single chemical object, that is deployed within the 3D builder.
Author
Marco Foscato
Definition at line 60 of file ChemicalObjectModel.java.
Constructor & Destructor Documentation
ChemicalObjectModel() [1/2]
denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel (DGraph molGraph, IAtomContainer fmol, ZMatrix zmat, String molName, List< ObjectPair > rotatableBnds, List< RingClosingAttractor > attractors, Map< RingClosingAttractor, Integer > attToAtmID, List< Set< ObjectPair > > allRCACombs, List< RingClosure > ringClosures, List< Integer > oldToNewOrder, List< Integer > newToOldOrder, Logger logger)
Constructs an item specifying all its features.
Parameters
molGraph the graph representation
fmol the CDK molecular representation
zmat the internal coordinates representation
molName the reference name of this molecule
rotatableBnds the list of rotatable bonds (as pairs of atom indexes)
attractors all the ring closing attractors (RCA)
attToAtmID the correspondence between RCA and atom index in the ZMatrix
allRCACombs all combinations of compatible pairs of RCAs
ringClosures the list of closed multi-fragment rings
logger the tool to use for logging.
Definition at line 144 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.allRCACombs, denoptim.molecularmodeling.ChemicalObjectModel.attractors, denoptim.molecularmodeling.ChemicalObjectModel.attToAtmID, denoptim.molecularmodeling.ChemicalObjectModel.convertRingsToRCACombinations(), denoptim.molecularmodeling.ChemicalObjectModel.fmol, denoptim.graph.DGraph.hasOrEmbedsRings(), denoptim.molecularmodeling.ChemicalObjectModel.logger, denoptim.molecularmodeling.ChemicalObjectModel.molGraph, denoptim.molecularmodeling.ChemicalObjectModel.molName, denoptim.molecularmodeling.ChemicalObjectModel.newToOldOrder, denoptim.molecularmodeling.ChemicalObjectModel.oldToNewOrder, denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds, and denoptim.molecularmodeling.ChemicalObjectModel.zmat.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.deepcopy().
ChemicalObjectModel() [2/2]
denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel (DGraph molGraph, IAtomContainer fmol, ZMatrix zmat, String molName, List< ObjectPair > rotatableBnds, List< Integer > oldToNewOrder, List< Integer > newToOldOrder, Logger logger) throws DENOPTIMException
Constructs a Molecule3DBuilder specifying all its features.
Parameters
molGraph the graph representation
fmol the CDK molecular representation
zmat the internal coordinates representation
molName the reference name of this molecule
rotatableBnds the list of rotatable bonds (as pairs of atom
oldToNewOrder indexes that allow to map the atom position before and after the reordering needed to make use of internal coordinates possible.
newToOldOrder indexes that allow to map the atom position before and after the reordering needed to make use of internal coordinates possible.
logger the tool dealing with log messages. indexes)
Definition at line 200 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.convertRingsToRCACombinations(), denoptim.molecularmodeling.ChemicalObjectModel.findAttractors(), denoptim.molecularmodeling.ChemicalObjectModel.fmol, denoptim.graph.DGraph.hasOrEmbedsRings(), denoptim.molecularmodeling.ChemicalObjectModel.logger, denoptim.molecularmodeling.ChemicalObjectModel.molGraph, denoptim.molecularmodeling.ChemicalObjectModel.molName, denoptim.molecularmodeling.ChemicalObjectModel.newToOldOrder, denoptim.molecularmodeling.ChemicalObjectModel.oldToNewOrder, denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds, denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT(), and denoptim.molecularmodeling.ChemicalObjectModel.zmat.
Member Function Documentation
addBond()
void denoptim.molecularmodeling.ChemicalObjectModel.addBond (IAtom atmA, IAtom atmB, RingClosure nRc, BondType bndTyp)
Modify the molecule adding a cyclic bond between two atoms.
This method is ONLY meant to add new cyclic bonds and requires that the pair of involved atoms comes with the object RingClosure.
Parameters
atmA the first atom
atmA the second atom
nRc the RingClosure object describing the ring-closing arrangement of atoms.
Definition at line 704 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.addBond(), denoptim.molecularmodeling.ChemicalObjectModel.fmol, denoptim.graph.Edge.BondType.getCDKOrder(), denoptim.graph.Edge.BondType.hasCDKAnalogue(), and denoptim.molecularmodeling.ChemicalObjectModel.logger.
Referenced by denoptim.molecularmodeling.RingClosureTool.closeRings().
convertRingsToRCACombinations()
void denoptim.molecularmodeling.ChemicalObjectModel.convertRingsToRCACombinations () private
Definition at line 266 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.allRCACombs, denoptim.molecularmodeling.ChemicalObjectModel.attractors, and denoptim.graph.rings.RingClosingAttractor.getRingUser().
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel().
deepcopy()
ChemicalObjectModel denoptim.molecularmodeling.ChemicalObjectModel.deepcopy () throws DENOPTIMException
Return a new Molecule3DBuilder having exactly the same features of this Molecule3DBuilder.
Exceptions
DENOPTIMException
Definition at line 782 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.attractors, denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.graph.DGraph.clone(), denoptim.molecularmodeling.zmatrix.ZMatrix.clone(), denoptim.molecularmodeling.ChemicalObjectModel.logger, denoptim.molecularmodeling.ChemicalObjectModel.molName, denoptim.molecularmodeling.ChemicalObjectModel.newToOldOrder, and denoptim.molecularmodeling.ChemicalObjectModel.oldToNewOrder.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptAllRingClosures(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
findAttractors()
void denoptim.molecularmodeling.ChemicalObjectModel.findAttractors () private
Definition at line 250 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.attractors, denoptim.molecularmodeling.ChemicalObjectModel.attToAtmID, denoptim.molecularmodeling.ChemicalObjectModel.fmol, and denoptim.graph.rings.RingClosingAttractor.isAttractor().
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel().
getAtomOverlapScore()
double denoptim.molecularmodeling.ChemicalObjectModel.getAtomOverlapScore ()
Return the atoms overlap score which is calculated for all atoms pairs not in 1-4 or lower relationship.
Definition at line 647 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.atmOveralScore, denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, and denoptim.molecularmodeling.ChemicalObjectModel.fmol.
Referenced by denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator.compare().
getAttractor()
RingClosingAttractor denoptim.molecularmodeling.ChemicalObjectModel.getAttractor (int i)
Returns the attractor given its position in the list of attractors.
Definition at line 541 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.attractors.
getAttractorsList()
List< RingClosingAttractor > denoptim.molecularmodeling.ChemicalObjectModel.getAttractorsList ()
Returns the list of RuingClosingAttractors.
Definition at line 530 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.attractors.
getGraph()
DGraph denoptim.molecularmodeling.ChemicalObjectModel.getGraph ()
Returns the graph representation of this molecule as it was originally generated by DEOPTIM.
No change is expected after ring-closing step
Definition at line 497 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.molGraph.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getIAtomContainer()
IAtomContainer denoptim.molecularmodeling.ChemicalObjectModel.getIAtomContainer ()
Returns the CDK representation of the molecular system.
Definition at line 508 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.fmol.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptAllRingClosures(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getName()
String denoptim.molecularmodeling.ChemicalObjectModel.getName ()
Return the name of this molecule.
Definition at line 687 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.molName.
getNewRingClosures()
List< RingClosure > denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosures ()
Return the list of RingClosures that have been identified as closable head/tail of atom chains during RC-PSSROT conformational adaptation.
Definition at line 615 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.newRingClosures.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptAllRingClosures(), and denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator.compare().
getNewRingClosuresQuality()
double denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosuresQuality ()
Return the overal evaluation of the whole list of RingClosures.
Definition at line 626 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.newRingClosures, and denoptim.molecularmodeling.ChemicalObjectModel.overalRCScore.
Referenced by denoptim.molecularmodeling.RingClosureTool.RingClosedMolComparator.compare().
getNewToOldOrder()
List< Integer > denoptim.molecularmodeling.ChemicalObjectModel.getNewToOldOrder ()
Definition at line 243 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.newToOldOrder.
getNumberRotatableBonds()
int denoptim.molecularmodeling.ChemicalObjectModel.getNumberRotatableBonds ()
Returns the size of the current list of rotatable bonds.
Definition at line 603 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds.
getOldToNewOrder()
List< Integer > denoptim.molecularmodeling.ChemicalObjectModel.getOldToNewOrder ()
Definition at line 236 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.oldToNewOrder.
getRCACombinations()
List< Set< ObjectPair > > denoptim.molecularmodeling.ChemicalObjectModel.getRCACombinations ()
Returns the list of combinations of RingClosingAttractor.
This method require that there are Rings in the DGraph representation of this object.
Definition at line 581 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.allRCACombs.
Referenced by denoptim.molecularmodeling.RingClosureTool.attemptAllRingClosures(), and denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getRotatableBonds()
List< ObjectPair > denoptim.molecularmodeling.ChemicalObjectModel.getRotatableBonds ()
Returns the list of rotatable bonds.
Definition at line 592 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds.
Referenced by denoptim.molecularmodeling.MultiMolecularModelBuilder.buildMulti3DStructure().
getZMatIdxOfRCA()
int denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCA (RingClosingAttractor rca)
Returns
the index of the given RingClosingAttractor in the ZMatrix representation
Definition at line 553 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.attToAtmID.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCASrc().
getZMatIdxOfRCASrc()
int denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCASrc (RingClosingAttractor rca)
Returns
the index of the source atom of the given RingClosingAttractor (i.e., the only atom bonded to the
RingClosingAttractor) in the ZMatrix representation.
Definition at line 566 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex(), denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCA(), and denoptim.molecularmodeling.ChemicalObjectModel.zmat.
getZMatrix()
ZMatrix denoptim.molecularmodeling.ChemicalObjectModel.getZMatrix ()
Returns the ZMatrix representation of the molecule.
Definition at line 519 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.zmat.
purgeListRotatableBonds()
void denoptim.molecularmodeling.ChemicalObjectModel.purgeListRotatableBonds () throws DENOPTIMException
Remove the cyclic bonds from the list of rotatable bonds.
Exceptions
DENOPTIMException
Definition at line 738 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.fmol, denoptim.molecularmodeling.ChemicalObjectModel.logger, and denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds.
updateXYZ()
void denoptim.molecularmodeling.ChemicalObjectModel.updateXYZ (List< Point3d > newCoords) throws DENOPTIMException
currently loaded internal coordinates into Cartesian overwriting the current XYZ.
Definition at line 301 of file ChemicalObjectModel.java.
References denoptim.molecularmodeling.ChemicalObjectModel.fmol.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
updateXYZFromINT()
void denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT () throws DENOPTIMException
Converts currently loaded internal coordinates into Cartesian overwriting the current XYZ.
Definition at line 316 of file ChemicalObjectModel.java.
References denoptim.utils.MathUtils.distance(), denoptim.constants.DENOPTIMConstants.FLOATCOMPARISONTOLERANCE, denoptim.molecularmodeling.ChemicalObjectModel.fmol, denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2RefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngle2Value(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getAngleValue(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondLength(), denoptim.molecularmodeling.zmatrix.ZMatrix.getBondRefAtomIndex(), denoptim.molecularmodeling.zmatrix.ZMatrix.getChiralFlag(), denoptim.molecularmodeling.ChemicalObjectModel.logger, denoptim.utils.MathUtils.normDist(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZ(), and denoptim.molecularmodeling.ChemicalObjectModel.zmat.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityMinusOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ChiralityOne(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FirstAtomAtOrigin(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_FourthAtomWithDihedral(), denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_SecondAtomAlongZAxis(), and denoptim.molecularmodeling.ChemicalObjectModelTest.testUpdateXYZFromINT_ThirdAtomWithAngle().
Member Data Documentation
allRCACombs
List<Set<ObjectPair> > denoptim.molecularmodeling.ChemicalObjectModel.allRCACombs private
List of combinations of RingClosingAttractor (i.e., possible set of rings to create)
Definition at line 96 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.convertRingsToRCACombinations(), and denoptim.molecularmodeling.ChemicalObjectModel.getRCACombinations().
atmOveralScore
double denoptim.molecularmodeling.ChemicalObjectModel.atmOveralScore = Double.NaN private
Atom overlap score (for atoms not is 1-4 or lower relationship)
Definition at line 116 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.getAtomOverlapScore().
attractors
List<RingClosingAttractor> denoptim.molecularmodeling.ChemicalObjectModel.attractors private
List of RingClosingAttractors.
Definition at line 85 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.convertRingsToRCACombinations(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), denoptim.molecularmodeling.ChemicalObjectModel.findAttractors(), denoptim.molecularmodeling.ChemicalObjectModel.getAttractor(), and denoptim.molecularmodeling.ChemicalObjectModel.getAttractorsList().
attToAtmID
Map<RingClosingAttractor,Integer> denoptim.molecularmodeling.ChemicalObjectModel.attToAtmID private
Relation between RingClosingAttractor and index in the ZMatrix.
Definition at line 90 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.findAttractors(), and denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCA().
fmol
IAtomContainer denoptim.molecularmodeling.ChemicalObjectModel.fmol private
CDK representation.
Definition at line 70 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.addBond(), denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.findAttractors(), denoptim.molecularmodeling.ChemicalObjectModel.getAtomOverlapScore(), denoptim.molecularmodeling.ChemicalObjectModel.getIAtomContainer(), denoptim.molecularmodeling.ChemicalObjectModel.purgeListRotatableBonds(), denoptim.molecularmodeling.ChemicalObjectModel.updateXYZ(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
logger
Logger denoptim.molecularmodeling.ChemicalObjectModel.logger private
Program-specific logger.
Definition at line 121 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.addBond(), denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), denoptim.molecularmodeling.ChemicalObjectModel.purgeListRotatableBonds(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
molGraph
DGraph denoptim.molecularmodeling.ChemicalObjectModel.molGraph private
DENOPTIM representation.
Definition at line 65 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), and denoptim.molecularmodeling.ChemicalObjectModel.getGraph().
molName
String denoptim.molecularmodeling.ChemicalObjectModel.molName private
Reference name.
Definition at line 80 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), and denoptim.molecularmodeling.ChemicalObjectModel.getName().
newRingClosures
List<RingClosure> denoptim.molecularmodeling.ChemicalObjectModel.newRingClosures private
List of new ring closing environments.
Definition at line 106 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosures(), and denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosuresQuality().
newToOldOrder
List<Integer> denoptim.molecularmodeling.ChemicalObjectModel.newToOldOrder private
Definition at line 124 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), and denoptim.molecularmodeling.ChemicalObjectModel.getNewToOldOrder().
oldToNewOrder
List<Integer> denoptim.molecularmodeling.ChemicalObjectModel.oldToNewOrder private
Definition at line 123 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.deepcopy(), and denoptim.molecularmodeling.ChemicalObjectModel.getOldToNewOrder().
overalRCScore
double denoptim.molecularmodeling.ChemicalObjectModel.overalRCScore = Double.NaN private
Quality score of the list of ring closures.
Definition at line 111 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.getNewRingClosuresQuality().
rotatableBnds
List<ObjectPair> denoptim.molecularmodeling.ChemicalObjectModel.rotatableBnds private
List of rotatable bonds.
Definition at line 101 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.getNumberRotatableBonds(), denoptim.molecularmodeling.ChemicalObjectModel.getRotatableBonds(), and denoptim.molecularmodeling.ChemicalObjectModel.purgeListRotatableBonds().
zmat
ZMatrix denoptim.molecularmodeling.ChemicalObjectModel.zmat private
ZMatrix representation.
Definition at line 75 of file ChemicalObjectModel.java.
Referenced by denoptim.molecularmodeling.ChemicalObjectModel.ChemicalObjectModel(), denoptim.molecularmodeling.ChemicalObjectModel.getZMatIdxOfRCASrc(), denoptim.molecularmodeling.ChemicalObjectModel.getZMatrix(), and denoptim.molecularmodeling.ChemicalObjectModel.updateXYZFromINT().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/ChemicalObjectModel.java