DENOPTIM: denoptim.files.SingletonFileAccess Class Reference
denoptim.files.SingletonFileAccess Class Reference
Singleton for synchronizing multi-thread safe file access.
Public Member Functions
synchronized void writeData (String fileName, String data, boolean append) throws DENOPTIMException
Write data as an unformatted string to a text file.
Static Public Member Functions
static SingletonFileAccess getInstance ()
Returns the single instance of this class.
Private Member Functions
SingletonFileAccess ()
Static Private Attributes
static final SingletonFileAccess sfa = new SingletonFileAccess()
Detailed Description
Singleton for synchronizing multi-thread safe file access.
Author
Marco Foscato
Definition at line 30 of file SingletonFileAccess.java.
Constructor & Destructor Documentation
SingletonFileAccess()
denoptim.files.SingletonFileAccess.SingletonFileAccess () private
Definition at line 37 of file SingletonFileAccess.java.
Member Function Documentation
getInstance()
static SingletonFileAccess denoptim.files.SingletonFileAccess.getInstance () static
Returns the single instance of this class.
Definition at line 65 of file SingletonFileAccess.java.
References denoptim.files.SingletonFileAccess.sfa.
Referenced by denoptim.combinatorial.CEBLUtils.storeGraphOfLevel().
writeData()
synchronized void denoptim.files.SingletonFileAccess.writeData (String fileName, String data, boolean append) throws DENOPTIMException
Write data as an unformatted string to a text file.
Parameters
filename
data
append if true requires to append to file
Exceptions
DENOPTIMException
Definition at line 52 of file SingletonFileAccess.java.
References denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.combinatorial.CEBLUtils.storeGraphOfLevel().
Member Data Documentation
sfa
final SingletonFileAccess denoptim.files.SingletonFileAccess.sfa = new SingletonFileAccess() static private
Definition at line 33 of file SingletonFileAccess.java.
Referenced by denoptim.files.SingletonFileAccess.getInstance().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/files/SingletonFileAccess.java