DENOPTIM: denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler Class Reference
denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler Class Reference
This differs from DefaultChemObjectReaderErrorHandler just by ignoring messages about invalid symbol.
Public Member Functions
PartlySilencedChemObjReaderErrorHandler (final Class<?> clazz)
Constructs a new instance using a given class as the source for logging purposes.
PartlySilencedChemObjReaderErrorHandler (final ILoggingTool logger)
Constructs a new instance using the provided logging tool.
void handleError (String message)
void handleError (String message, Exception exception)
void handleError (String message, int row, int colStart, int colEnd)
void handleError (String message, int row, int colStart, int colEnd, Exception exception)
void handleFatalError (String message)
void handleFatalError (String message, Exception exception)
void handleFatalError (String message, int row, int colStart, int colEnd)
void handleFatalError (String message, int row, int colStart, int colEnd, Exception exception)
Private Member Functions
boolean isInvalidSymbolMessage (String message)
Private Attributes
final ILoggingTool logger
Detailed Description
This differs from DefaultChemObjectReaderErrorHandler just by ignoring messages about invalid symbol.
However, to achieve this result we need to overcome the closed permission mask of DefaultChemObjectReaderErrorHandler where the logger is private. As a result, we have to duplicate nearly the entire class.
Definition at line 394 of file DenoptimIO.java.
Constructor & Destructor Documentation
PartlySilencedChemObjReaderErrorHandler() [1/2]
denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.PartlySilencedChemObjReaderErrorHandler (final Class<?> clazz)
Constructs a new instance using a given class as the source for logging purposes.
Parameters
clazz the class for which the ILoggingTool should be constructed
Definition at line 403 of file DenoptimIO.java.
PartlySilencedChemObjReaderErrorHandler() [2/2]
denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.PartlySilencedChemObjReaderErrorHandler (final ILoggingTool logger)
Constructs a new instance using the provided logging tool.
Parameters
logger the logger to be used for emitting log entries
Definition at line 412 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
Member Function Documentation
handleError() [1/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError (String message)
Definition at line 417 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.isInvalidSymbolMessage(), and denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleError() [2/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError (String message, Exception exception)
Definition at line 422 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.isInvalidSymbolMessage(), and denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleError() [3/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError (String message, int row, int colStart, int colEnd)
Definition at line 427 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.isInvalidSymbolMessage(), and denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleError() [4/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError (String message, int row, int colStart, int colEnd, Exception exception)
Definition at line 432 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.isInvalidSymbolMessage(), and denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleFatalError() [1/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleFatalError (String message)
Definition at line 437 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleFatalError() [2/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleFatalError (String message, Exception exception)
Definition at line 442 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleFatalError() [3/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleFatalError (String message, int row, int colStart, int colEnd)
Definition at line 447 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
handleFatalError() [4/4]
void denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleFatalError (String message, int row, int colStart, int colEnd, Exception exception)
Definition at line 452 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger.
isInvalidSymbolMessage()
boolean denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.isInvalidSymbolMessage (String message) private
Definition at line 456 of file DenoptimIO.java.
Referenced by denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError().
Member Data Documentation
logger
final ILoggingTool denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.logger private
Definition at line 396 of file DenoptimIO.java.
Referenced by denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleError(), denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.handleFatalError(), and denoptim.io.DenoptimIO.PartlySilencedChemObjReaderErrorHandler.PartlySilencedChemObjReaderErrorHandler().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/io/DenoptimIO.java