DENOPTIM: denoptim.graph.FragmentTest Class Reference
denoptim.graph.FragmentTest Class Reference
Unit test for DENOPTIMFragment.
Public Member Functions
void testHandlingAPsAsObjOrProperty () throws Exception
void testConversionToIAC () throws Exception
void testClone () throws Exception
void testIsomorphicTo () throws Exception
void testIsomorphicInLinear () throws Exception
Static Public Member Functions
static Fragment makeFragment () throws DENOPTIMException
static Fragment makeFragmentA () throws DENOPTIMException
static Fragment makeFragmentB () throws DENOPTIMException
Differs from the fragment produced by makeFragmentA() only by the identity of one atom.
static Fragment makeFragmentC () throws DENOPTIMException
Differs from the fragment produced by makeFragmentA() only by the one APCLass.
Static Private Attributes
static final String APRULE = "MyRule"
static final String APSUBRULE = "1"
static final String APCLASS
static final String APCSEP = DENOPTIMConstants.SEPARATORAPPROPSCL
Detailed Description
Unit test for DENOPTIMFragment.
Author
Marco Foscato
Definition at line 46 of file FragmentTest.java.
Member Function Documentation
makeFragment()
static Fragment denoptim.graph.FragmentTest.makeFragment () throws DENOPTIMException static
Definition at line 157 of file FragmentTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.FragmentTest.APCLASS, denoptim.graph.Vertex.getAP(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setBuildingBlockType(), denoptim.graph.Fragment.setSymmetricAPSets(), and denoptim.graph.Vertex.setVertexId().
Referenced by denoptim.graph.FragmentTest.testClone(), denoptim.io.DenoptimIOTest.testIOMolFragment(), and denoptim.json.DENOPTIMgsonTest.testMolecularFragmentSerialization().
makeFragmentA()
static Fragment denoptim.graph.FragmentTest.makeFragmentA () throws DENOPTIMException static
Definition at line 238 of file FragmentTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), and denoptim.graph.APClass.make().
Referenced by denoptim.graph.SymmetricSetWithModeTest.testEquals(), denoptim.graph.SymmetricAPsTest.testGetSameAsThis(), denoptim.graph.SymmetricSetWithModeTest.testHashCode(), denoptim.graph.FragmentTest.testIsomorphicInLinear(), denoptim.graph.FragmentTest.testIsomorphicTo(), and denoptim.graph.SymmetricAPsTest.testSameAs().
makeFragmentB()
static Fragment denoptim.graph.FragmentTest.makeFragmentB () throws DENOPTIMException static
Differs from the fragment produced by makeFragmentA() only by the identity of one atom.
Definition at line 267 of file FragmentTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), and denoptim.graph.APClass.make().
Referenced by denoptim.graph.FragmentTest.testIsomorphicTo().
makeFragmentC()
static Fragment denoptim.graph.FragmentTest.makeFragmentC () throws DENOPTIMException static
Differs from the fragment produced by makeFragmentA() only by the one APCLass.
Definition at line 296 of file FragmentTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), and denoptim.graph.APClass.make().
Referenced by denoptim.graph.FragmentTest.testIsomorphicTo().
testClone()
void denoptim.graph.FragmentTest.testClone () throws Exception
Definition at line 200 of file FragmentTest.java.
References denoptim.graph.Fragment.clone(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.Vertex.getProperty(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.Vertex.isRCV, denoptim.graph.FragmentTest.makeFragment(), and denoptim.graph.Vertex.setProperty().
testConversionToIAC()
void denoptim.graph.FragmentTest.testConversionToIAC () throws Exception
Definition at line 101 of file FragmentTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.FragmentTest.APCLASS, denoptim.graph.FragmentTest.APCSEP, denoptim.graph.FragmentTest.APRULE, denoptim.graph.Vertex.getAP(), denoptim.graph.Fragment.getAPCountOnAtom(), denoptim.graph.Fragment.getIAtomContainer(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.Vertex.getSymmetricAPs(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), and denoptim.graph.Vertex.BBType.UNDEFINED.
testHandlingAPsAsObjOrProperty()
void denoptim.graph.FragmentTest.testHandlingAPsAsObjOrProperty () throws Exception
Definition at line 57 of file FragmentTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.FragmentTest.APCLASS, denoptim.constants.DENOPTIMConstants.APSTAG, denoptim.graph.Fragment.getAPCountOnAtom(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.Vertex.getProperty(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.graph.Fragment.projectPropertyToAP(), and denoptim.graph.Vertex.setProperty().
testIsomorphicInLinear()
void denoptim.graph.FragmentTest.testIsomorphicInLinear () throws Exception
Definition at line 339 of file FragmentTest.java.
References denoptim.utils.DummyAtomHandler.addDummiesOnLinearities(), denoptim.graph.Fragment.isIsomorphicTo(), and denoptim.graph.FragmentTest.makeFragmentA().
testIsomorphicTo()
void denoptim.graph.FragmentTest.testIsomorphicTo () throws Exception
Definition at line 321 of file FragmentTest.java.
References denoptim.graph.Fragment.isIsomorphicTo(), denoptim.graph.FragmentTest.makeFragmentA(), denoptim.graph.FragmentTest.makeFragmentB(), and denoptim.graph.FragmentTest.makeFragmentC().
Member Data Documentation
APCLASS
final String denoptim.graph.FragmentTest.APCLASS static private
Initial value:
= APRULE
            + DENOPTIMConstants.SEPARATORAPPROPSCL + APSUBRULE
Definition at line 50 of file FragmentTest.java.
Referenced by denoptim.graph.FragmentTest.makeFragment(), denoptim.graph.FragmentTest.testConversionToIAC(), and denoptim.graph.FragmentTest.testHandlingAPsAsObjOrProperty().
APCSEP
final String denoptim.graph.FragmentTest.APCSEP = DENOPTIMConstants.SEPARATORAPPROPSCL static private
Definition at line 52 of file FragmentTest.java.
Referenced by denoptim.graph.FragmentTest.testConversionToIAC().
APRULE
final String denoptim.graph.FragmentTest.APRULE = "MyRule" static private
Definition at line 48 of file FragmentTest.java.
Referenced by denoptim.graph.FragmentTest.testConversionToIAC().
APSUBRULE
final String denoptim.graph.FragmentTest.APSUBRULE = "1" static private
Definition at line 49 of file FragmentTest.java.
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/FragmentTest.java