DENOPTIM: denoptim.utils.SizeControlledSetTest Class Reference
denoptim.utils.SizeControlledSetTest Class Reference
Unit test for SizeControlledSet.
Public Member Functions
void test () throws Exception
Package Attributes
File tempDir
Private Attributes
final String SEP = System.getProperty("file.separator")
Detailed Description
Unit test for SizeControlledSet.
Author
Marco Foscato
Definition at line 39 of file SizeControlledSetTest.java.
Member Function Documentation
test()
void denoptim.utils.SizeControlledSetTest.test () throws Exception
Definition at line 49 of file SizeControlledSetTest.java.
References denoptim.utils.SizeControlledSet.addNewUniqueEntry(), denoptim.utils.SizeControlledSet.contains(), denoptim.io.DenoptimIO.readList(), denoptim.utils.SizeControlledSetTest.SEP, denoptim.utils.SizeControlledSet.size(), and denoptim.utils.SizeControlledSetTest.tempDir.
Member Data Documentation
SEP
final String denoptim.utils.SizeControlledSetTest.SEP = System.getProperty("file.separator") private
Definition at line 41 of file SizeControlledSetTest.java.
Referenced by denoptim.utils.SizeControlledSetTest.test().
tempDir
File denoptim.utils.SizeControlledSetTest.tempDir package
Definition at line 44 of file SizeControlledSetTest.java.
Referenced by denoptim.utils.SizeControlledSetTest.test().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/utils/SizeControlledSetTest.java