DENOPTIM: denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer Class Reference
denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer Class Reference
Public Member Functions
void startServer ()
int getPort ()
void stopServer ()
void run ()
Private Attributes
ServerSocket server
Detailed Description
Definition at line 91 of file SocketProvidedDescriptorTest.java.
Member Function Documentation
getPort()
int denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.getPort ()
Definition at line 117 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.server.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver().
run()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.run ()
Definition at line 135 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.server.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.startServer().
startServer()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.startServer ()
Definition at line 95 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.run(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.server.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.setUpSertver().
stopServer()
void denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.stopServer ()
Definition at line 122 of file SocketProvidedDescriptorTest.java.
References denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.server.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.ClossServer().
Member Data Documentation
server
ServerSocket denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.server private
Definition at line 93 of file SocketProvidedDescriptorTest.java.
Referenced by denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.getPort(), denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.run(), denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.startServer(), and denoptim.fitness.descriptors.SocketProvidedDescriptorTest.MySocketServer.stopServer().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fitness/descriptors/SocketProvidedDescriptorTest.java