DENOPTIM: denoptim.programs.fitnessevaluator.FitnessRunner Class Reference
denoptim.programs.fitnessevaluator.FitnessRunner Class Reference
Stand-alone fitness provider.
Public Member Functions
FitnessRunner (File configFile, File workDir)
Creates and configures the program task.
void runProgram () throws Throwable
Public Member Functions inherited from denoptim.task.ProgramTask
ProgramTask (File configFile, File workDir)
Creates and configures the program task.
Object call ()
This method redirects the callable functionality to an abstract method (namely ProgramTask#runProgram()) to be specified by the implementations of this abstract class.
void printErrorToFile ()
Method that can be called to create a text file with the error triggered by any Throwable that can be thrown by the execution of the program.
Public Member Functions inherited from denoptim.task.Task
Task (final int id)
int getId ()
void setVerbosity (int verbosity)
Set the verbosity: i.e., amount of log printed by this class.
void setWorkSpace (File workDir)
Sets the pathname of the work space, i.e., the location where the task is supposed to use move to or to threat as the result of "pwd" at runtime.
boolean isCompleted ()
boolean foundException ()
Throwable getException ()
String getErrorMessage ()
void stopTask ()
Stop the task if not already completed.
String toString ()
Returns a string identifying this task by its ID and reporting whether an exception has been thrown and if the tasks is completed.
void setNotify (boolean notify)
Protected Member Functions
void handleThrowable ()
Method to handle any Throwable originated from the runProgram() method.
Protected Member Functions inherited from denoptim.task.ProgramTask
void handleThrowable ()
Method to handle any Throwable originated from the runProgram() method.
void stopLogger ()
Stops the program-specific logger and releases the lock file on the logfile.
abstract void runProgram () throws Throwable
Private Attributes
FPRunner runner = null
Additional Inherited Members
Public Attributes inherited from denoptim.task.Task
Object lock = new Object()
Lock for addressing synchronization issues.
Protected Attributes inherited from denoptim.task.ProgramTask
File configFilePathName
File containing configuration parameters for the program task.
String loggerIdentifier = "none"
Identifier of this program's logger.
Protected Attributes inherited from denoptim.task.Task
boolean notifyGlobalTaskManager = false
Flag controlling whether this task is expected to notify the static task manager.
boolean completed = false
Flag about completion.
boolean hasException = false
Flag about exception.
String errMsg = ""
Error message produced by any subtask.
Throwable thrownExc
Exception thrown.
int id
A user-assigned id for this task.
ProcessHandler processHandler
Executor for external bash script.
File workDir
The file system location where we want to be placed when doing the work.
int verbosity = 0
Verbosity level.
final String SEP = System.getProperty("file.separator")
System-dependent file separator.
final String NL = System.getProperty("line.separator")
System-dependent line separator (newline)
Detailed Description
Stand-alone fitness provider.
This class implements a method that allows to run a fitness evaluation in a stand-alone fashion. The configuration of the fitness provider is given as a DENOPTIM's input parameter file, that is in all equal to the parameters file used by GARunner and FragSpaceExplorer.
Author
Marco Foscato
Definition at line 38 of file FitnessRunner.java.
Constructor & Destructor Documentation
FitnessRunner()
denoptim.programs.fitnessevaluator.FitnessRunner.FitnessRunner (File configFile, File workDir)
Creates and configures the program task.
Parameters
configFile the file containing the configuration parameters.
workDir the file system location from which to run the program.
Definition at line 49 of file FitnessRunner.java.
References denoptim.task.Task.workDir.
Member Function Documentation
handleThrowable()
void denoptim.programs.fitnessevaluator.FitnessRunner.handleThrowable () protected
Method to handle any Throwable originated from the runProgram() method.
This method can be overwritten to alter the behavior in case of specific needs.
Reimplemented from denoptim.task.ProgramTask.
Definition at line 78 of file FitnessRunner.java.
References denoptim.programs.fitnessevaluator.FitnessRunner.runner, and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
runProgram()
void denoptim.programs.fitnessevaluator.FitnessRunner.runProgram () throws Throwable
Reimplemented from denoptim.task.ProgramTask.
Definition at line 57 of file FitnessRunner.java.
References denoptim.programs.fitnessevaluator.FRParameters.checkParameters(), denoptim.task.ProgramTask.configFilePathName, denoptim.task.ProgramTask.loggerIdentifier, denoptim.programs.RunTimeParameters.printParameters(), denoptim.programs.fitnessevaluator.FRParameters.processParameters(), denoptim.programs.RunTimeParameters.readParameterFile(), denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.programs.fitnessevaluator.FitnessRunner.runner, denoptim.programs.RunTimeParameters.setWorkDirectory(), denoptim.programs.RunTimeParameters.startProgramSpecificLogger(), and denoptim.task.Task.workDir.
Member Data Documentation
runner
FPRunner denoptim.programs.fitnessevaluator.FitnessRunner.runner = null private
Definition at line 40 of file FitnessRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FitnessRunner.handleThrowable(), and denoptim.programs.fitnessevaluator.FitnessRunner.runProgram().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/fitnessevaluator/FitnessRunner.java