DENOPTIM: denoptim.fragmenter.FragmenterToolsTest Class Reference
denoptim.fragmenter.FragmenterToolsTest Class Reference
Unit test for fragmenter's tools.
Public Member Functions
void testGetMatchingBonds () throws Exception
void testExploreHapticity () throws Exception
Works on this system.
void testExploreConnectivity () throws Exception
void testFilterFragment () throws Exception
void testGetMWSlotIdentifier () throws Exception
Private Attributes
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance()
Private builder of atom containers.
Detailed Description
Unit test for fragmenter's tools.
Definition at line 38 of file FragmenterToolsTest.java.
Member Function Documentation
testExploreConnectivity()
void denoptim.fragmenter.FragmenterToolsTest.testExploreConnectivity () throws Exception
Definition at line 224 of file FragmenterToolsTest.java.
References denoptim.fragmenter.FragmenterToolsTest.builder, and denoptim.fragmenter.FragmenterTools.exploreConnectivity().
testExploreHapticity()
void denoptim.fragmenter.FragmenterToolsTest.testExploreHapticity () throws Exception
Works on this system.
   A          B
 C-C-C     C-C-C-C-O-O
  |/       |/_/
   Ru-------Fe___
  /|       /|\ \ \
 C-C      C-C-C-C-C-S-S
  C           D
Definition at line 111 of file FragmenterToolsTest.java.
References denoptim.fragmenter.FragmenterToolsTest.builder, and denoptim.fragmenter.FragmenterTools.exploreHapticity().
testFilterFragment()
void denoptim.fragmenter.FragmenterToolsTest.testFilterFragment () throws Exception
Definition at line 271 of file FragmenterToolsTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.fragmenter.FragmenterToolsTest.builder, denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.fragmenter.FragmenterTools.filterFragment(), denoptim.graph.APClass.make(), denoptim.programs.fragmenter.FragmenterParameters.setFragRejectionSMARTS(), denoptim.programs.fragmenter.FragmenterParameters.setFragRetentionSMARTS(), denoptim.programs.fragmenter.FragmenterParameters.setMaxFragHeavyAtomCount(), denoptim.programs.fragmenter.FragmenterParameters.setMinFragHeavyAtomCount(), denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClassCombinations(), denoptim.programs.fragmenter.FragmenterParameters.setRejectedAPClasses(), denoptim.programs.fragmenter.FragmenterParameters.setRejectedElements(), denoptim.programs.fragmenter.FragmenterParameters.setRejectedFormulaLessThan(), denoptim.programs.fragmenter.FragmenterParameters.setRejectedFormulaMoreThan(), denoptim.programs.fragmenter.FragmenterParameters.setRejectWeirdIsotopes(), and denoptim.graph.Vertex.BBType.UNDEFINED.
testGetMatchingBonds()
void denoptim.fragmenter.FragmenterToolsTest.testGetMatchingBonds () throws Exception
Definition at line 49 of file FragmenterToolsTest.java.
References denoptim.fragmenter.FragmenterToolsTest.builder, and denoptim.fragmenter.FragmenterTools.getMatchingBondsAllInOne().
testGetMWSlotIdentifier()
void denoptim.fragmenter.FragmenterToolsTest.testGetMWSlotIdentifier () throws Exception
Definition at line 545 of file FragmenterToolsTest.java.
References denoptim.fragmenter.FragmenterToolsTest.builder, denoptim.constants.DENOPTIMConstants.DUMMYATMSYMBOL, denoptim.fragmenter.FragmenterTools.getMWSlotIdentifier(), and denoptim.graph.Vertex.BBType.UNDEFINED.
Member Data Documentation
builder
IChemObjectBuilder denoptim.fragmenter.FragmenterToolsTest.builder = SilentChemObjectBuilder.getInstance() private
Private builder of atom containers.
Definition at line 44 of file FragmenterToolsTest.java.
Referenced by denoptim.fragmenter.FragmenterToolsTest.testExploreConnectivity(), denoptim.fragmenter.FragmenterToolsTest.testExploreHapticity(), denoptim.fragmenter.FragmenterToolsTest.testFilterFragment(), denoptim.fragmenter.FragmenterToolsTest.testGetMatchingBonds(), and denoptim.fragmenter.FragmenterToolsTest.testGetMWSlotIdentifier().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragmenter/FragmenterToolsTest.java