DENOPTIM: denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure Class Reference
denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure Class Reference
Calculates the molecular similarity against a target compound the fingerprint of which is given as parameter, and using a given list of substructures.
Public Member Functions
TanimotoMolSimilarityBySubstructure ()
Constructor for a TanimotoMolSimilarity object.
DescriptorSpecification getSpecification ()
Get the specification attribute of Tanimoto molecular similarity.
String[] getParameterNames ()
Gets the parameterNames attribute of the TanimotoMolSimilarityBySubstructure object.
Object getParameterType (String name)
void setParameters (Object[] params) throws CDKException
Set the parameters attribute of TanimotoMolSimilarityBySubstructure object.
Object[] getParameters ()
String[] getDescriptorNames ()
DescriptorValue calculate (IAtomContainer mol)
IDescriptorResult getDescriptorResultType ()
String getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
Returns
the title
String getDictionaryDefinition ()
Get a string that describes the descriptor in detail.Might contain mathematical formulation.
See also
DescriptorEngine
Returns
the description of this descriptor, possibly containing equations that clarify how it is calculated.
String[] getDictionaryClass ()
Get the classification of this descriptor.A descriptor can belong to one or more classes simultaneously.
Returns
String getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
String getDictionaryDefinition ()
Get a string that describes the descriptor in detail.
String[] getDictionaryClass ()
Get the classification of this descriptor.
Private Attributes
IBitFingerprint referenceFingerprint
IFingerprinter fingerprinter
String[] substructuressmarts
Static Private Attributes
static final String[] PARAMNAMES
static final String[] NAMES = {"TanimotoSimilarityBySubstructure"}
Detailed Description
Calculates the molecular similarity against a target compound the fingerprint of which is given as parameter, and using a given list of substructures.
Definition at line 44 of file TanimotoMolSimilarityBySubstructure.java.
Constructor & Destructor Documentation
TanimotoMolSimilarityBySubstructure()
denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.TanimotoMolSimilarityBySubstructure ()
Constructor for a TanimotoMolSimilarity object.
Definition at line 62 of file TanimotoMolSimilarityBySubstructure.java.
Member Function Documentation
calculate()
DescriptorValue denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate (IAtomContainer mol)
Definition at line 177 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDescriptorNames(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameterNames(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.referenceFingerprint.
getDescriptorNames()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDescriptorNames ()
Definition at line 168 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.NAMES.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate().
getDescriptorResultType()
IDescriptorResult denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDescriptorResultType ()
Definition at line 216 of file TanimotoMolSimilarityBySubstructure.java.
getDictionaryClass()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDictionaryClass ()
Get the classification of this descriptor.A descriptor can belong to one or more classes simultaneously.
Returns
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 253 of file TanimotoMolSimilarityBySubstructure.java.
getDictionaryDefinition()
String denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDictionaryDefinition ()
Get a string that describes the descriptor in detail.Might contain mathematical formulation.
See also
DescriptorEngine
Returns
the description of this descriptor, possibly containing equations that clarify how it is calculated.
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 234 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.PARAMNAMES.
getDictionaryTitle()
String denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
Returns
the title
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 225 of file TanimotoMolSimilarityBySubstructure.java.
getParameterNames()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameterNames ()
Gets the parameterNames attribute of the TanimotoMolSimilarityBySubstructure object.
Returns
the parameterNames value
Definition at line 97 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.PARAMNAMES.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate().
getParameters()
Object[] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameters ()
Definition at line 156 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.referenceFingerprint, and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.substructuressmarts.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate().
getParameterType()
Object denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameterType (String name)
Definition at line 105 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.PARAMNAMES.
getSpecification()
DescriptorSpecification denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getSpecification ()
Get the specification attribute of Tanimoto molecular similarity.
Given the dependency on the substructures list and reference fingerprint, the implementation identifier is made dependent on those two parameters. Consequently resetting the parameter with two new instances of the substructures and reference fingerprint (even is effectively equal) will result in two different DescriptorSpecification objects.
Returns
the specification of this descriptor.
Definition at line 77 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.referenceFingerprint, and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.substructuressmarts.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate().
setParameters()
void denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.setParameters (Object[] params) throws CDKException
Set the parameters attribute of TanimotoMolSimilarityBySubstructure object.
The descriptor takes two parameters: the array of substructures defining the fingerprint bits, and the fingerprint against which we want to calculate similarity.
Parameters
params the array of parameters
Definition at line 128 of file TanimotoMolSimilarityBySubstructure.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.referenceFingerprint, and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.substructuressmarts.
Member Data Documentation
fingerprinter
IFingerprinter denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.fingerprinter private
Definition at line 50 of file TanimotoMolSimilarityBySubstructure.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.setParameters().
NAMES
final String [] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.NAMES = {"TanimotoSimilarityBySubstructure"} static private
Definition at line 55 of file TanimotoMolSimilarityBySubstructure.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDescriptorNames().
PARAMNAMES
final String [] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.PARAMNAMES static private
Initial value:
= new String[] {
            "substructuressmarts","referenceFingerprint"}
Definition at line 52 of file TanimotoMolSimilarityBySubstructure.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getDictionaryDefinition(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameterNames(), and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameterType().
referenceFingerprint
IBitFingerprint denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.referenceFingerprint private
Definition at line 49 of file TanimotoMolSimilarityBySubstructure.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.calculate(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.setParameters().
substructuressmarts
String [] denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.substructuressmarts private
Definition at line 51 of file TanimotoMolSimilarityBySubstructure.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarityBySubstructure.setParameters().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fitness/descriptors/TanimotoMolSimilarityBySubstructure.java