DENOPTIM: denoptim.fragspace.APMapFinderTest Class Reference
denoptim.fragspace.APMapFinderTest Class Reference
Unit test.
Public Member Functions
void testAPMapFinder_Constrained () throws Exception
void testAPMapFinder_ConstrainAll () throws Exception
void testAPMapFinder () throws Exception
void testFindMappingCompatibileAPs () throws Exception
Private Member Functions
FragmentSpace prepare () throws DENOPTIMException
Static Private Attributes
static APClass APCA
static APClass APCB
static APClass APCC
static APClass APCD
static APClass APCE
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 48 of file APMapFinderTest.java.
Member Function Documentation
prepare()
FragmentSpace denoptim.fragspace.APMapFinderTest.prepare () throws DENOPTIMException private
Definition at line 54 of file APMapFinderTest.java.
References denoptim.fragspace.APMapFinderTest.APCA, denoptim.fragspace.APMapFinderTest.APCB, denoptim.fragspace.APMapFinderTest.APCC, denoptim.fragspace.APMapFinderTest.APCD, denoptim.fragspace.APMapFinderTest.APCE, denoptim.graph.APClass.make(), and denoptim.fragspace.FragmentSpace.setAPclassBasedApproach().
Referenced by denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll(), and denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained().
testAPMapFinder()
void denoptim.fragspace.APMapFinderTest.testAPMapFinder () throws Exception
Definition at line 178 of file APMapFinderTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.fragspace.APMapFinderTest.APCA, denoptim.fragspace.APMapFinderTest.APCB, denoptim.fragspace.APMapFinderTest.APCC, denoptim.fragspace.APMapFinderTest.APCD, denoptim.fragspace.APMapFinder.foundMapping(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.APMapFinder.getAllAPMappings(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.APMapFinder.getChosenAPMapping(), denoptim.fragspace.APMapFinderTest.prepare(), and denoptim.graph.Vertex.setBuildingBlockType().
testAPMapFinder_ConstrainAll()
void denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll () throws Exception
Definition at line 153 of file APMapFinderTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.fragspace.APMapFinderTest.APCA, denoptim.fragspace.APMapFinder.foundMapping(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.APMapFinder.getAllAPMappings(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.APMapFinder.getChosenAPMapping(), denoptim.fragspace.APMapFinderTest.prepare(), and denoptim.graph.Vertex.setBuildingBlockType().
testAPMapFinder_Constrained()
void denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained () throws Exception
Definition at line 119 of file APMapFinderTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.fragspace.APMapFinderTest.APCA, denoptim.fragspace.APMapFinderTest.APCD, denoptim.fragspace.APMapFinder.foundMapping(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.APMapFinder.getAllAPMappings(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.APMapFinderTest.prepare(), and denoptim.graph.Vertex.setBuildingBlockType().
testFindMappingCompatibileAPs()
void denoptim.fragspace.APMapFinderTest.testFindMappingCompatibileAPs () throws Exception
Definition at line 285 of file APMapFinderTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.fragspace.APMapFinder.findMappingCompatibileAPs(), denoptim.graph.Vertex.getAP(), denoptim.graph.EmptyVertex.getAttachmentPoints(), denoptim.graph.APClass.make(), and denoptim.fragspace.FragmentSpace.setAPclassBasedApproach().
Member Data Documentation
APCA
APClass denoptim.fragspace.APMapFinderTest.APCA static private
Definition at line 50 of file APMapFinderTest.java.
Referenced by denoptim.fragspace.APMapFinderTest.prepare(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), denoptim.fragspace.APMapFinderTest.testAPMapFinder_ConstrainAll(), and denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained().
APCB
APClass denoptim.fragspace.APMapFinderTest.APCB static private
Definition at line 50 of file APMapFinderTest.java.
Referenced by denoptim.fragspace.APMapFinderTest.prepare(), and denoptim.fragspace.APMapFinderTest.testAPMapFinder().
APCC
APClass denoptim.fragspace.APMapFinderTest.APCC static private
Definition at line 50 of file APMapFinderTest.java.
Referenced by denoptim.fragspace.APMapFinderTest.prepare(), and denoptim.fragspace.APMapFinderTest.testAPMapFinder().
APCD
APClass denoptim.fragspace.APMapFinderTest.APCD static private
Definition at line 50 of file APMapFinderTest.java.
Referenced by denoptim.fragspace.APMapFinderTest.prepare(), denoptim.fragspace.APMapFinderTest.testAPMapFinder(), and denoptim.fragspace.APMapFinderTest.testAPMapFinder_Constrained().
APCE
APClass denoptim.fragspace.APMapFinderTest.APCE static private
Definition at line 50 of file APMapFinderTest.java.
Referenced by denoptim.fragspace.APMapFinderTest.prepare().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragspace/APMapFinderTest.java