DENOPTIM: denoptim.graph.DGraphTest Class Reference
denoptim.graph.DGraphTest Class Reference
Unit test for DENOPTIMGraph.
Public Member Functions
void testRemoveUnusedRCVs () throws Exception
void testGetEmbeddingPath () throws Exception
void testGetEmbeddedGraphInClone () throws Exception
void testGetSourceVertex () throws Exception
void testGetLevel () throws Exception
void testReplaceVertex () throws Exception
void testReplaceVertex_inRing () throws Exception
void testReplaceSingleSubGraph () throws Exception, DENOPTIMException
void testReplaceSingleSubGraph_inTemplate () throws Exception
void testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation () throws Exception
void testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation () throws Exception
void testReplaceSingleSubGraph_ringFormation () throws Exception
void testRemoveVertex () throws Exception
void testSameAs_Equal () throws DENOPTIMException
void testSameAs_DiffVertex () throws DENOPTIMException
void testSameAs_SameSymmSet () throws Exception
void testSameAs_DiffSymmSet () throws Exception
void testSameAs_SameRings () throws DENOPTIMException
void testSameAs_DisorderRings () throws Exception
void testSameAs_DiffRings () throws DENOPTIMException
void testGetAvailableAPs_returnsListOfAvailableAPs () throws DENOPTIMException
void testClone () throws DENOPTIMException
void testGetMutationSites () throws DENOPTIMException
void testRemoveCapping () throws Exception
void testFromToJSON () throws Exception
void testGraphIsomorphism () throws Exception
void testExtractSubgraph () throws Exception
void testExtractSubgraphFromCollection () throws Exception
void testFindVertex () throws Exception
void testSymmetricSetLabels () throws Exception
void testConvertSymmetricLabelsToSymmetricSets () throws Exception
void testGetSymmetricSubGraphs () throws Exception
void testGetChildrenTree () throws Exception
void testGetChildrenTreeWithBranchIdentifier () throws Exception
void testGetInterfaceAPs () throws Exception
void testGetSubgraphAPs () throws Exception
DGraph[] makeIsostructuralGraphs () throws Exception
void testIsIsostructuralTo () throws Exception
void testGetEdgesWithSrcOrTrg () throws Exception
void testEmbedPatternsInTemplates () throws Exception
void testDetectSymVertexSets () throws Exception
void testExploreGraph_nothingToExplore () throws Exception
void testExploreGraph_simpleGraph () throws Exception
void testExploreGraph_noCrossingTemplateBoundary () throws Exception
void testIsConnected () throws Exception
void testGetVertexAnyLevel () throws Exception
Static Public Member Functions
static FragmentSpace prepare () throws DENOPTIMException
static DGraph makeDeeplyEmbeddedGraph () throws DENOPTIMException
Returns a graph that contains a 10-layered recursive structure.
static DGraph makeTestGraph_treeWithOutScaffold (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that intentionally violates APClass compatibility and looks like this:
static DGraph makeTestGraphA ()
Build a graph meant to be used in unit tests.
static DGraph makeTestGraphA2 ()
Build a graph meant to be used in unit tests.
static DGraph makeTestGraphM () throws DENOPTIMException
Returns a graph with definition of symmetric vertexes and symmetric APs meant for testing purposes.
static DGraph makeTestGraphN () throws DENOPTIMException
Returns a graph with peculiar definition of symmetric vertexes and symmetric APs meant for testing purposes.
static DGraph makeTestGraphO_A (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that intentionally violates APClass compatibility and looks like this:
static DGraph makeTestGraphO_B (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that intentionally violates APClass compatibility and looks like this:
Private Member Functions
DGraph makeTestGraphB (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphC (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphD (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphDSub1 (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphDSub2 (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphE (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphF (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphG (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphH (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphI (FragmentSpace fs) throws Exception
Creates a test graph that looks like this:
DGraph makeTestGraphJ (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphK (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeTestGraphL (FragmentSpace fs) throws DENOPTIMException
Creates a test graph that looks like this:
DGraph makeDisorderedGraph (FragmentSpace fs) throws DENOPTIMException
Makes a graph with disordered list of vertexes, i.e., the first vertex is not the source.
void buildVertexAndConnectToGraph (EmptyVertex v, int apCount, DGraph graph) throws DENOPTIMException
Static Private Member Functions
static DGraph makeTestGraph0 (FragmentSpace fs) throws Exception
Build a graph meant to be used in unit tests.
static DGraph makeTestGraph1 (FragmentSpace fs) throws Exception
Build a graph meant to be used in unit tests.
Static Private Attributes
static APClass APCA
static APClass APCB
static APClass APCC
static APClass APCD
static APClass CAPP
static String a ="A"
static String b ="B"
static String c ="C"
static String d ="D"
static String cap ="cap"
Detailed Description
Unit test for DENOPTIMGraph.
Author
Marco Foscato
Definition at line 71 of file DGraphTest.java.
Member Function Documentation
buildVertexAndConnectToGraph()
void denoptim.graph.DGraphTest.buildVertexAndConnectToGraph (EmptyVertex v, int apCount, DGraph graph) throws DENOPTIMException private
Definition at line 3024 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.testClone(), denoptim.graph.DGraphTest.testFromToJSON(), denoptim.graph.DGraphTest.testRemoveVertex(), denoptim.graph.DGraphTest.testSameAs_DiffRings(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), denoptim.graph.DGraphTest.testSameAs_DiffVertex(), denoptim.graph.DGraphTest.testSameAs_DisorderRings(), denoptim.graph.DGraphTest.testSameAs_Equal(), denoptim.graph.DGraphTest.testSameAs_SameRings(), and denoptim.graph.DGraphTest.testSameAs_SameSymmSet().
makeDeeplyEmbeddedGraph()
static DGraph denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph () throws DENOPTIMException static
Returns a graph that contains a 10-layered recursive structure.
Before running this you must run DGraphTest#prepare()
Definition at line 1300 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.APCA, denoptim.graph.DGraphTest.APCB, denoptim.graph.DGraphTest.APCC, denoptim.graph.DGraphTest.APCD, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.Template.setInnerGraph(), denoptim.graph.Vertex.setVertexId(), and denoptim.graph.Vertex.BBType.UNDEFINED.
Referenced by denoptim.graph.DGraphTest.testExploreGraph_noCrossingTemplateBoundary(), denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone(), denoptim.graph.DGraphTest.testGetEmbeddingPath(), denoptim.graph.DGraphTest.testGetVertexAnyLevel(), and denoptim.ga.XoverSiteTest.testProjectToClonedGraphs().
makeDisorderedGraph()
DGraph denoptim.graph.DGraphTest.makeDisorderedGraph (FragmentSpace fs) throws DENOPTIMException private
Makes a graph with disordered list of vertexes, i.e., the first vertex is not the source.
v5-0-->0-v3-1-->1-v4-0-->0-v1-1-->0-v2
Returns
a disordered graph
Exceptions
DENOPTIMException
Definition at line 1266 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), and denoptim.graph.Vertex.newVertexFromLibrary().
Referenced by denoptim.graph.DGraphTest.testGetLevel(), and denoptim.graph.DGraphTest.testGetSourceVertex().
makeIsostructuralGraphs()
DGraph[] denoptim.graph.DGraphTest.makeIsostructuralGraphs () throws Exception
Definition at line 3818 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.APCA, denoptim.graph.DGraphTest.APCB, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setProperty(), and denoptim.graph.Vertex.setUniquefyingProperty().
Referenced by denoptim.graph.DGraphTest.testIsIsostructuralTo().
makeTestGraph0()
static DGraph denoptim.graph.DGraphTest.makeTestGraph0 (FragmentSpace fs) throws Exception static private
Build a graph meant to be used in unit tests.
The returned graph has only the scaffold.
Returns
a new instance of the test graph.
Definition at line 2692 of file DGraphTest.java.
References denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testGraphIsomorphism(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
makeTestGraph1()
static DGraph denoptim.graph.DGraphTest.makeTestGraph1 (FragmentSpace fs) throws Exception static private
Build a graph meant to be used in unit tests.
The returned graph has only the scaffold and one vertex, plus the edge
Returns
a new instance of the test graph.
Definition at line 2709 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testGraphIsomorphism(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
makeTestGraph_treeWithOutScaffold()
static DGraph denoptim.graph.DGraphTest.makeTestGraph_treeWithOutScaffold (FragmentSpace fs) throws DENOPTIMException static
Creates a test graph that intentionally violates APClass compatibility and looks like this:
   v1--v2
  /
v0  (not a scaffold, but the seed of the tree!)
 \
  v3--v4
Definition at line 1951 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ringFormation().
makeTestGraphA()
static DGraph denoptim.graph.DGraphTest.makeTestGraphA () static
Build a graph meant to be used in unit tests.
The returned graph has the following structure:
       (free)
       ap2
      /
[C1-C0-ap0]-[ap0-O-ap1]-[ap0-H]
 |    \
 ap3   ap1
 |       \
(free)    [ap0-H]
Returns
a new instance of the test graph.
Definition at line 2742 of file DGraphTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.ga.EAUtilsTest.testCrowdingProbability().
makeTestGraphA2()
static DGraph denoptim.graph.DGraphTest.makeTestGraphA2 () static
Build a graph meant to be used in unit tests.
The structure of the graph is the following:
         [ap1-EV1-ap0]-[ap0-EV2]
        /
       ap2
      /
[C1-C0-ap0]-[ap0-O-ap1]-[ap0-H]
 |    \
 ap3   ap1
 |       \
 |        [ap0-H]
 [ap0-EV3]
Contrary to test graph A, this graph contains:
mixture of vertex types
APClasses
Returns
a new instance of the test graph.
Definition at line 2831 of file DGraphTest.java.
References denoptim.graph.DGraphTest.a, denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.b, denoptim.graph.DGraphTest.c, denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraphTest.d, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.APClass.make(), denoptim.graph.Edge.BondType.NONE, denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockId(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.graph.Edge.BondType.TRIPLE.
Referenced by denoptim.graph.AttachmentPointQueryTest.setUp(), denoptim.graph.EdgeQueryTest.setUp(), denoptim.graph.VertexQueryTest.setUp(), and denoptim.graph.DGraphTest.testFindVertex().
makeTestGraphB()
DGraph denoptim.graph.DGraphTest.makeTestGraphB (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
       (C)-(C)-v3
      /
     | (B)-(B)-v2
     |/
 (A)-v1-(B)-(B)-v2
      |
     (A)
      |
     (A)
   scaffold
     (A)
      |
     0(A)
      |
2(A)-v1-1(B)-(B)-v2
     |\
     | 3(B)-(B)-v2
     \
      4(C)-(C)-v3
Definition at line 239 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.DGraphTest.testReplaceVertex(), and denoptim.graph.DGraphTest.testSymmetricSetLabels().
makeTestGraphC()
DGraph denoptim.graph.DGraphTest.makeTestGraphC (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
    v1-(B)-(B)-v1-(B)-(B)-v1-(B)-(B)-v1
     |           \
    (A)           (A)-(A)-v0
     |
    (A)
  scaffold
    (A)
     |
    0(A)
     |
     v1-1(B)-(B)-v1-(B)-(B)-v1-(B)-(B)-v1
                  \
                   (A)-(A)-v0
Definition at line 317 of file DGraphTest.java.
References denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testExploreGraph_simpleGraph(), denoptim.graph.DGraphTest.testGetLevel(), denoptim.graph.DGraphTest.testGetSourceVertex(), denoptim.graph.DGraphTest.testGetVertexAnyLevel(), and denoptim.graph.DGraphTest.testIsConnected().
makeTestGraphD()
DGraph denoptim.graph.DGraphTest.makeTestGraphD (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
       (C)-(C)-v6-(D)--(B)-v7
       /                    |
      /                   chord
     |                      |
     | (B)-(C)-v6-(D)--(B)-v7
     |/
 (A)-v1-(B)-(C)-v6-(D)--(B)-v7
      |                     |
     (A)                    |
      |                   chord
     (A)                    |
   scaffold(D)----------(B)-v7
     (A)
      |
     0(A)
      |
     v1
      |
     2(A)
      |
     0(A)
      |
2(A)-v1-1(B)-(B)-v2
     |\
     | 3(B)-(B)-v2
     \
      4(C)-(C)-v3
Definition at line 413 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.graph.DGraphTest.testExtractSubgraphFromCollection(), denoptim.graph.DGraphTest.testGetChildrenTree(), denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph(), and denoptim.graph.DGraphTest.testReplaceVertex_inRing().
makeTestGraphDSub1()
DGraph denoptim.graph.DGraphTest.makeTestGraphDSub1 (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
      (C)-(C)-v6-(D)--(B)-v7
      /                    |
     /                   chord
    |                      |
    | (B)-(C)-v6-(D)--(B)-v7
    |/
(A)-v1-(B)-(C)-v6-(D)--(B)-v7
Definition at line 509 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testExtractSubgraph(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
makeTestGraphDSub2()
DGraph denoptim.graph.DGraphTest.makeTestGraphDSub2 (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
       0(A)
      /
2(A)-v1-1(B)-(B)-v2
     |\
     | 3(B)-(B)-v2
     \
      4(C)-(C)-v3
Definition at line 564 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testExtractSubgraph().
makeTestGraphE()
DGraph denoptim.graph.DGraphTest.makeTestGraphE (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
2(A)-v1-1(B)-2(A)-v1(*)-1(B)-2(A)-v1(**)
     | \           |\
     |  |          | 3(B)-2(A)-v1(**)
     |  |
     |  3(B)-2(A)-v1(*)-1(B)-2(A)-v1
     |             |\
     |             | 3(B)-2(A)-v1
     \
      4(C)-2(A)-v1
where only those marked with a star are included in the symmetric sets.
Definition at line 613 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets().
makeTestGraphF()
DGraph denoptim.graph.DGraphTest.makeTestGraphF (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
      (C)-(C)-v6-(D)--(D)-v7
      /                    |
     /                   chord
    |                      |
    | (B)-(C)-v6-(D)--(D)-v7
    |  |
    | /     (B)  (A)           (B)
    |/         \/              /
(A)-v1-(B)-(B)-v1-(A)--(A)-v1--(B)
     |          |          |\
    (A)         |          | (C)
                |         (A)
                |
                (C)--(C)-v6-(D)
Definition at line 691 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg(), denoptim.graph.DGraphTest.testGetSymmetricSubGraphs(), and denoptim.graph.DGraphTest.testReplaceSingleSubGraph().
makeTestGraphG()
DGraph denoptim.graph.DGraphTest.makeTestGraphG (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
       (C)-(C)-v6-(D)--(B)-v7
       /                    |
      /                   chord
     |                      |
     | (B)-(C)-v6-(D)--(B)-v7
     |  |            --------------(C)-v6-(D)--(B)-v7
     |  /           /                              |
     | /     (A)  (B)           (B)                |
     |/         \/              /                chord
 (A)-v1-(B)-(B)-v1-(A)--(A)-v1--(B)                |
      |          |          |\                     |
     (A)         |          | (C)--(C)-v6-(D)--(B)-v7
      |          |          |
      |          |         (A)--(C)-v6-(D)--(B)-v7
      |          |                              |
      |          |                            chord
      |          |                              |
      |          ---------(C)--(C)-v6-(D)--(B)--v7
      |
     0(A)
      |
     v1
      |
     2(A)
      |
     0(A)
      |
2(A)-v1-1(B)-(B)-v2
     |\
     | 3(B)-(B)-v2
     \
      4(C)-(C)-v3
This is the result of replacing two vertexes in graph D with Graph F and welding connections.
Definition at line 788 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), and denoptim.graph.Vertex.newVertexFromLibrary().
Referenced by denoptim.graph.DGraphTest.testReplaceSingleSubGraph().
makeTestGraphH()
DGraph denoptim.graph.DGraphTest.makeTestGraphH (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
      (C)-(C)-v6-(D)--(B)-v7
      /                    |
     /                   chord
    |                      |
    | (B)-(C)-v6-(D)--(B)-v7
    |/
(A)-v1-(B)
     \
      (A)
Definition at line 921 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.makeTestGraphI().
makeTestGraphI()
DGraph denoptim.graph.DGraphTest.makeTestGraphI (FragmentSpace fs) throws Exception private
Creates a test graph that looks like this:
      (A)-(C)-v6-(D)--(B)-v7
      /                    |
     /                   chord
    |                      |
    | (B)-(C)-v6-(D)--(B)-v7
    |/
template-(A)
Definition at line 968 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.DGraphTest.makeTestGraphH(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Template.setInnerGraph().
Referenced by denoptim.graph.DGraphTest.testGetInterfaceAPs(), denoptim.graph.DGraphTest.testGetSubgraphAPs(), denoptim.graph.DGraphTest.testGetVertexAnyLevel(), and denoptim.graph.DGraphTest.testReplaceSingleSubGraph_inTemplate().
makeTestGraphJ()
DGraph denoptim.graph.DGraphTest.makeTestGraphJ (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
                    0(A)
                   /
       0(A)--2(A)-v1b-1(B)
      /           | \
2(A)-v1-1(B)       \  3(B)
     |\     \        4(C)-(B)-v2b
     | 3(B)  \
     \       (B)-v2
      4(C)
Definition at line 1019 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testReplaceSingleSubGraph_inTemplate().
makeTestGraphK()
DGraph denoptim.graph.DGraphTest.makeTestGraphK (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
      (C)-(C)-v6-(D)--(C)-v1-(capped)
     /
    | (B)-(C)-v6*-(D)--(C)-v1**-(capped)
    |/
(A)-v1-(B)-(C)-v6*-(D)--(C)-v1**-(capped)
where vertexes marked with either * or ** are in symmetric sets, and "capped" means all APs have been used by capping groups.
Definition at line 1060 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraphTest.cap, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.graph.DGraphTest.testGetSymmetricSubGraphs().
makeTestGraphL()
DGraph denoptim.graph.DGraphTest.makeTestGraphL (FragmentSpace fs) throws DENOPTIMException private
Creates a test graph that looks like this:
       (C)-(C)-v6-(D)--(B)-v7
       /                    |
      /                   chord
     |                      |
     | (B)-(C)-v6-(D)--(B)-v7
     |/
 (A)-v1-(B)
      |
     0(A)
      |
     2(A)
      |
  (B)-v1-(C)-v6-(D)--(B)-v7
      |                  |
     0(A)                 |
      |                chord
     (A)                 |
   v1_scaffold(D)-------(B)-v7
     (A)
      |
     0(A)
      |
     v1
      |
     2(A)
      |
     0(A)
      |
2(A)-v1-1(B)-(B)-v2
     |\
     | 3(B)-(B)-v2
     \
      4(C)-(C)-v3
Definition at line 1168 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testEmbedPatternsInTemplates().
makeTestGraphM()
static DGraph denoptim.graph.DGraphTest.makeTestGraphM () throws DENOPTIMException static
Returns a graph with definition of symmetric vertexes and symmetric APs meant for testing purposes.
Before running this you must run DGraphTest#prepare()
This is the graph we return (symmetric APs are marked by s and s'):
              s(B)-(B)-v3
             /
       (A)-v1-s(B)-(B)-v4
       /     \
      /       s(B)-(B)-v5
     /
  s(A)  s'(B)-v9
 /     /
v0====
 \     \
  s(A)   s'(B)-v10
    |
     \        s(B)-(B)-v6
      \      /
       (A)-v2-s(B)-(B)-v7
             \
              s(B)-(B)-v8
Definition at line 4061 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.addSymmetricAPSet(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.APCA, denoptim.graph.DGraphTest.APCB, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.graph.Vertex.setVertexId().
Referenced by denoptim.graph.DGraphTest.testDetectSymVertexSets().
makeTestGraphN()
static DGraph denoptim.graph.DGraphTest.makeTestGraphN () throws DENOPTIMException static
Returns a graph with peculiar definition of symmetric vertexes and symmetric APs meant for testing purposes.
Before running this you must run DGraphTest#prepare()
This is the graph we return (symmetric APs are marked by s and s'):
              s(B)-(B)-v3
             /
       (B)s-v1-s(B)-(B)-v4
       /     \
      /       s(B)-(B)-v5                     s(B)
     /                                       /
  s(B)  s(B)---------------------------(B)s-v9-s(B)
 /     /                                     \
v0====        (v0 is SCAFFOLD!)               s(B)
 \     \
  s(B)  s(B)
    |
     \        s(B)-(B)-v6
      \      /
       (B)s-v2-s(B)-(B)-v7
             \
              s(B)
Definition at line 4149 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.addSymmetricAPSet(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.APCB, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.graph.Vertex.setVertexId().
makeTestGraphO_A()
static DGraph denoptim.graph.DGraphTest.makeTestGraphO_A (FragmentSpace fs) throws DENOPTIMException static
Creates a test graph that intentionally violates APClass compatibility and looks like this:
 (A)-(A)-v4
  |
 s2-(B)-(D)-v3a-(D)-v7a
  |\                 /
  | \              chord
  |  \              |
  |   (C)-v3b-(D)-v7b
  |
 (A)-(B)-v5
Definition at line 4253 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.DGraphTest.testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ringFormation(), and denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation().
makeTestGraphO_B()
static DGraph denoptim.graph.DGraphTest.makeTestGraphO_B (FragmentSpace fs) throws DENOPTIMException static
Creates a test graph that intentionally violates APClass compatibility and looks like this:
 (A)-(D)-v3b-(D)-v7b
  |              |
  |     v6       |
  |   (D)       chord
  |   |          |
 s1-(D)    (C)--v7a
  |       /
 (A)-(A)-v1-(B)-(B)-v2a
         | \
         |  (B)-(B)-v2b
         (A)-(D)-v3a
Definition at line 4318 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.DGraph.renumberGraphVertices(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
Referenced by denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_differentBranch(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation(), and denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation().
prepare()
static FragmentSpace denoptim.graph.DGraphTest.prepare () throws DENOPTIMException static
Definition at line 79 of file DGraphTest.java.
References denoptim.graph.DGraphTest.a, denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Edge.BondType.ANY, denoptim.graph.DGraphTest.APCA, denoptim.graph.DGraphTest.APCB, denoptim.graph.DGraphTest.APCC, denoptim.graph.DGraphTest.APCD, denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.graph.DGraphTest.b, denoptim.graph.DGraphTest.c, denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraphTest.cap, denoptim.graph.DGraphTest.CAPP, denoptim.graph.DGraphTest.d, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpace.getCappingLibrary(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), denoptim.graph.Vertex.setAsRCV(), and denoptim.graph.Vertex.setBuildingBlockType().
Referenced by denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraphTest.testDetectSymVertexSets(), denoptim.graph.DGraphTest.testEmbedPatternsInTemplates(), denoptim.graph.DGraphTest.testExploreGraph_simpleGraph(), denoptim.graph.DGraphTest.testExtractSubgraph(), denoptim.graph.DGraphTest.testExtractSubgraphFromCollection(), denoptim.graph.DGraphTest.testGetChildrenTree(), denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier(), denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg(), denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone(), denoptim.graph.DGraphTest.testGetEmbeddingPath(), denoptim.graph.DGraphTest.testGetInterfaceAPs(), denoptim.graph.DGraphTest.testGetLevel(), denoptim.graph.DGraphTest.testGetSourceVertex(), denoptim.graph.DGraphTest.testGetSubgraphAPs(), denoptim.graph.DGraphTest.testGetSymmetricSubGraphs(), denoptim.graph.DGraphTest.testGetVertexAnyLevel(), denoptim.graph.DGraphTest.testGraphIsomorphism(), denoptim.graph.DGraphTest.testIsConnected(), denoptim.graph.DGraphTest.testIsIsostructuralTo(), denoptim.graph.rings.PathSubGraphTest.testMakePathSubGraph_differentBranch(), denoptim.ga.XoverSiteTest.testProjectToClonedGraphs(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_inTemplate(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ringFormation(), denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation(), denoptim.graph.DGraphTest.testReplaceVertex(), denoptim.graph.DGraphTest.testReplaceVertex_inRing(), and denoptim.graph.DGraphTest.testSymmetricSetLabels().
testClone()
void denoptim.graph.DGraphTest.testClone () throws DENOPTIMException
Definition at line 2572 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.closableChains, denoptim.graph.DGraph.gEdges, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.AttachmentPoint.getOwner(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.graphId, denoptim.graph.DGraph.gRings, denoptim.graph.DGraph.gVertices, and denoptim.graph.DGraph.localMsg.
testConvertSymmetricLabelsToSymmetricSets()
void denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets () throws Exception
Definition at line 3565 of file DGraphTest.java.
References denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphE(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.Vertex.setProperty(), and denoptim.constants.DENOPTIMConstants.VRTSYMMSETID.
testDetectSymVertexSets()
void denoptim.graph.DGraphTest.testDetectSymVertexSets () throws Exception
Definition at line 4201 of file DGraphTest.java.
References denoptim.graph.DGraph.detectSymVertexSets(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphM(), and denoptim.graph.DGraphTest.prepare().
testEmbedPatternsInTemplates()
void denoptim.graph.DGraphTest.testEmbedPatternsInTemplates () throws Exception
Definition at line 4007 of file DGraphTest.java.
References denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraphTest.makeTestGraphL(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.GraphPattern.RING, and denoptim.graph.Vertex.BBType.SCAFFOLD.
testExploreGraph_noCrossingTemplateBoundary()
void denoptim.graph.DGraphTest.testExploreGraph_noCrossingTemplateBoundary () throws Exception
Definition at line 4413 of file DGraphTest.java.
References denoptim.graph.DGraph.exploreGraph(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph().
testExploreGraph_nothingToExplore()
void denoptim.graph.DGraphTest.testExploreGraph_nothingToExplore () throws Exception
Definition at line 4373 of file DGraphTest.java.
References denoptim.graph.DGraph.exploreGraph(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.graph.Vertex.setBuildingBlockType().
testExploreGraph_simpleGraph()
void denoptim.graph.DGraphTest.testExploreGraph_simpleGraph () throws Exception
Definition at line 4387 of file DGraphTest.java.
References denoptim.graph.DGraph.exploreGraph(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphC(), and denoptim.graph.DGraphTest.prepare().
testExtractSubgraph()
void denoptim.graph.DGraphTest.testExtractSubgraph () throws Exception
Definition at line 3161 of file DGraphTest.java.
References denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.makeTestGraphDSub2(), and denoptim.graph.DGraphTest.prepare().
testExtractSubgraphFromCollection()
void denoptim.graph.DGraphTest.testExtractSubgraphFromCollection () throws Exception
Definition at line 3202 of file DGraphTest.java.
References denoptim.graph.DGraph.extractSubgraph(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexWithId(), denoptim.graph.DGraphTest.makeTestGraphD(), and denoptim.graph.DGraphTest.prepare().
testFindVertex()
void denoptim.graph.DGraphTest.testFindVertex () throws Exception
Definition at line 3260 of file DGraphTest.java.
References denoptim.graph.DGraphTest.b, denoptim.graph.DGraphTest.c, denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraphTest.d, denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.DGraph.findVertices(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.APClass.make(), denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.Vertex.VertexType.MolecularFragment, and denoptim.graph.Edge.BondType.TRIPLE.
testFromToJSON()
void denoptim.graph.DGraphTest.testFromToJSON () throws Exception
Definition at line 3036 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.DGraph.fromJson(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.toJson().
testGetAvailableAPs_returnsListOfAvailableAPs()
void denoptim.graph.DGraphTest.testGetAvailableAPs_returnsListOfAvailableAPs () throws DENOPTIMException
Definition at line 2545 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getAvailableAPs(), and denoptim.graph.Vertex.getVertexId().
testGetChildrenTree()
void denoptim.graph.DGraphTest.testGetChildrenTree () throws Exception
Definition at line 3668 of file DGraphTest.java.
References denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphD(), and denoptim.graph.DGraphTest.prepare().
testGetChildrenTreeWithBranchIdentifier()
void denoptim.graph.DGraphTest.testGetChildrenTreeWithBranchIdentifier () throws Exception
Definition at line 3708 of file DGraphTest.java.
References denoptim.graph.DGraph.directedPathExists(), denoptim.graph.DGraph.getBranchIdOfVertexAtPosition(), denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphD(), and denoptim.graph.DGraphTest.prepare().
testGetEdgesWithSrcOrTrg()
void denoptim.graph.DGraphTest.testGetEdgesWithSrcOrTrg () throws Exception
Definition at line 3985 of file DGraphTest.java.
References denoptim.graph.DGraph.getEdgesWithSrc(), denoptim.graph.DGraph.getEdgesWithTrg(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphF(), and denoptim.graph.DGraphTest.prepare().
testGetEmbeddedGraphInClone()
void denoptim.graph.DGraphTest.testGetEmbeddedGraphInClone () throws Exception
Definition at line 1492 of file DGraphTest.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.getEmbeddedGraphInClone(), denoptim.graph.DGraph.getEmbeddingPath(), denoptim.graph.Template.getInnerGraph(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), and denoptim.graph.DGraphTest.prepare().
testGetEmbeddingPath()
void denoptim.graph.DGraphTest.testGetEmbeddingPath () throws Exception
Definition at line 1464 of file DGraphTest.java.
References denoptim.graph.DGraph.getEmbeddingPath(), denoptim.graph.Template.getInnerGraph(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), and denoptim.graph.DGraphTest.prepare().
testGetInterfaceAPs()
void denoptim.graph.DGraphTest.testGetInterfaceAPs () throws Exception
Definition at line 3753 of file DGraphTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getInterfaceAPs(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphI(), and denoptim.graph.DGraphTest.prepare().
testGetLevel()
void denoptim.graph.DGraphTest.testGetLevel () throws Exception
Definition at line 1564 of file DGraphTest.java.
References denoptim.graph.DGraph.getLevel(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.graph.DGraphTest.makeTestGraphC(), and denoptim.graph.DGraphTest.prepare().
testGetMutationSites()
void denoptim.graph.DGraphTest.testGetMutationSites () throws DENOPTIMException
Definition at line 2663 of file DGraphTest.java.
References denoptim.graph.DGraph.addVertex(), denoptim.graph.Template.ContractLevel.FIXED, denoptim.graph.Template.ContractLevel.FREE, denoptim.graph.DGraph.getMutableSites(), and denoptim.graph.Template.getTestTemplate().
testGetSourceVertex()
void denoptim.graph.DGraphTest.testGetSourceVertex () throws Exception
Definition at line 1547 of file DGraphTest.java.
References denoptim.graph.DGraph.getSourceVertex(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeDisorderedGraph(), denoptim.graph.DGraphTest.makeTestGraphC(), and denoptim.graph.DGraphTest.prepare().
testGetSubgraphAPs()
void denoptim.graph.DGraphTest.testGetSubgraphAPs () throws Exception
Definition at line 3791 of file DGraphTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getSubgraphAPs(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraphTest.makeTestGraphI(), and denoptim.graph.DGraphTest.prepare().
testGetSymmetricSubGraphs()
void denoptim.graph.DGraphTest.testGetSymmetricSubGraphs () throws Exception
Definition at line 3613 of file DGraphTest.java.
References denoptim.graph.DGraph.getSymmetricSubGraphs(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphK(), and denoptim.graph.DGraphTest.prepare().
testGetVertexAnyLevel()
void denoptim.graph.DGraphTest.testGetVertexAnyLevel () throws Exception
Definition at line 4473 of file DGraphTest.java.
References denoptim.graph.Template.getInnerGraph(), denoptim.graph.DGraph.getVertexAnyLevel(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.makeTestGraphI(), and denoptim.graph.DGraphTest.prepare().
testGraphIsomorphism()
void denoptim.graph.DGraphTest.testGraphIsomorphism () throws Exception
Definition at line 3098 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraphTest.makeTestGraph0(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.Vertex.setProperty(), and denoptim.graph.Vertex.setUniquefyingProperty().
testIsConnected()
void denoptim.graph.DGraphTest.testIsConnected () throws Exception
Definition at line 4432 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.isConnected(), denoptim.graph.DGraphTest.makeTestGraphC(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.graph.Vertex.setBuildingBlockType().
testIsIsostructuralTo()
void denoptim.graph.DGraphTest.testIsIsostructuralTo () throws Exception
Definition at line 3897 of file DGraphTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.APCC, denoptim.graph.DGraphTest.APCD, denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraph0(), denoptim.graph.DGraphTest.makeTestGraph1(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphDSub1(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.replaceSingleSubGraph(), denoptim.graph.Vertex.setProperty(), and denoptim.graph.Vertex.setUniquefyingProperty().
testRemoveCapping()
void denoptim.graph.DGraphTest.testRemoveCapping () throws Exception
Definition at line 2923 of file DGraphTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addVertex(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraph.containsVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getGraphOwner(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.removeCappingGroups(), denoptim.graph.DGraph.removeCappingGroupsOn(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
testRemoveUnusedRCVs()
void denoptim.graph.DGraphTest.testRemoveUnusedRCVs () throws Exception
Definition at line 1341 of file DGraphTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraphTest.cap, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getRCVertices(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.graph.APClass.RCACLASSMINUS, denoptim.graph.APClass.RCACLASSPLUS, denoptim.graph.DGraph.replaceUnusedRCVsWithCapps(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.graph.Edge.BondType.SINGLE.
testRemoveVertex()
void denoptim.graph.DGraphTest.testRemoveVertex () throws Exception
Definition at line 2004 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexCount(), and denoptim.graph.DGraph.removeVertex().
testReplaceSingleSubGraph()
void denoptim.graph.DGraphTest.testReplaceSingleSubGraph () throws Exception, DENOPTIMException
Definition at line 1746 of file DGraphTest.java.
References denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.Vertex.getAP(), denoptim.graph.rings.PathSubGraph.getEdgesPath(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSourceVertex(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.makeTestGraphF(), denoptim.graph.DGraphTest.makeTestGraphG(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.reassignSymmetricLabels(), and denoptim.graph.DGraph.replaceSingleSubGraph().
testReplaceSingleSubGraph_inTemplate()
void denoptim.graph.DGraphTest.testReplaceSingleSubGraph_inTemplate () throws Exception
Definition at line 1793 of file DGraphTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getAvailableAPs(), denoptim.graph.Ring.getDistance(), denoptim.graph.Ring.getHeadVertex(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getRings(), denoptim.graph.Ring.getTailVertex(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraphTest.makeTestGraphI(), denoptim.graph.DGraphTest.makeTestGraphJ(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraph.replaceSingleSubGraph().
testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation()
void denoptim.graph.DGraphTest.testReplaceSingleSubGraph_NonScafToNonScaf_withAPClassViolation () throws Exception
Definition at line 1892 of file DGraphTest.java.
References denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraphTest.makeTestGraphO_A(), denoptim.graph.DGraphTest.makeTestGraphO_B(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.reassignSymmetricLabels(), and denoptim.graph.DGraph.replaceSingleSubGraph().
testReplaceSingleSubGraph_ringFormation()
void denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ringFormation () throws Exception
Definition at line 1982 of file DGraphTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraphTest.makeTestGraph_treeWithOutScaffold(), denoptim.graph.DGraphTest.makeTestGraphO_A(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraph.replaceSingleSubGraph().
testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation()
void denoptim.graph.DGraphTest.testReplaceSingleSubGraph_ScafToScaf_withAPClassViolation () throws Exception
Definition at line 1842 of file DGraphTest.java.
References denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.AttachmentPoint.getLinkedAP(), denoptim.graph.DGraph.getRingCount(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraphTest.makeTestGraphO_A(), denoptim.graph.DGraphTest.makeTestGraphO_B(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.reassignSymmetricLabels(), and denoptim.graph.DGraph.replaceSingleSubGraph().
testReplaceVertex()
void denoptim.graph.DGraphTest.testReplaceVertex () throws Exception
Definition at line 1587 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.containsVertex(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAttachmentPoints(), denoptim.graph.Vertex.getBuildingBlockId(), denoptim.graph.Vertex.getBuildingBlockType(), denoptim.graph.DGraph.getSymmetricSetCount(), denoptim.graph.DGraph.getSymSetForVertex(), denoptim.graph.DGraph.getSymSetsIterator(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.gVertices, denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.replaceVertex(), and denoptim.graph.Vertex.BBType.SCAFFOLD.
testReplaceVertex_inRing()
void denoptim.graph.DGraphTest.testReplaceVertex_inRing () throws Exception
Definition at line 1721 of file DGraphTest.java.
References denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraphTest.makeTestGraphD(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraph.replaceVertex().
testSameAs_DiffRings()
void denoptim.graph.DGraphTest.testSameAs_DiffRings () throws DENOPTIMException
Definition at line 2469 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_DiffSymmSet()
void denoptim.graph.DGraphTest.testSameAs_DiffSymmSet () throws Exception
Definition at line 2247 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_DiffVertex()
void denoptim.graph.DGraphTest.testSameAs_DiffVertex () throws DENOPTIMException
Definition at line 2144 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_DisorderRings()
void denoptim.graph.DGraphTest.testSameAs_DisorderRings () throws Exception
Definition at line 2392 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_Equal()
void denoptim.graph.DGraphTest.testSameAs_Equal () throws DENOPTIMException
Definition at line 2109 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_SameRings()
void denoptim.graph.DGraphTest.testSameAs_SameRings () throws DENOPTIMException
Definition at line 2315 of file DGraphTest.java.
References denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSameAs_SameSymmSet()
void denoptim.graph.DGraphTest.testSameAs_SameSymmSet () throws Exception
Definition at line 2179 of file DGraphTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.DGraph.addEdge(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.graph.DGraphTest.buildVertexAndConnectToGraph(), denoptim.graph.Vertex.getAP(), and denoptim.graph.DGraph.sameAs().
testSymmetricSetLabels()
void denoptim.graph.DGraphTest.testSymmetricSetLabels () throws Exception
Definition at line 3531 of file DGraphTest.java.
References denoptim.graph.Vertex.getProperty(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraphTest.makeTestGraphB(), denoptim.graph.DGraphTest.prepare(), denoptim.graph.DGraph.reassignSymmetricLabels(), and denoptim.constants.DENOPTIMConstants.VRTSYMMSETID.
Member Data Documentation
a
String denoptim.graph.DGraphTest.a ="A" static private
Definition at line 75 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphA2(), and denoptim.graph.DGraphTest.prepare().
APCA
APClass denoptim.graph.DGraphTest.APCA static private
Definition at line 74 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraphM(), and denoptim.graph.DGraphTest.prepare().
APCB
APClass denoptim.graph.DGraphTest.APCB static private
Definition at line 74 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.makeIsostructuralGraphs(), denoptim.graph.DGraphTest.makeTestGraphM(), denoptim.graph.DGraphTest.makeTestGraphN(), and denoptim.graph.DGraphTest.prepare().
APCC
APClass denoptim.graph.DGraphTest.APCC static private
Definition at line 74 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
APCD
APClass denoptim.graph.DGraphTest.APCD static private
Definition at line 74 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeDeeplyEmbeddedGraph(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testIsIsostructuralTo().
b
String denoptim.graph.DGraphTest.b ="B" static private
Definition at line 75 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testFindVertex().
c
String denoptim.graph.DGraphTest.c ="C" static private
Definition at line 75 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testFindVertex().
cap
String denoptim.graph.DGraphTest.cap ="cap" static private
Definition at line 75 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphK(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testRemoveUnusedRCVs().
CAPP
APClass denoptim.graph.DGraphTest.CAPP static private
Definition at line 74 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.prepare().
d
String denoptim.graph.DGraphTest.d ="D" static private
Definition at line 75 of file DGraphTest.java.
Referenced by denoptim.graph.DGraphTest.makeTestGraphA2(), denoptim.graph.DGraphTest.prepare(), and denoptim.graph.DGraphTest.testFindVertex().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/DGraphTest.java