DENOPTIM: denoptim.gui.GUI Class Reference
denoptim.gui.GUI Class Reference
Graphical User Interface of the DENOPTIM package.
Public Member Functions
GUI (CommandLine cmd)
Constructor that specifies parameters.
void run ()
Launch the application.
Protected Member Functions
void closeIfAllSaved ()
Close GUI is there are no unsaved changes to the open components.
Static Package Attributes
static final String GUILOGGER = "GUILogger"
Name of logger for the GUI.
static final Randomizer PRNG = new Randomizer(System.currentTimeMillis())
Random number generator specific for the GUI, and any of its tasks.
Static Private Member Functions
static boolean weRunOnMacDarkMode ()
Checks if we are in dark mode.
Private Attributes
JFrame frame
GUI window frame.
JPanel framePane
Panel including tool bar.
GUIMainPanel mainPanel
Panel including all but tool bar.
int width = 960
Default width.
int height = 690
Default height.
CommandLine cmd
Command line options.
Detailed Description
Graphical User Interface of the DENOPTIM package.
This GUI aims to facilitate:
creation of the various types of DENOPTIM input files,
execution of GUI-controlled runs,
reuse and modification of DENOPTIM input files,
inspection of results produced by DENOPTIM runs.
Author
Marco Foscato
Definition at line 56 of file GUI.java.
Constructor & Destructor Documentation
GUI()
denoptim.gui.GUI.GUI (CommandLine cmd)
Constructor that specifies parameters.
Definition at line 103 of file GUI.java.
References denoptim.gui.GUI.cmd, and denoptim.gui.GUI.GUILOGGER.
Member Function Documentation
closeIfAllSaved()
void denoptim.gui.GUI.closeIfAllSaved () protected
Close GUI is there are no unsaved changes to the open components.
Definition at line 225 of file GUI.java.
References denoptim.gui.GUI.frame, denoptim.task.StaticTaskManager.hasActive(), denoptim.gui.GUIMainPanel.hasUnsavedChanges(), denoptim.gui.GUI.mainPanel, and denoptim.task.StaticTaskManager.stopAll().
Referenced by denoptim.gui.MainToolBar.initialize(), and denoptim.gui.GUI.run().
run()
void denoptim.gui.GUI.run ()
Launch the application.
Definition at line 117 of file GUI.java.
References denoptim.gui.GUIMainPanel.add(), denoptim.gui.GUI.closeIfAllSaved(), denoptim.gui.GUI.cmd, denoptim.files.FileUtils.detectFileFormat(), denoptim.gui.GUI.frame, denoptim.gui.GUI.framePane, denoptim.gui.GUI.height, denoptim.gui.GUI.mainPanel, denoptim.gui.MainToolBar.openFile(), denoptim.task.StaticTaskManager.queueStatusBar, denoptim.gui.MainToolBar.setRefToMainPanel(), denoptim.gui.MainToolBar.setRefToMasterGUI(), denoptim.files.FileFormat.UNRECOGNIZED, denoptim.gui.GUI.weRunOnMacDarkMode(), and denoptim.gui.GUI.width.
weRunOnMacDarkMode()
static boolean denoptim.gui.GUI.weRunOnMacDarkMode () static private
Checks if we are in dark mode.
Definition at line 205 of file GUI.java.
Referenced by denoptim.gui.GUI.run().
Member Data Documentation
cmd
CommandLine denoptim.gui.GUI.cmd private
Command line options.
Definition at line 86 of file GUI.java.
Referenced by denoptim.gui.GUI.GUI(), and denoptim.gui.GUI.run().
frame
JFrame denoptim.gui.GUI.frame private
GUI window frame.
Definition at line 61 of file GUI.java.
Referenced by denoptim.gui.GUI.closeIfAllSaved(), and denoptim.gui.GUI.run().
framePane
JPanel denoptim.gui.GUI.framePane private
Panel including tool bar.
Definition at line 66 of file GUI.java.
Referenced by denoptim.gui.GUI.run().
GUILOGGER
final String denoptim.gui.GUI.GUILOGGER = "GUILogger" static package
Name of logger for the GUI.
Definition at line 91 of file GUI.java.
Referenced by denoptim.gui.FragmentViewPanel.getLoadedStructure(), denoptim.gui.GUI.GUI(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
height
int denoptim.gui.GUI.height = 690 private
Default height.
Definition at line 81 of file GUI.java.
Referenced by denoptim.gui.GUI.run().
mainPanel
GUIMainPanel denoptim.gui.GUI.mainPanel private
Panel including all but tool bar.
Definition at line 71 of file GUI.java.
Referenced by denoptim.gui.GUI.closeIfAllSaved(), and denoptim.gui.GUI.run().
PRNG
final Randomizer denoptim.gui.GUI.PRNG = new Randomizer(System.currentTimeMillis()) static package
Random number generator specific for the GUI, and any of its tasks.
Definition at line 96 of file GUI.java.
Referenced by denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer().
width
int denoptim.gui.GUI.width = 960 private
Default width.
Definition at line 76 of file GUI.java.
Referenced by denoptim.gui.GUI.run().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUI.java