DENOPTIM: denoptim.graph.FragIsomorphNode Class Reference
denoptim.graph.FragIsomorphNode Class Reference
Public Member Functions
FragIsomorphNode (IAtom atm)
FragIsomorphNode (AttachmentPoint ap)
String getLabel ()
Object getOriginal ()
boolean isAtm ()
Point3d getPoint3d ()
Package Attributes
String label = "none"
Elemental symbol or name used to identify the node content.
Object original
Reference to the object that originally generated this node.
boolean isAtm = true
true if the original object was an atom.
Detailed Description
Definition at line 9 of file FragIsomorphNode.java.
Constructor & Destructor Documentation
FragIsomorphNode() [1/2]
denoptim.graph.FragIsomorphNode.FragIsomorphNode (IAtom atm)
Definition at line 28 of file FragIsomorphNode.java.
References denoptim.utils.MoleculeUtils.getSymbolOrLabel().
FragIsomorphNode() [2/2]
denoptim.graph.FragIsomorphNode.FragIsomorphNode (AttachmentPoint ap)
Definition at line 37 of file FragIsomorphNode.java.
References denoptim.graph.AttachmentPoint.getAPClass(), and denoptim.graph.APClass.toString().
Member Function Documentation
getLabel()
String denoptim.graph.FragIsomorphNode.getLabel ()
Definition at line 46 of file FragIsomorphNode.java.
References denoptim.graph.FragIsomorphNode.label.
getOriginal()
Object denoptim.graph.FragIsomorphNode.getOriginal ()
Definition at line 53 of file FragIsomorphNode.java.
References denoptim.graph.FragIsomorphNode.original.
getPoint3d()
Point3d denoptim.graph.FragIsomorphNode.getPoint3d ()
Definition at line 67 of file FragIsomorphNode.java.
References denoptim.utils.MoleculeUtils.getPoint3d(), and denoptim.graph.FragIsomorphNode.original.
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement().
isAtm()
boolean denoptim.graph.FragIsomorphNode.isAtm ()
Definition at line 60 of file FragIsomorphNode.java.
References denoptim.graph.FragIsomorphNode.isAtm.
Member Data Documentation
isAtm
boolean denoptim.graph.FragIsomorphNode.isAtm = true package
true if the original object was an atom.
Definition at line 24 of file FragIsomorphNode.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), and denoptim.graph.FragIsomorphNode.isAtm().
label
String denoptim.graph.FragIsomorphNode.label = "none" package
Elemental symbol or name used to identify the node content.
Definition at line 14 of file FragIsomorphNode.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), and denoptim.graph.FragIsomorphNode.getLabel().
original
Object denoptim.graph.FragIsomorphNode.original package
Reference to the object that originally generated this node.
Definition at line 19 of file FragIsomorphNode.java.
Referenced by denoptim.graph.FragIsomorphNode.getOriginal(), and denoptim.graph.FragIsomorphNode.getPoint3d().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/FragIsomorphNode.java