DENOPTIM: denoptim.gui.GUIPrepareFitnessRunner.InputForm Class Reference
denoptim.gui.GUIPrepareFitnessRunner.InputForm Class Reference
Public Member Functions
InputForm (Dimension d)
void importParametersFromDenoptimParamsFile (String fileName) throws Exception
Imports parameters from a properly formatted parameters file.
void importSingleParameter (String key, String value) throws Exception
void putParametersToString (StringBuilder sb) throws Exception
Public Member Functions inherited from denoptim.gui.ParametersForm
ParametersForm ()
Empty constructor.
void importParametersFromDenoptimParamsFile (String fileName) throws Exception
void importSingleParameter (String key, String value) throws Exception
void putParametersToString (StringBuilder sb) throws Exception
boolean hasUnsavedChanges ()
Returns the flag signaling unsaved changes.
void setUnsavedChanges (boolean val)
Set the status of the flag signaling unsaved changes.
void showUnknownKeyWarning (Component parent, String paramType)
Shown a warning dialog that informs the user about having found text that is not present in the ParametersForm implementation and is treated as free text.
void importParametersFromDenoptimParamsFile (String fileName) throws Exception
void importSingleParameter (String key, String value) throws Exception
void putParametersToString (StringBuilder sb) throws Exception
boolean hasUnsavedChanges ()
void setUnsavedChanges (boolean val)
Package Attributes
JPanel block
String keyInFile = "FR-Input"
JTextField txtInFile
String keyOutFile = "FR-Output"
JTextField txtOutFile
String NL = System.getProperty("line.separator")
Package Attributes inherited from denoptim.gui.ParametersForm
final Dimension fileLabelSize = new Dimension(250,28)
Default sizes for file pathname labels.
final int preferredHeight
Default text field height.
final Dimension fileFieldSize = new Dimension(350,preferredHeight)
Default sizes for file pathname fields.
final Dimension strFieldSize = new Dimension(75,preferredHeight)
Default sizes for short pathname fields (i.e., string or number)
Private Attributes
Map< String, Object > mapKeyFieldToValueField
Map connecting the parameter keyword and the field containing the parameter value.
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
Additional Inherited Members
Protected Member Functions inherited from denoptim.gui.ParametersForm
String getStringIfNotEmpty (String key, JTextField field, String prefix, String suffix)
Produced the KEY:VALUE string for a general text field.
String getStringIfNotEmpty (String key, JEditorPane field, boolean multipleLines)
Produced the KEY:VALUE string for a general text editor pane The text can include numbers, characters, or both.
String getStringIfNotEmpty (String key, JTextField field)
Produced the KEY:VALUE string for a general text field.
String getStringForKVLine (String key, JSpinner spinner)
Produced the KEY:VALUE string for a general spinner.
String getStringIfSelected (String key, JRadioButton btn)
Produced the KEY:VALUE string for a on/off button.
String getStringFromTable (String key, JTable tab)
Produced an overall string including one or more KEY:VALUE strings taken from a table.
String getStringFromTable (String key, JTable tab, boolean skipHeader)
Produced an overall string including one or more KEY:VALUE strings taken from a table.
String getStringFromTable (String key, JTable tab, int[] fields, boolean skipHeader)
Produced an overall string including one or more KEY:VALUE strings taken from a table.
String getStringFromTable (String key, JTable tab, int[] fields, String sep, boolean skipHeader)
Produced an overall string including one or more KEY:VALUE strings taken from a table.
void importParametersFromDenoptimParamsFile (String fileName, String keyRoot) throws Exception
Reads in the parameters from a text file collecting
DENOPTIM parameters in the form of KEY=VALUE lines.
void preliminatyTasksUponImportingParams ()
Overwritten by subclasses.
void adaptVisibility ()
Overwritten by subclasses.
void importParameterFromLine (String line) throws Exception
void addToUnformattedTxt (String key, String value)
JPanel getPanelForUnformattedInput ()
String getTextForUnformattedSettings ()
void clearUnformattedTxtArea ()
Protected Attributes inherited from denoptim.gui.ParametersForm
boolean unsavedChanges = false
Flag notifying that some data was not saved.
FieldListener fieldListener
Listener for changes in parameters of this form.
RdbFieldChange rdbFieldChange
Listener for changes in radio button-bound parameters.
TabFieldChange tabFieldChange
Listener for changes in table-bound parameters.
CmbFieldChange cmbFieldChange
Listener for changes in combo box-bound parameters.
Map< String, Boolean > checkedFlags = new HashMap<String,Boolean>()
Map of keyword to search for when reading a parameters file.
JTextArea txtUnformattedInput = new JTextArea(5,20)
Storage of unformatted text for input files.
boolean foundCLIOnlyContent = false
Flag recording we have imported text containing a line that is not interpreted as a GUI-controllable parameter.
Detailed Description
Definition at line 91 of file GUIPrepareFitnessRunner.java.
Constructor & Destructor Documentation
InputForm()
denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm (Dimension d)
Definition at line 114 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.GUIPrepareFitnessRunner.InputForm.block, denoptim.gui.ParametersForm.fieldListener, denoptim.gui.ParametersForm.fileFieldSize, denoptim.gui.ParametersForm.fileLabelSize, denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyInFile, denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyOutFile, denoptim.gui.GUIPrepareFitnessRunner.InputForm.mapKeyFieldToValueField, denoptim.gui.GUIFileOpener.pickFileForTxtField(), denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtInFile, and denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtOutFile.
Member Function Documentation
importParametersFromDenoptimParamsFile()
void denoptim.gui.GUIPrepareFitnessRunner.InputForm.importParametersFromDenoptimParamsFile (String fileName) throws Exception
Imports parameters from a properly formatted parameters file.
The file is a text file with lines containing KEY=VALUE pairs.
Parameters
fileName the pathname of the file to read
Exceptions
Exception
Reimplemented from denoptim.gui.ParametersForm.
Definition at line 184 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.ParametersForm.clearUnformattedTxtArea(), denoptim.gui.GUIPrepareFitnessRunner.InputForm.importParametersFromDenoptimParamsFile(), and denoptim.gui.ParametersForm.showUnknownKeyWarning().
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.importParametersFromDenoptimParamsFile().
importSingleParameter()
void denoptim.gui.GUIPrepareFitnessRunner.InputForm.importSingleParameter (String key, String value) throws Exception
Reimplemented from denoptim.gui.ParametersForm.
Definition at line 196 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.ParametersForm.addToUnformattedTxt(), denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyInFile, and denoptim.gui.GUIPrepareFitnessRunner.InputForm.mapKeyFieldToValueField.
putParametersToString()
void denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString (StringBuilder sb) throws Exception
Reimplemented from denoptim.gui.ParametersForm.
Definition at line 233 of file GUIPrepareFitnessRunner.java.
References denoptim.gui.ParametersForm.getStringIfNotEmpty(), denoptim.gui.ParametersForm.getTextForUnformattedSettings(), denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyInFile, denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyOutFile, denoptim.gui.GUIPrepareFitnessRunner.InputForm.NL, denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtInFile, and denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtOutFile.
Member Data Documentation
block
JPanel denoptim.gui.GUIPrepareFitnessRunner.InputForm.block package
Definition at line 98 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm().
keyInFile
String denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyInFile = "FR-Input" package
Definition at line 106 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.importSingleParameter(), denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString().
keyOutFile
String denoptim.gui.GUIPrepareFitnessRunner.InputForm.keyOutFile = "FR-Output" package
Definition at line 109 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString().
mapKeyFieldToValueField
Map<String,Object> denoptim.gui.GUIPrepareFitnessRunner.InputForm.mapKeyFieldToValueField private
Map connecting the parameter keyword and the field containing the parameter value.
Definition at line 104 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.importSingleParameter(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm().
NL
String denoptim.gui.GUIPrepareFitnessRunner.InputForm.NL = System.getProperty("line.separator") package
Definition at line 112 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString().
serialVersionUID
final long denoptim.gui.GUIPrepareFitnessRunner.InputForm.serialVersionUID = 1L static private
Version UID.
Definition at line 96 of file GUIPrepareFitnessRunner.java.
txtInFile
JTextField denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtInFile package
Definition at line 107 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString().
txtOutFile
JTextField denoptim.gui.GUIPrepareFitnessRunner.InputForm.txtOutFile package
Definition at line 110 of file GUIPrepareFitnessRunner.java.
Referenced by denoptim.gui.GUIPrepareFitnessRunner.InputForm.InputForm(), and denoptim.gui.GUIPrepareFitnessRunner.InputForm.putParametersToString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIPrepareFitnessRunner.java