DENOPTIM: denoptim.gui.GUIGraphHandler Class Reference
denoptim.gui.GUIGraphHandler Class Reference
A panel that understands DENOPTIM graphs and allows to create and edit them.
Classes
class ConfigTemplateDialog
Dialog to configure one or more templates.
class GraphSpinnerChangeEvent
class showHideLabelsListener
Public Member Functions
void paint (Graphics g)
GUIGraphHandler (GUIMainPanel mainPanel)
Constructor.
void importGraphsFromFile (File file)
Imports graphs from file.
boolean hasUnsavedChanges ()
Check whether there are unsaved changes.
void dispose ()
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Static Public Attributes
static AtomicInteger graphHandlerTabUID
Unique identified for instances of this handler.
static AtomicInteger graphUID = new AtomicInteger(1)
Unique identified for graphs built here.
Protected Attributes
ArrayList< DGraph > dnGraphLibrary
The currently loaded list of graphs.
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Private Member Functions
void initialize ()
Initialize the panel and add buttons.
void enableGraphDependentButtons (boolean enable)
void createEmptyVertexAndPlaceItInGraph (ArrayList< AttachmentPoint > selAps)
void startGraphFromFragSpaceOrCreationOfEmptyVertex () throws DENOPTIMException
Start the construction of a new graph from scratch.
void initializeCurrentGraph ()
void addChordOnGraph (ArrayList< Vertex > rcvs)
Edits the currently loaded graph by adding a chord involving the two selected vertices.
void extendGraphFromFragSpace (ArrayList< AttachmentPoint > selAps)
Extends the current graph by appending a node to a specific free AP on the growing graph.
void extendCurrentGraph (AttachmentPoint apOnIncomingVrtx, ArrayList< AttachmentPoint > selAps)
void collectFragAndAPsCompatibleWithSelectedAPs (ArrayList< AttachmentPoint > srcAPs)
void appendGraphsFromConvertingMolecule (File file, FragmenterParameters frgParams, Component parent)
void appendGraphsFromFile (File file)
ArrayList< DGraph > readGraphsFromFile (File file)
void loadCurrentGraphIdxToViewer (boolean keepSprites)
Loads the graph corresponding to the field currGrphIdx.
void clearCurrentSystem ()
Clears the current graph viewer but keeps track of the latest graph loaded.
void updateGraphListSpinner ()
void loadFragmentSpace () throws Exception
void deprotectEditedSystem ()
void protectEditedSystem ()
void removeCurrentDnGraph () throws DENOPTIMException
void saveUnsavedChanges ()
Private Attributes
ArrayList< IAtomContainer > molLibrary
The currently loaded list of molecular representations of the graphs.
DGraph dnGraph
The unsaved version of the currently loaded graph.
int currGrphIdx = 0
The index of the currently loaded dnGraph [0–(n-1)}.
boolean unsavedChanges = false
Flag signaling that loaded data has changes since last save.
GraphVertexMolViewerPanel visualPanel
JPanel graphCtrlPane
JPanel graphNavigPane
JButton btnFragSpace
String loadFSToolTip
JPanel pnlMouseMode
JButton btnPickMode
JButton btnMoveMode
JButton btnAddGraph
JButton btnGraphDel
JButton btnOpenGraphs
JSpinner graphNavigSpinner
JLabel totalGraphsLabel
final GraphSpinnerChangeEvent graphSpinnerListener
JPanel pnlEditVrtxBtns
JButton btnAddLibVrtx
JButton btnAddEmptyVrtx
JButton btnDelSel
JButton btnAddChord
JButton btnAddSymSet
JPanel pnlShowLabels
JButton btnLabAPC
JButton btnLabBT
JButton btnLabBB
JPanel pnlSaveEdits
JButton btnSaveEdits
ArrayList< Vertex > compatVrtxs
Subset of vertices for compatible building block selecting GUI.
Map< Integer, Integer > genToLocIDMap
Map converting fragIDs in fragment library to fragIDs in subset of compatible fragments.
boolean updateMolViewer = false
final String CONTRACTKEY = "CONTRACT"
final String BBTYPEKEY = "BBTYPE"
boolean painted
FragmentSpace fragSpace = null
The fragment space this handler works with.
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
static final IChemObjectBuilder builder
Detailed Description
A panel that understands DENOPTIM graphs and allows to create and edit them.
Author
Marco Foscato
Definition at line 96 of file GUIGraphHandler.java.
Constructor & Destructor Documentation
GUIGraphHandler()
denoptim.gui.GUIGraphHandler.GUIGraphHandler (GUIMainPanel mainPanel)
Constructor.
Definition at line 234 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.graphHandlerTabUID, denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUICardPanel.mainPanel.
Member Function Documentation
addChordOnGraph()
void denoptim.gui.GUIGraphHandler.addChordOnGraph (ArrayList< Vertex > rcvs) private
Edits the currently loaded graph by adding a chord involving the two selected vertices.
Parameters
rcvs the selected vertices. Must be two vertices.
Definition at line 1311 of file GUIGraphHandler.java.
References denoptim.graph.DGraph.addRing(), denoptim.gui.GUIGraphHandler.dnGraph, and denoptim.graph.Edge.BondType.UNDEFINED.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
appendGraphsFromConvertingMolecule()
void denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule (File file, FragmenterParameters frgParams, Component parent) private
Definition at line 1557 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.graph.DGraph.embedPatternsInTemplates(), denoptim.programs.fragmenter.FragmenterParameters.embedRingsInTemplate, denoptim.gui.GUIGraphHandler.fragSpace, denoptim.programs.fragmenter.FragmenterParameters.getCuttingRules(), denoptim.programs.fragmenter.FragmenterParameters.getEmbeddedRingsContract(), denoptim.io.IteratingAtomContainerReader.getIteratorType(), denoptim.programs.fragmenter.FragmenterParameters.getLinearAngleLimit(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.programs.fragmenter.FragmenterParameters.getScaffoldingPolicy(), denoptim.io.IteratingAtomContainerReader.hasNext(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.ga.EAUtils.makeGraphFromFragmentationOfMol(), denoptim.gui.GUIGraphHandler.molLibrary, denoptim.io.IteratingAtomContainerReader.next(), denoptim.fragmenter.FragmenterTools.prepareMolToFragmentation(), denoptim.graph.GraphPattern.RING, denoptim.programs.fragmenter.FragmenterParameters.setAddExplicitH(), denoptim.programs.fragmenter.FragmenterParameters.setWorkingIn3D(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
Referenced by denoptim.gui.GUIGraphHandler.initialize().
appendGraphsFromFile()
void denoptim.gui.GUIGraphHandler.appendGraphsFromFile (File file) private
Definition at line 1686 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.builder, denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.files.FileUtils.detectFileFormat(), denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.molLibrary, denoptim.gui.GUIGraphHandler.readGraphsFromFile(), denoptim.io.DenoptimIO.readSDFFile(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
Referenced by denoptim.gui.GUIGraphHandler.initialize().
clearCurrentSystem()
void denoptim.gui.GUIGraphHandler.clearCurrentSystem () private
Clears the current graph viewer but keeps track of the latest graph loaded.
Definition at line 1851 of file GUIGraphHandler.java.
References denoptim.gui.GraphVertexMolViewerPanel.clearCurrentSystem(), denoptim.gui.GUIGraphHandler.dnGraph, and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), and denoptim.gui.GUIGraphHandler.removeCurrentDnGraph().
collectFragAndAPsCompatibleWithSelectedAPs()
void denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs (ArrayList< AttachmentPoint > srcAPs) private
Definition at line 1460 of file GUIGraphHandler.java.
References denoptim.graph.Vertex.clone(), denoptim.gui.GUIGraphHandler.compatVrtxs, denoptim.gui.GUIGraphHandler.fragSpace, denoptim.gui.GUIGraphHandler.genToLocIDMap, denoptim.fragspace.FragmentSpace.getAPsCompatibleWithThese(), denoptim.graph.Vertex.getProperty(), denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELD, denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELDSEP, and denoptim.graph.Vertex.setProperty().
Referenced by denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace().
createEmptyVertexAndPlaceItInGraph()
void denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph (ArrayList< AttachmentPoint > selAps) private
Definition at line 1092 of file GUIGraphHandler.java.
References denoptim.graph.DGraph.addVertex(), denoptim.gui.GUIModalDialog.btnDone, denoptim.gui.GUIVertexSelector.ctrlPane, denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.graph.Vertex.getAP(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIVertexSelector.load(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.protectEditedSystem(), denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate(), denoptim.gui.GUIVertexSelector.setRequireApSelection(), denoptim.gui.GUIModalDialog.showDialog(), denoptim.gui.GUIGraphHandler.unsavedChanges, denoptim.gui.GUIGraphHandler.updateMolViewer, and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
deprotectEditedSystem()
void denoptim.gui.GUIGraphHandler.deprotectEditedSystem () private
Definition at line 1915 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.btnAddGraph, denoptim.gui.GUIGraphHandler.btnOpenGraphs, denoptim.gui.GUIGraphHandler.btnSaveEdits, denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.graphNavigSpinner, denoptim.gui.GUIGraphHandler.graphSpinnerListener, and denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.setEnabled().
Referenced by denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), and denoptim.gui.GUIGraphHandler.saveUnsavedChanges().
dispose()
void denoptim.gui.GUIGraphHandler.dispose ()
Definition at line 2053 of file GUIGraphHandler.java.
References denoptim.gui.GraphVertexMolViewerPanel.dispose(), and denoptim.gui.GUIGraphHandler.visualPanel.
enableGraphDependentButtons()
void denoptim.gui.GUIGraphHandler.enableGraphDependentButtons (boolean enable) private
Definition at line 1078 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.btnAddChord, denoptim.gui.GUIGraphHandler.btnAddLibVrtx, denoptim.gui.GUIGraphHandler.btnAddSymSet, denoptim.gui.GUIGraphHandler.btnDelSel, denoptim.gui.GUIGraphHandler.btnLabAPC, denoptim.gui.GUIGraphHandler.btnLabBB, and denoptim.gui.GUIGraphHandler.btnLabBT.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
extendCurrentGraph()
void denoptim.gui.GUIGraphHandler.extendCurrentGraph (AttachmentPoint apOnIncomingVrtx, ArrayList< AttachmentPoint > selAps) private
Definition at line 1429 of file GUIGraphHandler.java.
References denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.clone(), denoptim.gui.GUIGraphHandler.dnGraph, denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getIndexInOwner(), denoptim.graph.DGraph.getMaxVertexId(), denoptim.graph.AttachmentPoint.getOwner(), and denoptim.graph.Vertex.setVertexId().
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), and denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace().
extendGraphFromFragSpace()
void denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace (ArrayList< AttachmentPoint > selAps) private
Extends the current graph by appending a node to a specific free AP on the growing graph.
This method will prompt a question on which incoming fragment to append
Parameters
selAps attachment points on the growing graph.
Definition at line 1345 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.gui.GUIGraphHandler.compatVrtxs, denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.gui.GUIGraphHandler.fragSpace, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getCappingLibrary(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.gui.GUIVertexSelector.load(), denoptim.gui.GUIVertexSelector.setRequireApSelection(), and denoptim.gui.GUIModalDialog.showDialog().
Referenced by denoptim.gui.GUIGraphHandler.initialize().
hasUnsavedChanges()
boolean denoptim.gui.GUIGraphHandler.hasUnsavedChanges ()
Check whether there are unsaved changes.
Returns
true if there are unsaved changes.
Reimplemented from denoptim.gui.GUICardPanel.
Definition at line 2042 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.unsavedChanges.
importGraphsFromFile()
void denoptim.gui.GUIGraphHandler.importGraphsFromFile (File file)
Imports graphs from file.
Parameters
file the file to open
Definition at line 1507 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.builder, denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.files.FileUtils.detectFileFormat(), denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUICardPanel.mainPanel, denoptim.gui.GUIGraphHandler.molLibrary, denoptim.gui.GUI.PRNG, denoptim.gui.GUIGraphHandler.readGraphsFromFile(), denoptim.io.DenoptimIO.readSDFFile(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
Referenced by denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIInspectFSERun.initialize(), denoptim.gui.GUIInspectGARun.initialize(), and denoptim.gui.MainToolBar.openFile().
initialize()
void denoptim.gui.GUIGraphHandler.initialize () private
Initialize the panel and add buttons.
Definition at line 247 of file GUIGraphHandler.java.
References denoptim.gui.ButtonsBar.add(), denoptim.gui.GUIGraphHandler.addChordOnGraph(), denoptim.graph.DGraph.addSymmetricSetOfVertices(), denoptim.files.FileUtils.addToRecentFiles(), denoptim.gui.GraphViewerPanel.LabelType.APC, denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GraphViewerPanel.LabelType.BBID, denoptim.gui.GUIGraphHandler.BBTYPEKEY, denoptim.gui.GraphViewerPanel.LabelType.BT, denoptim.gui.GUIGraphHandler.btnAddChord, denoptim.gui.GUIGraphHandler.btnAddEmptyVrtx, denoptim.gui.GUIGraphHandler.btnAddGraph, denoptim.gui.GUIGraphHandler.btnAddLibVrtx, denoptim.gui.GUIGraphHandler.btnAddSymSet, denoptim.gui.GUIGraphHandler.btnDelSel, denoptim.gui.GUIGraphHandler.btnFragSpace, denoptim.gui.GUIGraphHandler.btnGraphDel, denoptim.gui.GUIGraphHandler.btnLabAPC, denoptim.gui.GUIGraphHandler.btnLabBB, denoptim.gui.GUIGraphHandler.btnLabBT, denoptim.gui.GUIGraphHandler.btnMoveMode, denoptim.gui.GUIGraphHandler.btnOpenGraphs, denoptim.gui.GUIGraphHandler.btnPickMode, denoptim.gui.GUIGraphHandler.btnSaveEdits, denoptim.gui.GUIGraphHandler.CONTRACTKEY, denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIVertexInspector.dialogToDefineCuttingRules(), denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.files.FileAndFormat.file, denoptim.files.FileAndFormat.format, denoptim.gui.GUIGraphHandler.fragSpace, denoptim.gui.GraphVertexMolViewerPanel.getAPsSelectedInViewer(), denoptim.programs.fragmenter.FragmenterParameters.getCuttingRulesFilePathname(), denoptim.gui.GraphVertexMolViewerPanel.getSelectedNodesInViewer(), denoptim.gui.GUIGraphHandler.graphCtrlPane, denoptim.gui.GUIGraphHandler.graphNavigPane, denoptim.gui.GUIGraphHandler.graphNavigSpinner, denoptim.gui.GUIGraphHandler.graphSpinnerListener, denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.loadFragmentSpace(), denoptim.gui.GUIGraphHandler.loadFSToolTip, denoptim.gui.GUIFileOpener.pickFile(), denoptim.gui.GUIFileSaver.pickFileForSavingGraphs(), denoptim.gui.GUIFileSaver.pickFileForSavingVertexes(), denoptim.gui.GUIFileOpener.pickFileWithGraph(), denoptim.gui.GUIGraphHandler.pnlEditVrtxBtns, denoptim.gui.GUIGraphHandler.pnlMouseMode, denoptim.gui.GUIGraphHandler.pnlSaveEdits, denoptim.gui.GUIGraphHandler.pnlShowLabels, denoptim.gui.GUI.PRNG, denoptim.gui.GUIGraphHandler.protectEditedSystem(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.graph.DGraph.removeVertex(), denoptim.gui.GraphVertexMolViewerPanel.renderMolVieverToNeedUpdate(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), denoptim.graph.Template.setContractLevel(), denoptim.graph.Template.setInnerGraph(), denoptim.gui.GraphVertexMolViewerPanel.setMouseMode(), denoptim.gui.GUIModalDialog.showDialog(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.gui.GUIGraphHandler.totalGraphsLabel, denoptim.gui.GUIGraphHandler.unsavedChanges, denoptim.gui.GUIGraphHandler.updateMolViewer, denoptim.gui.GUIGraphHandler.visualPanel, denoptim.io.DenoptimIO.writeGraphsToFile(), and denoptim.io.DenoptimIO.writeVertexesToFile().
Referenced by denoptim.gui.GUIGraphHandler.GUIGraphHandler().
initializeCurrentGraph()
void denoptim.gui.GUIGraphHandler.initializeCurrentGraph () private
Definition at line 1291 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.builder, denoptim.gui.GraphVertexMolViewerPanel.clearMolecularViewer(), denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.graphUID, denoptim.gui.GUIGraphHandler.molLibrary, denoptim.graph.DGraph.setGraphId(), denoptim.gui.GUIGraphHandler.updateGraphListSpinner(), and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
loadCurrentGraphIdxToViewer()
void denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer (boolean keepSprites) private
Loads the graph corresponding to the field currGrphIdx.
Definition at line 1815 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.clearCurrentSystem(), denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.gui.GUIGraphHandler.molLibrary, and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), and denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.stateChanged().
loadFragmentSpace()
void denoptim.gui.GUIGraphHandler.loadFragmentSpace () throws Exception private
Definition at line 1903 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.fragSpace, denoptim.gui.FSParamsDialog.makeFragSpace(), denoptim.gui.GraphVertexMolViewerPanel.resetFragViewerCardDeck(), and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
paint()
void denoptim.gui.GUIGraphHandler.paint (Graphics g)
Definition at line 220 of file GUIGraphHandler.java.
References denoptim.gui.GraphVertexMolViewerPanel.moveDividerLocation(), denoptim.gui.GUIGraphHandler.painted, and denoptim.gui.GUIGraphHandler.visualPanel.
protectEditedSystem()
void denoptim.gui.GUIGraphHandler.protectEditedSystem () private
Definition at line 1940 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.btnAddGraph, denoptim.gui.GUIGraphHandler.btnOpenGraphs, denoptim.gui.GUIGraphHandler.btnSaveEdits, denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.graphNavigSpinner, denoptim.gui.GUIGraphHandler.graphSpinnerListener, and denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.setEnabled().
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
readGraphsFromFile()
ArrayList< DGraph > denoptim.gui.GUIGraphHandler.readGraphsFromFile (File file) private
Definition at line 1742 of file GUIGraphHandler.java.
References denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), and denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile().
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), and denoptim.gui.GUIGraphHandler.importGraphsFromFile().
removeCurrentDnGraph()
void denoptim.gui.GUIGraphHandler.removeCurrentDnGraph () throws DENOPTIMException private
Definition at line 1958 of file GUIGraphHandler.java.
References denoptim.gui.GraphVertexMolViewerPanel.bringCardToTopOfMolViewer(), denoptim.gui.GUIGraphHandler.clearCurrentSystem(), denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GraphVertexMolViewerPanel.EMPTYCARDNAME, denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.molLibrary, denoptim.gui.GUIGraphHandler.totalGraphsLabel, denoptim.gui.GUIGraphHandler.updateGraphListSpinner(), and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
saveUnsavedChanges()
void denoptim.gui.GUIGraphHandler.saveUnsavedChanges () private
Definition at line 2003 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.builder, denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.molLibrary, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.gui.GraphVertexMolViewerPanel.updateMolevularViewer(), denoptim.gui.GUIGraphHandler.updateMolViewer, and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
startGraphFromFragSpaceOrCreationOfEmptyVertex()
void denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex () throws DENOPTIMException private
Start the construction of a new graph from scratch.
Exceptions
DENOPTIMException
Definition at line 1168 of file GUIGraphHandler.java.
References denoptim.graph.DGraph.addVertex(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraph, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.gui.GUIGraphHandler.fragSpace, denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIVertexSelector.load(), denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.gui.GUIGraphHandler.protectEditedSystem(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.gui.GUIVertexSelector.setRequireApSelection(), denoptim.gui.GUIModalDialog.showDialog(), denoptim.gui.GUIGraphHandler.unsavedChanges, denoptim.gui.GUIGraphHandler.updateMolViewer, and denoptim.gui.GUIGraphHandler.visualPanel.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
updateGraphListSpinner()
void denoptim.gui.GUIGraphHandler.updateGraphListSpinner () private
Definition at line 1860 of file GUIGraphHandler.java.
References denoptim.gui.GUIGraphHandler.currGrphIdx, denoptim.gui.GUIGraphHandler.dnGraphLibrary, denoptim.gui.GUIGraphHandler.graphNavigSpinner, and denoptim.gui.GUIGraphHandler.totalGraphsLabel.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), and denoptim.gui.GUIGraphHandler.removeCurrentDnGraph().
Member Data Documentation
BBTYPEKEY
final String denoptim.gui.GUIGraphHandler.BBTYPEKEY = "BBTYPE" private
Definition at line 208 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.ConfigTemplateDialog.ConfigTemplateDialog(), and denoptim.gui.GUIGraphHandler.initialize().
btnAddChord
JButton denoptim.gui.GUIGraphHandler.btnAddChord private
Definition at line 177 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnAddEmptyVrtx
JButton denoptim.gui.GUIGraphHandler.btnAddEmptyVrtx private
Definition at line 175 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
btnAddGraph
JButton denoptim.gui.GUIGraphHandler.btnAddGraph private
Definition at line 163 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.protectEditedSystem().
btnAddLibVrtx
JButton denoptim.gui.GUIGraphHandler.btnAddLibVrtx private
Definition at line 174 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnAddSymSet
JButton denoptim.gui.GUIGraphHandler.btnAddSymSet private
Definition at line 178 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnDelSel
JButton denoptim.gui.GUIGraphHandler.btnDelSel private
Definition at line 176 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnFragSpace
JButton denoptim.gui.GUIGraphHandler.btnFragSpace private
Definition at line 152 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
btnGraphDel
JButton denoptim.gui.GUIGraphHandler.btnGraphDel private
Definition at line 164 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
btnLabAPC
JButton denoptim.gui.GUIGraphHandler.btnLabAPC private
Definition at line 181 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnLabBB
JButton denoptim.gui.GUIGraphHandler.btnLabBB private
Definition at line 183 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnLabBT
JButton denoptim.gui.GUIGraphHandler.btnLabBT private
Definition at line 182 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.enableGraphDependentButtons(), and denoptim.gui.GUIGraphHandler.initialize().
btnMoveMode
JButton denoptim.gui.GUIGraphHandler.btnMoveMode private
Definition at line 161 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
btnOpenGraphs
JButton denoptim.gui.GUIGraphHandler.btnOpenGraphs private
Definition at line 166 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.protectEditedSystem().
btnPickMode
JButton denoptim.gui.GUIGraphHandler.btnPickMode private
Definition at line 160 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
btnSaveEdits
JButton denoptim.gui.GUIGraphHandler.btnSaveEdits private
Definition at line 186 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.protectEditedSystem().
builder
final IChemObjectBuilder denoptim.gui.GUIGraphHandler.builder static private
Initial value:
=
            SilentChemObjectBuilder.getInstance()
Definition at line 204 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), and denoptim.gui.GUIGraphHandler.saveUnsavedChanges().
compatVrtxs
ArrayList<Vertex> denoptim.gui.GUIGraphHandler.compatVrtxs private
Subset of vertices for compatible building block selecting GUI.
These vertices are clones of those in the loaded library, and are annotate with fragmentID and AP pointers meant to facilitate a quick selection of compatible connections.
Definition at line 194 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), and denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace().
CONTRACTKEY
final String denoptim.gui.GUIGraphHandler.CONTRACTKEY = "CONTRACT" private
Definition at line 207 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.ConfigTemplateDialog.ConfigTemplateDialog(), and denoptim.gui.GUIGraphHandler.initialize().
currGrphIdx
int denoptim.gui.GUIGraphHandler.currGrphIdx = 0 private
The index of the currently loaded dnGraph [0–(n-1)}.
Definition at line 135 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.protectEditedSystem(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.stateChanged(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
dnGraph
DGraph denoptim.gui.GUIGraphHandler.dnGraph private
The unsaved version of the currently loaded graph.
Definition at line 125 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.addChordOnGraph(), denoptim.gui.GUIGraphHandler.clearCurrentSystem(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.extendCurrentGraph(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
dnGraphLibrary
ArrayList<DGraph> denoptim.gui.GUIGraphHandler.dnGraphLibrary protected
Initial value:
=
            new ArrayList<DGraph>()
The currently loaded list of graphs.
Definition at line 112 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
fragSpace
FragmentSpace denoptim.gui.GUIGraphHandler.fragSpace = null private
The fragment space this handler works with.
Definition at line 215 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs(), denoptim.gui.GUIGraphHandler.extendGraphFromFragSpace(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.loadFragmentSpace(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
genToLocIDMap
Map<Integer,Integer> denoptim.gui.GUIGraphHandler.genToLocIDMap private
Map converting fragIDs in fragment library to fragIDs in subset of compatible fragments.
Definition at line 200 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.collectFragAndAPsCompatibleWithSelectedAPs().
graphCtrlPane
JPanel denoptim.gui.GUIGraphHandler.graphCtrlPane private
Definition at line 146 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
graphHandlerTabUID
AtomicInteger denoptim.gui.GUIGraphHandler.graphHandlerTabUID static
Initial value:
=
            new AtomicInteger(1)
Unique identified for instances of this handler.
Definition at line 106 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.GUIGraphHandler().
graphNavigPane
JPanel denoptim.gui.GUIGraphHandler.graphNavigPane private
Definition at line 149 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
graphNavigSpinner
JSpinner denoptim.gui.GUIGraphHandler.graphNavigSpinner private
Definition at line 168 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.protectEditedSystem(), denoptim.gui.GUIGraphHandler.GraphSpinnerChangeEvent.stateChanged(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
graphSpinnerListener
final GraphSpinnerChangeEvent denoptim.gui.GUIGraphHandler.graphSpinnerListener private
Initial value:
=
            new GraphSpinnerChangeEvent()
Definition at line 170 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.deprotectEditedSystem(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.protectEditedSystem().
graphUID
AtomicInteger denoptim.gui.GUIGraphHandler.graphUID = new AtomicInteger(1) static
Unique identified for graphs built here.
Definition at line 130 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initializeCurrentGraph().
loadFSToolTip
String denoptim.gui.GUIGraphHandler.loadFSToolTip private
Initial value:
= "<html>Loads a space of graph building "
            + "blocks (BB Space).<br>"
            + "Graphs can be inspected without loading any space.<br>"
            + "However, loading a space allows to edit and build"
            + "graphs manually.</html>"
Definition at line 153 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
molLibrary
ArrayList<IAtomContainer> denoptim.gui.GUIGraphHandler.molLibrary private
Initial value:
=
            new ArrayList<IAtomContainer>()
The currently loaded list of molecular representations of the graphs.
Definition at line 119 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromConvertingMolecule(), denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), and denoptim.gui.GUIGraphHandler.saveUnsavedChanges().
painted
boolean denoptim.gui.GUIGraphHandler.painted private
Definition at line 210 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.paint().
pnlEditVrtxBtns
JPanel denoptim.gui.GUIGraphHandler.pnlEditVrtxBtns private
Definition at line 173 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
pnlMouseMode
JPanel denoptim.gui.GUIGraphHandler.pnlMouseMode private
Definition at line 159 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
pnlSaveEdits
JPanel denoptim.gui.GUIGraphHandler.pnlSaveEdits private
Definition at line 185 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
pnlShowLabels
JPanel denoptim.gui.GUIGraphHandler.pnlShowLabels private
Definition at line 180 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize().
serialVersionUID
final long denoptim.gui.GUIGraphHandler.serialVersionUID = 1L static private
Version UID.
Definition at line 101 of file GUIGraphHandler.java.
totalGraphsLabel
JLabel denoptim.gui.GUIGraphHandler.totalGraphsLabel private
Definition at line 169 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), and denoptim.gui.GUIGraphHandler.updateGraphListSpinner().
unsavedChanges
boolean denoptim.gui.GUIGraphHandler.unsavedChanges = false private
Flag signaling that loaded data has changes since last save.
Definition at line 140 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.hasUnsavedChanges(), denoptim.gui.GUIGraphHandler.initialize(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
updateMolViewer
boolean denoptim.gui.GUIGraphHandler.updateMolViewer = false private
Definition at line 202 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
visualPanel
GraphVertexMolViewerPanel denoptim.gui.GUIGraphHandler.visualPanel private
Definition at line 143 of file GUIGraphHandler.java.
Referenced by denoptim.gui.GUIGraphHandler.showHideLabelsListener.actionPerformed(), denoptim.gui.GUIGraphHandler.clearCurrentSystem(), denoptim.gui.GUIGraphHandler.createEmptyVertexAndPlaceItInGraph(), denoptim.gui.GUIGraphHandler.dispose(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIGraphHandler.initializeCurrentGraph(), denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(), denoptim.gui.GUIGraphHandler.loadFragmentSpace(), denoptim.gui.GUIGraphHandler.paint(), denoptim.gui.GUIGraphHandler.removeCurrentDnGraph(), denoptim.gui.GUIGraphHandler.saveUnsavedChanges(), and denoptim.gui.GUIGraphHandler.startGraphFromFragSpaceOrCreationOfEmptyVertex().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIGraphHandler.java