DENOPTIM: denoptim.molecularmodeling.zmatrix.ZMatrixBond Class Reference
denoptim.molecularmodeling.zmatrix.ZMatrixBond Class Reference
Representation of a bond in the ZMatrix.
Public Member Functions
ZMatrixBond (ZMatrixAtom atm1, ZMatrixAtom atm2)
Constructor for ZMatrixBond.
ZMatrixAtom getAtm1 ()
Get the first atom in the bond.
ZMatrixAtom getAtm2 ()
Get the second atom in the bond.
void setAtm1 (ZMatrixAtom atm1)
Set the first atom in the bond.
void setAtm2 (ZMatrixAtom atm2)
Set the second atom in the bond.
boolean equals (Object o)
int hashCode ()
String toString ()
Private Attributes
ZMatrixAtom atm1
ZMatrixAtom atm2
Detailed Description
Representation of a bond in the ZMatrix.
Definition at line 6 of file ZMatrixBond.java.
Constructor & Destructor Documentation
ZMatrixBond()
denoptim.molecularmodeling.zmatrix.ZMatrixBond.ZMatrixBond (ZMatrixAtom atm1, ZMatrixAtom atm2)
Constructor for ZMatrixBond.
Parameters
atm1 The first atom in the bond
atm2 The second atom in the bond
Definition at line 18 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1, and denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals().
Member Function Documentation
equals()
boolean denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals (Object o)
Definition at line 71 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1, denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2, denoptim.molecularmodeling.zmatrix.ZMatrixAtom.equals(), and denoptim.molecularmodeling.zmatrix.ZMatrixBond.ZMatrixBond().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixBondEquals().
getAtm1()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm1 ()
Get the first atom in the bond.
Returns
The first atom in the bond
Definition at line 30 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), and denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone().
getAtm2()
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm2 ()
Get the second atom in the bond.
Returns
The second atom in the bond
Definition at line 41 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrix.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixTest.testClone(), and denoptim.molecularmodeling.zmatrix.ZMatrixBondTest.testEquals().
hashCode()
int denoptim.molecularmodeling.zmatrix.ZMatrixBond.hashCode ()
Definition at line 90 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1, denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId().
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixAtomTest.testZMatrixBondHashCode(), and denoptim.molecularmodeling.zmatrix.ZMatrixBondTest.testZMatrixBondHashCode().
setAtm1()
void denoptim.molecularmodeling.zmatrix.ZMatrixBond.setAtm1 (ZMatrixAtom atm1)
Set the first atom in the bond.
Parameters
atm1 The first atom in the bond to set
Definition at line 52 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixBondTest.testEquals().
setAtm2()
void denoptim.molecularmodeling.zmatrix.ZMatrixBond.setAtm2 (ZMatrixAtom atm2)
Set the second atom in the bond.
Parameters
atm2 The second atom in the bond to set
Definition at line 63 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2.
toString()
String denoptim.molecularmodeling.zmatrix.ZMatrixBond.toString ()
Definition at line 104 of file ZMatrixBond.java.
References denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1, denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2, and denoptim.molecularmodeling.zmatrix.ZMatrixAtom.getId().
Member Data Documentation
atm1
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm1 private
Definition at line 8 of file ZMatrixBond.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm1(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.setAtm1(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixBond.ZMatrixBond().
atm2
ZMatrixAtom denoptim.molecularmodeling.zmatrix.ZMatrixBond.atm2 private
Definition at line 9 of file ZMatrixBond.java.
Referenced by denoptim.molecularmodeling.zmatrix.ZMatrixBond.equals(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.getAtm2(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.hashCode(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.setAtm2(), denoptim.molecularmodeling.zmatrix.ZMatrixBond.toString(), and denoptim.molecularmodeling.zmatrix.ZMatrixBond.ZMatrixBond().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/molecularmodeling/zmatrix/ZMatrixBond.java