DENOPTIM: denoptim.graph.EdgeQuery Class Reference
denoptim.graph.EdgeQuery Class Reference
A query for edges: a list of properties that target edges should possess in order to match this query.
Public Member Functions
EdgeQuery (Long srcVertexId, Long trgVertexId, Integer srcAPID, Integer trgAPID, BondType bt, APClass srcAPC, APClass trgAPC)
Constructor for an edge from all parameters.
Long getSourceVertexId ()
Integer getSourceAPIdx ()
Integer getTargetAPIdx ()
Long getTargetVertexId ()
APClass getSourceAPClass ()
APClass getTargetAPClass ()
BondType getBondType ()
Private Attributes
Long srcVertexId = null
The vertex id of the source fragment.
Long trgVertexId = null
the vertex id of the destination fragment
Integer srcAPID = null
The index of the attachment point in the list of DAPs associated with the source fragment.
Integer trgAPID = null
The index of the attachment point in the list of DAPs associated with the target fragment.
BondType bondType = null
The bond type associated with the connection between the fragments.
APClass srcAPC = null
The class associated with the source AP.
APClass trgAPC = null
The class associated with the target AP.
Detailed Description
A query for edges: a list of properties that target edges should possess in order to match this query.
Definition at line 27 of file EdgeQuery.java.
Constructor & Destructor Documentation
EdgeQuery()
denoptim.graph.EdgeQuery.EdgeQuery (Long srcVertexId, Long trgVertexId, Integer srcAPID, Integer trgAPID, BondType bt, APClass srcAPC, APClass trgAPC)
Constructor for an edge from all parameters.
Parameters
srcVertexId vertex ID of the source vertex
trgVertexId vertex ID of the target vertex
srcAPID index of the AttachmentPoint on the source vertex
trgAPID index of the AttachmentPoint on the target vertex
btype the bond type
srcAPC the APClass on the source AttachmentPoint .
trgAPC the APClass on the target AttachmentPoint .
Definition at line 83 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.srcAPC, denoptim.graph.EdgeQuery.srcAPID, denoptim.graph.EdgeQuery.srcVertexId, denoptim.graph.EdgeQuery.trgAPC, denoptim.graph.EdgeQuery.trgAPID, and denoptim.graph.EdgeQuery.trgVertexId.
Member Function Documentation
getBondType()
BondType denoptim.graph.EdgeQuery.getBondType ()
Definition at line 140 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.bondType.
Referenced by denoptim.graph.DGraph.findVertices().
getSourceAPClass()
APClass denoptim.graph.EdgeQuery.getSourceAPClass ()
Definition at line 126 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.srcAPC.
Referenced by denoptim.graph.DGraph.findVertices().
getSourceAPIdx()
Integer denoptim.graph.EdgeQuery.getSourceAPIdx ()
Definition at line 105 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.srcAPID.
Referenced by denoptim.graph.DGraph.findVertices().
getSourceVertexId()
Long denoptim.graph.EdgeQuery.getSourceVertexId ()
Definition at line 98 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.srcVertexId.
Referenced by denoptim.graph.DGraph.findVertices().
getTargetAPClass()
APClass denoptim.graph.EdgeQuery.getTargetAPClass ()
Definition at line 133 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.trgAPC.
Referenced by denoptim.graph.DGraph.findVertices().
getTargetAPIdx()
Integer denoptim.graph.EdgeQuery.getTargetAPIdx ()
Definition at line 112 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.trgAPID.
Referenced by denoptim.graph.DGraph.findVertices().
getTargetVertexId()
Long denoptim.graph.EdgeQuery.getTargetVertexId ()
Definition at line 119 of file EdgeQuery.java.
References denoptim.graph.EdgeQuery.trgVertexId.
Referenced by denoptim.graph.DGraph.findVertices().
Member Data Documentation
bondType
BondType denoptim.graph.EdgeQuery.bondType = null private
The bond type associated with the connection between the fragments.
Definition at line 55 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.getBondType().
srcAPC
APClass denoptim.graph.EdgeQuery.srcAPC = null private
The class associated with the source AP.
Definition at line 60 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getSourceAPClass().
srcAPID
Integer denoptim.graph.EdgeQuery.srcAPID = null private
The index of the attachment point in the list of DAPs associated with the source fragment.
Definition at line 44 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getSourceAPIdx().
srcVertexId
Long denoptim.graph.EdgeQuery.srcVertexId = null private
The vertex id of the source fragment.
Definition at line 33 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getSourceVertexId().
trgAPC
APClass denoptim.graph.EdgeQuery.trgAPC = null private
The class associated with the target AP.
Definition at line 65 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getTargetAPClass().
trgAPID
Integer denoptim.graph.EdgeQuery.trgAPID = null private
The index of the attachment point in the list of DAPs associated with the target fragment.
Definition at line 50 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getTargetAPIdx().
trgVertexId
Long denoptim.graph.EdgeQuery.trgVertexId = null private
the vertex id of the destination fragment
Definition at line 38 of file EdgeQuery.java.
Referenced by denoptim.graph.EdgeQuery.EdgeQuery(), and denoptim.graph.EdgeQuery.getTargetVertexId().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/EdgeQuery.java