DENOPTIM: denoptim.gui.GUIInspectFSERun Class Reference
denoptim.gui.GUIInspectFSERun Class Reference
A panel that allows to inspect the output of an combinatorial experiment exploring a fragment space.
Public Member Functions
GUIInspectFSERun (GUIMainPanel mainPanel)
Constructor.
void importFSERunData (File folder)
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Static Public Attributes
static AtomicInteger fseInspectorTabUID = new AtomicInteger(1)
Unique identified for instances of this handler.
Private Member Functions
void initialize ()
Initialize the panel and add buttons.
void resetView ()
void resetViewInPlotByLevel ()
void resetViewInPlotOfSortedList ()
CandidateLW choseAmongPossiblyOverlapping (JComponent parent, List< CandidateLW > overlappingItems)
void renderViewWithSelectedItem (CandidateLW item)
void renderViewWithoutSelectedItems ()
Private Attributes
JPanel ctrlPanel
JPanel ctrlPanelLeft
JPanel ctrlPanelRight
JSplitPane centralPanel
JPanel rightPanel
MoleculeViewPanel molViewer
JPanel chartHolderPanel
JComboBox< String > cmbPlotType
ArrayList< CandidateLW > allItems
int itemsWithFitness = 0
int minLevel = 1
int maxLevel = -1
JLabel lblTotItems
Map< Integer, CandidateLW > mapItemsInByLevel
ArrayList< CandidateLW > sorted
DefaultXYDataset datasetAllFit
DefaultXYDataset datasetSorted
DefaultXYDataset datasetSelectedLev = new DefaultXYDataset()
DefaultXYDataset datasetSelectedOrd = new DefaultXYDataset()
JFreeChart chartByLevel
JFreeChart chartBySorted
ChartPanel chartPanelByLevel
ChartPanel chartPanelSorted
JButton openGraph
Button offering the possibility to load the graph inspector for a selected item.
String pathToSelectedItem
Storage of pathname to the item selected in the chart.
Static Private Attributes
static final long serialVersionUID = 2245706077350445364L
Version UID.
Additional Inherited Members
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Detailed Description
A panel that allows to inspect the output of an combinatorial experiment exploring a fragment space.
Author
Marco Foscato
Definition at line 91 of file GUIInspectFSERun.java.
Constructor & Destructor Documentation
GUIInspectFSERun()
denoptim.gui.GUIInspectFSERun.GUIInspectFSERun (GUIMainPanel mainPanel)
Constructor.
Definition at line 156 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.fseInspectorTabUID, denoptim.gui.GUIInspectFSERun.initialize(), and denoptim.gui.GUICardPanel.mainPanel.
Member Function Documentation
choseAmongPossiblyOverlapping()
CandidateLW denoptim.gui.GUIInspectFSERun.choseAmongPossiblyOverlapping (JComponent parent, List< CandidateLW > overlappingItems) private
Definition at line 758 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
importFSERunData()
void denoptim.gui.GUIInspectFSERun.importFSERunData (File folder)
Definition at line 338 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.allItems, denoptim.gui.GUIInspectFSERun.chartByLevel, denoptim.gui.GUIInspectFSERun.chartBySorted, denoptim.gui.GUIInspectFSERun.chartHolderPanel, denoptim.gui.GUIInspectFSERun.chartPanelByLevel, denoptim.gui.GUIInspectFSERun.chartPanelSorted, denoptim.gui.GUIPreferences.chartPointSize, denoptim.gui.GUIInspectFSERun.choseAmongPossiblyOverlapping(), denoptim.gui.GUIInspectFSERun.datasetAllFit, denoptim.gui.GUIInspectFSERun.datasetSorted, denoptim.constants.DENOPTIMConstants.FITFILENAMEEXTOUT, denoptim.constants.DENOPTIMConstants.FITFILENAMEPREFIX, denoptim.graph.CandidateLW.getFitness(), denoptim.graph.CandidateLW.getLevel(), denoptim.graph.CandidateLW.hasFitness(), denoptim.gui.GUIInspectFSERun.itemsWithFitness, denoptim.gui.GUIInspectFSERun.lblTotItems, denoptim.gui.GUICardPanel.mainPanel, denoptim.gui.GUIInspectFSERun.mapItemsInByLevel, denoptim.gui.GUIInspectFSERun.maxLevel, denoptim.gui.GUIInspectFSERun.minLevel, denoptim.io.DenoptimIO.readLightWeightCandidate(), denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems(), denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem(), denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel(), denoptim.gui.GUIInspectFSERun.resetViewInPlotOfSortedList(), denoptim.gui.GUIInspectFSERun.rightPanel, and denoptim.gui.GUIInspectFSERun.sorted.
Referenced by denoptim.gui.HomePanel.initialize(), and denoptim.gui.MainToolBar.openFile().
initialize()
void denoptim.gui.GUIInspectFSERun.initialize () private
Initialize the panel and add buttons.
Definition at line 169 of file GUIInspectFSERun.java.
References denoptim.gui.ButtonsBar.add(), denoptim.gui.GUIMainPanel.add(), denoptim.gui.GUIInspectFSERun.centralPanel, denoptim.gui.GUIInspectFSERun.chartHolderPanel, denoptim.gui.GUIInspectFSERun.cmbPlotType, denoptim.gui.GUIInspectFSERun.ctrlPanel, denoptim.gui.GUIInspectFSERun.ctrlPanelLeft, denoptim.gui.GUIInspectFSERun.ctrlPanelRight, denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.gui.GUIInspectFSERun.lblTotItems, denoptim.gui.GUICardPanel.mainPanel, denoptim.gui.GUIInspectFSERun.molViewer, denoptim.gui.GUIInspectFSERun.openGraph, denoptim.gui.GUIInspectFSERun.pathToSelectedItem, denoptim.gui.GUIInspectFSERun.resetView(), and denoptim.gui.GUIInspectFSERun.rightPanel.
Referenced by denoptim.gui.GUIInspectFSERun.GUIInspectFSERun().
renderViewWithoutSelectedItems()
void denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems () private
Definition at line 823 of file GUIInspectFSERun.java.
References denoptim.gui.MoleculeViewPanel.clearAll(), denoptim.gui.GUIInspectFSERun.datasetSelectedLev, denoptim.gui.GUIInspectFSERun.datasetSelectedOrd, denoptim.gui.GUIInspectFSERun.molViewer, and denoptim.gui.GUIInspectFSERun.openGraph.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
renderViewWithSelectedItem()
void denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem (CandidateLW item) private
Definition at line 795 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.chartByLevel, denoptim.gui.GUIInspectFSERun.chartBySorted, denoptim.gui.GUIInspectFSERun.datasetSelectedLev, denoptim.gui.GUIInspectFSERun.datasetSelectedOrd, denoptim.graph.CandidateLW.getFitness(), denoptim.graph.CandidateLW.getLevel(), denoptim.graph.CandidateLW.getPathToFile(), denoptim.gui.MoleculeViewPanel.loadChemicalStructureFromFile(), denoptim.gui.GUIInspectFSERun.molViewer, denoptim.gui.GUIInspectFSERun.openGraph, denoptim.gui.GUIInspectFSERun.pathToSelectedItem, and denoptim.gui.GUIInspectFSERun.sorted.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
resetView()
void denoptim.gui.GUIInspectFSERun.resetView () private
Definition at line 302 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.cmbPlotType, denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotOfSortedList().
Referenced by denoptim.gui.GUIInspectFSERun.initialize().
resetViewInPlotByLevel()
void denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel () private
Definition at line 316 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.chartByLevel, denoptim.gui.GUIInspectFSERun.maxLevel, and denoptim.gui.GUIInspectFSERun.minLevel.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.resetView().
resetViewInPlotOfSortedList()
void denoptim.gui.GUIInspectFSERun.resetViewInPlotOfSortedList () private
Definition at line 327 of file GUIInspectFSERun.java.
References denoptim.gui.GUIInspectFSERun.chartBySorted, and denoptim.gui.GUIInspectFSERun.itemsWithFitness.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.resetView().
Member Data Documentation
allItems
ArrayList<CandidateLW> denoptim.gui.GUIInspectFSERun.allItems private
Definition at line 113 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
centralPanel
JSplitPane denoptim.gui.GUIInspectFSERun.centralPanel private
Definition at line 106 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize().
chartByLevel
JFreeChart denoptim.gui.GUIInspectFSERun.chartByLevel private
Definition at line 133 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel().
chartBySorted
JFreeChart denoptim.gui.GUIInspectFSERun.chartBySorted private
Definition at line 134 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotOfSortedList().
chartHolderPanel
JPanel denoptim.gui.GUIInspectFSERun.chartHolderPanel private
Definition at line 109 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.initialize().
chartPanelByLevel
ChartPanel denoptim.gui.GUIInspectFSERun.chartPanelByLevel private
Definition at line 135 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
chartPanelSorted
ChartPanel denoptim.gui.GUIInspectFSERun.chartPanelSorted private
Definition at line 136 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
cmbPlotType
JComboBox<String> denoptim.gui.GUIInspectFSERun.cmbPlotType private
Definition at line 111 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize(), and denoptim.gui.GUIInspectFSERun.resetView().
ctrlPanel
JPanel denoptim.gui.GUIInspectFSERun.ctrlPanel private
Definition at line 103 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize().
ctrlPanelLeft
JPanel denoptim.gui.GUIInspectFSERun.ctrlPanelLeft private
Definition at line 104 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize().
ctrlPanelRight
JPanel denoptim.gui.GUIInspectFSERun.ctrlPanelRight private
Definition at line 105 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize().
datasetAllFit
DefaultXYDataset denoptim.gui.GUIInspectFSERun.datasetAllFit private
Definition at line 128 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
datasetSelectedLev
DefaultXYDataset denoptim.gui.GUIInspectFSERun.datasetSelectedLev = new DefaultXYDataset() private
Definition at line 130 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
datasetSelectedOrd
DefaultXYDataset denoptim.gui.GUIInspectFSERun.datasetSelectedOrd = new DefaultXYDataset() private
Definition at line 131 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
datasetSorted
DefaultXYDataset denoptim.gui.GUIInspectFSERun.datasetSorted private
Definition at line 129 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
fseInspectorTabUID
AtomicInteger denoptim.gui.GUIInspectFSERun.fseInspectorTabUID = new AtomicInteger(1) static
Unique identified for instances of this handler.
Definition at line 101 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.GUIInspectFSERun().
itemsWithFitness
int denoptim.gui.GUIInspectFSERun.itemsWithFitness = 0 private
Definition at line 114 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotOfSortedList().
lblTotItems
JLabel denoptim.gui.GUIInspectFSERun.lblTotItems private
Definition at line 117 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.initialize().
mapItemsInByLevel
Map<Integer,CandidateLW> denoptim.gui.GUIInspectFSERun.mapItemsInByLevel private
Definition at line 119 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData().
maxLevel
int denoptim.gui.GUIInspectFSERun.maxLevel = -1 private
Definition at line 116 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel().
minLevel
int denoptim.gui.GUIInspectFSERun.minLevel = 1 private
Definition at line 115 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.resetViewInPlotByLevel().
molViewer
MoleculeViewPanel denoptim.gui.GUIInspectFSERun.molViewer private
Definition at line 108 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize(), denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
openGraph
JButton denoptim.gui.GUIInspectFSERun.openGraph private
Button offering the possibility to load the graph inspector for a selected item.
Definition at line 142 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize(), denoptim.gui.GUIInspectFSERun.renderViewWithoutSelectedItems(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
pathToSelectedItem
String denoptim.gui.GUIInspectFSERun.pathToSelectedItem private
Storage of pathname to the item selected in the chart.
This is used to enable loading the graph inspector at any time after selection of the item in the chart.
Definition at line 149 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.initialize(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
rightPanel
JPanel denoptim.gui.GUIInspectFSERun.rightPanel private
Definition at line 107 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.initialize().
serialVersionUID
final long denoptim.gui.GUIInspectFSERun.serialVersionUID = 2245706077350445364L static private
Version UID.
Definition at line 96 of file GUIInspectFSERun.java.
sorted
ArrayList<CandidateLW> denoptim.gui.GUIInspectFSERun.sorted private
Definition at line 120 of file GUIInspectFSERun.java.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), and denoptim.gui.GUIInspectFSERun.renderViewWithSelectedItem().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUIInspectFSERun.java