DENOPTIM: denoptim.io.DenoptimIO Class Reference
denoptim.io.DenoptimIO Class Reference
Utility methods for input/output.
Classes
class PartlySilencedChemObjReaderErrorHandler
This differs from DefaultChemObjectReaderErrorHandler just by ignoring messages about invalid symbol.
Static Public Member Functions
static Object readDENOPTIMData (String pathname) throws Exception
Reads any content of a given pathname and tries to read DENOPTIM data from it.
static List< Candidate > readGenerationFromSummary (File file) throws DENOPTIMException
Reads a FileFormat#GENSUMMARY file and searches all the files defining each member of the population.
static List< IAtomContainer > readAllAtomContainers (File file) throws IOException, CDKException
Returns a single collection with all atom containers found in a file of any format.
static ArrayList< IAtomContainer > readSDFFile (String fileName) throws DENOPTIMException
Reads a file containing multiple molecules (multiple SD format))
static File writeVertexesToFile (File file, FileFormat format, List< Vertex > vertexes) throws DENOPTIMException
Writes vertexes to file.
static File writeVertexToFile (File file, FileFormat format, Vertex vertex, boolean append) throws DENOPTIMException
Writes vertexes to file.
static File writeVertexesToFile (File file, FileFormat format, List< Vertex > vertexes, boolean append) throws DENOPTIMException
Writes vertexes to file.
static void writeVertexesToJSON (File file, List< Vertex > vertexes) throws DENOPTIMException
Writes vertexes to JSON file.
static void writeVertexesToJSON (File file, List< Vertex > vertexes, boolean append) throws DENOPTIMException
Writes vertexes to JSON file.
static void writeVertexToSDF (String pathName, Vertex vertex) throws DENOPTIMException
Writes a vertex to an SDF file.
static void writeVertexesToSDF (File file, List< Vertex > vertexes, boolean append) throws DENOPTIMException
Write a list of vertexes to file.
static void writeSDFFile (String fileName, IAtomContainer mol) throws DENOPTIMException
Writes IAtomContainer to SDF file.
static void writeSDFFile (String fileName, List< IAtomContainer > mols) throws DENOPTIMException
Writes IAtomContainers to SDF file.
static void writeSDFFile (String fileName, List< IAtomContainer > mols, boolean append) throws DENOPTIMException
Writes a set of IAtomContainers to SDF file.
static void writeSDFFile (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException
Writes an IAtomContainer to SDF file.
static void writeMol2File (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException
static void writeXYZFile (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException
static void writeSmilesSet (String fileName, String[] smiles, boolean append) throws DENOPTIMException
Writes multiple smiles string array to the specified file.
static void writeSmiles (String fileName, String smiles, boolean append) throws DENOPTIMException
Writes a single smiles string to the specified file.
static void writeData (String fileName, String data, boolean append) throws DENOPTIMException
Write text-like data file.
static List< CandidateLW > readLightWeightCandidate (File file) throws DENOPTIMException
Read only selected data from a GA produced items.
static double[] readPopulationProps (File file) throws DENOPTIMException
Read the min, max, mean, and median of a population from FileFormat#GENSUMMARY file.
static List< String > readPopulationMemberPathnames (File file) throws DENOPTIMException
Read the pathnames to the population members from a FileFormat#GENSUMMARY file.
static List< CandidateLW > readPopulationMembersTraces (File file) throws DENOPTIMException
Read the minimal info that can be found in a FileFormat#GENSUMMARY file about the members of a population.
static ArrayList< String > readList (String fileName) throws DENOPTIMException
Read list of data as text.
static ArrayList< String > readList (String fileName, boolean allowEmpty) throws DENOPTIMException
Read list of data as text.
static String readText (String fileName) throws DENOPTIMException
Read text from file.
static List< Map< String, Object > > readSDFProperties (String pathName, List< String > propNames) throws DENOPTIMException
Extract selected properties from SDF files.
static String getChemDoodleString (IAtomContainer mol) throws DENOPTIMException
Generate the ChemDoodle representation of the molecule.
static Set< APClass > readAllAPClasses (File fragLib)
static void writeCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > ends) throws DENOPTIMException
The class compatibility matrix.
static void readCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > compatMap, HashMap< APClass, APClass > cappingMap, Set< APClass > forbiddenEndList) throws DENOPTIMException
Read the APclass compatibility matrix data from file.
static void readRCCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > rcCompatMap) throws DENOPTIMException
Reads the APclass compatibility matrix for ring-closing connections (the RC-CPMap).
static ArrayList< Candidate > readCandidates (File file) throws DENOPTIMException
Reads SDF files that represent one or more tested candidates.
static ArrayList< Candidate > readCandidates (File file, boolean allowNoUID) throws DENOPTIMException
Reads SDF files that represent one or more tested or to be tested candidates.
static void writeCandidatesToFile (File file, List< Candidate > popMembers, boolean append) throws DENOPTIMException
Writes candidate items to file.
static void writeCandidateToFile (File file, Candidate candidate, boolean append) throws DENOPTIMException
Writes one candidate item to file.
static ArrayList< GraphEdit > readDENOPTIMGraphEditFromFile (String fileName) throws DENOPTIMException
Reads a list of graph editing tasks from a JSON file.
static ArrayList< DGraph > readDENOPTIMGraphsFromFile (File inFile) throws Exception
Reads a list of DGraphs from file.
static ArrayList< DGraph > readDENOPTIMGraphsFromFile (File inFile, FileFormat format) throws Exception
Reads a list of DGraphs from file.
static ArrayList< DGraph > readDENOPTIMGraphsFromSDFile (String fileName) throws DENOPTIMException
Reads a list of <DGraphs from a SDF file.
static DGraph readGraphFromSDFileIAC (IAtomContainer mol) throws DENOPTIMException
Converts an atom container read in from an SDF file into a graph, if possible.
static DGraph readGraphFromSDFileIAC (IAtomContainer mol, int molId) throws DENOPTIMException
Converts an atom container read in from an SDF file into a graph, if possible.
static DGraph readGraphFromSDFileIAC (IAtomContainer mol, int molId, String fileName) throws DENOPTIMException
Converts an atom container read in from an SDF file into a graph, if possible.
static ArrayList< DGraph > readDENOPTIMGraphsFromTxtFile (String fileName, FragmentSpace fragSpace, Logger logger) throws DENOPTIMException
Reads a list of <DGraphs from a text file.
static ArrayList< Vertex > readDENOPTIMVertexesFromJSONFile (String fileName) throws DENOPTIMException
Reads a list of Vertexes from a JSON file.
static ArrayList< DGraph > readDENOPTIMGraphsFromJSONFile (String fileName) throws DENOPTIMException
Reads a list of DGraphs from a JSON file.
static File writeGraphToFile (File file, FileFormat format, DGraph graph, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the a graph to file.
static File writeGraphsToFile (File file, FileFormat format, List< DGraph > modGraphs, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graphs to file.
static void writeGraphsToSDF (File file, List< DGraph > graphs, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graphs to SDF file.
static void writeGraphToSDF (File file, DGraph graph, boolean append, boolean make3D, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graph to SDF file.
static void writeGraphToSDF (File file, DGraph graph, boolean append, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graph to SDF file.
static void writeGraphsToSDF (File file, List< DGraph > graphs, boolean append, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graphs to SDF file.
static void writeGraphsToSDF (File file, List< DGraph > modGraphs, boolean append, boolean make3D, Logger logger, Randomizer randomizer) throws DENOPTIMException
Writes the graphs to SDF file.
static void writeGraphToJSON (File file, DGraph graph) throws DENOPTIMException
Writes the graph to JSON file.
static void writeGraphsToJSON (File file, List< DGraph > graphs) throws DENOPTIMException
Writes the graphs to JSON file.
static void writeGraphsToJSON (File file, List< DGraph > graphs, boolean append) throws DENOPTIMException
Writes the graphs to JSON file.
static void writeGraphToFile (String fileName, DGraph graph, boolean append) throws DENOPTIMException
Writes the string representation of a graph to file.
static Map< File, FileFormat > readRecentFilesMap ()
Reads the file defined in DENOPTIMConstants#RECENTFILESLIST and makes a map that contains the pathname and the format of each recent file.
static ArrayList< Vertex > readVertexes (File file, Vertex.BBType bbt) throws UndetectedFileFormatException, IOException, IllegalArgumentException, DENOPTIMException
Reads Vertexes from any file that can contain such items.
static ArrayList< Vertex > readDENOPTIMVertexesFromSDFile (String fileName, Vertex.BBType bbt) throws DENOPTIMException
Reads a list of Vertexes from a SDF file.
static LinkedHashMap< String, String > readCSDFormulae (File file) throws DENOPTIMException
Read molecular formula from TXT data representation produced by Cambridge Structural Database tools (such as Conquest).
static void readCuttingRules (BufferedReader reader, List< CuttingRule > cutRules, String source) throws DENOPTIMException
Read cutting rules from a stream.
static void readCuttingRules (File file, List< CuttingRule > cutRules) throws DENOPTIMException
Read cutting rules from a properly formatted text file.
static void readCuttingRules (ArrayList< String > cutRulLines, List< CuttingRule > cutRules, String source) throws DENOPTIMException
Read cutting rules from a properly formatted text file.
static void writeCuttingRules (File file, List< CuttingRule > cutRules) throws DENOPTIMException
Writes a formatted text file that collects cutting rule.
static void appendTxtFiles (File f1, List< File > files) throws IOException
Appends the second file to the first.
static List< BridgeHeadFindingRule > readBridgeHesFindingRules (String fileName) throws DENOPTIMException
Reads a list of rules for identifying potential bridge-head sites.
static List< BridgeHeadFindingRule > readBridgeHesFindingRules (BufferedReader br) throws IOException
Reads a list of rules for identifying potential bridge-head sites.
static void scanLoggingLevels (Logger logger)
Utility to trigger logging at all known levels.
Static Public Attributes
static final String FS = System.getProperty("file.separator")
File separator from system.
static final String NL = System.getProperty("line.separator")
Newline character from system.
Static Private Attributes
static final IChemObjectBuilder builder
Detailed Description
Utility methods for input/output.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 117 of file DenoptimIO.java.
Member Function Documentation
appendTxtFiles()
static void denoptim.io.DenoptimIO.appendTxtFiles (File f1, List< File > files) throws IOException static
Appends the second file to the first.
Parameters
f1 file being elongated
list files providing the content to place in f1.
Exceptions
IOException
Definition at line 2650 of file DenoptimIO.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations().
getChemDoodleString()
static String denoptim.io.DenoptimIO.getChemDoodleString (IAtomContainer mol) throws DENOPTIMException static
Generate the ChemDoodle representation of the molecule.
Parameters
mol
Returns
molecule as a formatted string
Exceptions
DENOPTIMException
Definition at line 1163 of file DenoptimIO.java.
readAllAPClasses()
static Set< APClass > denoptim.io.DenoptimIO.readAllAPClasses (File fragLib) static
Definition at line 1200 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readVertexes(), and denoptim.graph.Vertex.BBType.UNDEFINED.
Referenced by denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromCappingGroupLibs(), denoptim.gui.CompatibilityMatrixForm.importAllAPClassesFromFragmentLibs(), and denoptim.io.DenoptimIOTest.testReadAllAPClasses().
readAllAtomContainers()
static List< IAtomContainer > denoptim.io.DenoptimIO.readAllAtomContainers (File file) throws IOException, CDKException static
Returns a single collection with all atom containers found in a file of any format.
CIF files are internally converted to SDF files, causing loss of information beyond molecular structure in Cartesian coordinates. So, if you need more than molecular structure from CIF files, do not use this method.
Parameters
file the file to read.
Returns
the list of containers found in the file.
Exceptions
IOException if the file is not found or not readable.
CDKException if the reading of the file goes wrong.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 287 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.FS, denoptim.files.FileUtils.getTempFolder(), and denoptim.io.DenoptimIO.readAllAtomContainers().
Referenced by denoptim.gui.MoleculeViewPanel.fillDataTable(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.gui.GUIVertexInspector.importStructureFromFile(), denoptim.io.IteratingAtomContainerReader.IteratingAtomContainerReader(), denoptim.gui.MoleculeViewPanel.loadChemicalStructureFromFile(), denoptim.fitness.FitnessExpressionParser.makeIBitFingerprint(), denoptim.programs.mol2graph.Mol2GraphParameters.processParameters(), denoptim.io.DenoptimIO.readAllAtomContainers(), denoptim.task.FitnessTask.runExternalFitness(), denoptim.gui.MoleculeViewPanel.showPopup(), and denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF().
readBridgeHesFindingRules() [1/2]
static List< BridgeHeadFindingRule > denoptim.io.DenoptimIO.readBridgeHesFindingRules (BufferedReader br) throws IOException static
Reads a list of rules for identifying potential bridge-head sites.
Parameters
reader the source of data.
Returns
the list of rules found in the reader.
Exceptions
IOException
DENOPTIMException in case we cannot read, find, or understand the data.
Definition at line 2735 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getReader().
readBridgeHesFindingRules() [2/2]
static List< BridgeHeadFindingRule > denoptim.io.DenoptimIO.readBridgeHesFindingRules (String fileName) throws DENOPTIMException static
Reads a list of rules for identifying potential bridge-head sites.
Parameters
fileName the pathname of the file to read
Returns
the list of rules found in the file.
Exceptions
DENOPTIMException in case we cannot read, find, or understand the data.
Definition at line 2694 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readBridgeHesFindingRules().
Referenced by denoptim.graph.rings.RingClosureParameters.interpretKeyword(), denoptim.io.DenoptimIO.readBridgeHesFindingRules(), and denoptim.graph.rings.RingClosureParameters.RingClosureParameters().
readCandidates() [1/2]
static ArrayList< Candidate > denoptim.io.DenoptimIO.readCandidates (File file) throws DENOPTIMException static
Reads SDF files that represent one or more tested candidates.
Candidates are provided with a graph representation, a unique identifier, and either a fitness value or a mol_error defining why this candidate could not be evaluated.
Parameters
file the SDF file to read.
Returns
the list of candidates.
Exceptions
DENOPTIMException is something goes wrong while reading the file or interpreting its content
Definition at line 1464 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readCandidates().
Referenced by denoptim.ga.EAUtils.getPopulationFromFile(), denoptim.gui.MoleculeViewPanel.loadChemicalStructureFromFile(), denoptim.io.DenoptimIO.readCandidates(), denoptim.io.DenoptimIO.readDENOPTIMData(), denoptim.io.DenoptimIO.readGenerationFromSummary(), and denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram().
readCandidates() [2/2]
static ArrayList< Candidate > denoptim.io.DenoptimIO.readCandidates (File file, boolean allowNoUID) throws DENOPTIMException static
Reads SDF files that represent one or more tested or to be tested candidates.
Parameters
file the SDF file to read.
allowNoUID use true if candidates should be allowed to have no unique identifier.
Returns
the list of candidates.
Exceptions
DENOPTIMException is something goes wrong while reading the file or interpreting its content
Definition at line 1483 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.GAGENDIRNAMEROOT, denoptim.io.DenoptimIO.readSDFFile(), denoptim.graph.Candidate.setGeneration(), and denoptim.graph.Candidate.setSDFFile().
readCompatibilityMatrix()
static void denoptim.io.DenoptimIO.readCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > compatMap, HashMap< APClass, APClass > cappingMap, Set< APClass > forbiddenEndList) throws DENOPTIMException static
Read the APclass compatibility matrix data from file.
Parameters
fileName the file to be read
compatMap container for the APClass compatibility rules
cappingMap container for the capping rules
forbiddenEndList container for the definition of forbidden ends
Exceptions
DENOPTIMException
Definition at line 1291 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.APCMAPCAPPING, denoptim.constants.DENOPTIMConstants.APCMAPCOMPRULE, denoptim.constants.DENOPTIMConstants.APCMAPFORBIDDENEND, denoptim.constants.DENOPTIMConstants.APCMAPIGNORE, and denoptim.graph.APClass.make().
Referenced by denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.fragspace.FragmentSpace.importCompatibilityMatrixFromFile(), and denoptim.gui.CompatibilityMatrixForm.importCPMapFromFile().
readCSDFormulae()
static LinkedHashMap< String, String > denoptim.io.DenoptimIO.readCSDFormulae (File file) throws DENOPTIMException static
Read molecular formula from TXT data representation produced by Cambridge Structural Database tools (such as Conquest).
Essentially, this method reads a text file expecting to find lines as the following among lines with other kinds of information:
REFCODE: ABEWOT
[...]
Formula:           C36 H44 Cl1 P2 Ru1 1+,F6 P1 1-
Parameters
file the text file to read
Returns
the mapping of CSD's REFCODE as key to their respective molecular formula as formatted in the input.
Exceptions
DENOPTIMException if any exception occurs during the reading of the file or if the file does not exist.
Definition at line 2427 of file DenoptimIO.java.
Referenced by denoptim.programs.fragmenter.FragmenterParameters.processParameters(), and denoptim.io.DenoptimIOTest.testReadCSDFormulae().
readCuttingRules() [1/3]
static void denoptim.io.DenoptimIO.readCuttingRules (ArrayList< String > cutRulLines, List< CuttingRule > cutRules, String source) throws DENOPTIMException static
Read cutting rules from a properly formatted text file.
Parameters
cutRulLines text lines containing cutting rules. These are expected to be lines starting with the DENOPTIMConstants.CUTRULKEYWORD keyword.
cutRules the collector of the cutting rules. The collection is already sorted by priority when this method returns.
source the source of text. This is used only in logging as the source of the text that we are trying to convert into cutting rules. For example, a file name.
Exceptions
DENOPTIMException in case there are errors in the formatting of the text contained in the file.
Definition at line 2554 of file DenoptimIO.java.
References denoptim.programs.fragmenter.CuttingRule.getPriority().
readCuttingRules() [2/3]
static void denoptim.io.DenoptimIO.readCuttingRules (BufferedReader reader, List< CuttingRule > cutRules, String source) throws DENOPTIMException static
Read cutting rules from a stream.
Parameters
reader the stream providing text lines.
cutRules the collector of the cutting rules. The collection is already sorted by priority when this method returns.
source the source of text. This is used only in logging as the source of the text that we are trying to convert into cutting rules. For example, a file name.
Exceptions
DENOPTIMException in case there are errors in the formatting of the text contained in the file.
Definition at line 2485 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.CUTRULKEYWORD, and denoptim.io.DenoptimIO.readCuttingRules().
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), denoptim.gui.GUIVertexInspector.dialogToDefineCuttingRules(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), denoptim.programs.mol2graph.Mol2GraphParameters.processParameters(), denoptim.io.DenoptimIO.readCuttingRules(), denoptim.io.DenoptimIOTest.testIOCuttingRules(), and denoptim.io.DenoptimIOTest.testReadCuttingRulsedDefault().
readCuttingRules() [3/3]
static void denoptim.io.DenoptimIO.readCuttingRules (File file, List< CuttingRule > cutRules) throws DENOPTIMException static
Read cutting rules from a properly formatted text file.
Parameters
file the file to read.
cutRules the collector of the cutting rules. The collection is already sorted by priority when this method returns.
Exceptions
DENOPTIMException in case there are errors in the formatting of the text contained in the file.
Definition at line 2523 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.CUTRULKEYWORD, denoptim.io.DenoptimIO.readCuttingRules(), and denoptim.io.DenoptimIO.readList().
readDENOPTIMData()
static Object denoptim.io.DenoptimIO.readDENOPTIMData (String pathname) throws Exception static
Reads any content of a given pathname and tries to read DENOPTIM data from it.
As the type of the returned value if not defined this method is meant of untyped coding context, like the interfacing with Python. Please, avoid to use it in typed code context, like within JAVA code.
Parameters
pathname the pathname to read.
Returns
any DENOPTIM-like data that could be found in the given pathname.
Exceptions
Exception if for any reason no data can be returned.
Definition at line 144 of file DenoptimIO.java.
References denoptim.files.FileUtils.detectFileFormat(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.io.DenoptimIO.readCandidates(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.io.DenoptimIO.readGenerationFromSummary(), denoptim.io.DenoptimIO.readVertexes(), and denoptim.files.FileFormat.UNRECOGNIZED.
Referenced by denoptim.integration.python.Py4JGetawayServer.loadData().
readDENOPTIMGraphEditFromFile()
static ArrayList< GraphEdit > denoptim.io.DenoptimIO.readDENOPTIMGraphEditFromFile (String fileName) throws DENOPTIMException static
Reads a list of graph editing tasks from a JSON file.
Parameters
fileName the pathname of the file to read
Returns
the list of editing tasks
Exceptions
DENOPTIMException
Definition at line 1567 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.programs.grapheditor.GraphEdParameters.processParameters().
readDENOPTIMGraphsFromFile() [1/2]
static ArrayList< DGraph > denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile (File inFile) throws Exception static
Reads a list of DGraphs from file.
Parameters
fileName the pathname of the file to read
Returns
the list of graphs
Exceptions
Exception
Definition at line 1637 of file DenoptimIO.java.
References denoptim.files.FileUtils.detectFileFormat(), and denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile().
Referenced by denoptim.programs.combinatorial.CEBLParameters.processParameters(), denoptim.programs.graphlisthandler.GraphListsHandlerParameters.processParameters(), denoptim.ga.EAUtils.readCandidateFromFile(), denoptim.io.DenoptimIO.readDENOPTIMData(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.gui.GUIGraphHandler.readGraphsFromFile(), denoptim.programs.grapheditor.GraphEdParameters.readInputGraphs(), denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.programs.genetweeker.GeneOpsRunner.runMutation(), denoptim.programs.isomorphism.Isomorphism.runProgram(), and denoptim.programs.genetweeker.GeneOpsRunner.runXOver().
readDENOPTIMGraphsFromFile() [2/2]
static ArrayList< DGraph > denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile (File inFile, FileFormat format) throws Exception static
Reads a list of DGraphs from file.
Parameters
inFile the file to read
format the format of the file to read. We assume this has been detected from previous calls of FileUtils#detectFileFormat(File) and that now we want to avoid having to call that method again.
Returns
the list of graphs
Exceptions
Exception
Definition at line 1657 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.GRAPHTAG, denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile(), denoptim.io.DenoptimIO.readVertexes(), denoptim.graph.Vertex.BBType.UNDEFINED, and denoptim.files.FileFormat.VRTXSDF.
readDENOPTIMGraphsFromJSONFile()
static ArrayList< DGraph > denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile (String fileName) throws DENOPTIMException static
Reads a list of DGraphs from a JSON file.
Parameters
fileName the pathname of the file to read
Returns
the list of graphs
Exceptions
DENOPTIMException
Definition at line 1961 of file DenoptimIO.java.
References denoptim.graph.DGraph.fromJson(), and denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.combinatorial.CombinatorialExplorerByLayer.exploreCombinationsAtGivenLevel(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.gui.GUIGraphHandler.readGraphsFromFile(), denoptim.io.DenoptimIO.readVertexes(), and denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs().
readDENOPTIMGraphsFromSDFile()
static ArrayList< DGraph > denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile (String fileName) throws DENOPTIMException static
Reads a list of <DGraphs from a SDF file.
Parameters
fileName the pathname of the file to read.
Returns
the list of graphs
Exceptions
DENOPTIMException
Definition at line 1712 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readGraphFromSDFileIAC(), and denoptim.io.DenoptimIO.readSDFFile().
Referenced by denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.gui.GUIGraphHandler.readGraphsFromFile(), and denoptim.io.DenoptimIO.readVertexes().
readDENOPTIMGraphsFromTxtFile()
static ArrayList< DGraph > denoptim.io.DenoptimIO.readDENOPTIMGraphsFromTxtFile (String fileName, FragmentSpace fragSpace, Logger logger) throws DENOPTIMException static
Reads a list of <DGraphs from a text file.
Parameters
fileName the pathname of the file to read.
Returns
the list of graphs.
Exceptions
DENOPTIMException
Definition at line 1838 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.APCMAPIGNORE, and denoptim.utils.GraphConversionTool.getGraphFromString().
readDENOPTIMVertexesFromJSONFile()
static ArrayList< Vertex > denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile (String fileName) throws DENOPTIMException static
Reads a list of Vertexes from a JSON file.
Parameters
fileName the pathname of the file to read.
Returns
the list of vertexes.
Exceptions
DENOPTIMException
Definition at line 1895 of file DenoptimIO.java.
References denoptim.graph.Vertex.fromJson(), and denoptim.json.DENOPTIMgson.getReader().
Referenced by denoptim.io.DenoptimIO.readVertexes(), denoptim.io.DenoptimIOTest.testAppendToJSON(), and denoptim.io.DenoptimIO.writeVertexesToJSON().
readDENOPTIMVertexesFromSDFile()
static ArrayList< Vertex > denoptim.io.DenoptimIO.readDENOPTIMVertexesFromSDFile (String fileName, Vertex.BBType bbt) throws DENOPTIMException static
Reads a list of Vertexes from a SDF file.
Parameters
fileName the pathname of the file to read.
Returns
the list of vertexes.
Exceptions
DENOPTIMException
Definition at line 2386 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getReader(), denoptim.graph.Vertex.parseVertexFromSDFFormat(), and denoptim.io.DenoptimIO.readSDFFile().
Referenced by denoptim.io.DenoptimIO.readVertexes().
readGenerationFromSummary()
static List< Candidate > denoptim.io.DenoptimIO.readGenerationFromSummary (File file) throws DENOPTIMException static
Reads a FileFormat#GENSUMMARY file and searches all the files defining each member of the population.
If the pathnames found in FileFormat#GENSUMMARY do not exist, this method will try to build the candidate's files pathnames relative to the location of the FileFormat#GENSUMMARY. This assumes that the original folder structure of a FileFormat#GA_RUN has been preserved.
Parameters
file the generation summary file (FileFormat#GENSUMMARY) to read
Returns
population members
Exceptions
DENOPTIMException
Definition at line 242 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readCandidates(), and denoptim.io.DenoptimIO.readPopulationMemberPathnames().
Referenced by denoptim.io.DenoptimIO.readDENOPTIMData(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
readGraphFromSDFileIAC() [1/3]
static DGraph denoptim.io.DenoptimIO.readGraphFromSDFileIAC (IAtomContainer mol) throws DENOPTIMException static
Converts an atom container read in from an SDF file into a graph, if possible.
Otherwise, throws an exception.
Parameters
mol the atom container coming from SDF representation
molId identified used only for logging purposed
Returns
the corresponding graph or null.
Exceptions
DENOPTIMException is the atom container cannot be converted due to lack of the proper SDF tags, or failure in the conversion.
Definition at line 1738 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readGraphFromSDFileIAC().
Referenced by denoptim.graph.Candidate.Candidate(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile(), and denoptim.io.DenoptimIO.readGraphFromSDFileIAC().
readGraphFromSDFileIAC() [2/3]
static DGraph denoptim.io.DenoptimIO.readGraphFromSDFileIAC (IAtomContainer mol, int molId) throws DENOPTIMException static
Converts an atom container read in from an SDF file into a graph, if possible.
Otherwise, throws an exception.
Parameters
mol the atom container coming from SDF representation
molId identified used only for logging purposed
Returns
the corresponding graph or null.
Exceptions
DENOPTIMException is the atom container cannot be converted due to lack of the proper SDF tags, or failure in the conversion.
Definition at line 1755 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readGraphFromSDFileIAC().
readGraphFromSDFileIAC() [3/3]
static DGraph denoptim.io.DenoptimIO.readGraphFromSDFileIAC (IAtomContainer mol, int molId, String fileName) throws DENOPTIMException static
Converts an atom container read in from an SDF file into a graph, if possible.
Otherwise, throws an exception.
Parameters
mol the atom container coming from SDF representation
molId identified used only for logging purposes. If negative it is ignored.
fileName a pathname used only for logging errors. This is usually the pathname to the file from which we took the atom container. If empty it is ignored
Returns
the corresponding graph or null.
Exceptions
DENOPTIMException is the atom container cannot be converted due to lack of the proper SDF tags, or failure in the conversion.
Definition at line 1776 of file DenoptimIO.java.
References denoptim.graph.DGraph.fromJson(), denoptim.constants.DENOPTIMConstants.GRAPHJSONTAG, and denoptim.constants.DENOPTIMConstants.GRAPHTAG.
readLightWeightCandidate()
static List< CandidateLW > denoptim.io.DenoptimIO.readLightWeightCandidate (File file) throws DENOPTIMException static
Read only selected data from a GA produced items.
This is a light-weight reader of SDF files containing an item, which can be successfully or Unsuccessfully evaluated.
Parameters
fileName the pathname to SDF file
Returns
the light-weight item description.
Exceptions
DENOPTIMException
Definition at line 855 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.FITNESSTAG, denoptim.constants.DENOPTIMConstants.GRAPHLEVELTAG, denoptim.constants.DENOPTIMConstants.MOLERRORTAG, denoptim.constants.DENOPTIMConstants.PROVENANCE, denoptim.io.DenoptimIO.readSDFProperties(), denoptim.graph.CandidateLW.setError(), denoptim.graph.CandidateLW.setFitness(), denoptim.graph.CandidateLW.setGeneratingSource(), denoptim.graph.CandidateLW.setLevel(), and denoptim.constants.DENOPTIMConstants.UNIQUEIDTAG.
Referenced by denoptim.gui.GUIInspectFSERun.importFSERunData(), denoptim.gui.GUIInspectGARun.readOneGeneration(), and denoptim.io.DenoptimIOTest.testReadLightWeightCandidate().
readList() [1/2]
static ArrayList< String > denoptim.io.DenoptimIO.readList (String fileName) throws DENOPTIMException static
Read list of data as text.
Parameters
fileName the pathname to the file to read.
Returns
list of data
Exceptions
DENOPTIMException
Definition at line 1046 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readList().
Referenced by denoptim.gui.GUIInspectGARun.buildAndFillMonitorPlot(), denoptim.files.FileUtils.canWriteAndReadTo(), denoptim.integration.tinker.ConformationalSearchPSSROT.fixLongeLinesInXYZ(), denoptim.fitness.FitnessExpressionParser.makeStringArray(), denoptim.ga.ExternalCmdsListener.processExternalCmdFile(), denoptim.io.DenoptimIO.readCuttingRules(), denoptim.io.DenoptimIO.readList(), denoptim.io.DenoptimIO.readPopulationMemberPathnames(), denoptim.io.DenoptimIO.readPopulationMembersTraces(), denoptim.io.DenoptimIO.readPopulationProps(), denoptim.io.DenoptimIO.readRecentFilesMap(), denoptim.ga.EAUtils.readUID(), denoptim.utils.SizeControlledSetTest.test(), denoptim.programs.denovo.GAParametersTest.testLogging(), and denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads().
readList() [2/2]
static ArrayList< String > denoptim.io.DenoptimIO.readList (String fileName, boolean allowEmpty) throws DENOPTIMException static
Read list of data as text.
Parameters
fileName the pathname to the file to read.
allowEmpty if true the method is allowed to return an empty list if the file exists and is empty
Returns
list of data
Exceptions
DENOPTIMException
Definition at line 1062 of file DenoptimIO.java.
readPopulationMemberPathnames()
static List< String > denoptim.io.DenoptimIO.readPopulationMemberPathnames (File file) throws DENOPTIMException static
Read the pathnames to the population members from a FileFormat#GENSUMMARY file.
Parameters
fileName the pathname to the file to read.
Returns
list of data
Exceptions
DENOPTIMException
Definition at line 971 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.FS, and denoptim.io.DenoptimIO.readList().
Referenced by denoptim.io.DenoptimIO.readGenerationFromSummary(), and denoptim.gui.GUIInspectGARun.readOneGeneration().
readPopulationMembersTraces()
static List< CandidateLW > denoptim.io.DenoptimIO.readPopulationMembersTraces (File file) throws DENOPTIMException static
Read the minimal info that can be found in a FileFormat#GENSUMMARY file about the members of a population.
Parameters
fileName the pathname to the FileFormat#GENSUMMARY file to read.
Returns
list of population members defined to the extent that information is available in the FileFormat#GENSUMMARY file.
Exceptions
DENOPTIMException if the file cannot be read.
Definition at line 1004 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readList(), and denoptim.graph.CandidateLW.setFitness().
Referenced by denoptim.gui.GUIInspectGARun.readOneGeneration().
readPopulationProps()
static double[] denoptim.io.DenoptimIO.readPopulationProps (File file) throws DENOPTIMException static
Read the min, max, mean, and median of a population from FileFormat#GENSUMMARY file.
Parameters
fileName the pathname to the file to read.
Returns
list of data
Exceptions
DENOPTIMException
Definition at line 930 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readList().
Referenced by denoptim.gui.GUIInspectGARun.readOneGeneration().
readRCCompatibilityMatrix()
static void denoptim.io.DenoptimIO.readRCCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > rcCompatMap) throws DENOPTIMException static
Reads the APclass compatibility matrix for ring-closing connections (the RC-CPMap).
Note that RC-CPMap is by definition symmetric. Though, true entries can be defined either from X:Y or Y:X, and we make sure such entries are stored in the map. This method assumes that the APclasses reported in the RC-CPMap are defined, w.r.t bond order, in the regular compatibility matrix as we wont check it this condition is satisfied.
Parameters
fileName
rcCompatMap
Exceptions
DENOPTIMException
Definition at line 1385 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.APCMAPCOMPRULE, denoptim.constants.DENOPTIMConstants.APCMAPIGNORE, and denoptim.graph.APClass.make().
Referenced by denoptim.fragspace.FragmentSpace.FragmentSpace(), and denoptim.fragspace.FragmentSpace.importRCCompatibilityMatrixFromFile().
readRecentFilesMap()
static Map< File, FileFormat > denoptim.io.DenoptimIO.readRecentFilesMap () static
Reads the file defined in DENOPTIMConstants#RECENTFILESLIST and makes a map that contains the pathname and the format of each recent file.
Ignores any entry that is present in the file but cannot be found in the system.
Returns
the recent files map
Definition at line 2275 of file DenoptimIO.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.files.FileUtils.checkExists(), denoptim.io.DenoptimIO.readList(), and denoptim.constants.DENOPTIMConstants.RECENTFILESLIST.
Referenced by denoptim.files.FileUtils.addToRecentFiles(), and denoptim.gui.MainToolBar.updateOpenRecentMenu().
readSDFFile()
static ArrayList< IAtomContainer > denoptim.io.DenoptimIO.readSDFFile (String fileName) throws DENOPTIMException static
Reads a file containing multiple molecules (multiple SD format))
Parameters
fileName the file containing the molecules
Returns
IAtomContainer[] an array of molecules
Exceptions
DENOPTIMException
Definition at line 354 of file DenoptimIO.java.
Referenced by denoptim.gui.GUIGraphHandler.appendGraphsFromFile(), denoptim.gui.GUIGraphHandler.importGraphsFromFile(), denoptim.io.DenoptimIO.readCandidates(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromSDFile(), denoptim.io.DenoptimIO.readSDFProperties(), denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.graph.TemplateTest.testGetIAtomContainer(), denoptim.graph.TemplateTest.testGetIAtomContainer_DeepVertex(), and denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol().
readSDFProperties()
static List< Map< String, Object > > denoptim.io.DenoptimIO.readSDFProperties (String pathName, List< String > propNames) throws DENOPTIMException static
Extract selected properties from SDF files.
Parameters
pathName to the file to read
propNames the list of property names to extract. All the rest will be ignored.
Returns
a corresponding map of results.
Exceptions
DENOPTIMException if the file cannot be read.
Definition at line 1137 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.readSDFFile().
Referenced by denoptim.io.DenoptimIO.readLightWeightCandidate().
readText()
static String denoptim.io.DenoptimIO.readText (String fileName) throws DENOPTIMException static
Read text from file.
Parameters
fileName the pathname to the file to read.
Returns
the text.
Exceptions
DENOPTIMException
Definition at line 1103 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.NL.
Referenced by denoptim.combinatorial.CEBLUtils.deserializeCheckpoint(), denoptim.gui.GUITextReader.displayContent(), and denoptim.programs.fitnessevaluator.FPRunner.run().
readVertexes()
static ArrayList< Vertex > denoptim.io.DenoptimIO.readVertexes (File file, Vertex.BBType bbt) throws UndetectedFileFormatException, IOException, IllegalArgumentException, DENOPTIMException static
Reads Vertexes from any file that can contain such items.
Parameters
file the file we want to read.
bbt the type of building blocks assigned to each new vertex, if not already specified by the content of the file, i.e., this method does not overwrite the Vertex.BBType defined in the file.
Exceptions
IOException
UndetectedFileFormatException
DENOPTIMException
IllegalArgumentException
Exception
Definition at line 2329 of file DenoptimIO.java.
References denoptim.files.FileUtils.detectFileFormat(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromJSONFile(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromSDFile(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromSDFile(), and denoptim.graph.Template.setInnerGraph().
Referenced by denoptim.fragmenter.ParallelConformerExtractionAlgorithm.createAndSubmitTasks(), denoptim.fragspace.FragmentSpace.FragmentSpace(), denoptim.gui.GUIVertexInspector.importVerticesFromFile(), denoptim.gui.GUIVertexInspector.initialize(), denoptim.fragmenter.FragmenterTools.manageFragmentCollection(), denoptim.programs.fragmenter.FragmenterParameters.processParameters(), denoptim.io.DenoptimIO.readAllAPClasses(), denoptim.io.DenoptimIO.readDENOPTIMData(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.programs.fragmenter.Fragmenter.runProgram(), denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.io.DenoptimIOTest.testIOMolFragment(), and denoptim.io.DenoptimIOTest.testIOTemplate().
scanLoggingLevels()
static void denoptim.io.DenoptimIO.scanLoggingLevels (Logger logger) static
Utility to trigger logging at all known levels.
Useful to check what is the effective verbosity level.
Parameters
logger
Definition at line 2763 of file DenoptimIO.java.
writeCandidatesToFile()
static void denoptim.io.DenoptimIO.writeCandidatesToFile (File file, List< Candidate > popMembers, boolean append) throws DENOPTIMException static
Writes candidate items to file.
Always overwrites.
Parameters
file the file where to print.
popMembers the list of candidates to print to file.
append use true to append if the file exist
Exceptions
DENOPTIMException
Definition at line 1519 of file DenoptimIO.java.
References denoptim.files.FileFormat.CANDIDATESDF, and denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.ga.EAUtils.outputPopulationDetails().
writeCandidateToFile()
static void denoptim.io.DenoptimIO.writeCandidateToFile (File file, Candidate candidate, boolean append) throws DENOPTIMException static
Writes one candidate item to file.
Always overwrites.
Parameters
file the file where to print.
candidate the candidate to print to file.
append use true to append if the file exist
Exceptions
DENOPTIMException
Definition at line 1545 of file DenoptimIO.java.
References denoptim.files.FileFormat.CANDIDATESDF, and denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.ga.EAUtils.getPopulationFromFile(), denoptim.ga.EAUtils.outputFinalResults(), denoptim.task.FitnessTask.runFitnessProvider(), and denoptim.io.DenoptimIOTest.testReadGenerationFromSummary().
writeCompatibilityMatrix()
static void denoptim.io.DenoptimIO.writeCompatibilityMatrix (String fileName, HashMap< APClass, ArrayList< APClass > > cpMap, HashMap< APClass, APClass > capMap, HashSet< APClass > ends) throws DENOPTIMException static
The class compatibility matrix.
Parameters
fileName the file to be read
cpMap container for the APClass compatibility rules
capMap container for the capping rules
ends container for the definition of forbidden ends
Definition at line 1228 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.APCMAPCAPPING, denoptim.constants.DENOPTIMConstants.APCMAPCOMPRULE, denoptim.constants.DENOPTIMConstants.APCMAPFORBIDDENEND, denoptim.constants.DENOPTIMConstants.APCMAPIGNORE, denoptim.io.DenoptimIO.NL, and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.gui.CompatibilityMatrixForm.writeCopatibilityMatrixFile().
writeCuttingRules()
static void denoptim.io.DenoptimIO.writeCuttingRules (File file, List< CuttingRule > cutRules) throws DENOPTIMException static
Writes a formatted text file that collects cutting rule.
Parameters
file the file where to write.
cutRules the cutting rules to write.
Exceptions
DENOPTIMException
Definition at line 2620 of file DenoptimIO.java.
References denoptim.constants.DENOPTIMConstants.CUTRULKEYWORD, denoptim.io.DenoptimIO.NL, and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.gui.CuttingRulesSelectionDialog.CuttingRulesSelectionDialog(), and denoptim.io.DenoptimIOTest.testIOCuttingRules().
writeData()
static void denoptim.io.DenoptimIO.writeData (String fileName, String data, boolean append) throws DENOPTIMException static
Write text-like data file.
Parameters
fileName
data
append
Exceptions
DENOPTIMException
Definition at line 824 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.NL.
Referenced by denoptim.utils.SizeControlledSet.addNewUniqueEntry(), denoptim.files.FileUtils.addToRecentFiles(), denoptim.files.FileUtils.canWriteAndReadTo(), denoptim.integration.tinker.ConformationalSearchPSSROT.fixLongeLinesInXYZ(), denoptim.gui.FragmentViewPanel.getStructureFromJmolViewer(), denoptim.ga.EAUtils.outputPopulationDetails(), denoptim.integration.tinker.ConformationalSearchPSSROT.performPSSROT(), denoptim.utils.Randomizer.print(), denoptim.task.ProgramTask.printErrorToFile(), denoptim.logging.Monitor.printHeader(), denoptim.logging.Monitor.printSnapshot(), denoptim.logging.Monitor.printSummary(), denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.ga.EAUtils.selectBasedOnFitness(), denoptim.combinatorial.CEBLUtils.serializeCheckPoint(), denoptim.main.MainTest.testDefineProgramBehavior(), denoptim.io.DenoptimIOTest.testDetectFileFormat(), denoptim.graph.TemplateTest.testGetIAtomContainer(), denoptim.graph.TemplateTest.testGetIAtomContainer_DeepVertex(), denoptim.ga.EAUtilsTest.testMakeGraphFromFragmentationOfMol(), denoptim.io.DenoptimIOTest.testReadAllAtomContainersFromCIF(), denoptim.io.DenoptimIOTest.testReadCSDFormulae(), denoptim.io.DenoptimIOTest.testSerializeDeserializeDENOPTIMGraphs(), denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads(), denoptim.io.DenoptimIO.writeCompatibilityMatrix(), denoptim.io.DenoptimIO.writeCuttingRules(), denoptim.files.SingletonFileAccess.writeData(), denoptim.io.DenoptimIO.writeGraphsToJSON(), denoptim.io.DenoptimIO.writeGraphToFile(), denoptim.ga.EAUtils.writeUID(), and denoptim.io.DenoptimIO.writeVertexesToJSON().
writeGraphsToFile()
static File denoptim.io.DenoptimIO.writeGraphsToFile (File file, FileFormat format, List< DGraph > modGraphs, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graphs to file.
Always overwrites.
Parameters
file the file where to print
format how to print graphs on file
modGraphs the list of graphs to print
Returns
the reference to the file written.
Exceptions
DENOPTIMException
Definition at line 2065 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToJSON(), and denoptim.io.DenoptimIO.writeGraphsToSDF().
Referenced by denoptim.gui.GUIGraphHandler.initialize(), denoptim.programs.grapheditor.GraphEditor.runProgram(), and denoptim.programs.mol2graph.Mol2Graph.runProgram().
writeGraphsToJSON() [1/2]
static void denoptim.io.DenoptimIO.writeGraphsToJSON (File file, List< DGraph > graphs) throws DENOPTIMException static
Writes the graphs to JSON file.
Parameters
file the file where to print
graphs the list of graphs to print
Exceptions
DENOPTIMException
Definition at line 2226 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getWriter(), and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.io.DenoptimIO.writeGraphsToFile(), and denoptim.io.DenoptimIO.writeGraphToJSON().
writeGraphsToJSON() [2/2]
static void denoptim.io.DenoptimIO.writeGraphsToJSON (File file, List< DGraph > graphs, boolean append) throws DENOPTIMException static
Writes the graphs to JSON file.
Parameters
file the file where to print
graphs the list of graphs to print
append use true to append
Exceptions
DENOPTIMException
Definition at line 2243 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getWriter(), and denoptim.io.DenoptimIO.writeData().
writeGraphsToSDF() [1/3]
static void denoptim.io.DenoptimIO.writeGraphsToSDF (File file, List< DGraph > graphs, boolean append, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graphs to SDF file.
Parameters
file the file where to print
graphs the list of graphs to print
append use true to append to the file
Exceptions
DENOPTIMException
Definition at line 2155 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToSDF().
writeGraphsToSDF() [2/3]
static void denoptim.io.DenoptimIO.writeGraphsToSDF (File file, List< DGraph > graphs, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graphs to SDF file.
Parameters
file the file where to print
graphs the list of graphs to print
Exceptions
DENOPTIMException
Definition at line 2099 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToSDF().
Referenced by denoptim.ga.EAUtils.buildCandidatesByXOver(), denoptim.io.DenoptimIO.writeGraphsToFile(), denoptim.io.DenoptimIO.writeGraphsToSDF(), and denoptim.io.DenoptimIO.writeGraphToSDF().
writeGraphsToSDF() [3/3]
static void denoptim.io.DenoptimIO.writeGraphsToSDF (File file, List< DGraph > modGraphs, boolean append, boolean make3D, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graphs to SDF file.
Parameters
file the file where to print
modGraphs the list of graphs to print
append use true to append to the file
make3D use true to convert graph to 3d. If false an empty molecule will be used.
Exceptions
DENOPTIMException
Definition at line 2174 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.builder, denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.utils.GraphUtils.writeSDFFields(), and denoptim.io.DenoptimIO.writeSDFFile().
writeGraphToFile() [1/2]
static File denoptim.io.DenoptimIO.writeGraphToFile (File file, FileFormat format, DGraph graph, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the a graph to file.
Always overwrites.
Parameters
file the file where to print.
format how to print graphs on file.
graph the graph to print.
Exceptions
DENOPTIMException
Definition at line 2029 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphToJSON(), and denoptim.io.DenoptimIO.writeGraphToSDF().
Referenced by denoptim.programs.mol2graph.Mol2Graph.runProgram().
writeGraphToFile() [2/2]
static void denoptim.io.DenoptimIO.writeGraphToFile (String fileName, DGraph graph, boolean append) throws DENOPTIMException static
Writes the string representation of a graph to file.
Parameters
fileName the file where to print
graph the graph to print
append use true to append
Exceptions
DENOPTIMException
Definition at line 2260 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeData().
writeGraphToJSON()
static void denoptim.io.DenoptimIO.writeGraphToJSON (File file, DGraph graph) throws DENOPTIMException static
Writes the graph to JSON file.
Parameters
file the file where to print
graph the graphs to print
Exceptions
DENOPTIMException
Definition at line 2209 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToJSON().
Referenced by denoptim.graph.DGraph.appendVertexOnAP(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.graph.DGraph.removeChainUpToBranching(), and denoptim.io.DenoptimIO.writeGraphToFile().
writeGraphToSDF() [1/2]
static void denoptim.io.DenoptimIO.writeGraphToSDF (File file, DGraph graph, boolean append, boolean make3D, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graph to SDF file.
Parameters
file the file where to print.
graph the of graph to print.
append use true to append to the file.
make3D use true to convert graph to 3d.
Exceptions
DENOPTIMException
Definition at line 2117 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToSDF().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.ga.EAUtils.buildCandidateByMutation(), denoptim.utils.MoleculeUtils.extractIACForSubgraph(), denoptim.ga.GraphOperations.performMutation(), and denoptim.io.DenoptimIO.writeGraphToFile().
writeGraphToSDF() [2/2]
static void denoptim.io.DenoptimIO.writeGraphToSDF (File file, DGraph graph, boolean append, Logger logger, Randomizer randomizer) throws DENOPTIMException static
Writes the graph to SDF file.
Parameters
file the file where to print
graph the of graph to print
append use true to append to the file
Exceptions
DENOPTIMException
Definition at line 2136 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeGraphsToSDF().
writeMol2File()
static void denoptim.io.DenoptimIO.writeMol2File (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException static
Definition at line 706 of file DenoptimIO.java.
writeSDFFile() [1/4]
static void denoptim.io.DenoptimIO.writeSDFFile (String fileName, IAtomContainer mol) throws DENOPTIMException static
Writes IAtomContainer to SDF file.
Parameters
fileName The file to be write to.
mol The molecules to be written.
Exceptions
DENOPTIMException
Definition at line 620 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.molecularmodeling.MultiMolecularModelBuilder.build3DTree(), denoptim.fragmenter.FragmenterTools.checkElementalAnalysisAgainstFormula(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.fragmenter.FragmenterTools.filterStrucutresBySMARTS(), denoptim.utils.MoleculeUtils.getSMILESForMolecule(), denoptim.gui.MoleculeViewPanel.loadChemicalStructure(), denoptim.gui.FragmentViewPanel.loadStructure(), denoptim.graph.rings.PathSubGraph.makeMolecularRepresentation(), denoptim.utils.DummyAtomHandler.removeDummyInHapto(), denoptim.graph.rings.RingClosureFinder.reportForDebug(), denoptim.task.FitnessTask.runFitnessProvider(), denoptim.programs.genetweeker.GeneOpsRunner.runMutation(), denoptim.programs.moldecularmodelbuilder.MolecularModelBuilder.runProgram(), denoptim.programs.genetweeker.GeneOpsRunner.runXOver(), denoptim.fragmenter.ParallelFragmentationAlgorithm.splitInputForThreads(), denoptim.fragmenter.FragmentClustererTest.testCluster(), denoptim.fitness.FitnessProviderTest.testGetFitnessWithParametrizedDescriptors(), denoptim.fitness.FitnessExpressionParserTest.testProcessExpressions(), denoptim.io.DenoptimIOTest.testReadLightWeightCandidate(), denoptim.fragmenter.ParallelFragmentationAlgorithmTest.testSplitInputForThreads(), denoptim.io.DenoptimIO.writeCandidatesToFile(), denoptim.io.DenoptimIO.writeCandidateToFile(), denoptim.io.DenoptimIO.writeGraphsToSDF(), denoptim.io.DenoptimIO.writeSDFFile(), and denoptim.io.DenoptimIO.writeVertexesToSDF().
writeSDFFile() [2/4]
static void denoptim.io.DenoptimIO.writeSDFFile (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException static
Writes an IAtomContainer to SDF file.
Parameters
fileName The file to be written to
mol The molecule to be written
append
Exceptions
DENOPTIMException
Definition at line 685 of file DenoptimIO.java.
writeSDFFile() [3/4]
static void denoptim.io.DenoptimIO.writeSDFFile (String fileName, List< IAtomContainer > mols) throws DENOPTIMException static
Writes IAtomContainers to SDF file.
Parameters
fileName The file to be write to.
mols The molecules to be written.
Exceptions
DENOPTIMException
Definition at line 636 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeSDFFile().
writeSDFFile() [4/4]
static void denoptim.io.DenoptimIO.writeSDFFile (String fileName, List< IAtomContainer > mols, boolean append) throws DENOPTIMException static
Writes a set of IAtomContainers to SDF file.
Parameters
fileName The file to be written to
mols The molecules to be written
append use true to append to the file
Exceptions
DENOPTIMException
Definition at line 651 of file DenoptimIO.java.
writeSmiles()
static void denoptim.io.DenoptimIO.writeSmiles (String fileName, String smiles, boolean append) throws DENOPTIMException static
Writes a single smiles string to the specified file.
Parameters
fileName The file to be written to
smiles
append if true append to the file
Exceptions
DENOPTIMException
Definition at line 794 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.NL.
writeSmilesSet()
static void denoptim.io.DenoptimIO.writeSmilesSet (String fileName, String[] smiles, boolean append) throws DENOPTIMException static
Writes multiple smiles string array to the specified file.
Parameters
fileName The file to be written to
smiles array of smiles strings to be written
append if true append to the file
Exceptions
DENOPTIMException
Definition at line 761 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.NL.
writeVertexesToFile() [1/2]
static File denoptim.io.DenoptimIO.writeVertexesToFile (File file, FileFormat format, List< Vertex > vertexes) throws DENOPTIMException static
Writes vertexes to file.
Always overwrites.
Parameters
file the file where to print
format how to print vertexes on file
vertexes the list of vertexes to print
Exceptions
DENOPTIMException
Definition at line 472 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeVertexesToFile().
Referenced by denoptim.fragmenter.ConformerExtractorTask.call(), denoptim.fragmenter.FragmenterTools.fragmentation(), denoptim.gui.GUIGraphHandler.initialize(), denoptim.gui.GUIVertexInspector.initialize(), denoptim.fragmenter.FragmenterTools.manageFragmentCollection(), denoptim.io.DenoptimIOTest.testAppendToJSON(), denoptim.fragmenter.FragmentClustererTest.testCluster(), denoptim.io.DenoptimIOTest.testIOEmptyVertex(), denoptim.io.DenoptimIOTest.testIOMolFragment(), denoptim.io.DenoptimIOTest.testIOTemplate(), denoptim.io.DenoptimIO.writeVertexesToFile(), and denoptim.io.DenoptimIO.writeVertexToFile().
writeVertexesToFile() [2/2]
static File denoptim.io.DenoptimIO.writeVertexesToFile (File file, FileFormat format, List< Vertex > vertexes, boolean append) throws DENOPTIMException static
Writes vertexes to file.
Always overwrites.
Parameters
file the file where to print
format how to print vertexes on file
vertexes the list of vertexes to print
Exceptions
DENOPTIMException
Definition at line 506 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeVertexesToJSON(), and denoptim.io.DenoptimIO.writeVertexesToSDF().
writeVertexesToJSON() [1/2]
static void denoptim.io.DenoptimIO.writeVertexesToJSON (File file, List< Vertex > vertexes) throws DENOPTIMException static
Writes vertexes to JSON file.
Always overwrites.
Parameters
file the file where to print.
vertexes the list of vertexes to print.
Exceptions
DENOPTIMException
Definition at line 539 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeVertexesToJSON().
Referenced by denoptim.io.DenoptimIO.writeVertexesToFile(), and denoptim.io.DenoptimIO.writeVertexesToJSON().
writeVertexesToJSON() [2/2]
static void denoptim.io.DenoptimIO.writeVertexesToJSON (File file, List< Vertex > vertexes, boolean append) throws DENOPTIMException static
Writes vertexes to JSON file.
Always overwrites.
Parameters
file the file where to print.
vertexes the list of vertexes to print.
append use true to append to the existing list of vertexes found in the file.
Exceptions
DENOPTIMException
Definition at line 556 of file DenoptimIO.java.
References denoptim.json.DENOPTIMgson.getWriter(), denoptim.io.DenoptimIO.readDENOPTIMVertexesFromJSONFile(), and denoptim.io.DenoptimIO.writeData().
writeVertexesToSDF()
static void denoptim.io.DenoptimIO.writeVertexesToSDF (File file, List< Vertex > vertexes, boolean append) throws DENOPTIMException static
Write a list of vertexes to file.
Parameters
file the file to write to.
vertexes the vertexes to be written.
append use true to append instead of overwriting.
Exceptions
DENOPTIMException
Definition at line 599 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), denoptim.graph.FragmentIsomorphismInspector.isomorphismExists(), denoptim.io.DenoptimIOTest.testReadAllAPClasses(), denoptim.io.DenoptimIO.writeVertexesToFile(), and denoptim.io.DenoptimIO.writeVertexToSDF().
writeVertexToFile()
static File denoptim.io.DenoptimIO.writeVertexToFile (File file, FileFormat format, Vertex vertex, boolean append) throws DENOPTIMException static
Writes vertexes to file.
Always overwrites.
Parameters
file the file where to print
format how to print vertexes on file
vertex the vertex to print
Exceptions
DENOPTIMException
Definition at line 488 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeVertexesToFile().
Referenced by denoptim.fragmenter.FragmenterTools.manageFragmentCollection().
writeVertexToSDF()
static void denoptim.io.DenoptimIO.writeVertexToSDF (String pathName, Vertex vertex) throws DENOPTIMException static
Writes a vertex to an SDF file.
Parameters
pathName pathname where to write.
vertices list of vertices to write.
Exceptions
DENOPTIMException
Definition at line 581 of file DenoptimIO.java.
References denoptim.io.DenoptimIO.writeVertexesToSDF().
writeXYZFile()
static void denoptim.io.DenoptimIO.writeXYZFile (String fileName, IAtomContainer mol, boolean append) throws DENOPTIMException static
Definition at line 729 of file DenoptimIO.java.
Member Data Documentation
builder
final IChemObjectBuilder denoptim.io.DenoptimIO.builder static private
Initial value:
=
            SilentChemObjectBuilder.getInstance()
Definition at line 130 of file DenoptimIO.java.
Referenced by denoptim.io.DenoptimIO.writeGraphsToSDF().
FS
final String denoptim.io.DenoptimIO.FS = System.getProperty("file.separator") static
File separator from system.
Definition at line 123 of file DenoptimIO.java.
Referenced by denoptim.files.FileUtils.getAvailableFileName(), denoptim.programs.fragmenter.FragmenterParameters.getMWSlotFileNameAllFrags(), denoptim.programs.fragmenter.FragmenterParameters.getMWSlotFileNameUnqFrags(), denoptim.io.DenoptimIO.readAllAtomContainers(), and denoptim.io.DenoptimIO.readPopulationMemberPathnames().
NL
final String denoptim.io.DenoptimIO.NL = System.getProperty("line.separator") static
Newline character from system.
Definition at line 128 of file DenoptimIO.java.
Referenced by denoptim.utils.FormulaUtils.compareFormulaAndElementalAnalysis(), denoptim.files.FileUtils.isLineInTxtFile(), denoptim.io.DenoptimIO.readText(), denoptim.utils.DummyAtomHandler.removeDummy(), denoptim.utils.DummyAtomHandler.removeDummyInHapto(), denoptim.io.DenoptimIO.writeCompatibilityMatrix(), denoptim.io.DenoptimIO.writeCuttingRules(), denoptim.io.DenoptimIO.writeData(), denoptim.io.DenoptimIO.writeSmiles(), and denoptim.io.DenoptimIO.writeSmilesSet().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/io/DenoptimIO.java