DENOPTIM: denoptim.gui.ScrollableJPupupMenu Class Reference
denoptim.gui.ScrollableJPupupMenu Class Reference
A popup menu' that has a fixed size and can be scrolled to see menu items that do not fit into the fixed-size panel.
Public Member Functions
ScrollableJPupupMenu ()
void showMenu (Component invoker, int x, int y)
Displays the menu with the components that have been added so far.
void addCheckBox (JCheckBox item)
Add a check box to the list of check boxes to display in the menu.
Protected Member Functions
List< JCheckBox > getAllBChekBoxes ()
Returns the list of check boxes that is displayed in the menu.
Private Attributes
JPopupMenu menu
JPanel menuPanel
List< JCheckBox > allBChekBoxes = new ArrayList<JCheckBox>()
Detailed Description
A popup menu' that has a fixed size and can be scrolled to see menu items that do not fit into the fixed-size panel.
Definition at line 24 of file ScrollableJPupupMenu.java.
Constructor & Destructor Documentation
ScrollableJPupupMenu()
denoptim.gui.ScrollableJPupupMenu.ScrollableJPupupMenu ()
Definition at line 32 of file ScrollableJPupupMenu.java.
Member Function Documentation
addCheckBox()
void denoptim.gui.ScrollableJPupupMenu.addCheckBox (JCheckBox item)
Add a check box to the list of check boxes to display in the menu.
Parameters
item
Definition at line 80 of file ScrollableJPupupMenu.java.
References denoptim.gui.ScrollableJPupupMenu.allBChekBoxes.
Referenced by denoptim.gui.GUIInspectGARun.buildAndFillMonitorPlot().
getAllBChekBoxes()
List< JCheckBox > denoptim.gui.ScrollableJPupupMenu.getAllBChekBoxes () protected
Returns the list of check boxes that is displayed in the menu.
Returns
Definition at line 91 of file ScrollableJPupupMenu.java.
References denoptim.gui.ScrollableJPupupMenu.allBChekBoxes.
Referenced by denoptim.gui.GUIInspectGARun.initialize().
showMenu()
void denoptim.gui.ScrollableJPupupMenu.showMenu (Component invoker, int x, int y)
Displays the menu with the components that have been added so far.
Parameters
invoker
x
y
Definition at line 43 of file ScrollableJPupupMenu.java.
References denoptim.gui.ScrollableJPupupMenu.allBChekBoxes, denoptim.gui.ScrollableJPupupMenu.menu, and denoptim.gui.ScrollableJPupupMenu.menuPanel.
Referenced by denoptim.gui.GUIInspectGARun.initialize().
Member Data Documentation
allBChekBoxes
List<JCheckBox> denoptim.gui.ScrollableJPupupMenu.allBChekBoxes = new ArrayList<JCheckBox>() private
Definition at line 28 of file ScrollableJPupupMenu.java.
Referenced by denoptim.gui.ScrollableJPupupMenu.addCheckBox(), denoptim.gui.ScrollableJPupupMenu.getAllBChekBoxes(), and denoptim.gui.ScrollableJPupupMenu.showMenu().
menu
JPopupMenu denoptim.gui.ScrollableJPupupMenu.menu private
Definition at line 26 of file ScrollableJPupupMenu.java.
Referenced by denoptim.gui.ScrollableJPupupMenu.showMenu().
menuPanel
JPanel denoptim.gui.ScrollableJPupupMenu.menuPanel private
Definition at line 27 of file ScrollableJPupupMenu.java.
Referenced by denoptim.gui.ScrollableJPupupMenu.showMenu().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/ScrollableJPupupMenu.java