DENOPTIM: denoptim.gui.GUITextReader Class Reference
denoptim.gui.GUITextReader Class Reference
A panel that allows to print the content of a text file into a GUI tab.
Public Member Functions
GUITextReader (GUIMainPanel mainPanel)
Constructor.
void displayContent (File file)
Print the content of the given file in this tab's pane.
Public Member Functions inherited from denoptim.gui.GUICardPanel
GUICardPanel (GUIMainPanel mainPanel, String newPanelName)
Constructor for JPanel meant to be a single "card" in the deck of cards.
boolean hasUnsavedChanges ()
Check for unsaved changes in the components included in this card.
Static Public Attributes
static AtomicInteger texReaderTabUID = new AtomicInteger(1)
Unique identified for instances of this handler.
Private Member Functions
void initialize ()
Initialize the panel and add buttons.
void setSourceTitle (String string)
Private Attributes
JTextPane txtPane
TitledBorder border
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
Additional Inherited Members
Protected Attributes inherited from denoptim.gui.GUICardPanel
GUIMainPanel mainPanel
The main panel (cards deck)
Detailed Description
A panel that allows to print the content of a text file into a GUI tab.
Author
Marco Foscato
Definition at line 44 of file GUITextReader.java.
Constructor & Destructor Documentation
GUITextReader()
denoptim.gui.GUITextReader.GUITextReader (GUIMainPanel mainPanel)
Constructor.
Definition at line 65 of file GUITextReader.java.
References denoptim.gui.GUITextReader.initialize(), denoptim.gui.GUICardPanel.mainPanel, and denoptim.gui.GUITextReader.texReaderTabUID.
Member Function Documentation
displayContent()
void denoptim.gui.GUITextReader.displayContent (File file)
Print the content of the given file in this tab's pane.
Parameters
file the file to be read
Definition at line 109 of file GUITextReader.java.
References denoptim.io.DenoptimIO.readText(), denoptim.gui.GUITextReader.setSourceTitle(), and denoptim.gui.GUITextReader.txtPane.
Referenced by denoptim.gui.MainToolBar.openFile().
initialize()
void denoptim.gui.GUITextReader.initialize () private
Initialize the panel and add buttons.
Definition at line 78 of file GUITextReader.java.
References denoptim.gui.ButtonsBar.add(), denoptim.gui.GUITextReader.border, and denoptim.gui.GUITextReader.txtPane.
Referenced by denoptim.gui.GUITextReader.GUITextReader().
setSourceTitle()
void denoptim.gui.GUITextReader.setSourceTitle (String string) private
Definition at line 136 of file GUITextReader.java.
References denoptim.gui.GUITextReader.border.
Referenced by denoptim.gui.GUITextReader.displayContent().
Member Data Documentation
border
TitledBorder denoptim.gui.GUITextReader.border private
Definition at line 57 of file GUITextReader.java.
Referenced by denoptim.gui.GUITextReader.initialize(), and denoptim.gui.GUITextReader.setSourceTitle().
serialVersionUID
final long denoptim.gui.GUITextReader.serialVersionUID = 1L static private
Version UID.
Definition at line 49 of file GUITextReader.java.
texReaderTabUID
AtomicInteger denoptim.gui.GUITextReader.texReaderTabUID = new AtomicInteger(1) static
Unique identified for instances of this handler.
Definition at line 54 of file GUITextReader.java.
Referenced by denoptim.gui.GUITextReader.GUITextReader().
txtPane
JTextPane denoptim.gui.GUITextReader.txtPane private
Definition at line 56 of file GUITextReader.java.
Referenced by denoptim.gui.GUITextReader.displayContent(), and denoptim.gui.GUITextReader.initialize().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/GUITextReader.java