DENOPTIM: denoptim.fragspace.FragmentSpaceTest Class Reference
denoptim.fragspace.FragmentSpaceTest Class Reference
Unit test for fragment space.
Classes
class TestCase
Public Member Functions
void testSymmetry () throws Exception
void testGetFragsWithAPClass () throws Exception
void testGetVerticesWithAPClass () throws Exception
void testGetVerticesWithAPClasses () throws Exception
void testGetVerticesWithAPFingerprint () throws Exception
void testGetFragsWithAPClassStartingWith () throws Exception
void testGetFragAPsCompatibleWithClass () throws Exception
void testGetFragAPsCompatibleWithTheseAPs () throws Exception
void testGetFragmentsCompatibleWithTheseAPs () throws Exception
void testGetRCVsForAPClass () throws Exception
void testGetRCVsWithAPClass () throws Exception
void testFusedRingAddedToFragmentLibrary () throws Exception
Check that the following graph's fused ring gets added to the fragment library.
void testFusedRingAddedToScaffoldLibrary () throws Exception
Checks that a graph with a fused ring containing a scaffold vertex is added to the scaffold library.
void testFusedRingOnlyAddedOnce () throws DENOPTIMException
void testUseWholeMolGeometryForExtractedTemplates () throws Exception
Works with this graph:
Static Package Attributes
static File tempDir
Private Member Functions
FragmentSpaceParameters buildFragmentSpace () throws DENOPTIMException
TestCase getTestCase () throws DENOPTIMException
Template getExpectedTemplate (DGraph g, Vertex c3) throws DENOPTIMException
Fragment getCarbonVertex () throws DENOPTIMException
Vertex getRCV () throws DENOPTIMException
Point3d getRandomVector ()
Private Attributes
final Random rng = new Random()
Static Private Attributes
static final String SEP = System.getProperty("file.separator")
static final int APSUBRULE = 0
static final String RULAPCS = "apc-S"
static final String RULAPC1 = "apc-1"
static final String RULAPC2 = "apc-2"
static final String RULAPC3 = "apc-3"
static final String RULAPC4 = "apc-4"
static final String RULAPC5 = "a_p_c-5"
static final String RULAPC6 = "a_p_c-6"
static final String RULAPCC1 = "cap-1"
static final String RULAPCC2 = "cap-2"
static final BBType BBTFRAG = BBType.FRAGMENT
static APClass APCS
static APClass APC1
static APClass APC2
static APClass APC3
static APClass APC4
static APClass APC5
static APClass APC6
static APClass APCC1
static APClass APCC2
Detailed Description
Unit test for fragment space.
Author
Marco Foscato
Definition at line 74 of file FragmentSpaceTest.java.
Member Function Documentation
buildFragmentSpace()
FragmentSpaceParameters denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace () throws DENOPTIMException private
Definition at line 109 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.APC3, denoptim.fragspace.FragmentSpaceTest.APC4, denoptim.fragspace.FragmentSpaceTest.APC5, denoptim.fragspace.FragmentSpaceTest.APC6, denoptim.fragspace.FragmentSpaceTest.APCC1, denoptim.fragspace.FragmentSpaceTest.APCC2, denoptim.fragspace.FragmentSpaceTest.APCS, denoptim.fragspace.FragmentSpaceTest.APSUBRULE, denoptim.graph.Edge.BondType.DOUBLE, denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.fragspace.FragmentSpaceTest.RULAPC1, denoptim.fragspace.FragmentSpaceTest.RULAPC2, denoptim.fragspace.FragmentSpaceTest.RULAPC3, denoptim.fragspace.FragmentSpaceTest.RULAPC4, denoptim.fragspace.FragmentSpaceTest.RULAPC5, denoptim.fragspace.FragmentSpaceTest.RULAPC6, denoptim.fragspace.FragmentSpaceTest.RULAPCC1, denoptim.fragspace.FragmentSpaceTest.RULAPCC2, denoptim.fragspace.FragmentSpaceTest.RULAPCS, denoptim.fragspace.FragmentSpaceTest.SEP, denoptim.graph.Edge.BondType.SINGLE, denoptim.fragspace.FragmentSpaceTest.tempDir, denoptim.io.DenoptimIO.writeCompatibilityMatrix(), and denoptim.io.DenoptimIO.writeVertexesToSDF().
Referenced by denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClassStartingWith(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), denoptim.fragspace.FragmentSpaceTest.testSymmetry(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
getCarbonVertex()
Fragment denoptim.fragspace.FragmentSpaceTest.getCarbonVertex () throws DENOPTIMException private
Definition at line 892 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpaceTest.getRandomVector(), and denoptim.utils.GraphUtils.getUniqueVertexIndex().
Referenced by denoptim.fragspace.FragmentSpaceTest.getTestCase().
getExpectedTemplate()
Template denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate (DGraph g, Vertex c3) throws DENOPTIMException private
Definition at line 876 of file FragmentSpaceTest.java.
References denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.removeVertex(), denoptim.graph.DGraph.renumberGraphVertices(), denoptim.graph.Vertex.setBuildingBlockId(), and denoptim.graph.Template.setInnerGraph().
Referenced by denoptim.fragspace.FragmentSpaceTest.getTestCase().
getRandomVector()
Point3d denoptim.fragspace.FragmentSpaceTest.getRandomVector () private
Definition at line 929 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.rng.
Referenced by denoptim.fragspace.FragmentSpaceTest.getCarbonVertex(), and denoptim.fragspace.FragmentSpaceTest.getRCV().
getRCV()
Vertex denoptim.fragspace.FragmentSpaceTest.getRCV () throws DENOPTIMException private
Definition at line 911 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpaceTest.getRandomVector(), and denoptim.utils.GraphUtils.getUniqueVertexIndex().
Referenced by denoptim.fragspace.FragmentSpaceTest.getTestCase().
getTestCase()
TestCase denoptim.fragspace.FragmentSpaceTest.getTestCase () throws DENOPTIMException private
  ↑         ↑
← C1 - C2 - C3 →
  .  / |    ↓
  C4 . C5 →
  ↓    ↓
Definition at line 840 of file FragmentSpaceTest.java.
References denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpaceTest.getCarbonVertex(), denoptim.fragspace.FragmentSpaceTest.getExpectedTemplate(), denoptim.fragspace.FragmentSpaceTest.getRCV(), and denoptim.graph.DGraph.renumberGraphVertices().
Referenced by denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary(), and denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce().
testFusedRingAddedToFragmentLibrary()
void denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToFragmentLibrary () throws Exception
Check that the following graph's fused ring gets added to the fragment library.
Dots are chords ↑ ↑ ← C1 - C2 - C3 → . / | ↓ C4 . C5 → ↓ ↓
Exceptions
Exception
Definition at line 738 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.files.FileUtils.deleteFile(), denoptim.fragspace.FragmentSpaceTest.TestCase.expected, denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedFragments(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedScaffolds(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.fragspace.FragmentSpaceTest.TestCase.graph, and denoptim.graph.Template.sameAs().
testFusedRingAddedToScaffoldLibrary()
void denoptim.fragspace.FragmentSpaceTest.testFusedRingAddedToScaffoldLibrary () throws Exception
Checks that a graph with a fused ring containing a scaffold vertex is added to the scaffold library.
Exceptions
Exception
Definition at line 771 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.files.FileUtils.deleteFile(), denoptim.fragspace.FragmentSpaceTest.TestCase.expected, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.graph.Template.getInnerGraph(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedFragments(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedScaffolds(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), denoptim.graph.DGraph.getVertexList(), denoptim.fragspace.FragmentSpaceTest.TestCase.graph, denoptim.graph.Template.sameAs(), denoptim.graph.Vertex.BBType.SCAFFOLD, and denoptim.graph.Vertex.setBuildingBlockType().
testFusedRingOnlyAddedOnce()
void denoptim.fragspace.FragmentSpaceTest.testFusedRingOnlyAddedOnce () throws DENOPTIMException
Definition at line 801 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.DGraph.clone(), denoptim.files.FileUtils.deleteFile(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedFragments(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedScaffolds(), denoptim.fragspace.FragmentSpaceTest.getTestCase(), and denoptim.fragspace.FragmentSpaceTest.TestCase.graph.
testGetFragAPsCompatibleWithClass()
void denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass () throws Exception
Definition at line 464 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.graph.APClass.isCPMapCompatibleWith(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.graph.Vertex.newVertexFromLibrary().
testGetFragAPsCompatibleWithTheseAPs()
void denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs () throws Exception
Definition at line 489 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.BBTFRAG, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.fragspace.IdFragmentAndAP.getApId(), denoptim.fragspace.FragmentSpace.getFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.IdFragmentAndAP.getVertexMolId(), denoptim.fragspace.IdFragmentAndAP.getVertexMolType(), denoptim.graph.APClass.isCPMapCompatibleWith(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.graph.Vertex.newVertexFromLibrary().
testGetFragmentsCompatibleWithTheseAPs()
void denoptim.fragspace.FragmentSpaceTest.testGetFragmentsCompatibleWithTheseAPs () throws Exception
Definition at line 539 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.BBTFRAG, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpace.getFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), and denoptim.fragspace.FragmentSpace.isDefined().
testGetFragsWithAPClass()
void denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass () throws Exception
Definition at line 302 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.Vertex.getAP(), denoptim.graph.AttachmentPoint.getAPClass(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpace.getFragsWithAPClass(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.graph.Vertex.newVertexFromLibrary().
testGetFragsWithAPClassStartingWith()
void denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClassStartingWith () throws Exception
Definition at line 440 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClassStartingWith(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.fragspace.FragmentSpaceTest.RULAPC5.
testGetRCVsForAPClass()
void denoptim.fragspace.FragmentSpaceTest.testGetRCVsForAPClass () throws Exception
Definition at line 559 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.fragspace.FragmentSpace.getRCVsForAPClass(), denoptim.graph.APClass.make(), denoptim.graph.APClass.RCACLASSMINUS, denoptim.graph.APClass.RCACLASSPLUS, denoptim.graph.rings.RingClosingAttractor.RCALABELPERAPCLASS, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.graph.Vertex.setAsRCV().
testGetRCVsWithAPClass()
void denoptim.fragspace.FragmentSpaceTest.testGetRCVsWithAPClass () throws Exception
Definition at line 653 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAP(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.fragspace.FragmentSpace.getRCVsWithAPClass(), denoptim.graph.APClass.make(), denoptim.graph.APClass.RCACLASSMINUS, denoptim.graph.APClass.RCACLASSPLUS, denoptim.graph.rings.RingClosingAttractor.RCALABELPERAPCLASS, denoptim.graph.Fragment.sameAs(), denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), and denoptim.graph.Vertex.setAsRCV().
testGetVerticesWithAPClass()
void denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClass () throws Exception
Definition at line 324 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClass(), and denoptim.fragspace.FragmentSpace.isDefined().
testGetVerticesWithAPClasses()
void denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses () throws Exception
Definition at line 341 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpace.getVerticesWithAPClasses(), and denoptim.fragspace.FragmentSpace.isDefined().
testGetVerticesWithAPFingerprint()
void denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint () throws Exception
Definition at line 364 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.fragspace.FragmentSpaceTest.APC1, denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.APCS, denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.fragspace.FragmentSpaceTest.BBTFRAG, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.fragspace.FragmentSpace.getVerticesWithAPFingerprint(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.graph.Fragment.projectAPsToProperties().
testSymmetry()
void denoptim.fragspace.FragmentSpaceTest.testSymmetry () throws Exception
Definition at line 277 of file FragmentSpaceTest.java.
References denoptim.fragspace.FragmentSpaceTest.APC4, denoptim.fragspace.FragmentSpaceTest.APC5, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.utils.GraphUtils.getUniqueVertexIndex(), denoptim.fragspace.FragmentSpace.isDefined(), and denoptim.graph.Vertex.newVertexFromLibrary().
testUseWholeMolGeometryForExtractedTemplates()
void denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates () throws Exception
Works with this graph:
           c1
           |
  v1--v2--v3
       |   |
       |   v11
       |   (chord)
       |   v10          c3
       |   |            |
      v4--v6--v9--v5---v7
       |           \    |
      c2            \   v12
                     |  (chord)
                     \  v13
                      \ |
                       v8-v13
                       |
                       c4
Definition at line 977 of file FragmentSpaceTest.java.
References denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.DGraph.addEdge(), denoptim.fragspace.FragmentSpace.addFusedRingsToFragmentLibrary(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.fragspace.FragmentSpaceTest.APC2, denoptim.fragspace.FragmentSpaceTest.APC3, denoptim.fragspace.FragmentSpaceTest.APC4, denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.fragspace.FragmentSpaceTest.BBTFRAG, denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.DGraph.clone(), denoptim.molecularmodeling.ThreeDimTreeBuilder.convertGraphTo3DAtomContainer(), denoptim.files.FileUtils.deleteFile(), denoptim.graph.Edge.BondType.DOUBLE, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpaceParameters.getFragmentSpace(), denoptim.graph.Vertex.getIAtomContainer(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedFragments(), denoptim.fragspace.FragmentSpaceParameters.getPathnameToAppendedScaffolds(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.utils.MoleculeUtils.getSymbolOrLabel(), denoptim.fragspace.FragmentSpace.getVertexFromLibrary(), denoptim.graph.APClass.make(), denoptim.graph.Fragment.projectAPsToProperties(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpaceTest.SEP, denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Edge.BondType.SINGLE, and denoptim.fragspace.FragmentSpaceTest.tempDir.
Member Data Documentation
APC1
APClass denoptim.fragspace.FragmentSpaceTest.APC1 static private
Definition at line 98 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceTest.getCarbonVertex(), denoptim.fragspace.FragmentSpaceTest.getRCV(), denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithClass(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses(), and denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint().
APC2
APClass denoptim.fragspace.FragmentSpaceTest.APC2 static private
Definition at line 99 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClass(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPClasses(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
APC3
APClass denoptim.fragspace.FragmentSpaceTest.APC3 static private
Definition at line 100 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
APC4
APClass denoptim.fragspace.FragmentSpaceTest.APC4 static private
Definition at line 101 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), denoptim.fragspace.FragmentSpaceTest.testSymmetry(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
APC5
APClass denoptim.fragspace.FragmentSpaceTest.APC5 static private
Definition at line 102 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testSymmetry().
APC6
APClass denoptim.fragspace.FragmentSpaceTest.APC6 static private
Definition at line 103 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
APCC1
APClass denoptim.fragspace.FragmentSpaceTest.APCC1 static private
Definition at line 104 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
APCC2
APClass denoptim.fragspace.FragmentSpaceTest.APCC2 static private
Definition at line 105 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
APCS
APClass denoptim.fragspace.FragmentSpaceTest.APCS static private
Definition at line 97 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint().
APSUBRULE
final int denoptim.fragspace.FragmentSpaceTest.APSUBRULE = 0 static private
Definition at line 83 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
BBTFRAG
final BBType denoptim.fragspace.FragmentSpaceTest.BBTFRAG = BBType.FRAGMENT static private
Definition at line 95 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.testGetFragAPsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetFragmentsCompatibleWithTheseAPs(), denoptim.fragspace.FragmentSpaceTest.testGetVerticesWithAPFingerprint(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
rng
final Random denoptim.fragspace.FragmentSpaceTest.rng = new Random() private
Definition at line 81 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.getRandomVector().
RULAPC1
final String denoptim.fragspace.FragmentSpaceTest.RULAPC1 = "apc-1" static private
Definition at line 86 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPC2
final String denoptim.fragspace.FragmentSpaceTest.RULAPC2 = "apc-2" static private
Definition at line 87 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPC3
final String denoptim.fragspace.FragmentSpaceTest.RULAPC3 = "apc-3" static private
Definition at line 88 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPC4
final String denoptim.fragspace.FragmentSpaceTest.RULAPC4 = "apc-4" static private
Definition at line 89 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPC5
final String denoptim.fragspace.FragmentSpaceTest.RULAPC5 = "a_p_c-5" static private
Definition at line 90 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testGetFragsWithAPClassStartingWith().
RULAPC6
final String denoptim.fragspace.FragmentSpaceTest.RULAPC6 = "a_p_c-6" static private
Definition at line 91 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPCC1
final String denoptim.fragspace.FragmentSpaceTest.RULAPCC1 = "cap-1" static private
Definition at line 92 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPCC2
final String denoptim.fragspace.FragmentSpaceTest.RULAPCC2 = "cap-2" static private
Definition at line 93 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
RULAPCS
final String denoptim.fragspace.FragmentSpaceTest.RULAPCS = "apc-S" static private
Definition at line 85 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace().
SEP
final String denoptim.fragspace.FragmentSpaceTest.SEP = System.getProperty("file.separator") static private
Definition at line 76 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
tempDir
File denoptim.fragspace.FragmentSpaceTest.tempDir static package
Definition at line 79 of file FragmentSpaceTest.java.
Referenced by denoptim.fragspace.FragmentSpaceTest.buildFragmentSpace(), and denoptim.fragspace.FragmentSpaceTest.testUseWholeMolGeometryForExtractedTemplates().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/fragspace/FragmentSpaceTest.java