DENOPTIM: denoptim.fitness.DescriptorForFitness Class Reference
denoptim.fitness.DescriptorForFitness Class Reference
This is a reference to a specific descriptor value.
Public Member Functions
DescriptorForFitness (String shortName, String className, IDescriptor implementation, int resultId)
DescriptorForFitness (String shortName, String className, IDescriptor implementation, int resultId, String[] dictClasses, String dictDefinition, String dictTitle)
String getShortName ()
void setVariables (List< Variable > variables)
Overwrites the list of variables using this descriptor.
List< Variable > getVariables ()
Get the variables that make use of values produced by this descriptor.
String getClassName ()
IDescriptor getImplementation ()
String getDictTitle ()
String getDictDefinition ()
String[] getDictClasses ()
String toString ()
String getDictString ()
Utility only meant to print some info.
DescriptorForFitness cloneAllButImpl ()
This is a sort of cloning that returns a new DescriptorForFitness with the same field content of this one (i.e., deep copy), but a shallow copy of the list of variables, and a null implementation.
DescriptorForFitness makeCopy () throws DENOPTIMException
Copy this descriptor and created an independent instance of the underlying descriptor implementation.
void addDependentVariable (Variable v)
Append the reference to a variable that used data produced by the calculation of this descriptor.
Protected Attributes
String className
ClassName pointing to the implementation of this descriptor's calculator.
IDescriptor implementation
Implementation of the descriptor's calculator.
String shortName
Descriptor short name.
List< Variable > variables = new ArrayList<Variable>()
Variables that use values calculated by this descriptor.
int resultId = 0
Pointer to a specific results among those that are produced by the calculation of this descriptor, or 0 for descriptors that produce a single value.
String[] dictClasses
The class(es) of descriptor as define in the descriptor dictionary.
String dictDefinition
The Definition of descriptor as define in the descriptor dictionary.
String dictTitle
The title of descriptor as define in the descriptor dictionary.
Static Private Member Functions
static IDescriptor newDescriptorImplementation (DescriptorForFitness oldParent) throws DENOPTIMException
Static Private Attributes
static IChemObjectBuilder cdkBuilder
Utility for constructing CDK objects.
Detailed Description
This is a reference to a specific descriptor value.
Not the numerical result, but the identity of the value.
Definition at line 37 of file DescriptorForFitness.java.
Constructor & Destructor Documentation
DescriptorForFitness() [1/2]
denoptim.fitness.DescriptorForFitness.DescriptorForFitness (String shortName, String className, IDescriptor implementation, int resultId)
Definition at line 89 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.className, denoptim.fitness.DescriptorForFitness.implementation, denoptim.fitness.DescriptorForFitness.resultId, and denoptim.fitness.DescriptorForFitness.shortName.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl().
DescriptorForFitness() [2/2]
denoptim.fitness.DescriptorForFitness.DescriptorForFitness (String shortName, String className, IDescriptor implementation, int resultId, String[] dictClasses, String dictDefinition, String dictTitle)
Definition at line 100 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.className, denoptim.fitness.DescriptorForFitness.dictClasses, denoptim.fitness.DescriptorForFitness.dictDefinition, denoptim.fitness.DescriptorForFitness.dictTitle, denoptim.fitness.DescriptorForFitness.implementation, denoptim.fitness.DescriptorForFitness.resultId, and denoptim.fitness.DescriptorForFitness.shortName.
Member Function Documentation
addDependentVariable()
void denoptim.fitness.DescriptorForFitness.addDependentVariable (Variable v)
Append the reference to a variable that used data produced by the calculation of this descriptor.
Parameters
v the reference to the variable.
Definition at line 301 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.variables.
Referenced by denoptim.fitness.FitnessExpressionParser.parse(), denoptim.fitness.FitnessProviderTest.testGetFitness(), and denoptim.fitness.FitnessProviderTest.testGetFitnessWithCustomDescriptors().
cloneAllButImpl()
DescriptorForFitness denoptim.fitness.DescriptorForFitness.cloneAllButImpl ()
This is a sort of cloning that returns a new DescriptorForFitness with the same field content of this one (i.e., deep copy), but a shallow copy of the list of variables, and a null implementation.
The latter will have to be instantiated elsewhere.
Returns
a clone with null descriptor implementation
Definition at line 235 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.className, denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.dictClasses, denoptim.fitness.DescriptorForFitness.dictDefinition, denoptim.fitness.DescriptorForFitness.dictTitle, denoptim.fitness.DescriptorForFitness.resultId, denoptim.fitness.DescriptorForFitness.setVariables(), denoptim.fitness.DescriptorForFitness.shortName, and denoptim.fitness.DescriptorForFitness.variables.
Referenced by denoptim.fitness.FitnessProvider.FitnessProvider(), and denoptim.fitness.DescriptorForFitness.makeCopy().
getClassName()
String denoptim.fitness.DescriptorForFitness.getClassName ()
Definition at line 141 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.className.
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm(), and denoptim.fitness.FitnessProvider.FitnessProvider().
getDictClasses()
String[] denoptim.fitness.DescriptorForFitness.getDictClasses ()
Definition at line 169 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.dictClasses.
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
getDictDefinition()
String denoptim.fitness.DescriptorForFitness.getDictDefinition ()
Definition at line 162 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.dictDefinition.
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
getDictString()
String denoptim.fitness.DescriptorForFitness.getDictString ()
Utility only meant to print some info.
Definition at line 206 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.dictClasses, denoptim.fitness.DescriptorForFitness.dictDefinition, and denoptim.fitness.DescriptorForFitness.dictTitle.
getDictTitle()
String denoptim.fitness.DescriptorForFitness.getDictTitle ()
Definition at line 155 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.dictTitle.
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
getImplementation()
IDescriptor denoptim.fitness.DescriptorForFitness.getImplementation ()
Definition at line 148 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.implementation.
Referenced by denoptim.gui.FitnessParametersForm.FitnessParametersForm().
getShortName()
String denoptim.fitness.DescriptorForFitness.getShortName ()
Definition at line 112 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.shortName.
Referenced by denoptim.gui.FitnessParametersForm.DescriptorTreeNode.DescriptorTreeNode(), denoptim.gui.FitnessParametersForm.FitnessParametersForm(), denoptim.fitness.FitnessExpressionParser.parse(), and denoptim.fitness.FitnessExpressionParserTest.testProcessExpressions().
getVariables()
List< Variable > denoptim.fitness.DescriptorForFitness.getVariables ()
Get the variables that make use of values produced by this descriptor.
Returns
the list of variables.
Definition at line 134 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.variables.
Referenced by denoptim.fitness.FitnessProvider.getFitness(), and denoptim.fitness.FitnessExpressionParserTest.testProcessExpressions().
makeCopy()
DescriptorForFitness denoptim.fitness.DescriptorForFitness.makeCopy () throws DENOPTIMException
Copy this descriptor and created an independent instance of the underlying descriptor implementation.
Exceptions
DENOPTIMException
Definition at line 251 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), and denoptim.fitness.DescriptorForFitness.newDescriptorImplementation().
Referenced by denoptim.fitness.FitnessExpressionParser.parse().
newDescriptorImplementation()
static IDescriptor denoptim.fitness.DescriptorForFitness.newDescriptorImplementation (DescriptorForFitness oldParent) throws DENOPTIMException static private
Definition at line 260 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.cdkBuilder, and denoptim.fitness.DescriptorForFitness.className.
Referenced by denoptim.fitness.DescriptorForFitness.makeCopy().
setVariables()
void denoptim.fitness.DescriptorForFitness.setVariables (List< Variable > variables)
Overwrites the list of variables using this descriptor.
Parameters
variables the new list of variable.
Definition at line 123 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.variables.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl().
toString()
String denoptim.fitness.DescriptorForFitness.toString ()
Definition at line 177 of file DescriptorForFitness.java.
References denoptim.fitness.DescriptorForFitness.className, denoptim.fitness.DescriptorForFitness.implementation, denoptim.fitness.DescriptorForFitness.resultId, denoptim.fitness.DescriptorForFitness.shortName, and denoptim.fitness.DescriptorForFitness.variables.
Member Data Documentation
cdkBuilder
IChemObjectBuilder denoptim.fitness.DescriptorForFitness.cdkBuilder static private
Initial value:
=
            DefaultChemObjectBuilder.getInstance()
Utility for constructing CDK objects.
Definition at line 84 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.newDescriptorImplementation().
className
String denoptim.fitness.DescriptorForFitness.className protected
ClassName pointing to the implementation of this descriptor's calculator.
Definition at line 42 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.getClassName(), denoptim.fitness.DescriptorForFitness.newDescriptorImplementation(), and denoptim.fitness.DescriptorForFitness.toString().
dictClasses
String [] denoptim.fitness.DescriptorForFitness.dictClasses protected
The class(es) of descriptor as define in the descriptor dictionary.
Definition at line 69 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.getDictClasses(), and denoptim.fitness.DescriptorForFitness.getDictString().
dictDefinition
String denoptim.fitness.DescriptorForFitness.dictDefinition protected
The Definition of descriptor as define in the descriptor dictionary.
Definition at line 74 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.getDictDefinition(), and denoptim.fitness.DescriptorForFitness.getDictString().
dictTitle
String denoptim.fitness.DescriptorForFitness.dictTitle protected
The title of descriptor as define in the descriptor dictionary.
Definition at line 79 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.getDictString(), and denoptim.fitness.DescriptorForFitness.getDictTitle().
implementation
IDescriptor denoptim.fitness.DescriptorForFitness.implementation protected
Implementation of the descriptor's calculator.
Definition at line 47 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.DescriptorForFitness.getImplementation(), denoptim.fitness.FitnessExpressionParser.parse(), and denoptim.fitness.DescriptorForFitness.toString().
resultId
int denoptim.fitness.DescriptorForFitness.resultId = 0 protected
Pointer to a specific results among those that are produced by the calculation of this descriptor, or 0 for descriptors that produce a single value.
Definition at line 64 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), and denoptim.fitness.DescriptorForFitness.toString().
shortName
String denoptim.fitness.DescriptorForFitness.shortName protected
Descriptor short name.
Definition at line 52 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.DescriptorForFitness(), denoptim.fitness.FitnessProvider.getFitness(), denoptim.fitness.DescriptorForFitness.getShortName(), and denoptim.fitness.DescriptorForFitness.toString().
variables
List<Variable> denoptim.fitness.DescriptorForFitness.variables = new ArrayList<Variable>() protected
Variables that use values calculated by this descriptor.
Definition at line 57 of file DescriptorForFitness.java.
Referenced by denoptim.fitness.DescriptorForFitness.addDependentVariable(), denoptim.fitness.DescriptorForFitness.cloneAllButImpl(), denoptim.fitness.DescriptorForFitness.getVariables(), denoptim.fitness.DescriptorForFitness.setVariables(), and denoptim.fitness.DescriptorForFitness.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fitness/DescriptorForFitness.java