DENOPTIM: denoptim.fitness.descriptors.TanimotoMolSimilarity Class Reference
denoptim.fitness.descriptors.TanimotoMolSimilarity Class Reference
Calculates the molecular similarity against a target compound the fingerprint of which is given as parameter.
Public Member Functions
TanimotoMolSimilarity ()
Constructor for a TanimotoMolSimilarity object.
DescriptorSpecification getSpecification ()
Get the specification attribute of Tanimoto molecular similarity.
String[] getParameterNames ()
Gets the parameterNames attribute of the TanimotoMolSimilarity object.
Object getParameterType (String name)
void setParameters (Object[] params) throws CDKException
Set the parameters attribute of TanimotoMolSimilarity object.
Object[] getParameters ()
String[] getDescriptorNames ()
DescriptorValue calculate (IAtomContainer mol)
IDescriptorResult getDescriptorResultType ()
String getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
Returns
the title
String getDictionaryDefinition ()
Get a string that describes the descriptor in detail.Might contain mathematical formulation.
See also
DescriptorEngine
Returns
the description of this descriptor, possibly containing equations that clarify how it is calculated.
String[] getDictionaryClass ()
Get the classification of this descriptor.A descriptor can belong to one or more classes simultaneously.
Returns
String getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
String getDictionaryDefinition ()
Get a string that describes the descriptor in detail.
String[] getDictionaryClass ()
Get the classification of this descriptor.
Static Public Member Functions
static IFingerprinter makeIFingerprinter (String classShortName) throws CDKException
Private Attributes
IBitFingerprint referenceFingerprint
IFingerprinter fingerprinter
String fingerprinterName = "none"
Static Private Attributes
static final String[] PARAMNAMES
static final String[] NAMES = {"TanimotoSimilarity"}
static IChemObjectBuilder cdkBuilder
Utility for constructing CDK objects.
Detailed Description
Calculates the molecular similarity against a target compound the fingerprint of which is given as parameter.
Definition at line 48 of file TanimotoMolSimilarity.java.
Constructor & Destructor Documentation
TanimotoMolSimilarity()
denoptim.fitness.descriptors.TanimotoMolSimilarity.TanimotoMolSimilarity ()
Constructor for a TanimotoMolSimilarity object.
Definition at line 72 of file TanimotoMolSimilarity.java.
Member Function Documentation
calculate()
DescriptorValue denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate (IAtomContainer mol)
Definition at line 221 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarity.getDescriptorNames(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameterNames(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.referenceFingerprint.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityTest.testTanimotoMolSimilarity().
getDescriptorNames()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarity.getDescriptorNames ()
Definition at line 212 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.NAMES.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate().
getDescriptorResultType()
IDescriptorResult denoptim.fitness.descriptors.TanimotoMolSimilarity.getDescriptorResultType ()
Definition at line 273 of file TanimotoMolSimilarity.java.
getDictionaryClass()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarity.getDictionaryClass ()
Get the classification of this descriptor.A descriptor can belong to one or more classes simultaneously.
Returns
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 308 of file TanimotoMolSimilarity.java.
getDictionaryDefinition()
String denoptim.fitness.descriptors.TanimotoMolSimilarity.getDictionaryDefinition ()
Get a string that describes the descriptor in detail.Might contain mathematical formulation.
See also
DescriptorEngine
Returns
the description of this descriptor, possibly containing equations that clarify how it is calculated.
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 291 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.PARAMNAMES.
getDictionaryTitle()
String denoptim.fitness.descriptors.TanimotoMolSimilarity.getDictionaryTitle ()
Gets the title of this descriptor as it should be in the dictionary.
Returns
the title
Implements denoptim.fitness.IDenoptimDescriptor.
Definition at line 282 of file TanimotoMolSimilarity.java.
getParameterNames()
String[] denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameterNames ()
Gets the parameterNames attribute of the TanimotoMolSimilarity object.
Returns
the parameterNames value
Definition at line 104 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.PARAMNAMES.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate().
getParameters()
Object[] denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameters ()
Definition at line 200 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinterName, and denoptim.fitness.descriptors.TanimotoMolSimilarity.referenceFingerprint.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate().
getParameterType()
Object denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameterType (String name)
Definition at line 112 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.PARAMNAMES.
getSpecification()
DescriptorSpecification denoptim.fitness.descriptors.TanimotoMolSimilarity.getSpecification ()
Get the specification attribute of Tanimoto molecular similarity.
Given the dependency on the fingerpringer and reference fingerprint, the implementation identifier is made dependent on those two parameters. Consequently resetting the parameter with two new instances of the fingerpringer and reference fingerprint (even is effectively equal) will result in two different DescriptorSpecification objects.
Returns
the specification of this descriptor.
Definition at line 86 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinterName, and denoptim.fitness.descriptors.TanimotoMolSimilarity.referenceFingerprint.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate().
makeIFingerprinter()
static IFingerprinter denoptim.fitness.descriptors.TanimotoMolSimilarity.makeIFingerprinter (String classShortName) throws CDKException static
Definition at line 162 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.cdkBuilder.
Referenced by denoptim.fitness.FitnessExpressionParser.makeIFingerprinter(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.setParameters().
setParameters()
void denoptim.fitness.descriptors.TanimotoMolSimilarity.setParameters (Object[] params) throws CDKException
Set the parameters attribute of TanimotoMolSimilarity object.
The descriptor takes two parameters: the class name of the fingerprinter used to generate the fingerprints (e.g., org.openscience.cdk.fingerprint.PubchemFingerprinter), and the fingerprint against which we want to calculate similarity.
Parameters
params the array of parameters
Definition at line 134 of file TanimotoMolSimilarity.java.
References denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinter, denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinterName, denoptim.fitness.descriptors.TanimotoMolSimilarity.makeIFingerprinter(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.referenceFingerprint.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarityTest.testTanimotoMolSimilarity().
Member Data Documentation
cdkBuilder
IChemObjectBuilder denoptim.fitness.descriptors.TanimotoMolSimilarity.cdkBuilder static private
Initial value:
=
            DefaultChemObjectBuilder.getInstance()
Utility for constructing CDK objects.
Definition at line 64 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.makeIFingerprinter().
fingerprinter
IFingerprinter denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinter private
Definition at line 54 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.setParameters().
fingerprinterName
String denoptim.fitness.descriptors.TanimotoMolSimilarity.fingerprinterName = "none" private
Definition at line 55 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.setParameters().
NAMES
final String [] denoptim.fitness.descriptors.TanimotoMolSimilarity.NAMES = {"TanimotoSimilarity"} static private
Definition at line 59 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.getDescriptorNames().
PARAMNAMES
final String [] denoptim.fitness.descriptors.TanimotoMolSimilarity.PARAMNAMES static private
Initial value:
= new String[] {
            "fingerprinterImplementation","referenceFingerprint"}
Definition at line 56 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.getDictionaryDefinition(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameterNames(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameterType().
referenceFingerprint
IBitFingerprint denoptim.fitness.descriptors.TanimotoMolSimilarity.referenceFingerprint private
Definition at line 53 of file TanimotoMolSimilarity.java.
Referenced by denoptim.fitness.descriptors.TanimotoMolSimilarity.calculate(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getParameters(), denoptim.fitness.descriptors.TanimotoMolSimilarity.getSpecification(), and denoptim.fitness.descriptors.TanimotoMolSimilarity.setParameters().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/fitness/descriptors/TanimotoMolSimilarity.java