DENOPTIM: denoptim.ga.ExternalCmdsListener Class Reference
denoptim.ga.ExternalCmdsListener Class Reference
Service that watches the interface folder (i.e., see GAParameters#interfaceDir) for instructions coming from outside the JVM.
Public Member Functions
ExternalCmdsListener (Path pathname, Logger logger) throws IOException
void run ()
Starts listening for events and keeps listening in its own thread.
void closeWatcher () throws IOException
void setReferenceToRunningEAlgorithm (EvolutionaryAlgorithm ea)
Private Member Functions
void processExternalCmdFile (File file)
Private Attributes
final Path pathname
final WatchService watcher
final WatchKey key
EvolutionaryAlgorithm ea
boolean intendedStop = false
Flag signaling that we are intentionally interrupting the service.
final String NL = System.getProperty("line.separator")
Logger logger = null
Program-specific logger.
Detailed Description
Service that watches the interface folder (i.e., see GAParameters#interfaceDir) for instructions coming from outside the JVM.
The instructions are given as files in the interface folder.
Author
Marco Foscato
Definition at line 53 of file ExternalCmdsListener.java.
Constructor & Destructor Documentation
ExternalCmdsListener()
denoptim.ga.ExternalCmdsListener.ExternalCmdsListener (Path pathname, Logger logger) throws IOException
Definition at line 75 of file ExternalCmdsListener.java.
References denoptim.ga.ExternalCmdsListener.logger, denoptim.ga.ExternalCmdsListener.pathname, and denoptim.ga.ExternalCmdsListener.watcher.
Member Function Documentation
closeWatcher()
void denoptim.ga.ExternalCmdsListener.closeWatcher () throws IOException
Definition at line 221 of file ExternalCmdsListener.java.
References denoptim.ga.ExternalCmdsListener.intendedStop.
Referenced by denoptim.programs.denovo.GARunner.stopExternalCmdListener().
processExternalCmdFile()
void denoptim.ga.ExternalCmdsListener.processExternalCmdFile (File file) private
Definition at line 153 of file ExternalCmdsListener.java.
References denoptim.ga.EvolutionaryAlgorithm.addCandidates(), denoptim.ga.ExternalCmdsListener.ea, denoptim.ga.ExternalCmdsListener.logger, denoptim.ga.ExternalCmdsListener.NL, denoptim.io.DenoptimIO.readList(), denoptim.ga.EvolutionaryAlgorithm.removeCandidates(), and denoptim.ga.EvolutionaryAlgorithm.stopRun().
Referenced by denoptim.ga.ExternalCmdsListener.run().
run()
void denoptim.ga.ExternalCmdsListener.run ()
Starts listening for events and keeps listening in its own thread.
Definition at line 91 of file ExternalCmdsListener.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.exception.ExceptionUtils.getStackTraceAsString(), denoptim.ga.ExternalCmdsListener.intendedStop, denoptim.ga.ExternalCmdsListener.key, denoptim.ga.ExternalCmdsListener.logger, denoptim.ga.ExternalCmdsListener.pathname, denoptim.ga.ExternalCmdsListener.processExternalCmdFile(), and denoptim.ga.ExternalCmdsListener.watcher.
setReferenceToRunningEAlgorithm()
void denoptim.ga.ExternalCmdsListener.setReferenceToRunningEAlgorithm (EvolutionaryAlgorithm ea)
Definition at line 229 of file ExternalCmdsListener.java.
References denoptim.ga.ExternalCmdsListener.ea.
Referenced by denoptim.ga.EvolutionaryAlgorithm.run().
Member Data Documentation
ea
EvolutionaryAlgorithm denoptim.ga.ExternalCmdsListener.ea private
Definition at line 59 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.processExternalCmdFile(), and denoptim.ga.ExternalCmdsListener.setReferenceToRunningEAlgorithm().
intendedStop
boolean denoptim.ga.ExternalCmdsListener.intendedStop = false private
Flag signaling that we are intentionally interrupting the service.
Definition at line 64 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.closeWatcher(), and denoptim.ga.ExternalCmdsListener.run().
key
final WatchKey denoptim.ga.ExternalCmdsListener.key private
Definition at line 58 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.run().
logger
Logger denoptim.ga.ExternalCmdsListener.logger = null private
Program-specific logger.
Definition at line 71 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.ExternalCmdsListener(), denoptim.ga.ExternalCmdsListener.processExternalCmdFile(), and denoptim.ga.ExternalCmdsListener.run().
NL
final String denoptim.ga.ExternalCmdsListener.NL = System.getProperty("line.separator") private
Definition at line 66 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.processExternalCmdFile().
pathname
final Path denoptim.ga.ExternalCmdsListener.pathname private
Definition at line 56 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.ExternalCmdsListener(), and denoptim.ga.ExternalCmdsListener.run().
watcher
final WatchService denoptim.ga.ExternalCmdsListener.watcher private
Definition at line 57 of file ExternalCmdsListener.java.
Referenced by denoptim.ga.ExternalCmdsListener.ExternalCmdsListener(), and denoptim.ga.ExternalCmdsListener.run().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/ga/ExternalCmdsListener.java