DENOPTIM: denoptim.graph.VertexTest Class Reference
denoptim.graph.VertexTest Class Reference
Unit test for DENOPTIMVertex.
Public Member Functions
void testFromToJSON_minimal () throws Exception
void testFromToJSON_withSymmetricAPs () throws Exception
void testSameAs_Equal ()
void testSameAs_DiffAPNum ()
void testClone () throws Exception
void testGetMutationSites () throws Exception
void testGetAPsWithAPClassStartingWith () throws Exception
void testIsConnectedToAromaticBridge () throws Exception
Private Attributes
StringBuilder reason = new StringBuilder()
Detailed Description
Unit test for DENOPTIMVertex.
Author
Marco Foscato
Definition at line 48 of file VertexTest.java.
Member Function Documentation
testClone()
void denoptim.graph.VertexTest.testClone () throws Exception
Definition at line 163 of file VertexTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Fragment.addAPOnAtom(), denoptim.graph.Fragment.addAtom(), denoptim.graph.Fragment.addBond(), denoptim.graph.EmptyVertex.clone(), denoptim.graph.Fragment.clone(), denoptim.graph.Vertex.getAllAPClasses(), denoptim.graph.EmptyVertex.getNumberOfAPs(), denoptim.graph.Vertex.getNumberOfAPs(), denoptim.graph.Vertex.getProperty(), denoptim.graph.EmptyVertex.getSymmetricAPSets(), denoptim.graph.Fragment.getSymmetricAPSets(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.Vertex.getVertexId(), denoptim.graph.Vertex.isRCV, denoptim.graph.APClass.make(), and denoptim.graph.Vertex.setProperty().
testFromToJSON_minimal()
void denoptim.graph.VertexTest.testFromToJSON_minimal () throws Exception
Definition at line 55 of file VertexTest.java.
References denoptim.graph.Vertex.VertexType.EmptyVertex, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.fromJson(), denoptim.graph.Vertex.VertexType.MolecularFragment, denoptim.graph.Vertex.VertexType.Template, denoptim.graph.EmptyVertex.toJson(), denoptim.graph.Fragment.toJson(), denoptim.graph.Template.toJson(), and denoptim.graph.Vertex.vertexType.
testFromToJSON_withSymmetricAPs()
void denoptim.graph.VertexTest.testFromToJSON_withSymmetricAPs () throws Exception
Definition at line 79 of file VertexTest.java.
References denoptim.graph.SymmetricSet< T >.add(), denoptim.graph.EmptyVertex.addAP(), denoptim.graph.EmptyVertex.addSymmetricAPSet(), denoptim.graph.Vertex.fromJson(), denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.getSymmetricAPSets(), denoptim.graph.APClass.make(), and denoptim.graph.EmptyVertex.toJson().
testGetAPsWithAPClassStartingWith()
void denoptim.graph.VertexTest.testGetAPsWithAPClassStartingWith () throws Exception
Definition at line 246 of file VertexTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.Vertex.getAPsWithAPClassStartingWith(), and denoptim.graph.APClass.make().
testGetMutationSites()
void denoptim.graph.VertexTest.testGetMutationSites () throws Exception
Definition at line 217 of file VertexTest.java.
References denoptim.graph.Vertex.BBType.CAP, denoptim.utils.MutationType.EXTEND, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getMutationSites(), denoptim.graph.Vertex.BBType.NONE, denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setMutationTypes(), and denoptim.graph.Vertex.BBType.UNDEFINED.
testIsConnectedToAromaticBridge()
void denoptim.graph.VertexTest.testIsConnectedToAromaticBridge () throws Exception
Definition at line 267 of file VertexTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.graph.APClass.APCAROMBRIDGE2EL, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getPolarizedRCV(), denoptim.graph.Vertex.isAromaticBridge(), denoptim.graph.Vertex.isConnectedToAromaticBridge(), and denoptim.graph.APClass.make().
testSameAs_DiffAPNum()
void denoptim.graph.VertexTest.testSameAs_DiffAPNum ()
Definition at line 143 of file VertexTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.VertexTest.reason, and denoptim.graph.EmptyVertex.sameAs().
testSameAs_Equal()
void denoptim.graph.VertexTest.testSameAs_Equal ()
Definition at line 110 of file VertexTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.VertexTest.reason, denoptim.graph.EmptyVertex.sameAs(), denoptim.graph.Vertex.setProperty(), and denoptim.graph.Vertex.setUniquefyingProperty().
Member Data Documentation
reason
StringBuilder denoptim.graph.VertexTest.reason = new StringBuilder() private
Definition at line 50 of file VertexTest.java.
Referenced by denoptim.graph.VertexTest.testSameAs_DiffAPNum(), and denoptim.graph.VertexTest.testSameAs_Equal().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/graph/VertexTest.java