DENOPTIM: denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine Class Reference
denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine Class Reference
Single line in the list of APClass compatibility rules.
Public Member Functions
CompatibilityRuleLine (APClass srcAPClass)
void clearMatches ()
int renderIfMatches (String regex)
Checks if there is any component matching the regex query and returns the number of matches.
void renderdAsSelected (boolean selected)
void mouseClicked (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent e)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
Private Attributes
JTextField srcClassName
JScrollPane srcClassNameScroller
JPanel trgClassesPanel
JScrollPane trgClassesScroller
JButton btnAdd
TrgRemovalListener trgDelListener
APClass srcAPClass
boolean isSelected = false
final Dimension minSrcAPClassName = new Dimension(200,26)
final Dimension scrollerSize = new Dimension(300,41)
final Color SELECTEDBACKGROUND = Color.BLUE
final Color DEFAULTBACKGROUND
Static Private Attributes
static final long serialVersionUID = -5007017502551954331L
Version UID.
Detailed Description
Single line in the list of APClass compatibility rules.
Definition at line 1394 of file CompatibilityMatrixForm.java.
Constructor & Destructor Documentation
CompatibilityRuleLine()
denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine (APClass srcAPClass)
Definition at line 1421 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.allAPClasses, denoptim.gui.CompatibilityMatrixForm.allAPRules, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.btnAdd, denoptim.gui.CompatibilityMatrixForm.compatMap, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.DEFAULTBACKGROUND, denoptim.graph.APClass.getRule(), denoptim.graph.APClass.make(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.minSrcAPClassName, denoptim.gui.CompatibilityMatrixForm.REMOVETRGAPC, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.scrollerSize, denoptim.gui.GUIModalDialog.showDialog(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcAPClass, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcClassName, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcClassNameScroller, denoptim.graph.APClass.toString(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesPanel, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesScroller, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgDelListener, and denoptim.gui.CompatibilityMatrixForm.updateAPClassCompatibilitiesList().
Member Function Documentation
clearMatches()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.clearMatches ()
Definition at line 1561 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.isSelected, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesPanel.
mouseClicked()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseClicked (MouseEvent e)
Definition at line 1635 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.isSelected, and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected().
mouseEntered()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseEntered (MouseEvent e)
Definition at line 1653 of file CompatibilityMatrixForm.java.
mouseExited()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseExited (MouseEvent e)
Definition at line 1656 of file CompatibilityMatrixForm.java.
mousePressed()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mousePressed (MouseEvent e)
Definition at line 1647 of file CompatibilityMatrixForm.java.
mouseReleased()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseReleased (MouseEvent e)
Definition at line 1650 of file CompatibilityMatrixForm.java.
renderdAsSelected()
void denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected (boolean selected)
Definition at line 1618 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.DEFAULTBACKGROUND, denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.SELECTEDBACKGROUND, and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcClassName.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.clearMatches(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseClicked(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
renderIfMatches()
int denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches (String regex)
Checks if there is any component matching the regex query and returns the number of matches.
Parameters
regex
Returns
the number of matches
Definition at line 1582 of file CompatibilityMatrixForm.java.
References denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.isSelected, denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.matchesAPClass(), denoptim.gui.CompatibilityMatrixForm.TargetAPClassToken.renderAsSelected(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcAPClass, denoptim.graph.APClass.toString(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesPanel.
Referenced by denoptim.gui.CompatibilityMatrixForm.searchAPClass().
Member Data Documentation
btnAdd
JButton denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.btnAdd private
Definition at line 1405 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
DEFAULTBACKGROUND
final Color denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.DEFAULTBACKGROUND private
Initial value:
=
            UIManager.getLookAndFeelDefaults().getColor("Panel.background")
Definition at line 1415 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected().
isSelected
boolean denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.isSelected = false private
Definition at line 1410 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.clearMatches(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.mouseClicked(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
minSrcAPClassName
final Dimension denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.minSrcAPClassName = new Dimension(200,26) private
Definition at line 1412 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
scrollerSize
final Dimension denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.scrollerSize = new Dimension(300,41) private
Definition at line 1413 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
SELECTEDBACKGROUND
final Color denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.SELECTEDBACKGROUND = Color.BLUE private
Definition at line 1414 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected().
serialVersionUID
final long denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.serialVersionUID = -5007017502551954331L static private
Version UID.
Definition at line 1399 of file CompatibilityMatrixForm.java.
srcAPClass
APClass denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcAPClass private
Definition at line 1408 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
srcClassName
JTextField denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcClassName private
Definition at line 1401 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderdAsSelected().
srcClassNameScroller
JScrollPane denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.srcClassNameScroller private
Definition at line 1402 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
trgClassesPanel
JPanel denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesPanel private
Definition at line 1403 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.clearMatches(), denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine(), and denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.renderIfMatches().
trgClassesScroller
JScrollPane denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgClassesScroller private
Definition at line 1404 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
trgDelListener
TrgRemovalListener denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.trgDelListener private
Definition at line 1406 of file CompatibilityMatrixForm.java.
Referenced by denoptim.gui.CompatibilityMatrixForm.CompatibilityRuleLine.CompatibilityRuleLine().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/CompatibilityMatrixForm.java