DENOPTIM: denoptim.gui.VertexAsTwoDimStructureViewPanel Class Reference
denoptim.gui.VertexAsTwoDimStructureViewPanel Class Reference
A panel to visualize a vertex as two-dimensional chemical structure with attachment point table.
Classes
class AtomOrAPGenerator
class PausableTableModelListener
class TwoDimStructurePanel
Panel dealing with the painting of 2D chemical representation.
Public Member Functions
VertexAsTwoDimStructureViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
VertexAsTwoDimStructureViewPanel (boolean editableTable, int dividerPosition)
Constructor that allows to specify whether the AP table is editable or not.
void setVertexSpecificEditableAPTable (boolean editable)
void loadVertexToViewer (Vertex v)
boolean hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
void deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
void clearAll ()
Removes the currently visualized molecule and AP table.
void clearAPTable ()
Clears the table of attachment points.
ArrayList< AttachmentPoint > getSelectedAPs ()
Identifies which attachment points are selected in the visualized table.
ArrayList< Integer > getSelectedAPIDs ()
Identifies which attachment points are selected in the visualized table.
void activateTabEditsListener (boolean var)
Allows to activate and deactivate the listener.
Map< Integer, AttachmentPoint > getMapOfAPsInTable ()
DefaultTableModel getAPTableModel ()
ArrayList< Integer > getSelectedAPIDs ()
Map< Integer, AttachmentPoint > getMapOfAPsInTable ()
DefaultTableModel getAPTableModel ()
Public Attributes
boolean alteredAPData = false
Flag signaling that data about APs has been changed in the GUI.
Public Attributes inherited from denoptim.gui.IVertexAPSelection
final String APDATACHANGEEVENT = "APDATA"
Protected Attributes
Map< Integer, AttachmentPoint > mapAPs = null
Temporary list of attachment points of the current fragment.
DefaultTableModel apTabModel
JTable apTable
Private Member Functions
void initialize (int dividerPosition)
void loadVertexStructure ()
void clearPanel ()
trashed the current panel displaying any 2D structure and replaces it with a new empty panel.
void updateAPsMapAndTable ()
Uses the AP of the Fragment to create a new map and table of APs.
void preSelectAPs ()
Private Attributes
Vertex vertex
The currently loaded fragment.
JScrollPane viewPanel
JPanel twoDimView
JScrollPane tabPanel
boolean editableAPTable = false
boolean vertexSpecificAPTabEditable = true
Static Private Attributes
static final long serialVersionUID = 1L
Version UID.
Detailed Description
A panel to visualize a vertex as two-dimensional chemical structure with attachment point table.
Author
Marco Foscato
Definition at line 79 of file VertexAsTwoDimStructureViewPanel.java.
Constructor & Destructor Documentation
VertexAsTwoDimStructureViewPanel() [1/2]
denoptim.gui.VertexAsTwoDimStructureViewPanel.VertexAsTwoDimStructureViewPanel (boolean editableTable)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
editableTable use true to make the AP table editable
Definition at line 328 of file VertexAsTwoDimStructureViewPanel.java.
VertexAsTwoDimStructureViewPanel() [2/2]
denoptim.gui.VertexAsTwoDimStructureViewPanel.VertexAsTwoDimStructureViewPanel (boolean editableTable, int dividerPosition)
Constructor that allows to specify whether the AP table is editable or not.
Parameters
parent the parent component.
editableTable use true to make the AP table editable
dividerPosition allows to set the initial position of the divide
Definition at line 342 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.editableAPTable, and denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize().
Member Function Documentation
activateTabEditsListener()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.activateTabEditsListener (boolean var)
Allows to activate and deactivate the listener.
Parameters
var use true to activate the listener
Definition at line 608 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel, and denoptim.gui.VertexAsTwoDimStructureViewPanel.PausableTableModelListener.setActive().
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable(), denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
clearAll()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAll ()
Removes the currently visualized molecule and AP table.
Definition at line 519 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable().
clearAPTable()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable ()
Clears the table of attachment points.
Definition at line 529 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.activateTabEditsListener(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAll(), denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
clearPanel()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.clearPanel () private
trashed the current panel displaying any 2D structure and replaces it with a new empty panel.
Definition at line 432 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.twoDimView, and denoptim.gui.VertexAsTwoDimStructureViewPanel.viewPanel.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexStructure().
deprotectEdits()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.deprotectEdits ()
Overrides the flag signaling unsaved edits to saying that there are no altered data.
Definition at line 457 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.alteredAPData.
getAPTableModel()
DefaultTableModel denoptim.gui.VertexAsTwoDimStructureViewPanel.getAPTableModel ()
Implements denoptim.gui.IVertexAPSelection.
Definition at line 633 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel.
getMapOfAPsInTable()
Map< Integer, AttachmentPoint > denoptim.gui.VertexAsTwoDimStructureViewPanel.getMapOfAPsInTable ()
Implements denoptim.gui.IVertexAPSelection.
Definition at line 625 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.mapAPs.
getSelectedAPIDs()
ArrayList< Integer > denoptim.gui.VertexAsTwoDimStructureViewPanel.getSelectedAPIDs ()
Identifies which attachment points are selected in the visualized table.
Returns
the list of attachment points indexes
Implements denoptim.gui.IVertexAPSelection.
Definition at line 565 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.apTable.
getSelectedAPs()
ArrayList< AttachmentPoint > denoptim.gui.VertexAsTwoDimStructureViewPanel.getSelectedAPs ()
Identifies which attachment points are selected in the visualized table.
Returns
the list of attachment points
Definition at line 547 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.apTable, and denoptim.gui.VertexAsTwoDimStructureViewPanel.mapAPs.
hasUnsavedAPEdits()
boolean denoptim.gui.VertexAsTwoDimStructureViewPanel.hasUnsavedAPEdits ()
Check for unsaved edits to the AP data.
Returns
true if there are unsaved edits
Definition at line 446 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.alteredAPData.
initialize()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize (int dividerPosition) private
Definition at line 352 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.apTable, denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel, denoptim.gui.VertexAsTwoDimStructureViewPanel.clearPanel(), denoptim.gui.VertexAsTwoDimStructureViewPanel.editableAPTable, denoptim.gui.VertexAsTwoDimStructureViewPanel.tabPanel, and denoptim.gui.VertexAsTwoDimStructureViewPanel.vertexSpecificAPTabEditable.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.VertexAsTwoDimStructureViewPanel().
loadVertexStructure()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexStructure () private
Definition at line 416 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.clearPanel(), denoptim.gui.VertexAsTwoDimStructureViewPanel.twoDimView, and denoptim.gui.VertexAsTwoDimStructureViewPanel.vertex.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer().
loadVertexToViewer()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer (Vertex v)
Definition at line 401 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable(), denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexStructure(), denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs(), denoptim.gui.VertexAsTwoDimStructureViewPanel.setVertexSpecificEditableAPTable(), denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.vertex.
Referenced by denoptim.gui.VertexViewPanel.loadFragmentToViewer().
preSelectAPs()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs () private
Definition at line 492 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.activateTabEditsListener(), denoptim.gui.VertexAsTwoDimStructureViewPanel.apTable, denoptim.graph.Vertex.getProperty(), denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELD, denoptim.gui.GUIVertexSelector.PRESELECTEDAPSFIELDSEP, and denoptim.gui.VertexAsTwoDimStructureViewPanel.vertex.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer().
setVertexSpecificEditableAPTable()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.setVertexSpecificEditableAPTable (boolean editable)
Definition at line 394 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.vertexSpecificAPTabEditable.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer().
updateAPsMapAndTable()
void denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable () private
Uses the AP of the Fragment to create a new map and table of APs.
Definition at line 468 of file VertexAsTwoDimStructureViewPanel.java.
References denoptim.gui.VertexAsTwoDimStructureViewPanel.activateTabEditsListener(), denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel, denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable(), denoptim.graph.Vertex.getAttachmentPoints(), denoptim.gui.VertexAsTwoDimStructureViewPanel.mapAPs, and denoptim.gui.VertexAsTwoDimStructureViewPanel.vertex.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer().
Member Data Documentation
alteredAPData
boolean denoptim.gui.VertexAsTwoDimStructureViewPanel.alteredAPData = false
Flag signaling that data about APs has been changed in the GUI.
Definition at line 100 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.deprotectEdits(), denoptim.gui.VertexAsTwoDimStructureViewPanel.hasUnsavedAPEdits(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.PausableTableModelListener.tableChanged().
apTable
JTable denoptim.gui.VertexAsTwoDimStructureViewPanel.apTable protected
Definition at line 106 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.getSelectedAPIDs(), denoptim.gui.VertexAsTwoDimStructureViewPanel.getSelectedAPs(), denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs().
apTabModel
DefaultTableModel denoptim.gui.VertexAsTwoDimStructureViewPanel.apTabModel protected
Definition at line 105 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.activateTabEditsListener(), denoptim.gui.VertexAsTwoDimStructureViewPanel.clearAPTable(), denoptim.gui.VertexAsTwoDimStructureViewPanel.getAPTableModel(), denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
editableAPTable
boolean denoptim.gui.VertexAsTwoDimStructureViewPanel.editableAPTable = false private
Definition at line 109 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.VertexAsTwoDimStructureViewPanel().
mapAPs
Map<Integer, AttachmentPoint> denoptim.gui.VertexAsTwoDimStructureViewPanel.mapAPs = null protected
Temporary list of attachment points of the current fragment.
Definition at line 95 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.getMapOfAPsInTable(), denoptim.gui.VertexAsTwoDimStructureViewPanel.getSelectedAPs(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
serialVersionUID
final long denoptim.gui.VertexAsTwoDimStructureViewPanel.serialVersionUID = 1L static private
Version UID.
Definition at line 85 of file VertexAsTwoDimStructureViewPanel.java.
tabPanel
JScrollPane denoptim.gui.VertexAsTwoDimStructureViewPanel.tabPanel private
Definition at line 104 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize().
twoDimView
JPanel denoptim.gui.VertexAsTwoDimStructureViewPanel.twoDimView private
Definition at line 103 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.clearPanel(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexStructure().
vertex
Vertex denoptim.gui.VertexAsTwoDimStructureViewPanel.vertex private
The currently loaded fragment.
Definition at line 90 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexStructure(), denoptim.gui.VertexAsTwoDimStructureViewPanel.loadVertexToViewer(), denoptim.gui.VertexAsTwoDimStructureViewPanel.preSelectAPs(), denoptim.gui.VertexAsTwoDimStructureViewPanel.TwoDimStructurePanel.TwoDimStructurePanel(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.updateAPsMapAndTable().
vertexSpecificAPTabEditable
boolean denoptim.gui.VertexAsTwoDimStructureViewPanel.vertexSpecificAPTabEditable = true private
Definition at line 112 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.initialize(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.setVertexSpecificEditableAPTable().
viewPanel
JScrollPane denoptim.gui.VertexAsTwoDimStructureViewPanel.viewPanel private
Definition at line 102 of file VertexAsTwoDimStructureViewPanel.java.
Referenced by denoptim.gui.VertexAsTwoDimStructureViewPanel.clearPanel().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/VertexAsTwoDimStructureViewPanel.java