DENOPTIM: denoptim.task.StaticTaskManager Class Reference
denoptim.task.StaticTaskManager Class Reference
Manager for tasks submitted by the GUI.
Classes
class ShutDownHook
Shutdown hook that stops all child tasks upon shutdown of JavaVM.
Static Public Member Functions
static StaticTaskManager getInstance ()
Gets the singleton instance of this class.
static void addTodoTask ()
static void addTodoTasks (int addedTasksCount)
static void subtractDoneTask ()
static void subtractDoneTasks (int doneTasksCount)
static String getQueueSnapshot ()
static void submitAndWait (Task task) throws InterruptedException, ExecutionException
Submits a task and waits for completion.
static void submit (Task task)
static void stop (Task task)
static void stopAll ()
static boolean hasActive ()
static void setLinkToProgressBar (JProgressBar bar)
Adds a reference to the given progress bar.
Static Public Attributes
static int valProgressBar = 1
Value indicated in the progress bar of the GUI.
static int maxProgressBar = 1
Queue max indicator for progress bar in GUI.
static JProgressBar queueStatusBar = null
Reference to progress bar in GUI.
static final String PROGRESSBARUPDATE = "UPDATE-PROGRESS-BAR"
Property change fired to indicate the need to update progress bar.
Private Member Functions
StaticTaskManager ()
Static Private Attributes
static final StaticTaskManager instance = new StaticTaskManager()
The only, static instance of this class.
static ThreadPoolExecutor tpe
The executor of threads.
static Map< Task, Future<?> > subToFutureMap
Maps the relation between a task that is submitted and its future handle.
static final int maxParallelPrograms = 4
Maximum number of denoptim ProgramTasks that can be run in parallel.
static final int queueSize = 10
Queue size.
static final Object LOCK = new Object()
Synchronisation lock for queue progress bar.
Detailed Description
Manager for tasks submitted by the GUI.
The main purpose is to launch and manage calls placed upon requests coming from the GUI and aimed at running DENOPTIM's main classes in GARunner and FragSpaceExplorer.
Author
Marco Foscato
Definition at line 44 of file StaticTaskManager.java.
Constructor & Destructor Documentation
StaticTaskManager()
denoptim.task.StaticTaskManager.StaticTaskManager () private
Definition at line 100 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.maxParallelPrograms, denoptim.task.StaticTaskManager.queueSize, and denoptim.task.StaticTaskManager.tpe.
Member Function Documentation
addTodoTask()
static void denoptim.task.StaticTaskManager.addTodoTask () static
Definition at line 178 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.addTodoTasks().
Referenced by denoptim.task.StaticTaskManager.submit().
addTodoTasks()
static void denoptim.task.StaticTaskManager.addTodoTasks (int addedTasksCount) static
Definition at line 185 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.LOCK, denoptim.task.StaticTaskManager.maxProgressBar, denoptim.task.StaticTaskManager.queueStatusBar, and denoptim.task.StaticTaskManager.valProgressBar.
Referenced by denoptim.task.StaticTaskManager.addTodoTask().
getInstance()
static StaticTaskManager denoptim.task.StaticTaskManager.getInstance () static
Gets the singleton instance of this class.
Returns
Definition at line 171 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.instance.
Referenced by denoptim.main.Main.main().
getQueueSnapshot()
static String denoptim.task.StaticTaskManager.getQueueSnapshot () static
Returns
a string with HTML code, but no html head/tail tags. This string is meant to be inserted in a larger string with head/tail tags.
Definition at line 243 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.tpe.
Referenced by denoptim.gui.GUIPrepare.initialize().
hasActive()
static boolean denoptim.task.StaticTaskManager.hasActive () static
Definition at line 302 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.tpe.
Referenced by denoptim.gui.GUI.closeIfAllSaved().
setLinkToProgressBar()
static void denoptim.task.StaticTaskManager.setLinkToProgressBar (JProgressBar bar) static
Adds a reference to the given progress bar.
This to enable the task manager to report queue status.
Parameters
bar
Definition at line 314 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.queueStatusBar.
Referenced by denoptim.gui.MainToolBar.initialize().
stop()
static void denoptim.task.StaticTaskManager.stop (Task task) static
Definition at line 278 of file StaticTaskManager.java.
References denoptim.task.Task.stopTask(), and denoptim.task.StaticTaskManager.subToFutureMap.
stopAll()
static void denoptim.task.StaticTaskManager.stopAll () static
Definition at line 290 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.subToFutureMap.
Referenced by denoptim.gui.GUI.closeIfAllSaved(), denoptim.task.StaticTaskManager.ShutDownHook.run(), and denoptim.main.Main.terminate().
submit()
static void denoptim.task.StaticTaskManager.submit (Task task) static
Definition at line 268 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.addTodoTask(), denoptim.task.Task.setNotify(), denoptim.task.StaticTaskManager.subToFutureMap, and denoptim.task.StaticTaskManager.tpe.
Referenced by denoptim.gui.GUIPrepare.initialize().
submitAndWait()
static void denoptim.task.StaticTaskManager.submitAndWait (Task task) throws InterruptedException, ExecutionException static
Submits a task and waits for completion.
Parameters
task the task to submit.
Exceptions
ExecutionException
InterruptedException
Definition at line 260 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.tpe.
Referenced by denoptim.main.Main.runProgramTask().
subtractDoneTask()
static void denoptim.task.StaticTaskManager.subtractDoneTask () static
Definition at line 211 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.subtractDoneTasks().
Referenced by denoptim.task.ProgramTask.call(), and denoptim.task.Task.stopTask().
subtractDoneTasks()
static void denoptim.task.StaticTaskManager.subtractDoneTasks (int doneTasksCount) static
Definition at line 218 of file StaticTaskManager.java.
References denoptim.task.StaticTaskManager.LOCK, denoptim.task.StaticTaskManager.maxProgressBar, denoptim.task.StaticTaskManager.queueStatusBar, and denoptim.task.StaticTaskManager.valProgressBar.
Referenced by denoptim.task.StaticTaskManager.subtractDoneTask().
Member Data Documentation
instance
final StaticTaskManager denoptim.task.StaticTaskManager.instance = new StaticTaskManager() static private
The only, static instance of this class.
Definition at line 49 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.getInstance().
LOCK
final Object denoptim.task.StaticTaskManager.LOCK = new Object() static private
Synchronisation lock for queue progress bar.
Definition at line 96 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.addTodoTasks(), and denoptim.task.StaticTaskManager.subtractDoneTasks().
maxParallelPrograms
final int denoptim.task.StaticTaskManager.maxParallelPrograms = 4 static private
Maximum number of denoptim ProgramTasks that can be run in parallel.
Definition at line 66 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.StaticTaskManager().
maxProgressBar
int denoptim.task.StaticTaskManager.maxProgressBar = 1 static
Queue max indicator for progress bar in GUI.
Definition at line 81 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.addTodoTasks(), and denoptim.task.StaticTaskManager.subtractDoneTasks().
PROGRESSBARUPDATE
final String denoptim.task.StaticTaskManager.PROGRESSBARUPDATE = "UPDATE-PROGRESS-BAR" static
Property change fired to indicate the need to update progress bar.
Definition at line 91 of file StaticTaskManager.java.
queueSize
final int denoptim.task.StaticTaskManager.queueSize = 10 static private
Queue size.
Definition at line 71 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.StaticTaskManager().
queueStatusBar
JProgressBar denoptim.task.StaticTaskManager.queueStatusBar = null static
Reference to progress bar in GUI.
Null when we start.
Definition at line 86 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.addTodoTasks(), denoptim.gui.GUI.run(), denoptim.task.StaticTaskManager.setLinkToProgressBar(), and denoptim.task.StaticTaskManager.subtractDoneTasks().
subToFutureMap
Map<Task,Future<?> > denoptim.task.StaticTaskManager.subToFutureMap static private
Initial value:
=
            new HashMap<Task,Future<?>>()
Maps the relation between a task that is submitted and its future handle.
Definition at line 59 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.ShutDownHook.run(), denoptim.task.StaticTaskManager.stop(), denoptim.task.StaticTaskManager.stopAll(), and denoptim.task.StaticTaskManager.submit().
tpe
ThreadPoolExecutor denoptim.task.StaticTaskManager.tpe static private
The executor of threads.
Definition at line 54 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.getQueueSnapshot(), denoptim.task.StaticTaskManager.hasActive(), denoptim.task.StaticTaskManager.ShutDownHook.run(), denoptim.task.StaticTaskManager.StaticTaskManager(), denoptim.task.StaticTaskManager.submit(), and denoptim.task.StaticTaskManager.submitAndWait().
valProgressBar
int denoptim.task.StaticTaskManager.valProgressBar = 1 static
Value indicated in the progress bar of the GUI.
Definition at line 76 of file StaticTaskManager.java.
Referenced by denoptim.task.StaticTaskManager.addTodoTasks(), and denoptim.task.StaticTaskManager.subtractDoneTasks().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/task/StaticTaskManager.java