DENOPTIM: denoptim.graph.rings.RingClosureFinder Class Reference
denoptim.graph.rings.RingClosureFinder Class Reference
Tool to explore the conformational space of chains of atoms and identify ring closing conformations.
Static Public Member Functions
static boolean evaluateClosability (List< IAtom > path, ArrayList< Boolean > rotatability, ArrayList< ArrayList< Point3d > > dihRefs, ArrayList< ArrayList< Double > > closableConfs, RingClosureParameters settings)
Giving a list of points in 3D space (the path) this method evaluates whether it exists at least one conformation of the chain that allows to form ring by connecting the head and the tail of the chain.
static boolean hasClosableRotamer (List< Point3d > chain, ArrayList< Boolean > rotatability, ArrayList< Double > dihedrals, ArrayList< Double > dihIncement, int activeRot, double step, int h1, int h2, int t1, int t2, ArrayList< Double > clsablConds, ArrayList< ArrayList< Double > > closableConfs, boolean doExhaustiveSearch, boolean writeAllConfs, Logger logger, int rec)
Scan rotatable space looking for conformations that satisfy closability condition.
Static Private Member Functions
static void reportForDebug (String filename, List< Point3d > chain)
Method for reporting a path of atoms (list of points) as SDF file.
Static Private Attributes
static final String NL = DENOPTIMConstants.EOL
Detailed Description
Tool to explore the conformational space of chains of atoms and identify ring closing conformations.
Author
Marco Foscato
Definition at line 49 of file RingClosureFinder.java.
Member Function Documentation
evaluateClosability()
static boolean denoptim.graph.rings.RingClosureFinder.evaluateClosability (List< IAtom > path, ArrayList< Boolean > rotatability, ArrayList< ArrayList< Point3d > > dihRefs, ArrayList< ArrayList< Double > > closableConfs, RingClosureParameters settings) static
Giving a list of points in 3D space (the path) this method evaluates whether it exists at least one conformation of the chain that allows to form ring by connecting the head and the tail of the chain.
Parameters
path the chain of atoms
rotatability list of flags defining which bond is rotatable
Returns
true is a closable conformation is found
Definition at line 65 of file RingClosureFinder.java.
References denoptim.utils.MathUtils.angle(), denoptim.utils.MathUtils.computeDihedralAngle(), denoptim.graph.rings.RingClosureParameters.doExhaustiveConfSrch(), denoptim.graph.rings.RingClosure.getClosabilityConditions(), denoptim.graph.rings.RingClosureParameters.getConfPathExtraTolerance(), denoptim.graph.rings.RingClosureParameters.getLinearityLimit(), denoptim.programs.RunTimeParameters.getLogger(), denoptim.graph.rings.RingClosureParameters.getMaxNumberRotatableBonds(), denoptim.graph.rings.RingClosureParameters.getPathConfSearchStep(), and denoptim.graph.rings.RingClosureFinder.hasClosableRotamer().
Referenced by denoptim.graph.rings.PathClosabilityTools.evaluate3DPathClosability().
hasClosableRotamer()
static boolean denoptim.graph.rings.RingClosureFinder.hasClosableRotamer (List< Point3d > chain, ArrayList< Boolean > rotatability, ArrayList< Double > dihedrals, ArrayList< Double > dihIncement, int activeRot, double step, int h1, int h2, int t1, int t2, ArrayList< Double > clsablConds, ArrayList< ArrayList< Double > > closableConfs, boolean doExhaustiveSearch, boolean writeAllConfs, Logger logger, int rec) static
Scan rotatable space looking for conformations that satisfy closability condition.
Parameters
chain the chain of atoms as a list of points in 3D space
rotatability flags defining which bond is rotatable
dihedrals the current value of the dihedral angles
activeRot index of the currently active (rotating) bond
step the step taken by each sequential rotation of the bond
h1 the index of the first point defining the head vector
h2 the index of the second point defining the head vector
t1 the index of the first point defining the tail vector
t2 the index of the second point defining the tail vector
clsablConds the closability condition vector meant to feed RingClosure
Returns
true when the first closable conformation is found
Definition at line 204 of file RingClosureFinder.java.
References denoptim.graph.rings.RingClosureFinder.hasClosableRotamer(), denoptim.graph.rings.RingClosure.isClosable(), denoptim.graph.rings.RingClosureFinder.NL, and denoptim.graph.rings.RingClosureFinder.reportForDebug().
Referenced by denoptim.graph.rings.RingClosureFinder.evaluateClosability(), and denoptim.graph.rings.RingClosureFinder.hasClosableRotamer().
reportForDebug()
static void denoptim.graph.rings.RingClosureFinder.reportForDebug (String filename, List< Point3d > chain) static private
Method for reporting a path of atoms (list of points) as SDF file.
Definition at line 392 of file RingClosureFinder.java.
References denoptim.io.DenoptimIO.writeSDFFile().
Referenced by denoptim.graph.rings.RingClosureFinder.hasClosableRotamer().
Member Data Documentation
NL
final String denoptim.graph.rings.RingClosureFinder.NL = DENOPTIMConstants.EOL static private
Definition at line 52 of file RingClosureFinder.java.
Referenced by denoptim.graph.rings.RingClosureFinder.hasClosableRotamer().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/RingClosureFinder.java