DENOPTIM: denoptim.graph.Ring Class Reference
denoptim.graph.Ring Class Reference
This class represents the closure of a ring in a spanning tree.
Classes
class DENOPTIMRingSerializer
Public Member Functions
Ring ()
Ring (List< Vertex > vertices)
void addVertex (Vertex v)
Append a DENOPTIMVertex to the list.
Vertex getHeadVertex ()
Vertex getTailVertex ()
Vertex getVertexAtPosition (int i)
int indexOf (Vertex v)
Returns the index of the first occurrence of the specified element in this ring, or -1 if this list does not contain the element.
int getSize ()
BondType getBondType ()
void setBondType (BondType bndType)
Set the bond type (i.e., bond order) of the chord connecting the head and the tail vertices.
boolean contains (Vertex v)
Checks whether a given vertex is part of this ring.
boolean containsID (int vid)
Checks whether a given vertex is part of this ring.
String toString ()
List< Vertex > getVertices ()
void removeVertex (Vertex oldVrtx)
void replaceVertex (Vertex oldVrtx, Vertex newVrtx)
Replaces a vertex that belong to this ring with a new one.
boolean insertVertex (int position, Vertex newLink)
Adds a vertex to the ring, in the given position.
boolean insertVertex (Vertex newLink, Vertex vA, Vertex vB)
Adds a vertex to the ring, and in between two defined vertices.
int getDistance (Vertex v1, Vertex v2) throws DENOPTIMException
Measures how many edges there are between two edges along the sequence of vertices that defined this fundamental ring.
Vertex getCloserToHead (Vertex vA, Vertex vB)
Chooses among the two given vertices the one that is closer to the head vertex.
Vertex getCloserToTail (Vertex vA, Vertex vB)
Chooses among the two given vertices the one that is closer to the tail vertex.
Vertex getCloserTo (Vertex vA, Vertex vB, Vertex vT)
Chooses among the two given vertices the one that is closer to the target vertex.
int getPositionOf (Vertex v)
Private Attributes
List< Vertex > vertices
List of DENOPTIMVertex involved in the ring.
BondType bndTyp = BondType.UNDEFINED
Bond type (i.e., bond order) to be used between head and tail vertices.
Detailed Description
This class represents the closure of a ring in a spanning tree.
Author
Marco Foscato
Definition at line 39 of file Ring.java.
Constructor & Destructor Documentation
Ring() [1/2]
denoptim.graph.Ring.Ring ()
Definition at line 53 of file Ring.java.
References denoptim.graph.Ring.vertices.
Ring() [2/2]
denoptim.graph.Ring.Ring (List< Vertex > vertices)
Definition at line 60 of file Ring.java.
References denoptim.graph.Ring.vertices.
Member Function Documentation
addVertex()
void denoptim.graph.Ring.addVertex (Vertex v)
Append a DENOPTIMVertex to the list.
Definition at line 71 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.ga.GraphOperationsTest.addRings(), denoptim.graph.DGraph.clone(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), and denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets().
contains()
boolean denoptim.graph.Ring.contains (Vertex v)
Checks whether a given vertex is part of this ring.
Parameters
v the candidate DENOPTIMVertex
Returns
true if the given vertex is contained in the list of DENOPTIMVertexs involved in this ring
Definition at line 172 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.Ring.getCloserTo(), denoptim.graph.Ring.getDistance(), and denoptim.graph.Ring.insertVertex().
containsID()
boolean denoptim.graph.Ring.containsID (int vid)
Checks whether a given vertex is part of this ring.
Parameters
vid the ID of the candidate DENOPTIMVertex
Returns
true if the list of DENOPTIMVertexs involved in this ring contains the given vertex ID
Definition at line 187 of file Ring.java.
References denoptim.graph.Ring.vertices.
getBondType()
BondType denoptim.graph.Ring.getBondType ()
Returns
the bond type (i.e., bond order) of the chord connecting the head and the tail vertices
Definition at line 146 of file Ring.java.
References denoptim.graph.Ring.bndTyp.
Referenced by denoptim.graph.Ring.DENOPTIMRingSerializer.serialize().
getCloserTo()
Vertex denoptim.graph.Ring.getCloserTo (Vertex vA, Vertex vB, Vertex vT)
Chooses among the two given vertices the one that is closer to the target vertex.
Parameters
vA first candidate.
vB second candidate.
vT the target vertex.
Returns
the vertex closer to the target vertex.
Definition at line 378 of file Ring.java.
References denoptim.graph.Ring.contains(), and denoptim.graph.Ring.getDistance().
Referenced by denoptim.graph.Ring.getCloserToHead(), denoptim.graph.Ring.getCloserToTail(), and denoptim.graph.RingTest.testGetCloserVertex().
getCloserToHead()
Vertex denoptim.graph.Ring.getCloserToHead (Vertex vA, Vertex vB)
Chooses among the two given vertices the one that is closer to the head vertex.
Parameters
vA first candidate.
vB second candidate
Returns
the vertex closer to the head.
Definition at line 349 of file Ring.java.
References denoptim.graph.Ring.getCloserTo(), and denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.RingTest.testGetCloserVertex().
getCloserToTail()
Vertex denoptim.graph.Ring.getCloserToTail (Vertex vA, Vertex vB)
Chooses among the two given vertices the one that is closer to the tail vertex.
Parameters
vA first candidate.
vB second candidate
Returns
the vertex closer to the tail.
Definition at line 363 of file Ring.java.
References denoptim.graph.Ring.getCloserTo(), and denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.RingTest.testGetCloserVertex().
getDistance()
int denoptim.graph.Ring.getDistance (Vertex v1, Vertex v2) throws DENOPTIMException
Measures how many edges there are between two edges along the sequence of vertices that defined this fundamental ring.
Parameters
v1
v2
Returns
the distance between the vertices (i.e., number of edges).
Exceptions
DENOPTIMException if either vertex is not part of this ring.
Definition at line 325 of file Ring.java.
References denoptim.graph.Ring.contains(), and denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.Ring.getCloserTo(), denoptim.graph.RingTest.testGetDistance(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getHeadVertex()
Vertex denoptim.graph.Ring.getHeadVertex ()
Returns
the first vertex in the list of DENOPTIMVertexs involved in this ring
Definition at line 83 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.DGraph.sameAsRings(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getPositionOf()
int denoptim.graph.Ring.getPositionOf (Vertex v)
Parameters
v the vertex to search for
Returns
the index of that vertex (first instance), or -1 if that vertex is not part of the ring.
Definition at line 415 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.DGraph.removeChainUpToBranching().
getSize()
int denoptim.graph.Ring.getSize ()
Returns
the size of the list of DENOPTIMVertexs involved in this ring
Definition at line 134 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.sameAsRings(), and denoptim.graph.Ring.DENOPTIMRingSerializer.serialize().
getTailVertex()
Vertex denoptim.graph.Ring.getTailVertex ()
Returns
the last vertex in the list of DENOPTIMVertexs involved in this ring
Definition at line 95 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.DGraph.sameAsRings(), and denoptim.graph.DGraphTest.testReplaceSubGraph_inTemplate().
getVertexAtPosition()
Vertex denoptim.graph.Ring.getVertexAtPosition (int i)
Returns
the vertex at the given position in the list of DENOPTIMVertexs involved in this ring
Definition at line 107 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.Vertex.isConnectedToAromaticBridge(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.sameAsRings(), denoptim.graph.Ring.DENOPTIMRingSerializer.serialize(), and denoptim.graph.RingTest.testGetCloserVertex().
getVertices()
List< Vertex > denoptim.graph.Ring.getVertices ()
Definition at line 214 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.DGraph.extractPattern().
indexOf()
int denoptim.graph.Ring.indexOf (Vertex v)
Returns the index of the first occurrence of the specified element in this ring, or -1 if this list does not contain the element.
Definition at line 122 of file Ring.java.
References denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.RingTest.testUndirectedComparison().
insertVertex() [1/2]
boolean denoptim.graph.Ring.insertVertex (int position, Vertex newLink)
Adds a vertex to the ring, in the given position.
Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters
position the position where the vertex will be found after insertion.
newLink vertex to add to this ring.
Returns
true if the vertex is inserted, or false if the operation cannot be performed for any reason, e.g., the vertex is already contained in this ring.
Definition at line 275 of file Ring.java.
References denoptim.graph.Ring.contains(), and denoptim.graph.Ring.vertices.
Referenced by denoptim.graph.RingTest.testUndirectedComparison().
insertVertex() [2/2]
boolean denoptim.graph.Ring.insertVertex (Vertex newLink, Vertex vA, Vertex vB)
Adds a vertex to the ring, and in between two defined vertices.
Parameters
newLink vertex to add to this ring.
vA one of the vertices in between which the new vertex should in inserted.
vB one of the vertices in between which the new vertex should in inserted.
Returns
true if the vertex is inserted, or false if the operation cannot be performed for any reason, e.g., the vertex is already contained in this ring, or either of the two reference vertices are not themselves contained here.
Definition at line 298 of file Ring.java.
References denoptim.graph.Ring.contains(), and denoptim.graph.Ring.vertices.
removeVertex()
void denoptim.graph.Ring.removeVertex (Vertex oldVrtx)
Definition at line 242 of file Ring.java.
References denoptim.graph.Ring.vertices.
replaceVertex()
void denoptim.graph.Ring.replaceVertex (Vertex oldVrtx, Vertex newVrtx)
Replaces a vertex that belong to this ring with a new one.
Parameters
oldVrtx the vertex to be replaced.
newVrtx the vertex the replace the old one with.
Definition at line 255 of file Ring.java.
References denoptim.graph.Ring.vertices.
setBondType()
void denoptim.graph.Ring.setBondType (BondType bndType)
Set the bond type (i.e., bond order) of the chord connecting the head and the tail vertices.
Definition at line 158 of file Ring.java.
Referenced by denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.clone(), denoptim.graph.rings.CyclicGraphHandler.combineCompatPathSubGraphs(), denoptim.graph.DGraph.DENOPTIMGraphDeserializer.deserialize(), denoptim.graph.DGraph.makeAllGraphsWithDifferentRingSets(), and denoptim.graph.rings.RandomCombOfRingsIterator.next().
toString()
String denoptim.graph.Ring.toString ()
Returns
the string representation of this ring
Definition at line 208 of file Ring.java.
References denoptim.graph.Ring.vertices.
Member Data Documentation
bndTyp
BondType denoptim.graph.Ring.bndTyp = BondType.UNDEFINED private
Bond type (i.e., bond order) to be used between head and tail vertices.
Definition at line 49 of file Ring.java.
Referenced by denoptim.graph.Ring.getBondType().
vertices
List<Vertex> denoptim.graph.Ring.vertices private
List of DENOPTIMVertex involved in the ring.
Definition at line 44 of file Ring.java.
Referenced by denoptim.graph.Ring.addVertex(), denoptim.graph.Ring.contains(), denoptim.graph.Ring.containsID(), denoptim.graph.Ring.getCloserToHead(), denoptim.graph.Ring.getCloserToTail(), denoptim.graph.Ring.getDistance(), denoptim.graph.Ring.getHeadVertex(), denoptim.graph.Ring.getPositionOf(), denoptim.graph.Ring.getSize(), denoptim.graph.Ring.getTailVertex(), denoptim.graph.Ring.getVertexAtPosition(), denoptim.graph.Ring.getVertices(), denoptim.graph.Ring.indexOf(), denoptim.graph.Ring.insertVertex(), denoptim.graph.Ring.removeVertex(), denoptim.graph.Ring.replaceVertex(), denoptim.graph.Ring.Ring(), and denoptim.graph.Ring.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/Ring.java