DENOPTIM: denoptim.gui.IVertexAPSelection Interface Reference
denoptim.gui.IVertexAPSelection Interface Reference
Interface for all vertex viewers that intend to allow selection of attachment points.
Public Member Functions
ArrayList< Integer > getSelectedAPIDs ()
Map< Integer, AttachmentPoint > getMapOfAPsInTable ()
DefaultTableModel getAPTableModel ()
Public Attributes
final String APDATACHANGEEVENT = "APDATA"
Detailed Description
Interface for all vertex viewers that intend to allow selection of attachment points.
Definition at line 32 of file IVertexAPSelection.java.
Member Function Documentation
getAPTableModel()
DefaultTableModel denoptim.gui.IVertexAPSelection.getAPTableModel ()
Implemented in denoptim.gui.FragmentViewPanel, denoptim.gui.VertexAsGraphViewPanel, and denoptim.gui.VertexAsTwoDimStructureViewPanel.
Referenced by denoptim.gui.VertexViewPanel.getAPTableModel().
getMapOfAPsInTable()
Map< Integer, AttachmentPoint > denoptim.gui.IVertexAPSelection.getMapOfAPsInTable ()
Implemented in denoptim.gui.FragmentViewPanel, denoptim.gui.VertexAsGraphViewPanel, and denoptim.gui.VertexAsTwoDimStructureViewPanel.
Referenced by denoptim.gui.VertexViewPanel.getActiveMapAPs().
getSelectedAPIDs()
ArrayList< Integer > denoptim.gui.IVertexAPSelection.getSelectedAPIDs ()
Implemented in denoptim.gui.FragmentViewPanel, denoptim.gui.VertexAsGraphViewPanel, and denoptim.gui.VertexAsTwoDimStructureViewPanel.
Referenced by denoptim.gui.VertexViewPanel.getSelectedAPIDs().
Member Data Documentation
APDATACHANGEEVENT
final String denoptim.gui.IVertexAPSelection.APDATACHANGEEVENT = "APDATA"
Definition at line 34 of file IVertexAPSelection.java.
Referenced by denoptim.gui.GUIVertexInspector.initialize(), denoptim.gui.VertexViewPanel.initialize(), denoptim.gui.FragmentViewPanel.PausableTableModelListener.tableChanged(), denoptim.gui.VertexAsGraphViewPanel.PausableTableModelListener.tableChanged(), and denoptim.gui.VertexAsTwoDimStructureViewPanel.PausableTableModelListener.tableChanged().
The documentation for this interface was generated from the following file:
/github/workspace/src/main/java/denoptim/gui/IVertexAPSelection.java