{% set version = "3.1.3" %}
{% set openjdk_version = "11.0.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  path: ..

build:
  number: 12

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only
  license_file: LICENSE.txt
  summary: 'Package for de novo design and virtual screening of functional molecules of any kind.'
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
