/*
 *   DENOPTIM
 *   Copyright (C) 2019 Vishwesh Venkatraman <vishwesh.venkatraman@ntnu.no>
 * 
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published
 *   by the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package molecule;

import java.io.Serializable;

/**
 * This class represents the edge between 2 fragments (vertices)
 * @author Vishwesh Venkatraman
 */
public class DENOPTIMEdge implements Serializable 
{
    // these ids refer to the vertex id generated by denoptim
    /*
     * // the vertex id of the source fragment
     */
    private int srcVertex; 
    /*
     * // the vertex id of the destination fragment
     */
    private int trgVertex; 
    
    /*
     * the index of the attachment point in the list of DAPs associated
     * with the source fragment
     */
    private int srcDAP;
    
    /*
     * the index of the attachment point in the list of DAPs associated
     * with the target fragment
     */
    private int trgDAP;

    /*
     * The bond type associated with the connection between the fragments
     */

    private int bondType;
    
    /*
     * The class associated with the source AP
     */
    private String srcRcn;
    
    /*
     * The class associated with the target AP
     */
    
    private String trgRcn;
    
//------------------------------------------------------------------------------
    
    public DENOPTIMEdge(int m_src, int m_trg, int m_srcDAP, int m_trgDAP, 
                                                                    int m_btype)
    {
        srcVertex = m_src;
        trgVertex = m_trg;
        srcDAP = m_srcDAP;
        trgDAP = m_trgDAP;
        bondType = m_btype;  
        trgRcn = "";
        srcRcn = "";
    }
    
//------------------------------------------------------------------------------

    public void setSourceVertex(int m_src)
    {
        srcVertex = m_src;
    }
    
//------------------------------------------------------------------------------

    public void setSourceDAP(int m_srcDAP)
    {
        srcDAP = m_srcDAP;
    }
    
//------------------------------------------------------------------------------

    public void setTargetDAP(int m_trgDAP)
    {
        trgDAP = m_trgDAP;
    }        

//------------------------------------------------------------------------------

    public void setTargetVertex(int m_trg)
    {
        trgVertex = m_trg;
    }

//------------------------------------------------------------------------------

    public void setBondType(int m_btype)
    {
        bondType = m_btype; 
    }
    
//------------------------------------------------------------------------------

    public int getSourceVertex()
    {
        return srcVertex;
    }
    
//------------------------------------------------------------------------------

    public int getSourceDAP()
    {
        return srcDAP;
    }
    
//------------------------------------------------------------------------------

    public int getTargetDAP()
    {
        return trgDAP;
    }        

//------------------------------------------------------------------------------

    public int getTargetVertex()
    {
        return trgVertex;
    }
    
//------------------------------------------------------------------------------
    
    public String getSourceReaction()
    {
        return srcRcn;
    }
    
//------------------------------------------------------------------------------
    
    public String getTargetReaction()
    {
        return trgRcn;
    }    
    
//------------------------------------------------------------------------------
    
    public void setSourceReaction(String m_rcn)
    {
        srcRcn = m_rcn;
    }
    
//------------------------------------------------------------------------------
    
    public void setTargetReaction(String m_rcn)
    {
        trgRcn = m_rcn;
    }    
    

//------------------------------------------------------------------------------

    public int getBondType()
    {
        return bondType;
    }

//------------------------------------------------------------------------------

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder(64);
        sb.append(srcVertex).append("_").append(srcDAP).append("_").
                append(trgVertex).append("_").append(trgDAP).append("_").
                append(bondType);
        if (srcRcn.length() > 0 && trgRcn.length() > 0)
            sb.append("_").append(srcRcn).append("_").append(trgRcn);

        return sb.toString();
    }

//------------------------------------------------------------------------------    
}
