{% set openjdk_version = "11.0.*" %}

package:
  name: denoptim
  version: {{ environ.get('DENOPTIM_VERSION', '') }}

source:
  path: ..

build:
  noarch: generic
  number: 2

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
    - python
    - python-build
    - setuptools
  run:
    - openjdk =={{ openjdk_version }}
    - python
    - py4j

#test:
#  commands:
#    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only
  license_file: ../COPYING
  summary: 'Package for de novo design and virtual screening of functional molecules of any kind.'
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
