name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'devel_docs'

jobs:
  documentation:
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./doc/doxygen

    steps:
      - name: Where
        run: |
          pwd
          ls
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          working-directory: ${{env.working-directory}}
          doxyfile-path: 'doc/doxygen'
