name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'master'

jobs:
  documentation:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./doc
           
      - name: Check for broken links in Markdown
        run: |
           if grep -q "\.md:" ./doc/doxygen_warn.log; then
             grep "\.md:" ./doc/doxygen_warn.log
             exit 1
           fi

      # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html/
          force_orphan: true
