name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'devel_docs'

jobs:
  documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          working-directory: 'submodule/'
          doxyfile-path: 'doc/doxygen'
