name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'devel_docs'

jobs:
  documentation:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@devel_docs
      - name: Where
        run: |
          pwd
          ls
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./doc/doxygen
