name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'devel_docs'

jobs:
  documentation:
    runs-on: [ubuntu-latest]

    steps:
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          working-directory: '../../../doc'
          doxyfile-path: './Doxyfile'
