name: 'Doxygen Documentation'

on:
  push:
    branches:
      - 'devel_docs'

jobs:
  documentation:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: devel_docs

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./doc/doxygen

      - name: Check broken links
         run:! grep -q "\.md:" doxygen_warn.log

      # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/doxygen/html/
          force_orphan: true
