name: 'TestCommand'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Get version identifier
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
        echo ${GITHUB_REF#refs/tags/v}


